using System.Collections.Generic;
using System.Text.Json;

namespace LauncherV2.Plugins.DiabloII;

/// <summary>
/// Derives the FULL active location universe for a standalone (no-AP) D2 run from
/// the launcher's own settings + the bundled location table — the same thing an
/// Archipelago server delivers via the Connected packet's <c>missing_locations</c>.
///
/// Why the launcher can do this without asking the game: in standalone the mod runs
/// <c>g_apMode = FALSE</c> (it reads d2arch.ini <c>[settings]</c>, never the AP
/// <c>ap_settings</c> path that sets AP mode). With AP mode off, the mod's
/// <c>IsDifficultyActive()</c> returns TRUE for every difficulty, so the active
/// universe is simply "every location an enabled category contributes, across ALL
/// three difficulties" — fully determined by the [settings] the launcher just wrote.
///
/// Each category maps 1:1 to a <c>location_name_groups</c> entry in d2_locations.json
/// (generated by _dump_locations.py from the apworld's locations.py) and to a single
/// settings toggle below. Collection is special: it's only in the pool under
/// Goal=Collection, and then only for the individually ticked set/rune/gem/special
/// items (resolved by AP-id arithmetic, matching locations.py's 50000-block layout).
/// </summary>
public static class D2LocationUniverse
{
    /// Collection AP-id layout (locations.py COLL_LOC_BASE = 50000):
    ///   50000-50031 sets (32) · 50032-50064 runes (33) ·
    ///   50065-50099 gems (35, one CollectGems flag) · 50100-50109 specials (10)
    private const int CollBase = 50000;

    /// All active location ids for these settings. Pass the parsed d2_locations.json
    /// (location_name_to_id + location_name_groups). Returns ids only — the tracker
    /// resolves names + categories from the same data package.
    public static long[] ComputeActiveIds(D2RandomizerSettings s, JsonElement dataPackage)
    {
        var nameToId = new Dictionary<string, long>();
        if (dataPackage.TryGetProperty("location_name_to_id", out var locs))
            foreach (var kv in locs.EnumerateObject())
                if (kv.Value.TryGetInt64(out var id))
                    nameToId[kv.Name] = id;

        var result = new List<long>();
        if (!dataPackage.TryGetProperty("location_name_groups", out var groups))
            return result.ToArray();

        foreach (var grp in groups.EnumerateObject())
        {
            if (!IsGroupEnabled(grp.Name, s)) continue;
            bool isCollection = grp.Name == "Collection";

            foreach (var nameEl in grp.Value.EnumerateArray())
            {
                string? n = nameEl.GetString();
                if (n == null || !nameToId.TryGetValue(n, out long id)) continue;
                if (isCollection && !IsCollectionItemEnabled(id, s)) continue;
                result.Add(id);
            }
        }
        return result.ToArray();
    }

    /// Maps a category card to the [settings] toggle that puts it in the pool.
    /// Story quests are always required (the mod forces g_apQuestStory = TRUE).
    private static bool IsGroupEnabled(string group, D2RandomizerSettings s) => group switch
    {
        "Story Quests"      => true,
        "Hunt"              => s.QuestHunting,
        "Clear Zones"       => s.QuestKillZones,
        "Exploration"       => s.QuestExploration,
        "Waypoints"         => s.QuestWaypoints,
        "Level Milestones"  => s.QuestLevelMilestones,
        "Zone Gates"        => s.ZoneLocking,
        "Shrines"           => s.CheckShrines,
        "Urns"              => s.CheckUrns,
        "Barrels"           => s.CheckBarrels,
        "Chests"            => s.CheckChests,
        "Set Pickups"       => s.CheckSetPickups,
        "Gold Milestones"   => s.CheckGoldMilestones,
        "Cow Level"         => s.CheckCowLevel,
        "Mercenary"         => s.CheckMercMilestones,
        "Hellforge & Runes" => s.CheckHellforgeRunes,
        "NPC Dialogue"      => s.CheckNpcDialogue,
        "Runewords"         => s.CheckRunewordCrafting,
        "Cube Recipes"      => s.CheckCubeRecipes,
        "Collection"        => s.Goal == 3,   // Goal 3 = Collection
        _                   => false,
    };

    /// Within the Collection group, only the ticked items are in the pool.
    private static bool IsCollectionItemEnabled(long id, D2RandomizerSettings s)
    {
        int off = (int)(id - CollBase);
        if (off < 0)    return false;
        if (off < 32)   return At(s.CollectSets,     off);        // sets   50000-50031
        if (off < 65)   return At(s.CollectRunes,    off - 32);   // runes  50032-50064
        if (off < 100)  return s.CollectGems;                     // gems   50065-50099
        if (off < 110)  return At(s.CollectSpecials, off - 100);  // specials 50100-50109
        return false;
    }

    private static bool At(bool[] arr, int i) => i >= 0 && i < arr.Length && arr[i];
}
