using System;
using System.Collections.Generic;
using System.IO;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
using LauncherV2.Core;

namespace LauncherV2.Plugins.Emulated.Games;

// ═══════════════════════════════════════════════════════════════════════════════
// DonkeyKongCountry3Plugin — Archipelago integration for Donkey Kong Country 3:
// Dixie Kong's Double Trouble! (SNES), on the proven BizHawk Lua-pipe bridge.
//
// COMMUNITY WORLD. The apworld is PoryGone's "Donkey Kong Country 3"
// (TheLX5/Archipelago, branch `dktoluca`, world_version 1.1.0) — NOT in AP-main.
// game string "Donkey Kong Country 3", patch_suffix ".apdkc3", items_handling
// 0b111 (FULL remote). The patch's declared base ROM is the US 1.0 dump (MD5
// 120abf304f0c40fe059f6a192ed4f947 = USHASH in worlds/dkc3/Rom.py).
// SOURCE: https://github.com/TheLX5/Archipelago  (branch `dktoluca`, worlds/dkc3)
//
// NOTE ON THE CODENAME: on TheLX5/Archipelago the DKC3 work lives on the
// `dktoluca` branch and ships as `dktoluca.apworld` releases ("Donkey Kong
// Toluca" is lx5's umbrella codename). Inside that branch, worlds/dkc3 is the
// PoryGone "Donkey Kong Country 3" world this plugin targets (game string and
// patch_suffix below are taken verbatim from worlds/dkc3/Client.py).
//
// STATUS: location DETECTION + goal are REAL and SOURCE-DERIVED (the 220-location
// table in "Donkey Kong Country 3.lua" was GENERATED by PARSING worlds/dkc3
// Rom.py location_rom_data — each location is {WRAM addr, bit, optional invert} —
// joined with Locations.py/__init__.py for the two Victory goal carriers; the
// single-flag-block bit math, the "D3" LoROM-header check, and the save-loaded
// gate are mirrored from Client.py game_watcher; mock-verified through MoonSharp
// against synthetic WRAM/CARTROM). items_handling = 0b111 (FULL remote): the dkc3
// client owns ALL item delivery via an intricate, heavily-state-gated set of WRAM
// writes (a recv-index handshake, per-item count increments, Bear/Swanky/Boomer
// coin-display pokes, the Patch & Skis progressive-boat upgrade state machine, and
// the Victory CLIENT_GOAL trigger). That path is deferred ("Donkey Kong Country
// 3.lua" receive_item is a no-op) until it can be confirmed in-emulator, rather
// than shipped unverified — checks + goal are fully functional regardless.
//
// AP PATCH (.apdkc3 → .sfc): a standard APDeltaPatch container (bsdiff4 over the
// vanilla ROM), applied via the shared SnesApPatchHelper (resolve the seed's
// patch, validate the base ROM MD5, run apply_appatch.py on a library COPY — the
// original is never modified). Base ROM: the user's own DKC3 cartridge dump (4 MB,
// headerless .sfc), identified by CONTENT (size + MD5) — never by filename (§11).
// ═══════════════════════════════════════════════════════════════════════════════

public sealed class DonkeyKongCountry3Plugin : EmulatorPlugin
{
    public DonkeyKongCountry3Plugin() => LoadSettings();

    // ── Identity ──────────────────────────────────────────────────────────────

    public override string GameId      => "donkey_kong_country_3";
    public override string DisplayName => "Donkey Kong Country 3";
    public override string Subtitle    => "SNES · Emulated";
    public override string ApWorldName => "Donkey Kong Country 3";

    public override string Description =>
        "Donkey Kong Country 3: Dixie Kong's Double Trouble! is RARE's 1996 SNES " +
        "platformer. Donkey and Diddy have vanished, so Dixie Kong and her baby " +
        "cousin Kiddy set out across the Northern Kremisphere to find them. In the " +
        "Archipelago randomizer, every level flag, bonus coin, DK coin, KONG-letter " +
        "set, boss, and Banana Bird cave across the map joins the multiworld pool. " +
        "Scuttle the Knautilus and defeat Baron K. Roolenstein — or hunt down the " +
        "Banana Birds and rescue their mother — to complete your goal. Bring your " +
        "own Donkey Kong Country 3 (USA) SNES ROM.";

    // ── Visual identity ───────────────────────────────────────────────────────

    public override string ThemeAccentColor => "#3FA34D";   // Dixie's jungle green

    // ── Emulator specifics ────────────────────────────────────────────────────

    protected override string RomSystem     => "SNES";
    protected override string LuaScriptName => "bizhawk_ap_connector.lua";
    protected override string LuaModuleName => "Donkey Kong Country 3";

    // §14: the SNES emulators this world is played on. BizHawk is verified; snes9x
    // is the headline alternative the AP SNES ecosystem runs on, with Mesen as a
    // third option (both shown per their bridge state in the dropdown).
    protected override IReadOnlyList<string> SupportedEmulatorIds =>
        new[] { "bizhawk", "snes9x", "mesen" };

    private const string PatchExt  = ".apdkc3";
    private const string ResultExt = ".sfc";

    /// The vanilla DKC3 cartridge dump the randomizer is built for, identified by
    /// CONTENT (4 MB + MD5) — never by filename. The patch container declares the
    /// US 1.0 dump (USHASH in worlds/dkc3/Rom.py) as its base; the patch
    /// container's own base_checksum is independently re-checked by
    /// apply_appatch.py before patching, so this list only drives the launcher's
    /// "wrong version" hint. The canonical dump is the headerless .sfc
    /// (Utils.read_snes_rom strips any 512-byte copier header before hashing).
    protected override IReadOnlyList<RomIdentity> AcceptableBaseRoms
        => new[]
        {
            new RomIdentity(4 * 1024 * 1024,                     // 4,194,304 bytes
                            "120abf304f0c40fe059f6a192ed4f947",
                            "Donkey Kong Country 3 - Dixie Kong's Double Trouble! (USA) v1.0"),
        };

    /// "Donkey Kong Country 3.lua" mirrors the official SNIClient game_watcher: a
    /// single 0x81-byte progress-flag scan → AP location ids (per-location bit +
    /// optional invert), gated on the "D3" LoROM header and a loaded save file,
    /// and a goal read of the two Victory carrier bits (kastle_kaos / banana_bird_
    /// mother). All addresses are SOURCE-DERIVED from the apworld client and
    /// mock-verified; needs a real playthrough to confirm live.
    public override bool ChecksImplemented => true;

    /// The Donkey Kong Country 3 datapackage checksum is announced by the server in
    /// RoomInfo, not embedded as a constant in the apworld; left null. The
    /// launcher's "apworld updated" warning is simply not raised for this game
    /// until a live RoomInfo checksum is captured and pinned here.
    public string? BuiltAgainstDataPackageChecksum => null;

    // ── AP patch settings ─────────────────────────────────────────────────────

    public string? ApPatchPath { get; private set; }

    protected override void OnSavingSettings(IDictionary<string, object?> bag)
        => bag["ap_patch_path"] = ApPatchPath;

    protected override void OnLoadingSettings(JsonElement root)
    {
        if (root.TryGetProperty("ap_patch_path", out var el))
            ApPatchPath = el.GetString();
    }

    private string? ResolvePatchPath(out string how)
        => SnesApPatchHelper.ResolvePatch(
            PatchExt, ApPatchPath, GetSeedName?.Invoke(), CurrentSlotName, out how);

    public void SetExplicitPatch(string path) { ApPatchPath = path; SaveSettings(); }

    /// ROM safety net: when a patch is known, demand exactly its base ROM
    /// (base_checksum) so the launcher can ask the player by fingerprint instead
    /// of silently patching the wrong dump.
    public override RomRequirement? GetUnmetRomRequirement()
    {
        string? wantMd5 = null;
        var patch = ResolvePatchPath(out _);
        if (patch != null) wantMd5 = SnesApPatchHelper.ReadManifestField(patch, "base_checksum");

        bool haveRom = RomPath != null && File.Exists(RomPath);

        if (wantMd5 == null)
            return haveRom ? null
                 : new RomRequirement("Donkey Kong Country 3", "SNES",
                       "Donkey Kong Country 3 (USA)",
                       RequiredMd5: null, WrongVersionPresent: false, BuildRomFilter());

        if (haveRom && ComputeMd5(RomPath!).Equals(wantMd5, StringComparison.OrdinalIgnoreCase))
            return null;

        return new RomRequirement(
            "Donkey Kong Country 3", "SNES",
            "Donkey Kong Country 3 (USA) — the original vanilla cartridge dump",
            wantMd5, WrongVersionPresent: haveRom, BuildRomFilter());
    }

    private void RegisterSeed(string outRom, string patch)
    {
        try
        {
            SeedLibraryStore.Instance.Register(new SeedEntry
            {
                GameId         = GameId,
                PatchedRomPath = outRom,
                PatchPath      = patch,
                SeedName       = SnesApPatchHelper.ParseSeedFromPatch(patch),
                SlotName       = CurrentSlotName ?? "",
                CreatedUtc     = DateTimeOffset.UtcNow,
            });
        }
        catch { /* registry is non-essential to launching */ }
    }

    // ── Session ROM: apply the .apdkc3 to a library copy ──────────────────────

    protected override async Task<string?> PrepareSessionRomAsync(
        ApSession session, CancellationToken ct)
    {
        string? patch = ResolvePatchPath(out string how);
        if (patch == null)
        {
            SessionRomNote =
                "[Donkey Kong Country 3] No AP patch (.apdkc3) found — launching the " +
                "vanilla ROM. Checks and ITEM DELIVERY CANNOT WORK on a vanilla ROM: " +
                "generate the multiworld, then pick the patch in Settings → Donkey " +
                "Kong Country 3 (or drop it under " + SnesApPatchHelper.ApOutputDirectory + ").";
            return null;
        }

        if (RomPath == null || !File.Exists(RomPath))
        {
            SessionRomNote =
                "[Donkey Kong Country 3] No base ROM set — import your vanilla US " +
                "cartridge dump in Settings, then relaunch.";
            return null;
        }

        var result = await SnesApPatchHelper.ApplyAsync(
            "Donkey Kong Country 3", patch, how, RomPath!, RomLibraryDirectory, ResultExt, ct);
        SessionRomNote = result.Note;
        if (result.OutRom != null) RegisterSeed(result.OutRom, patch);
        return result.OutRom;
    }

    // ── Settings panel: base panel + AP patch section ─────────────────────────

    public override UIElement? CreateSettingsPanel()
    {
        var basePanel = base.CreateSettingsPanel();
        if (basePanel is not StackPanel panel) return basePanel;

        var muted = new SolidColorBrush(Color.FromRgb(0x72, 0x7A, 0x99));
        var fg    = new SolidColorBrush(Color.FromRgb(0xCC, 0xD0, 0xE0));

        panel.Children.Add(new TextBlock
        {
            Text = "ARCHIPELAGO PATCH", FontSize = 10, FontWeight = FontWeights.SemiBold,
            Foreground = muted, Margin = new Thickness(0, 20, 0, 8),
        });
        panel.Children.Add(new TextBlock
        {
            Text = "The multiworld generator produces a .apdkc3 patch for your slot. " +
                   "The launcher applies it to a COPY of your ROM at launch (your file " +
                   "is never modified). Leave empty to auto-use the newest patch from " +
                   "the Archipelago output folder.",
            FontSize = 11, Foreground = muted, TextWrapping = TextWrapping.Wrap,
            Margin = new Thickness(0, 0, 0, 8),
        });

        var patchRow = new DockPanel { Margin = new Thickness(0, 0, 0, 4) };
        var patchBox = new TextBox
        {
            Text = ApPatchPath ?? "", Margin = new Thickness(0, 0, 8, 0),
            IsReadOnly = true, FontSize = 12,
            Background  = new SolidColorBrush(Color.FromRgb(0x0C, 0x10, 0x20)),
            Foreground  = fg,
            BorderBrush = new SolidColorBrush(Color.FromRgb(0x1E, 0x22, 0x33)),
        };
        var clearBtn = new Button
        {
            Content = "Auto", Width = 50, Margin = new Thickness(0, 0, 8, 0),
            Padding = new Thickness(0, 6, 0, 6),
            Background  = new SolidColorBrush(Color.FromRgb(0x1A, 0x1E, 0x30)),
            Foreground  = fg,
            BorderBrush = new SolidColorBrush(Color.FromRgb(0x2A, 0x30, 0x50)),
            ToolTip = "Clear the explicit pick — auto-detect the newest generated patch.",
        };
        var pickBtn = new Button
        {
            Content = "Select AP patch...", Width = 130, Padding = new Thickness(0, 6, 0, 6),
            Background  = new SolidColorBrush(Color.FromRgb(0x1A, 0x1E, 0x30)),
            Foreground  = fg,
            BorderBrush = new SolidColorBrush(Color.FromRgb(0x2A, 0x30, 0x50)),
        };

        var autoNote = new TextBlock
        {
            FontSize = 10, Foreground = muted, TextWrapping = TextWrapping.Wrap,
            Margin = new Thickness(0, 4, 0, 0),
        };
        void RefreshAutoNote()
        {
            string? auto = ResolvePatchPath(out string how);
            autoNote.Text = ApPatchPath != null
                ? "Explicit patch selected — auto-detection off."
                : auto != null
                    ? $"Auto-detected ({how}): {auto}"
                    : $"No .apdkc3 found under {SnesApPatchHelper.ApOutputDirectory} yet.";
        }
        RefreshAutoNote();

        pickBtn.Click += (_, _) =>
        {
            var dlg = new Microsoft.Win32.OpenFileDialog
            {
                Title  = "Select Archipelago patch for Donkey Kong Country 3",
                Filter = "AP DKC3 patch (*.apdkc3)|*.apdkc3|All files (*.*)|*.*",
            };
            if (Directory.Exists(SnesApPatchHelper.ApOutputDirectory))
                dlg.InitialDirectory = SnesApPatchHelper.ApOutputDirectory;
            if (dlg.ShowDialog() != true) return;
            ApPatchPath   = dlg.FileName;
            patchBox.Text = dlg.FileName;
            SaveSettings();
            RefreshAutoNote();
        };
        clearBtn.Click += (_, _) =>
        {
            ApPatchPath   = null;
            patchBox.Text = "";
            SaveSettings();
            RefreshAutoNote();
        };

        DockPanel.SetDock(pickBtn,  Dock.Right);
        DockPanel.SetDock(clearBtn, Dock.Right);
        patchRow.Children.Add(pickBtn);
        patchRow.Children.Add(clearBtn);
        patchRow.Children.Add(patchBox);
        panel.Children.Add(patchRow);
        panel.Children.Add(autoNote);

        return panel;
    }
}
