using System;
using System.Collections.Generic;
using System.IO;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
using LauncherV2.Core;

namespace LauncherV2.Plugins.Emulated.Games;

// ═══════════════════════════════════════════════════════════════════════════════
// DonkeyKongCountry2Plugin — Archipelago integration for Donkey Kong Country 2:
// Diddy's Kong Quest (SNES), on the proven BizHawk Lua-pipe bridge.
//
// COMMUNITY WORLD. The apworld is lx5's "Donkey Kong Country 2" (TheLX5/Archipelago,
// branch `dkc2`, world_version 3.1.2) — NOT in AP-main. game string "Donkey Kong
// Country 2", patch_suffix ".apdkc2", items_handling 0b111 (FULL remote). The
// patch's declared base ROM is the US REV1 dump (MD5
// d323e6bb4ccc85fd7b416f58350bc1a2 = HASH_US_REV_1); the vanilla US 1.0 dump
// hashes 98458530599b9dff8a7414a7f20b777a (HASH_US).
// SOURCE: https://github.com/TheLX5/Archipelago  (branch `dkc2`, worlds/dkc2)
//
// STATUS: location DETECTION + goal are REAL and SOURCE-DERIVED (the 581-location
// table in "Donkey Kong Country 2.lua" was GENERATED by JOINING worlds/dkc2
// Locations.all_locations (name → AP id) with Levels.location_id_to_level_id
// (name → [loc_type, level_num, data]); the per-type bit math, the per-family
// settings gates, the in-map / brightness gates, the "DKC2" header check, and the
// runtime 0xDEAD validation flag are all mirrored from Client.py game_watcher;
// mock-verified through MoonSharp against synthetic WRAM/SRAM/CARTROM).
// items_handling = 0b111 (FULL remote): the dkc2 client owns ALL item delivery via
// an intricate, heavily-state-gated set of SRAM/WRAM writes (kong-unlock bitmask,
// ability/animal/object unlock bytes, currency increments, trap counters, an SFX
// strobe, a recv-index handshake, plus EnergyLink DK barrels / TrapLink / DeathLink
// / SharedDamage). That path is deferred ("Donkey Kong Country 2.lua" receive_item
// is a no-op) until it can be confirmed in-emulator, rather than shipped unverified
// — checks + goal are fully functional regardless.
//
// AP PATCH (.apdkc2 → .sfc): a standard APProcedurePatch container (apply_tokens +
// apply_bsdiff4 + shuffle/trivia/hint/settings passes), applied via the shared
// SnesApPatchHelper (resolve the seed's patch, validate the base ROM MD5, run
// apply_appatch.py on a library COPY — the original is never modified). Base ROM:
// the user's own DKC2 cartridge dump (4 MB, headerless .sfc), identified by
// CONTENT (size + MD5) — never by filename (§11).
// ═══════════════════════════════════════════════════════════════════════════════

public sealed class DonkeyKongCountry2Plugin : EmulatorPlugin
{
    public DonkeyKongCountry2Plugin() => LoadSettings();

    // ── Identity ──────────────────────────────────────────────────────────────

    public override string GameId      => "donkey_kong_country_2";
    public override string DisplayName => "Donkey Kong Country 2";
    public override string Subtitle    => "SNES · Emulated";
    public override string ApWorldName => "Donkey Kong Country 2";

    public override string Description =>
        "Donkey Kong Country 2: Diddy's Kong Quest is RARE's 1995 SNES platformer. " +
        "Kaptain K. Rool has kidnapped Donkey Kong, and Diddy and Dixie give chase " +
        "across Crocodile Isle. In the Archipelago randomizer, every level clear, " +
        "bonus room, KONG letter, DK coin, banana coin, banana bunch, balloon, and " +
        "Swanky quiz across the isle joins the multiworld pool. Collect enough to " +
        "storm the Flying Krock and finish your goal. Bring your own Donkey Kong " +
        "Country 2 (USA) SNES ROM.";

    // ── Visual identity ───────────────────────────────────────────────────────

    public override string ThemeAccentColor => "#B23A2E";   // Diddy's cap / pirate red

    // ── Emulator specifics ────────────────────────────────────────────────────

    protected override string RomSystem     => "SNES";
    protected override string LuaScriptName => "bizhawk_ap_connector.lua";
    protected override string LuaModuleName => "Donkey Kong Country 2";

    // §14: the SNES emulators this world is played on. BizHawk is verified; snes9x
    // is the headline alternative the AP SNES ecosystem runs on, with Mesen as a
    // third option (both shown per their bridge state in the dropdown).
    protected override IReadOnlyList<string> SupportedEmulatorIds =>
        new[] { "bizhawk", "snes9x", "mesen" };

    private const string PatchExt  = ".apdkc2";
    private const string ResultExt = ".sfc";

    /// The vanilla DKC2 cartridge dump the randomizer is built for, identified by
    /// CONTENT (4 MB + MD5) — never by filename. The patch container declares the
    /// US REV1 dump (HASH_US_REV_1 in worlds/dkc2/Rom.py) as its base; we accept
    /// both the REV1 and the original US 1.0 (HASH_US) fingerprints, since the
    /// patch container's own base_checksum is independently re-checked by
    /// apply_appatch.py before patching — this list only drives the launcher's
    /// "wrong version" hint. The canonical dump is the headerless .sfc
    /// (Utils.read_snes_rom strips any 512-byte copier header before hashing).
    protected override IReadOnlyList<RomIdentity> AcceptableBaseRoms
        => new[]
        {
            new RomIdentity(4 * 1024 * 1024,                     // 4,194,304 bytes
                            "d323e6bb4ccc85fd7b416f58350bc1a2",
                            "Donkey Kong Country 2 (USA) (Rev 1)"),
            new RomIdentity(4 * 1024 * 1024,                     // 4,194,304 bytes
                            "98458530599b9dff8a7414a7f20b777a",
                            "Donkey Kong Country 2 (USA) v1.0"),
        };

    /// "Donkey Kong Country 2.lua" mirrors the official SNIClient game_watcher: a
    /// per-type level/sanity flag scan → AP location ids, the per-family settings
    /// gates, the in-map + full-brightness gates, the "DKC2" header + 0xDEAD
    /// runtime validation, and the composite settings[0x01] goal (bonus 0x61 +
    /// DK-coin 0x6B). All addresses are SOURCE-DERIVED from the apworld client and
    /// mock-verified; needs a real playthrough to confirm live.
    public override bool ChecksImplemented => true;

    /// The Donkey Kong Country 2 datapackage checksum is announced by the server in
    /// RoomInfo, not embedded as a constant in the apworld; left null. The
    /// launcher's "apworld updated" warning is simply not raised for this game
    /// until a live RoomInfo checksum is captured and pinned here.
    public string? BuiltAgainstDataPackageChecksum => null;

    // ── AP patch settings ─────────────────────────────────────────────────────

    public string? ApPatchPath { get; private set; }

    protected override void OnSavingSettings(IDictionary<string, object?> bag)
        => bag["ap_patch_path"] = ApPatchPath;

    protected override void OnLoadingSettings(JsonElement root)
    {
        if (root.TryGetProperty("ap_patch_path", out var el))
            ApPatchPath = el.GetString();
    }

    private string? ResolvePatchPath(out string how)
        => SnesApPatchHelper.ResolvePatch(
            PatchExt, ApPatchPath, GetSeedName?.Invoke(), CurrentSlotName, out how);

    public void SetExplicitPatch(string path) { ApPatchPath = path; SaveSettings(); }

    /// ROM safety net: when a patch is known, demand exactly its base ROM
    /// (base_checksum) so the launcher can ask the player by fingerprint instead
    /// of silently patching the wrong dump.
    public override RomRequirement? GetUnmetRomRequirement()
    {
        string? wantMd5 = null;
        var patch = ResolvePatchPath(out _);
        if (patch != null) wantMd5 = SnesApPatchHelper.ReadManifestField(patch, "base_checksum");

        bool haveRom = RomPath != null && File.Exists(RomPath);

        if (wantMd5 == null)
            return haveRom ? null
                 : new RomRequirement("Donkey Kong Country 2", "SNES",
                       "Donkey Kong Country 2 (USA)",
                       RequiredMd5: null, WrongVersionPresent: false, BuildRomFilter());

        if (haveRom && ComputeMd5(RomPath!).Equals(wantMd5, StringComparison.OrdinalIgnoreCase))
            return null;

        return new RomRequirement(
            "Donkey Kong Country 2", "SNES",
            "Donkey Kong Country 2 (USA) — the original vanilla cartridge dump",
            wantMd5, WrongVersionPresent: haveRom, BuildRomFilter());
    }

    private void RegisterSeed(string outRom, string patch)
    {
        try
        {
            SeedLibraryStore.Instance.Register(new SeedEntry
            {
                GameId         = GameId,
                PatchedRomPath = outRom,
                PatchPath      = patch,
                SeedName       = SnesApPatchHelper.ParseSeedFromPatch(patch),
                SlotName       = CurrentSlotName ?? "",
                CreatedUtc     = DateTimeOffset.UtcNow,
            });
        }
        catch { /* registry is non-essential to launching */ }
    }

    // ── Session ROM: apply the .apdkc2 to a library copy ──────────────────────

    protected override async Task<string?> PrepareSessionRomAsync(
        ApSession session, CancellationToken ct)
    {
        string? patch = ResolvePatchPath(out string how);
        if (patch == null)
        {
            SessionRomNote =
                "[Donkey Kong Country 2] No AP patch (.apdkc2) found — launching the " +
                "vanilla ROM. Checks and ITEM DELIVERY CANNOT WORK on a vanilla ROM: " +
                "generate the multiworld, then pick the patch in Settings → Donkey " +
                "Kong Country 2 (or drop it under " + SnesApPatchHelper.ApOutputDirectory + ").";
            return null;
        }

        if (RomPath == null || !File.Exists(RomPath))
        {
            SessionRomNote =
                "[Donkey Kong Country 2] No base ROM set — import your vanilla US " +
                "cartridge dump in Settings, then relaunch.";
            return null;
        }

        var result = await SnesApPatchHelper.ApplyAsync(
            "Donkey Kong Country 2", patch, how, RomPath!, RomLibraryDirectory, ResultExt, ct);
        SessionRomNote = result.Note;
        if (result.OutRom != null) RegisterSeed(result.OutRom, patch);
        return result.OutRom;
    }

    // ── Settings panel: base panel + AP patch section ─────────────────────────

    public override UIElement? CreateSettingsPanel()
    {
        var basePanel = base.CreateSettingsPanel();
        if (basePanel is not StackPanel panel) return basePanel;

        var muted = new SolidColorBrush(Color.FromRgb(0x72, 0x7A, 0x99));
        var fg    = new SolidColorBrush(Color.FromRgb(0xCC, 0xD0, 0xE0));

        panel.Children.Add(new TextBlock
        {
            Text = "ARCHIPELAGO PATCH", FontSize = 10, FontWeight = FontWeights.SemiBold,
            Foreground = muted, Margin = new Thickness(0, 20, 0, 8),
        });
        panel.Children.Add(new TextBlock
        {
            Text = "The multiworld generator produces a .apdkc2 patch for your slot. " +
                   "The launcher applies it to a COPY of your ROM at launch (your file " +
                   "is never modified). Leave empty to auto-use the newest patch from " +
                   "the Archipelago output folder.",
            FontSize = 11, Foreground = muted, TextWrapping = TextWrapping.Wrap,
            Margin = new Thickness(0, 0, 0, 8),
        });

        var patchRow = new DockPanel { Margin = new Thickness(0, 0, 0, 4) };
        var patchBox = new TextBox
        {
            Text = ApPatchPath ?? "", Margin = new Thickness(0, 0, 8, 0),
            IsReadOnly = true, FontSize = 12,
            Background  = new SolidColorBrush(Color.FromRgb(0x0C, 0x10, 0x20)),
            Foreground  = fg,
            BorderBrush = new SolidColorBrush(Color.FromRgb(0x1E, 0x22, 0x33)),
        };
        var clearBtn = new Button
        {
            Content = "Auto", Width = 50, Margin = new Thickness(0, 0, 8, 0),
            Padding = new Thickness(0, 6, 0, 6),
            Background  = new SolidColorBrush(Color.FromRgb(0x1A, 0x1E, 0x30)),
            Foreground  = fg,
            BorderBrush = new SolidColorBrush(Color.FromRgb(0x2A, 0x30, 0x50)),
            ToolTip = "Clear the explicit pick — auto-detect the newest generated patch.",
        };
        var pickBtn = new Button
        {
            Content = "Select AP patch...", Width = 130, Padding = new Thickness(0, 6, 0, 6),
            Background  = new SolidColorBrush(Color.FromRgb(0x1A, 0x1E, 0x30)),
            Foreground  = fg,
            BorderBrush = new SolidColorBrush(Color.FromRgb(0x2A, 0x30, 0x50)),
        };

        var autoNote = new TextBlock
        {
            FontSize = 10, Foreground = muted, TextWrapping = TextWrapping.Wrap,
            Margin = new Thickness(0, 4, 0, 0),
        };
        void RefreshAutoNote()
        {
            string? auto = ResolvePatchPath(out string how);
            autoNote.Text = ApPatchPath != null
                ? "Explicit patch selected — auto-detection off."
                : auto != null
                    ? $"Auto-detected ({how}): {auto}"
                    : $"No .apdkc2 found under {SnesApPatchHelper.ApOutputDirectory} yet.";
        }
        RefreshAutoNote();

        pickBtn.Click += (_, _) =>
        {
            var dlg = new Microsoft.Win32.OpenFileDialog
            {
                Title  = "Select Archipelago patch for Donkey Kong Country 2",
                Filter = "AP DKC2 patch (*.apdkc2)|*.apdkc2|All files (*.*)|*.*",
            };
            if (Directory.Exists(SnesApPatchHelper.ApOutputDirectory))
                dlg.InitialDirectory = SnesApPatchHelper.ApOutputDirectory;
            if (dlg.ShowDialog() != true) return;
            ApPatchPath   = dlg.FileName;
            patchBox.Text = dlg.FileName;
            SaveSettings();
            RefreshAutoNote();
        };
        clearBtn.Click += (_, _) =>
        {
            ApPatchPath   = null;
            patchBox.Text = "";
            SaveSettings();
            RefreshAutoNote();
        };

        DockPanel.SetDock(pickBtn,  Dock.Right);
        DockPanel.SetDock(clearBtn, Dock.Right);
        patchRow.Children.Add(pickBtn);
        patchRow.Children.Add(clearBtn);
        patchRow.Children.Add(patchBox);
        panel.Children.Add(patchRow);
        panel.Children.Add(autoNote);

        return panel;
    }
}
