using System;
using System.Collections.Generic;
using System.IO;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using LauncherV2.Core;

namespace LauncherV2.Plugins.Emulated.Games;

// ═══════════════════════════════════════════════════════════════════════════════
// DonkeyKong64Plugin — Archipelago integration for Donkey Kong 64 (Nintendo 64), on
// the proven BizHawk Lua-pipe bridge (N64 core).
//
// WORLD SOURCE: Donkey Kong 64 is NOT in ArchipelagoMW/Archipelago main — it ships
// in the community apworld https://github.com/MultiworldGG/MultiworldGG
// (worlds/dk64; archipelago.json game "Donkey Kong 64", world_version 1.5.7,
// minimum_ap_version 0.6.5; authors 2dos / AlmostSeagull / Ballaam / Green Bean /
// Killklli / Lrauq / PoryGone / Umed; the same source 2dos ships in the
// DK64-Randomizer repo's archipelago/ folder, releases at
// 2dos/DK64-Randomizer-Release). dk64.lua records the exact source URLs.
//
// STATUS: location DETECTION + goal are REAL and SOURCE-DERIVED. The 857-location
// flag table in dk64.lua was GENERATED by joining the world's own
// client/ap_check_ids.py (name → AP id) with client/check_flag_locations.py
// (EEPROM flag index → name, DROPSANITY_FLAG_START=0x426) and the shop-flag formula
// in DK64Client.getCheckStatus, and the EEPROM LSB-first bit math + the win-
// condition goal logic are replicated exactly from the reference client
// (DK64Client.readFlag / readChecks / is_victory); mock-verified through MoonSharp
// against synthetic big-endian N64 RDRAM + ROM. items_handling = 0b001 (the client
// sets ctx.items_handling = 0b001) — the PATCHED GAME grants its own locally-found
// items, so a SOLO seed plays fully and every check is reported in a multiworld.
// Delivering REMOTE multiworld items is the client's guarded RDRAM write path
// (writeFedData / writeCountData / setFlag into the live save + CountStruct); it is
// deferred (dk64.lua receive_item is a no-op) until it can be confirmed in-emulator,
// rather than shipped unverified — a wrong RDRAM write corrupts the live save.
// Checks + goal flow regardless.
//
// N64 NOTE: N64 is BIG-ENDIAN. The DK64 AP client is a direct-process-memory
// EmuLoaderClient (PJ64 / Mupen / BizHawk-DK64-Edition / RMG / ares / gopher /
// simple64); the RDRAM + ROM it reads are identical to BizHawk's "RDRAM" / "ROM"
// Lua domains. It addresses RDRAM by ABSOLUTE N64 KSEG0 pointers (0x80xxxxxx) with
// NO pointer-chase for the flag/goal reads — DK64MemoryMap is a flat list of fixed
// addresses — so dk64.lua strips KSEG0 (addr & 0x7FFFFF) and reads "RDRAM" there.
// The EEPROM save bitfield (0x807ECEA8) holds every location-checked flag; the
// "RAMB" (52 41 4D 42) cartridge signature at ROM 0x759290 is what the client
// validates (EmuLoaderClient signature_offset=0x759290, signature_value=0x52414D42)
// — dk64.lua gates all detection on it. N64 runs on BizHawk here only (the
// BizHawk-DK64-Edition is one of the DK64 community's supported targets; PJ64/RMG/
// ares/etc. are the external native client's own targets, not this launcher's bridge).
//
// HOW DONKEY KONG 64 IS PATCHED — IMPORTANT: unlike most AP ROM games, DK64 is NOT
// patched by the Archipelago generator and the world emits no APProcedurePatch
// container the launcher could apply. The player builds their playable seed with
// the DK64 Randomizer (dev.dk64randomizer.com / the DK64-Randomizer release), which
// takes their own legally-obtained "Donkey Kong 64 (USA)" ROM (dk64.z64), SHRINKS it
// via static/patches/shrink-dk64.bps, then patches in the seed + the "RAMB"
// signature — producing a randomized .z64. The player loads THAT .z64 here — the
// launcher applies no patch of its own; it loads the ROM directly (§11: the library
// copy, original untouched), same shape as the FF1 / Banjo-Tooie plugins. Because
// the ROM is shrunk and every seed differs, the randomized file has no fixed size or
// MD5 — it is identified by CONTENT via the runtime "RAMB" signature dk64.lua
// validates, never by filename (§11). The vanilla USA cartridge dump (32 MiB,
// MD5 9ec41abf…68c) is also accepted at import so a player is not blocked, but only
// the randomized .z64 actually carries the multiworld's checks/items.
// ═══════════════════════════════════════════════════════════════════════════════

public sealed class DonkeyKong64Plugin : EmulatorPlugin
{
    public DonkeyKong64Plugin() => LoadSettings();

    // ── Identity ──────────────────────────────────────────────────────────────

    public override string GameId      => "dk64";
    public override string DisplayName => "Donkey Kong 64";
    public override string Subtitle    => "N64 · Emulated";
    public override string ApWorldName => "Donkey Kong 64";

    public override string Description =>
        "Donkey Kong 64 is Rare's sprawling Nintendo 64 collect-a-thon, where five " +
        "Kongs — DK, Diddy, Lanky, Tiny and Chunky — comb eight enormous worlds to " +
        "thwart King K. Rool and his Blast-o-Matic. In the Archipelago randomizer, " +
        "Golden Bananas, blueprints, moves, Kongs, keys, coins and the countless " +
        "collectibles across DK Isles join the multiworld pool — meet your chosen " +
        "win condition (defeat K. Rool by default) to complete your run. Donkey " +
        "Kong 64 is randomized with the DK64 Randomizer, which patches your own USA " +
        "ROM into the seed's .z64.";

    public override string ThemeAccentColor => "#F2B01E";   // DK64 banana gold

    // ── Emulator specifics ────────────────────────────────────────────────────

    protected override string RomSystem     => "N64";

    // §14: N64 runs on BizHawk here (the DK64 community ships a BizHawk-DK64-Edition
    // as one of its supported clients). snes9x/mGBA/Mesen are SNES/GB-GBA/NES
    // emulators — not N64 — so they are deliberately NOT offered for this game.
    protected override IReadOnlyList<string> SupportedEmulatorIds =>
        new[] { "bizhawk" };
    protected override string LuaScriptName => "bizhawk_ap_connector.lua";
    protected override string LuaModuleName => "dk64";

    /// dk64.lua reports checks + goal (857-flag table generated from the apworld;
    /// EEPROM bit math + win-condition goal from the reference client; mock-verified).
    /// Remote-item delivery is the documented deferred piece (items_handling =
    /// 0b001, client-driven RDRAM/CountStruct writes).
    public override bool ChecksImplemented => true;

    /// The ROM the player loads is the DK64-Randomizer-built .z64 (the randomizer
    /// shrinks the USA ROM via shrink-dk64.bps then patches the seed + the "RAMB"
    /// signature), identified by CONTENT — never by filename (§11). The randomized
    /// ROM is shrunk and every seed differs, so it has no fixed size/MD5; dk64.lua's
    /// "RAMB" signature (ROM 0x759290) confirms it is really an AP DK64 ROM at launch.
    /// The vanilla "Donkey Kong 64 (USA)" cartridge dump (33,554,432 bytes = 32 MiB,
    /// MD5 9ec41abf2519fc386cadd0731f6e868c, native big-endian .z64) is also accepted
    /// at import so a player pointing at the un-randomized file is not blocked — but
    /// only the randomized .z64 carries the multiworld's checks/items.
    protected override IReadOnlyList<RomIdentity> AcceptableBaseRoms => new[]
    {
        new RomIdentity(33_554_432, "9ec41abf2519fc386cadd0731f6e868c",
            "Donkey Kong 64 (USA) — vanilla .z64 cartridge dump (build your seed with the DK64 Randomizer first)"),
    };

    // ── AP patch ────────────────────────────────────────────────────────────────
    //
    // DK64 has no APProcedurePatch the launcher applies (see header). We keep the
    // standard hook shape for consistency, but the resolver is only an optional
    // override: if a player ever drops an explicit patch container in Settings it
    // would be honored; otherwise the DK64-Randomizer-built .z64 is loaded directly
    // with no patch step. The AP generator never emits one.

    private const string PatchExt = ".apdk64";

    /// Explicit patch override chosen by the user (Settings / drag-drop). Null =
    /// none — the normal DK64 path, the randomized .z64 is loaded as-is.
    public string? ApPatchPath { get; private set; }

    protected override void OnSavingSettings(IDictionary<string, object?> bag)
        => bag["ap_patch_path"] = ApPatchPath;

    protected override void OnLoadingSettings(JsonElement root)
    {
        if (root.TryGetProperty("ap_patch_path", out var el)) ApPatchPath = el.GetString();
    }

    /// Set an explicit patch override (rare for DK64) and persist it.
    public void SetExplicitPatch(string path) { ApPatchPath = path; SaveSettings(); }

    /// ROM safety net. DK64 has no launcher-applied patch carrying an expected MD5,
    /// so the only requirement we can surface is "a DK64 ROM is present" — the player
    /// supplies the DK64-Randomizer-built .z64 themselves. A future explicit .apdk64
    /// override (which the AP generator does not emit) would still demand its base
    /// MD5 if one is set.
    public override RomRequirement? GetUnmetRomRequirement()
    {
        var patch = SnesApPatchHelper.ResolvePatch(
            PatchExt, ApPatchPath, GetSeedName?.Invoke(), CurrentSlotName, out _);
        string? wantMd5 = patch != null
            ? SnesApPatchHelper.ReadManifestField(patch, "base_checksum") : null;
        bool haveRom = RomPath != null && File.Exists(RomPath);

        if (wantMd5 == null)
            return haveRom ? null
                 : new RomRequirement("Donkey Kong 64", "N64",
                       "your DK64-Randomizer-built .z64 (make it with the DK64 Randomizer " +
                       "from your own Donkey Kong 64 (USA) ROM)",
                       RequiredMd5: null, WrongVersionPresent: false, BuildRomFilter());

        if (haveRom && ComputeMd5(RomPath!).Equals(wantMd5, StringComparison.OrdinalIgnoreCase))
            return null;

        return new RomRequirement("Donkey Kong 64", "N64",
            "Donkey Kong 64 (USA) — the exact ROM this patch was generated against",
            wantMd5, WrongVersionPresent: haveRom, BuildRomFilter());
    }

    // ── Session ROM ───────────────────────────────────────────────────────────
    //
    // The normal DK64 path applies NO patch — the player's library ROM IS the
    // DK64-Randomizer-built .z64 they produced, so we return null and the base class
    // launches it directly. Only an explicit .apdk64 override (not emitted by the AP
    // generator) would trigger SnesApPatchHelper; that branch is kept for parity with
    // the other emulated games but is inert for standard DK64 seeds.

    protected override async Task<string?> PrepareSessionRomAsync(
        ApSession session, CancellationToken ct)
    {
        string? patch = SnesApPatchHelper.ResolvePatch(
            PatchExt, ApPatchPath, GetSeedName?.Invoke(), CurrentSlotName, out string how);
        if (patch == null)
        {
            // Standard DK64: no launcher-applied AP patch. The library ROM is the
            // DK64-Randomizer-built .z64 the player generated with the DK64 Randomizer.
            SessionRomNote =
                "[Donkey Kong 64] Donkey Kong 64 is randomized by the DK64 Randomizer " +
                "(not by the launcher) — launching your ROM directly. Make sure this is " +
                "the randomized .z64 you built from your own Donkey Kong 64 (USA) ROM, " +
                "not the vanilla cartridge dump.";
            return null;
        }

        // Optional explicit-override path (kept for parity; DK64 never emits .apdk64).
        var res = await SnesApPatchHelper.ApplyAsync(
            "Donkey Kong 64", patch, how, RomPath!,
            RomLibraryDirectory, ".z64", ct);
        SessionRomNote = res.Note;
        if (res.OutRom != null) RegisterSeed(res.OutRom, patch);
        return res.OutRom;
    }

    /// Record a produced/reused patched ROM in the seed library. Never throws.
    /// (Only reached on the optional explicit-override path — standard DK64 seeds
    /// launch the DK64-Randomizer-built ROM directly and never get here.)
    private void RegisterSeed(string outRom, string patch)
    {
        try
        {
            SeedLibraryStore.Instance.Register(new SeedEntry
            {
                GameId         = GameId,
                PatchedRomPath = outRom,
                PatchPath      = patch,
                SeedName       = SnesApPatchHelper.ParseSeedFromPatch(patch),
                SlotName       = CurrentSlotName ?? "",
                CreatedUtc     = DateTimeOffset.UtcNow,
            });
        }
        catch { /* registry is non-essential to launching */ }
    }
}
