using System;
using System.Collections.Generic;
using System.IO;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using LauncherV2.Core;

namespace LauncherV2.Plugins.Emulated.Games;

// ═══════════════════════════════════════════════════════════════════════════════
// FFTacticsAdvancePlugin — Archipelago integration for Final Fantasy Tactics
// Advance (GBA), on the proven BizHawk Lua-pipe bridge.
//
// COMMUNITY APWORLD. FFTA is NOT in ArchipelagoMW/Archipelago main; it is
// spicynun's world (a fork), on the `ffta` branch:
//   https://github.com/spicynun/Archipelago/tree/ffta/worlds/ffta
//   (FFTAClient.game = "Final Fantasy Tactics Advance"; patch_suffix .apffta).
//
// STATUS: location DETECTION + goal are REAL and SOURCE-DERIVED. The 311-group /
// 1866-location table in ffta.lua was GENERATED by EXECUTING the world's own
// locations.py group-builder (MissionGroups + DispatchMissionGroups) — ids exact,
// not hand-copied — and the flag-scan + goal byte + "FFTA_USVER" ROM-name guard
// replicate FFTAClient.game_watcher exactly, mock-verified through MoonSharp
// against synthetic System-Bus memory.
//
// items_handling = 0b101 (remote items + starting inventory). FFTA is not a
// self-granting ROM for remote items, but its delivery path is an intricate,
// state-sensitive guarded System-Bus mailbox handshake (next-item + one-item
// lookahead written to 0x201f46c/0x201f46e, the game's received-item counter at
// 0x2002AF0 bumped, a trigger byte set, all behind a multi-byte guard list AND a
// world-map "Marche not moving" gate). That needs in-emulator confirmation before
// it is wired, so it is deferred (ffta.lua receive_item is a documented no-op)
// rather than shipped unverified. Detection + goal are fully live; a solo seed
// reports every check and completes its goal.
//
// AP PATCH (.apffta → .gba): FFTAProcedurePatch is a standard APProcedurePatch
// container (base_patch.bsdiff4 + progressive_shop_patch.bsdiff4 + token_data.bin),
// applied via the shared SnesApPatchHelper — resolve the seed's patch, validate
// the base ROM MD5 (the manifest base_checksum / FFTAProcedurePatch.hash), run
// apply_appatch.py on a library COPY (the original is never modified). Base ROM:
// the user's own Final Fantasy Tactics Advance (USA, Australia) cartridge dump
// (16 MB, MD5 cd99…b7bd), identified by CONTENT (size + MD5) — never by filename
// (§11).
// ═══════════════════════════════════════════════════════════════════════════════

public sealed class FFTacticsAdvancePlugin : EmulatorPlugin
{
    public FFTacticsAdvancePlugin() => LoadSettings();

    // ── Identity ──────────────────────────────────────────────────────────────

    public override string GameId      => "ffta";
    public override string DisplayName => "Final Fantasy Tactics Advance";
    public override string Subtitle    => "GBA · Emulated";

    // Exact AP world id ("game" string in FFTAClient.game / FFTAProcedurePatch).
    public override string ApWorldName => "Final Fantasy Tactics Advance";

    public override string Description =>
        "Final Fantasy Tactics Advance is the GBA tactical RPG set in the world of " +
        "Ivalice. In the Archipelago randomizer, the rewards from missions and " +
        "dispatch quests across the land join the multiworld pool, with options for " +
        "the final mission, job-unlock requirements, progressive gates and shops, " +
        "and law cards. Clear your chosen final mission to complete your goal.";

    public override string ThemeAccentColor => "#3C6E9C";   // Ivalice sky blue

    // ── Emulator specifics ────────────────────────────────────────────────────

    protected override string RomSystem     => "GBA";

    // §14: GBA emulators — BizHawk verified; mGBA/Mesen are the alternatives
    // (shown per their bridge state in the dropdown).
    protected override IReadOnlyList<string> SupportedEmulatorIds =>
        new[] { "bizhawk", "mgba", "mesen" };
    protected override string LuaScriptName => "bizhawk_ap_connector.lua";
    protected override string LuaModuleName => "ffta";

    /// ffta.lua reports checks + goal (table generated from the apworld's own
    /// group builder; game_watcher flag math; mock-verified). Remote-item delivery
    /// is the documented deferred piece (0b101, intricate guarded mailbox path).
    public override bool ChecksImplemented => true;

    /// The vanilla cartridge dump the randomizer is built for, by CONTENT
    /// (16 MB + MD5) — never by filename. The patch base_checksum
    /// (FFTAProcedurePatch.hash) validates the exact dump before anything is
    /// written. FFTA (USA, Australia) is a 16 MB cartridge.
    protected override IReadOnlyList<RomIdentity> AcceptableBaseRoms => new[]
    {
        new RomIdentity(16 * 1024 * 1024, "cd99cdde3d45554c1b36fbeb8863b7bd",
                        "Final Fantasy Tactics Advance (USA, Australia)"),
    };

    // ── AP patch ────────────────────────────────────────────────────────────────

    private const string PatchExt = ".apffta";

    /// Explicit .apffta chosen by the user (Settings / drag-drop). Null = auto.
    public string? ApPatchPath { get; private set; }

    protected override void OnSavingSettings(IDictionary<string, object?> bag)
        => bag["ap_patch_path"] = ApPatchPath;

    protected override void OnLoadingSettings(JsonElement root)
    {
        if (root.TryGetProperty("ap_patch_path", out var el)) ApPatchPath = el.GetString();
    }

    /// Set the explicit AP patch (drag-and-drop / room-link import) and persist it.
    public void SetExplicitPatch(string path) { ApPatchPath = path; SaveSettings(); }

    /// ROM safety net: the resolved patch tells us the EXACT vanilla ROM MD5 it
    /// needs — demand that specific dump when ours is missing or the wrong one.
    public override RomRequirement? GetUnmetRomRequirement()
    {
        var patch = SnesApPatchHelper.ResolvePatch(
            PatchExt, ApPatchPath, GetSeedName?.Invoke(), CurrentSlotName, out _);
        string? wantMd5 = patch != null
            ? SnesApPatchHelper.ReadManifestField(patch, "base_checksum") : null;
        bool haveRom = RomPath != null && File.Exists(RomPath);

        if (wantMd5 == null)
            return haveRom ? null
                 : new RomRequirement("Final Fantasy Tactics Advance", "GBA",
                       "Final Fantasy Tactics Advance (USA, Australia)",
                       RequiredMd5: null, WrongVersionPresent: false, BuildRomFilter());

        if (haveRom && ComputeMd5(RomPath!).Equals(wantMd5, StringComparison.OrdinalIgnoreCase))
            return null;

        return new RomRequirement("Final Fantasy Tactics Advance", "GBA",
            "Final Fantasy Tactics Advance (USA, Australia) — your original cartridge dump",
            wantMd5, WrongVersionPresent: haveRom, BuildRomFilter());
    }

    // ── Session ROM: apply the .apffta to a library copy ──────────────────────

    protected override async Task<string?> PrepareSessionRomAsync(
        ApSession session, CancellationToken ct)
    {
        string? patch = SnesApPatchHelper.ResolvePatch(
            PatchExt, ApPatchPath, GetSeedName?.Invoke(), CurrentSlotName, out string how);
        if (patch == null)
        {
            SessionRomNote =
                "[Final Fantasy Tactics Advance] No AP patch (.apffta) found — " +
                "launching the vanilla ROM. Generate the multiworld, then pick the " +
                "patch in Settings (or drop it under " +
                SnesApPatchHelper.ApOutputDirectory + ").";
            return null;
        }

        var res = await SnesApPatchHelper.ApplyAsync(
            "Final Fantasy Tactics Advance", patch, how, RomPath!,
            RomLibraryDirectory, ".gba", ct);
        SessionRomNote = res.Note;
        if (res.OutRom != null) RegisterSeed(res.OutRom, patch);
        return res.OutRom;
    }

    /// Record a produced/reused patched ROM in the seed library. Never throws.
    private void RegisterSeed(string outRom, string patch)
    {
        try
        {
            SeedLibraryStore.Instance.Register(new SeedEntry
            {
                GameId         = GameId,
                PatchedRomPath = outRom,
                PatchPath      = patch,
                SeedName       = SnesApPatchHelper.ParseSeedFromPatch(patch),
                SlotName       = CurrentSlotName ?? "",
                CreatedUtc     = DateTimeOffset.UtcNow,
            });
        }
        catch { /* registry is non-essential to launching */ }
    }
}
