using System;
using System.Collections.Generic;
using System.IO;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using LauncherV2.Core;

namespace LauncherV2.Plugins.Emulated.Games;

// ═══════════════════════════════════════════════════════════════════════════════
// FinalFantasyMysticQuestPlugin — Archipelago integration for Final Fantasy Mystic
// Quest (SNES, USA), on the proven BizHawk Lua-pipe bridge.
//
// STATUS: location DETECTION + goal are REAL and SOURCE-DERIVED. The three
// location tables in ffmq.lua (230 chest/box containers + 16 NPC + 20 battlefield
// = 266 locations) were GENERATED by PARSING worlds/ffmq source (the exact
// location_table Regions.py builds, the NPC_CHECKS dict + chest/battlefield scan
// ranges from Client.py); the MSB-first flag math, the live-read consistency gate
// ({01 'F' 'F' 'M' 'Q' 'R'} at WRAM 0x3749), the "MQ" ROM-header signature and the
// COMPLETED&0x80 + GAME_FLAGS[30]&0x18 goal are all replicated exactly from
// Client.py, and mock-verified through MoonSharp against synthetic SNES memory
// (14/14). items_handling = 0b001 — the PATCHED GAME grants its own locally-found
// items, so a SOLO seed plays fully and every check is reported. Delivering REMOTE
// multiworld items is the client's CARTRAM hand-off (RECEIVED_DATA at $E0:1FF0);
// that single guarded write is the documented deferred piece (ffmq.lua receive_item
// is a no-op) until it can be confirmed in-emulator — a wrong CARTRAM write would
// corrupt the save — exactly like the other SNES modules in this wave.
//
// HOW FFMQ IS RANDOMIZED — IMPORTANT: like Final Fantasy 1, FFMQ is NOT patched by
// Archipelago with a self-contained binary diff. The .apmq the generator produces
// is an APPatch (procedure="custom", NO base_checksum, NO bsdiff/token blob) — it
// is a ZIP of randomizer INSTRUCTIONS (itemplacement/flagset/rooms yaml), not a
// patch SnesApPatchHelper can apply. The player builds their ROM on the FFMQR web
// service (https://ap.ffmqrando.net/Archipelago): they upload their own legally-
// obtained FFMQ (USA v1.0 or v1.1) ROM + the .apmq, and the site returns the final
// patched *.sfc. That ALREADY-PATCHED .sfc is what the player loads here — the
// launcher applies no patch of its own; it loads the ROM directly (§11: the
// library copy, original untouched). It is identified by CONTENT (size + the "MQ"
// ROM-header signature ffmq.lua verifies) — never by filename (§11). The patched
// output is a standard 512 KB LoROM (524,288 bytes); each seed differs, so no fixed
// MD5 can be demanded — the size + signature are the stable fingerprint, mirroring
// the FinalFantasy1Plugin pattern exactly.
// ═══════════════════════════════════════════════════════════════════════════════

public sealed class FinalFantasyMysticQuestPlugin : EmulatorPlugin
{
    public FinalFantasyMysticQuestPlugin() => LoadSettings();

    // ── Identity ──────────────────────────────────────────────────────────────

    public override string GameId      => "ffmq";
    public override string DisplayName => "Final Fantasy Mystic Quest";
    public override string Subtitle    => "SNES · Emulated";
    public override string ApWorldName => "Final Fantasy Mystic Quest";

    public override string Description =>
        "Final Fantasy Mystic Quest is the approachable SNES action-RPG spin-off, " +
        "set across four continents linked by the Focus Tower. In the Archipelago " +
        "randomizer, every chest, box, battlefield reward, and NPC gift joins the " +
        "multiworld pool, with optional map, crest, and companion shuffles. Fight " +
        "down through the Focus Tower and defeat the Dark King to complete your " +
        "goal. Build your ROM at ap.ffmqrando.net from your own FFMQ (USA) cartridge.";

    public override string ThemeAccentColor => "#3C6FB8";   // Mystic Quest sky blue

    // ── Emulator specifics ────────────────────────────────────────────────────

    protected override string RomSystem     => "SNES";

    // §14: the SNES emulators this world is played on. BizHawk is verified; snes9x
    // is the headline alternative (the §14 Discord ask was "SNES: BizHawk or
    // snes9x"), with Mesen as a third option — both shown per their bridge state.
    // NOTE: the snes9x NWA bridge maps only WRAM + SRAM, so the "MQ" ROM-header
    // gate can't run there yet; BizHawk is the confirmed path.
    protected override IReadOnlyList<string> SupportedEmulatorIds =>
        new[] { "bizhawk", "snes9x", "mesen" };
    protected override string LuaScriptName => "bizhawk_ap_connector.lua";
    protected override string LuaModuleName => "ffmq";

    /// ffmq.lua reports checks + goal (tables generated from the apworld; bit math
    /// + gates from Client.py; mock-verified). Remote-item delivery is the
    /// documented deferred piece (items_handling = 0b001, guarded CARTRAM write).
    public override bool ChecksImplemented => true;

    /// The ROM the player loads is the ALREADY-PATCHED FFMQ .sfc produced by the
    /// FFMQR web service (ap.ffmqrando.net) from their own USA cartridge + the
    /// .apmq, identified by CONTENT — never by filename (§11). The patched output
    /// is a standard 512 KB LoROM (524,288 bytes). No MD5 is pinned: every seed
    /// differs, so size is the stable detector and ffmq.lua's "MQ" ROM-header
    /// signature confirms it is really an FFMQ ROM at launch. (The FFMQR randomizer
    /// accepts both USA v1.0 and v1.1 dumps as input, converting v1.1→v1.0
    /// internally; both yield a 524,288-byte patched ROM here.)
    protected override IReadOnlyList<RomIdentity> AcceptableBaseRoms => new[]
    {
        new RomIdentity(524_288, null,
            "Final Fantasy Mystic Quest (USA) — your patched ROM from ap.ffmqrando.net"),
    };

    // ── AP patch ────────────────────────────────────────────────────────────────
    //
    // FFMQ has no APProcedurePatch the launcher can apply (see header) — the .apmq
    // is consumed by the FFMQR web service together with the player's ROM. We keep
    // the standard hook shape for consistency, but the resolver is only an optional
    // override: if a player ever drops an explicit container in Settings it would be
    // honored, otherwise the patched ROM is loaded directly with no patch step. The
    // AP generator never emits a launcher-appliable patch for FFMQ.

    private const string PatchExt = ".apmq";

    /// Explicit patch override chosen by the user (Settings / drag-drop). Null =
    /// none — the normal FFMQ path, the patched .sfc is loaded as-is.
    public string? ApPatchPath { get; private set; }

    protected override void OnSavingSettings(IDictionary<string, object?> bag)
        => bag["ap_patch_path"] = ApPatchPath;

    protected override void OnLoadingSettings(JsonElement root)
    {
        if (root.TryGetProperty("ap_patch_path", out var el)) ApPatchPath = el.GetString();
    }

    /// Set an explicit patch override (rare for FFMQ) and persist it.
    public void SetExplicitPatch(string path) { ApPatchPath = path; SaveSettings(); }

    /// ROM safety net. FFMQ has no launcher-appliable patch carrying an expected
    /// MD5, so the only requirement we can surface is "an FFMQ ROM is present" —
    /// the player supplies the patched .sfc themselves. A future explicit override
    /// container (which the AP generator does not emit) would still demand its base
    /// MD5 if one were set.
    public override RomRequirement? GetUnmetRomRequirement()
    {
        var patch = SnesApPatchHelper.ResolvePatch(
            PatchExt, ApPatchPath, GetSeedName?.Invoke(), CurrentSlotName, out _);
        string? wantMd5 = patch != null
            ? SnesApPatchHelper.ReadManifestField(patch, "base_checksum") : null;
        bool haveRom = RomPath != null && File.Exists(RomPath);

        if (wantMd5 == null)
            return haveRom ? null
                 : new RomRequirement("Final Fantasy Mystic Quest", "SNES",
                       "your patched Final Fantasy Mystic Quest (USA) ROM " +
                       "(build it at ap.ffmqrando.net from your own cartridge + the .apmq)",
                       RequiredMd5: null, WrongVersionPresent: false, BuildRomFilter());

        if (haveRom && ComputeMd5(RomPath!).Equals(wantMd5, StringComparison.OrdinalIgnoreCase))
            return null;

        return new RomRequirement("Final Fantasy Mystic Quest", "SNES",
            "Final Fantasy Mystic Quest (USA) — the exact ROM this patch was generated against",
            wantMd5, WrongVersionPresent: haveRom, BuildRomFilter());
    }

    // ── Session ROM ───────────────────────────────────────────────────────────
    //
    // The normal FFMQ path applies NO patch — the player's library ROM IS the
    // already-patched .sfc built on ap.ffmqrando.net, so we return null and the
    // base class launches it directly. Only an explicit override container (not
    // emitted by the AP generator) would trigger SnesApPatchHelper; that branch is
    // kept for parity with the other emulated games but is inert for standard FFMQ
    // seeds.

    protected override async Task<string?> PrepareSessionRomAsync(
        ApSession session, CancellationToken ct)
    {
        string? patch = SnesApPatchHelper.ResolvePatch(
            PatchExt, ApPatchPath, GetSeedName?.Invoke(), CurrentSlotName, out string how);
        if (patch == null)
        {
            // Standard FFMQ: no launcher-appliable patch exists. The library ROM is
            // the patched .sfc the player built on the FFMQR web service.
            SessionRomNote =
                "[Final Fantasy Mystic Quest] FFMQ is patched on ap.ffmqrando.net " +
                "(not by Archipelago) — launching your ROM directly. Make sure this " +
                "ROM is the patched .sfc you built from your cartridge + the .apmq " +
                "file, not the unmodified cartridge dump.";
            return null;
        }

        // Optional explicit-override path (kept for parity; FFMQ never emits an
        // applieable .apmq — its .apmq is consumed by the web service instead).
        var res = await SnesApPatchHelper.ApplyAsync(
            "Final Fantasy Mystic Quest", patch, how, RomPath!,
            RomLibraryDirectory, ".sfc", ct);
        SessionRomNote = res.Note;
        if (res.OutRom != null) RegisterSeed(res.OutRom, patch);
        return res.OutRom;
    }

    /// Record a produced/reused patched ROM in the seed library. Never throws.
    /// (Only reached on the optional explicit-override path — standard FFMQ seeds
    /// launch the web-service-patched ROM directly and never get here.)
    private void RegisterSeed(string outRom, string patch)
    {
        try
        {
            SeedLibraryStore.Instance.Register(new SeedEntry
            {
                GameId         = GameId,
                PatchedRomPath = outRom,
                PatchPath      = patch,
                SeedName       = SnesApPatchHelper.ParseSeedFromPatch(patch),
                SlotName       = CurrentSlotName ?? "",
                CreatedUtc     = DateTimeOffset.UtcNow,
            });
        }
        catch { /* registry is non-essential to launching */ }
    }
}
