using System;
using System.Collections.Generic;
using System.IO;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using LauncherV2.Core;

namespace LauncherV2.Plugins.Emulated.Games;

// ═══════════════════════════════════════════════════════════════════════════════
// FinalFantasyVIPlugin — Archipelago integration for Final Fantasy VI: Worlds
// Collide (SNES, FF3us), on the proven BizHawk Lua-pipe bridge.
//
// STATUS: location DETECTION + goal are REAL and SOURCE-DERIVED. The two location
// tables in ff6wc.lua (58 event-flag checks + 259 treasure chests, plus the special-
// cased Lone Wolf / Narshe Weapon Shop pairs and the point-of-no-return back-fill)
// were GENERATED by PARSING the official apworld worlds/ff6wc (Rom.py
// event_flag_location_names + treasure_chest_data, each name's AP id = base_id 6000 +
// its index in Locations.location_table). The event/treasure bit math, the "6WC" ROM
// signature, the map/menu in-game gate and the CARTRAM victory byte are replicated
// exactly from Client.py; the generated tables also cross-check against the community
// EmoTracker autotracking addresses. Mock-verified through MoonSharp against synthetic
// SNES memory. items_handling = 0b111 — the AP SERVER drives ALL item delivery; the
// reference client applies each item with intricate, type-specific guarded writes
// (character init/recruit bits + counters + SwdTech/Blitz, esper bits + counters, a
// 255-slot field-inventory scan for items). That whole write path is the documented
// deferred piece (ff6wc.lua receive_item is a no-op) until it can be confirmed in-
// emulator — a wrong WRAM write would corrupt the save — exactly like the other SNES
// modules in this wave. Checks + goal flow regardless.
//
// THE PATCH (.apff6wc) is an APDeltaPatch (bsdiff4) — the SAME family as A Link to
// the Past's .aplttp and Super Metroid's .apsm, applied by the shared
// SnesApPatchHelper + Plugins/Scripts/apply_appatch.py on a library COPY (the
// original ROM is never modified). The FF6WC generator runs the WorldsCollide
// randomizer at generation time against the vanilla FF3us ROM and ships the result
// as the bsdiff4 .apff6wc patch, so unlike Final Fantasy Mystic Quest there is NO
// external web-patch step — the launcher applies the patch itself.
//
// Base ROM: the user's own legally-obtained Final Fantasy III (USA) — i.e. FF3us /
// FF6 NA 1.0 — cartridge dump (3,145,728 bytes, headerless, MD5
// e986575b98300f721ce27c180264d890), identified by CONTENT (size + MD5) — never by
// filename (§11). apply_appatch.py independently re-checks the patch container's own
// base_checksum before patching, so this only drives the launcher's "wrong version"
// hint.
// ═══════════════════════════════════════════════════════════════════════════════

public sealed class FinalFantasyVIPlugin : EmulatorPlugin
{
    public FinalFantasyVIPlugin() => LoadSettings();

    // ── Identity ──────────────────────────────────────────────────────────────

    public override string GameId      => "ff6wc";
    public override string DisplayName => "Final Fantasy VI";
    public override string Subtitle    => "SNES · Emulated";
    public override string ApWorldName => "Final Fantasy 6 Worlds Collide";

    public override string Description =>
        "Final Fantasy VI: Worlds Collide is the open-world randomizer of the SNES " +
        "classic (released as Final Fantasy III in North America). You start with the " +
        "airship and roam freely between the World of Balance and the World of Ruin; " +
        "the Archipelago randomizer scatters characters, espers, and treasures across " +
        "both worlds into the multiworld pool. Complete your objectives and defeat " +
        "Kefka to win.";

    public override string ThemeAccentColor => "#1E63B0";   // Worlds Collide steel blue

    // ── Emulator specifics ────────────────────────────────────────────────────

    protected override string RomSystem     => "SNES";

    // §14: the SNES emulators this world is played on. BizHawk is verified; snes9x is
    // the headline alternative (the §14 Discord ask was "SNES: BizHawk or snes9x"),
    // with Mesen as a third option — all shown per their bridge state in the dropdown.
    // NOTE: the snes9x NWA bridge maps only WRAM + SRAM, so the "6WC" ROM-header gate
    // (in cartridge ROM) can't run there yet; BizHawk is the confirmed path.
    protected override IReadOnlyList<string> SupportedEmulatorIds =>
        new[] { "bizhawk", "snes9x", "mesen" };
    protected override string LuaScriptName => "bizhawk_ap_connector.lua";
    protected override string LuaModuleName => "ff6wc";

    /// ff6wc.lua reports checks + goal (tables generated from the apworld; bit math +
    /// gates from Client.py; mock-verified). Remote-item delivery is the documented
    /// deferred piece (items_handling = 0b111, intricate per-type guarded writes).
    public override bool ChecksImplemented => true;

    /// The vanilla Final Fantasy III (USA) cartridge dump the randomizer is built for,
    /// identified by CONTENT (3 MB + MD5), never by filename. This is the long-standing
    /// community-known FF3us NA 1.0 hash every FF6WC generator validates against
    /// (Rom.py NA10HASH); apply_appatch.py independently re-checks the patch
    /// container's own base_checksum before patching, so this only drives the
    /// launcher's "wrong version" hint. The ROM is headerless (3,145,728 bytes); a
    /// copier-headered dump (3,146,240 bytes) is the wrong size and is rejected at
    /// import.
    protected override IReadOnlyList<RomIdentity> AcceptableBaseRoms => new[]
    {
        new RomIdentity(3_145_728,                            // 3 MB, headerless
                        "e986575b98300f721ce27c180264d890",
                        "Final Fantasy III (USA) — FF3us / FF6 NA 1.0 cartridge dump"),
    };

    // ── AP patch settings ─────────────────────────────────────────────────────

    private const string PatchExt  = ".apff6wc";
    private const string ResultExt = ".sfc";

    /// Explicit .apff6wc chosen by the user (Settings / drag-drop). Null = auto.
    public string? ApPatchPath { get; private set; }

    protected override void OnSavingSettings(IDictionary<string, object?> bag)
        => bag["ap_patch_path"] = ApPatchPath;

    protected override void OnLoadingSettings(JsonElement root)
    {
        if (root.TryGetProperty("ap_patch_path", out var el)) ApPatchPath = el.GetString();
    }

    private string? ResolvePatchPath(out string how)
        => SnesApPatchHelper.ResolvePatch(
            PatchExt, ApPatchPath, GetSeedName?.Invoke(), CurrentSlotName, out how);

    /// Set the explicit AP patch (drag-and-drop / room-link import) and persist it.
    public void SetExplicitPatch(string path) { ApPatchPath = path; SaveSettings(); }

    /// ROM safety net: the resolved patch tells us the EXACT vanilla ROM MD5 it needs
    /// (base_checksum) — demand that specific dump when ours is missing or wrong.
    public override RomRequirement? GetUnmetRomRequirement()
    {
        string? wantMd5 = null;
        var patch = ResolvePatchPath(out _);
        if (patch != null) wantMd5 = SnesApPatchHelper.ReadManifestField(patch, "base_checksum");

        bool haveRom = RomPath != null && File.Exists(RomPath);

        if (wantMd5 == null)
            return haveRom ? null
                 : new RomRequirement("Final Fantasy VI", "SNES",
                       "Final Fantasy III (USA) — FF3us / FF6 NA 1.0 cartridge dump",
                       RequiredMd5: null, WrongVersionPresent: false, BuildRomFilter());

        if (haveRom && ComputeMd5(RomPath!).Equals(wantMd5, StringComparison.OrdinalIgnoreCase))
            return null;

        return new RomRequirement("Final Fantasy VI", "SNES",
            "Final Fantasy III (USA) — your original FF3us / FF6 NA 1.0 cartridge dump",
            wantMd5, WrongVersionPresent: haveRom, BuildRomFilter());
    }

    // ── Session ROM: apply the .apff6wc to a library copy ─────────────────────

    protected override async Task<string?> PrepareSessionRomAsync(
        ApSession session, CancellationToken ct)
    {
        string? patch = ResolvePatchPath(out string how);
        if (patch == null)
        {
            SessionRomNote =
                "[Final Fantasy VI] No AP patch (.apff6wc) found — launching the " +
                "vanilla ROM. Checks and ITEM DELIVERY CANNOT WORK on a vanilla ROM: " +
                "generate the multiworld, then pick the patch in Settings → Final " +
                "Fantasy VI (or drop it under " + SnesApPatchHelper.ApOutputDirectory +
                ").";
            return null;
        }

        if (RomPath == null || !File.Exists(RomPath))
        {
            SessionRomNote =
                "[Final Fantasy VI] No base ROM set — import your Final Fantasy III " +
                "(USA) cartridge dump in Settings, then relaunch.";
            return null;
        }

        var result = await SnesApPatchHelper.ApplyAsync(
            "Final Fantasy VI", patch, how, RomPath!, RomLibraryDirectory, ResultExt, ct);
        SessionRomNote = result.Note;
        if (result.OutRom != null) RegisterSeed(result.OutRom, patch);
        return result.OutRom;
    }

    /// Record a produced/reused patched ROM in the seed library. Never throws.
    private void RegisterSeed(string outRom, string patch)
    {
        try
        {
            SeedLibraryStore.Instance.Register(new SeedEntry
            {
                GameId         = GameId,
                PatchedRomPath = outRom,
                PatchPath      = patch,
                SeedName       = SnesApPatchHelper.ParseSeedFromPatch(patch),
                SlotName       = CurrentSlotName ?? "",
                CreatedUtc     = DateTimeOffset.UtcNow,
            });
        }
        catch { /* registry is non-essential to launching */ }
    }
}
