using System;
using System.Collections.Generic;
using System.IO;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using LauncherV2.Core;

namespace LauncherV2.Plugins.Emulated.Games;

// ═══════════════════════════════════════════════════════════════════════════════
// FinalFantasyIVPlugin — Archipelago integration for Final Fantasy IV: Free
// Enterprise (SNES), on the proven BizHawk Lua-pipe bridge.
//
// STATUS: location DETECTION + goal are REAL and SOURCE-DERIVED. The three location
// tables in ff4fe.lua (399 treasure + 75 reward + 32 objective = 506 of the world's
// 508 locations) were GENERATED by PARSING worlds/ff4fe source — re-running the exact
// locations.py `all_locations` construction over the world's own data CSVs through
// its own csvdb.py, then assigning AP ids the way FF4FEWorld does (base_id 7191991 +
// position in all_locations) and splitting them by the in-game decode category
// FF4FEClient uses; the LSB-first treasure/reward bit math, the six-sentinel
// safe-state gate, the "4FE" ROM-header signature and the victory-byte goal are all
// replicated exactly from Client.py + rom.py, and mock-verified through MoonSharp
// against synthetic SNES memory (8/8). items_handling = 0b111 — the AP SERVER drives
// item delivery, but FF4FE's apply path is intricate decision logic over the live
// inventory / junk-tier / sell settings / seed flags with guarded WRAM+SRAM writes
// gated on the game's own received-item counter; that single hand-off is the
// documented deferred piece (ff4fe.lua receive_item is a no-op) until it can be
// confirmed in-emulator — a wrong WRAM/SRAM write would corrupt the save — exactly
// like the other SNES modules in this wave. Checks + goal flow regardless.
//
// HOW FF4FE IS RANDOMIZED — IMPORTANT: like Final Fantasy 1 and FFMQ, FF4 Free
// Enterprise is NOT patched by Archipelago with a self-contained binary diff. The
// .apff4fe the generator produces is an FF4FEProcedurePatch whose single procedure
// (`call_fe`) invokes the actual Free Enterprise randomizer (FreeEnt.cmd_make
// MakeCommand) installed in the AP data directory (…/data/ff4fe). So the ROM is
// built by the AP client's own patch step at generation/host time — there is no
// bsdiff/token blob SnesApPatchHelper could apply, and the FE engine isn't present
// in this launcher. The player therefore brings the ALREADY-BUILT *.sfc that the AP
// client produced from their own legally-obtained FF4 (USA) cartridge + the .apff4fe
// — and the launcher loads it directly (§11: the library copy, original untouched),
// applying no patch of its own. It is identified by CONTENT (size + the "4FE"
// ROM-header signature ff4fe.lua verifies) — never by filename (§11). The build
// output is a standard 2 MB LoROM (2,097,152 bytes); each seed differs, so no fixed
// MD5 can be demanded — the size + signature are the stable fingerprint, mirroring
// the FinalFantasy1Plugin / FinalFantasyMysticQuestPlugin pattern exactly.
//
// BASE ROM: the FF4FE world's settings pin the FF4 USA 1.1 cartridge — "Final
// Fantasy II (USA) (Rev A).sfc", MD5 27D02A4F03E172E029C9B82AC3DB79F7 (rom.py
// FF4FESettings.RomFile.md5s + FF4FEProcedurePatch.hash). That dump (1,048,576
// bytes) is accepted at import so a player who points at the un-built cartridge is
// not blocked — but only the AP-built ROM carries the multiworld's checks.
// ═══════════════════════════════════════════════════════════════════════════════

public sealed class FinalFantasyIVPlugin : EmulatorPlugin
{
    public FinalFantasyIVPlugin() => LoadSettings();

    // ── Identity ──────────────────────────────────────────────────────────────

    public override string GameId      => "ff4fe";
    public override string DisplayName => "Final Fantasy IV: Free Enterprise";
    public override string Subtitle    => "SNES · Emulated";
    public override string ApWorldName => "Final Fantasy IV Free Enterprise";

    public override string Description =>
        "Final Fantasy IV: Free Enterprise is the open-world randomizer of the SNES " +
        "classic, built for racing and exploration: you get the airship from the " +
        "start and tackle the quests in any order. In the Archipelago randomizer, " +
        "every treasure chest, event reward, and objective across the Overworld, " +
        "Underworld, and Moon joins the multiworld pool. Find the Crystal and defeat " +
        "Zeromus on the Moon to complete your goal. Build your ROM with the " +
        "Archipelago client from your own Final Fantasy II (USA) cartridge.";

    public override string ThemeAccentColor => "#2A4DA8";   // Final Fantasy crystal blue

    // ── Emulator specifics ────────────────────────────────────────────────────

    protected override string RomSystem     => "SNES";

    // §14: the SNES emulators this world is played on. BizHawk is the verified
    // SNIClient target; snes9x is the headline alternative (the §14 Discord ask was
    // "SNES: BizHawk or snes9x"), with Mesen as a third option — both shown per
    // their bridge state. NOTE: the snes9x NWA bridge maps only WRAM + SRAM, so the
    // "4FE" ROM-header gate (read from the cartridge ROM) can't run there yet;
    // BizHawk is the confirmed path.
    protected override IReadOnlyList<string> SupportedEmulatorIds =>
        new[] { "bizhawk", "snes9x", "mesen" };
    protected override string LuaScriptName => "bizhawk_ap_connector.lua";
    protected override string LuaModuleName => "ff4fe";

    /// ff4fe.lua reports checks + goal (tables generated from the apworld; bit math
    /// + safe-state gate + victory goal from Client.py/rom.py; mock-verified).
    /// Remote-item delivery is the documented deferred piece (items_handling =
    /// 0b111, intricate guarded WRAM+SRAM inventory writes).
    public override bool ChecksImplemented => true;

    /// The ROM the player loads is the ALREADY-BUILT FF4FE .sfc the Archipelago
    /// client produced (via the embedded Free Enterprise randomizer) from their own
    /// FF4 (USA) cartridge + the .apff4fe, identified by CONTENT — never by filename
    /// (§11). The build output is a standard 2 MB LoROM (2,097,152 bytes). No MD5 is
    /// pinned: every seed differs, so size is the stable detector and ff4fe.lua's
    /// "4FE" ROM-header signature confirms it is really an FF4FE ROM at launch. The
    /// vanilla FF4 USA 1.1 cartridge dump (Final Fantasy II (USA) (Rev A),
    /// 1,048,576 bytes, MD5 27D02A4F03E172E029C9B82AC3DB79F7 — the exact dump the
    /// world pins) is also accepted so a player who points at the un-built file is
    /// not blocked at import; only the AP-built ROM carries the multiworld's checks.
    protected override IReadOnlyList<RomIdentity> AcceptableBaseRoms => new[]
    {
        new RomIdentity(2_097_152, null,
            "Final Fantasy IV: Free Enterprise — your Archipelago-built ROM (2 MB)"),
        new RomIdentity(1_048_576, "27d02a4f03e172e029c9b82ac3db79f7",
            "Final Fantasy II (USA) (Rev A) — vanilla FF4 cartridge dump " +
            "(build the Free Enterprise ROM with the Archipelago client first)"),
    };

    // ── AP patch ────────────────────────────────────────────────────────────────
    //
    // FF4FE has no APProcedurePatch the launcher can apply (see header) — the
    // .apff4fe is consumed by the AP client's own Free Enterprise build step, which
    // needs the FE engine installed in the AP data directory and is not present in
    // this launcher. We keep the standard hook shape for consistency, but the
    // resolver is only an optional override: if a player ever drops an explicit
    // container in Settings it would be honored, otherwise the built ROM is loaded
    // directly with no patch step. The AP generator never emits a launcher-appliable
    // patch for FF4FE.

    private const string PatchExt = ".apff4fe";

    /// Explicit patch override chosen by the user (Settings / drag-drop). Null =
    /// none — the normal FF4FE path, the built .sfc is loaded as-is.
    public string? ApPatchPath { get; private set; }

    protected override void OnSavingSettings(IDictionary<string, object?> bag)
        => bag["ap_patch_path"] = ApPatchPath;

    protected override void OnLoadingSettings(JsonElement root)
    {
        if (root.TryGetProperty("ap_patch_path", out var el)) ApPatchPath = el.GetString();
    }

    /// Set an explicit patch override (rare for FF4FE) and persist it.
    public void SetExplicitPatch(string path) { ApPatchPath = path; SaveSettings(); }

    /// ROM safety net. FF4FE has no launcher-appliable patch carrying an expected
    /// MD5, so the only requirement we can surface is "an FF4FE ROM is present" —
    /// the player supplies the built .sfc themselves. A future explicit override
    /// container (which the AP generator does not emit) would still demand its base
    /// MD5 if one were set.
    public override RomRequirement? GetUnmetRomRequirement()
    {
        var patch = SnesApPatchHelper.ResolvePatch(
            PatchExt, ApPatchPath, GetSeedName?.Invoke(), CurrentSlotName, out _);
        string? wantMd5 = patch != null
            ? SnesApPatchHelper.ReadManifestField(patch, "base_checksum") : null;
        bool haveRom = RomPath != null && File.Exists(RomPath);

        if (wantMd5 == null)
            return haveRom ? null
                 : new RomRequirement("Final Fantasy IV: Free Enterprise", "SNES",
                       "your Archipelago-built Final Fantasy IV: Free Enterprise ROM " +
                       "(build it with the Archipelago client from your own FF4 (USA) " +
                       "cartridge + the .apff4fe)",
                       RequiredMd5: null, WrongVersionPresent: false, BuildRomFilter());

        if (haveRom && ComputeMd5(RomPath!).Equals(wantMd5, StringComparison.OrdinalIgnoreCase))
            return null;

        return new RomRequirement("Final Fantasy IV: Free Enterprise", "SNES",
            "Final Fantasy II (USA) (Rev A) — the exact FF4 dump this patch was built against",
            wantMd5, WrongVersionPresent: haveRom, BuildRomFilter());
    }

    // ── Session ROM ───────────────────────────────────────────────────────────
    //
    // The normal FF4FE path applies NO patch — the player's library ROM IS the
    // already-built .sfc the Archipelago client produced via the Free Enterprise
    // randomizer, so we return null and the base class launches it directly. Only an
    // explicit override container (not emitted by the AP generator, and unappliable
    // without the FE engine) would trigger SnesApPatchHelper; that branch is kept for
    // parity with the other emulated games but is inert for standard FF4FE seeds.

    protected override async Task<string?> PrepareSessionRomAsync(
        ApSession session, CancellationToken ct)
    {
        string? patch = SnesApPatchHelper.ResolvePatch(
            PatchExt, ApPatchPath, GetSeedName?.Invoke(), CurrentSlotName, out string how);
        if (patch == null)
        {
            // Standard FF4FE: no launcher-appliable patch exists. The library ROM is
            // the .sfc the player built with the Archipelago client (Free Enterprise).
            SessionRomNote =
                "[Final Fantasy IV: Free Enterprise] FF4 Free Enterprise is built by " +
                "the Archipelago client's own Free Enterprise randomizer (not a patch " +
                "the launcher applies) — launching your ROM directly. Make sure this " +
                "ROM is the .sfc you built from your FF4 (USA) cartridge + the .apff4fe " +
                "file, not the unmodified cartridge dump.";
            return null;
        }

        // Optional explicit-override path (kept for parity; FF4FE never emits an
        // applieable .apff4fe — its patch is consumed by the FE build step instead).
        var res = await SnesApPatchHelper.ApplyAsync(
            "Final Fantasy IV: Free Enterprise", patch, how, RomPath!,
            RomLibraryDirectory, ".sfc", ct);
        SessionRomNote = res.Note;
        if (res.OutRom != null) RegisterSeed(res.OutRom, patch);
        return res.OutRom;
    }

    /// Record a produced/reused patched ROM in the seed library. Never throws.
    /// (Only reached on the optional explicit-override path — standard FF4FE seeds
    /// launch the AP-built ROM directly and never get here.)
    private void RegisterSeed(string outRom, string patch)
    {
        try
        {
            SeedLibraryStore.Instance.Register(new SeedEntry
            {
                GameId         = GameId,
                PatchedRomPath = outRom,
                PatchPath      = patch,
                SeedName       = SnesApPatchHelper.ParseSeedFromPatch(patch),
                SlotName       = CurrentSlotName ?? "",
                CreatedUtc     = DateTimeOffset.UtcNow,
            });
        }
        catch { /* registry is non-essential to launching */ }
    }
}
