using System;
using System.Collections.Generic;
using System.IO;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using LauncherV2.Core;

namespace LauncherV2.Plugins.Emulated.Games;

// ═══════════════════════════════════════════════════════════════════════════════
// LegendOfZeldaPlugin — Archipelago integration for The Legend of Zelda (NES, NA
// 1.0), on the proven BizHawk Lua-pipe bridge.
//
// STATUS: location DETECTION + goal are REAL and SOURCE-DERIVED (the 155-location
// table in tloz.lua was GENERATED by parsing worlds/tloz/Locations.py —
// location_table = major_locations + all_level_locations + shop_locations, +base_id
// 7000; the status-block/bit math, the "LOZ" PRG-ROM signature, the game_mode==5
// gate and the game_mode==19 victory are replicated exactly from the world's
// BizHawk client and cross-validated against the merged main-branch legacy
// connector data/lua/connector_tloz.lua, and mock-verified through MoonSharp
// against synthetic NES memory). items_handling = 0b101 — the AP SERVER drives item
// delivery; the reference client writes received items into NES RAM through a
// guarded 16-bit-counter handshake (RAM 0x0677/0x067B) + per-item guarded writes.
// That guarded multi-write path is the documented deferred piece (tloz.lua
// receive_item is a no-op) until it can be confirmed in-emulator, rather than
// shipped unverified — a wrong RAM write corrupts the save / desyncs the counter.
// Checks + goal flow regardless.
//
// AP PATCH (.aptloz → .nes): an APDeltaPatch container (z1_base_patch.bsdiff4 over
// the full base ROM), applied via the shared SnesApPatchHelper (resolve the seed's
// patch, validate the base ROM via the manifest base_checksum, run the
// manifest-driven apply_appatch.py on a library COPY — the original is never
// modified). Base ROM: the user's own The Legend of Zelda (U) (PRG0) NES cartridge
// dump, identified by CONTENT (size + the exact NA 1.0 MD5) — never by filename
// (§11).
//
// SOURCE NOTE: worlds/tloz on AP main (world_version 1.0.0) shipped with a LEGACY
// custom client; the clean fixed-RAM-block BizHawkClient (worlds/tloz/Client.py) is
// the open v2 PR #4832 (branch The-Legend-of-Zelda-AP), not yet merged at time of
// writing. Both agree on every address/bit this integration uses; the BizHawkClient
// form is the one modelled, as the direct equivalent of the ff1/mm2 BizHawk clients.
// ═══════════════════════════════════════════════════════════════════════════════

public sealed class LegendOfZeldaPlugin : EmulatorPlugin
{
    public LegendOfZeldaPlugin() => LoadSettings();

    // ── Identity ──────────────────────────────────────────────────────────────

    public override string GameId      => "tloz";
    public override string DisplayName => "The Legend of Zelda";
    public override string Subtitle    => "NES · Emulated";
    public override string ApWorldName => "The Legend of Zelda";

    public override string Description =>
        "The Legend of Zelda, the 1986 NES original that founded the series. In the " +
        "Archipelago randomizer every overworld secret, dungeon item, key, shop slot " +
        "and heart container is shuffled into the multiworld pool across all nine " +
        "labyrinths and the overworld. Gather the eight Triforce fragments, enter " +
        "Death Mountain, and defeat Ganon to rescue Zelda and complete your goal. " +
        "Bring your own The Legend of Zelda (U) (PRG0) NES ROM.";

    public override string ThemeAccentColor => "#1F8A3B";   // Zelda overworld green

    // ── Emulator specifics ────────────────────────────────────────────────────

    protected override string RomSystem     => "NES";

    // §14: NES emulators — BizHawk is the tloz community's verified client target
    // (the world's client is a BizHawkClient); Mesen is the NES alternative (shown
    // per its bridge state in the dropdown). mGBA is NOT offered — it is a GB/GBA
    // emulator and cannot host NES.
    protected override IReadOnlyList<string> SupportedEmulatorIds =>
        new[] { "bizhawk", "mesen" };
    protected override string LuaScriptName => "bizhawk_ap_connector.lua";
    protected override string LuaModuleName => "tloz";

    /// tloz.lua reports checks + goal (table generated from the apworld; status-block
    /// bit math from the world's BizHawk client; mock-verified). Remote-item delivery
    /// is the documented deferred piece (items_handling = 0b101, server-driven guarded
    /// RAM writes).
    public override bool ChecksImplemented => true;

    /// The vanilla NES cartridge dump the randomizer is built for, by CONTENT —
    /// never by filename (§11). worlds/tloz/Rom.py pins the NA (1.0) release: MD5
    /// 337bd6f1a1163df31bf2633665589ab0 (The Legend of Zelda (U) (PRG0) [!]). The
    /// standard iNES dump is a 16-byte header + 128 KB PRG + 8 KB CHR = 131,088
    /// bytes. The world hashes the file as read (read_snes_rom only strips a 512-byte
    /// copier header, which this size does not carry), so the whole-file MD5 IS the
    /// manifest base_checksum — pinned here as the exact, name-independent detector.
    /// The authoritative gate is the patch's own base_checksum (validated by
    /// apply_appatch.py before any byte is written), and tloz.lua's "LOZ" PRG-ROM
    /// signature confirms a real TLoZ ROM at launch.
    protected override IReadOnlyList<RomIdentity> AcceptableBaseRoms => new[]
    {
        new RomIdentity(131_088, "337bd6f1a1163df31bf2633665589ab0",
                        "The Legend of Zelda (U) (PRG0) [!] — NES cartridge dump (NA 1.0)"),
    };

    // ── AP patch ────────────────────────────────────────────────────────────────

    private const string PatchExt = ".aptloz";

    /// Explicit .aptloz chosen by the user (Settings / drag-drop). Null = auto.
    public string? ApPatchPath { get; private set; }

    protected override void OnSavingSettings(IDictionary<string, object?> bag)
        => bag["ap_patch_path"] = ApPatchPath;

    protected override void OnLoadingSettings(JsonElement root)
    {
        if (root.TryGetProperty("ap_patch_path", out var el)) ApPatchPath = el.GetString();
    }

    /// Set the explicit AP patch (drag-and-drop / room-link import) and persist it.
    public void SetExplicitPatch(string path) { ApPatchPath = path; SaveSettings(); }

    /// ROM safety net: the resolved patch tells us the EXACT base ROM the manifest
    /// was generated against (base_checksum). TLoZ's APDeltaPatch is a bsdiff over
    /// the full base ROM, so its base_checksum is the whole-file MD5 — the same one
    /// we pin in AcceptableBaseRoms — which we can compare directly against ours.
    /// Demand that specific dump when ours is missing or the wrong one.
    public override RomRequirement? GetUnmetRomRequirement()
    {
        var patch = SnesApPatchHelper.ResolvePatch(
            PatchExt, ApPatchPath, GetSeedName?.Invoke(), CurrentSlotName, out _);
        string? wantMd5 = patch != null
            ? SnesApPatchHelper.ReadManifestField(patch, "base_checksum") : null;
        bool haveRom = RomPath != null && File.Exists(RomPath);

        if (wantMd5 == null)
            return haveRom ? null
                 : new RomRequirement("The Legend of Zelda", "NES",
                       "The Legend of Zelda (U) (PRG0) — your original NES cartridge dump",
                       RequiredMd5: "337bd6f1a1163df31bf2633665589ab0",
                       WrongVersionPresent: false, BuildRomFilter());

        if (haveRom && ComputeMd5(RomPath!).Equals(wantMd5, StringComparison.OrdinalIgnoreCase))
            return null;

        return new RomRequirement("The Legend of Zelda", "NES",
            "The Legend of Zelda (U) (PRG0) — the exact ROM this patch was generated against",
            wantMd5, WrongVersionPresent: haveRom, BuildRomFilter());
    }

    // ── Session ROM: apply the .aptloz to a library copy ───────────────────────

    protected override async Task<string?> PrepareSessionRomAsync(
        ApSession session, CancellationToken ct)
    {
        string? patch = SnesApPatchHelper.ResolvePatch(
            PatchExt, ApPatchPath, GetSeedName?.Invoke(), CurrentSlotName, out string how);
        if (patch == null)
        {
            SessionRomNote =
                "[The Legend of Zelda] No AP patch (.aptloz) found — launching the " +
                "vanilla ROM. Generate the multiworld, then pick the patch in Settings " +
                "(or drop it under " + SnesApPatchHelper.ApOutputDirectory + ").";
            return null;
        }

        var res = await SnesApPatchHelper.ApplyAsync(
            "The Legend of Zelda", patch, how, RomPath!,
            RomLibraryDirectory, ".nes", ct);
        SessionRomNote = res.Note;
        if (res.OutRom != null) RegisterSeed(res.OutRom, patch);
        return res.OutRom;
    }

    /// Record a produced/reused patched ROM in the seed library. Never throws.
    private void RegisterSeed(string outRom, string patch)
    {
        try
        {
            SeedLibraryStore.Instance.Register(new SeedEntry
            {
                GameId         = GameId,
                PatchedRomPath = outRom,
                PatchPath      = patch,
                SeedName       = SnesApPatchHelper.ParseSeedFromPatch(patch),
                SlotName       = CurrentSlotName ?? "",
                CreatedUtc     = DateTimeOffset.UtcNow,
            });
        }
        catch { /* registry is non-essential to launching */ }
    }
}
