using System;
using System.Collections.Generic;
using System.IO;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using LauncherV2.Core;

namespace LauncherV2.Plugins.Emulated.Games;

// ═══════════════════════════════════════════════════════════════════════════════
// LufiaIIPlugin — Archipelago integration for Lufia II: Rise of the Sinistrals —
// Ancient Cave mode (SNES), on the proven BizHawk Lua-pipe bridge (and snes9x).
//
// STATUS: location DETECTION + goal are REAL and SOURCE-DERIVED (lufia2ac.lua
// mirrors worlds/lufia2ac/Client.py's counter-based TX scan + the goal record;
// the location-id offsets — blue-chest count 113, Boss 0x01C2, Iris 0x039C+ —
// were GENERATED by parsing Locations.py/__init__.py; mock-verified through
// MoonSharp against synthetic CARTRAM). items_handling = 0b111 (FULLY REMOTE) —
// the game grants NOTHING locally; every received item is delivered through the
// client's RX cartridge-SRAM handshake. That write path is transcribed exactly
// in lufia2ac.lua but GATED (RECEIVE_ITEMS_VERIFIED = false) until it can be
// confirmed in-emulator, so item delivery is the documented deferred piece (it
// records but never performs an unverified SRAM write). Checks and goal flow now.
//
// AP PATCH (.apl2ac → .sfc): L2ACDeltaPatch is an APDeltaPatch — the same
// bsdiff4-based ZIP container family as A Link to the Past's .aplttp / Pokémon
// Emerald's .apemerald — applied via the shared SnesApPatchHelper (resolve the
// seed's patch, validate the base ROM MD5, run apply_appatch.py on a library
// COPY; the user's original ROM is never modified). NOT an external-randomizer
// world, so the standard patch flow applies.
//
// Base ROM: the user's own vanilla "Lufia II - Rise of the Sinistrals (USA)"
// cartridge dump (4 MB, headerless), identified by CONTENT (size + MD5) — never
// by filename (§11). The patch container's base_checksum re-validates the exact
// dump before anything is written.
// ═══════════════════════════════════════════════════════════════════════════════

public sealed class LufiaIIPlugin : EmulatorPlugin
{
    public LufiaIIPlugin() => LoadSettings();

    // ── Identity ──────────────────────────────────────────────────────────────

    public override string GameId      => "lufia2ac";
    public override string DisplayName => "Lufia II";
    public override string Subtitle    => "SNES · Emulated";

    // The apworld's `game:` string (worlds/lufia2ac/Client.py + __init__.py).
    public override string ApWorldName => "Lufia II Ancient Cave";

    public override string Description =>
        "Lufia II: Rise of the Sinistrals hides a full roguelike — the Ancient Cave — " +
        "inside the SNES RPG. In the Archipelago randomizer you descend 99 ever-harder " +
        "floors, and the blue-chest treasures, Iris relics, capsule monsters and party " +
        "members join the multiworld pool. Reach your goal floor, defeat the boss, or " +
        "hunt the Iris treasures to win.";

    // ── Visual identity ───────────────────────────────────────────────────────

    public override string ThemeAccentColor => "#2E6FB0";   // Lufia menu blue

    // ── Emulator specifics ────────────────────────────────────────────────────

    protected override string RomSystem     => "SNES";
    protected override string LuaScriptName => "bizhawk_ap_connector.lua";
    protected override string LuaModuleName => "lufia2ac";

    // §14: the SNES emulators this world is played on. BizHawk is verified; the
    // §14 Discord ask was "SNES: BizHawk or snes9x", so snes9x is the headline
    // alternative, with Mesen a third option (each shown per its bridge state in
    // the dropdown).
    protected override IReadOnlyList<string> SupportedEmulatorIds =>
        new[] { "bizhawk", "snes9x", "mesen" };

    /// lufia2ac.lua reports checks + goal (counter scan + goal record generated
    /// from the apworld; mock-verified). Remote-item delivery is the documented
    /// deferred piece (gated SRAM write), so this is true for checks/goal.
    public override bool ChecksImplemented => true;

    /// The Lufia II datapackage checksum is announced by the server in RoomInfo,
    /// not embedded as a constant in the apworld; left null. The launcher's
    /// "apworld updated" warning is simply not raised for this game until a live
    /// RoomInfo checksum is captured and pinned here.
    public string? BuiltAgainstDataPackageChecksum => null;

    /// The vanilla Lufia II cartridge dump the randomizer is built for, by CONTENT
    /// (4 MB headerless + MD5), never by filename. This is the long-standing
    /// community-known US hash every AP Lufia II generator validates against
    /// (worlds/lufia2ac/Rom.py L2USHASH); apply_appatch.py independently re-checks
    /// the patch container's own base_checksum before patching, so this only drives
    /// the launcher's "wrong version" hint. A headered copy (4 MB + 512-byte SMC
    /// header) has a different size+MD5 and is correctly rejected here.
    protected override IReadOnlyList<RomIdentity> AcceptableBaseRoms => new[]
    {
        new RomIdentity(4 * 1024 * 1024,                     // 4,194,304 bytes
                        "6efc477d6203ed2b3b9133c1cd9e9c5d",
                        "Lufia II - Rise of the Sinistrals (USA)"),
    };

    // ── AP patch ────────────────────────────────────────────────────────────────

    private const string PatchExt  = ".apl2ac";
    private const string ResultExt = ".sfc";

    /// Explicit .apl2ac chosen by the user (Settings / drag-drop). Null = auto.
    public string? ApPatchPath { get; private set; }

    protected override void OnSavingSettings(IDictionary<string, object?> bag)
        => bag["ap_patch_path"] = ApPatchPath;

    protected override void OnLoadingSettings(JsonElement root)
    {
        if (root.TryGetProperty("ap_patch_path", out var el))
            ApPatchPath = el.GetString();
    }

    private string? ResolvePatchPath(out string how)
        => SnesApPatchHelper.ResolvePatch(
            PatchExt, ApPatchPath, GetSeedName?.Invoke(), CurrentSlotName, out how);

    /// Set the explicit AP patch (drag-and-drop / room-link import) and persist it.
    public void SetExplicitPatch(string path) { ApPatchPath = path; SaveSettings(); }

    /// ROM safety net: the resolved patch tells us the EXACT vanilla ROM MD5 it
    /// needs — demand that specific dump when ours is missing or the wrong one.
    public override RomRequirement? GetUnmetRomRequirement()
    {
        string? wantMd5 = null;
        var patch = ResolvePatchPath(out _);
        if (patch != null) wantMd5 = SnesApPatchHelper.ReadManifestField(patch, "base_checksum");

        bool haveRom = RomPath != null && File.Exists(RomPath);

        if (wantMd5 == null)
            return haveRom ? null
                 : new RomRequirement("Lufia II", "SNES",
                       "Lufia II - Rise of the Sinistrals (USA)",
                       RequiredMd5: null, WrongVersionPresent: false, BuildRomFilter());

        if (haveRom && ComputeMd5(RomPath!).Equals(wantMd5, StringComparison.OrdinalIgnoreCase))
            return null;

        return new RomRequirement(
            "Lufia II", "SNES",
            "Lufia II - Rise of the Sinistrals (USA) — your original vanilla cartridge dump",
            wantMd5, WrongVersionPresent: haveRom, BuildRomFilter());
    }

    // ── Session ROM: apply the .apl2ac to a library copy ──────────────────────

    protected override async Task<string?> PrepareSessionRomAsync(
        ApSession session, CancellationToken ct)
    {
        string? patch = ResolvePatchPath(out string how);
        if (patch == null)
        {
            SessionRomNote =
                "[Lufia II] No AP patch (.apl2ac) found — launching the vanilla ROM. " +
                "Checks and item delivery CANNOT WORK on a vanilla ROM: generate the " +
                "multiworld, then pick the patch in Settings → Lufia II (or drop it " +
                "under " + SnesApPatchHelper.ApOutputDirectory + ").";
            return null;
        }

        if (RomPath == null || !File.Exists(RomPath))
        {
            SessionRomNote =
                "[Lufia II] No base ROM set — import your vanilla US Lufia II cartridge " +
                "dump in Settings, then relaunch.";
            return null;
        }

        var result = await SnesApPatchHelper.ApplyAsync(
            "Lufia II", patch, how, RomPath!, RomLibraryDirectory, ResultExt, ct);
        SessionRomNote = result.Note;
        if (result.OutRom != null) RegisterSeed(result.OutRom, patch);
        return result.OutRom;
    }

    /// Record a produced/reused patched ROM in the seed library. Never throws.
    private void RegisterSeed(string outRom, string patch)
    {
        try
        {
            SeedLibraryStore.Instance.Register(new SeedEntry
            {
                GameId         = GameId,
                PatchedRomPath = outRom,
                PatchPath      = patch,
                SeedName       = SnesApPatchHelper.ParseSeedFromPatch(patch),
                SlotName       = CurrentSlotName ?? "",
                CreatedUtc     = DateTimeOffset.UtcNow,
            });
        }
        catch { /* registry is non-essential to launching */ }
    }
}
