using System;
using System.Collections.Generic;
using System.IO;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
using LauncherV2.Core;

namespace LauncherV2.Plugins.Emulated.Games;

// ═══════════════════════════════════════════════════════════════════════════════
// MegaManX3Plugin — Archipelago integration for Mega Man X3 (SNES), on the proven
// BizHawk Lua-pipe bridge (and the snes9x NWA backend).
//
// COMMUNITY WORLD. The apworld is lx5's "Mega Man X3" (TheLX5/Archipelago, branch
// `mmx3-main`, world_version 1.5.2) — NOT in AP-main. game string "Mega Man X3",
// patch_suffix ".apmmx3", items_handling 0b111.
// Source: https://github.com/TheLX5/Archipelago  (worlds/mmx3)
//
// STATUS: location DETECTION + goal are REAL and SOURCE-DERIVED. The 121-location
// table in "Mega Man X3.lua" was GENERATED by JOINING worlds/mmx3/Locations.py
// (all_locations: name → AP id) with worlds/mmx3/Levels.py (location_id_to_level_id:
// name → [level_id, internal_id, data_bit]) — 121/121 names matched, 0 mismatches.
// The per-internal_id decode (heart-tank bit = 1<<(level_id-1); sub-tank/upgrade
// masks; ride/chip masks; bit/byte/vile nibbles; >=0x300 medal, >=0x200 boss,
// >=0x100 pickup arrays), the "MMX3" ROM-header identity, the live 0xDEAD
// validation gate and the Victory-flag goal are mirrored from Client.py
// game_watcher. Mock-verified through MoonSharp against synthetic WRAM/CARTROM.
// items_handling = 0b111 (FULL remote) — the mmx3 client owns ALL item delivery
// via an intricate, heavily-state-gated set of WRAM writes (weapon/upgrade/tank/
// ride-armor/chip/boss-access arrays + a recv-index handshake + arsenal save/load +
// EnergyLink/DeathLink/HP-trade), so there is no game-self-grant fallback; that
// delivery path is deferred ("Mega Man X3.lua" receive_item is a no-op) until it
// can be confirmed in-emulator, rather than shipped unverified. Checks + goal work
// regardless.
//
// THE PATCH (.apmmx3) is MMX3ProcedurePatch — an APProcedurePatch whose procedure is
// [("relocate_graphics", …), ("apply_tokens", ["token_patch.bin"]),
//  ("apply_bsdiff4", ["mmx3_basepatch.bsdiff4"])], result ".sfc",
// hash = [HASH_US, HASH_LEGACY]. That is the SAME container family as A Link to the
// Past's .aplttp and Mega Man X's .apmmx (token + bsdiff4 + a manifest), so the
// shared SnesApPatchHelper + Plugins/Scripts/apply_appatch.py apply it via the
// manifest-declared procedure: resolve the seed's patch, validate the base ROM MD5
// (against the container's own base_checksum), run the patcher on a library COPY —
// the user's original ROM is never modified.
// Base ROM: the user's own Mega Man X3 (USA) cartridge dump (2 MB / 16 Mbit),
// identified by CONTENT (size + MD5) — never by filename (§11). The Legacy
// Collection ROM extract (same 2 MB, different MD5) is also accepted.
// ═══════════════════════════════════════════════════════════════════════════════

public sealed class MegaManX3Plugin : EmulatorPlugin
{
    public MegaManX3Plugin() => LoadSettings();

    // ── Identity ──────────────────────────────────────────────────────────────

    public override string GameId      => "mega_man_x3";
    public override string DisplayName => "Mega Man X3";
    public override string Subtitle    => "SNES · Emulated";
    public override string ApWorldName => "Mega Man X3";

    public override string Description =>
        "Mega Man X3 is the 1995 SNES finale of the 16-bit X trilogy. In the " +
        "Archipelago randomizer the eight Maverick boss clears and stage medals, " +
        "Heart Tanks, Sub Tanks, the four armor upgrade capsules, ride armor chips, " +
        "Z-Saber and (optionally) every stage pickup join the multiworld pool, with " +
        "shuffled stage access and Dr. Doppler's Lab / Vile-stage unlock conditions. " +
        "Fight through the Mavericks and defeat Dr. Doppler to complete your goal. " +
        "Bring your own Mega Man X3 (USA) SNES ROM.";

    // ── Visual identity ───────────────────────────────────────────────────────

    public override string ThemeAccentColor => "#2EA043";   // X3 armor green

    // ── Emulator specifics ────────────────────────────────────────────────────

    protected override string RomSystem     => "SNES";
    protected override string LuaScriptName => "bizhawk_ap_connector.lua";
    protected override string LuaModuleName => "Mega Man X3";

    // §14: the SNES emulators this world is played on. BizHawk is verified; the
    // §14 ask was "SNES: BizHawk or snes9x", so snes9x is the headline alternative,
    // with Mesen as a third option (each shown per its bridge state in the dropdown).
    protected override IReadOnlyList<string> SupportedEmulatorIds =>
        new[] { "bizhawk", "snes9x", "mesen" };

    private const string PatchExt  = ".apmmx3";
    private const string ResultExt = ".sfc";

    /// The vanilla Mega Man X3 cartridge dumps the randomizer is built for,
    /// identified by CONTENT (2 MB + MD5), never by filename. These are the
    /// hashes worlds/mmx3/Rom.py validates against (HASH_US = the No-Intro
    /// "Mega Man X3 (USA)"; HASH_LEGACY = the Legacy Collection ROM extract).
    /// apply_appatch.py independently re-checks the patch container's own
    /// base_checksum before patching, so this only drives the launcher's
    /// "wrong version" hint.
    protected override IReadOnlyList<RomIdentity> AcceptableBaseRoms
        => new[]
        {
            new RomIdentity(2_097_152,                            // 2 MB (16 Mbit)
                            "cfe8c11f0dce19e4fa5f3fd75775e47c",
                            "Mega Man X3 (USA)"),
            new RomIdentity(2_097_152,
                            "ff683b75e75e9b59f0c713c7512a016b",
                            "Mega Man X3 (Legacy Collection ROM)"),
        };

    /// "Mega Man X3.lua" mirrors the official SNIClient game_watcher: a per-
    /// internal_id scan of the cleared_levels / defeated_bosses / collected_*
    /// WRAM blocks (gated by the live 0xDEAD validation word, the "MMX3" header
    /// and the CARTROM pickupsanity flag) → AP location ids, plus the Victory-flag
    /// goal. The table is GENERATED from the apworld source and mock-verified; a
    /// real playthrough confirms it live.
    public override bool ChecksImplemented => true;

    /// The Mega Man X3 datapackage checksum is announced by the server in RoomInfo,
    /// not embedded as a constant in the apworld; left null. The launcher's
    /// "apworld updated" warning is simply not raised for this game until a live
    /// RoomInfo checksum is captured and pinned here.
    public string? BuiltAgainstDataPackageChecksum => null;

    // ── AP patch settings ─────────────────────────────────────────────────────

    /// Explicit .apmmx3 chosen by the user (Settings / drag-drop). Null = auto.
    public string? ApPatchPath { get; private set; }

    protected override void OnSavingSettings(IDictionary<string, object?> bag)
        => bag["ap_patch_path"] = ApPatchPath;

    protected override void OnLoadingSettings(JsonElement root)
    {
        if (root.TryGetProperty("ap_patch_path", out var el))
            ApPatchPath = el.GetString();
    }

    private string? ResolvePatchPath(out string how)
        => SnesApPatchHelper.ResolvePatch(
            PatchExt, ApPatchPath, GetSeedName?.Invoke(), CurrentSlotName, out how);

    /// Set the explicit AP patch (drag-and-drop / room-link import) and persist it.
    public void SetExplicitPatch(string path) { ApPatchPath = path; SaveSettings(); }

    /// ROM safety net: when a patch is known, demand exactly its base ROM
    /// (base_checksum) so the launcher can ask the player by fingerprint instead
    /// of silently patching the wrong dump.
    public override RomRequirement? GetUnmetRomRequirement()
    {
        string? wantMd5 = null;
        var patch = ResolvePatchPath(out _);
        if (patch != null) wantMd5 = SnesApPatchHelper.ReadManifestField(patch, "base_checksum");

        bool haveRom = RomPath != null && File.Exists(RomPath);

        if (wantMd5 == null)
            return haveRom ? null
                 : new RomRequirement("Mega Man X3", "SNES",
                       "Mega Man X3 (USA)",
                       RequiredMd5: null, WrongVersionPresent: false, BuildRomFilter());

        if (haveRom && ComputeMd5(RomPath!).Equals(wantMd5, StringComparison.OrdinalIgnoreCase))
            return null;

        return new RomRequirement(
            "Mega Man X3", "SNES",
            "Mega Man X3 (USA) — the original vanilla cartridge dump",
            wantMd5, WrongVersionPresent: haveRom, BuildRomFilter());
    }

    private void RegisterSeed(string outRom, string patch)
    {
        try
        {
            SeedLibraryStore.Instance.Register(new SeedEntry
            {
                GameId         = GameId,
                PatchedRomPath = outRom,
                PatchPath      = patch,
                SeedName       = SnesApPatchHelper.ParseSeedFromPatch(patch),
                SlotName       = CurrentSlotName ?? "",
                CreatedUtc     = DateTimeOffset.UtcNow,
            });
        }
        catch { /* registry is non-essential to launching */ }
    }

    // ── Session ROM: apply the .apmmx3 to a library copy ──────────────────────

    protected override async Task<string?> PrepareSessionRomAsync(
        ApSession session, CancellationToken ct)
    {
        string? patch = ResolvePatchPath(out string how);
        if (patch == null)
        {
            SessionRomNote =
                "[Mega Man X3] No AP patch (.apmmx3) found — launching the vanilla " +
                "ROM. Checks CANNOT WORK on a vanilla ROM: generate the multiworld, " +
                "then pick the patch in Settings → Mega Man X3 (or drop it under " +
                SnesApPatchHelper.ApOutputDirectory + ").";
            return null;
        }

        if (RomPath == null || !File.Exists(RomPath))
        {
            SessionRomNote =
                "[Mega Man X3] No base ROM set — import your vanilla Mega Man X3 (USA) " +
                "cartridge dump in Settings, then relaunch.";
            return null;
        }

        var result = await SnesApPatchHelper.ApplyAsync(
            "Mega Man X3", patch, how, RomPath!, RomLibraryDirectory, ResultExt, ct);
        SessionRomNote = result.Note;
        if (result.OutRom != null) RegisterSeed(result.OutRom, patch);
        return result.OutRom;
    }

    // ── Settings panel: base panel + AP patch section ─────────────────────────

    public override UIElement? CreateSettingsPanel()
    {
        var basePanel = base.CreateSettingsPanel();
        if (basePanel is not StackPanel panel) return basePanel;

        var muted = new SolidColorBrush(Color.FromRgb(0x72, 0x7A, 0x99));
        var fg    = new SolidColorBrush(Color.FromRgb(0xCC, 0xD0, 0xE0));

        panel.Children.Add(new TextBlock
        {
            Text = "ARCHIPELAGO PATCH", FontSize = 10, FontWeight = FontWeights.SemiBold,
            Foreground = muted, Margin = new Thickness(0, 20, 0, 8),
        });
        panel.Children.Add(new TextBlock
        {
            Text = "The multiworld generator produces a .apmmx3 patch for your slot. " +
                   "The launcher applies it to a COPY of your ROM at launch (your file " +
                   "is never modified). Leave empty to auto-use the newest patch from " +
                   "the Archipelago output folder.",
            FontSize = 11, Foreground = muted, TextWrapping = TextWrapping.Wrap,
            Margin = new Thickness(0, 0, 0, 8),
        });

        var patchRow = new DockPanel { Margin = new Thickness(0, 0, 0, 4) };
        var patchBox = new TextBox
        {
            Text = ApPatchPath ?? "", Margin = new Thickness(0, 0, 8, 0),
            IsReadOnly = true, FontSize = 12,
            Background  = new SolidColorBrush(Color.FromRgb(0x0C, 0x10, 0x20)),
            Foreground  = fg,
            BorderBrush = new SolidColorBrush(Color.FromRgb(0x1E, 0x22, 0x33)),
        };
        var clearBtn = new Button
        {
            Content = "Auto", Width = 50, Margin = new Thickness(0, 0, 8, 0),
            Padding = new Thickness(0, 6, 0, 6),
            Background  = new SolidColorBrush(Color.FromRgb(0x1A, 0x1E, 0x30)),
            Foreground  = fg,
            BorderBrush = new SolidColorBrush(Color.FromRgb(0x2A, 0x30, 0x50)),
            ToolTip = "Clear the explicit pick — auto-detect the newest generated patch.",
        };
        var pickBtn = new Button
        {
            Content = "Select AP patch...", Width = 130, Padding = new Thickness(0, 6, 0, 6),
            Background  = new SolidColorBrush(Color.FromRgb(0x1A, 0x1E, 0x30)),
            Foreground  = fg,
            BorderBrush = new SolidColorBrush(Color.FromRgb(0x2A, 0x30, 0x50)),
        };

        var autoNote = new TextBlock
        {
            FontSize = 10, Foreground = muted, TextWrapping = TextWrapping.Wrap,
            Margin = new Thickness(0, 4, 0, 0),
        };
        void RefreshAutoNote()
        {
            string? auto = ResolvePatchPath(out string how);
            autoNote.Text = ApPatchPath != null
                ? "Explicit patch selected — auto-detection off."
                : auto != null
                    ? $"Auto-detected ({how}): {auto}"
                    : $"No .apmmx3 found under {SnesApPatchHelper.ApOutputDirectory} yet.";
        }
        RefreshAutoNote();

        pickBtn.Click += (_, _) =>
        {
            var dlg = new Microsoft.Win32.OpenFileDialog
            {
                Title  = "Select Archipelago patch for Mega Man X3",
                Filter = "AP MMX3 patch (*.apmmx3)|*.apmmx3|All files (*.*)|*.*",
            };
            if (Directory.Exists(SnesApPatchHelper.ApOutputDirectory))
                dlg.InitialDirectory = SnesApPatchHelper.ApOutputDirectory;
            if (dlg.ShowDialog() != true) return;
            ApPatchPath   = dlg.FileName;
            patchBox.Text = dlg.FileName;
            SaveSettings();
            RefreshAutoNote();
        };
        clearBtn.Click += (_, _) =>
        {
            ApPatchPath   = null;
            patchBox.Text = "";
            SaveSettings();
            RefreshAutoNote();
        };

        DockPanel.SetDock(pickBtn,  Dock.Right);
        DockPanel.SetDock(clearBtn, Dock.Right);
        patchRow.Children.Add(pickBtn);
        patchRow.Children.Add(clearBtn);
        patchRow.Children.Add(patchBox);
        panel.Children.Add(patchRow);
        panel.Children.Add(autoNote);

        return panel;
    }
}
