using System;
using System.Collections.Generic;
using System.IO;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using LauncherV2.Core;

namespace LauncherV2.Plugins.Emulated.Games;

// ═══════════════════════════════════════════════════════════════════════════════
// PokemonRBPlugin — Archipelago integration for Pokémon Red & Blue (Game Boy), on
// the proven BizHawk Lua-pipe bridge. The pokemon_rb apworld is one world that
// covers BOTH cartridges, so this plugin accepts either base ROM (Red OR Blue)
// and either patch extension (.apred / .apblue).
//
// STATUS: location DETECTION + goal are REAL and SOURCE-DERIVED. The 709-location
// table in pokemon_rb.lua was GENERATED by executing the official
// worlds/pokemon_rb/locations.py and replicating client.py's exact
// location_map / location_bytes_bits build (flag → byte/bit math, the five WRAM
// flag arrays, the two "list" pair-locations), and the in-game/not-crashed gate +
// the EventFlag[280]&1 victory goal are taken verbatim from client.game_watcher.
// Mock-verified through MoonSharp against synthetic GB memory. items_handling =
// 0b001 — the server sends only THIS slot's own items and the PATCHED GAME grants
// its locally-found items itself, so a SOLO seed plays fully and every check is
// reported in a multiworld. Delivering REMOTE items is the client's guarded
// APItem-byte WRAM write; it is deferred (pokemon_rb.lua receive_item is a no-op)
// until it can be confirmed in-emulator, rather than shipped unverified.
//
// AP PATCH (.apred / .apblue → .gb): a standard APProcedurePatch container
// (bsdiff4 + token_data), applied via the shared SnesApPatchHelper (resolve the
// seed's patch, validate the base ROM MD5 from the manifest base_checksum, run
// apply_appatch.py on a library COPY — the original is never modified). Base ROM:
// the user's own Pokémon Red OR Blue (USA/Europe) cartridge dump (1 MB), identified
// by CONTENT (size + MD5) — never by filename (§11).
// ═══════════════════════════════════════════════════════════════════════════════

public sealed class PokemonRBPlugin : EmulatorPlugin
{
    public PokemonRBPlugin() => LoadSettings();

    // ── Identity ──────────────────────────────────────────────────────────────

    public override string GameId      => "pokemon_rb";
    public override string DisplayName => "Pokémon Red & Blue";
    public override string Subtitle    => "GB · Emulated";
    public override string ApWorldName => "Pokemon Red and Blue";

    public override string Description =>
        "Pokémon Red & Blue are the Game Boy originals that launched the series. In " +
        "the Archipelago randomizer, badges, key items, TMs, HMs and overworld items " +
        "across Kanto join the multiworld pool. Beat the Elite Four and become Champion " +
        "to complete your goal. One world covers both versions — bring your Red or Blue dump.";

    public override string ThemeAccentColor => "#B81818";   // Pokémon Red

    // ── Emulator specifics ────────────────────────────────────────────────────

    protected override string RomSystem     => "GB";

    // §14: Game Boy — BizHawk verified; mGBA/Mesen are the alternatives (shown
    // per their bridge state in the dropdown).
    protected override IReadOnlyList<string> SupportedEmulatorIds =>
        new[] { "bizhawk", "mgba", "mesen" };
    protected override string LuaScriptName => "bizhawk_ap_connector.lua";
    protected override string LuaModuleName => "pokemon_rb";

    /// pokemon_rb.lua reports checks + goal (709-location table generated from the
    /// apworld; mock-verified). Remote-item delivery is the documented deferred piece.
    public override bool ChecksImplemented => true;

    /// The vanilla cartridge dumps the randomizer is built for, by CONTENT
    /// (1 MB + MD5) — never by filename. BOTH Pokémon Red and Pokémon Blue are
    /// accepted (one apworld covers both); the patch base_checksum validates the
    /// exact dump before anything is written.
    protected override IReadOnlyList<RomIdentity> AcceptableBaseRoms => new[]
    {
        new RomIdentity(1024 * 1024, "3d45c1ee9abd5738df46d2bdda8b57dc",
                        "Pokémon Red (USA, Europe)"),
        new RomIdentity(1024 * 1024, "50927e843568814f7ed45ec4f944bd8b",
                        "Pokémon Blue (USA, Europe)"),
    };

    // ── AP patch ────────────────────────────────────────────────────────────────

    // pokemon_rb ships one world but two cartridges → two patch extensions.
    private const string PatchExtRed  = ".apred";
    private const string PatchExtBlue = ".apblue";

    /// Explicit .apred/.apblue chosen by the user (Settings / drag-drop). Null = auto.
    public string? ApPatchPath { get; private set; }

    protected override void OnSavingSettings(IDictionary<string, object?> bag)
        => bag["ap_patch_path"] = ApPatchPath;

    protected override void OnLoadingSettings(JsonElement root)
    {
        if (root.TryGetProperty("ap_patch_path", out var el)) ApPatchPath = el.GetString();
    }

    /// Set the explicit AP patch (drag-and-drop / room-link import) and persist it.
    public void SetExplicitPatch(string path) { ApPatchPath = path; SaveSettings(); }

    /// Resolve the best patch across BOTH Red and Blue extensions, in the helper's
    /// normal priority order (explicit pick → this room's seed+slot → slot name →
    /// newest). When the user pinned an explicit patch it always wins and its own
    /// extension is irrelevant. Otherwise we ask the helper for each extension and
    /// keep the newer-modified of the two matches (so a Blue seed resolves to the
    /// .apblue even when a stale .apred is lying around).
    private string? ResolveBestPatch(out string how)
    {
        if (!string.IsNullOrEmpty(ApPatchPath) && File.Exists(ApPatchPath))
        {
            how = "picked in Settings";
            return ApPatchPath;
        }

        string? seed = GetSeedName?.Invoke();
        string? red  = SnesApPatchHelper.ResolvePatch(PatchExtRed,  null, seed, CurrentSlotName, out string howRed);
        string? blue = SnesApPatchHelper.ResolvePatch(PatchExtBlue, null, seed, CurrentSlotName, out string howBlue);

        if (red != null && blue != null)
        {
            // Both versions have a candidate — keep the more recently written one.
            bool redNewer = File.GetLastWriteTimeUtc(red) >= File.GetLastWriteTimeUtc(blue);
            how = redNewer ? howRed : howBlue;
            return redNewer ? red : blue;
        }
        if (red != null)  { how = howRed;  return red;  }
        if (blue != null) { how = howBlue; return blue; }
        how = "no patch found";
        return null;
    }

    /// ROM safety net: the resolved patch tells us the EXACT vanilla ROM MD5 it
    /// needs (Red's or Blue's) — demand that specific dump when ours is missing or
    /// the wrong one.
    public override RomRequirement? GetUnmetRomRequirement()
    {
        string? patch = ResolveBestPatch(out _);
        string? wantMd5 = patch != null
            ? SnesApPatchHelper.ReadManifestField(patch, "base_checksum") : null;
        bool haveRom = RomPath != null && File.Exists(RomPath);

        if (wantMd5 == null)
            return haveRom ? null
                 : new RomRequirement("Pokémon Red & Blue", "GB",
                       "Pokémon Red or Blue (USA, Europe)",
                       RequiredMd5: null, WrongVersionPresent: false, BuildRomFilter());

        if (haveRom && ComputeMd5(RomPath!).Equals(wantMd5, StringComparison.OrdinalIgnoreCase))
            return null;

        // Name the exact version the patch wants so the prompt is unambiguous.
        string versionLabel = wantMd5.Equals("50927e843568814f7ed45ec4f944bd8b",
                                  StringComparison.OrdinalIgnoreCase)
            ? "Pokémon Blue (USA, Europe) — your original cartridge dump"
            : "Pokémon Red (USA, Europe) — your original cartridge dump";

        return new RomRequirement("Pokémon Red & Blue", "GB",
            versionLabel, wantMd5, WrongVersionPresent: haveRom, BuildRomFilter());
    }

    // ── Session ROM: apply the .apred/.apblue to a library copy ────────────────

    protected override async Task<string?> PrepareSessionRomAsync(
        ApSession session, CancellationToken ct)
    {
        string? patch = ResolveBestPatch(out string how);
        if (patch == null)
        {
            SessionRomNote =
                "[Pokémon Red & Blue] No AP patch (.apred / .apblue) found — " +
                "launching the vanilla ROM. Generate the multiworld, then pick the " +
                "patch in Settings (or drop it under " +
                SnesApPatchHelper.ApOutputDirectory + ").";
            return null;
        }

        var res = await SnesApPatchHelper.ApplyAsync(
            "Pokémon Red & Blue", patch, how, RomPath!,
            RomLibraryDirectory, ".gb", ct);
        SessionRomNote = res.Note;
        if (res.OutRom != null) RegisterSeed(res.OutRom, patch);
        return res.OutRom;
    }

    /// Record a produced/reused patched ROM in the seed library. Never throws.
    private void RegisterSeed(string outRom, string patch)
    {
        try
        {
            SeedLibraryStore.Instance.Register(new SeedEntry
            {
                GameId         = GameId,
                PatchedRomPath = outRom,
                PatchPath      = patch,
                SeedName       = SnesApPatchHelper.ParseSeedFromPatch(patch),
                SlotName       = CurrentSlotName ?? "",
                CreatedUtc     = DateTimeOffset.UtcNow,
            });
        }
        catch { /* registry is non-essential to launching */ }
    }
}
