using System;
using System.Collections.Generic;
using System.IO;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using LauncherV2.Core;

namespace LauncherV2.Plugins.Emulated.Games;

// ═══════════════════════════════════════════════════════════════════════════════
// PokemonBWPlugin — Archipelago integration for Pokémon Black & White (Nintendo
// DS), on the proven BizHawk Lua-pipe bridge. BizHawk runs NDS through its bundled
// melonDS core (the second NDS game in the launcher, after Pokémon Platinum).
//
// STATUS: location DETECTION + goal are REAL and SOURCE-DERIVED. The 633 flag +
// 649 dex locations in pokemon_bw.lua were GENERATED by importing the community
// apworld's OWN data tables (data/locations/ingame_items/*.py +
// data/locations/dexsanity.py) and running its OWN lookup() id-assignment formulas
// with Python (https://github.com/BlastSlimey/PokemonBWAP, apworld pokemon_bw v0.3.999,
// world_version 0.3.200, minimum_ap_version 0.6.3), replicating PokemonBWClient's
// exact flag/dex check model (check_flag_locations / check_dex_locations) and all
// EIGHT goal options (client.goals: ghetsis / champion / cynthia / cobalion /
// tmhm_hunt / seven_sages_hunt / legendary_hunt / pokemon_master). The client reads
// the save through BizHawk's "Main RAM" NDS domain (NOT "ARM9 System Bus" — that is
// Platinum's; BW differs); the Lua module mirrors that exactly — it follows the
// pointer at Main-RAM 0x000024 to the save block, gates on the in-game byte at
// 0x000034, and self-disables on a non-BW ROM (NDS header title "POKEMON B…IRBO01"
// / "POKEMON W…IRAO01" at Main-RAM 0x3FFA80 — exactly client.validate_rom).
//
// items_handling = 0b111 (ctx.items_handling in client.validate_rom) — the AP
// SERVER drives ALL item delivery (this slot's own AND remote items), and the
// reference client WRITES received items into the live save RAM, bumping the game's
// own received-item counter. That guarded save-RAM write is the one deferred piece
// (pokemon_bw.lua receive_item is a documented no-op) until it can be confirmed
// in-emulator, rather than shipped unverified — a wrong save write would corrupt the
// save. Same posture as ff1.lua / pokemon_platinum.lua / cvcotm.lua. Checks + goal
// flow regardless.
//
// AP PATCH (.apblack / .apwhite → .nds): UNLIKE Pokémon Platinum's bsdiff4-based
// .applatinum, the BW patch is a CUSTOM APAutoPatchInterface (rom.py:
// PokemonBlackPatch / PokemonWhitePatch) that REBUILDS the .nds with the bundled
// `ndspy` library from a procedures.txt step list (base_patch / season_patch /
// write_wild_pokemon / …) — there is NO bsdiff/IPS/token `procedure` in its
// manifest. The launcher's shared SnesApPatchHelper / apply_appatch.py can only
// apply procedure-based containers, so it CANNOT produce the BW ROM. The patched
// .nds is produced by Archipelago's OWN BizHawk client (double-clicking the
// .apblack/.apwhite runs the apworld patcher, reading the base ROM from AP host
// settings). The launcher therefore launches the player's already-patched .nds
// DIRECTLY — the FF1 pattern (PrepareSessionRomAsync returns null) — rather than
// risk a corrupt ROM. The .apblack extension hook below is kept inert for parity.
//
// BASE ROM: the world identifies the base ROM PURELY by its 18-byte NDS header
// signature — get_base_rom_bytes() accepts ANY file whose first 18 bytes are
// b'POKEMON B\0\0\0IRBO01' (Black) or b'POKEMON W\0\0\0IRAO01' (White), with NO
// size or MD5 constraint (the base ROM is supplied through AP host settings, not
// diffed against a pinned dump like Platinum's PLATINUM_*_US_HASH). So no honest
// fixed (size, MD5) can be pinned here: AcceptableBaseRoms is left empty (accept
// any .nds the picker allows), and pokemon_bw.lua enforces the SAME header
// signature at launch — disabling on a non-BW ROM exactly as the client does. The
// user imports their already-patched .nds (or a US English Black/White dump).
// ═══════════════════════════════════════════════════════════════════════════════

public sealed class PokemonBWPlugin : EmulatorPlugin
{
    public PokemonBWPlugin() => LoadSettings();

    // ── Identity ──────────────────────────────────────────────────────────────

    public override string GameId      => "pokemon_bw";
    public override string DisplayName => "Pokémon Black & White";
    public override string Subtitle    => "NDS · Emulated";
    public override string ApWorldName => "Pokemon Black and White";

    public override string Description =>
        "Pokémon Black and White introduce the fifth generation of the series on " +
        "the Nintendo DS. Travel the Unova region, catch all-new Pokémon, earn the " +
        "eight gym badges, and confront Team Plasma. In the Archipelago randomizer, " +
        "overworld and hidden items, gym badges, TMs/HMs, and optional Dexsanity " +
        "catches feed the multiworld pool. Your goal is configurable — defeat " +
        "Ghetsis, become Champion, beat Cynthia, hunt the legendaries, and more. " +
        "(Runs on BizHawk's melonDS core.)";

    public override string ThemeAccentColor => "#3A3A3C";   // Reshiram/Zekrom monochrome grey

    // ── Emulator specifics ────────────────────────────────────────────────────

    protected override string RomSystem     => "NDS";

    // §14: NDS is hosted only by BizHawk here (its bundled melonDS core). No other
    // backend in the launcher drives NDS today, so BizHawk is the single supported
    // emulator for this game.
    protected override IReadOnlyList<string> SupportedEmulatorIds =>
        new[] { "bizhawk" };
    protected override string LuaScriptName => "bizhawk_ap_connector.lua";
    protected override string LuaModuleName => "pokemon_bw";

    /// pokemon_bw.lua reports checks + goal (633 flag + 649 dex locations generated
    /// from the apworld; all 8 goals modelled from client.goals; mock-verified).
    /// Remote-item delivery is the documented deferred piece (items_handling 0b111
    /// = server-driven save-RAM writes).
    public override bool ChecksImplemented => true;

    /// The world identifies its base ROM ONLY by the 18-byte NDS header signature
    /// (POKEMON B…IRBO01 / POKEMON W…IRAO01) — NO size or MD5 is checked at patch
    /// time (the base ROM is supplied via AP host settings, not diffed against a
    /// pinned dump). So no honest fixed (size, MD5) can be pinned: accept any .nds
    /// the picker allows, and let pokemon_bw.lua enforce the same header signature
    /// at launch (disabling on a non-BW ROM exactly as the client does).
    protected override IReadOnlyList<RomIdentity> AcceptableBaseRoms =>
        Array.Empty<RomIdentity>();

    // ── AP patch ────────────────────────────────────────────────────────────────
    //
    // BW patching is performed by Archipelago's OWN BizHawk client (ndspy rebuild —
    // see the class header), not by the launcher's procedure-based helper. We keep
    // the standard hook shape for consistency, but it is inert: the player loads the
    // already-patched .nds directly. An explicit .apblack drop in Settings would be
    // honored as an override path, but the AP generator's container cannot be applied
    // by SnesApPatchHelper, so the normal path always loads the ROM as-is.

    // PokemonBlackPatch.patch_file_ending (rom.py). White seeds emit ".apwhite";
    // both rebuild to ".nds". The default extension is used only by the optional
    // explicit-override resolver below.
    private const string PatchExt = ".apblack";

    /// Explicit patch override chosen by the user (Settings / drag-drop). Null =
    /// none — the normal BW path: the already-patched .nds is loaded as-is.
    public string? ApPatchPath { get; private set; }

    protected override void OnSavingSettings(IDictionary<string, object?> bag)
        => bag["ap_patch_path"] = ApPatchPath;

    protected override void OnLoadingSettings(JsonElement root)
    {
        if (root.TryGetProperty("ap_patch_path", out var el)) ApPatchPath = el.GetString();
    }

    /// Set an explicit AP patch (drag-and-drop / room-link import) and persist it.
    public void SetExplicitPatch(string path) { ApPatchPath = path; SaveSettings(); }

    /// ROM safety net. The BW patch carries no base-ROM MD5 (header-only identity),
    /// so the only requirement we can surface is "a Black/White ROM is present" —
    /// the player supplies the already-patched .nds (or a US dump) themselves.
    public override RomRequirement? GetUnmetRomRequirement()
    {
        if (RomPath != null && File.Exists(RomPath)) return null;
        return new RomRequirement("Pokémon Black & White", "NDS",
            "your Archipelago-patched Pokémon Black or White ROM (.nds) — " +
            "produced by double-clicking the .apblack/.apwhite from your seed",
            RequiredMd5: null, WrongVersionPresent: false, BuildRomFilter());
    }

    // ── Session ROM ─────────────────────────────────────────────────────────────
    //
    // The normal BW path applies NO patch in the launcher — the library ROM IS the
    // already-patched .nds (Archipelago's own client rebuilt it via ndspy), so we
    // return null and the base class launches it directly. The .apblack/.apwhite
    // container cannot be applied by SnesApPatchHelper (no bsdiff/IPS/token
    // procedure — it is an ndspy rebuild), so there is no in-launcher apply step.

    protected override Task<string?> PrepareSessionRomAsync(
        ApSession session, CancellationToken ct)
    {
        SessionRomNote =
            "[Pokémon Black & White] BW ROMs are patched by Archipelago's own " +
            "BizHawk client (double-click the .apblack/.apwhite from your seed to " +
            "produce the .nds) — the launcher loads your ROM directly. Make sure " +
            "this ROM is the AP-patched .nds for THIS seed; an unpatched cartridge " +
            "dump will not report checks or receive items.";
        return Task.FromResult<string?>(null);
    }
}
