using System;
using System.Collections.Generic;
using System.IO;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using LauncherV2.Core;

namespace LauncherV2.Plugins.Emulated.Games;

// ═══════════════════════════════════════════════════════════════════════════════
// PokemonPlatinumPlugin — Archipelago integration for Pokémon Platinum (Nintendo
// DS), on the proven BizHawk Lua-pipe bridge. BizHawk runs NDS through its bundled
// melonDS core; this is the first NDS game in the launcher.
//
// STATUS: location DETECTION + goal are REAL and SOURCE-DERIVED. The 761-location
// table in pokemon_platinum.lua was GENERATED by parsing the community apworld's
// data_gen/locations.toml (https://github.com/ljtpetersen/platinum_archipelago,
// world version 0.2.0, minimum_ap_version 0.6.7) and replicating client.py's exact
// raw-id + check model (FlagCheck / OnceCheck / VarCheck over the save's vars_flags
// and once-flag blocks), and the goal (event_checks["beat_cynthia"] = flag 2404) is
// taken verbatim from PokemonPlatinumClient.game_watcher. The client reads the save
// through BizHawk's "ARM9 System Bus" NDS domain (and "ROM" for identity); the Lua
// module mirrors that exactly — it discovers the AP struct via the pointer at
// 0x023DFFFC, validates its " AP "×3+version header, follows savedata_ptr, and
// self-disables on a non-AP ROM (NDS header title "POKEMON PL" = unpatched,
// "PLAP <ver>" = the patched revision — exactly client.validate_rom).
//
// items_handling = 0b001 (RemoteItems off, the default) — the server sends only
// THIS slot's own items and the PATCHED GAME grants its locally-found items itself,
// so a SOLO seed plays fully and every check is reported in a multiworld. Applying
// REMOTE items (RemoteItems on → 0b011) is the client's guarded ring-buffer write
// into the AP struct's remote_item_queue; it is the one deferred piece
// (pokemon_platinum.lua receive_item is a documented no-op) until it can be
// confirmed in-emulator, rather than shipped unverified. Same posture as
// pokemon_rb.lua / cvcotm.lua.
//
// AP PATCH (.applatinum → .nds): a standard APAutoPatchInterface container
// (manifest + base_patch_us_rev0/rev1.bsdiff4 + ap.bin + narc edits), exactly like
// Pokémon Emerald's .apemerald and the SNES SNIClient patches — bsdiff4 over the
// vanilla ROM. Applied via the shared SnesApPatchHelper (resolve the seed's patch,
// validate the base ROM MD5 from the manifest base_checksum, run apply_appatch.py
// on a library COPY — the original is never modified), producing a .nds.
//
// BASE ROM: the user's own Pokémon Platinum (USA) cartridge dump — accepted in BOTH
// revisions (Rev 0 and Rev 1; the apworld ships a bsdiff4 base patch for each and
// validates either MD5). Identified by CONTENT (size + MD5) — never by filename
// (§11). The two MD5s are the apworld's own PLATINUM_1_0_US_HASH / _1_1_US_HASH;
// the size is the No-Intro standard 256 MiB cartridge dump those MD5s belong to.
// ═══════════════════════════════════════════════════════════════════════════════

public sealed class PokemonPlatinumPlugin : EmulatorPlugin
{
    public PokemonPlatinumPlugin() => LoadSettings();

    // ── Identity ──────────────────────────────────────────────────────────────

    public override string GameId      => "pokemon_platinum";
    public override string DisplayName => "Pokémon Platinum";
    public override string Subtitle    => "NDS · Emulated";
    public override string ApWorldName => "Pokemon Platinum";

    public override string Description =>
        "Pokémon Platinum is the definitive Sinnoh adventure for the Nintendo DS. " +
        "In the Archipelago randomizer, badges, HMs, key items, and overworld and " +
        "hidden items across Sinnoh feed the multiworld pool. Defeat Champion Cynthia " +
        "to complete your goal. (Runs on BizHawk's melonDS core.)";

    public override string ThemeAccentColor => "#9B7FB8";   // Platinum / Giratina lilac

    // ── Emulator specifics ────────────────────────────────────────────────────

    protected override string RomSystem     => "NDS";

    // §14: NDS is hosted only by BizHawk here (its bundled melonDS core). No other
    // backend in the launcher drives NDS today, so BizHawk is the single supported
    // emulator for this game.
    protected override IReadOnlyList<string> SupportedEmulatorIds =>
        new[] { "bizhawk" };
    protected override string LuaScriptName => "bizhawk_ap_connector.lua";
    protected override string LuaModuleName => "pokemon_platinum";

    /// pokemon_platinum.lua reports checks + goal (761-location table generated from
    /// the apworld; mock-verified). Remote-item delivery is the documented deferred
    /// piece (items_handling 0b001 means the patched game self-grants its own items).
    public override bool ChecksImplemented => true;

    /// The vanilla cartridge dumps the randomizer is built for, by CONTENT
    /// (size + MD5) — never by filename. BOTH US revisions are accepted (the apworld
    /// ships a bsdiff4 base patch for each and validates either MD5 before writing).
    /// MD5s are the apworld's PLATINUM_1_0_US_HASH / PLATINUM_1_1_US_HASH; the size
    /// is the No-Intro 256 MiB cartridge dump those exact MD5s identify.
    protected override IReadOnlyList<RomIdentity> AcceptableBaseRoms => new[]
    {
        new RomIdentity(268_435_456, "d66ad7a2a0068b5d46e0781ca4953ae9",
                        "Pokémon Platinum (USA)"),
        new RomIdentity(268_435_456, "ab828b0d13f09469a71460a34d0de51b",
                        "Pokémon Platinum (USA) (Rev 1)"),
    };

    // ── AP patch ────────────────────────────────────────────────────────────────

    // PokemonPlatinumPatch.patch_file_ending (rom/__init__.py).
    private const string PatchExt = ".applatinum";

    /// Explicit .applatinum chosen by the user (Settings / drag-drop). Null = auto.
    public string? ApPatchPath { get; private set; }

    protected override void OnSavingSettings(IDictionary<string, object?> bag)
        => bag["ap_patch_path"] = ApPatchPath;

    protected override void OnLoadingSettings(JsonElement root)
    {
        if (root.TryGetProperty("ap_patch_path", out var el)) ApPatchPath = el.GetString();
    }

    /// Set the explicit AP patch (drag-and-drop / room-link import) and persist it.
    public void SetExplicitPatch(string path) { ApPatchPath = path; SaveSettings(); }

    /// The patch that would be used right now, in the shared helper's priority order
    /// (explicit pick → this room's seed+slot → slot name → newest generated).
    private string? ResolvePatch(out string how)
        => SnesApPatchHelper.ResolvePatch(
               PatchExt, ApPatchPath, GetSeedName?.Invoke(), CurrentSlotName, out how);

    /// ROM safety net: the resolved patch tells us the EXACT vanilla ROM MD5 it
    /// needs (Rev 0's or Rev 1's) — demand that specific dump when ours is missing
    /// or the wrong one.
    public override RomRequirement? GetUnmetRomRequirement()
    {
        string? patch = ResolvePatch(out _);
        string? wantMd5 = patch != null
            ? SnesApPatchHelper.ReadManifestField(patch, "base_checksum") : null;
        bool haveRom = RomPath != null && File.Exists(RomPath);

        if (wantMd5 == null)
            return haveRom ? null
                 : new RomRequirement("Pokémon Platinum", "NDS",
                       "Pokémon Platinum (USA) — your original cartridge dump",
                       RequiredMd5: null, WrongVersionPresent: false, BuildRomFilter());

        if (haveRom && ComputeMd5(RomPath!).Equals(wantMd5, StringComparison.OrdinalIgnoreCase))
            return null;

        // Name the exact revision the patch wants so the prompt is unambiguous.
        string versionLabel = wantMd5.Equals("ab828b0d13f09469a71460a34d0de51b",
                                  StringComparison.OrdinalIgnoreCase)
            ? "Pokémon Platinum (USA) (Rev 1) — your original cartridge dump"
            : "Pokémon Platinum (USA) — your original cartridge dump";

        return new RomRequirement("Pokémon Platinum", "NDS",
            versionLabel, wantMd5, WrongVersionPresent: haveRom, BuildRomFilter());
    }

    // ── Session ROM: apply the .applatinum to a library copy ───────────────────

    protected override async Task<string?> PrepareSessionRomAsync(
        ApSession session, CancellationToken ct)
    {
        string? patch = ResolvePatch(out string how);
        if (patch == null)
        {
            SessionRomNote =
                "[Pokémon Platinum] No AP patch (.applatinum) found — launching the " +
                "vanilla ROM. Checks and item delivery CANNOT WORK on a vanilla ROM: " +
                "generate the multiworld, then pick the patch in Settings (or drop it " +
                "under " + SnesApPatchHelper.ApOutputDirectory + ").";
            return null;
        }

        var res = await SnesApPatchHelper.ApplyAsync(
            "Pokémon Platinum", patch, how, RomPath!,
            RomLibraryDirectory, ".nds", ct);
        SessionRomNote = res.Note;
        if (res.OutRom != null) RegisterSeed(res.OutRom, patch);
        return res.OutRom;
    }

    /// Record a produced/reused patched ROM in the seed library. Never throws.
    private void RegisterSeed(string outRom, string patch)
    {
        try
        {
            SeedLibraryStore.Instance.Register(new SeedEntry
            {
                GameId         = GameId,
                PatchedRomPath = outRom,
                PatchPath      = patch,
                SeedName       = SnesApPatchHelper.ParseSeedFromPatch(patch),
                SlotName       = CurrentSlotName ?? "",
                CreatedUtc     = DateTimeOffset.UtcNow,
            });
        }
        catch { /* registry is non-essential to launching */ }
    }
}
