using System;
using System.Collections.Generic;
using System.IO;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using LauncherV2.Core;

namespace LauncherV2.Plugins.Emulated.Games;

// ═══════════════════════════════════════════════════════════════════════════════
// SMZ3Plugin — Archipelago integration for SMZ3, the Super Metroid + A Link to the
// Past Crossover Item Randomizer (SNES), on the proven BizHawk Lua-pipe bridge.
//
// STATUS: location DETECTION + goal are REAL and SOURCE-DERIVED. The two 316-entry
// location tables in smz3.lua (100 Super Metroid + 216 A Link to the Past) were
// GENERATED by AST-parsing every Location(self, <Id>, ...) call in the apworld's
// TotalSMZ3/Regions tree, applying the exact id math the client uses
// (ap_id = locations_start_id(85000) + convertLocSMZ3IDToAPID(Id)) — mock-verified
// through MoonSharp against synthetic SRAM ring-queue records. Both on-ROM queue
// layouts (old + the 0.4.4 "optimized" one, selected by ROM-name byte 7) and the
// dual-game goal (SM Mother-Brain ending OR Z3 credits on whichever game is active)
// are implemented faithfully. items_handling = 0b101 — the PATCHED GAME grants its
// own locally-found items, so a SOLO seed plays fully and every check is reported.
// Delivering REMOTE multiworld items is the RECV-ring-queue write path; it is
// implemented in smz3.lua but held behind a gate (REMOTE_ITEMS_VERIFIED=false)
// until confirmed in-emulator, rather than risk a wrong item/player encoding.
//
// THE PATCH (.apsmz3 → .sfc): an APProcedurePatch container. UNUSUAL BASE-ROM
// MODEL — SMZ3 fuses TWO games. The AP generator builds a combined 6 MB
// (0x600000) ROM from the player's own Super Metroid (Japan+US) dump AND their own
// A Link to the Past (Japan 1.0) dump (Rom.py.combine_smz3_rom), and the patch's
// base_checksum is the MD5 of that COMBINED ROM (SMZ3ProcedurePatch.hash =
// 3a177ba9879e3dd04fb623a219d175b2). So at LAUNCH the user supplies that single
// combined SMZ3 base ROM; the launcher applies the .apsmz3 to a library COPY of it
// (the original is never modified) via the shared SnesApPatchHelper, producing the
// playable .sfc. AcceptableBaseRoms / GetUnmetRomRequirement therefore describe the
// COMBINED ROM (6 MB + that MD5), and the patch container's base_checksum is the
// real gate — identical mechanics to ALinkToThePastPlugin, only the ROM identity
// differs. (The two source cartridge dumps are needed only at generation time, by
// the AP host that builds the seed — not by the launcher.)
//
// KNOWN HELPER GAP (documented honestly, not silently): the SMZ3 procedure's first
// step is "apply_basepatch" (it injects the apworld's data/zsm.ips), a custom AP
// patch-extension step. The shared Plugins/Scripts/apply_appatch.py understands
// apply_ips / apply_bsdiff4 / apply_tokens but not "apply_basepatch" (and zsm.ips
// ships inside the apworld, not the .apsmz3), so patch application of an .apsmz3
// needs that one helper step added before live item delivery is end-to-end. The
// in-emulator DETECTION + goal logic in smz3.lua is complete and unaffected by this
// helper gap; it is called out here so a player is never left wondering.
// ═══════════════════════════════════════════════════════════════════════════════

public sealed class SMZ3Plugin : EmulatorPlugin
{
    public SMZ3Plugin() => LoadSettings();

    // ── Identity ──────────────────────────────────────────────────────────────

    public override string GameId      => "smz3";
    public override string DisplayName => "SMZ3 (Super Metroid + A Link to the Past)";
    public override string Subtitle    => "SNES · Emulated";
    public override string ApWorldName => "SMZ3";

    public override string Description =>
        "SMZ3 is the legendary crossover randomizer that fuses Super Metroid and A " +
        "Link to the Past into one combined SNES adventure. Every item across both " +
        "worlds — Samus's beams and tanks, Link's swords, bottles, and dungeon " +
        "prizes — joins the multiworld pool, and you warp freely between Zebes and " +
        "Hyrule. Defeat both Ganon and Mother Brain to complete your goal.";

    // Super Metroid energy-tank red / Zelda Triforce gold meet in the middle — a
    // warm amber that reads as "both games at once".
    public override string ThemeAccentColor => "#D08A2C";

    // ── Emulator specifics ────────────────────────────────────────────────────

    protected override string RomSystem     => "SNES";
    protected override string LuaScriptName => "bizhawk_ap_connector.lua";
    protected override string LuaModuleName => "smz3";

    // §14: SMZ3 is an SNES SNIClient world — same backends as A Link to the Past /
    // Super Metroid. BizHawk is verified; snes9x + Mesen are the alternatives,
    // shown per their bridge state in the dropdown.
    protected override IReadOnlyList<string> SupportedEmulatorIds =>
        new[] { "bizhawk", "snes9x", "mesen" };

    /// smz3.lua reports checks (both halves) + the dual-game goal, from tables
    /// generated out of the apworld and mock-verified. Remote-item delivery is the
    /// documented gated/deferred piece (see class header).
    public override bool ChecksImplemented => true;

    /// The COMBINED SMZ3 base ROM, identified by CONTENT (6 MB + MD5), never by
    /// filename. This is the 0x600000-byte image the AP generator builds by merging
    /// a Super Metroid (Japan+US) dump with an A Link to the Past (Japan 1.0) dump;
    /// its MD5 is SMZ3ProcedurePatch.hash. apply_appatch.py independently re-checks
    /// the .apsmz3 container's own base_checksum before patching, so this only
    /// drives the launcher's "wrong version" hint. (The size-only fallback lets the
    /// 6 MB combined ROM be recognised even if a future SMZ3 build re-hashes.)
    protected override IReadOnlyList<RomIdentity> AcceptableBaseRoms => new[]
    {
        new RomIdentity(0x600000, "3a177ba9879e3dd04fb623a219d175b2",
                        "SMZ3 combined base ROM (Super Metroid JU + A Link to the Past JP 1.0)"),
    };

    // ── AP patch ────────────────────────────────────────────────────────────────

    private const string PatchExt  = ".apsmz3";
    private const string ResultExt = ".sfc";

    /// Explicit .apsmz3 chosen by the user (Settings / drag-drop). Null = auto.
    public string? ApPatchPath { get; private set; }

    protected override void OnSavingSettings(IDictionary<string, object?> bag)
        => bag["ap_patch_path"] = ApPatchPath;

    protected override void OnLoadingSettings(JsonElement root)
    {
        if (root.TryGetProperty("ap_patch_path", out var el)) ApPatchPath = el.GetString();
    }

    /// Set the explicit AP patch (drag-and-drop / room-link import) and persist it.
    public void SetExplicitPatch(string path) { ApPatchPath = path; SaveSettings(); }

    /// ROM safety net: the resolved patch tells us the EXACT base ROM MD5 it needs
    /// (the combined-ROM hash) — demand that specific dump when ours is missing or
    /// the wrong one, by fingerprint rather than silently patching the wrong file.
    public override RomRequirement? GetUnmetRomRequirement()
    {
        var patch = SnesApPatchHelper.ResolvePatch(
            PatchExt, ApPatchPath, GetSeedName?.Invoke(), CurrentSlotName, out _);
        string? wantMd5 = patch != null
            ? SnesApPatchHelper.ReadManifestField(patch, "base_checksum") : null;
        bool haveRom = RomPath != null && File.Exists(RomPath);

        const string versionLabel =
            "SMZ3 combined base ROM (Super Metroid JU + A Link to the Past JP 1.0)";

        if (wantMd5 == null)
            return haveRom ? null
                 : new RomRequirement("SMZ3", "SNES", versionLabel,
                       RequiredMd5: null, WrongVersionPresent: false, BuildRomFilter());

        if (haveRom && ComputeMd5(RomPath!).Equals(wantMd5, StringComparison.OrdinalIgnoreCase))
            return null;

        return new RomRequirement("SMZ3", "SNES",
            versionLabel + " — built by your AP host from your own SM + ALttP dumps",
            wantMd5, WrongVersionPresent: haveRom, BuildRomFilter());
    }

    // ── Session ROM: apply the .apsmz3 to a library copy ──────────────────────

    protected override async Task<string?> PrepareSessionRomAsync(
        ApSession session, CancellationToken ct)
    {
        string? patch = SnesApPatchHelper.ResolvePatch(
            PatchExt, ApPatchPath, GetSeedName?.Invoke(), CurrentSlotName, out string how);
        if (patch == null)
        {
            SessionRomNote =
                "[SMZ3] No AP patch (.apsmz3) found — launching the base ROM. Checks " +
                "and ITEM DELIVERY require the patched ROM: generate the multiworld, " +
                "then pick the patch in Settings → SMZ3 (or drop it under " +
                SnesApPatchHelper.ApOutputDirectory + ").";
            return null;
        }

        if (RomPath == null || !File.Exists(RomPath))
        {
            SessionRomNote =
                "[SMZ3] No base ROM set — import your combined SMZ3 base ROM (the 6 MB " +
                "image your AP host built from a Super Metroid (JU) dump and an A Link " +
                "to the Past (JP 1.0) dump) in Settings, then relaunch.";
            return null;
        }

        var res = await SnesApPatchHelper.ApplyAsync(
            "SMZ3", patch, how, RomPath!, RomLibraryDirectory, ResultExt, ct);
        SessionRomNote = res.Note;
        if (res.OutRom != null) RegisterSeed(res.OutRom, patch);
        return res.OutRom;
    }

    /// Record a produced/reused patched ROM in the seed library. Never throws.
    private void RegisterSeed(string outRom, string patch)
    {
        try
        {
            SeedLibraryStore.Instance.Register(new SeedEntry
            {
                GameId         = GameId,
                PatchedRomPath = outRom,
                PatchPath      = patch,
                SeedName       = SnesApPatchHelper.ParseSeedFromPatch(patch),
                SlotName       = CurrentSlotName ?? "",
                CreatedUtc     = DateTimeOffset.UtcNow,
            });
        }
        catch { /* registry is non-essential to launching */ }
    }
}
