using System;
using System.Collections.Generic;
using System.IO;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
using LauncherV2.Core;

namespace LauncherV2.Plugins.Emulated.Games;

// ═══════════════════════════════════════════════════════════════════════════════
// SuperMarioWorldPlugin — Archipelago integration for Super Mario World (SNES),
// on the proven BizHawk Lua-pipe bridge (and the snes9x NWA backend).
//
// STATUS: location DETECTION + goal are REAL and SOURCE-DERIVED. The 763-location
// table in smw.lua was GENERATED by JOINING worlds/smw/Locations.py
// (all_locations: name → AP id) with worlds/smw/Levels.py (location_id_to_level_id:
// name → [level_id, check_type]); the per-type bit/byte math + option gates + the
// "SMW" ROM-header identity + the {0x28,0x31,0x32} goal levels are mirrored from
// Client.py game_watcher (world_version 2.1.1). Mock-verified through MoonSharp
// against synthetic WRAM/CARTROM. items_handling = 0b111 (FULL remote) — the SMW
// client owns ALL item delivery via an intricate per-item-type set of guarded
// WRAM writes, so there is no game-self-grant fallback; that delivery path is
// deferred (smw.lua receive_item is a no-op) until it can be confirmed in-emulator,
// rather than shipped unverified. Checks + goal work regardless of that gap.
//
// THE PATCH (.apsmw) is SMWDeltaPatch — an APDeltaPatch, i.e. an APProcedurePatch
// whose procedure is [("apply_bsdiff4", ["delta.bsdiff4"])], result ".sfc",
// base_checksum = the SMW US 1.0 MD5. That is the SAME container family as A Link
// to the Past's .aplttp (bsdiff4 + manifest), so the shared SnesApPatchHelper +
// Plugins/Scripts/apply_appatch.py apply it unchanged: resolve the seed's patch,
// validate the base ROM MD5 (against the container's own base_checksum), run the
// patcher on a library COPY — the user's original ROM is never modified.
// Base ROM: the user's own Super Mario World (US 1.0) cartridge dump (512 KB),
// identified by CONTENT (size + MD5) — never by filename (§11).
// ═══════════════════════════════════════════════════════════════════════════════

public sealed class SuperMarioWorldPlugin : EmulatorPlugin
{
    public SuperMarioWorldPlugin() => LoadSettings();

    // ── Identity ──────────────────────────────────────────────────────────────

    public override string GameId      => "smw";
    public override string DisplayName => "Super Mario World";
    public override string Subtitle    => "SNES · Emulated";
    public override string ApWorldName => "Super Mario World";

    public override string Description =>
        "Super Mario World is the SNES platforming landmark across Dinosaur Land. " +
        "The Archipelago randomizer shuffles every level's exits, switch palaces, " +
        "Yoshi, and power-ups into the multiworld pool — with optional Dragon Coin, " +
        "3-Up Moon, Hidden 1-Up, bonus-block and full Blocksanity checks. Beat " +
        "Bowser (or finish the Special world) to complete your goal.";

    // ── Visual identity ───────────────────────────────────────────────────────

    public override string ThemeAccentColor => "#E52521";   // Mario red

    // ── Emulator specifics ────────────────────────────────────────────────────

    protected override string RomSystem     => "SNES";
    protected override string LuaScriptName => "bizhawk_ap_connector.lua";
    protected override string LuaModuleName => "smw";

    // §14: the SNES emulators this world is played on. BizHawk is verified; the
    // §14 ask was "SNES: BizHawk or snes9x", so snes9x is the headline alternative,
    // with Mesen as a third option (each shown per its bridge state in the dropdown).
    protected override IReadOnlyList<string> SupportedEmulatorIds =>
        new[] { "bizhawk", "snes9x", "mesen" };

    private const string PatchExt  = ".apsmw";
    private const string ResultExt = ".sfc";

    /// The vanilla Super Mario World cartridge dump the randomizer is built for,
    /// identified by CONTENT (512 KB + MD5), never by filename. This is the
    /// long-standing community-known US 1.0 hash every AP SMW generator validates
    /// against (worlds/smw/Rom.py USHASH); apply_appatch.py independently re-checks
    /// the patch container's own base_checksum before patching, so this only drives
    /// the launcher's "wrong version" hint.
    protected override IReadOnlyList<RomIdentity> AcceptableBaseRoms
        => new[]
        {
            new RomIdentity(512 * 1024,                           // 524,288 bytes
                            "cdd3c8c37322978ca8669b34bc89c804",
                            "Super Mario World (USA)"),
        };

    /// smw.lua mirrors the official SNIClient game_watcher: a per-check-type scan
    /// of WRAM progress/dragon/moon/1up/bonus/blocksanity data (gated by the
    /// per-seed CARTROM option flags + event table) → AP location ids, and the
    /// game-state ≥ 0x18 / goal-level credits goal. The table is GENERATED from
    /// the apworld source and mock-verified; a real playthrough confirms it live.
    public override bool ChecksImplemented => true;

    /// The Super Mario World datapackage checksum is announced by the server in
    /// RoomInfo, not embedded as a constant in the apworld; left null. The
    /// launcher's "apworld updated" warning is simply not raised for this game
    /// until a live RoomInfo checksum is captured and pinned here.
    public string? BuiltAgainstDataPackageChecksum => null;

    // ── AP patch settings ─────────────────────────────────────────────────────

    /// Explicit .apsmw chosen by the user (Settings / drag-drop). Null = auto.
    public string? ApPatchPath { get; private set; }

    protected override void OnSavingSettings(IDictionary<string, object?> bag)
        => bag["ap_patch_path"] = ApPatchPath;

    protected override void OnLoadingSettings(JsonElement root)
    {
        if (root.TryGetProperty("ap_patch_path", out var el))
            ApPatchPath = el.GetString();
    }

    private string? ResolvePatchPath(out string how)
        => SnesApPatchHelper.ResolvePatch(
            PatchExt, ApPatchPath, GetSeedName?.Invoke(), CurrentSlotName, out how);

    /// Set the explicit AP patch (drag-and-drop / room-link import) and persist it.
    public void SetExplicitPatch(string path) { ApPatchPath = path; SaveSettings(); }

    /// ROM safety net: when a patch is known, demand exactly its base ROM
    /// (base_checksum) so the launcher can ask the player by fingerprint instead
    /// of silently patching the wrong dump.
    public override RomRequirement? GetUnmetRomRequirement()
    {
        string? wantMd5 = null;
        var patch = ResolvePatchPath(out _);
        if (patch != null) wantMd5 = SnesApPatchHelper.ReadManifestField(patch, "base_checksum");

        bool haveRom = RomPath != null && File.Exists(RomPath);

        if (wantMd5 == null)
            return haveRom ? null
                 : new RomRequirement("Super Mario World", "SNES",
                       "Super Mario World (USA)",
                       RequiredMd5: null, WrongVersionPresent: false, BuildRomFilter());

        if (haveRom && ComputeMd5(RomPath!).Equals(wantMd5, StringComparison.OrdinalIgnoreCase))
            return null;

        return new RomRequirement(
            "Super Mario World", "SNES",
            "Super Mario World (USA) — the original vanilla cartridge dump",
            wantMd5, WrongVersionPresent: haveRom, BuildRomFilter());
    }

    private void RegisterSeed(string outRom, string patch)
    {
        try
        {
            SeedLibraryStore.Instance.Register(new SeedEntry
            {
                GameId         = GameId,
                PatchedRomPath = outRom,
                PatchPath      = patch,
                SeedName       = SnesApPatchHelper.ParseSeedFromPatch(patch),
                SlotName       = CurrentSlotName ?? "",
                CreatedUtc     = DateTimeOffset.UtcNow,
            });
        }
        catch { /* registry is non-essential to launching */ }
    }

    // ── Session ROM: apply the .apsmw to a library copy ───────────────────────

    protected override async Task<string?> PrepareSessionRomAsync(
        ApSession session, CancellationToken ct)
    {
        string? patch = ResolvePatchPath(out string how);
        if (patch == null)
        {
            SessionRomNote =
                "[Super Mario World] No AP patch (.apsmw) found — launching the " +
                "vanilla ROM. Checks CANNOT WORK on a vanilla ROM: generate the " +
                "multiworld, then pick the patch in Settings → Super Mario World " +
                "(or drop it under " + SnesApPatchHelper.ApOutputDirectory + ").";
            return null;
        }

        if (RomPath == null || !File.Exists(RomPath))
        {
            SessionRomNote =
                "[Super Mario World] No base ROM set — import your vanilla US 1.0 " +
                "cartridge dump in Settings, then relaunch.";
            return null;
        }

        var result = await SnesApPatchHelper.ApplyAsync(
            "Super Mario World", patch, how, RomPath!, RomLibraryDirectory, ResultExt, ct);
        SessionRomNote = result.Note;
        if (result.OutRom != null) RegisterSeed(result.OutRom, patch);
        return result.OutRom;
    }

    // ── Settings panel: base panel + AP patch section ─────────────────────────

    public override UIElement? CreateSettingsPanel()
    {
        var basePanel = base.CreateSettingsPanel();
        if (basePanel is not StackPanel panel) return basePanel;

        var muted = new SolidColorBrush(Color.FromRgb(0x72, 0x7A, 0x99));
        var fg    = new SolidColorBrush(Color.FromRgb(0xCC, 0xD0, 0xE0));

        panel.Children.Add(new TextBlock
        {
            Text = "ARCHIPELAGO PATCH", FontSize = 10, FontWeight = FontWeights.SemiBold,
            Foreground = muted, Margin = new Thickness(0, 20, 0, 8),
        });
        panel.Children.Add(new TextBlock
        {
            Text = "The multiworld generator produces a .apsmw patch for your slot. " +
                   "The launcher applies it to a COPY of your ROM at launch (your file " +
                   "is never modified). Leave empty to auto-use the newest patch from " +
                   "the Archipelago output folder.",
            FontSize = 11, Foreground = muted, TextWrapping = TextWrapping.Wrap,
            Margin = new Thickness(0, 0, 0, 8),
        });

        var patchRow = new DockPanel { Margin = new Thickness(0, 0, 0, 4) };
        var patchBox = new TextBox
        {
            Text = ApPatchPath ?? "", Margin = new Thickness(0, 0, 8, 0),
            IsReadOnly = true, FontSize = 12,
            Background  = new SolidColorBrush(Color.FromRgb(0x0C, 0x10, 0x20)),
            Foreground  = fg,
            BorderBrush = new SolidColorBrush(Color.FromRgb(0x1E, 0x22, 0x33)),
        };
        var clearBtn = new Button
        {
            Content = "Auto", Width = 50, Margin = new Thickness(0, 0, 8, 0),
            Padding = new Thickness(0, 6, 0, 6),
            Background  = new SolidColorBrush(Color.FromRgb(0x1A, 0x1E, 0x30)),
            Foreground  = fg,
            BorderBrush = new SolidColorBrush(Color.FromRgb(0x2A, 0x30, 0x50)),
            ToolTip = "Clear the explicit pick — auto-detect the newest generated patch.",
        };
        var pickBtn = new Button
        {
            Content = "Select AP patch...", Width = 130, Padding = new Thickness(0, 6, 0, 6),
            Background  = new SolidColorBrush(Color.FromRgb(0x1A, 0x1E, 0x30)),
            Foreground  = fg,
            BorderBrush = new SolidColorBrush(Color.FromRgb(0x2A, 0x30, 0x50)),
        };

        var autoNote = new TextBlock
        {
            FontSize = 10, Foreground = muted, TextWrapping = TextWrapping.Wrap,
            Margin = new Thickness(0, 4, 0, 0),
        };
        void RefreshAutoNote()
        {
            string? auto = ResolvePatchPath(out string how);
            autoNote.Text = ApPatchPath != null
                ? "Explicit patch selected — auto-detection off."
                : auto != null
                    ? $"Auto-detected ({how}): {auto}"
                    : $"No .apsmw found under {SnesApPatchHelper.ApOutputDirectory} yet.";
        }
        RefreshAutoNote();

        pickBtn.Click += (_, _) =>
        {
            var dlg = new Microsoft.Win32.OpenFileDialog
            {
                Title  = "Select Archipelago patch for Super Mario World",
                Filter = "AP SMW patch (*.apsmw)|*.apsmw|All files (*.*)|*.*",
            };
            if (Directory.Exists(SnesApPatchHelper.ApOutputDirectory))
                dlg.InitialDirectory = SnesApPatchHelper.ApOutputDirectory;
            if (dlg.ShowDialog() != true) return;
            ApPatchPath   = dlg.FileName;
            patchBox.Text = dlg.FileName;
            SaveSettings();
            RefreshAutoNote();
        };
        clearBtn.Click += (_, _) =>
        {
            ApPatchPath   = null;
            patchBox.Text = "";
            SaveSettings();
            RefreshAutoNote();
        };

        DockPanel.SetDock(pickBtn,  Dock.Right);
        DockPanel.SetDock(clearBtn, Dock.Right);
        patchRow.Children.Add(pickBtn);
        patchRow.Children.Add(clearBtn);
        patchRow.Children.Add(patchBox);
        panel.Children.Add(patchRow);
        panel.Children.Add(autoNote);

        return panel;
    }
}
