using System.Collections.Generic;
using System.Windows;
using LauncherV2.Plugins.Emulated;

namespace LauncherV2.Plugins.Emulated.Games;

// ═══════════════════════════════════════════════════════════════════════════════
// SuperMarioSunshinePlugin — Archipelago integration for Super Mario Sunshine
// (GameCube), the community apworld "Super Mario Sunshine" by Joshark.
//
// WORLD SOURCE: Joshark/archipelago-sms (fork of hatkirby/Archipelago).
//   Latest release: "Mario Sunshine AP V0.5.2" (tag 0.5.2, Feb 2025).
//   9 release assets in v0.5.2 (exact names not extracted from release page).
//   AP game string: "Super Mario Sunshine" (inferred from fork content + release
//   naming; verify against __init__.py when integrating).
//   Contributors: Joshark (owner), gerbiljames, SomeJakeGuy, Griffork, vasumv.
//
// WHAT THE APWORLD RANDOMIZES:
//   Shines, Blue Coins, Nozzle Boxes — these form the location pool. Shine and
//   Blue Coin counts are adjusted at generation time to prevent fill failures.
//   Nozzle Boxes (except Delfino Plaza) were added as checks in v0.5.0. Nozzle
//   Rando is supported. Filler: 1Ups and extra Shines fill the remaining pool.
//   DeathLink: supported (added in v0.5.0).
//
// PATCH WORKFLOW: since v0.5.0 the AP world generates a patch file rather than
//   requiring manual cheat codes. The player generates a patched GCN ISO via the
//   SMS AP world, loads it in Dolphin, and connects via the standard Archipelago
//   launcher. The launcher does not apply the patch — that is done by the AP
//   generator. This plugin loads the patched ISO directly (same pattern as other
//   Dolphin GCN plugins: launcher launches Dolphin, the ISO is the library copy).
//
// EMULATOR: Dolphin (GameCube). BizHawk does not host a GCN core.
//   AvailableBackends() returns an empty list for "GCN" today (Dolphin not yet in
//   EmulatorBackends) — the UI shows the honest "no emulator configured" state,
//   exactly as KirbyAirRidePlugin and PokemonXDPlugin do.
//
// GATE TO ENABLE:
//   1. Add Dolphin to EmulatorBackends (id "dolphin", system "GCN").
//   2. Build a Dolphin memory-read bridge (or leverage an SMS AP Client if one
//      ships) and implement the Lua module or equivalent bridge.
//   3. Confirm the exact game string from worlds/__init__.py.
//   4. Set ChecksImplemented to true and update the description.
//
// ISO: Super Mario Sunshine (NTSC-U, game ID GMSE01).
//   No launcher-side ROM validation is defined here — the player supplies a
//   patched ISO generated by the SMS AP world. AcceptableBaseRoms is left empty
//   (no constraint) so any GCN ISO the player points to is accepted.
// ═══════════════════════════════════════════════════════════════════════════════

public sealed class SuperMarioSunshinePlugin : EmulatorPlugin
{
    public SuperMarioSunshinePlugin() => LoadSettings();

    // ── Identity ──────────────────────────────────────────────────────────────

    public override string GameId      => "super_mario_sunshine";
    public override string DisplayName => "Super Mario Sunshine";
    public override string Subtitle    => "GameCube · Emulated (Dolphin)";

    // Exact AP world game string — verify against worlds/__init__.py.
    public override string ApWorldName => "Super Mario Sunshine";

    public override string Description =>
        "Super Mario Sunshine is Nintendo's 2002 GameCube platformer set on the " +
        "tropical Isle Delfino. Armed with F.L.U.D.D. (Flash Liquidizer Ultra " +
        "Dousing Device), Mario must collect Shine Sprites to restore sunlight to " +
        "the island and clear his name after being framed by a mysterious shadow " +
        "doppelganger. Levels span sun-drenched beach towns, coral-reef lagoons, " +
        "amusement parks, and a volcano summit.\n\n" +
        "In the Archipelago randomizer (by Joshark), Shine Sprites, Blue Coins, " +
        "and Nozzle Boxes form the multiworld location pool. The AP world generates " +
        "a patched ISO; load it in Dolphin and connect via the Archipelago launcher. " +
        "DeathLink and Nozzle Rando are supported. The launcher will add integrated " +
        "Dolphin support in a future update.\n\n" +
        "Source: github.com/Joshark/archipelago-sms (v0.5.2 · Feb 2025).";

    public override string ThemeAccentColor => "#E87A00";   // F.L.U.D.D. orange / Isle Delfino sun

    // ── Emulator specifics ────────────────────────────────────────────────────

    // Dolphin is the canonical GameCube emulator; it is not yet in
    // EmulatorBackends (BizHawk does not host GCN), so AvailableBackends()
    // returns an empty list and the UI shows the honest "coming soon" state.
    protected override string RomSystem => "GCN";

    // Declare Dolphin so the intent is recorded; the base class resolves this
    // against EmulatorBackends.BackendsForSystem("GCN") which currently returns
    // nothing — a graceful no-op rather than a silent wrong default.
    protected override IReadOnlyList<string> SupportedEmulatorIds =>
        new[] { "dolphin" };

    // No confirmed Lua module exists yet for this game through the launcher bridge.
    // The SMS AP world ships its own patch flow; a future Dolphin bridge would
    // provide a module name here.
    protected override string LuaScriptName => "bizhawk_ap_connector.lua";
    protected override string LuaModuleName => "super_mario_sunshine";

    // Checks are not yet implemented through the launcher bridge; the SMS AP world
    // and Dolphin client handle the AP connection when launched manually.
    public override bool ChecksImplemented => false;
}
