using System;
using System.Collections.Generic;
using System.IO;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using LauncherV2.Core;

namespace LauncherV2.Plugins.Emulated.Games;

// ═══════════════════════════════════════════════════════════════════════════════
// WarioLand4Plugin — Archipelago integration for Wario Land 4 (GBA), on the proven
// BizHawk Lua-pipe bridge.
//
// COMMUNITY APWORLD. Wario Land 4 is NOT in ArchipelagoMW/Archipelago main; it is
// lil David's custom world:
//   https://github.com/lilDavid/Archipelago-Wario-Land-4   (world_version 3.3.3,
//   minimum_ap_version 0.6.0). Base patch: https://github.com/lilDavid/WL4-Archipelago-Patch .
//
// STATUS: location DETECTION + goal are REAL and SOURCE-DERIVED. The 292-entry
// location table in wario_land_4.lua was GENERATED by importing the world's own
// locations.py and calling LocationData.to_ap_id() (ids exact, not hand-copied);
// the inventory-bit math + game-mode gate + "WARIOLANDAP{E,J}" ROM signature are
// replicated exactly from client.py (WL4Client.handle_inventory / handle_goal),
// and mock-verified through MoonSharp against synthetic System-Bus memory.
//
// items_handling = LOCAL_ITEMS (0b001): the PATCHED GAME grants its own locally
// found items, so a SOLO seed plays fully and every check is reported in a
// multiworld. Delivering REMOTE multiworld items is the client's guarded
// System-Bus mailbox handshake (IncomingItemID + IncomingItemSender +
// MultiworldState); it depends on per-seed player-name encoding and needs
// in-emulator confirmation, so it is deferred (wario_land_4.lua receive_item is
// a documented no-op) rather than shipped unverified.
//
// AP PATCH (.apwl4 → .gba): WL4ProcedurePatch is a standard APProcedurePatch
// container (basepatch.bsdiff4 + token_data.bin + an update_header step that
// rewrites the cartridge name to WARIOLANDAP{E,J}), applied via the shared
// SnesApPatchHelper — resolve the seed's patch, validate the base ROM MD5 (the
// manifest base_checksum), run apply_appatch.py on a library COPY (the original
// is never modified). Base ROM: the user's own Wario Land 4 (USA, Europe)
// cartridge dump (8 MB, MD5 5fe4…a404), identified by CONTENT (size + MD5) —
// never by filename (§11). The Japanese dump (8 MB, MD5 99c8…f5c2) shares the
// ROM mapping and is also accepted by the world, but the patch validates against
// the US/EU checksum, so that is the one demanded when ours is missing/wrong.
// ═══════════════════════════════════════════════════════════════════════════════

public sealed class WarioLand4Plugin : EmulatorPlugin
{
    public WarioLand4Plugin() => LoadSettings();

    // ── Identity ──────────────────────────────────────────────────────────────

    public override string GameId      => "wario_land_4";
    public override string DisplayName => "Wario Land 4";
    public override string Subtitle    => "GBA · Emulated";

    // Exact AP world id ("game" string in the world's archipelago.json and
    // WL4Client.game / WL4World).
    public override string ApWorldName => "Wario Land 4";

    public override string Description =>
        "Wario Land 4 is Wario's GBA treasure-hunting platformer. In the " +
        "Archipelago randomizer, every jewel piece, CD, full-health item, Keyzer " +
        "and diamond across the six passages joins the multiworld pool, with " +
        "difficulty-aware location sets and optional Death Link. Beat the Golden " +
        "Diva to complete your goal.";

    public override string ThemeAccentColor => "#E8B11C";   // Wario gold

    // ── Emulator specifics ────────────────────────────────────────────────────

    protected override string RomSystem     => "GBA";

    // §14: GBA emulators — BizHawk verified; mGBA/Mesen are the alternatives
    // (shown per their bridge state in the dropdown).
    protected override IReadOnlyList<string> SupportedEmulatorIds =>
        new[] { "bizhawk", "mgba", "mesen" };
    protected override string LuaScriptName => "bizhawk_ap_connector.lua";
    protected override string LuaModuleName => "wario_land_4";

    /// wario_land_4.lua reports checks + goal (table generated from the apworld;
    /// inventory-bit math from client.py; mock-verified). Remote-item delivery is
    /// the documented deferred piece (items_handling = 0b001, self-granting ROM).
    public override bool ChecksImplemented => true;

    /// The vanilla cartridge dump the randomizer is built for, by CONTENT
    /// (8 MB + MD5) — never by filename. The patch base_checksum validates the
    /// exact dump before anything is written. The world accepts US/EU and JP
    /// (same ROM mapping, ~25 bytes apart); both are 8 MB.
    protected override IReadOnlyList<RomIdentity> AcceptableBaseRoms => new[]
    {
        new RomIdentity(8 * 1024 * 1024, "5fe47355a33e3fabec2a1607af88a404",
                        "Wario Land 4 (USA, Europe)"),
        new RomIdentity(8 * 1024 * 1024, "99c8ad779a16be513a9fdff502b6f5c2",
                        "Wario Land 4 (Japan)"),
    };

    // ── AP patch ────────────────────────────────────────────────────────────────

    private const string PatchExt = ".apwl4";

    /// Explicit .apwl4 chosen by the user (Settings / drag-drop). Null = auto.
    public string? ApPatchPath { get; private set; }

    protected override void OnSavingSettings(IDictionary<string, object?> bag)
        => bag["ap_patch_path"] = ApPatchPath;

    protected override void OnLoadingSettings(JsonElement root)
    {
        if (root.TryGetProperty("ap_patch_path", out var el)) ApPatchPath = el.GetString();
    }

    /// Set the explicit AP patch (drag-and-drop / room-link import) and persist it.
    public void SetExplicitPatch(string path) { ApPatchPath = path; SaveSettings(); }

    /// ROM safety net: the resolved patch tells us the EXACT vanilla ROM MD5 it
    /// needs — demand that specific dump when ours is missing or the wrong one.
    public override RomRequirement? GetUnmetRomRequirement()
    {
        var patch = SnesApPatchHelper.ResolvePatch(
            PatchExt, ApPatchPath, GetSeedName?.Invoke(), CurrentSlotName, out _);
        string? wantMd5 = patch != null
            ? SnesApPatchHelper.ReadManifestField(patch, "base_checksum") : null;
        bool haveRom = RomPath != null && File.Exists(RomPath);

        if (wantMd5 == null)
            return haveRom ? null
                 : new RomRequirement("Wario Land 4", "GBA",
                       "Wario Land 4 (USA, Europe)",
                       RequiredMd5: null, WrongVersionPresent: false, BuildRomFilter());

        if (haveRom && ComputeMd5(RomPath!).Equals(wantMd5, StringComparison.OrdinalIgnoreCase))
            return null;

        return new RomRequirement("Wario Land 4", "GBA",
            "Wario Land 4 (USA, Europe) — your original cartridge dump",
            wantMd5, WrongVersionPresent: haveRom, BuildRomFilter());
    }

    // ── Session ROM: apply the .apwl4 to a library copy ───────────────────────

    protected override async Task<string?> PrepareSessionRomAsync(
        ApSession session, CancellationToken ct)
    {
        string? patch = SnesApPatchHelper.ResolvePatch(
            PatchExt, ApPatchPath, GetSeedName?.Invoke(), CurrentSlotName, out string how);
        if (patch == null)
        {
            SessionRomNote =
                "[Wario Land 4] No AP patch (.apwl4) found — launching the vanilla " +
                "ROM. Generate the multiworld, then pick the patch in Settings (or " +
                "drop it under " + SnesApPatchHelper.ApOutputDirectory + ").";
            return null;
        }

        var res = await SnesApPatchHelper.ApplyAsync(
            "Wario Land 4", patch, how, RomPath!,
            RomLibraryDirectory, ".gba", ct);
        SessionRomNote = res.Note;
        if (res.OutRom != null) RegisterSeed(res.OutRom, patch);
        return res.OutRom;
    }

    /// Record a produced/reused patched ROM in the seed library. Never throws.
    private void RegisterSeed(string outRom, string patch)
    {
        try
        {
            SeedLibraryStore.Instance.Register(new SeedEntry
            {
                GameId         = GameId,
                PatchedRomPath = outRom,
                PatchPath      = patch,
                SeedName       = SnesApPatchHelper.ParseSeedFromPatch(patch),
                SlotName       = CurrentSlotName ?? "",
                CreatedUtc     = DateTimeOffset.UtcNow,
            });
        }
        catch { /* registry is non-essential to launching */ }
    }
}
