using System;
using System.Collections.Generic;
using System.IO;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using LauncherV2.Core;

namespace LauncherV2.Plugins.Emulated.Games;

// ═══════════════════════════════════════════════════════════════════════════════
// YuGiOh2006Plugin — Archipelago integration for Yu-Gi-Oh! Ultimate Masters:
// World Championship Tournament 2006 (GBA), on the proven BizHawk Lua-pipe bridge.
//
// STATUS: location DETECTION + goal are REAL and SOURCE-DERIVED. The 165-location
// table in yugioh06.lua was GENERATED by parsing worlds/yugioh06/locations.py with
// the world's id math (start_id = 5730000; flag_id = value-1; location_id =
// flag_id + 5730001), and the flag-scan + goal flag + "YUGIOHWCT06" ROM signature
// are replicated exactly from worlds/yugioh06/client_bh.py. Mock-verified through
// MoonSharp against synthetic EWRAM/ROM buffers (signature, save-state gate, known
// flag bits, goal). items_handling = 0b001 — the PATCHED GAME already carries its
// own locally-placed items (the patch writes the items→locations map into ROM at
// 0xF310), so a SOLO seed plays fully and every check is reported in a multiworld.
// Delivering REMOTE multiworld items is the client's guarded EWRAM bitmap write
// (0x5308 items + the 0x6C38/0x5325 money pair); it is deferred (yugioh06.lua
// receive_item is a documented no-op carrying the exact recipe) until it can be
// confirmed in-emulator, rather than shipped unverified — a wrong EWRAM write
// could corrupt the save. Checks + goal flow regardless.
//
// AP PATCH (.apygo06 → .gba): YGO06ProcedurePatch is a standard APProcedurePatch
// container (base_patch.bsdiff4 + token_data.bin, optional draft/ocg bsdiff4
// steps), applied via the shared SnesApPatchHelper — resolve the seed's patch,
// validate the base ROM MD5 (the manifest base_checksum), run apply_appatch.py on
// a library COPY (the original is never modified). Base ROM: the user's own
// Yu-Gi-Oh! WCT 2006 cartridge dump (8 MB), identified by CONTENT (size + MD5) —
// never by filename (§11). The patch is built against the USA dump; the Europe
// dump is also accepted at import (both share the "YUGIOHWCT06" signature), and
// the patch base_checksum demands the exact dump before anything is written.
// ═══════════════════════════════════════════════════════════════════════════════

public sealed class YuGiOh2006Plugin : EmulatorPlugin
{
    public YuGiOh2006Plugin() => LoadSettings();

    // ── Identity ──────────────────────────────────────────────────────────────

    public override string GameId      => "yugioh06";
    public override string DisplayName => "Yu-Gi-Oh! 2006";
    public override string Subtitle    => "GBA · Emulated";

    // Exact AP world id — the `game` string in worlds/yugioh06 (client_bh.py
    // `game = "Yu-Gi-Oh! 2006"`, the Yugioh06World definition, and every
    // Yugioh2006Item/Location). NOT the folder id "yugioh06".
    public override string ApWorldName => "Yu-Gi-Oh! 2006";

    public override string Description =>
        "Yu-Gi-Oh! Ultimate Masters: World Championship Tournament 2006 is the " +
        "definitive GBA card-battle simulator, with over 2000 cards and 90+ " +
        "Challenges. In the Archipelago randomizer, campaign bonuses, Limited and " +
        "Theme Duels, campaign opponents, booster packs and key card collections " +
        "join the multiworld pool. Defeat the final campaign boss to complete your " +
        "goal.";

    public override string ThemeAccentColor => "#6A2C8F";   // Millennium purple

    // ── Emulator specifics ────────────────────────────────────────────────────

    protected override string RomSystem     => "GBA";

    // §14: GBA emulators — BizHawk is the yugioh06 community's verified client
    // target; mGBA/Mesen are the alternatives (shown per their bridge state in the
    // dropdown).
    protected override IReadOnlyList<string> SupportedEmulatorIds =>
        new[] { "bizhawk", "mgba", "mesen" };
    protected override string LuaScriptName => "bizhawk_ap_connector.lua";
    protected override string LuaModuleName => "yugioh06";

    /// yugioh06.lua reports checks + goal (table generated from the apworld; flag
    /// math from client_bh.py; mock-verified). Remote-item delivery is the
    /// documented deferred piece (items_handling = 0b001; the game self-grants its
    /// own placed items, remote items are a guarded EWRAM write awaiting in-emulator
    /// confirmation).
    public override bool ChecksImplemented => true;

    /// The vanilla cartridge dumps the randomizer is built for, by CONTENT
    /// (8 MB + MD5) — never by filename. The USA dump is the patch base; the Europe
    /// dump is accepted at import too (worlds/yugioh06 lists both MD5s and both
    /// share the runtime "YUGIOHWCT06" signature yugioh06.lua verifies). The patch
    /// base_checksum validates the exact dump before anything is written.
    protected override IReadOnlyList<RomIdentity> AcceptableBaseRoms => new[]
    {
        new RomIdentity(8 * 1024 * 1024, "b8a7c976b28172995fe9e465d654297a",
                        "Yu-Gi-Oh! Ultimate Masters: WCT 2006 (USA)"),
        new RomIdentity(8 * 1024 * 1024, "020411d3b08f5639eb8cb878283f84bf",
                        "Yu-Gi-Oh! Ultimate Masters: WCT 2006 (Europe)"),
    };

    // ── AP patch ────────────────────────────────────────────────────────────────

    private const string PatchExt = ".apygo06";

    /// Explicit .apygo06 chosen by the user (Settings / drag-drop). Null = auto.
    public string? ApPatchPath { get; private set; }

    protected override void OnSavingSettings(IDictionary<string, object?> bag)
        => bag["ap_patch_path"] = ApPatchPath;

    protected override void OnLoadingSettings(JsonElement root)
    {
        if (root.TryGetProperty("ap_patch_path", out var el)) ApPatchPath = el.GetString();
    }

    /// Set the explicit AP patch (drag-and-drop / room-link import) and persist it.
    public void SetExplicitPatch(string path) { ApPatchPath = path; SaveSettings(); }

    /// ROM safety net: the resolved patch tells us the EXACT vanilla ROM MD5 it
    /// needs — demand that specific dump when ours is missing or the wrong one.
    public override RomRequirement? GetUnmetRomRequirement()
    {
        var patch = SnesApPatchHelper.ResolvePatch(
            PatchExt, ApPatchPath, GetSeedName?.Invoke(), CurrentSlotName, out _);
        string? wantMd5 = patch != null
            ? SnesApPatchHelper.ReadManifestField(patch, "base_checksum") : null;
        bool haveRom = RomPath != null && File.Exists(RomPath);

        if (wantMd5 == null)
            return haveRom ? null
                 : new RomRequirement("Yu-Gi-Oh! Ultimate Masters: WCT 2006", "GBA",
                       "Yu-Gi-Oh! Ultimate Masters: WCT 2006 (USA)",
                       RequiredMd5: null, WrongVersionPresent: false, BuildRomFilter());

        if (haveRom && ComputeMd5(RomPath!).Equals(wantMd5, StringComparison.OrdinalIgnoreCase))
            return null;

        return new RomRequirement("Yu-Gi-Oh! Ultimate Masters: WCT 2006", "GBA",
            "Yu-Gi-Oh! Ultimate Masters: WCT 2006 — your original cartridge dump",
            wantMd5, WrongVersionPresent: haveRom, BuildRomFilter());
    }

    // ── Session ROM: apply the .apygo06 to a library copy ─────────────────────

    protected override async Task<string?> PrepareSessionRomAsync(
        ApSession session, CancellationToken ct)
    {
        string? patch = SnesApPatchHelper.ResolvePatch(
            PatchExt, ApPatchPath, GetSeedName?.Invoke(), CurrentSlotName, out string how);
        if (patch == null)
        {
            SessionRomNote =
                "[Yu-Gi-Oh! 2006] No AP patch (.apygo06) found — launching the " +
                "vanilla ROM. Generate the multiworld, then pick the patch in " +
                "Settings (or drop it under " +
                SnesApPatchHelper.ApOutputDirectory + ").";
            return null;
        }

        var res = await SnesApPatchHelper.ApplyAsync(
            "Yu-Gi-Oh! 2006", patch, how, RomPath!,
            RomLibraryDirectory, ".gba", ct);
        SessionRomNote = res.Note;
        if (res.OutRom != null) RegisterSeed(res.OutRom, patch);
        return res.OutRom;
    }

    /// Record a produced/reused patched ROM in the seed library. Never throws.
    private void RegisterSeed(string outRom, string patch)
    {
        try
        {
            SeedLibraryStore.Instance.Register(new SeedEntry
            {
                GameId         = GameId,
                PatchedRomPath = outRom,
                PatchPath      = patch,
                SeedName       = SnesApPatchHelper.ParseSeedFromPatch(patch),
                SlotName       = CurrentSlotName ?? "",
                CreatedUtc     = DateTimeOffset.UtcNow,
            });
        }
        catch { /* registry is non-essential to launching */ }
    }
}
