using System;
using System.Collections.Generic;
using System.IO;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using LauncherV2.Core;

namespace LauncherV2.Plugins.Emulated.Games;

// ═══════════════════════════════════════════════════════════════════════════════
// ZeldaIIPlugin — Archipelago integration for Zelda II: The Adventure of Link
// (NES, USA), on the proven BizHawk Lua-pipe bridge.
//
// STATUS: location DETECTION + goal are REAL and SOURCE-DERIVED (the 106-location
// set in zelda2.lua — 95 flag-array + 11 NPC — was GENERATED by parsing
// worlds/zelda2/game_data.py location_table + special_locations; the AP location
// id IS the raw numeric key, no base_id offset, exactly as Client.py iterates
// them; the INVERTED flag-array bit math, the NORMAL NPC bit math, the
// "LEGEND OF ZELDA2" PRG-ROM signature, the game_state ∈ {0x0B,0x05} gate and the
// goal_trigger == 0x04 victory are replicated exactly from worlds/zelda2/Client.py,
// and mock-verified through MoonSharp against synthetic NES memory).
// items_handling = 0b111 — the AP SERVER drives ALL item delivery; the reference
// client writes the next item id into WRAM 0x1A10 and bumps the obtained-count at
// WRAM 0x1A1C, gated on the game's own 0x1A10 mailbox reading 0x00. That guarded
// WRAM write is the documented deferred piece (zelda2.lua receive_item is a no-op)
// until it can be confirmed in-emulator, rather than shipped unverified — a wrong
// WRAM write corrupts the save / desyncs the count. Checks + goal flow regardless.
//
// SOURCE NOTE: this world lives in the MultiworldGG fork of Archipelago
// (github.com/MultiworldGG/MultiworldGG, worlds/zelda2), not in ArchipelagoMW main.
// game string "Zelda II: The Adventure of Link", author "Pink Switch",
// world_version 1.0.1. It is a BizHawkClient world (worlds/zelda2/Client.py
// subclasses BizHawkClient), the direct equivalent of the ff1/mm2/tloz BizHawk
// clients this launcher already ships.
//
// AP PATCH (.apz2 → .nes): an APProcedurePatch container (Z2ProcPatch) whose
// procedure is apply_bsdiff4(z2_base.bsdiff4) → apply_tokens(token_patch.bin) →
// repoint_vanilla_tables. The bsdiff4 + token steps are exactly what the shared
// SnesApPatchHelper runs via Plugins/Scripts/apply_appatch.py; the third step
// (repoint_vanilla_tables) is an apworld-specific Python extension the launcher's
// generic applier does not execute. It only rescales the random-encounter timer
// table from one option byte the patch already wrote — a gameplay tuning pass, not
// a structural requirement for checks/goal/items — so the launcher-applied ROM is
// fully playable and AP-correct; only the encounter cadence may differ from a
// MultiworldGG-applied ROM. The patch is applied to a library COPY (the original
// is never modified, §11), result ".nes".
//
// BASE ROM — IMPORTANT (headered vs headerless): the user supplies their own
// Zelda II (USA) NES cartridge dump, identified by CONTENT — never by filename
// (§11). The standard No-Intro iNES dump is a 16-byte header + 128 KB PRG + 128 KB
// CHR = 262,160 bytes, whole-file MD5 764d36fa8a2450834da5e8194281035a — that is
// the file the player actually has, pinned in AcceptableBaseRoms. The apworld's
// own manifest base_checksum, by contrast, is 88c0493fb1146834836c0ff4f3e06e45 —
// the MD5 of the HEADERLESS ROM (worlds/zelda2/Rom.py strips the iNES header via
// read_headerless_nes_rom BEFORE hashing). The two are the same cartridge, just
// hashed with/without the 16-byte header. We therefore pin and demand the headered
// file MD5 here (what the picker can verify) rather than the manifest's headerless
// value, and zelda2.lua's "LEGEND OF ZELDA2" PRG-ROM signature confirms a real
// Zelda II ROM at launch.
// ═══════════════════════════════════════════════════════════════════════════════

public sealed class ZeldaIIPlugin : EmulatorPlugin
{
    public ZeldaIIPlugin() => LoadSettings();

    // ── Identity ──────────────────────────────────────────────────────────────

    public override string GameId      => "zelda2";
    public override string DisplayName => "Zelda II: The Adventure of Link";
    public override string Subtitle    => "NES · Emulated";
    public override string ApWorldName => "Zelda II: The Adventure of Link";

    public override string Description =>
        "Zelda II: The Adventure of Link, the 1987 NES sequel that took the series " +
        "side-scrolling, with towns, magic spells, experience levels and the " +
        "sword-and-shield combat of the Hyrulean overworld. In the Archipelago " +
        "randomizer the items across all six palaces, the Great Palace and every " +
        "overworld secret, plus the spells the seven sages teach, are shuffled into " +
        "the multiworld pool. Gather the crystals, return them to the palaces, and " +
        "defeat Thunderbird and Dark Link in the Great Palace to claim the Triforce " +
        "of Courage and complete your goal. Bring your own Zelda II: The Adventure " +
        "of Link (USA) NES ROM.";

    public override string ThemeAccentColor => "#C84C0C";   // Zelda II box/HUD orange-red

    // ── Emulator specifics ────────────────────────────────────────────────────

    protected override string RomSystem     => "NES";

    // §14: NES emulators — BizHawk is the zelda2 world's verified client target
    // (worlds/zelda2/Client.py is a BizHawkClient); Mesen is the NES alternative
    // (shown per its bridge state in the dropdown). mGBA is NOT offered — it is a
    // GB/GBA emulator and cannot host NES.
    protected override IReadOnlyList<string> SupportedEmulatorIds =>
        new[] { "bizhawk", "mesen" };
    protected override string LuaScriptName => "bizhawk_ap_connector.lua";
    protected override string LuaModuleName => "zelda2";

    /// zelda2.lua reports checks + goal (tables generated from the apworld; the
    /// inverted flag-array + normal NPC bit math from Client.py; mock-verified).
    /// Remote-item delivery is the documented deferred piece (items_handling =
    /// 0b111, server-driven guarded WRAM writes).
    public override bool ChecksImplemented => true;

    /// The vanilla NES cartridge dump the randomizer is built for, by CONTENT —
    /// never by filename (§11). The standard No-Intro "Zelda II - The Adventure of
    /// Link (USA)" iNES dump is a 16-byte header + 128 KB PRG + 128 KB CHR =
    /// 262,160 bytes, whole-file MD5 764d36fa8a2450834da5e8194281035a — pinned here
    /// as the exact, name-independent detector (this is the file the player has).
    /// The apworld's manifest base_checksum is instead the HEADERLESS MD5
    /// (88c0493fb1146834836c0ff4f3e06e45 — Rom.py strips the iNES header before
    /// hashing), so GetUnmetRomRequirement deliberately demands the headered value
    /// rather than the manifest field; zelda2.lua's "LEGEND OF ZELDA2" PRG-ROM
    /// signature confirms a real Zelda II ROM at launch.
    protected override IReadOnlyList<RomIdentity> AcceptableBaseRoms => new[]
    {
        new RomIdentity(262_160, "764d36fa8a2450834da5e8194281035a",
                        "Zelda II - The Adventure of Link (USA) — NES cartridge dump (iNES, headered)"),
    };

    // ── AP patch ────────────────────────────────────────────────────────────────

    private const string PatchExt = ".apz2";

    /// Explicit .apz2 chosen by the user (Settings / drag-drop). Null = auto.
    public string? ApPatchPath { get; private set; }

    protected override void OnSavingSettings(IDictionary<string, object?> bag)
        => bag["ap_patch_path"] = ApPatchPath;

    protected override void OnLoadingSettings(JsonElement root)
    {
        if (root.TryGetProperty("ap_patch_path", out var el)) ApPatchPath = el.GetString();
    }

    /// Set the explicit AP patch (drag-and-drop / room-link import) and persist it.
    public void SetExplicitPatch(string path) { ApPatchPath = path; SaveSettings(); }

    /// ROM safety net. The .apz2 manifest's base_checksum is the HEADERLESS MD5
    /// (88c0493…), which does NOT equal the headered file the player actually holds
    /// (764d36… — see the class header), so we do NOT compare the manifest field
    /// against the user's file here; that would always mis-fire as "wrong ROM".
    /// Instead we demand the known headered dump by its pinned MD5. The patch's own
    /// base_checksum is still the authoritative gate at apply time — apply_appatch.py
    /// validates it before any byte is written (and a "checksum mismatch" there is
    /// the surfaced error if the supplied ROM is not what the patch expects).
    public override RomRequirement? GetUnmetRomRequirement()
    {
        bool haveRom = RomPath != null && File.Exists(RomPath);
        const string headeredMd5 = "764d36fa8a2450834da5e8194281035a";

        if (haveRom &&
            ComputeMd5(RomPath!).Equals(headeredMd5, StringComparison.OrdinalIgnoreCase))
            return null;

        return new RomRequirement("Zelda II: The Adventure of Link", "NES",
            "Zelda II - The Adventure of Link (USA) — your original NES cartridge dump",
            RequiredMd5: headeredMd5,
            WrongVersionPresent: haveRom, BuildRomFilter());
    }

    // ── Session ROM: apply the .apz2 to a library copy ─────────────────────────

    protected override async Task<string?> PrepareSessionRomAsync(
        ApSession session, CancellationToken ct)
    {
        string? patch = SnesApPatchHelper.ResolvePatch(
            PatchExt, ApPatchPath, GetSeedName?.Invoke(), CurrentSlotName, out string how);
        if (patch == null)
        {
            SessionRomNote =
                "[Zelda II] No AP patch (.apz2) found — launching the vanilla ROM. " +
                "Generate the multiworld, then pick the patch in Settings (or drop " +
                "it under " + SnesApPatchHelper.ApOutputDirectory + ").";
            return null;
        }

        var res = await SnesApPatchHelper.ApplyAsync(
            "Zelda II", patch, how, RomPath!,
            RomLibraryDirectory, ".nes", ct);
        SessionRomNote = res.Note;
        if (res.OutRom != null) RegisterSeed(res.OutRom, patch);
        return res.OutRom;
    }

    /// Record a produced/reused patched ROM in the seed library. Never throws.
    private void RegisterSeed(string outRom, string patch)
    {
        try
        {
            SeedLibraryStore.Instance.Register(new SeedEntry
            {
                GameId         = GameId,
                PatchedRomPath = outRom,
                PatchPath      = patch,
                SeedName       = SnesApPatchHelper.ParseSeedFromPatch(patch),
                SlotName       = CurrentSlotName ?? "",
                CreatedUtc     = DateTimeOffset.UtcNow,
            });
        }
        catch { /* registry is non-essential to launching */ }
    }
}
