using System;
using System.Collections.Generic;
using System.IO;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using LauncherV2.Core;

namespace LauncherV2.Plugins.Emulated.Games;

// ═══════════════════════════════════════════════════════════════════════════════
// ZillionPlugin — Archipelago integration for Zillion (Sega Master System), on the
// proven BizHawk Lua-pipe bridge.
//
// STATUS: location DETECTION + goal are REAL and SOURCE-DERIVED. The check model
// in zillion.lua was GENERATED by parsing worlds/zillion (client.py + id_maps.py +
// config.py) AND the standalone randomizer the client delegates memory access to,
// beauxq/zilliandomizer (zri/memory.py + zri/rai.py + low_resources/ram_info.py):
// every RAM address, the in-game gate, the canister-acquired bit scan, the
// rescue-from-character-status fold, the win condition, and the ROM-to-RAM AP
// signature are replicated exactly, and mock-verified through MoonSharp against
// synthetic SMS memory. items_handling = 0b001 — the PATCHED GAME grants its own
// locally-found items, so a SOLO seed plays fully and every check is reported in a
// multiworld. Delivering OTHER players' items is the client's guarded RAM write to
// the 0xC2E0 item-pickup queue; it is deferred (zillion.lua receive_item is a
// no-op) until it can be confirmed in-emulator, rather than shipped unverified.
//
// PER-SEED LOCATION MAP — IMPORTANT: unlike most ROM games, Zillion's location ids
// are NOT a fixed flag array. Which physical canister (room + bit) maps to which
// AP location id is RANDOMIZED PER SEED and delivered in the `Connected` packet's
// slot_data as `loc_mem_to_id` (+ `rescues` + `start_char`). The launcher already
// forwards slot_data verbatim in ap_config.json, and zillion.lua reads it to build
// the map at init — so no static location table is possible or correct here.
//
// AP PATCH (.apzl → .sms): a standard APAutoPatchInterface container, applied via
// the shared SnesApPatchHelper (resolve the seed's patch, validate the base ROM
// MD5, run apply_appatch.py on a library COPY — the original is never modified).
// Base ROM: the user's own "Zillion (UE) [!]" cartridge dump (128 KB / 131072 B,
// MD5 d4bf9e7bcf9a48da53785d2ae7bc4270 — the patch.US_HASH), identified by CONTENT
// (size + MD5) — never by filename (§11).
//
// HOW ZILLION IS NORMALLY PLAYED: the reference client targets RetroArch (its /sms
// command, READ_CORE_RAM over UDP). The SMS RAM it reads (Z80 0xC000..0xDFFF) is
// the same memory BizHawk's SMSHawk core exposes as "System Bus" / "Main RAM", so
// the proven BizHawk Lua bridge drives the identical check/goal logic — see
// zillion.lua's MEMORY MODEL header.
// ═══════════════════════════════════════════════════════════════════════════════

public sealed class ZillionPlugin : EmulatorPlugin
{
    public ZillionPlugin() => LoadSettings();

    // ── Identity ──────────────────────────────────────────────────────────────

    public override string GameId      => "zillion";
    public override string DisplayName => "Zillion";
    public override string Subtitle    => "SMS · Emulated";
    public override string ApWorldName => "Zillion";

    public override string Description =>
        "Zillion is the 1987 8-bit Sega Master System metroidvania based on the " +
        "anime Akai Koudan Zillion. In the Archipelago randomizer, the ID Cards, " +
        "floppy disks, Opa-Opas, gun power-ups and rescues hidden in canisters " +
        "across the base join the multiworld pool, with the three playable " +
        "characters shuffled in. Reach and defeat the final boss to complete your " +
        "goal.";

    public override string ThemeAccentColor => "#1E6FB8";   // Zillion SMS blue

    // ── Emulator specifics ────────────────────────────────────────────────────

    protected override string RomSystem     => "SMS";

    // §14: SMS emulators — BizHawk (SMSHawk) is wired for the Lua bridge; MesenCE
    // also hosts SMS and is the alternative (shown per its bridge state in the
    // dropdown). mGBA is NOT offered — it is a GB/GBA emulator and cannot host SMS.
    protected override IReadOnlyList<string> SupportedEmulatorIds =>
        new[] { "bizhawk", "mesen" };
    protected override string LuaScriptName => "bizhawk_ap_connector.lua";
    protected override string LuaModuleName => "zillion";

    /// zillion.lua reports checks + goal (check model parsed from the apworld +
    /// the zilliandomizer memory source; mock-verified). The per-seed canister→id
    /// map is built at runtime from slot_data. Remote-item delivery is the
    /// documented deferred piece (items_handling = 0b001, game self-grants locals).
    public override bool ChecksImplemented => true;

    /// The vanilla cartridge dump the randomizer is built for, by CONTENT
    /// (128 KB + MD5) — never by filename. "Zillion (UE) [!]" (a.k.a. USA v1.1)
    /// is the exact dump patch.US_HASH validates before anything is written.
    protected override IReadOnlyList<RomIdentity> AcceptableBaseRoms => new[]
    {
        new RomIdentity(131_072, "d4bf9e7bcf9a48da53785d2ae7bc4270",
                        "Zillion (UE) [!] — Sega Master System cartridge dump"),
    };

    // ── AP patch ────────────────────────────────────────────────────────────────

    private const string PatchExt = ".apzl";

    /// Explicit .apzl chosen by the user (Settings / drag-drop). Null = auto.
    public string? ApPatchPath { get; private set; }

    protected override void OnSavingSettings(IDictionary<string, object?> bag)
        => bag["ap_patch_path"] = ApPatchPath;

    protected override void OnLoadingSettings(JsonElement root)
    {
        if (root.TryGetProperty("ap_patch_path", out var el)) ApPatchPath = el.GetString();
    }

    /// Set the explicit AP patch (drag-and-drop / room-link import) and persist it.
    public void SetExplicitPatch(string path) { ApPatchPath = path; SaveSettings(); }

    /// ROM safety net: the resolved patch tells us the EXACT vanilla ROM MD5 it
    /// needs — demand that specific dump when ours is missing or the wrong one.
    public override RomRequirement? GetUnmetRomRequirement()
    {
        var patch = SnesApPatchHelper.ResolvePatch(
            PatchExt, ApPatchPath, GetSeedName?.Invoke(), CurrentSlotName, out _);
        string? wantMd5 = patch != null
            ? SnesApPatchHelper.ReadManifestField(patch, "base_checksum") : null;
        bool haveRom = RomPath != null && File.Exists(RomPath);

        if (wantMd5 == null)
            return haveRom ? null
                 : new RomRequirement("Zillion", "SMS",
                       "Zillion (UE) [!] (Sega Master System)",
                       RequiredMd5: null, WrongVersionPresent: false, BuildRomFilter());

        if (haveRom && ComputeMd5(RomPath!).Equals(wantMd5, StringComparison.OrdinalIgnoreCase))
            return null;

        return new RomRequirement("Zillion", "SMS",
            "Zillion (UE) [!] — your original Sega Master System cartridge dump",
            wantMd5, WrongVersionPresent: haveRom, BuildRomFilter());
    }

    // ── Session ROM: apply the .apzl to a library copy ────────────────────────

    protected override async Task<string?> PrepareSessionRomAsync(
        ApSession session, CancellationToken ct)
    {
        string? patch = SnesApPatchHelper.ResolvePatch(
            PatchExt, ApPatchPath, GetSeedName?.Invoke(), CurrentSlotName, out string how);
        if (patch == null)
        {
            SessionRomNote =
                "[Zillion] No AP patch (.apzl) found — launching the vanilla ROM. " +
                "Generate the multiworld, then pick the patch in Settings (or drop " +
                "it under " + SnesApPatchHelper.ApOutputDirectory + ").";
            return null;
        }

        var res = await SnesApPatchHelper.ApplyAsync(
            "Zillion", patch, how, RomPath!,
            RomLibraryDirectory, ".sms", ct);
        SessionRomNote = res.Note;
        if (res.OutRom != null) RegisterSeed(res.OutRom, patch);
        return res.OutRom;
    }

    /// Record a produced/reused patched ROM in the seed library. Never throws.
    private void RegisterSeed(string outRom, string patch)
    {
        try
        {
            SeedLibraryStore.Instance.Register(new SeedEntry
            {
                GameId         = GameId,
                PatchedRomPath = outRom,
                PatchPath      = patch,
                SeedName       = SnesApPatchHelper.ParseSeedFromPatch(patch),
                SlotName       = CurrentSlotName ?? "",
                CreatedUtc     = DateTimeOffset.UtcNow,
            });
        }
        catch { /* registry is non-essential to launching */ }
    }
}
