// GENERATED by tools/gen_world_relay_ids.py -- do not edit by hand.
//
// Read from star_fox_64.apworld, world version 0.4.1.
// These are ids and a protocol version, generated from the world's own
// tables the same way a RAM map is. No world code is carried here.

using System.Collections.Generic;

namespace LauncherV2.Core.Worlds;

internal static class StarFox64Ids
{
    /// The ROM answers the handshake with this; a mismatch means the
    /// player's ROM was built by a different version of the world.
    public const uint RomVersion = 0x000401;   // 0.4.1

    /// Reporting THIS location is the world's way of saying the goal is done.
    public const long GoalLocationId = 0;

    /// slot_data option name -> the id the ROM expects.
    public static readonly IReadOnlyDictionary<string, ushort> OptionIds =
        new Dictionary<string, ushort>
        {
            ["deathlink"] = 0,
            ["ringlink"] = 1,
            ["victory_condition"] = 2,
            ["required_medals"] = 3,
            ["level_access"] = 4,
            ["shuffle_starting_level"] = 5,
            ["shuffle_medals"] = 6,
            ["shuffle_checkpoints"] = 7,
            ["accomplished_sends_complete"] = 8,
            ["radio_rando"] = 9,
            ["engine_glow"] = 10,
            ["default_lives"] = 11,
            ["medal_corneria"] = 12,
            ["medal_meteo"] = 13,
            ["medal_sector_y"] = 14,
            ["medal_katina"] = 15,
            ["medal_fortuna"] = 16,
            ["medal_aquas"] = 17,
            ["medal_solar"] = 18,
            ["medal_sector_x"] = 19,
            ["medal_zoness"] = 20,
            ["medal_titania"] = 21,
            ["medal_sector_z"] = 22,
            ["medal_macbeth"] = 23,
            ["medal_area_6"] = 24,
            ["medal_bolse"] = 25,
            ["medal_venom"] = 26,
        };
}
