using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Win32;
using LauncherV2.Core;

// NOTE on type qualification (BUILD GOTCHA — CS0104):
// This project sets BOTH <UseWPF>true</UseWPF> and <UseWindowsForms>true</UseWindowsForms>.
// That makes a long list of simple type names ambiguous between WPF and WinForms
// (Clipboard, MessageBox, Application, Color, Brush(es), Button, TextBox, CheckBox,
// Orientation, FontWeights, HorizontalAlignment, Cursors, Thickness, OpenFileDialog…).
// To avoid CS0104 this file deliberately does NOT do `using System.Windows.Controls;` /
// `using System.Windows.Media;` — every WPF UI type below is written FULLY QUALIFIED
// (System.Windows.Controls.*, System.Windows.Media.*, System.Windows.MessageBox, …).
// It also does NOT declare any file-level `using X = System.Windows...;` alias
// (CS1537 — GlobalUsings.cs already aliases the short names; a local alias would
// conflict). Bare names from GlobalUsings, or full qualification, only.
// (OpenFolderDialog is unambiguous — it lives only in Microsoft.Win32 — so it is
// referenced by its short name with `using Microsoft.Win32;` above.)

namespace LauncherV2.Plugins.AgeOfEmpires2DE;

// ═══════════════════════════════════════════════════════════════════════════════
// AgeOfEmpires2DEPlugin — detect / guide / launch for "Age of Empires II:
// Definitive Edition" (Xbox Game Studios / Microsoft, 2019) played through the
// COMMUNITY Archipelago integration by dmwever and Stefrex1. This is a
// "ConnectsItself" integration: the bundled "Age of Empires II: DE Client"
// (a Python component inside the player's Archipelago release) owns the AP slot
// and relays to the running game — the launcher must NOT hold its own ApClient
// on the slot.
//
// ── HONEST REALITY CHECK (2026-06-15) — verified against dmwever/Archipelago ──
// The integration is a COMMUNITY CUSTOM apworld (NOT in AP-main), distributed via:
//   https://github.com/dmwever/Ageipelago/releases
//
// The pieces are:
//
//   * THE BASE GAME is the user's own legally-owned Age of Empires II: Definitive
//     Edition (Steam appid 813780, Xbox Game Studios). Paid software — the launcher
//     must not, and does not, ship or recreate it.
//
//   * THE APWORLD FILE is the .apworld from Ageipelago releases. The player
//     installs it into their Archipelago custom_worlds folder (or via the AP
//     Launcher) before generating a room. This is NOT bundled by this launcher.
//
//   * THE "Age of Empires II: DE Client" is a PYTHON client SHIPPED INSIDE the
//     player's Archipelago release. It is registered in worlds/age2de/__init__.py
//     as  Component("Age of Empires II: DE Client", func=run_client,
//     component_type=Type.CLIENT)  and launched as component "Age2Client".
//     VERIFIED against dmwever/Archipelago worlds/age2de/__init__.py.
//     The client holds the AP server connection and communicates with the running
//     game via FILE IPC: it reads/writes the user's AoE2 DE user folder
//     (C:\Users\<USER>\Games\Age of Empires 2 DE\<ID>\) — saved game files and
//     a dedicated AP data folder that the game's mod reads. VERIFIED from the
//     client source (ApClient.py/GameClient.py).
//
//   * THE MOD is installed via the AoE2 DE Steam Workshop or bundled with the
//     apworld. It runs inside the game engine and communicates with the client
//     via the user folder file IPC. The player must subscribe/install this mod
//     and enable it in-game. The per-room .aoe2scenario files generated by the
//     apworld are placed into the user's scenario folder.
//
//   * CONNECTION: the player enters server / slot / password INTO THE "Age of
//     Empires II: DE Client" — there is no connection arg on the game and no
//     config file this launcher can pre-write. Hence ConnectsItself = true: the
//     launcher must NOT also sit on the slot or the two would kick each other.
//
// ── WHAT THIS PLUGIN HONESTLY DOES ───────────────────────────────────────────
//   1. DETECT the Steam AoE2 DE install (appid 813780) via the standard
//      registry → libraryfolders.vdf → appmanifest_813780.acf → common pipeline.
//      A manual root-dir OVERRIDE (folder picker) is supported and persisted in
//      this plugin's OWN sidecar (Games/ROMs/age2de/age2de_launcher.json).
//   2. DETECT the AoE2 DE user folder under C:\Users\<USER>\Games\Age of
//      Empires 2 DE\  (the <ID> subfolder), which the AP client must be
//      configured to point at. A manual override is also supported.
//   3. LOCATE the bundled AP client in the user's Archipelago install (READ-ONLY:
//      C:\ProgramData\Archipelago is NEVER written). Prefer any exe matching
//      "*age*2*client*.exe" or "*aoe2*client*.exe"; fall back to
//      ArchipelagoLauncher.exe (which dispatches by component name).
//   4. LAUNCH (best effort): start the "Age of Empires II: DE Client" (it owns
//      the AP slot + relays to the game), then open AoE2 DE (via the Steam URL
//      steam://rungameid/813780 or the detected exe).
//   5. GUIDE the per-room .aoe2scenario setup step and mod-enable step honestly.
//   6. NEVER claim an install exists when it does not; never modify the Steam copy.
//
// ── GAME STRING (VERIFIED against dmwever/Archipelago worlds/age2de/__init__.py) ─
//   AGE2_DE = "Age Of Empires II: Definitive Edition"
//   class Age2World: game = AGE2_DE
//   Component("Age of Empires II: DE Client", func=run_client, Type.CLIENT)
// ═══════════════════════════════════════════════════════════════════════════════

public sealed class AgeOfEmpires2DEPlugin : IGamePlugin
{
    // ── Constants — Steam / AP facts (verified 2026-06-15) ─────────────────────

    /// AoE2 DE Steam application id (VERIFIED — store.steampowered.com/app/813780).
    private const string SteamAppId = "813780";
    private static readonly string SteamRunUrl = "steam://rungameid/" + SteamAppId;

    /// Standard Steam install subfolder for AoE2 DE.
    private const string SteamCommonFolderName = "AoE2DE";

    /// Candidate exe names inside the AoE2 DE install (any one present = valid).
    private static readonly string[] GameExeNames =
    {
        "AoE2DE_s.exe",    // Steam release main exe
        "AoE2DE.exe",
    };

    /// The %USERPROFILE%\Games path root where AoE2 DE stores per-user data. Each
    /// user profile gets a subfolder named with a numeric ID.
    private const string GamesRootFolderName = "Age of Empires 2 DE";

    /// Default Archipelago install root on Windows (READ-ONLY).
    private const string DefaultArchipelagoRoot = @"C:\ProgramData\Archipelago";

    /// Generic AP launcher exe that dispatches components by name.
    private const string ArchipelagoLauncherExe = "ArchipelagoLauncher.exe";

    /// The exact AP component name for the DE client (VERIFIED).
    private const string Age2ClientComponentName = "Age of Empires II: DE Client";

    /// Community apworld release page.
    private const string ApworldReleasesUrl =
        "https://github.com/dmwever/Ageipelago/releases";

    /// GitHub releases API for news feed.
    private const string ApworldReleasesApiUrl =
        "https://api.github.com/repos/dmwever/Ageipelago/releases";

    /// AoE2 DE on Steam.
    private const string SteamStoreUrl =
        "https://store.steampowered.com/app/813780/Age_of_Empires_II_Definitive_Edition/";

    /// Archipelago releases — the Age2 client ships inside this download.
    private const string ArchipelagoReleasesUrl =
        "https://github.com/ArchipelagoMW/Archipelago/releases";

    private const string ArchipelagoSite = "https://archipelago.gg";

    private static readonly HttpClient _http = new()
    {
        Timeout = TimeSpan.FromMinutes(2),
        DefaultRequestHeaders = { { "User-Agent", "Archipelago-Launcher/2.0" } }
    };

    // ── IGamePlugin — Identity ────────────────────────────────────────────────

    public string GameId      => "age2de";
    public string DisplayName => "Age of Empires II: DE";
    public string Subtitle    => "Native PC · Archipelago";

    /// EXACT AP game string — VERIFIED against dmwever/Archipelago worlds/age2de/__init__.py:
    ///   AGE2_DE = "Age Of Empires II: Definitive Edition"
    ///   class Age2World: game = AGE2_DE
    public string ApWorldName => "Age Of Empires II: Definitive Edition";

    public string IconPath =>
        Path.Combine(AppContext.BaseDirectory, "Assets", "age2de.png");

    public string ThemeAccentColor => "#6B3A1F";   // AoE2 parchment-brown
    public string[] GameBadges     => new[] { "Requires AoE2 DE", "Custom APWorld" };

    public string Description =>
        "Age of Empires II: Definitive Edition is Microsoft's remaster of the classic " +
        "medieval real-time strategy game — build a civilization, command armies, and " +
        "conquer history across 35+ campaigns. This integration is a COMMUNITY-MADE " +
        "Archipelago world by dmwever and Stefrex1 (not yet in AP main), distributed " +
        "as a custom .apworld file from Ageipelago on GitHub. You bring your own copy " +
        "of AoE2 DE (Steam appid 813780); install the custom apworld into Archipelago; " +
        "enable the AP mod in-game; place your per-room .aoe2scenario file in your " +
        "scenario folder; and connect using Archipelago's bundled \"Age of Empires II: " +
        "DE Client\", which holds the multiworld connection and relays checks and items " +
        "through file IPC in your AoE2 DE user folder. The launcher detects your " +
        "install and can start the client and the game with one click.";

    public string? VideoPreviewUrl => null;
    public string[] ScreenshotUrls => Array.Empty<string>();

    // ── Version state ─────────────────────────────────────────────────────────
    // The independently-versioned part of this integration is the community apworld
    // (Ageipelago). No single version stamp this plugin can author honestly from the
    // running install; the news feed surfaces the release versions instead.
    public string? InstalledVersion => null;
    public string? AvailableVersion => null;

    /// "Installed" == a valid AoE2 DE install was found (Steam or override).
    public bool IsInstalled => ResolveSteamDir() != null;
    public bool IsRunning   { get; private set; }

    public string GameDirectory => ResolveSteamDir() ?? "";

    // ── Paths ─────────────────────────────────────────────────────────────────

    private string SettingsSidecarDir
        => Path.Combine(AppContext.BaseDirectory, "Games", "ROMs", GameId);
    private string SettingsSidecarPath
        => Path.Combine(SettingsSidecarDir, "age2de_launcher.json");

    // ── Internal override state ────────────────────────────────────────────────

    private string? _overrideRootDir;    // AoE2 DE Steam install root override
    private string? _overrideUserDir;    // AoE2 DE user-profile folder override
    private string? _overrideApDir;      // Archipelago install override (READ-ONLY)

    private Process? _gameProcess;
    private Process? _clientProcess;

    // ── AP bridge events (ConnectsItself — inert) ─────────────────────────────
    // The "Age of Empires II: DE Client" owns the AP slot; the launcher relays
    // nothing. These three events exist only for interface compatibility.
#pragma warning disable CS0067
    public event Action<long[]>? LocationsChecked;
    public event Action?         GoalCompleted;
    public event Action<int>?    GameExited;
#pragma warning restore CS0067

    // ── Constructor — restore overrides from sidecar ──────────────────────────

    public AgeOfEmpires2DEPlugin()
    {
        try
        {
            var s = LoadSettings();
            if (!string.IsNullOrWhiteSpace(s.RootDirOverride) && Directory.Exists(s.RootDirOverride))
                _overrideRootDir = s.RootDirOverride;
            if (!string.IsNullOrWhiteSpace(s.UserDirOverride) && Directory.Exists(s.UserDirOverride))
                _overrideUserDir = s.UserDirOverride;
            if (!string.IsNullOrWhiteSpace(s.ApInstallOverride) && Directory.Exists(s.ApInstallOverride))
                _overrideApDir = s.ApInstallOverride;
        }
        catch { /* fall back to detection only */ }
    }

    // ── Lifecycle — CheckForUpdate ────────────────────────────────────────────

    public Task CheckForUpdateAsync(CancellationToken ct = default)
        => Task.CompletedTask;

    // ── Lifecycle — InstallOrUpdate (guided setup) ────────────────────────────
    // This plugin does NOT download the paid game, the apworld, or the mod.
    // It provides honest status and step-by-step guidance.

    public Task InstallOrUpdateAsync(
        IProgress<(int Pct, string Msg)> progress,
        CancellationToken ct = default)
    {
        progress.Report((10, "Checking for your Age of Empires II: DE install..."));

        string? steamDir  = ResolveSteamDir();
        string? userDir   = ResolveUserDir();
        string? client    = ResolveBundledClient();

        var sb = new StringBuilder();

        if (steamDir != null)
            sb.Append("Your AoE2 DE install was detected at \"").Append(steamDir).Append("\". ");
        else
            sb.Append("Age of Empires II: Definitive Edition was not detected. Install it via " +
                      "Steam (appid ").Append(SteamAppId).Append("), or set its folder in Settings. ");

        if (userDir != null)
            sb.Append("AoE2 DE user folder: \"").Append(userDir).Append("\". ");
        else
            sb.Append("AoE2 DE user folder not found automatically (usually at " +
                      @"C:\Users\<YOU>\Games\Age of Empires 2 DE\<ID>\). " +
                      "Set it in Settings so the AP client can locate it. ");

        if (client != null)
            sb.Append("The Age of Empires II: DE Client was located in your Archipelago install. ");
        else
            sb.Append("The Archipelago install was not found. Make sure Archipelago is installed " +
                      "(default: C:\\ProgramData\\Archipelago) and set the folder in Settings if " +
                      "it is elsewhere. ");

        sb.Append("\n\nSetup steps:\n");
        sb.Append("1) Download the Ageipelago .apworld from GitHub releases and install it into " +
                  "Archipelago (drop it into your custom_worlds folder, or use the AP Launcher).\n");
        sb.Append("2) Generate a multiworld room — this creates a .aoe2scenario file for your " +
                  "slot. Place it in your AoE2 DE user scenarios folder " +
                  @"(<ID>\resources\_common\scenario\)." + "\n");
        sb.Append("3) Subscribe to and enable the Archipelago mod in AoE2 DE (Steam Workshop " +
                  "or bundled with the apworld). Enable it in the in-game mod manager.\n");
        sb.Append("4) Press Play here (or run \"Age of Empires II: DE Client\" from the " +
                  "Archipelago Launcher) and enter your server, slot, and password in the client.\n");
        sb.Append("5) Load the generated scenario in AoE2 DE to start your multiworld session.");

        progress.Report((100, sb.ToString()));
        return Task.CompletedTask;
    }

    // ── Lifecycle — Verify ────────────────────────────────────────────────────

    public Task<bool> VerifyInstallAsync(CancellationToken ct = default)
        => Task.FromResult(IsInstalled);

    // ── Existing-install validation (override picker) ─────────────────────────

    public string? ValidateExistingInstall(string folder)
    {
        if (string.IsNullOrWhiteSpace(folder) || !Directory.Exists(folder))
            return "That folder does not exist. Pick your AoE2 DE install folder " +
                   "(the one containing AoE2DE_s.exe).";
        if (LooksLikeAoE2Root(folder)) return null;

        try
        {
            string nested = Path.Combine(folder, SteamCommonFolderName);
            if (LooksLikeAoE2Root(nested)) return null;
        }
        catch { /* ignore */ }

        return "That does not look like an Age of Empires II: DE installation. Pick " +
               "the folder that contains AoE2DE_s.exe (usually " +
               @"...\steamapps\common\AoE2DE).";
    }

    // ── Lifecycle — Launch ────────────────────────────────────────────────────
    // ConnectsItself = true: start the Python client (it owns the slot), then open
    // AoE2 DE. The player enters server/slot/password inside the client.

    public Task LaunchAsync(ApSession session, CancellationToken ct = default)
    {
        _ = session; // connection is entered in the Age2 Client, not via args here

        string? client = ResolveBundledClient();
        if (client != null)
        {
            try { StartBundledClient(client); } catch { /* non-fatal */ }
        }

        try { StartAoE2DE(); } catch { /* non-fatal */ }

        return Task.CompletedTask;
    }

    /// AoE2 DE is a standalone game — plain (non-AP) play is fully supported.
    public bool SupportsStandalone => true;

    /// The "Age of Empires II: DE Client" owns the AP slot (ConnectsItself).
    public bool ConnectsItself => true;

    public Task LaunchStandaloneAsync(CancellationToken ct = default)
    {
        // Plain AoE2 DE — do not start the AP client.
        StartAoE2DE();
        return Task.CompletedTask;
    }

    public Task StopAsync()
    {
        try { _gameProcess?.Kill(entireProcessTree: true); } catch { }
        try { _clientProcess?.Kill(entireProcessTree: true); } catch { }
        _gameProcess   = null;
        _clientProcess = null;
        IsRunning      = false;
        return Task.CompletedTask;
    }

    // ── AP bridge — inert (ConnectsItself) ───────────────────────────────────

    public Task ReceiveItemsAsync(ApNetworkItem[] items, int index, CancellationToken ct = default)
    {
        // The Age2 client receives items from AP directly and relays them to the game
        // via file IPC in the user folder; nothing for the launcher to forward.
        return Task.CompletedTask;
    }

    public void OnApStateChanged(ApConnectionState state)
    {
        // The Age2 client renders its own connection state; no launcher HUD channel.
    }

    // ── Settings UI ───────────────────────────────────────────────────────────

    public System.Windows.UIElement? CreateSettingsPanel()
    {
        var muted   = new System.Windows.Media.SolidColorBrush(System.Windows.Media.Color.FromRgb(0x72, 0x7A, 0x99));
        var fg      = new System.Windows.Media.SolidColorBrush(System.Windows.Media.Color.FromRgb(0xCC, 0xD0, 0xE0));
        var success = new System.Windows.Media.SolidColorBrush(System.Windows.Media.Color.FromRgb(0x4C, 0xAF, 0x50));
        var warn    = new System.Windows.Media.SolidColorBrush(System.Windows.Media.Color.FromRgb(0xD0, 0xA0, 0x40));
        var link    = new System.Windows.Media.SolidColorBrush(System.Windows.Media.Color.FromRgb(0x60, 0x9A, 0xFF));

        var panel = new System.Windows.Controls.StackPanel
            { Margin = new System.Windows.Thickness(0, 0, 0, 20) };

        // ── Honesty header ────────────────────────────────────────────────
        panel.Children.Add(new System.Windows.Controls.TextBlock
        {
            Text =
                "This is a COMMUNITY APWorld (not yet in AP main) by dmwever and Stefrex1. " +
                "You need your own AoE2 DE (Steam), the Ageipelago .apworld installed in " +
                "Archipelago, and Archipelago's bundled \"Age of Empires II: DE Client\" to " +
                "connect. The launcher detects your install, starts the client and the game, " +
                "but you enter your server/slot/password inside the client. Your Archipelago " +
                "install is only ever READ to find the client — nothing is written there.",
            FontSize = 11, Foreground = warn,
            TextWrapping = System.Windows.TextWrapping.Wrap,
            Margin = new System.Windows.Thickness(0, 0, 0, 14),
        });

        // ── Section: Steam install (root dir) ─────────────────────────────
        panel.Children.Add(SectionHeader("AGE OF EMPIRES II: DE INSTALL (ROOT DIRECTORY)", muted));

        string? rootDir = ResolveSteamDir();
        panel.Children.Add(new System.Windows.Controls.TextBlock
        {
            Text = rootDir != null
                ? "Detected (appid " + SteamAppId + "):\n" + rootDir
                : "Not detected via Steam. Install AoE2 DE (appid " + SteamAppId +
                  ") or set the folder below.",
            FontSize = 11, Foreground = rootDir != null ? success : muted,
            TextWrapping = System.Windows.TextWrapping.Wrap,
            Margin = new System.Windows.Thickness(0, 0, 0, 8),
        });

        var rootRow = new System.Windows.Controls.DockPanel
            { Margin = new System.Windows.Thickness(0, 0, 0, 4) };
        var rootBox = new System.Windows.Controls.TextBox
        {
            Text = _overrideRootDir ?? rootDir ?? "", IsReadOnly = true, FontSize = 12,
            Margin     = new System.Windows.Thickness(0, 0, 8, 0),
            Background = new System.Windows.Media.SolidColorBrush(System.Windows.Media.Color.FromRgb(0x0C, 0x10, 0x20)),
            Foreground = fg,
            BorderBrush = new System.Windows.Media.SolidColorBrush(System.Windows.Media.Color.FromRgb(0x1E, 0x22, 0x33)),
            ToolTip    = "Your AoE2 DE install folder (contains AoE2DE_s.exe). Detected from " +
                         "Steam automatically; set it here to override.",
        };
        var rootBtn = MakeButton("Select folder...", 120, fg);
        rootBtn.Click += (_, _) =>
        {
            var dlg = new OpenFolderDialog
            {
                Title            = "Select your AoE2 DE install folder (contains AoE2DE_s.exe)",
                InitialDirectory = Directory.Exists(_overrideRootDir ?? rootDir ?? "")
                                   ? (_overrideRootDir ?? rootDir!) : AppContext.BaseDirectory,
            };
            if (dlg.ShowDialog() != true) return;
            string picked = dlg.FolderName;
            string? bad   = ValidateExistingInstall(picked);
            if (bad != null)
            {
                System.Windows.MessageBox.Show(bad, "Not an AoE2 DE folder",
                    System.Windows.MessageBoxButton.OK,
                    System.Windows.MessageBoxImage.Warning);
                return;
            }
            if (!LooksLikeAoE2Root(picked))
            {
                string nested = Path.Combine(picked, SteamCommonFolderName);
                if (LooksLikeAoE2Root(nested)) picked = nested;
            }
            _overrideRootDir = picked;
            rootBox.Text     = picked;
            SaveRootDirOverride(picked);
        };
        System.Windows.Controls.DockPanel.SetDock(rootBtn,
            System.Windows.Controls.Dock.Right);
        rootRow.Children.Add(rootBtn);
        rootRow.Children.Add(rootBox);
        panel.Children.Add(rootRow);

        // ── Section: AoE2 DE user folder ──────────────────────────────────
        panel.Children.Add(SectionHeader("AGE OF EMPIRES II: DE USER FOLDER", muted));

        string? userDir = ResolveUserDir();
        panel.Children.Add(new System.Windows.Controls.TextBlock
        {
            Text = userDir != null
                ? "Detected:\n" + userDir
                : "Not found automatically. It is usually at\n" +
                  @"C:\Users\<YOU>\Games\Age of Empires 2 DE\<ID>\" +
                  "\nThe AP client must be pointed at this folder. Set it below.",
            FontSize = 11, Foreground = userDir != null ? success : muted,
            TextWrapping = System.Windows.TextWrapping.Wrap,
            Margin = new System.Windows.Thickness(0, 0, 0, 8),
        });

        var userRow = new System.Windows.Controls.DockPanel
            { Margin = new System.Windows.Thickness(0, 0, 0, 4) };
        var userBox = new System.Windows.Controls.TextBox
        {
            Text = _overrideUserDir ?? userDir ?? "", IsReadOnly = true, FontSize = 12,
            Margin      = new System.Windows.Thickness(0, 0, 8, 0),
            Background  = new System.Windows.Media.SolidColorBrush(System.Windows.Media.Color.FromRgb(0x0C, 0x10, 0x20)),
            Foreground  = fg,
            BorderBrush = new System.Windows.Media.SolidColorBrush(System.Windows.Media.Color.FromRgb(0x1E, 0x22, 0x33)),
            ToolTip     = "Your AoE2 DE user folder " +
                          @"(C:\Users\<YOU>\Games\Age of Empires 2 DE\<ID>\). " +
                          "The AP client reads/writes here to relay checks and items.",
        };
        var userBtn = MakeButton("Select folder...", 120, fg);
        userBtn.Click += (_, _) =>
        {
            var dlg = new OpenFolderDialog
            {
                Title = "Select your AoE2 DE user folder " +
                        @"(…\Games\Age of Empires 2 DE\<ID>\)",
                InitialDirectory = Directory.Exists(_overrideUserDir ?? userDir ?? "")
                                   ? (_overrideUserDir ?? userDir!) : AppContext.BaseDirectory,
            };
            if (dlg.ShowDialog() != true) return;
            _overrideUserDir = dlg.FolderName;
            userBox.Text     = dlg.FolderName;
            SaveUserDirOverride(dlg.FolderName);
        };
        System.Windows.Controls.DockPanel.SetDock(userBtn,
            System.Windows.Controls.Dock.Right);
        userRow.Children.Add(userBtn);
        userRow.Children.Add(userBox);
        panel.Children.Add(userRow);
        panel.Children.Add(new System.Windows.Controls.TextBlock
        {
            Text = "The Age of Empires II: DE Client reads and writes this folder to pass " +
                   "checks and items between Archipelago and the running game. If the client " +
                   "says \"user folder not set\", point it here with /set_user_folder.",
            FontSize = 11, Foreground = muted,
            TextWrapping = System.Windows.TextWrapping.Wrap,
            Margin = new System.Windows.Thickness(0, 6, 0, 12),
        });

        // ── Section: Archipelago install (READ-ONLY) ───────────────────────
        panel.Children.Add(SectionHeader("ARCHIPELAGO INSTALL (READ-ONLY — TO FIND THE CLIENT)", muted));

        string? apRoot = ResolveArchipelagoRoot();
        string? client = ResolveBundledClient();
        panel.Children.Add(new System.Windows.Controls.TextBlock
        {
            Text = client != null
                ? "Age of Empires II: DE Client located:\n" + client
                : apRoot != null
                    ? "Archipelago install found at \"" + apRoot + "\", but the Age2 client " +
                      "exe was not located inside it. You can still run it from the " +
                      "Archipelago Launcher (open \"Age of Empires II: DE Client\")."
                    : "Archipelago install not found. Set its folder below, or run the client " +
                      "from the Archipelago Launcher directly.",
            FontSize = 11, Foreground = client != null ? success : muted,
            TextWrapping = System.Windows.TextWrapping.Wrap,
            Margin = new System.Windows.Thickness(0, 0, 0, 6),
        });

        var apRow = new System.Windows.Controls.DockPanel
            { Margin = new System.Windows.Thickness(0, 0, 0, 4) };
        var apBox = new System.Windows.Controls.TextBox
        {
            Text = _overrideApDir ?? apRoot ?? "", IsReadOnly = true, FontSize = 12,
            Margin      = new System.Windows.Thickness(0, 0, 8, 0),
            Background  = new System.Windows.Media.SolidColorBrush(System.Windows.Media.Color.FromRgb(0x0C, 0x10, 0x20)),
            Foreground  = fg,
            BorderBrush = new System.Windows.Media.SolidColorBrush(System.Windows.Media.Color.FromRgb(0x1E, 0x22, 0x33)),
            ToolTip     = "Your Archipelago install folder (default " + DefaultArchipelagoRoot +
                          "). READ-ONLY — only used to locate the Age2 DE client.",
        };
        var apBtn = MakeButton("Select folder...", 120, fg);
        apBtn.Click += (_, _) =>
        {
            var dlg = new OpenFolderDialog
            {
                Title = "Select your Archipelago install folder (read-only — to find the Age2 Client)",
                InitialDirectory = Directory.Exists(_overrideApDir ?? apRoot ?? "")
                    ? (_overrideApDir ?? apRoot!)
                    : (Directory.Exists(DefaultArchipelagoRoot)
                        ? DefaultArchipelagoRoot : AppContext.BaseDirectory),
            };
            if (dlg.ShowDialog() != true) return;
            _overrideApDir = dlg.FolderName;
            apBox.Text     = dlg.FolderName;
            SaveApInstallOverride(dlg.FolderName);
        };
        System.Windows.Controls.DockPanel.SetDock(apBtn,
            System.Windows.Controls.Dock.Right);
        apRow.Children.Add(apBtn);
        apRow.Children.Add(apBox);
        panel.Children.Add(apRow);
        panel.Children.Add(new System.Windows.Controls.TextBlock
        {
            Text = "This folder is never modified — the launcher only reads it to find the " +
                   "Age of Empires II: DE Client. If left unset, run the client from the " +
                   "Archipelago Launcher yourself.",
            FontSize = 11, Foreground = muted,
            TextWrapping = System.Windows.TextWrapping.Wrap,
            Margin = new System.Windows.Thickness(0, 6, 0, 12),
        });

        // ── Section: Setup steps ───────────────────────────────────────────
        panel.Children.Add(SectionHeader("SETUP & CONNECTION", muted));
        panel.Children.Add(new System.Windows.Controls.TextBlock
        {
            Text =
                "1) Own and install Age of Empires II: Definitive Edition " +
                "(Steam appid " + SteamAppId + ").\n" +
                "2) Download the Ageipelago .apworld from GitHub (see link below) and install " +
                "it into Archipelago (drop it in the custom_worlds folder, or use the AP " +
                "Launcher's \"Install APWorld\" option).\n" +
                "3) Generate a multiworld room — this produces a .aoe2scenario file for your " +
                "slot. Copy it into your AoE2 DE scenario folder " +
                @"(<user_folder>\resources\_common\scenario\)." + "\n" +
                "4) In AoE2 DE, open the Mod Manager and enable the Archipelago mod.\n" +
                "5) Press Play here (or run \"Age of Empires II: DE Client\" from the " +
                "Archipelago Launcher), then enter your server, slot, and password in the " +
                "client console.\n" +
                "6) In AoE2 DE, load the generated scenario to start your session.\n\n" +
                "If the client says 'user folder not set', run /set_user_folder in the " +
                "client and pick your " +
                @"C:\Users\<YOU>\Games\Age of Empires 2 DE\<ID>\ folder.",
            FontSize = 11, Foreground = fg,
            TextWrapping = System.Windows.TextWrapping.Wrap,
            Margin = new System.Windows.Thickness(0, 0, 0, 12),
        });

        // ── Links ─────────────────────────────────────────────────────────
        panel.Children.Add(SectionHeader("LINKS", muted));
        foreach (var (label, url) in new[]
        {
            ("Ageipelago APWorld releases (GitHub) ↗",  ApworldReleasesUrl),
            ("AoE2 DE on Steam ↗",                      SteamStoreUrl),
            ("Archipelago Releases ↗",                  ArchipelagoReleasesUrl),
            ("Archipelago Official ↗",                  ArchipelagoSite),
        })
        {
            var btn = new System.Windows.Controls.Button
            {
                Content = label,
                HorizontalAlignment = System.Windows.HorizontalAlignment.Left,
                Padding         = new System.Windows.Thickness(0, 2, 0, 2),
                Background      = System.Windows.Media.Brushes.Transparent,
                BorderThickness = new System.Windows.Thickness(0),
                FontSize        = 12,
                Margin          = new System.Windows.Thickness(0, 0, 0, 4),
                Foreground      = link,
                Cursor          = System.Windows.Input.Cursors.Hand,
            };
            string u = url;
            btn.Click += (_, _) =>
            {
                try { Process.Start(new ProcessStartInfo(u) { UseShellExecute = true }); }
                catch { /* non-fatal */ }
            };
            panel.Children.Add(btn);
        }

        return panel;
    }

    private static System.Windows.Controls.TextBlock SectionHeader(
        string text, System.Windows.Media.Brush muted)
        => new System.Windows.Controls.TextBlock
        {
            Text = text, FontSize = 10,
            FontWeight = System.Windows.FontWeights.SemiBold,
            Foreground = muted,
            Margin = new System.Windows.Thickness(0, 8, 0, 8),
        };

    private static System.Windows.Controls.Button MakeButton(
        string content, double width, System.Windows.Media.Brush fg)
        => new System.Windows.Controls.Button
        {
            Content     = content,
            Width       = width,
            Padding     = new System.Windows.Thickness(0, 6, 0, 6),
            Background  = new System.Windows.Media.SolidColorBrush(System.Windows.Media.Color.FromRgb(0x1A, 0x1E, 0x30)),
            Foreground  = fg,
            BorderBrush = new System.Windows.Media.SolidColorBrush(System.Windows.Media.Color.FromRgb(0x2A, 0x30, 0x50)),
        };

    // ── News feed ─────────────────────────────────────────────────────────────
    // The Ageipelago GitHub releases are the most honest versioned "news" for this
    // integration. Never throws — empty on failure.

    public async Task<NewsItem[]> GetNewsAsync(CancellationToken ct = default)
    {
        try
        {
            string json = await _http.GetStringAsync(ApworldReleasesApiUrl, ct);
            using var doc = JsonDocument.Parse(json);
            if (doc.RootElement.ValueKind != JsonValueKind.Array)
                return Array.Empty<NewsItem>();

            var items = new List<NewsItem>();
            foreach (var el in doc.RootElement.EnumerateArray())
            {
                DateTimeOffset date = DateTimeOffset.MinValue;
                if (el.TryGetProperty("published_at", out var d) &&
                    d.ValueKind == JsonValueKind.String)
                    DateTimeOffset.TryParse(d.GetString(), out date);

                items.Add(new NewsItem(
                    Title:   el.TryGetProperty("name",     out var n) ? n.GetString() ?? "" : "",
                    Body:    el.TryGetProperty("body",     out var b) ? b.GetString() ?? "" : "",
                    Version: el.TryGetProperty("tag_name", out var t) ? t.GetString() ?? "" : "",
                    Date:    date,
                    Url:     el.TryGetProperty("html_url", out var u) ? u.GetString() : null
                ));
                if (items.Count >= 10) break;
            }
            return items.ToArray();
        }
        catch { return Array.Empty<NewsItem>(); }
    }

    // ── Private helpers — AoE2 DE install detection ───────────────────────────

    private string? ResolveSteamDir()
    {
        if (!string.IsNullOrWhiteSpace(_overrideRootDir) &&
            LooksLikeAoE2Root(_overrideRootDir))
            return _overrideRootDir;
        try { return DetectSteamAoE2Dir(); }
        catch { return null; }
    }

    private static bool LooksLikeAoE2Root(string dir)
    {
        try
        {
            if (string.IsNullOrWhiteSpace(dir) || !Directory.Exists(dir)) return false;
            foreach (string exe in GameExeNames)
                if (File.Exists(Path.Combine(dir, exe))) return true;
            return false;
        }
        catch { return false; }
    }

    private static string? DetectSteamAoE2Dir()
    {
        foreach (string steamRoot in SteamRoots())
        {
            if (string.IsNullOrWhiteSpace(steamRoot)) continue;
            foreach (string lib in SteamLibraryRoots(steamRoot))
            {
                try
                {
                    string steamapps = Path.Combine(lib, "steamapps");
                    string manifest  = Path.Combine(steamapps, "appmanifest_" + SteamAppId + ".acf");
                    if (!File.Exists(manifest)) continue;

                    string common     = Path.Combine(steamapps, "common");
                    string? installDir = ReadAcfInstallDir(manifest);
                    if (installDir != null)
                    {
                        string candidate = Path.Combine(common, installDir);
                        if (LooksLikeAoE2Root(candidate)) return candidate;
                    }
                    string conventional = Path.Combine(common, SteamCommonFolderName);
                    if (LooksLikeAoE2Root(conventional)) return conventional;
                }
                catch { /* try next library */ }
            }
        }
        return null;
    }

    // ── Private helpers — AoE2 DE user folder detection ──────────────────────

    /// The AoE2 DE user folder: override wins, else the first
    /// C:\Users\<USER>\Games\Age of Empires 2 DE\<numeric-id>\ folder found.
    private string? ResolveUserDir()
    {
        if (!string.IsNullOrWhiteSpace(_overrideUserDir) &&
            Directory.Exists(_overrideUserDir))
            return _overrideUserDir;
        try { return DetectAoE2UserDir(); }
        catch { return null; }
    }

    private static string? DetectAoE2UserDir()
    {
        // AoE2 DE stores user data under %USERPROFILE%\Games\Age of Empires 2 DE\<numeric-id>\
        string? userProfile = null;
        try { userProfile = Environment.GetFolderPath(Environment.SpecialFolder.UserProfile); }
        catch { }
        if (string.IsNullOrWhiteSpace(userProfile)) return null;

        string root = Path.Combine(userProfile, "Games", GamesRootFolderName);
        if (!Directory.Exists(root)) return null;

        // There is normally exactly one numeric subfolder (the Xbox/Steam user ID).
        foreach (string sub in Directory.EnumerateDirectories(root))
        {
            string name = Path.GetFileName(sub);
            if (IsNumericFolderName(name)) return sub;
        }
        return null;
    }

    private static bool IsNumericFolderName(string name)
    {
        if (string.IsNullOrWhiteSpace(name)) return false;
        foreach (char c in name)
            if (c < '0' || c > '9') return false;
        return name.Length > 0;
    }

    // ── Private helpers — Archipelago install / client (READ-ONLY) ───────────

    private string? ResolveArchipelagoRoot()
    {
        if (!string.IsNullOrWhiteSpace(_overrideApDir) &&
            Directory.Exists(_overrideApDir))
            return _overrideApDir;
        try
        {
            if (Directory.Exists(DefaultArchipelagoRoot))
                return DefaultArchipelagoRoot;
            foreach (Environment.SpecialFolder sf in new[]
            {
                Environment.SpecialFolder.LocalApplicationData,
                Environment.SpecialFolder.ProgramFiles,
                Environment.SpecialFolder.ProgramFilesX86,
            })
            {
                string? baseDir = null;
                try { baseDir = Environment.GetFolderPath(sf); } catch { }
                if (!string.IsNullOrWhiteSpace(baseDir))
                {
                    string cand = Path.Combine(baseDir, "Archipelago");
                    if (Directory.Exists(cand)) return cand;
                }
            }
        }
        catch { }
        return null;
    }

    private string? ResolveBundledClient()
    {
        try
        {
            string? root = ResolveArchipelagoRoot();
            if (root == null || !Directory.Exists(root)) return null;

            // Prefer a dedicated Age2 client exe if one was bundled.
            string? age2Client = FindExe(root,
                name => (name.Contains("age") && name.Contains("2") &&
                         name.Contains("client")) ||
                        (name.Contains("aoe") && name.Contains("client")));
            if (age2Client != null) return age2Client;

            // Fall back to the generic AP launcher (we pass it the component name).
            string launcher = Path.Combine(root, ArchipelagoLauncherExe);
            if (File.Exists(launcher)) return launcher;

            return FindExe(root,
                name => name.Contains("archipelagolauncher") ||
                       (name.Contains("archipelago") && name.Contains("launcher")));
        }
        catch { return null; }
    }

    private static bool IsGenericApLauncher(string exePath)
    {
        string name = Path.GetFileNameWithoutExtension(exePath).ToLowerInvariant();
        return name.Contains("launcher") && !name.Contains("age");
    }

    private static string? FindExe(string dir, Func<string, bool> predicate)
    {
        try
        {
            if (!Directory.Exists(dir)) return null;
            foreach (string exe in Directory.EnumerateFiles(dir, "*.exe",
                                                            SearchOption.TopDirectoryOnly))
            {
                string name = Path.GetFileNameWithoutExtension(exe).ToLowerInvariant();
                if (predicate(name)) return exe;
            }
        }
        catch { }
        return null;
    }

    // ── Private helpers — launch ──────────────────────────────────────────────

    private void StartBundledClient(string clientExe)
    {
        var psi = new ProcessStartInfo
        {
            FileName         = clientExe,
            WorkingDirectory = Path.GetDirectoryName(clientExe) ?? "",
            UseShellExecute  = false,
        };
        // If it is the generic AP launcher, pass the component name to dispatch.
        if (IsGenericApLauncher(clientExe))
            psi.Arguments = Quote(Age2ClientComponentName);

        var proc = Process.Start(psi);
        if (proc == null) return;

        _clientProcess = proc;
        IsRunning      = true;
        try
        {
            proc.EnableRaisingEvents = true;
            proc.Exited += (_, _) =>
            {
                if (_gameProcess == null || _gameProcess.HasExited)
                    IsRunning = false;
            };
        }
        catch { /* non-fatal */ }
    }

    private void StartAoE2DE()
    {
        string? root = ResolveSteamDir();
        string? exe  = null;
        if (root != null)
        {
            foreach (string name in GameExeNames)
            {
                string cand = Path.Combine(root, name);
                if (File.Exists(cand)) { exe = cand; break; }
            }
        }

        if (exe != null)
        {
            var proc = Process.Start(new ProcessStartInfo
            {
                FileName         = exe,
                WorkingDirectory = root!,
                UseShellExecute  = true,
            });
            if (proc != null)
            {
                _gameProcess = proc;
                IsRunning    = true;
                try
                {
                    proc.EnableRaisingEvents = true;
                    proc.Exited += (_, _) =>
                    {
                        IsRunning = false;
                        GameExited?.Invoke(proc.ExitCode);
                    };
                }
                catch { /* non-fatal */ }
            }
            return;
        }

        // Fall back to Steam URL (preferred for AoE2 anyway — lets Steam verify DLC).
        if (SteamIsInstalled())
        {
            try
            {
                Process.Start(new ProcessStartInfo(SteamRunUrl) { UseShellExecute = true });
                IsRunning = true;
                return;
            }
            catch { /* fall through */ }
        }

        throw new FileNotFoundException(
            "Could not find AoE2DE_s.exe. Open this game's Settings and pick your " +
            "AoE2 DE install folder, or install the game via Steam (appid " +
            SteamAppId + ").",
            GameExeNames[0]);
    }

    private static bool SteamIsInstalled()
    {
        foreach (string r in SteamRoots())
        {
            try { if (!string.IsNullOrWhiteSpace(r) && Directory.Exists(r)) return true; }
            catch { }
        }
        return false;
    }

    private static string Quote(string value)
    {
        if (string.IsNullOrEmpty(value)) return "\"\"";
        bool needs = value.IndexOfAny(new[] { ' ', '\t', '"' }) >= 0;
        if (!needs) return value;
        return "\"" + value.Replace("\"", "\\\"") + "\"";
    }

    // ── Private helpers — Steam detection (standard pipeline) ─────────────────

    private static IEnumerable<string> SteamRoots()
    {
        string? hkcu = ReadRegistryString(Registry.CurrentUser,
            @"Software\Valve\Steam", "SteamPath");
        if (!string.IsNullOrWhiteSpace(hkcu)) yield return NormalizeSteamPath(hkcu);

        string? hklm = ReadRegistryString(Registry.LocalMachine,
            @"SOFTWARE\WOW6432Node\Valve\Steam", "InstallPath");
        if (!string.IsNullOrWhiteSpace(hklm)) yield return NormalizeSteamPath(hklm);

        string? hklm64 = ReadRegistryString(Registry.LocalMachine,
            @"SOFTWARE\Valve\Steam", "InstallPath");
        if (!string.IsNullOrWhiteSpace(hklm64)) yield return NormalizeSteamPath(hklm64);

        string? progX86 = Environment.GetFolderPath(
            Environment.SpecialFolder.ProgramFilesX86);
        if (!string.IsNullOrWhiteSpace(progX86))
            yield return Path.Combine(progX86, "Steam");
    }

    private static string NormalizeSteamPath(string p)
        => p.Replace('/', '\\').TrimEnd('\\');

    private static IEnumerable<string> SteamLibraryRoots(string steamRoot)
    {
        var seen = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        if (seen.Add(steamRoot)) yield return steamRoot;

        string vdf = Path.Combine(steamRoot, "steamapps", "libraryfolders.vdf");
        if (!File.Exists(vdf)) yield break;

        string text;
        try { text = File.ReadAllText(vdf); }
        catch { yield break; }

        foreach (string path in ExtractVdfPaths(text))
        {
            string norm = path.Replace('/', '\\').TrimEnd('\\');
            if (norm.Length > 0 && seen.Add(norm))
                yield return norm;
        }
    }

    private static IEnumerable<string> ExtractVdfPaths(string text)
    {
        const string key = "\"path\"";
        int i = 0;
        while ((i = text.IndexOf(key, i, StringComparison.OrdinalIgnoreCase)) >= 0)
        {
            i += key.Length;
            int open = text.IndexOf('"', i);
            if (open < 0) yield break;
            int close = text.IndexOf('"', open + 1);
            if (close < 0) yield break;
            string raw = text.Substring(open + 1, close - open - 1);
            yield return raw.Replace("\\\\", "\\");
            i = close + 1;
        }
    }

    private static string? ReadAcfInstallDir(string acfPath)
    {
        try
        {
            string text = File.ReadAllText(acfPath);
            const string key = "\"installdir\"";
            int i = text.IndexOf(key, StringComparison.OrdinalIgnoreCase);
            if (i < 0) return null;
            i += key.Length;
            int open = text.IndexOf('"', i);
            if (open < 0) return null;
            int close = text.IndexOf('"', open + 1);
            if (close < 0) return null;
            return text.Substring(open + 1, close - open - 1).Replace("\\\\", "\\");
        }
        catch { return null; }
    }

    private static string? ReadRegistryString(
        RegistryKey hive, string subKey, string valueName)
    {
        try
        {
            using RegistryKey? k = hive.OpenSubKey(subKey);
            return k?.GetValue(valueName) as string;
        }
        catch { return null; }
    }

    // ── Private helpers — sidecar settings ───────────────────────────────────

    private sealed class Age2DESettings
    {
        public string? RootDirOverride  { get; set; }
        public string? UserDirOverride  { get; set; }
        public string? ApInstallOverride { get; set; }
    }

    private Age2DESettings LoadSettings()
    {
        try
        {
            if (File.Exists(SettingsSidecarPath))
            {
                string txt = File.ReadAllText(SettingsSidecarPath);
                if (!string.IsNullOrWhiteSpace(txt))
                    return JsonSerializer.Deserialize<Age2DESettings>(txt) ?? new();
            }
        }
        catch { /* corrupt → defaults */ }
        return new();
    }

    private void SaveSettings(Age2DESettings s)
    {
        try
        {
            Directory.CreateDirectory(SettingsSidecarDir);
            File.WriteAllText(SettingsSidecarPath,
                JsonSerializer.Serialize(s,
                    new JsonSerializerOptions { WriteIndented = true }),
                new UTF8Encoding(false));
        }
        catch { /* non-fatal */ }
    }

    private void SaveRootDirOverride(string dir)
    {
        var s = LoadSettings(); s.RootDirOverride = dir; SaveSettings(s);
    }

    private void SaveUserDirOverride(string dir)
    {
        var s = LoadSettings(); s.UserDirOverride = dir; SaveSettings(s);
    }

    private void SaveApInstallOverride(string dir)
    {
        var s = LoadSettings(); s.ApInstallOverride = dir; SaveSettings(s);
    }
}
