-- ═══════════════════════════════════════════════════════════════════════════════
-- ctjot.lua — game module for the Archipelago BizHawk connector.
--            Chrono Trigger: Jets of Time (SNES)
--
-- STATUS: REAL implementation, SOURCE-DERIVED from the CTJoT apworld's SNIClient
-- subclass. The 193-entry location table was GENERATED by parsing the source with
-- Python (ast) — the three flag dicts the client actually scans, JOINed by NAME
-- with data/location_data.json (loc_id = LOCATION_ID_START + value) — not hand-
-- copied, so it is exact. Addresses + masks + item handshake are replicated 1:1
-- from worlds/ctjot/Client.py (class CTJoTSNIClient, game = "Chrono Trigger Jets
-- of Time"). Loads and runs crash-free on any ROM; self-disables on a non-AP
-- cartridge. Mock-verified through MoonSharp against synthetic SNES memory.
--   SOURCE: https://github.com/Anguirel86/Archipelago (branch "ctjot")
--           worlds/ctjot/Client.py + worlds/ctjot/data/location_data.json
--           (the same source the ctjot.apworld ships from)
--
-- HOW CTJoT IS DISTRIBUTED (important — like FF1, NOT a normal AP patch)
-- ──────────────────────────────────────────────────────────────────────
--   The apworld has NO generate_output / APProcedurePatch — there is no .apctjot
--   file. The player generates a patched ROM (.sfc) + matching .yaml together from
--   the CTJoT web generator (https://multiworld.ctjot.com), uploading their own US
--   Chrono Trigger ROM. That ALREADY-PATCHED .sfc is the ROM loaded here. The
--   patched ROM carries the "AP" signature this module validates.
--
-- MEMORY MODEL (SNI → BizHawk SNES domains)
-- ──────────────────────────────────────────
--   CTJoT is an SNIClient SNES game. Client.py's _convert_to_sni_addressing(a) =
--   (a - 0x7E0000) + WRAM_START(0xF50000), so its $7E/$7F work-RAM addresses are
--   all BizHawk "WRAM"-domain offsets (= SNES addr - 0x7E0000):
--     • EVENT block  $7F0000        → WRAM offset 0x10000 (0x200 bytes; all the
--                                     event + treasure "checked" flags)
--     • map id       0xF50100 (SNI) → WRAM offset 0x00100 (2 bytes, little-endian)
--     • RECV item    $7E287A        → WRAM offset 0x0287A (u8 — id to grant)
--     • RECV count   $7E287C        → WRAM offset 0x0287C (u8 — items consumed)
--   The AP "AP" signature the client validates (VALIDATION_ADDR, already SNI ROM
--   addressing) is in the cartridge ROM ("CARTROM") at 0x3F8C03.
--
-- HOW CTJoT CHECKS WORK (a flag scan, like ALttP — not a SEND/RECV queue)
--   Client.py._track_locations does ONE 0x200-byte read of the event block and
--   tests each location's (byte, bitmask). The client scans exactly three dicts:
--     • _locations_baseline_key_items : event   data[addr - 0x7F0000] & flag
--     • _locations_event_treasures    : event   data[addr - 0x7F0000] & flag
--     • _locations_treasure_chests    : chest   data[offset + 1]       & flag
--   The other dicts (_locations_tab_events, _locations_misc_events,
--   _locations_treasure_chests_not_in_logic) are NOT scanned and are excluded.
--   The table below stores the FINAL block-relative byte offset for both flavours,
--   so each entry collapses to  event_block[byteoff] & mask.
--
-- WHAT THIS DOES (mirrors worlds/ctjot/Client.py)
--   • poll(): the client's _track_locations scan → AP location ids, gated to the
--     slot's server location set AND the same in-game gate the client uses (not in
--     the "@ABC" gate-travel mode-7 scene, map id ∉ {0x00,0x1B1}, map id ≤ 0x1FF).
--   • is_goal_complete(): the multiworld victory flag — event_block[0x20] & 0x01
--     (VICTORY_ADDRESS $7F0020), the cross-mode/cross-ending completion bit the
--     CTJoT multiworld code adds to the ending selector scene.
--   • receive_item(): the client's _deliver_next_item handshake. items_handling =
--     0b011, so the server streams our own world's items too (the in-game event
--     code grants every received item). The game owns RECV count and its event
--     code zeroes the RECV slot once it consumes an item, so we only write the next
--     item when (a) count < #delivered and (b) the RECV slot is 0. In-game item ids
--     are item.item - ITEM_ID_START; only real items (id ≤ 255) are written to the
--     slot — event-only items (character pickups, id > 255) are skipped but still
--     advance the count, exactly as the client does.
--
-- MODULE CONTRACT (called by bizhawk_ap_connector.lua)
--   M.init(ctx) / M.poll() -> {ids} / M.is_goal_complete() -> bool /
--   M.receive_item(item_id, meta)
-- ═══════════════════════════════════════════════════════════════════════════════

local M = {}
M.name = "ctjot"

-- Location ids are ABSOLUTE (LOCATION_ID_START + value, both from the apworld), so
-- detection is fully self-contained — no per-slot data-package base is needed and
-- this stays true (same situation as ALttP / cvcotm, unlike Super Metroid).
local ADDRESSES_VERIFIED = true

-- ── Memory domains ────────────────────────────────────────────────────────────
local WRAM    = "WRAM"
local CARTROM = "CARTROM"     -- SNES cartridge ROM in BizHawk; fallback "ROM"

-- ── SNI-space constants, as BizHawk-domain offsets (Client.py module top) ─────
local EVENT_BLOCK_OFF = 0x10000          -- WRAM: $7F0000 event block base
local EVENT_BLOCK_SIZE= 0x200            -- bytes the client reads in one go
local MAPID_OFF       = 0x00100          -- WRAM: map id (LOCATION_ADDRESS 0xF50100)
local RECV_ITEM_OFF   = 0x0287A          -- WRAM: RECEIVE_ITEM_ADDR  $7E287A (u8)
local RECV_COUNT_OFF  = 0x0287C          -- WRAM: RECEIVED_ITEM_COUNT $7E287C (u8)
local VICTORY_OFF     = 0x20             -- within event block: VICTORY_ADDRESS $7F0020
local VICTORY_MASK    = 0x01

local ROMNAME_OFF     = 0x3F8C03         -- CARTROM: VALIDATION_ADDR; first 2 = "AP"

-- Item id math (Client.py).
local ITEM_ID_START      = 5100000
local MAX_IN_GAME_ITEM_ID= 255

-- Tracking gate (Client.py._track_locations).
local INVALID_TRACKING_MAPS = { [0x00]=true, [0x1B1]=true }  -- load / title screens
local MAX_MAP_ID            = 0x1FF
local GATE_TRAVEL_SIG       = { 0x40, 0x41, 0x42, 0x43 }       -- "@ABC" mode-7 pattern

-- ── Location table (GENERATED from worlds/ctjot/Client.py + location_data.json) ─
-- ap_id -> { event_block_byte_off, mask8 }. 193 entries (only the locations the
-- client actually scans). Checked when EVENT_BLOCK[byteoff] & mask. NOTE: a few
-- ap_ids deliberately SHARE one (byteoff,mask) — e.g. Pyramid Left/Right (416,1)
-- and Heckran Sealed 1/2 (416,4); the source sends an item for each when the shared
-- flag clears, so both ids legitimately appear with the same flag.
local LOC = {
  [5100001]={28,8},[5100002]={27,2},[5100003]={27,4},[5100004]={27,8},[5100005]={27,16},[5100006]={27,32},
  [5100007]={27,64},[5100008]={27,128},[5100009]={28,1},[5100010]={28,2},[5100011]={28,4},[5100012]={28,16},
  [5100013]={28,32},[5100014]={256,32},[5100015]={124,128},[5100016]={15,2},[5100017]={27,1},[5100018]={164,1},
  [5100019]={314,2},[5100020]={17,16},[5100021]={17,32},[5100022]={17,64},[5100023]={14,32},[5100024]={14,64},
  [5100025]={14,128},[5100026]={15,1},[5100027]={15,128},[5100028]={31,64},[5100029]={18,8},[5100030]={18,16},
  [5100031]={18,32},[5100032]={18,64},[5100033]={18,128},[5100034]={19,1},[5100035]={19,2},[5100036]={19,4},
  [5100037]={20,2},[5100038]={20,4},[5100039]={20,8},[5100040]={20,16},[5100041]={315,16},[5100042]={16,2},
  [5100043]={16,4},[5100044]={16,8},[5100045]={19,8},[5100046]={19,16},[5100047]={16,16},[5100048]={16,32},
  [5100049]={16,64},[5100050]={16,128},[5100051]={17,2},[5100052]={17,1},[5100053]={17,4},[5100054]={4,2},
  [5100055]={4,4},[5100056]={12,4},[5100057]={12,8},[5100058]={12,16},[5100059]={12,32},[5100060]={12,128},
  [5100062]={169,128},[5100063]={428,8},[5100064]={425,32},[5100065]={428,4},[5100066]={422,1},[5100067]={425,64},
  [5100068]={425,128},[5100069]={422,2},[5100070]={422,4},[5100071]={428,2},[5100072]={428,1},[5100073]={1,64},
  [5100074]={1,128},[5100075]={2,1},[5100076]={30,1},[5100077]={30,2},[5100078]={30,4},[5100079]={162,128},
  [5100080]={11,16},[5100081]={11,32},[5100082]={11,64},[5100083]={11,128},[5100084]={12,1},[5100085]={12,2},
  [5100086]={1,4},[5100087]={1,8},[5100088]={2,4},[5100089]={2,128},[5100090]={4,8},[5100091]={4,16},
  [5100092]={8,64},[5100093]={8,128},[5100094]={6,1},[5100095]={6,2},[5100096]={6,4},[5100097]={257,2},
  [5100098]={464,16},[5100099]={414,128},[5100100]={2,8},[5100101]={2,16},[5100102]={2,32},[5100103]={2,64},
  [5100104]={122,1},[5100105]={1,16},[5100106]={1,32},[5100107]={4,32},[5100108]={4,64},[5100109]={4,128},
  [5100110]={30,8},[5100111]={31,4},[5100112]={31,8},[5100113]={31,16},[5100114]={31,32},[5100115]={5,2},
  [5100116]={5,4},[5100117]={5,8},[5100118]={5,16},[5100119]={5,32},[5100120]={5,64},[5100121]={5,128},
  [5100122]={13,2},[5100123]={13,4},[5100124]={13,8},[5100125]={13,16},[5100126]={13,32},[5100127]={13,64},
  [5100128]={13,128},[5100129]={13,1},[5100130]={6,8},[5100131]={6,16},[5100132]={6,32},[5100133]={6,64},
  [5100134]={6,128},[5100135]={7,1},[5100136]={7,2},[5100137]={7,4},[5100138]={7,8},[5100139]={7,16},
  [5100140]={7,32},[5100141]={7,64},[5100142]={7,128},[5100143]={8,1},[5100144]={8,2},[5100145]={8,4},
  [5100146]={8,8},[5100147]={8,16},[5100148]={8,32},[5100149]={258,2},[5100150]={14,1},[5100151]={14,2},
  [5100152]={14,4},[5100153]={14,8},[5100154]={14,16},[5100155]={15,4},[5100156]={15,8},[5100157]={15,16},
  [5100158]={15,32},[5100159]={330,128},[5100160]={467,16},[5100161]={467,32},[5100162]={217,2},[5100163]={466,128},
  [5100164]={330,32},[5100165]={465,64},[5100166]={465,128},[5100167]={465,32},[5100168]={217,4},[5100169]={416,4},
  [5100170]={416,4},[5100171]={416,1},[5100172]={416,1},[5100173]={121,1},[5100174]={20,32},[5100175]={20,64},
  [5100176]={20,128},[5100177]={21,1},[5100178]={21,16},[5100179]={21,4},[5100180]={21,8},[5100181]={21,2},
  [5100182]={21,32},[5100183]={21,64},[5100184]={22,32},[5100185]={22,64},[5100186]={261,32},[5100187]={22,128},
  [5100188]={23,1},[5100189]={23,2},[5100190]={31,128},[5100191]={262,4},[5100242]={17,8},[5100312]={124,1},
  [5100313]={419,64},
}

-- ── Internal state ────────────────────────────────────────────────────────────
local reported        = {}     -- ap_id -> true once returned from poll()
local server_locations= nil     -- set of ap_ids the server expects (nil = all)
local items_received  = {}     -- ordered stream (extended ITEM lines)
local slot_number     = 0
local rom_ok          = nil     -- cached "AP" signature result (nil until checked)
local mem             = {}
local log_fn          = nil
local event_block     = {}      -- byte offset -> value, refreshed each poll

-- ── Logging ───────────────────────────────────────────────────────────────────
local function log(msg)
  if log_fn then pcall(log_fn, "[ctjot] " .. tostring(msg)) end
end

-- ── Memory API (resolved at init; 2-arg domain form + current-domain fallback) ─
local function resolve_memory_api()
  if not memory then return false end
  mem.read_u8   = memory.read_u8     or memory.readbyte
  mem.read_u16  = memory.read_u16_le or memory.readword
  mem.write_u8  = memory.write_u8    or memory.writebyte
  return mem.read_u8 ~= nil
end

local function rd(fn, addr, domain)
  if not fn then return nil end
  local ok, v = pcall(fn, addr, domain)
  if ok and type(v) == "number" then return v end
  ok, v = pcall(fn, addr)                       -- older API: current domain
  if ok and type(v) == "number" then return v end
  return nil
end

local function read_u8(addr, domain)  return rd(mem.read_u8,  addr, domain or WRAM) end
local function read_u16(addr, domain) return rd(mem.read_u16, addr, domain or WRAM) end

local function write_u8(addr, value, domain)
  if not mem.write_u8 then return end
  if pcall(mem.write_u8, addr, value, domain or WRAM) then return end
  pcall(mem.write_u8, addr, value)
end

-- Read from CARTROM, falling back to the legacy "ROM" domain name on cores that use it.
local function read_cartrom_u8(off)
  local ok, v = pcall(mem.read_u8, off, CARTROM)
  if ok and type(v) == "number" then return v end
  ok, v = pcall(mem.read_u8, off, "ROM")
  if ok and type(v) == "number" then return v end
  return nil
end

local function bit_and(a, b)
  -- 8-bit-safe AND without the bit library (cores vary).
  local res, bitval = 0, 1
  while a > 0 and b > 0 do
    if a % 2 == 1 and b % 2 == 1 then res = res + bitval end
    a = math.floor(a / 2); b = math.floor(b / 2); bitval = bitval * 2
  end
  return res
end

-- ── ROM identity: the AP-patched ROM carries "AP" at CARTROM 0x3F8C03 ─────────
local function rom_is_ap()
  if rom_ok ~= nil then return rom_ok end
  local a = read_cartrom_u8(ROMNAME_OFF)
  local p = read_cartrom_u8(ROMNAME_OFF + 1)
  if a == nil or p == nil then return false end          -- not readable yet; retry
  rom_ok = (a == string.byte("A") and p == string.byte("P"))
  if rom_ok then log("AP ROM verified ('AP' signature present)")
  else log("non-AP ROM (no 'AP' signature) — detection idle, no writes") end
  return rom_ok
end

-- ── Multiworld context ────────────────────────────────────────────────────────
local function load_locations(ids)
  if type(ids) ~= "table" then return end
  server_locations = {}
  local n = 0
  for _, id in ipairs(ids) do
    local v = tonumber(id)
    if v then server_locations[v] = true; n = n + 1 end
  end
  log("server location set: " .. n .. " ids")
end

local function wanted(ap_id)
  if server_locations == nil then return true end   -- no set provided → report all
  return server_locations[ap_id] == true
end

-- Item-stream filter. CTJoT uses items_handling = 0b011 (it WANTS its own world's
-- found items back too — the in-game event code grants every received item), so we
-- do NOT drop own-world items the way the items_handling=1 modules do. We only drop
-- pure server/starting-inventory placeholders (player 0 with no real location).
local function accept_item(it)
  if it.player == nil then return true end          -- legacy ITEM:<id> line
  if it.player == 0 and (it.location or 0) <= 0 then return false end
  return true
end

local function delivery_list()
  local out = {}
  for _, it in ipairs(items_received) do
    if accept_item(it) then out[#out + 1] = it end
  end
  return out
end

-- ── Detection gate (Client.py._track_locations) ───────────────────────────────
local function refresh_event_block()
  for i = 0, EVENT_BLOCK_SIZE - 1 do
    event_block[i] = read_u8(EVENT_BLOCK_OFF + i)
  end
end

-- True when it is SAFE to read checks: not in the gate-travel mode-7 scene (which
-- overwrites event RAM with the "@ABC" pattern), and on a real, in-range map.
local function tracking_ok()
  -- Gate-travel detection: event_block[0..3] == "@ABC".
  local b0,b1,b2,b3 = event_block[0], event_block[1], event_block[2], event_block[3]
  if b0 == GATE_TRAVEL_SIG[1] and b1 == GATE_TRAVEL_SIG[2]
     and b2 == GATE_TRAVEL_SIG[3] and b3 == GATE_TRAVEL_SIG[4] then
    return false
  end
  -- Map id (2 bytes LE at WRAM 0x0100). Skip load/title screens and out-of-range.
  local map_id = read_u16(MAPID_OFF)
  if map_id == nil then return false end
  if INVALID_TRACKING_MAPS[map_id] then return false end
  if map_id > MAX_MAP_ID then return false end
  return true
end

local function flag_set(byteoff, mask)
  local v = event_block[byteoff]
  if v == nil then return false end
  return bit_and(v, mask) ~= 0
end

-- ── Module contract ───────────────────────────────────────────────────────────

function M.init(ctx)
  if ctx and type(ctx.log) == "function" then log_fn = ctx.log end
  if not resolve_memory_api() then
    log("BizHawk memory API unavailable — module idle")
    ADDRESSES_VERIFIED = false
    return
  end
  local cfg = (ctx and ctx.config) or {}
  slot_number = tonumber(cfg.slot_number) or 0
  load_locations(cfg.locations)
  local n = 0; for _ in pairs(LOC) do n = n + 1 end
  log(("ready: slot #%d, %d location flags"):format(slot_number, n))
end

function M.poll()
  local new = {}
  if not ADDRESSES_VERIFIED then return new end
  if not rom_is_ap() then return new end
  refresh_event_block()
  if not tracking_ok() then return new end
  for ap_id, bm in pairs(LOC) do
    if not reported[ap_id] and wanted(ap_id) and flag_set(bm[1], bm[2]) then
      reported[ap_id] = true
      new[#new + 1] = ap_id
    end
  end
  return new
end

function M.is_goal_complete()
  if not ADDRESSES_VERIFIED or not rom_is_ap() then return false end
  refresh_event_block()
  return flag_set(VICTORY_OFF, VICTORY_MASK)
end

-- Record the grant, then push the next pending item to the game when the game is
-- ready for it — the client's _deliver_next_item handshake. The game owns the RECV
-- count and its event code zeroes the RECV slot once it consumes an item; we only
-- write the next item when count < #delivered AND the slot is empty (0). Event-only
-- AP items (character pickups, in-game id > MAX_IN_GAME_ITEM_ID) are not written to
-- the slot but still advance the count, exactly like the client.
function M.receive_item(item_id, meta)
  if type(meta) == "table" then
    items_received[#items_received + 1] = {
      item     = tonumber(item_id),
      index    = tonumber(meta.index),
      player   = tonumber(meta.player),
      flags    = tonumber(meta.flags),
      location = tonumber(meta.locId or meta.location),
    }
  else
    items_received[#items_received + 1] = { item = tonumber(item_id) }
  end

  if not ADDRESSES_VERIFIED or not rom_is_ap() then return end

  local list = delivery_list()
  local count = read_u8(RECV_COUNT_OFF)
  if count == nil then return end
  if count < #list then
    local slot = read_u8(RECV_ITEM_OFF)
    if slot == nil or slot ~= 0 then return end          -- game hasn't consumed last item yet
    local nxt = list[count + 1]
    if nxt and nxt.item then
      local in_game_id = nxt.item - ITEM_ID_START
      -- Only real in-game items (id ≤ 255) are written to the receive slot; event
      -- items (character pickups) are skipped but the count still advances.
      if in_game_id >= 0 and in_game_id <= MAX_IN_GAME_ITEM_ID then
        write_u8(RECV_ITEM_OFF, bit_and(in_game_id, 0xFF))
      end
      -- The client writes the count back manually (the event scripts can't reach
      -- this RAM); mirror that so the next poll feeds list[count+2], and so on.
      write_u8(RECV_COUNT_OFF, bit_and(count + 1, 0xFF))
    end
  end
end

return M
