-- ═══════════════════════════════════════════════════════════════════════════════
-- Donkey Kong Country 2.lua — game module for the Archipelago BizHawk connector.
--                          Donkey Kong Country 2: Diddy's Kong Quest (SNES)
--
-- STATUS: COMMUNITY world. location DETECTION + goal are REAL and SOURCE-DERIVED
-- from the official apworld worlds/dkc2 (Client.py game_watcher + Locations.py +
-- Levels.py, TheLX5/Archipelago @ branch `dkc2`, world_version 3.1.2). The
-- 581-entry location table was GENERATED by JOINING Locations.all_locations
-- (name → AP id) with Levels.location_id_to_level_id (name → [loc_type, level_num,
-- data]) — not hand-copied — so every (AP id → level_num/index) pair is exact.
-- Mock-verified through MoonSharp against synthetic WRAM/SRAM/CARTROM. Loads
-- crash-free on any ROM; self-disables on a non-AP cartridge.
--
-- SOURCE: https://github.com/TheLX5/Archipelago  (branch `dkc2`, worlds/dkc2)
--         game string "Donkey Kong Country 2", patch_suffix ".apdkc2",
--         items_handling 0b111 (FULL remote), base ROM US REV1
--         MD5 d323e6bb4ccc85fd7b416f58350bc1a2 (HASH_US_REV_1; the patch's
--         declared `hash`). The vanilla US 1.0 dump hashes
--         98458530599b9dff8a7414a7f20b777a (HASH_US).
--
-- MEMORY MODEL (SNI → BizHawk)  — see Research_V2/SNES_BRIDGE_2026-06-12.md
-- ──────────────────────────────────────────────────────────────────────────
--   The dkc2 client is an SNIClient. Its SNI addresses translate to BizHawk SNES
--   memory domains. DKC2 — unlike DKC1 — reads from THREE regions:
--     SNI WRAM_START(0xF50000)+off → domain "WRAM",    offset off  (= $7E0000+off)
--     SNI SRAM_START(0xE00000)+off → domain "CARTRAM", offset off  (battery SRAM;
--                                    fallback "SRAM")
--     SNI ROM_START(0x000000)+off  → domain "CARTROM", offset off  (raw ROM file
--                                    offset. Fallbacks "ROM"/"System Bus")
--   DKC2 is a HiROM cartridge, so the internal header at SNES $00:FFC0 lives at
--   ROM **file** offset 0xFFC0 (HiROM places the header there — NOT the LoROM
--   0x7FC0). The client read (DKC2_ROMHASH_START = 0xFFC0) and the AP patch write
--   (patch.write_bytes(0xFFC0, name) — name begins "DKC2") both use file offset
--   0xFFC0, so this module reads the signature from CARTROM 0xFFC0 directly.
--
--   The client (DKC2Memory enum) reads, and this module mirrors:
--     • general_data = Read(WRAM+0x00D0, 0x10) → WRAM
--         loaded_save = u16 LE at WRAM 0x00D5 (general_data[0x05:0x07]); ==0 → no save
--     • nmi_pointer  = Read(WRAM+0x0020, 0x02) → WRAM, u16 LE
--                      (0x8CE9 or 0x8CF1 == in a map / transition)
--     • validation   = Read(DKC2_INIT_FLAG = SRAM+0x822, 0x02) → CARTRAM, u16 LE
--                      (must == 0xDEAD; the basepatch sets it once running)
--     • current_level= Read(WRAM+0x08A8, 0x01) → WRAM
--     • loaded_level = Read(WRAM+0x00D3, 0x01) → WRAM
--     • current_map  = Read(WRAM+0x06B1, 0x01) → WRAM
--     • brightness   = Read(WRAM+0x0512, 0x01) → WRAM (& 0x0F == 0x0F = full)
--     • game_flags   = Read(WRAM+0x59B2, 0x60) → WRAM
--         bonus_flags   = game_flags[0x00:0x20]   (level bonus bitfield)
--         dk_coin_flags = game_flags[0x20:0x40]   (DK-coin bitfield)
--         stage_flags   = game_flags[0x40:0x60]   (level-clear bitfield)
--     • misc_flags   = Read(WRAM+0x08D2, 0x80) → WRAM   (kong_flags = misc[0x30])
--     • swanky_flags = Read(WRAM+0x08F0, 0x09) → WRAM
--     • sanity_flags = Read(WRAM+0x1FF00, 0x100) → WRAM (coin/bunch/balloon bits)
--     • settings     = Read(DKC2_SETTINGS = CARTROM 0x3DFF80, 0x40) → CARTROM
--         settings[0x01] = selected_goal
--         settings[0x20..0x25] = per-check-family enable bytes (see below)
--   IDENTITY / VALIDATION (mirrors validate_rom + the game_watcher 0xDEAD gate):
--     ROM header at CARTROM 0xFFC0 begins with "DKC2" and is not all-zero, AND
--     the runtime init flag at CARTRAM 0x822 reads 0xDEAD. The AP basepatch bakes
--     in the header and arms the init flag.
--
-- HOW DKC2 CHECKS WORK (mirrors Client.py game_watcher; per-location loc_type)
--   Each location carries {loc_type, level_num, data}. game_watcher only processes
--   a location while NOT in a map/transition (nmi_pointer != 0x8CE9/0x8CF1) AND at
--   full brightness (brightness & 0x0F == 0x0F). For the level-indexed bitfields it
--   computes:  level_offset = (level_num >> 3) & 0x1E ; level_bit = 1<<(level_num & 0x0F)
--   then reads a u16 LE word at flagarray[level_offset:level_offset+2]:
--     0x00 Level clear : stage_flags  word & level_bit
--     0x01 KONG        : level_num == current_level AND kong_flags & 0x0F == 0x0F   [gated kong_as_checks]
--     0x02 DK Coin     : dk_coin_flags word & level_bit                            [gated dk_coins_as_checks]
--     0x03 Bonus       : bonus_flags  word & level_bit
--     0x04 Swanky      : swanky_flags[level_num>>4] & (level_num & 0x07)            [gated swanky_as_checks]
--     0x05 Banana Coin : level_num == loaded_level AND sanity_flags[data] & 0x02   [gated coins_as_checks]
--     0x06 Banana Bunch: level_num == loaded_level AND sanity_flags[data] & 0x04   [gated bunches_as_checks]
--     0x07 Balloon     : level_num == loaded_level AND sanity_flags[data] & 0x01   [gated balloons_as_checks]
--   The five *_as_checks gates are per-seed CARTROM settings bytes
--   (settings[0x20..0x25]). DKC2 shares one set of flag arrays across check
--   families, so — unlike DKC1 — the gate matters: e.g. a level's bonus word also
--   backs DK-coin reads, and the KONG bit is a live player flag. We therefore read
--   the gates from CARTROM and apply them exactly as game_watcher does, so a
--   disabled family is never mis-reported. (Level-clear and Bonus are never gated.)
--
-- WHAT THIS DOES
--   • poll(): the game_watcher location scan above → AP location ids, gated to the
--     slot's server location set, to the per-family settings gates, and to the
--     in-game state (game_state set once a save is loaded and the player has
--     reached the map, i.e. nmi_pointer has read 0x8CE9/0x8CF1 at least once).
--   • is_goal_complete(): mirrors game_watcher's goal block — selected_goal =
--     settings[0x01]; goal_check bit 1 = bonus_flags level 0x61 set, bit 2 =
--     dk_coin_flags level 0x6B set; complete when goal_check & selected_goal ==
--     selected_goal. (Bit 1 = K. Rool defeated / The Flying Krock; bit 2 = Lost
--     World / Krocodile Core DK-coin — together they cover the "beat K. Rool",
--     "Lost World", and "both" goal options the server bakes into settings[0x01].)
--   • receive_item(): NO-OP (documented). items_handling = 0b111 (FULL remote) —
--     the dkc2 client owns ALL item delivery via an intricate, heavily-state-gated
--     set of SRAM/WRAM writes (kong-unlock bitmask, ability/animal/object unlock
--     bytes at SRAM offsets, currency increments, trap counters, an SFX strobe via
--     DKC2_SOUND_PLAYBACK, plus a recv-index handshake at DKC2_RECV_INDEX, all
--     gated on full brightness; EnergyLink DK barrels / TrapLink / DeathLink /
--     SharedDamage on top). That delivery path is the one piece that needs in-
--     emulator verification before it is wired, so it is left out rather than
--     shipped unverified (a wrong write would corrupt the save or desync the
--     recv-index). Checks + goal above are fully functional regardless.
--
-- MODULE CONTRACT (called by bizhawk_ap_connector.lua)
--   M.init(ctx) / M.poll() -> {ids} / M.is_goal_complete() -> bool /
--   M.receive_item(item_id, meta)
-- ═══════════════════════════════════════════════════════════════════════════════

local M = {}
M.name = "Donkey Kong Country 2"

local ADDRESSES_VERIFIED = true   -- table generated from worlds/dkc2 source

-- ── Memory domains ────────────────────────────────────────────────────────────
local WRAM    = "WRAM"
local CARTRAM = "CARTRAM"     -- battery SRAM in BizHawk; fallback "SRAM"
local CARTROM = "CARTROM"     -- SNES cartridge ROM in BizHawk; fallbacks below

-- ── Addresses / constants (worlds/dkc2/Client.py module top) ──────────────────
-- Expressed as BizHawk-domain offsets (already net of WRAM_START/SRAM_START/ROM_START).
local GENERAL_DATA_OFF  = 0x00D0      -- WRAM: 0x10 block; loaded_save = u16 LE at +0x05
local NMI_POINTER_OFF   = 0x0020      -- WRAM: u16 LE; == 0x8CE9/0x8CF1 while in a map
local VALIDATION_OFF    = 0x0822      -- CARTRAM: u16 LE init flag; must == 0xDEAD
local CURRENT_LEVEL_OFF = 0x08A8      -- WRAM: id of the level currently being played
local LOADED_LEVEL_OFF  = 0x00D3      -- WRAM: loaded level id (sanity checks key on it)
local CURRENT_MAP_OFF   = 0x06B1      -- WRAM: current overworld map id
local BRIGHTNESS_OFF    = 0x0512      -- WRAM: screen brightness; & 0x0F == 0x0F = full
local GAME_FLAGS_OFF    = 0x59B2      -- WRAM: base of the 0x60-byte game-flag block
local MISC_FLAGS_OFF    = 0x08D2      -- WRAM: base of the 0x80-byte misc-flag block
local SWANKY_FLAGS_OFF  = 0x08F0      -- WRAM: base of the swanky (quiz) flag block
local SANITY_FLAGS_OFF  = 0x1FF00     -- WRAM: base of the 0x100-byte sanity-flag array
local SETTINGS_OFF      = 0x3DFF80    -- CARTROM: base of the 0x40-byte settings block
local ROMHASH_OFF       = 0xFFC0      -- CARTROM: ROM-header title; first 4 = "DKC2"

-- Sub-offsets within blocks.
local LOADED_SAVE_SUB   = 0x05        -- general_data[0x05:0x07] = loaded_save (u16 LE)
local KONG_FLAG_SUB     = 0x30        -- misc_flags[0x30] = kong_flags
local BONUS_BASE        = 0x00        -- game_flags[0x00:0x20] = bonus_flags
local DKCOIN_BASE       = 0x20        -- game_flags[0x20:0x40] = dk_coin_flags
local STAGE_BASE        = 0x40        -- game_flags[0x40:0x60] = stage_flags (level clear)

-- Settings byte indices (CARTROM, settings[i]).
local SET_GOAL          = 0x01        -- selected_goal
local SET_DKCOIN        = 0x20        -- dk_coins_as_checks
local SET_KONG          = 0x21        -- kong_as_checks
local SET_BALLOON       = 0x22        -- balloons_as_checks
local SET_COIN          = 0x23        -- coins_as_checks
local SET_BUNCH         = 0x24        -- bunches_as_checks
local SET_SWANKY        = 0x25        -- swanky_as_checks

-- Sentinel values.
local IN_MAP_NMI_A      = 0x8CE9      -- nmi_pointer value while on the world map
local IN_MAP_NMI_B      = 0x8CF1      -- second in-map nmi_pointer value
local VALIDATED         = 0xDEAD      -- validation flag value when the basepatch is live

-- Per-location loc_type tags (Client.py game_watcher).
local T_CLEAR    = 0x00
local T_KONG     = 0x01
local T_DKCOIN   = 0x02
local T_BONUS    = 0x03
local T_SWANKY   = 0x04
local T_COIN     = 0x05
local T_BUNCH    = 0x06
local T_BALLOON  = 0x07

-- Goal flag positions (game_watcher goal block).
local GOAL_BONUS_LEVEL  = 0x61        -- bonus_flags level checked → goal bit 1
local GOAL_DKCOIN_LEVEL = 0x6B        -- dk_coin_flags level checked → goal bit 2

-- ── Location table (GENERATED from worlds/dkc2 Locations.py ⋈ Levels.py) ───────
-- ap_id -> { loc_type, level_num, data }. 581 entries (data present only for
-- coin/bunch/balloon types as the sanity index). AP ids are absolute
-- location_name_to_id values (STARTING_ID 0xBF0000-based); detection is
-- self-contained.
local LOC = {
  [12517376]={0,3},[12517377]={0,12},[12517378]={0,4},[12517379]={0,21},[12517380]={0,11},[12517381]={0,9},
  [12517382]={0,7},[12517383]={0,37},[12517384]={0,20},[12517385]={0,8},[12517386]={0,36},[12517387]={0,33},
  [12517388]={0,40},[12517389]={0,1},[12517390]={0,41},[12517391]={0,5},[12517392]={0,10},[12517393]={0,45},
  [12517394]={0,99},[12517395]={0,17},[12517396]={0,14},[12517397]={0,46},[12517398]={0,15},[12517399]={0,44},
  [12517400]={0,2},[12517401]={0,96},[12517402]={0,25},[12517403]={0,16},[12517404]={0,24},[12517405]={0,19},
  [12517407]={0,23},[12517408]={0,13},[12517409]={0,108},[12517410]={0,35},[12517411]={0,98},[12517412]={0,143},
  [12517413]={0,109},[12517414]={0,110},[12517415]={3,185},[12517416]={0,47},[12517418]={0,153},[12517419]={0,150},
  [12517420]={0,128},[12517421]={0,22},[12517422]={0,154},[12517424]={0,9},[12517425]={0,33},[12517426]={0,99},
  [12517427]={0,96},[12517428]={0,13},[12517440]={1,3},[12517441]={1,12},[12517442]={1,4},[12517443]={1,21},
  [12517444]={1,11},[12517445]={1,7},[12517446]={1,37},[12517447]={1,20},[12517448]={1,8},[12517449]={1,36},
  [12517450]={1,40},[12517451]={1,1},[12517452]={1,41},[12517453]={1,5},[12517454]={1,10},[12517455]={1,45},
  [12517456]={1,17},[12517457]={1,14},[12517458]={1,46},[12517459]={1,15},[12517460]={1,44},[12517461]={1,2},
  [12517462]={1,25},[12517463]={1,16},[12517464]={1,24},[12517465]={1,19},[12517466]={1,23},[12517467]={1,108},
  [12517468]={1,35},[12517469]={1,98},[12517470]={1,143},[12517471]={1,109},[12517472]={1,110},[12517473]={1,47},
  [12517474]={1,153},[12517475]={1,150},[12517476]={1,128},[12517477]={1,22},[12517478]={1,154},[12517504]={2,3},
  [12517505]={2,12},[12517506]={2,4},[12517507]={2,21},[12517508]={2,11},[12517509]={2,7},[12517510]={2,37},
  [12517511]={2,20},[12517512]={2,8},[12517513]={2,36},[12517514]={2,40},[12517515]={2,1},[12517516]={2,41},
  [12517517]={2,5},[12517518]={2,10},[12517519]={2,45},[12517520]={2,17},[12517521]={2,14},[12517522]={2,46},
  [12517523]={2,15},[12517524]={2,44},[12517525]={2,2},[12517526]={2,25},[12517527]={2,16},[12517528]={2,24},
  [12517529]={2,19},[12517530]={2,23},[12517531]={2,108},[12517532]={2,35},[12517533]={2,98},[12517534]={2,143},
  [12517535]={2,109},[12517536]={2,110},[12517537]={2,47},[12517538]={2,153},[12517539]={2,150},[12517540]={2,128},
  [12517541]={2,22},[12517542]={2,154},[12517568]={3,111},[12517569]={3,112},[12517570]={3,120},[12517571]={3,121},
  [12517572]={3,125},[12517573]={3,168},[12517574]={3,113},[12517575]={3,129},[12517576]={3,123},[12517577]={3,124},
  [12517578]={3,117},[12517579]={3,28},[12517580]={3,116},[12517581]={3,171},[12517582]={3,173},[12517583]={3,170},
  [12517584]={3,131},[12517585]={3,118},[12517586]={3,119},[12517587]={3,172},[12517588]={3,186},[12517589]={3,169},
  [12517590]={3,137},[12517591]={3,138},[12517592]={3,132},[12517593]={3,130},[12517594]={3,139},[12517595]={3,114},
  [12517596]={3,127},[12517597]={3,115},[12517598]={3,122},[12517599]={3,126},[12517600]={3,166},[12517601]={3,160},
  [12517602]={3,174},[12517603]={3,179},[12517604]={3,176},[12517605]={3,161},[12517606]={3,193},[12517607]={3,162},
  [12517608]={3,195},[12517609]={3,140},[12517610]={3,141},[12517611]={3,180},[12517612]={3,178},[12517613]={3,133},
  [12517614]={3,136},[12517615]={3,189},[12517616]={3,194},[12517617]={3,192},[12517618]={3,134},[12517619]={3,135},
  [12517620]={3,177},[12517621]={3,175},[12517622]={3,164},[12517623]={3,188},[12517624]={3,147},[12517625]={3,149},
  [12517626]={3,187},[12517627]={3,163},[12517628]={3,183},[12517629]={3,184},[12517630]={3,145},[12517631]={3,146},
  [12517632]={3,181},[12517633]={3,182},[12517634]={3,165},[12517635]={3,167},[12517696]={4,1},[12517697]={4,2},
  [12517698]={4,4},[12517699]={4,17},[12517700]={4,18},[12517701]={4,20},[12517702]={4,33},[12517703]={4,34},
  [12517704]={4,36},[12517705]={4,129},[12517706]={4,130},[12517707]={4,132},[12517708]={4,65},[12517709]={4,66},
  [12517710]={4,68},[12517711]={4,81},[12517712]={4,82},[12517713]={4,84},[12517888]={5,3,6},[12517889]={5,3,20},
  [12517890]={5,111,2},[12517891]={5,12,1},[12517892]={5,12,48},[12517893]={5,12,38},[12517894]={5,4,120},[12517895]={5,4,54},
  [12517896]={5,21,1},[12517897]={5,21,3},[12517898]={5,21,25},[12517899]={5,21,32},[12517900]={5,21,35},[12517901]={5,21,16},
  [12517902]={5,21,15},[12517903]={5,21,31},[12517904]={5,11,4},[12517905]={5,11,120},[12517906]={5,11,67},[12517907]={5,11,10},
  [12517908]={5,9,3},[12517909]={5,9,4},[12517910]={5,7,120},[12517911]={5,7,48},[12517912]={5,7,70},[12517913]={5,7,71},
  [12517914]={5,37,99},[12517915]={5,37,62},[12517916]={5,37,89},[12517917]={5,20,18},[12517918]={5,20,16},[12517919]={5,20,71},
  [12517920]={5,20,96},[12517921]={5,20,58},[12517922]={5,20,7},[12517923]={5,20,14},[12517924]={5,20,70},[12517925]={5,20,74},
  [12517926]={5,20,78},[12517927]={5,8,2},[12517928]={5,8,1},[12517929]={5,8,20},[12517930]={5,8,30},[12517931]={5,8,120},
  [12517932]={5,8,56},[12517933]={5,36,56},[12517934]={5,172,120},[12517935]={5,36,12},[12517936]={5,36,6},[12517937]={5,36,61},
  [12517938]={5,36,62},[12517939]={5,36,63},[12517940]={5,33,18},[12517941]={5,33,19},[12517942]={5,40,35},[12517943]={5,40,73},
  [12517944]={5,1,4},[12517945]={5,1,12},[12517946]={5,1,65},[12517947]={5,1,81},[12517948]={5,1,86},[12517949]={5,1,52},
  [12517950]={5,1,38},[12517951]={5,1,40},[12517952]={5,1,68},[12517953]={5,1,93},[12517954]={5,41,4},[12517955]={5,41,30},
  [12517956]={5,41,66},[12517957]={5,5,4},[12517958]={5,5,19},[12517959]={5,5,47},[12517960]={5,10,64},[12517961]={5,10,63},
  [12517962]={5,10,39},[12517963]={5,45,190},[12517964]={5,45,99},[12517965]={5,17,9},[12517966]={5,17,54},[12517967]={5,17,27},
  [12517968]={5,17,3},[12517969]={5,46,125},[12517970]={5,162,120},[12517971]={5,46,104},[12517972]={5,46,3},[12517973]={5,46,2},
  [12517974]={5,46,36},[12517975]={5,46,39},[12517976]={5,46,29},[12517977]={5,15,120},[12517978]={5,44,3},[12517979]={5,44,120},
  [12517980]={5,44,82},[12517981]={5,44,99},[12517982]={5,44,115},[12517983]={5,2,2},[12517984]={5,2,15},[12517985]={5,96,4},
  [12517986]={5,96,5},[12517987]={5,25,15},[12517988]={5,25,88},[12517989]={5,16,5},[12517990]={5,16,31},[12517991]={5,16,47},
  [12517992]={5,24,1},[12517993]={5,24,9},[12517994]={5,24,56},[12517995]={5,19,103},[12517996]={5,19,62},[12517997]={5,19,96},
  [12517998]={5,19,97},[12517999]={5,19,127},[12518000]={5,23,10},[12518001]={5,23,120},[12518002]={5,23,39},[12518003]={5,23,50},
  [12518004]={5,23,96},[12518005]={5,13,6},[12518006]={5,13,7},[12518007]={5,108,20},[12518008]={5,108,36},[12518009]={5,108,34},
  [12518010]={5,108,32},[12518011]={5,108,76},[12518012]={5,35,63},[12518013]={5,35,105},[12518014]={5,35,5},[12518015]={5,35,33},
  [12518016]={5,98,20},[12518017]={5,98,52},[12518018]={5,98,15},[12518019]={5,143,94},[12518020]={5,143,57},[12518021]={5,143,23},
  [12518022]={5,143,22},[12518023]={5,143,18},[12518024]={5,109,112},[12518025]={5,109,104},[12518026]={5,109,42},[12518027]={5,109,88},
  [12518028]={5,110,5},[12518029]={5,110,3},[12518030]={5,110,7},[12518031]={5,110,106},[12518032]={5,110,108},[12518033]={5,185,1},
  [12518034]={5,185,3},[12518035]={5,47,11},[12518036]={5,47,76},[12518037]={5,47,73},[12518038]={5,47,15},[12518039]={5,47,13},
  [12518040]={5,47,14},[12518041]={5,47,16},[12518042]={5,47,17},[12518043]={5,153,52},[12518044]={5,153,59},[12518045]={5,153,82},
  [12518046]={5,153,84},[12518047]={5,153,88},[12518048]={5,150,99},[12518049]={5,128,1},[12518050]={5,128,9},[12518051]={5,128,22},
  [12518052]={5,128,94},[12518053]={5,22,33},[12518054]={5,22,69},[12518055]={5,155,22},[12518056]={5,159,19},[12518057]={5,159,17},
  [12518058]={5,159,23},[12518059]={5,156,120},[12518144]={6,3,11},[12518145]={6,12,42},[12518146]={6,12,34},[12518147]={6,12,39},
  [12518148]={6,4,6},[12518149]={6,4,13},[12518150]={6,4,30},[12518151]={6,4,51},[12518152]={6,4,57},[12518153]={6,4,49},
  [12518154]={6,4,68},[12518155]={6,21,2},[12518156]={6,21,24},[12518157]={6,21,52},[12518158]={6,21,0},[12518159]={6,11,47},
  [12518160]={6,11,3},[12518161]={6,11,68},[12518162]={6,7,35},[12518163]={6,7,63},[12518164]={6,7,65},[12518165]={6,37,45},
  [12518166]={6,20,33},[12518167]={6,20,101},[12518168]={6,20,44},[12518169]={6,131,0},[12518170]={6,20,34},[12518171]={6,8,3},
  [12518172]={6,8,11},[12518173]={6,8,26},[12518174]={6,8,66},[12518175]={6,36,2},[12518176]={6,36,50},[12518177]={6,36,34},
  [12518178]={6,36,0},[12518179]={6,40,10},[12518180]={6,40,37},[12518181]={6,40,75},[12518182]={6,1,15},[12518183]={6,1,16},
  [12518184]={6,1,21},[12518185]={6,1,42},[12518186]={6,1,95},[12518187]={6,1,84},[12518188]={6,1,85},[12518189]={6,1,66},
  [12518190]={6,1,24},[12518191]={6,1,1},[12518192]={6,1,2},[12518193]={6,1,9},[12518194]={6,1,46},[12518195]={6,1,77},
  [12518196]={6,5,6},[12518197]={6,5,12},[12518198]={6,5,73},[12518199]={6,5,0},[12518200]={6,10,52},[12518201]={6,10,67},
  [12518202]={6,10,13},[12518203]={6,10,9},[12518204]={6,45,3},[12518205]={6,45,62},[12518206]={6,45,184},[12518207]={6,45,193},
  [12518208]={6,45,172},[12518209]={6,45,9},[12518210]={6,45,131},[12518211]={6,45,140},[12518212]={6,160,0},[12518213]={6,17,5},
  [12518214]={6,17,13},[12518215]={6,17,2},[12518216]={6,17,1},[12518217]={6,17,40},[12518218]={6,14,5},[12518219]={6,161,0},
  [12518220]={6,46,126},[12518221]={6,46,86},[12518222]={6,46,58},[12518223]={6,46,15},[12518224]={6,46,0},[12518225]={6,44,0},
  [12518226]={6,2,40},[12518227]={6,2,12},[12518228]={6,2,0},[12518229]={6,25,1},[12518230]={6,25,5},[12518231]={6,25,21},
  [12518232]={6,25,53},[12518233]={6,16,1},[12518234]={6,16,2},[12518235]={6,19,67},[12518236]={6,19,90},[12518237]={6,23,15},
  [12518238]={6,23,26},[12518239]={6,23,30},[12518240]={6,108,19},[12518241]={6,108,21},[12518242]={6,108,26},[12518243]={6,108,16},
  [12518244]={6,108,77},[12518245]={6,108,75},[12518246]={6,108,82},[12518247]={6,35,83},[12518248]={6,35,79},[12518249]={6,35,13},
  [12518250]={6,35,0},[12518251]={6,98,75},[12518252]={6,98,41},[12518253]={6,98,0},[12518254]={6,98,47},[12518255]={6,98,80},
  [12518256]={6,98,14},[12518257]={6,143,111},[12518258]={6,143,110},[12518259]={6,143,109},[12518260]={6,143,0},[12518261]={6,109,24},
  [12518262]={6,109,3},[12518263]={6,181,7},[12518264]={6,109,11},[12518265]={6,110,25},[12518266]={6,110,22},[12518267]={6,110,13},
  [12518268]={6,110,16},[12518269]={6,110,17},[12518270]={6,110,18},[12518271]={6,110,4},[12518272]={6,110,107},[12518273]={6,110,109},
  [12518274]={6,47,48},[12518275]={6,47,10},[12518276]={6,47,5},[12518277]={6,47,22},[12518278]={6,47,23},[12518279]={6,47,88},
  [12518280]={6,153,44},[12518281]={6,153,48},[12518282]={6,150,24},[12518283]={6,150,1},[12518284]={6,150,72},[12518285]={6,128,7},
  [12518286]={6,128,8},[12518287]={6,128,23},[12518288]={6,128,39},[12518289]={6,128,49},[12518290]={6,128,63},[12518291]={6,128,83},
  [12518292]={6,22,1},[12518293]={6,22,2},[12518294]={6,22,3},[12518295]={6,22,20},[12518296]={6,22,115},[12518297]={6,144,24},
  [12518298]={6,155,1},[12518299]={6,159,20},[12518300]={6,159,18},[12518400]={7,27,1},[12518401]={7,3,0},[12518402]={7,12,4},
  [12518403]={7,4,26},[12518404]={7,4,73},[12518405]={7,21,0},[12518406]={7,11,5},[12518407]={7,11,40},[12518408]={7,11,53},
  [12518409]={7,7,2},[12518410]={7,7,0},[12518411]={7,20,0},[12518412]={7,36,67},[12518413]={7,40,0},[12518414]={7,1,35},
  [12518415]={7,41,11},[12518416]={7,41,0},[12518417]={7,45,179},[12518418]={7,17,98},[12518419]={7,17,0},[12518420]={7,14,74},
  [12518421]={7,46,20},[12518422]={7,46,0},[12518423]={7,25,0},[12518424]={7,24,0},[12518425]={7,23,22},[12518426]={7,23,109},
  [12518427]={7,108,0},[12518428]={7,108,5},[12518429]={7,35,116},[12518430]={7,110,110},[12518431]={7,185,2},[12518432]={7,47,69},
  [12518433]={7,150,9},[12518434]={7,150,2},[12518435]={7,150,103},[12518436]={7,128,123},[12518437]={7,159,7},
}

-- ── Internal state ────────────────────────────────────────────────────────────
local reported         = {}     -- ap_id -> true once returned from poll()
local server_locations = nil    -- set of ap_ids the server expects (nil = all)
local rom_ok           = nil    -- cached "DKC2" header result
local game_state       = false  -- true once a save is loaded and the map reached
local mem              = {}
local log_fn           = nil

-- ── Logging ───────────────────────────────────────────────────────────────────
local function log(msg)
  if log_fn then pcall(log_fn, "[dkc2] " .. tostring(msg)) end
end

-- ── Memory API (resolved at init; 2-arg domain form + current-domain fallback) ─
local function resolve_memory_api()
  if not memory then return false end
  mem.read_u8  = memory.read_u8     or memory.readbyte
  mem.read_u16 = memory.read_u16_le or memory.readword
  return mem.read_u8 ~= nil
end

local function rd(fn, addr, domain)
  if not fn then return nil end
  local ok, v = pcall(fn, addr, domain)
  if ok and type(v) == "number" then return v end
  ok, v = pcall(fn, addr)                       -- older API: current domain
  if ok and type(v) == "number" then return v end
  return nil
end

local function read_wram_u8(off)   return rd(mem.read_u8,  off, WRAM) end
local function read_wram_u16(off)  return rd(mem.read_u16, off, WRAM) end

-- CARTRAM (battery SRAM) reads with a "SRAM" domain-name fallback.
local function read_cartram_u16(off)
  local ok, v = pcall(mem.read_u16, off, CARTRAM)
  if ok and type(v) == "number" then return v end
  ok, v = pcall(mem.read_u16, off, "SRAM")
  if ok and type(v) == "number" then return v end
  return nil
end

-- CARTROM reads with "ROM" / "System Bus" domain-name fallbacks (cores vary;
-- the raw-file-offset CARTROM/ROM form is what every SNES BizHawk core exposes).
local function read_cartrom_u8(off)
  local ok, v = pcall(mem.read_u8, off, CARTROM)
  if ok and type(v) == "number" then return v end
  ok, v = pcall(mem.read_u8, off, "ROM")
  if ok and type(v) == "number" then return v end
  ok, v = pcall(mem.read_u8, off, "System Bus")
  if ok and type(v) == "number" then return v end
  return nil
end

local function bit_and(a, b)
  -- 16-bit safe AND without the bit library (cores vary).
  local res, bitval = 0, 1
  while a > 0 and b > 0 do
    if a % 2 == 1 and b % 2 == 1 then res = res + bitval end
    a = math.floor(a / 2); b = math.floor(b / 2); bitval = bitval * 2
  end
  return res
end

-- ── ROM identity: the SNES header title starts with "DKC2" (validate_rom) ──────
-- validate_rom also rejects an all-zero hash; a real "DKC2" prefix already
-- excludes that, so the prefix check is sufficient here.
local function rom_is_ap()
  if rom_ok ~= nil then return rom_ok end
  local sig = "DKC2"
  for i = 1, #sig do
    local b = read_cartrom_u8(ROMHASH_OFF + i - 1)
    if b == nil then return false end          -- not readable yet; retry next poll
    if b ~= string.byte(sig, i) then
      rom_ok = false
      log("non-DKC2 ROM (no 'DKC2' header) — detection idle, no reports")
      return false
    end
  end
  rom_ok = true
  log("DKC2 ROM verified ('DKC2' header title present)")
  return true
end

-- ── Multiworld context ────────────────────────────────────────────────────────
local function load_locations(ids)
  if type(ids) ~= "table" then return end
  server_locations = {}
  local n = 0
  for _, id in ipairs(ids) do
    local v = tonumber(id)
    if v then server_locations[v] = true; n = n + 1 end
  end
  log("server location set: " .. n .. " ids")
end

local function wanted(ap_id)
  if server_locations == nil then return true end   -- no set provided → report all
  return server_locations[ap_id] == true
end

-- ── Per-poll snapshots (read once per poll, matching game_watcher) ────────────
local snap = {}     -- the RAM the client reads, refreshed each poll

local function read_region_wram(off, len)
  local t = {}
  for i = 0, len - 1 do t[i] = read_wram_u8(off + i) end
  return t
end

-- u16 LE from a WRAM byte table at index i (matches int.from_bytes(arr[i:i+2],"little")).
local function word_le(tbl, i)
  local lo = tbl[i]
  local hi = tbl[i + 1]
  if lo == nil or hi == nil then return nil end
  return lo + hi * 256
end

local function refresh_snapshot()
  local gd            = read_region_wram(GENERAL_DATA_OFF, 0x10)
  snap.loaded_save    = word_le(gd, LOADED_SAVE_SUB)
  snap.nmi_pointer    = read_wram_u16(NMI_POINTER_OFF)
  snap.validation     = read_cartram_u16(VALIDATION_OFF)
  snap.current_level  = read_wram_u8(CURRENT_LEVEL_OFF)
  snap.loaded_level   = read_wram_u8(LOADED_LEVEL_OFF)
  snap.brightness     = read_wram_u8(BRIGHTNESS_OFF)
  local game_flags    = read_region_wram(GAME_FLAGS_OFF, 0x60)
  snap.game_flags     = game_flags
  local misc          = read_region_wram(MISC_FLAGS_OFF, 0x80)
  snap.kong_flags     = misc[KONG_FLAG_SUB]
  snap.swanky_flags   = read_region_wram(SWANKY_FLAGS_OFF, 0x09)
  snap.sanity_flags   = read_region_wram(SANITY_FLAGS_OFF, 0x100)
end

-- Settings are read from CARTROM once (they are baked into the patched ROM).
local settings_cache = nil
local function settings_byte(idx)
  if settings_cache == nil then settings_cache = {} end
  if settings_cache[idx] == nil then
    settings_cache[idx] = read_cartrom_u8(SETTINGS_OFF + idx)
  end
  return settings_cache[idx]
end

-- full brightness == 0x0F in the low nibble (game_watcher gate).
local function full_brightness()
  return snap.brightness ~= nil and bit_and(snap.brightness, 0x0F) == 0x0F
end

-- in a map / transition? game_watcher skips location processing while here.
local function in_map()
  return snap.nmi_pointer ~= nil
     and (snap.nmi_pointer == IN_MAP_NMI_A or snap.nmi_pointer == IN_MAP_NMI_B)
end

-- A level-indexed bitfield word read (mirrors game_watcher's offset/bit math).
-- base = byte offset into game_flags of the desired sub-array.
local function level_word(base, level_num)
  local level_offset = bit_and(math.floor(level_num / 8), 0x1E)   -- (level_num>>3)&0x1E
  return word_le(snap.game_flags, base + level_offset)
end
local function level_bit(level_num)
  return 2 ^ (level_num % 16)                                     -- 1<<(level_num&0x0F)
end

-- ── One location's "checked?" test (mirrors game_watcher per loc_type) ────────
-- Returns true only when the location is satisfied AND its per-family settings
-- gate (if any) is enabled — exactly as game_watcher's elif chain decides.
local function location_checked(loc_type, level_num, data)
  if loc_type == T_CLEAR then
    local w = level_word(STAGE_BASE, level_num)
    return w ~= nil and bit_and(w, level_bit(level_num)) ~= 0

  elseif loc_type == T_KONG then
    if (settings_byte(SET_KONG) or 0) == 0 then return false end
    if snap.current_level ~= level_num then return false end
    return snap.kong_flags ~= nil and bit_and(snap.kong_flags, 0x0F) == 0x0F

  elseif loc_type == T_DKCOIN then
    if (settings_byte(SET_DKCOIN) or 0) == 0 then return false end
    local w = level_word(DKCOIN_BASE, level_num)
    return w ~= nil and bit_and(w, level_bit(level_num)) ~= 0

  elseif loc_type == T_BONUS then
    local w = level_word(BONUS_BASE, level_num)
    return w ~= nil and bit_and(w, level_bit(level_num)) ~= 0

  elseif loc_type == T_SWANKY then
    if (settings_byte(SET_SWANKY) or 0) == 0 then return false end
    -- bonus_offset = level_num>>4 ; bonus_bit = level_num & 0x07 (game_watcher).
    local bonus_offset = math.floor(level_num / 16)
    local bonus_bit    = level_num % 8
    local f = snap.swanky_flags[bonus_offset]
    return f ~= nil and bit_and(f, bonus_bit) ~= 0

  elseif loc_type == T_COIN then
    if (settings_byte(SET_COIN) or 0) == 0 then return false end
    if snap.loaded_level ~= level_num or data == nil then return false end
    local f = snap.sanity_flags[data]
    return f ~= nil and bit_and(f, 0x02) == 0x02

  elseif loc_type == T_BUNCH then
    if (settings_byte(SET_BUNCH) or 0) == 0 then return false end
    if snap.loaded_level ~= level_num or data == nil then return false end
    local f = snap.sanity_flags[data]
    return f ~= nil and bit_and(f, 0x04) == 0x04

  elseif loc_type == T_BALLOON then
    if (settings_byte(SET_BALLOON) or 0) == 0 then return false end
    if snap.loaded_level ~= level_num or data == nil then return false end
    local f = snap.sanity_flags[data]
    return f ~= nil and bit_and(f, 0x01) == 0x01
  end
  return false
end

-- ── Detection gate ────────────────────────────────────────────────────────────
-- game_watcher requires: a loaded save (loaded_save != 0), the runtime init flag
-- == 0xDEAD, and it latches game_state once nmi_pointer reads an in-map value.
-- We mirror that: game_state turns true on the first in-map read while validated.
local function update_game_state()
  if snap.loaded_save == nil or snap.loaded_save == 0 then
    game_state = false
    return false
  end
  if snap.validation ~= VALIDATED then
    -- ROM hash already matched "DKC2"; the runtime flag just isn't armed yet.
    game_state = false
    return false
  end
  if in_map() then game_state = true end
  return game_state
end

-- ── Module contract ───────────────────────────────────────────────────────────
function M.init(ctx)
  if ctx and type(ctx.log) == "function" then log_fn = ctx.log end
  if not resolve_memory_api() then
    log("BizHawk memory API unavailable — module idle")
    ADDRESSES_VERIFIED = false
    return
  end
  local cfg = (ctx and ctx.config) or {}
  load_locations(cfg.locations)
  local n = 0; for _ in pairs(LOC) do n = n + 1 end
  log("ready: " .. n .. " location flags (items_handling=0b111; receive_item is a "
      .. "documented no-op pending in-emulator verification)")
end

function M.poll()
  local new = {}
  if not ADDRESSES_VERIFIED then return new end
  if not rom_is_ap() then return new end
  refresh_snapshot()
  if not update_game_state() then return new end
  -- game_watcher breaks out of the location loop while in a map or not at full
  -- brightness; mirror that exactly so a transition never mis-reports.
  if in_map() or not full_brightness() then return new end
  for ap_id, ld in pairs(LOC) do
    if not reported[ap_id] and wanted(ap_id)
       and location_checked(ld[1], ld[2], ld[3]) then
      reported[ap_id] = true
      new[#new + 1] = ap_id
    end
  end
  return new
end

function M.is_goal_complete()
  if not ADDRESSES_VERIFIED or not rom_is_ap() then return false end
  refresh_snapshot()
  if snap.game_flags == nil then return false end
  local selected_goal = settings_byte(SET_GOAL)
  if selected_goal == nil or selected_goal == 0 then return false end
  -- goal_check bit 1: bonus_flags level 0x61 set; bit 2: dk_coin_flags level 0x6B.
  local goal_check = 0
  local wb = level_word(BONUS_BASE, GOAL_BONUS_LEVEL)
  if wb ~= nil and bit_and(wb, level_bit(GOAL_BONUS_LEVEL)) ~= 0 then
    goal_check = goal_check + 1
  end
  local wd = level_word(DKCOIN_BASE, GOAL_DKCOIN_LEVEL)
  if wd ~= nil and bit_and(wd, level_bit(GOAL_DKCOIN_LEVEL)) ~= 0 then
    goal_check = goal_check + 2
  end
  -- complete when (goal_check & selected_goal) == selected_goal.
  return bit_and(goal_check, selected_goal) == selected_goal
end

-- Remote multiworld items: see the file header. items_handling = 0b111 (FULL
-- remote) means the dkc2 client owns ALL item delivery — kong-unlock bitmask,
-- ability/animal/object unlock bytes at SRAM offsets, currency increments, trap
-- counters, an SFX strobe, a recv-index handshake at DKC2_RECV_INDEX, plus
-- EnergyLink DK barrels / TrapLink / DeathLink / SharedDamage, all heavily gated
-- on game state and full brightness. That path is the one piece deferred until it
-- can be confirmed in-emulator. No-op (never a wrong write) until then; checks +
-- goal above are fully functional.
function M.receive_item(item_id, meta)
  -- intentionally empty (documented)
end

return M
