-- ═══════════════════════════════════════════════════════════════════════════════
-- Donkey Kong Country 3.lua — game module for the Archipelago BizHawk connector.
--                    Donkey Kong Country 3: Dixie Kong's Double Trouble! (SNES)
--
-- STATUS: COMMUNITY world. location DETECTION + goal are REAL and SOURCE-DERIVED
-- from the official apworld worlds/dkc3 (Client.py game_watcher + Rom.py
-- location_rom_data + Locations.py + __init__.py, TheLX5/Archipelago @ branch
-- `dktoluca`, world_version 1.1.0, author PoryGone). The 220-entry location table
-- was GENERATED by PARSING Rom.py location_rom_data (ap_id → [wram_addr, bit,
-- optional invert]) with Python — not hand-copied — so every (AP id → offset/bit)
-- pair is exact. Mock-verified through MoonSharp against synthetic WRAM/CARTROM.
-- Loads crash-free on any ROM; self-disables on a non-AP cartridge.
--
-- SOURCE: https://github.com/TheLX5/Archipelago  (branch `dktoluca`, worlds/dkc3)
--         game string "Donkey Kong Country 3", patch_suffix ".apdkc3",
--         items_handling 0b111 (FULL remote), base ROM US 1.0
--         MD5 120abf304f0c40fe059f6a192ed4f947 (USHASH in worlds/dkc3/Rom.py).
--
-- MEMORY MODEL (SNI → BizHawk)  — see Research_V2/SNES_BRIDGE_2026-06-12.md
-- ──────────────────────────────────────────────────────────────────────────
--   The dkc3 client is an SNIClient. Its SNI addresses translate to BizHawk SNES
--   memory domains. DKC3 reads almost everything from WRAM, plus the ROM header
--   for identity:
--     SNI WRAM_START(0xF50000)+off → domain "WRAM",   offset off  (= $7E0000+off)
--     SNI ROM_START(0x000000)+off  → domain "CARTROM", offset off  (raw ROM file
--                                    offset. Fallbacks "ROM"/"System Bus")
--   DKC3 is a LoROM cartridge. The client's identity read is
--   DKC3_ROMHASH_START = 0x7FC0 (the LoROM internal-header title region), and the
--   AP patch writes the ROM name there (patch.write_bytes(0x7FC0, "D3...")). So
--   this module reads the signature from CARTROM file offset 0x7FC0 and requires
--   the first two bytes to be "D3" — exactly validate_rom's `rom_name[:2] != b"D3"`
--   gate. (validate_rom also rejects an all-zero hash; a real "D3" prefix already
--   excludes that.)
--
--   The client reads (Client.py), and this module mirrors:
--     • save_file_name = Read(WRAM+0x5D9, 0x5) → WRAM. "No save loaded" when
--       byte[0]==0x00 OR the 5 bytes are all 0x55 (uninitialised). game_watcher
--       early-returns in that case; we gate detection on the same condition.
--     • location_ram_data = Read(WRAM+0x5FE, 0x81) → WRAM. ONE contiguous 129-byte
--       progress-flag block at $7E05FE..$7E067E that backs EVERY location. Each
--       location is {wram_addr in [0x5FE,0x67F), bit, optional invert}:
--           data        = location_ram_data[wram_addr - 0x5FE]
--           masked      = data & (1 << bit)
--           bit_set     = masked ~= 0
--           invert_bit  = (#entry >= 3) and entry[3]    -- only some Brothers Bear
--           checked when bit_set ~= invert_bit
--       (No active uncommented location uses invert in 1.1.0 — the Brothers Bear
--       trade-sequence entries that did are disabled — but the invert path is
--       implemented for forward-compat and to match game_watcher byte-for-byte.)
--   IDENTITY / VALIDATION (mirrors validate_rom + the game_watcher re-checks):
--     ROM header at CARTROM 0x7FC0 begins with "D3", AND a save file is loaded
--     (save_file_name gate). The AP patch bakes the "D3<ver>_<player>_<seed>" name
--     into the header at generation time.
--
-- HOW DKC3 CHECKS WORK (mirrors Client.py game_watcher)
--   game_watcher reads the single 0x81-byte flag block once, then for every
--   location not already checked computes data & (1<<bit) and reports it when
--   bit_set ~= invert_bit. There are NO in-map / brightness / settings gates in
--   the dkc3 client (unlike dkc2): a flag is either set or not. The only gate is
--   "a save file is loaded" (and it stays loaded — game_watcher re-reads the save
--   name afterwards and the ROM hash, and bails if either changed; we mirror the
--   save re-read each poll via the same gate). "Non-included" locations are simply
--   never in the server's location set, so gating poll() to ctx.locations (the
--   server's set) reproduces the client's effective behaviour. The client's
--   separate "Handle Collected Locations" RAM-backfill block (writing flags for
--   already-collected co-op locations, and the level-unlock propagation) is a
--   WRITE-side convenience that does NOT affect which checks WE detect, so it is
--   intentionally not mirrored here (we never write).
--
-- GOAL (mirrors __init__.py victory placement + game_watcher CLIENT_GOAL)
--   DKC3 has two goals (Options.Goal):
--     • knautilus (0)         : Victory item is locked at the `kastle_kaos`
--                               location (ap id 0xDC30A7 → WRAM 0x655 bit 1).
--     • banana_bird_hunt (1)  : Victory item is locked at the `banana_bird_mother`
--                               location (ap id 0xDC30B6 → WRAM 0x5FE bit 4).
--   In the official client the goal completes when the server hands the player the
--   Victory item (0xDC3000) back — but that item only exists because the player
--   physically reached the goal location, which sets exactly that location's RAM
--   flag. So the faithful, memory-readable goal signal is: the goal location's bit
--   is set. We read BOTH carrier bits; completion is reached when EITHER is set
--   (a player can only ever reach their own seed's goal location, so detecting
--   either is correct without needing slot_data — and if config.goal is provided
--   we honour it to match the exact carrier). This is the same RAM transition the
--   client's victory item is downstream of.
--
-- WHAT THIS DOES
--   • poll(): the game_watcher flag scan above → AP location ids, gated to the
--     slot's server location set and to "a save file is loaded".
--   • is_goal_complete(): true once the goal-carrier RAM bit is set (see GOAL).
--   • receive_item(): NO-OP (documented). items_handling = 0b111 (FULL remote) —
--     the dkc3 client owns ALL item delivery via an intricate, heavily-state-gated
--     set of WRAM writes (a recv-index handshake at DKC3_RECV_PROGRESS_ADDR; per-
--     item count increments at item_rom_data WRAM offsets; special Bear/Swanky/
--     Boomer coin-display pokes gated on the live current-level bytes; the Patch &
--     Skis progressive-boat upgrade state machine touching the inventory + per-
--     world progress words; and the Victory CLIENT_GOAL trigger). That delivery
--     path is the one piece that needs in-emulator verification before it is wired,
--     so it is left out rather than shipped unverified (a wrong write would corrupt
--     the save or desync the recv-index). Checks + goal above are fully functional
--     regardless.
--
-- MODULE CONTRACT (called by bizhawk_ap_connector.lua)
--   M.init(ctx) / M.poll() -> {ids} / M.is_goal_complete() -> bool /
--   M.receive_item(item_id, meta)
-- ═══════════════════════════════════════════════════════════════════════════════

local M = {}
M.name = "Donkey Kong Country 3"

local ADDRESSES_VERIFIED = true   -- table generated from worlds/dkc3 source

-- ── Memory domains ────────────────────────────────────────────────────────────
local WRAM    = "WRAM"
local CARTROM = "CARTROM"     -- SNES cartridge ROM in BizHawk; fallbacks below

-- ── Addresses / constants (worlds/dkc3 Client.py + Rom.py) ────────────────────
-- Expressed as BizHawk-domain offsets (already net of WRAM_START / ROM_START).
local SAVE_NAME_OFF   = 0x5D9     -- WRAM: 5-byte save-file name; 0x00 / all-0x55 = none
local SAVE_NAME_LEN   = 0x05
local FLAGS_BASE_OFF  = 0x5FE     -- WRAM: base of the single 0x81-byte flag block
local FLAGS_LEN       = 0x81      -- 129 bytes ($7E05FE..$7E067E inclusive)
local ROMHASH_OFF     = 0x7FC0    -- CARTROM: LoROM header title; first 2 = "D3"

-- Save-name sentinels (Client.py game_watcher / validate_rom).
local SAVE_EMPTY_BYTE = 0x00      -- name[0] == 0x00 → no save
local SAVE_UNINIT     = 0x55      -- name == 0x55 * 5 → uninitialised slot

-- Goal carriers (ap id → flag block offset & bit). See GOAL header block.
--   knautilus        : kastle_kaos        0xDC30A7 = [0x655, 1] → off 0x57, bit 1
--   banana_bird_hunt : banana_bird_mother 0xDC30B6 = [0x5FE, 4] → off 0x00, bit 4
local GOAL_KNAUTILUS_OFF, GOAL_KNAUTILUS_BIT = 0x655 - FLAGS_BASE_OFF, 1
local GOAL_BBHUNT_OFF,    GOAL_BBHUNT_BIT    = 0x5FE - FLAGS_BASE_OFF, 4

-- Option value (Options.Goal): which carrier is THIS seed's goal. Honoured when
-- config.goal is provided; otherwise EITHER carrier completes (see header).
local GOAL_OPT_KNAUTILUS  = 0
local GOAL_OPT_BBHUNT     = 1
local selected_goal       = nil   -- nil = unknown → accept either carrier

-- ── Location table (GENERATED from worlds/dkc3 Rom.py location_rom_data) ───────
-- ap_id -> { flag_offset, bit, invert? }. 220 entries. flag_offset is the byte
-- index INTO the 0x81-byte flag block (= wram_addr - 0x5FE). `invert` (3rd field,
-- = 1) is present only on entries whose source tuple set invert=True; none are
-- active in 1.1.0 but the column is honoured for fidelity. AP ids are absolute
-- location_name_to_id values (0xDC3xxx); detection is self-contained.
local LOC = {
  [14430208]={89,1},[14430209]={89,2},[14430210]={89,3},[14430211]={89,5},[14430212]={92,1},[14430213]={92,2},
  [14430214]={92,3},[14430215]={92,5},[14430216]={91,1},[14430217]={91,2},[14430218]={91,3},[14430219]={91,5},
  [14430220]={95,1},[14430221]={95,2},[14430222]={95,3},[14430223]={95,5},[14430224]={94,1},[14430225]={94,2},
  [14430226]={94,3},[14430227]={94,5},[14430228]={100,1},[14430229]={100,2},[14430230]={100,3},[14430231]={100,5},
  [14430232]={102,1},[14430233]={102,2},[14430234]={102,3},[14430235]={102,5},[14430236]={93,1},[14430237]={93,2},
  [14430238]={93,3},[14430239]={93,5},[14430240]={99,1},[14430241]={99,2},[14430242]={99,3},[14430243]={99,5},
  [14430244]={104,1},[14430245]={104,2},[14430246]={104,3},[14430247]={104,5},[14430248]={105,1},[14430249]={105,2},
  [14430250]={105,3},[14430251]={105,5},[14430252]={108,1},[14430253]={108,2},[14430254]={108,3},[14430255]={108,5},
  [14430256]={90,1},[14430257]={90,2},[14430258]={90,3},[14430259]={90,5},[14430260]={109,1},[14430261]={109,2},
  [14430262]={109,3},[14430263]={109,5},[14430264]={106,1},[14430265]={106,2},[14430266]={106,3},[14430267]={106,5},
  [14430268]={111,1},[14430269]={111,2},[14430270]={111,3},[14430271]={111,5},[14430272]={116,1},[14430273]={116,2},
  [14430274]={116,3},[14430275]={116,5},[14430276]={98,1},[14430277]={98,2},[14430278]={98,3},[14430279]={98,5},
  [14430280]={112,1},[14430281]={112,2},[14430282]={112,3},[14430283]={112,5},[14430284]={114,1},[14430285]={114,2},
  [14430286]={114,3},[14430287]={114,5},[14430288]={117,1},[14430289]={117,2},[14430290]={117,3},[14430291]={117,5},
  [14430292]={97,1},[14430293]={97,2},[14430294]={97,3},[14430295]={97,5},[14430296]={110,1},[14430297]={110,2},
  [14430298]={110,3},[14430299]={110,5},[14430300]={113,1},[14430301]={113,2},[14430302]={113,3},[14430303]={113,5},
  [14430304]={96,1},[14430305]={96,2},[14430306]={96,3},[14430307]={96,5},[14430308]={120,1},[14430309]={120,2},
  [14430310]={120,3},[14430311]={120,5},[14430312]={118,1},[14430313]={118,2},[14430314]={118,3},[14430315]={118,5},
  [14430316]={107,1},[14430317]={107,2},[14430318]={107,3},[14430319]={107,5},[14430320]={121,1},[14430321]={121,2},
  [14430322]={121,3},[14430323]={121,5},[14430324]={119,1},[14430325]={119,2},[14430326]={119,3},[14430327]={119,5},
  [14430328]={124,1},[14430329]={124,2},[14430330]={124,3},[14430331]={124,5},[14430332]={122,1},[14430333]={122,2},
  [14430334]={122,3},[14430335]={122,5},[14430336]={103,1},[14430337]={103,2},[14430338]={103,3},[14430339]={103,5},
  [14430340]={123,1},[14430341]={123,2},[14430342]={123,3},[14430343]={123,5},[14430344]={115,1},[14430345]={115,2},
  [14430346]={115,3},[14430347]={115,5},[14430348]={125,1},[14430349]={125,2},[14430350]={125,3},[14430351]={125,4},
  [14430352]={125,5},[14430353]={126,1},[14430354]={126,2},[14430355]={126,3},[14430356]={126,5},[14430357]={127,1},
  [14430358]={127,2},[14430359]={127,3},[14430360]={127,4},[14430361]={127,5},[14430362]={101,1},[14430363]={101,2},
  [14430364]={101,3},[14430365]={101,4},[14430366]={101,5},[14430367]={128,1},[14430368]={128,5},[14430369]={81,1},
  [14430370]={82,1},[14430371]={83,1},[14430372]={84,1},[14430373]={85,1},[14430374]={86,1},[14430375]={87,1},
  [14430376]={88,1},[14430377]={73,1},[14430378]={71,1},[14430379]={70,1},[14430380]={68,1},[14430381]={69,1},
  [14430382]={72,1},[14430383]={74,1},[14430384]={75,1},[14430385]={76,1},[14430387]={78,1},[14430389]={80,1},
  [14430390]={0,4},[14430464]={89,7},[14430468]={92,7},[14430472]={91,7},[14430476]={95,7},[14430480]={94,7},
  [14430484]={100,7},[14430488]={102,7},[14430492]={93,7},[14430496]={99,7},[14430500]={104,7},[14430504]={105,7},
  [14430508]={108,7},[14430512]={90,7},[14430516]={109,7},[14430520]={106,7},[14430524]={111,7},[14430528]={116,7},
  [14430532]={98,7},[14430536]={112,7},[14430540]={114,7},[14430544]={117,7},[14430548]={97,7},[14430552]={110,7},
  [14430556]={113,7},[14430560]={96,7},[14430564]={120,7},[14430568]={118,7},[14430572]={107,7},[14430576]={121,7},
  [14430580]={119,7},[14430584]={124,7},[14430588]={122,7},[14430592]={103,7},[14430596]={123,7},[14430600]={115,7},
  [14430604]={125,7},[14430609]={126,7},[14430613]={127,7},[14430618]={101,7},
}

-- ── Internal state ────────────────────────────────────────────────────────────
local reported         = {}     -- ap_id -> true once returned from poll()
local server_locations = nil    -- set of ap_ids the server expects (nil = all)
local rom_ok           = nil    -- cached "D3" header result
local mem              = {}
local log_fn           = nil

-- ── Logging ───────────────────────────────────────────────────────────────────
local function log(msg)
  if log_fn then pcall(log_fn, "[dkc3] " .. tostring(msg)) end
end

-- ── Memory API (resolved at init; 2-arg domain form + current-domain fallback) ─
local function resolve_memory_api()
  if not memory then return false end
  mem.read_u8  = memory.read_u8 or memory.readbyte
  return mem.read_u8 ~= nil
end

local function read_wram_u8(off)
  if not mem.read_u8 then return nil end
  local ok, v = pcall(mem.read_u8, off, WRAM)
  if ok and type(v) == "number" then return v end
  ok, v = pcall(mem.read_u8, off)                 -- older API: current domain
  if ok and type(v) == "number" then return v end
  return nil
end

-- CARTROM reads with "ROM" / "System Bus" domain-name fallbacks (cores vary;
-- the raw-file-offset CARTROM/ROM form is what every SNES BizHawk core exposes).
local function read_cartrom_u8(off)
  local ok, v = pcall(mem.read_u8, off, CARTROM)
  if ok and type(v) == "number" then return v end
  ok, v = pcall(mem.read_u8, off, "ROM")
  if ok and type(v) == "number" then return v end
  ok, v = pcall(mem.read_u8, off, "System Bus")
  if ok and type(v) == "number" then return v end
  return nil
end

local function bit_and(a, b)
  -- 16-bit safe AND without the bit library (cores vary).
  local res, bitval = 0, 1
  while a > 0 and b > 0 do
    if a % 2 == 1 and b % 2 == 1 then res = res + bitval end
    a = math.floor(a / 2); b = math.floor(b / 2); bitval = bitval * 2
  end
  return res
end

-- ── ROM identity: the LoROM header title starts with "D3" (validate_rom) ───────
local function rom_is_ap()
  if rom_ok ~= nil then return rom_ok end
  local sig = "D3"
  for i = 1, #sig do
    local b = read_cartrom_u8(ROMHASH_OFF + i - 1)
    if b == nil then return false end          -- not readable yet; retry next poll
    if b ~= string.byte(sig, i) then
      rom_ok = false
      log("non-DKC3 ROM (no 'D3' header) — detection idle, no reports")
      return false
    end
  end
  rom_ok = true
  log("DKC3 ROM verified ('D3' header title present)")
  return true
end

-- ── Multiworld context ────────────────────────────────────────────────────────
local function load_locations(ids)
  if type(ids) ~= "table" then return end
  server_locations = {}
  local n = 0
  for _, id in ipairs(ids) do
    local v = tonumber(id)
    if v then server_locations[v] = true; n = n + 1 end
  end
  log("server location set: " .. n .. " ids")
end

local function wanted(ap_id)
  if server_locations == nil then return true end   -- no set provided → report all
  return server_locations[ap_id] == true
end

-- ── Per-poll snapshot of the single flag block (read once, like game_watcher) ──
local flags = nil   -- 0-indexed byte table of the 0x81-byte block

local function refresh_flags()
  flags = {}
  for i = 0, FLAGS_LEN - 1 do flags[i] = read_wram_u8(FLAGS_BASE_OFF + i) end
end

-- A save file is loaded? (game_watcher's first gate; mirrors validate save name.)
local function save_loaded()
  local b0 = read_wram_u8(SAVE_NAME_OFF)
  if b0 == nil or b0 == SAVE_EMPTY_BYTE then return false end
  -- all-0x55 → uninitialised slot.
  local all_uninit = true
  for i = 0, SAVE_NAME_LEN - 1 do
    local b = read_wram_u8(SAVE_NAME_OFF + i)
    if b ~= SAVE_UNINIT then all_uninit = false; break end
  end
  return not all_uninit
end

-- One location's "checked?" test (mirrors game_watcher's bit math exactly).
--   data = flags[off]; bit_set = (data & (1<<bit)) ~= 0; invert = entry[3]
--   checked when bit_set ~= invert
local function location_checked(off, bit, invert)
  if flags == nil then return false end
  local data = flags[off]
  if data == nil then return false end
  local bit_set    = bit_and(data, 2 ^ bit) ~= 0
  local invert_bit = (invert == 1)
  return bit_set ~= invert_bit
end

-- ── Module contract ───────────────────────────────────────────────────────────
function M.init(ctx)
  if ctx and type(ctx.log) == "function" then log_fn = ctx.log end
  if not resolve_memory_api() then
    log("BizHawk memory API unavailable — module idle")
    ADDRESSES_VERIFIED = false
    return
  end
  local cfg = (ctx and ctx.config) or {}
  load_locations(cfg.locations)
  -- Optional: honour the seed's goal carrier if slot_data exposed it.
  local g = cfg.goal
  if g == nil and type(cfg.slot_data) == "table" then g = cfg.slot_data.goal end
  local gv = tonumber(g)
  if gv == GOAL_OPT_KNAUTILUS or gv == GOAL_OPT_BBHUNT then selected_goal = gv end
  local n = 0; for _ in pairs(LOC) do n = n + 1 end
  log("ready: " .. n .. " location flags; goal="
      .. (selected_goal == nil and "either-carrier" or tostring(selected_goal))
      .. " (items_handling=0b111; receive_item is a documented no-op pending "
      .. "in-emulator verification)")
end

function M.poll()
  local new = {}
  if not ADDRESSES_VERIFIED then return new end
  if not rom_is_ap() then return new end
  if not save_loaded() then return new end        -- game_watcher's no-save gate
  refresh_flags()
  for ap_id, ld in pairs(LOC) do
    if not reported[ap_id] and wanted(ap_id)
       and location_checked(ld[1], ld[2], ld[3]) then
      reported[ap_id] = true
      new[#new + 1] = ap_id
    end
  end
  return new
end

function M.is_goal_complete()
  if not ADDRESSES_VERIFIED or not rom_is_ap() then return false end
  if not save_loaded() then return false end
  refresh_flags()
  if flags == nil then return false end
  local function carrier_set(off, bit)
    local d = flags[off]
    return d ~= nil and bit_and(d, 2 ^ bit) ~= 0
  end
  local knautilus = carrier_set(GOAL_KNAUTILUS_OFF, GOAL_KNAUTILUS_BIT)
  local bbhunt    = carrier_set(GOAL_BBHUNT_OFF,    GOAL_BBHUNT_BIT)
  if selected_goal == GOAL_OPT_KNAUTILUS then return knautilus end
  if selected_goal == GOAL_OPT_BBHUNT    then return bbhunt end
  return knautilus or bbhunt              -- unknown goal → either carrier completes
end

-- Remote multiworld items: see the file header. items_handling = 0b111 (FULL
-- remote) means the dkc3 client owns ALL item delivery — a recv-index handshake
-- at DKC3_RECV_PROGRESS_ADDR, per-item count increments at item_rom_data WRAM
-- offsets, the Bear/Swanky/Boomer coin-display pokes, the Patch & Skis
-- progressive-boat upgrade state machine, and the Victory CLIENT_GOAL trigger,
-- all heavily gated on live game state. That path is the one piece deferred until
-- it can be confirmed in-emulator. No-op (never a wrong write) until then; checks
-- + goal above are fully functional.
function M.receive_item(item_id, meta)
  -- intentionally empty (documented)
end

return M
