-- ═══════════════════════════════════════════════════════════════════════════════
-- Donkey Kong Country.lua — game module for the Archipelago BizHawk connector.
--                          Donkey Kong Country (SNES)
--
-- STATUS: COMMUNITY world. location DETECTION + goal are REAL and SOURCE-DERIVED
-- from the official apworld worlds/dkc (Client.py game_watcher + Locations.py +
-- Levels.py, TheLX5/Archipelago @ branch `dkc`, world_version 1.2.2). The
-- 369-entry location table was GENERATED by JOINING Locations.all_locations
-- (name → AP id) with Levels.location_id_to_level_id (name → [loc_type, level_num,
-- data]) — not hand-copied — so every (AP id → level_num/mask/sanity-index) pair
-- is exact. Mock-verified through MoonSharp against synthetic WRAM/CARTROM. Loads
-- crash-free on any ROM; self-disables on a non-AP cartridge.
--
-- SOURCE: https://github.com/TheLX5/Archipelago  (branch `dkc`, worlds/dkc)
--         game string "Donkey Kong Country", patch_suffix ".apdkc",
--         items_handling 0b111 (FULL remote), base ROM US 1.0
--         MD5 30c5f292ff4cbbfcc00fd8fa96c2de3b.
--
-- MEMORY MODEL (SNI → BizHawk)  — see Research_V2/SNES_BRIDGE_2026-06-12.md
-- ──────────────────────────────────────────────────────────────────────────
--   The dkc client is an SNIClient. Its SNI addresses translate to BizHawk SNES
--   memory domains:
--     SNI WRAM_START(0xF50000)+off → domain "WRAM",    offset off (= $7E0000+off)
--     SNI ROM_START(0x000000)+off  → domain "CARTROM", offset off (raw ROM file
--                                    offset. Fallbacks "ROM"/"System Bus")
--   DKC1 is a HiROM cartridge, so the internal header at SNES $00:FFC0 lives at
--   ROM **file** offset 0xFFC0 (HiROM places the header there — NOT the LoROM
--   0x7FC0). Both the client read (DKC_ROMHASH_START = 0xFFC0) and the AP patch
--   write (patch.write_bytes(0xFFC0, name)) use file offset 0xFFC0, so this module
--   reads the signature from CARTROM 0xFFC0 directly.
--
--   The client reads these RAM blocks (RAM enum in Client.py); this module reads
--   the same bytes:
--     • stage_flags  = Read(DKC_STAGE_FLAGS = WRAM+0x0583, 0x100)  → WRAM
--         level_flags[level_num] → WRAM 0x0583 + level_num
--     • sanity_flags = Read(DKC_SANITY_FLAGS = WRAM+0x1F800, 0x100) → WRAM
--         sanity_flags[idx]      → WRAM 0x1F800 + idx
--     • nmi_pointer  = Read(WRAM+0x001C, 0x02) → WRAM, u16 LE (0xE6B1 == in map)
--     • current_level= Read(WRAM+0x0563, 0x01) → WRAM
--     • loaded_level = Read(WRAM+0x003E, 0x01) → WRAM (goal: == 0x4C)
--     • brightness   = Read(WRAM+0x051A, 0x01) → WRAM (& 0x0F == 0x0F = full)
--     • kong_letters = Read(WRAM+0x057F, 0x01) → WRAM (& 0x10 == KONG complete)
--   IDENTITY / VALIDATION (mirrors validate_rom): ROM header at CARTROM 0xFFC0
--   begins with "DKC1" and is not all-zero. The AP basepatch bakes this in.
--
-- HOW DKC CHECKS WORK (mirrors Client.py game_watcher; per-location loc_type)
--   Each location carries {loc_type, level_num, data}. game_watcher only processes
--   a location while NOT in a map/transition (nmi_pointer != 0xE6B1) AND at full
--   brightness (brightness & 0x0F == 0x0F):
--     0x00 Level clear : level_flags[level_num] & 0x01
--     0x01 KONG        : level_num == current_level AND kong_flags & 0x10 == 0x10
--     0x02 Bonus       : level_flags[level_num] & data            (data = bonus mask)
--     0x03 Tokens      : level_num == current_level AND sanity_flags[data] & 0x04
--     0x04 Balloons    : level_num == current_level AND sanity_flags[data] & 0x01
--     0x05 Bunches     : level_num == current_level AND sanity_flags[data] & 0x02
--   Reptile Rumble appears under two ids: current_level 0xEA is remapped to 0x01
--   (game_watcher does the same) so its KONG/sanity checks match.
--   The KONG/token/balloon/bunch *sanity* check families are each gated by a
--   per-seed settings byte (kong_checks/token_checks/…). When the server didn't
--   place those locations, they simply aren't in this slot's `locations` filter,
--   so reporting them is impossible anyway — the settings read is therefore not
--   required for correctness and is omitted (it would need a CARTROM settings
--   read that adds no safety here).
--
-- WHAT THIS DOES
--   • poll(): the game_watcher location scan above → AP location ids, gated to the
--     slot's server location set and to the in-game state (game_state set once the
--     player has entered the map, i.e. nmi_pointer has read 0xE6B1 at least once).
--   • is_goal_complete(): loaded_level (WRAM 0x003E) == 0x4C — the K. Rool /
--     Gangplank Galleon credits map the client flags as CLIENT_GOAL.
--   • receive_item(): NO-OP (documented). items_handling = 0b111 (FULL remote) —
--     the dkc client owns ALL item delivery via an intricate, heavily-state-gated
--     set of SRAM/WRAM writes (kong unlock bitmask, ability/animal/object unlock
--     bytes, currency increments, trap counters, an SFX strobe, plus a recv-index
--     handshake at DKC_RECV_INDEX, all gated on full brightness; EnergyLink DK
--     barrels / TrapLink / DeathLink on top). That delivery path is the one piece
--     that needs in-emulator verification before it is wired, so it is left out
--     rather than shipped unverified (a wrong write would corrupt the save or
--     desync the recv-index). Checks + goal above are fully functional regardless.
--
-- MODULE CONTRACT (called by bizhawk_ap_connector.lua)
--   M.init(ctx) / M.poll() -> {ids} / M.is_goal_complete() -> bool /
--   M.receive_item(item_id, meta)
-- ═══════════════════════════════════════════════════════════════════════════════

local M = {}
M.name = "Donkey Kong Country"

local ADDRESSES_VERIFIED = true   -- table generated from worlds/dkc source

-- ── Memory domains ────────────────────────────────────────────────────────────
local WRAM    = "WRAM"
local CARTROM = "CARTROM"     -- SNES cartridge ROM in BizHawk; fallbacks below

-- ── Addresses / constants (worlds/dkc/Client.py module top) ───────────────────
-- Expressed as BizHawk-domain offsets (already net of WRAM_START / ROM_START).
local STAGE_FLAGS_OFF   = 0x0583      -- WRAM: base of the 0x100-byte level-flag array
local SANITY_FLAGS_OFF  = 0x1F800     -- WRAM: base of the 0x100-byte sanity-flag array
local NMI_POINTER_OFF   = 0x001C      -- WRAM: u16 LE; == 0xE6B1 while in a map
local CURRENT_LEVEL_OFF = 0x0563      -- WRAM: id of the level currently being played
local LOADED_LEVEL_OFF  = 0x003E      -- WRAM: loaded level id (goal: == 0x4C)
local BRIGHTNESS_OFF    = 0x051A      -- WRAM: screen brightness; & 0x0F == 0x0F = full
local KONG_LETTERS_OFF  = 0x057F      -- WRAM: KONG-letter flags; & 0x10 == complete
local ROMHASH_OFF       = 0xFFC0      -- CARTROM: ROM-header title; first 4 = "DKC1"

-- Sentinel values.
local IN_MAP_NMI        = 0xE6B1      -- nmi_pointer value while on the world map
local GOAL_LOADED_LEVEL = 0x004C      -- loaded_level value on the K. Rool ending map
local REPTILE_RUMBLE_ALT= 0xEA        -- current_level alias remapped to 0x01

-- Per-location loc_type tags (Client.py game_watcher).
local T_CLEAR    = 0x00
local T_KONG     = 0x01
local T_BONUS    = 0x02
local T_TOKEN    = 0x03
local T_BALLOON  = 0x04
local T_BUNCH    = 0x05

-- ── Location table (GENERATED from worlds/dkc Locations.py ⋈ Levels.py) ────────
-- ap_id -> { loc_type, level_num, data }. 369 entries (data present only for
-- bonus/token/balloon/bunch types). AP ids are absolute location_name_to_id
-- values (STARTING_ID 0xBF1000-based); detection is self-contained.
local LOC = {
  [12521472]={0,22},[12521473]={0,12},[12521474]={0,1},[12521475]={0,191},[12521476]={0,23},[12521477]={0,224},
  [12521478]={0,217},[12521479]={0,46},[12521480]={0,7},[12521481]={0,49},[12521482]={0,66},[12521483]={0,225},
  [12521484]={0,165},[12521485]={0,164},[12521486]={0,208},[12521487]={0,67},[12521488]={0,13},[12521489]={0,222},
  [12521490]={0,229},[12521491]={0,36},[12521492]={0,109},[12521493]={0,167},[12521494]={0,62},[12521495]={0,20},
  [12521496]={0,206},[12521497]={0,226},[12521498]={0,64},[12521499]={0,47},[12521500]={0,24},[12521501]={0,34},
  [12521503]={0,39},[12521504]={0,65},[12521505]={0,227},[12521506]={0,48},[12521507]={0,18},[12521508]={0,10},
  [12521509]={0,54},[12521510]={0,43},[12521511]={0,228},[12521512]={0,224},[12521514]={0,225},[12521515]={0,229},
  [12521516]={0,226},[12521517]={0,227},[12521518]={0,228},[12521536]={1,22},[12521537]={1,12},[12521538]={1,1},
  [12521539]={1,191},[12521540]={1,23},[12521542]={1,217},[12521543]={1,46},[12521544]={1,7},[12521545]={1,49},
  [12521546]={1,66},[12521548]={1,165},[12521549]={1,164},[12521550]={1,208},[12521551]={1,67},[12521552]={1,13},
  [12521553]={1,222},[12521555]={1,36},[12521556]={1,109},[12521557]={1,167},[12521558]={1,62},[12521559]={1,20},
  [12521560]={1,206},[12521562]={1,64},[12521563]={1,47},[12521564]={1,24},[12521565]={1,34},[12521567]={1,39},
  [12521568]={1,65},[12521570]={1,48},[12521571]={1,18},[12521572]={1,10},[12521573]={1,54},[12521574]={1,43},
  [12521600]={2,22,2},[12521601]={2,22,4},[12521602]={2,12,2},[12521603]={2,12,4},[12521604]={2,1,2},[12521605]={2,1,4},
  [12521606]={2,1,8},[12521607]={2,23,2},[12521608]={2,23,4},[12521609]={2,217,2},[12521610]={2,7,2},[12521611]={2,7,4},
  [12521612]={2,49,2},[12521613]={2,49,4},[12521614]={2,66,2},[12521615]={2,66,4},[12521616]={2,66,8},[12521617]={2,165,2},
  [12521618]={2,165,4},[12521619]={2,165,8},[12521620]={2,164,2},[12521621]={2,164,4},[12521622]={2,208,2},[12521623]={2,208,4},
  [12521624]={2,67,2},[12521625]={2,67,4},[12521626]={2,13,2},[12521627]={2,13,4},[12521628]={2,13,8},[12521629]={2,13,16},
  [12521630]={2,13,32},[12521631]={2,36,2},[12521632]={2,36,4},[12521633]={2,36,8},[12521634]={2,109,2},[12521635]={2,109,4},
  [12521636]={2,109,8},[12521637]={2,167,2},[12521638]={2,167,4},[12521639]={2,20,2},[12521640]={2,20,4},[12521641]={2,206,2},
  [12521642]={2,206,4},[12521643]={2,64,2},[12521644]={2,64,4},[12521645]={2,64,8},[12521646]={2,64,16},[12521647]={2,47,2},
  [12521648]={2,47,8},[12521649]={2,47,4},[12521650]={2,24,2},[12521651]={2,24,4},[12521652]={2,24,8},[12521653]={2,39,2},
  [12521654]={2,39,4},[12521655]={2,39,8},[12521656]={2,65,2},[12521657]={2,65,4},[12521658]={2,48,2},[12521659]={2,18,2},
  [12521660]={2,18,4},[12521661]={2,10,2},[12521662]={2,10,4},[12521663]={2,54,2},[12521664]={2,54,4},[12521665]={2,43,2},
  [12521666]={2,43,4},[12521728]={3,22,38},[12521729]={3,12,22},[12521730]={3,12,58},[12521731]={3,1,60},[12521732]={3,191,16},
  [12521733]={3,23,16},[12521734]={3,23,42},[12521735]={3,217,29},[12521736]={3,46,10},[12521737]={3,7,0},[12521738]={3,49,32},
  [12521739]={3,164,84},[12521740]={3,67,0},[12521741]={3,13,50},[12521742]={3,222,40},[12521743]={3,36,75},[12521744]={3,109,51},
  [12521745]={3,62,31},[12521746]={3,62,40},[12521747]={3,47,60},[12521748]={3,34,71},[12521749]={3,34,57},[12521750]={3,39,26},
  [12521751]={3,65,10},[12521752]={3,48,37},[12521753]={3,18,64},[12521754]={3,10,17},[12521755]={3,10,50},[12521756]={3,43,39},
  [12521984]={4,22,1},[12521985]={4,22,17},[12521986]={4,22,26},[12521987]={4,22,30},[12521988]={4,22,61},[12521989]={4,22,62},
  [12521990]={4,191,28},[12521991]={4,46,21},[12521992]={4,208,69},[12521993]={4,36,7},[12521994]={4,36,119},[12521995]={4,62,52},
  [12522240]={5,22,4},[12522241]={5,22,6},[12522242]={5,22,7},[12522243]={5,22,11},[12522244]={5,22,15},[12522245]={5,22,16},
  [12522246]={5,22,20},[12522247]={5,22,19},[12522248]={5,22,18},[12522249]={5,22,24},[12522250]={5,22,23},[12522251]={5,22,22},
  [12522252]={5,22,27},[12522253]={5,22,37},[12522254]={5,22,48},[12522255]={5,22,54},[12522256]={5,22,56},[12522257]={5,22,58},
  [12522258]={5,22,59},[12522259]={5,12,2},[12522260]={5,12,5},[12522261]={5,12,6},[12522262]={5,12,4},[12522263]={5,12,3},
  [12522264]={5,12,12},[12522265]={5,12,13},[12522266]={5,12,15},[12522267]={5,12,19},[12522268]={5,12,24},[12522269]={5,12,27},
  [12522270]={5,12,28},[12522271]={5,12,39},[12522272]={5,12,41},[12522273]={5,12,45},[12522274]={5,12,59},[12522275]={5,12,71},
  [12522276]={5,12,72},[12522277]={5,12,78},[12522278]={5,1,2},[12522279]={5,1,7},[12522280]={5,1,15},[12522281]={5,1,22},
  [12522282]={5,1,25},[12522283]={5,1,29},[12522284]={5,1,33},[12522285]={5,1,37},[12522286]={5,1,43},[12522287]={5,1,50},
  [12522288]={5,1,64},[12522289]={5,1,67},[12522290]={5,1,69},[12522291]={5,1,80},[12522292]={5,191,9},[12522293]={5,191,18},
  [12522294]={5,23,9},[12522295]={5,23,23},[12522296]={5,23,38},[12522297]={5,23,39},[12522298]={5,23,56},[12522299]={5,23,60},
  [12522300]={5,23,67},[12522301]={5,23,72},[12522302]={5,23,77},[12522303]={5,23,108},[12522304]={5,23,113},[12522305]={5,23,112},
  [12522306]={5,217,1},[12522307]={5,217,11},[12522308]={5,217,18},[12522309]={5,217,27},[12522310]={5,217,38},[12522311]={5,46,0},
  [12522312]={5,46,9},[12522313]={5,46,20},[12522314]={5,7,3},[12522315]={5,7,8},[12522316]={5,7,18},[12522317]={5,7,27},
  [12522318]={5,7,33},[12522319]={5,7,44},[12522320]={5,7,52},[12522321]={5,7,78},[12522322]={5,7,82},[12522323]={5,7,88},
  [12522324]={5,49,4},[12522325]={5,49,13},[12522326]={5,49,30},[12522327]={5,49,45},[12522328]={5,49,58},[12522329]={5,49,66},
  [12522330]={5,49,97},[12522331]={5,66,6},[12522332]={5,66,16},[12522333]={5,66,32},[12522334]={5,66,48},[12522335]={5,66,55},
  [12522336]={5,66,61},[12522337]={5,66,73},[12522338]={5,66,75},[12522339]={5,66,76},[12522340]={5,165,6},[12522341]={5,165,20},
  [12522342]={5,165,45},[12522343]={5,165,48},[12522344]={5,165,55},[12522345]={5,165,85},[12522346]={5,164,1},[12522347]={5,164,25},
  [12522348]={5,164,48},[12522349]={5,164,86},[12522350]={5,208,4},[12522351]={5,208,12},[12522352]={5,208,18},[12522353]={5,208,52},
  [12522354]={5,208,92},[12522355]={5,67,2},[12522356]={5,67,12},[12522357]={5,67,21},[12522358]={5,67,33},[12522359]={5,67,53},
  [12522360]={5,67,61},[12522361]={5,67,68},[12522362]={5,67,75},[12522363]={5,13,5},[12522364]={5,13,12},[12522365]={5,13,25},
  [12522366]={5,13,28},[12522367]={5,13,37},[12522368]={5,13,45},[12522369]={5,13,52},[12522370]={5,13,64},[12522371]={5,13,65},
  [12522372]={5,222,4},[12522373]={5,222,18},[12522374]={5,36,5},[12522375]={5,36,21},[12522376]={5,36,70},[12522377]={5,36,122},
  [12522378]={5,36,125},[12522379]={5,109,38},[12522380]={5,109,35},[12522381]={5,109,47},[12522382]={5,109,45},[12522383]={5,109,67},
  [12522384]={5,109,104},[12522385]={5,109,106},[12522386]={5,109,92},[12522387]={5,109,73},[12522388]={5,167,6},[12522389]={5,167,35},
  [12522390]={5,167,55},[12522391]={5,62,6},[12522392]={5,62,38},[12522393]={5,62,39},[12522394]={5,62,41},[12522395]={5,62,42},
  [12522396]={5,20,50},[12522397]={5,206,47},[12522398]={5,64,39},[12522399]={5,64,62},[12522400]={5,47,7},[12522401]={5,24,15},
  [12522402]={5,24,42},[12522403]={5,24,51},[12522404]={5,34,14},[12522405]={5,34,5},[12522406]={5,34,18},[12522407]={5,34,41},
  [12522408]={5,34,44},[12522409]={5,34,65},[12522410]={5,39,65},[12522411]={5,65,44},[12522412]={5,48,23},[12522413]={5,48,30},
  [12522414]={5,48,72},[12522415]={5,48,89},[12522416]={5,18,21},[12522417]={5,18,42},[12522418]={5,10,9},[12522419]={5,10,20},
  [12522420]={5,54,63},[12522421]={5,54,116},[12522422]={5,43,87},
}

-- ── Internal state ────────────────────────────────────────────────────────────
local reported         = {}     -- ap_id -> true once returned from poll()
local server_locations = nil    -- set of ap_ids the server expects (nil = all)
local rom_ok           = nil    -- cached "DKC1" header result
local game_state       = false  -- true once the player has entered the map
local mem              = {}
local log_fn           = nil

-- ── Logging ───────────────────────────────────────────────────────────────────
local function log(msg)
  if log_fn then pcall(log_fn, "[dkc] " .. tostring(msg)) end
end

-- ── Memory API (resolved at init; 2-arg domain form + current-domain fallback) ─
local function resolve_memory_api()
  if not memory then return false end
  mem.read_u8  = memory.read_u8     or memory.readbyte
  mem.read_u16 = memory.read_u16_le or memory.readword
  return mem.read_u8 ~= nil
end

local function rd(fn, addr, domain)
  if not fn then return nil end
  local ok, v = pcall(fn, addr, domain)
  if ok and type(v) == "number" then return v end
  ok, v = pcall(fn, addr)                       -- older API: current domain
  if ok and type(v) == "number" then return v end
  return nil
end

local function read_wram_u8(off)   return rd(mem.read_u8,  off, WRAM) end
local function read_wram_u16(off)  return rd(mem.read_u16, off, WRAM) end

-- CARTROM reads with "ROM" / "System Bus" domain-name fallbacks (cores vary;
-- the raw-file-offset CARTROM/ROM form is what every SNES BizHawk core exposes).
local function read_cartrom_u8(off)
  local ok, v = pcall(mem.read_u8, off, CARTROM)
  if ok and type(v) == "number" then return v end
  ok, v = pcall(mem.read_u8, off, "ROM")
  if ok and type(v) == "number" then return v end
  ok, v = pcall(mem.read_u8, off, "System Bus")
  if ok and type(v) == "number" then return v end
  return nil
end

local function bit_and(a, b)
  -- 8/16-bit safe AND without the bit library (cores vary).
  local res, bitval = 0, 1
  while a > 0 and b > 0 do
    if a % 2 == 1 and b % 2 == 1 then res = res + bitval end
    a = math.floor(a / 2); b = math.floor(b / 2); bitval = bitval * 2
  end
  return res
end

-- ── ROM identity: the SNES header title starts with "DKC1" (validate_rom) ──────
-- validate_rom also rejects an all-zero hash; a real "DKC1" prefix already
-- excludes that, so the prefix check is sufficient here.
local function rom_is_ap()
  if rom_ok ~= nil then return rom_ok end
  local sig = "DKC1"
  for i = 1, #sig do
    local b = read_cartrom_u8(ROMHASH_OFF + i - 1)
    if b == nil then return false end          -- not readable yet; retry next poll
    if b ~= string.byte(sig, i) then
      rom_ok = false
      log("non-DKC1 ROM (no 'DKC1' header) — detection idle, no reports")
      return false
    end
  end
  rom_ok = true
  log("DKC ROM verified ('DKC1' header title present)")
  return true
end

-- ── Multiworld context ────────────────────────────────────────────────────────
local function load_locations(ids)
  if type(ids) ~= "table" then return end
  server_locations = {}
  local n = 0
  for _, id in ipairs(ids) do
    local v = tonumber(id)
    if v then server_locations[v] = true; n = n + 1 end
  end
  log("server location set: " .. n .. " ids")
end

local function wanted(ap_id)
  if server_locations == nil then return true end   -- no set provided → report all
  return server_locations[ap_id] == true
end

-- ── Per-poll snapshots (read once per poll, matching game_watcher) ────────────
local snap = {}     -- the RAM the client reads, refreshed each poll

local function read_region_wram(off, len)
  local t = {}
  for i = 0, len - 1 do t[i] = read_wram_u8(off + i) end
  return t
end

local function refresh_snapshot()
  snap.nmi_pointer   = read_wram_u16(NMI_POINTER_OFF)
  snap.current_level = read_wram_u8(CURRENT_LEVEL_OFF)
  snap.loaded_level  = read_wram_u8(LOADED_LEVEL_OFF)
  snap.brightness    = read_wram_u8(BRIGHTNESS_OFF)
  snap.kong_flags    = read_wram_u8(KONG_LETTERS_OFF)
  snap.level_flags   = read_region_wram(STAGE_FLAGS_OFF,  0x100)
  snap.sanity_flags  = read_region_wram(SANITY_FLAGS_OFF, 0x100)
  -- Reptile Rumble has two ids; game_watcher folds 0xEA into 0x01.
  if snap.current_level == REPTILE_RUMBLE_ALT then snap.current_level = 0x01 end
end

-- full brightness == 0x0F in the low nibble (game_watcher gate).
local function full_brightness()
  return snap.brightness ~= nil and bit_and(snap.brightness, 0x0F) == 0x0F
end

-- in a map / transition? game_watcher skips location processing while here.
local function in_map()
  return snap.nmi_pointer ~= nil and snap.nmi_pointer == IN_MAP_NMI
end

-- ── One location's "checked?" test (mirrors game_watcher per loc_type) ────────
local function location_checked(loc_type, level_num, data)
  if loc_type == T_CLEAR then
    local f = snap.level_flags[level_num]
    return f ~= nil and bit_and(f, 0x01) ~= 0
  elseif loc_type == T_KONG then
    if snap.current_level ~= level_num then return false end
    return snap.kong_flags ~= nil and bit_and(snap.kong_flags, 0x10) == 0x10
  elseif loc_type == T_BONUS then
    local f = snap.level_flags[level_num]
    return f ~= nil and data ~= nil and bit_and(f, data) ~= 0
  elseif loc_type == T_TOKEN then
    if snap.current_level ~= level_num or data == nil then return false end
    local f = snap.sanity_flags[data]
    return f ~= nil and bit_and(f, 0x04) == 0x04
  elseif loc_type == T_BALLOON then
    if snap.current_level ~= level_num or data == nil then return false end
    local f = snap.sanity_flags[data]
    return f ~= nil and bit_and(f, 0x01) == 0x01
  elseif loc_type == T_BUNCH then
    if snap.current_level ~= level_num or data == nil then return false end
    local f = snap.sanity_flags[data]
    return f ~= nil and bit_and(f, 0x02) == 0x02
  end
  return false
end

-- ── Detection gate ────────────────────────────────────────────────────────────
-- game_watcher only marks game_state true after nmi_pointer reads 0xE6B1 (the
-- player has set foot on the map), and then only commits checks when NOT in a
-- map/transition and at full brightness. We latch game_state the same way.
local function update_game_state()
  if in_map() then game_state = true end
  return game_state
end

-- ── Module contract ───────────────────────────────────────────────────────────
function M.init(ctx)
  if ctx and type(ctx.log) == "function" then log_fn = ctx.log end
  if not resolve_memory_api() then
    log("BizHawk memory API unavailable — module idle")
    ADDRESSES_VERIFIED = false
    return
  end
  local cfg = (ctx and ctx.config) or {}
  load_locations(cfg.locations)
  local n = 0; for _ in pairs(LOC) do n = n + 1 end
  log("ready: " .. n .. " location flags (items_handling=0b111; receive_item is a "
      .. "documented no-op pending in-emulator verification)")
end

function M.poll()
  local new = {}
  if not ADDRESSES_VERIFIED then return new end
  if not rom_is_ap() then return new end
  refresh_snapshot()
  if not update_game_state() then return new end
  -- game_watcher breaks out of the location loop while in a map or not at full
  -- brightness; mirror that exactly so a transition never mis-reports.
  if in_map() or not full_brightness() then return new end
  for ap_id, ld in pairs(LOC) do
    if not reported[ap_id] and wanted(ap_id)
       and location_checked(ld[1], ld[2], ld[3]) then
      reported[ap_id] = true
      new[#new + 1] = ap_id
    end
  end
  return new
end

function M.is_goal_complete()
  if not ADDRESSES_VERIFIED or not rom_is_ap() then return false end
  refresh_snapshot()
  -- loaded_level == 0x4C is the K. Rool / Gangplank Galleon ending map.
  return snap.loaded_level ~= nil and snap.loaded_level == GOAL_LOADED_LEVEL
end

-- Remote multiworld items: see the file header. items_handling = 0b111 (FULL
-- remote) means the dkc client owns ALL item delivery — kong-unlock bitmask,
-- ability/animal/object unlock bytes, currency increments, trap counters, an SFX
-- strobe, a recv-index handshake at DKC_RECV_INDEX, plus EnergyLink DK barrels /
-- TrapLink / DeathLink, all heavily gated on game state and full brightness. That
-- path is the one piece deferred until it can be confirmed in-emulator. No-op
-- (never a wrong write) until then; checks + goal above are fully functional.
function M.receive_item(item_id, meta)
  -- intentionally empty (documented)
end

return M
