-- ═══════════════════════════════════════════════════════════════════════════════
-- earthbound.lua — game module for the Archipelago BizHawk connector.
--                 EarthBound (SNES)
--
-- STATUS: REAL implementation, SOURCE-DERIVED from the official AP world
-- worlds/earthbound (Client.py, an SNIClient subclass, + Rom.py +
-- game_data/local_data.py, world_version 4.3.1). The 526-entry location table
-- was GENERATED by parsing local_data.py `check_table` with Python (not
-- hand-copied), so it is exact; signature/goal/item-delivery addresses are read
-- straight out of Client.py. Loads and runs crash-free on any ROM; self-disables
-- on a non-AP cartridge.
--
-- MEMORY MODEL (SNI → BizHawk)
-- ────────────────────────────
--   EarthBound's client is an SNIClient. SNI addresses translate to BizHawk SNES
--   memory domains exactly as the A Link to the Past module documents:
--     SNI WRAM_START(0xF50000)+off → domain "WRAM",   offset off  (= $7E0000+off)
--     SNI SRAM_START(0xE00000)+off → domain "CARTRAM" (fallback "SRAM")
--   The AP basepatch writes a 21-byte ROM name beginning "MOM2AP" at the SNES
--   internal header $00:FFC0 (Rom.py: rom.write_bytes(0x00FFC0, rom.name)). Unlike
--   ALttP — whose AP marker is mirrored into CARTRAM — EarthBound's marker lives
--   ONLY in cartridge ROM, so we read it from BizHawk's "System Bus" at 0x00FFC0
--   (the client's literal address), falling back to "CARTROM" 0xFFC0 / 0x7FC0.
--   NOTE: the snes9x NWA bridge exposes only WRAM + SRAM (no ROM region), so the
--   ROM-signature gate cannot run there — consistent with snes9x being the
--   experimental, not-yet-live-verified backend. BizHawk is the verified path.
--
-- WHAT THIS DOES (mirrors worlds/earthbound/Client.py game_watcher)
--   • poll(): the client's location scan — two flag regions:
--       WRAM 0x9C00 (0x88 bytes) for the main world (loc_id < 0xEB1000) and
--       WRAM 0xB721 (0x41 bytes) for shop slots (loc_id >= 0xEB1000); each entry
--       is {byte_offset, bit} and a check fires when byte & (1<<bit). Gated to the
--       slot's server location set, to "not on the title screen" (SAVE_FILE != 0)
--       and to "not mid-textbox" (OPEN_WINDOW == 0xFF) exactly as the client.
--   • is_goal_complete(): GAME_CLEAR (WRAM 0x9C85) bit 0 — the client's CLIENT_GOAL
--     trigger (`game_clear[0] & 0x01`).
--   • receive_item(): the client's queue-driven delivery. ITEMQUEUE_HIGH
--     (WRAM 0xB576, u16) is the count already pushed to the game; when it trails
--     the delivered stream and the game is idle (no item in flight, no cutscene),
--     the next item id (item.item-0xEB0000) is written to the right receive slot:
--       id<=0xFD            → ITEM_RECEIVED   (WRAM 0xB570)
--       id in money table   → MONEY_RECIVED   (WRAM 0xB5F1) = table index + 1
--       else (special)      → SPECIAL_RECEIVED(WRAM 0xB572) = client_specials[id]
--     The money/special tables are tiny (3 + 22 entries) and embedded verbatim.
--     items_handling here is 0b001 by default (the patched game grants its own
--     found items) or 0b111 when the slot enabled remote_items; in BOTH cases the
--     server still streams this slot's items (those from other players at minimum),
--     so the delivery path is needed and is implemented faithfully.
--
-- MODULE CONTRACT (called by bizhawk_ap_connector.lua)
--   M.init(ctx) / M.poll() -> {ids} / M.is_goal_complete() -> bool /
--   M.receive_item(item_id, meta)
-- ═══════════════════════════════════════════════════════════════════════════════

local M = {}
M.name = "earthbound"

-- Tables generated from worlds/earthbound source; ap ids are absolute (the
-- 0xEB0000 base is already baked into the keys), so detection is self-contained.
local ADDRESSES_VERIFIED = true
local WORLD_VERSION      = "4.3.1"   -- archipelago.json / local_data.world_version

-- ── Memory domains ────────────────────────────────────────────────────────────
local WRAM    = "WRAM"
local CARTRAM = "CARTRAM"     -- SNES battery SRAM in BizHawk; fallback "SRAM"

-- ── SNI-space constants (Client.py module top), as BizHawk WRAM offsets ────────
-- (already net of WRAM_START 0xF50000).
local SAVE_FILE_OFF    = 0xB4A1        -- WRAM: save slot; 0 = title screen
local OPEN_WINDOW_OFF  = 0x8958        -- WRAM: textbox-open byte; 0xFF = clear
local GAME_CLEAR_OFF   = 0x9C85        -- WRAM: goal byte (bit 0 = beat the game)
local GIYGAS_CLEAR_OFF = 0x9C11        -- WRAM: epilogue flag (bit 0 = in epilogue)
local CUR_SCENE_OFF    = 0x97B8        -- WRAM: nonzero during cutscenes
-- Location flag regions.
local LOC_MAIN_BASE    = 0x9C00        -- WRAM: main-world flags (0x88 = 136 bytes)
local LOC_SHOP_BASE    = 0xB721        -- WRAM: shop-slot flags (0x41 = 65 bytes)
-- Item delivery (Client.py receive loop).
local ITEMQUEUE_HIGH   = 0xB576        -- WRAM u16: items already pushed to the game
local ITEM_RECEIVED    = 0xB570        -- WRAM u8 : standard item id (<= 0xFD)
local SPECIAL_RECEIVED = 0xB572        -- WRAM u8 : special item routine id
local MONEY_RECIVED    = 0xB5F1        -- WRAM u8 : money item (1-based money index)

-- ROM identity: the AP basepatch writes "MOM2AP…" at the SNES header $00:FFC0.
local AP_SIG          = "MOM2AP"
local SIG_BUS_ADDR    = 0x00FFC0       -- "System Bus": client's literal address
local SIG_CARTROM_HI  = 0xFFC0         -- "CARTROM": HiROM file offset of the header
local SIG_CARTROM_LO  = 0x7FC0         -- "CARTROM": LoROM offset (last-ditch)

-- The 0xEB0000 item-id base + the money / special id remaps (Client.py +
-- local_data.py). money_id_table is keyed by the game-local id (item-0xEB0000):
--   0x114 -> $10, 0x115 -> $100, 0x116 -> $1000  → written value = (index)+1.
local ITEM_ID_BASE = 0xEB0000
local MONEY_IDS    = { 0x114, 0x115, 0x116 }     -- order = money index source
-- client_specials: game-local id (item-0xEB0000) -> SPECIAL_RECEIVED routine id.
local CLIENT_SPECIALS = {
  [0xFE]=0x01,[0xFF]=0x02,[0x100]=0x0D,[0x101]=0x03,[0x102]=0x05,[0x103]=0x0E,
  [0x104]=0x06,[0x105]=0x07,[0x106]=0x08,[0x107]=0x09,[0x108]=0x0A,[0x109]=0x0B,
  [0x10A]=0x0C,[0x10B]=0x0F,[0x10C]=0x10,[0x10D]=0x11,[0x10E]=0x12,[0x10F]=0x13,
  [0x110]=0x14,[0x111]=0x04,[0x112]=0x15,[0x113]=0x16,
}

-- ── Location tables (GENERATED from local_data.py check_table) ─────────────────
-- ap_id -> { byte_offset, bit }. Checked when REGION[byte_offset] & (1<<bit).
-- Two regions, read separately, exactly as Client.py:
--   loc_id <  0xEB1000 → WRAM 0x9C00 + byte_offset   (main world, 251 entries)
--   loc_id >= 0xEB1000 → WRAM 0xB721 + byte_offset   (shop slots, 275 entries)
local LOC_MAIN = {
  [15400960]={17,3},[15400961]={108,4},[15400962]={107,7},[15400963]={17,6},[15400964]={132,3},
  [15400965]={130,1},[15400966]={71,6},[15400967]={19,0},[15400968]={108,0},[15400969]={17,4},
  [15400970]={108,1},[15400971]={108,2},[15400972]={108,3},[15400973]={17,7},[15400974]={17,5},
  [15400975]={108,6},[15400976]={108,7},[15400977]={108,5},[15400978]={18,0},[15400979]={91,5},
  [15400980]={109,1},[15400981]={109,2},[15400982]={109,0},[15400983]={76,5},[15400984]={18,2},
  [15400985]={18,1},[15400986]={18,3},[15400987]={18,4},[15400988]={133,2},[15400989]={110,0},
  [15400990]={109,5},[15400991]={109,7},[15400992]={110,1},[15400993]={110,2},[15400994]={109,6},
  [15400995]={131,7},[15400996]={109,4},[15400997]={109,3},[15400998]={18,5},[15400999]={133,4},
  [15401000]={23,1},[15401001]={110,4},[15401002]={110,5},[15401003]={110,3},[15401004]={18,6},
  [15401005]={110,6},[15401006]={111,0},[15401007]={111,1},[15401008]={110,7},[15401009]={102,2},
  [15401010]={13,6},[15401011]={111,2},[15401012]={111,3},[15401013]={115,4},[15401014]={115,3},
  [15401015]={115,5},[15401016]={115,6},[15401017]={115,7},[15401018]={116,0},[15401019]={116,1},
  [15401020]={132,5},[15401021]={29,2},[15401022]={29,3},[15401023]={29,4},[15401024]={115,2},
  [15401025]={114,5},[15401026]={115,1},[15401027]={114,4},[15401028]={115,0},[15401029]={114,7},
  [15401030]={114,6},[15401031]={118,2},[15401032]={118,7},[15401033]={118,1},[15401034]={118,4},
  [15401035]={118,5},[15401036]={118,6},[15401037]={118,3},[15401038]={56,0},[15401039]={119,0},
  [15401040]={19,1},[15401041]={112,0},[15401042]={111,5},[15401043]={111,7},[15401044]={112,2},
  [15401045]={112,1},[15401046]={111,6},[15401047]={111,4},[15401048]={133,1},[15401049]={18,7},
  [15401050]={134,3},[15401051]={10,6},[15401052]={49,5},[15401053]={83,4},[15401054]={23,7},
  [15401055]={48,2},[15401056]={113,0},[15401057]={112,6},[15401058]={112,4},[15401059]={112,7},
  [15401060]={112,5},[15401061]={113,3},[15401062]={113,1},[15401063]={113,2},[15401064]={112,3},
  [15401065]={85,1},[15401066]={114,3},[15401067]={113,5},[15401068]={114,1},[15401069]={113,6},
  [15401070]={113,7},[15401071]={113,4},[15401072]={114,0},[15401073]={114,2},[15401074]={88,3},
  [15401075]={131,4},[15401076]={120,5},[15401077]={120,3},[15401078]={119,3},[15401079]={120,6},
  [15401080]={120,2},[15401081]={119,5},[15401082]={119,2},[15401083]={119,7},[15401084]={119,4},
  [15401085]={119,1},[15401086]={120,1},[15401087]={120,0},[15401088]={120,4},[15401089]={119,6},
  [15401090]={116,2},[15401091]={116,3},[15401092]={116,4},[15401093]={116,5},[15401094]={65,7},
  [15401095]={116,6},[15401096]={116,7},[15401097]={77,1},[15401098]={84,4},[15401099]={25,3},
  [15401100]={131,6},[15401101]={99,7},[15401102]={121,2},[15401103]={121,3},[15401104]={121,6},
  [15401105]={121,5},[15401106]={121,4},[15401107]={25,2},[15401108]={122,2},[15401109]={122,3},
  [15401110]={122,1},[15401111]={121,7},[15401112]={122,0},[15401113]={120,7},[15401114]={121,0},
  [15401115]={121,1},[15401116]={25,4},[15401117]={100,4},[15401118]={90,7},[15401119]={50,6},
  [15401120]={15,4},[15401121]={124,6},[15401122]={124,7},[15401123]={125,0},[15401124]={42,0},
  [15401125]={125,2},[15401126]={125,4},[15401127]={125,3},[15401128]={125,1},[15401129]={87,4},
  [15401130]={9,7},[15401131]={125,6},[15401132]={125,5},[15401133]={125,7},[15401134]={122,6},
  [15401135]={122,4},[15401136]={122,5},[15401137]={123,0},[15401138]={123,1},[15401139]={51,3},
  [15401140]={122,7},[15401141]={131,0},[15401142]={49,7},[15401143]={123,6},[15401144]={123,2},
  [15401145]={124,5},[15401146]={124,0},[15401147]={124,1},[15401148]={124,2},[15401149]={123,4},
  [15401150]={123,7},[15401151]={123,5},[15401152]={124,4},[15401153]={124,3},[15401154]={123,3},
  [15401155]={89,1},[15401156]={126,4},[15401157]={126,3},[15401158]={126,2},[15401159]={126,5},
  [15401160]={126,0},[15401161]={126,1},[15401162]={62,7},[15401163]={63,1},[15401164]={63,0},
  [15401165]={63,2},[15401166]={62,6},[15401167]={132,7},[15401168]={127,7},[15401169]={131,1},
  [15401170]={130,6},[15401171]={19,3},[15401172]={127,6},[15401173]={127,2},[15401174]={127,0},
  [15401175]={127,5},[15401176]={126,7},[15401177]={127,3},[15401178]={126,6},[15401179]={127,1},
  [15401180]={127,4},[15401181]={60,6},[15401182]={128,1},[15401183]={128,2},[15401184]={128,3},
  [15401185]={128,4},[15401186]={128,0},[15401187]={129,1},[15401188]={128,7},[15401189]={129,0},
  [15401190]={128,6},[15401191]={128,5},[15401192]={19,4},[15401193]={129,2},[15401194]={129,4},
  [15401195]={129,5},[15401196]={129,6},[15401197]={134,1},[15401198]={132,4},[15401199]={134,4},
  [15401200]={129,7},[15401201]={117,1},[15401202]={117,0},[15401203]={117,2},[15401204]={117,4},
  [15401205]={117,3},[15401206]={117,5},[15401207]={117,6},[15401208]={118,0},[15401209]={117,7},
  [15401210]={129,3},
}
local LOC_SHOP = {
  [15405056]={0,0},[15405057]={0,1},[15405058]={0,2},[15405059]={0,3},[15405060]={0,4},[15405063]={1,0},
  [15405070]={2,0},[15405077]={3,0},[15405078]={3,1},[15405079]={3,2},[15405080]={3,3},[15405084]={4,0},
  [15405085]={4,1},[15405086]={4,2},[15405087]={4,3},[15405091]={5,0},[15405092]={5,1},[15405093]={5,2},
  [15405094]={5,3},[15405098]={6,0},[15405099]={6,1},[15405100]={6,2},[15405101]={6,3},[15405105]={7,0},
  [15405106]={7,1},[15405107]={7,2},[15405108]={7,3},[15405109]={7,4},[15405110]={7,5},[15405112]={8,0},
  [15405113]={8,1},[15405119]={9,0},[15405126]={10,0},[15405127]={10,1},[15405128]={10,2},[15405129]={10,3},
  [15405130]={10,4},[15405131]={10,5},[15405147]={13,0},[15405148]={13,1},[15405149]={13,2},[15405150]={13,3},
  [15405151]={13,4},[15405152]={13,5},[15405154]={14,0},[15405161]={15,0},[15405162]={15,1},[15405163]={15,2},
  [15405164]={15,3},[15405165]={15,4},[15405168]={16,0},[15405169]={16,1},[15405170]={16,2},[15405171]={16,3},
  [15405172]={16,4},[15405175]={17,0},[15405176]={17,1},[15405177]={17,2},[15405178]={17,3},[15405179]={17,4},
  [15405182]={18,0},[15405183]={18,1},[15405184]={18,2},[15405185]={18,3},[15405189]={19,0},[15405190]={19,1},
  [15405191]={19,2},[15405192]={19,3},[15405193]={19,4},[15405194]={19,5},[15405195]={19,6},[15405196]={20,0},
  [15405203]={21,0},[15405204]={21,1},[15405205]={21,2},[15405206]={21,3},[15405207]={21,4},[15405208]={21,5},
  [15405209]={21,6},[15405210]={22,0},[15405211]={22,1},[15405212]={22,2},[15405213]={22,3},[15405214]={22,4},
  [15405217]={23,0},[15405218]={23,1},[15405219]={23,2},[15405220]={23,3},[15405221]={23,4},[15405224]={24,0},
  [15405225]={24,1},[15405226]={24,2},[15405227]={24,3},[15405231]={25,0},[15405232]={25,1},[15405233]={25,2},
  [15405234]={25,3},[15405235]={25,4},[15405236]={25,5},[15405238]={26,0},[15405239]={26,1},[15405240]={26,2},
  [15405241]={26,3},[15405242]={26,4},[15405243]={26,5},[15405244]={26,6},[15405245]={27,0},[15405246]={27,1},
  [15405247]={27,2},[15405248]={27,3},[15405252]={28,0},[15405253]={28,1},[15405254]={28,2},[15405255]={28,3},
  [15405256]={28,4},[15405259]={29,0},[15405260]={29,1},[15405261]={29,2},[15405262]={29,3},[15405263]={29,4},
  [15405264]={29,5},[15405265]={29,6},[15405266]={30,0},[15405267]={30,1},[15405268]={30,2},[15405269]={30,3},
  [15405270]={30,4},[15405271]={30,5},[15405273]={31,0},[15405274]={31,1},[15405275]={31,2},[15405276]={31,3},
  [15405280]={32,0},[15405281]={32,1},[15405282]={32,2},[15405283]={32,3},[15405284]={32,4},[15405287]={33,0},
  [15405288]={33,1},[15405289]={33,2},[15405290]={33,3},[15405291]={33,4},[15405294]={34,0},[15405295]={34,1},
  [15405296]={34,2},[15405297]={34,3},[15405301]={35,0},[15405302]={35,1},[15405315]={37,0},[15405316]={37,1},
  [15405317]={37,2},[15405318]={37,3},[15405319]={37,4},[15405320]={37,5},[15405321]={37,6},[15405322]={38,0},
  [15405323]={38,1},[15405324]={38,2},[15405325]={38,3},[15405326]={38,4},[15405327]={38,5},[15405328]={38,6},
  [15405329]={39,0},[15405330]={39,1},[15405331]={39,2},[15405332]={39,3},[15405333]={39,4},[15405334]={39,5},
  [15405336]={40,0},[15405337]={40,1},[15405338]={40,2},[15405339]={40,3},[15405340]={40,4},[15405341]={40,5},
  [15405350]={42,0},[15405351]={42,1},[15405352]={42,2},[15405357]={43,0},[15405358]={43,1},[15405359]={43,2},
  [15405360]={43,3},[15405361]={43,4},[15405362]={43,5},[15405364]={44,0},[15405365]={44,1},[15405366]={44,2},
  [15405367]={44,3},[15405371]={45,0},[15405372]={45,1},[15405373]={45,2},[15405374]={45,3},[15405375]={45,4},
  [15405376]={45,5},[15405377]={45,6},[15405399]={49,0},[15405400]={49,1},[15405401]={49,2},[15405402]={49,3},
  [15405406]={50,0},[15405407]={50,1},[15405408]={50,2},[15405409]={50,3},[15405410]={50,4},[15405411]={50,5},
  [15405412]={50,6},[15405413]={51,0},[15405414]={51,1},[15405415]={51,2},[15405416]={51,3},[15405420]={52,0},
  [15405421]={52,1},[15405422]={52,2},[15405423]={52,3},[15405424]={52,4},[15405425]={52,5},[15405426]={52,6},
  [15405434]={54,0},[15405435]={54,1},[15405436]={54,2},[15405437]={54,3},[15405438]={54,4},[15405439]={54,5},
  [15405440]={54,6},[15405441]={55,0},[15405442]={55,1},[15405443]={55,2},[15405448]={56,0},[15405449]={56,1},
  [15405450]={56,2},[15405451]={56,3},[15405452]={56,4},[15405453]={56,5},[15405454]={56,6},[15405455]={57,0},
  [15405456]={57,1},[15405457]={57,2},[15405458]={57,3},[15405459]={57,4},[15405460]={57,5},[15405461]={57,6},
  [15405462]={58,0},[15405463]={58,1},[15405464]={58,2},[15405465]={58,3},[15405466]={58,4},[15405467]={58,5},
  [15405468]={58,6},[15405469]={59,0},[15405470]={59,1},[15405471]={59,2},[15405472]={59,3},[15405473]={59,4},
  [15405476]={60,0},[15405477]={60,1},[15405478]={60,2},[15405479]={60,3},[15405483]={61,0},[15405484]={61,1},
  [15405485]={61,2},[15405486]={61,3},[15405487]={61,4},[15405488]={61,5},[15405489]={61,6},[15405490]={62,0},
  [15405491]={62,1},[15405492]={62,2},[15405493]={62,3},[15405494]={62,4},[15405495]={62,5},[15405496]={62,6},
  [15405504]={64,0},[15405505]={64,1},[15405506]={64,2},[15405507]={64,3},[15405508]={64,4},
}

-- ── Internal state ────────────────────────────────────────────────────────────
local reported         = {}     -- ap_id -> true once returned from poll()
local server_locations = nil    -- set of ap_ids the server expects (nil = all)
local items_received   = {}     -- ordered stream (extended ITEM lines)
local slot_number      = 0
local remote_items     = false  -- slot enabled full remote (0b111)
local rom_ok           = nil    -- cached "MOM2AP" signature result
local mem              = {}
local log_fn           = nil

-- main/shop flag bytes, refreshed once per poll
local main_flags = {}
local shop_flags = {}

-- ── Logging ───────────────────────────────────────────────────────────────────
local function log(msg)
  if log_fn then pcall(log_fn, "[earthbound] " .. tostring(msg)) end
end

-- ── Memory API (resolved at init; 2-arg domain form + current-domain fallback) ─
local function resolve_memory_api()
  if not memory then return false end
  mem.read_u8   = memory.read_u8     or memory.readbyte
  mem.read_u16  = memory.read_u16_le or memory.readword
  mem.write_u8  = memory.write_u8    or memory.writebyte
  mem.write_u16 = memory.write_u16_le or memory.writeword
  return mem.read_u8 ~= nil
end

local function rd(fn, addr, domain)
  if not fn then return nil end
  local ok, v = pcall(fn, addr, domain)
  if ok and type(v) == "number" then return v end
  ok, v = pcall(fn, addr)                       -- older API: current domain
  if ok and type(v) == "number" then return v end
  return nil
end

local function read_u8(addr, domain)  return rd(mem.read_u8,  addr, domain or WRAM) end
local function read_u16(addr, domain) return rd(mem.read_u16, addr, domain or WRAM) end

local function write_u8(addr, value, domain)
  if not mem.write_u8 then return end
  if pcall(mem.write_u8, addr, value, domain or WRAM) then return end
  pcall(mem.write_u8, addr, value)
end

local function write_u16(addr, value, domain)
  if not mem.write_u16 then return end
  if pcall(mem.write_u16, addr, value, domain or WRAM) then return end
  pcall(mem.write_u16, addr, value)
end

-- Read one byte trying a list of {domain, addr} pairs in order (for the ROM sig).
local function read_first(pairs_list)
  for _, p in ipairs(pairs_list) do
    local ok, v = pcall(mem.read_u8, p[2], p[1])
    if ok and type(v) == "number" then return v, p end
  end
  return nil
end

local function bit_and(a, b)
  -- 16-bit safe AND without the bit library (cores vary).
  local res, bitval = 0, 1
  while a > 0 and b > 0 do
    if a % 2 == 1 and b % 2 == 1 then res = res + bitval end
    a = math.floor(a / 2); b = math.floor(b / 2); bitval = bitval * 2
  end
  return res
end

local POW2 = { [0]=1, 2, 4, 8, 16, 32, 64, 128 }

-- ── ROM identity: the AP basepatch writes "MOM2AP" at the SNES header $00:FFC0 ─
-- Tries "System Bus" 0x00FFC0 (the client's literal address) first, then CARTROM
-- HiROM/LoROM header offsets. Whichever domain yields "MOM2AP" is cached.
local function rom_is_ap()
  if rom_ok ~= nil then return rom_ok end
  -- Pick the domain/base that returns the first signature byte, then verify all 6.
  local first, picked = read_first({
    { "System Bus", SIG_BUS_ADDR },
    { "CARTROM",    SIG_CARTROM_HI },
    { "CARTROM",    SIG_CARTROM_LO },
    { "ROM",        SIG_CARTROM_HI },
  })
  if first == nil then return false end           -- ROM not readable yet; retry
  if first ~= string.byte(AP_SIG, 1) then
    rom_ok = false
    log("non-AP ROM (no 'MOM2AP' signature) — detection idle, no writes")
    return false
  end
  for i = 2, #AP_SIG do
    local ok, b = pcall(mem.read_u8, picked[2] + i - 1, picked[1])
    if not ok or type(b) ~= "number" then return false end
    if b ~= string.byte(AP_SIG, i) then
      rom_ok = false
      log("non-AP ROM (no 'MOM2AP' signature) — detection idle, no writes")
      return false
    end
  end
  rom_ok = true
  log(("AP ROM verified ('MOM2AP' present via %s 0x%X)"):format(picked[1], picked[2]))
  return true
end

-- ── Multiworld context ────────────────────────────────────────────────────────
local function load_locations(ids)
  if type(ids) ~= "table" then return end
  server_locations = {}
  local n = 0
  for _, id in ipairs(ids) do
    local v = tonumber(id)
    if v then server_locations[v] = true; n = n + 1 end
  end
  log("server location set: " .. n .. " ids")
end

local function wanted(ap_id)
  if server_locations == nil then return true end   -- no set provided → report all
  return server_locations[ap_id] == true
end

-- Item-stream filter, same policy as the ALttP module: in the default 0b001 mode
-- the patched game grants its own found items, so own-world items are dropped
-- unless the slot is in full remote mode; server/starting entries are dropped.
local function accept_item(it)
  if it.player == nil then return true end          -- legacy ITEM:<id> line
  if it.player == 0 and (it.location or 0) <= 0 then return false end
  if (not remote_items) and it.player == slot_number then return false end
  return true
end

local function delivery_list()
  local out = {}
  for _, it in ipairs(items_received) do
    if accept_item(it) then out[#out + 1] = it end
  end
  return out
end

-- ── Detection gates (Client.py game_watcher) ──────────────────────────────────
-- title screen: SAVE_FILE == 0; epilogue: GIYGAS_CLEAR bit 0 set.
local function in_gameplay()
  local save = read_u8(SAVE_FILE_OFF)
  if save == nil or save == 0 then return false end
  local epi = read_u8(GIYGAS_CLEAR_OFF)
  if epi ~= nil and bit_and(epi, 0x01) ~= 0 then return false end
  return true
end

-- textbox gate: the client only commits checks when OPEN_WINDOW == 0xFF.
local function textbox_clear()
  local w = read_u8(OPEN_WINDOW_OFF)
  return w ~= nil and w == 0xFF
end

local function refresh_flags()
  for i = 0, 0x87 do main_flags[i] = read_u8(LOC_MAIN_BASE + i) end
  for i = 0, 0x40 do shop_flags[i] = read_u8(LOC_SHOP_BASE + i) end
end

local function flag_set(region, off, bit)
  local b = region[off]
  if b == nil then return false end
  return bit_and(b, POW2[bit]) ~= 0
end

local function scan_into(new)
  for ap_id, e in pairs(LOC_MAIN) do
    if not reported[ap_id] and wanted(ap_id) and flag_set(main_flags, e[1], e[2]) then
      reported[ap_id] = true; new[#new + 1] = ap_id
    end
  end
  for ap_id, e in pairs(LOC_SHOP) do
    if not reported[ap_id] and wanted(ap_id) and flag_set(shop_flags, e[1], e[2]) then
      reported[ap_id] = true; new[#new + 1] = ap_id
    end
  end
end

-- ── Module contract ───────────────────────────────────────────────────────────

function M.init(ctx)
  if ctx and type(ctx.log) == "function" then log_fn = ctx.log end
  if not resolve_memory_api() then
    log("BizHawk memory API unavailable — module idle")
    ADDRESSES_VERIFIED = false
    return
  end
  local cfg = (ctx and ctx.config) or {}
  slot_number = tonumber(cfg.slot_number) or 0
  local sd = cfg.slot_data
  if type(sd) == "table" then
    remote_items = (sd.remote_items == true) or (tonumber(sd.remote_items) == 1)
  end
  load_locations(cfg.locations)
  local n = 0
  for _ in pairs(LOC_MAIN) do n = n + 1 end
  for _ in pairs(LOC_SHOP) do n = n + 1 end
  log(("ready (v%s): slot #%d, remote_items=%s, %d location flags")
      :format(WORLD_VERSION, slot_number, tostring(remote_items), n))
end

function M.poll()
  local new = {}
  if not ADDRESSES_VERIFIED then return new end
  if not rom_is_ap() then return new end
  if not in_gameplay() then return new end
  if not textbox_clear() then return new end       -- client skips checks mid-textbox
  refresh_flags()
  scan_into(new)
  return new
end

function M.is_goal_complete()
  if not ADDRESSES_VERIFIED or not rom_is_ap() then return false end
  local gc = read_u8(GAME_CLEAR_OFF)
  return gc ~= nil and bit_and(gc, 0x01) ~= 0
end

-- Queue-driven delivery, mirroring Client.py's receive loop. ITEMQUEUE_HIGH is the
-- count already handed to the game; when it trails the delivered stream and the
-- game is idle (no item in flight, not in a cutscene), push the next item to the
-- correct receive slot and bump the counter — the patched game consumes it.
function M.receive_item(item_id, meta)
  if type(meta) == "table" then
    items_received[#items_received + 1] = {
      item     = tonumber(item_id),
      index    = tonumber(meta.index),
      player   = tonumber(meta.player),
      flags    = tonumber(meta.flags),
      location = tonumber(meta.location or meta.locId),
    }
  else
    items_received[#items_received + 1] = { item = tonumber(item_id) }
  end

  if not ADDRESSES_VERIFIED or not rom_is_ap() or not in_gameplay() then return end

  -- Game-busy gates (Client.py): don't push while an item is mid-process or a
  -- cutscene is running.
  local pend_item    = read_u8(ITEM_RECEIVED)
  local pend_special = read_u8(SPECIAL_RECEIVED)
  local pend_money   = read_u8(MONEY_RECIVED)
  if (pend_item and pend_item ~= 0) or (pend_special and pend_special ~= 0)
     or (pend_money and pend_money ~= 0) then return end
  local cutscene = read_u8(CUR_SCENE_OFF)
  if cutscene and cutscene ~= 0 then return end

  local list = delivery_list()
  local count = read_u16(ITEMQUEUE_HIGH)
  if count == nil then return end
  if count >= #list then return end

  local nxt = list[count + 1]
  if not (nxt and nxt.item) then return end
  local gid = nxt.item - ITEM_ID_BASE             -- game-local id (item-0xEB0000)

  -- advance the counter first (matches the client: it writes recv_index+1 before
  -- the item byte so a mid-frame re-entry doesn't double-deliver).
  write_u16(ITEMQUEUE_HIGH, count + 1)

  if gid <= 0xFD then
    write_u8(ITEM_RECEIVED, bit_and(gid, 0xFF))
  else
    local money_index = nil
    for i = 1, #MONEY_IDS do if MONEY_IDS[i] == gid then money_index = i end end
    if money_index ~= nil then
      write_u8(MONEY_RECIVED, money_index)          -- 1-based, == list index + 1
    else
      local special = CLIENT_SPECIALS[gid]
      if special ~= nil then
        write_u8(SPECIAL_RECEIVED, special)
      else
        -- Unknown high id: counter already advanced (so we don't wedge the queue);
        -- nothing safe to write. Logged for diagnosis.
        log(("skipped unmapped item id 0x%X (no money/special mapping)"):format(gid))
      end
    end
  end
end

return M
