-- ═══════════════════════════════════════════════════════════════════════════════
-- ff4fe.lua — game module for the Archipelago BizHawk connector.
--             Final Fantasy IV: Free Enterprise (SNES)
--
-- STATUS: location DETECTION + goal are REAL and SOURCE-DERIVED from the official
-- AP world worlds/ff4fe (Client.py + locations.py + rom.py), the open PR adding the
-- game (ArchipelagoMW/Archipelago#3897, head Rosalie-A/Archipelago branch
-- Final-Fantasy-4-Free-Enterprise). The location tables (399 treasure + 75 reward +
-- 32 objective = 506 of the world's 508 locations) were GENERATED by PARSING the
-- source — re-running the exact locations.py `all_locations` construction over the
-- world's own data/treasure.csvdb + data/rewardslots.csvdb through its own csvdb.py,
-- then assigning AP ids the way FF4FEWorld does (base_id 7191991 + position in
-- all_locations) and splitting them by the in-game decode category FF4FEClient uses
-- — not hand-copied, so they are exact (mock-verified through MoonSharp against
-- synthetic SNES memory). Loads crash-free on any ROM; self-disables on a
-- non-AP/non-FF4FE cartridge.
--
-- MEMORY MODEL (SNI → BizHawk)  — same translation the A Link to the Past and Super
-- Metroid modules document (FF4FE's client is an SNIClient too):
-- ────────────────────────────
--   SNI WRAM_START(0xF50000)+off → domain "WRAM",    offset off (= $7E0000+off)
--   SNI SRAM_START(0xE00000)+off → domain "CARTRAM", offset off (fallback "SRAM")
--   The ROM-name the client validates is read at SNI 0x007FC0 (the LoROM internal
--   header) — in BizHawk the cartridge ROM ("CARTROM"/"ROM") at file offset 0x7FC0,
--   probed multi-domain with fallbacks like the EarthBound module's "MOM2AP" probe.
--   The AP build writes a custom header beginning "4FE" there (rom.py
--   FF4FEPatchExtension.call_fe + __init__ generate_output: rom_name = "4FE<ver>_…"),
--   exactly what Client.validate_rom checks (rom_name[:3] == b"4FE").
--
-- WHAT THIS DOES (mirrors worlds/ff4fe/Client.py game_watcher)
--   • poll(): the client's three flag scans → AP location ids, gated to the slot's
--     server location set and to the SAFE-STATE sentinel gate (Client.connection_check
--     reads six "are we in a cutscene/battle/menu" sentinel bytes; ALL must be 0 or it
--     does nothing — we mirror that so the menu's zeroed flag arrays never report
--     phantom checks).
--       - Treasure: byte=bit//8, bit%8 in the 64-byte array at WRAM 0x12A0,
--         LSB-first (treasure_data[byte] & (2**bit)); in-game bit index == fe_id.
--       - Reward:   same decode in the 16-byte array at WRAM 0x1510; in-game bit i
--         maps to fe_id i+0x200. (The client force-flags reward bit 1 — FE never
--         flags your starting character — so we do too.)
--       - Objectives: the 32-byte progress array at WRAM 0x1520; objective i is done
--         when objective_progress[i] > 0. Reported only while the objective COUNT
--         (SNI cart 0x10F0FC) is readable and > 0; otherwise objectives are simply
--         not scanned (graceful — never a false report).
--   • is_goal_complete(): victory byte at SRAM 0x070F2 > 0, behind the same six
--     sentinels read < 0x02 (Client.check_victory exactly — the >= 0x02 guard defends
--     against RAM initialised to static values everywhere).
--   • receive_item(): NO-OP for now (documented). items_handling = 0b111 — the AP
--     SERVER drives item delivery, but FF4FE's apply path is NOT a simple buffered
--     write: the reference client parses the live inventory, junk-tier/sell settings
--     and the seed's flag string, auto-sells junked items into the GP counter, sets
--     five special key-item flag bits, and threads items into free inventory slots
--     gated on the game's own received-item counter (SRAM 0x02FFE). That multi-read
--     decision logic is the documented deferred piece — a wrong WRAM/SRAM write would
--     corrupt the save — so it is intentionally left out rather than shipped
--     unverified, exactly like the other SNES modules in this wave. Checks + goal
--     flow regardless.
--
-- MODULE CONTRACT (called by bizhawk_ap_connector.lua)
--   M.init(ctx) / M.poll() -> {ids} / M.is_goal_complete() -> bool /
--   M.receive_item(item_id, meta)
-- ═══════════════════════════════════════════════════════════════════════════════

local M = {}
M.name = "ff4fe"

local ADDRESSES_VERIFIED = true   -- tables generated from worlds/ff4fe source

-- ── Memory domains ────────────────────────────────────────────────────────────
local WRAM    = "WRAM"
local CARTRAM = "CARTRAM"     -- SNES battery SRAM in BizHawk; fallback "SRAM"

-- ── SNI-space constants (rom.py), as BizHawk-domain offsets ────────────────────
-- WRAM offsets are net of WRAM_START (0xF50000); CARTRAM offsets net of 0xE00000.
local TREASURE_OFF     = 0x12A0       -- WRAM: treasure_found array (64 bytes → 512 bits)
local TREASURE_BYTES   = 64
local REWARD_OFF       = 0x1510       -- WRAM: checked_reward array (16 bytes → 128 bits)
local REWARD_BYTES     = 16
local OBJPROG_OFF      = 0x1520       -- WRAM: objective_progress array (32 bytes)
local OBJPROG_BYTES    = 32
local VICTORY_OFF      = 0x070F2      -- CARTRAM: victory byte ($E070F2)

-- Objective count / needed live in SNI cartridge space (bank 0x10). In BizHawk a
-- LoROM file offset; probed in the ROM domains. Only used to bound objective scan.
local OBJ_COUNT_CARTADDR  = 0x10F0FC  -- SNI; LoROM file offset 0x087EFC ((bank<<15)|(addr&0x7FFF))
local OBJ_NEEDED_CARTADDR = 0x10F0F9

-- ROM identity: the AP build writes a header starting "4FE" at the LoROM header
-- (SNI 0x007FC0 → CARTROM file offset 0x7FC0). Client.validate_rom: name[:3]=="4FE".
local ROM_SIG          = "4FE"
local SIG_CARTROM_LO   = 0x7FC0       -- LoROM file header offset (CARTROM/ROM)
local SIG_BUS_ADDR     = 0x00FFC0     -- System Bus form of the same header
local SIG_CARTROM_HI   = 0xFFC0       -- HiROM offset (last-ditch fallback)

-- Safe-state sentinels (rom.py sentinel_addresses): six "in a cutscene/battle/menu"
-- bytes. connection_check requires ALL == 0; check_victory requires ALL < 0x02.
-- Five are WRAM, one is CARTRAM. Stored as {domain, offset}.
local SENTINELS = {
  { WRAM,    0x06B1 },   -- 0xF506B1
  { WRAM,    0x06D9 },   -- 0xF506D9
  { WRAM,    0x0650 },   -- 0xF50650
  { WRAM,    0x0140 },   -- 0xF50140
  { WRAM,    0x0685 },   -- 0xF50685
  { CARTRAM, 0x070FD },  -- 0xE070FD
}

-- ── Location tables (GENERATED from worlds/ff4fe source; see file header) ──────
-- TREASURE: 399 entries. ap_id -> in-game treasure bit index (0..511). Checked when
-- treasure_data[bit//8] & (1 << (bit%8)) != 0 (LSB-first), where the bit index IS the
-- location's fe_id.
local LOC_TREASURE = {
  [7191991]=0,[7191992]=1,[7191993]=2,[7191994]=3,[7191995]=4,[7191996]=5,[7191997]=6,[7191998]=7,
  [7191999]=8,[7192000]=9,[7192001]=10,[7192002]=11,[7192003]=12,[7192004]=13,[7192005]=14,[7192006]=15,
  [7192007]=16,[7192008]=17,[7192009]=18,[7192010]=19,[7192011]=20,[7192012]=21,[7192013]=22,[7192014]=23,
  [7192015]=24,[7192016]=25,[7192017]=26,[7192018]=27,[7192019]=28,[7192020]=29,[7192021]=30,[7192022]=31,
  [7192023]=32,[7192024]=33,[7192025]=34,[7192026]=35,[7192027]=36,[7192028]=37,[7192029]=38,[7192030]=39,
  [7192031]=40,[7192032]=41,[7192033]=42,[7192034]=43,[7192035]=44,[7192036]=45,[7192037]=46,[7192038]=47,
  [7192039]=48,[7192040]=50,[7192041]=51,[7192042]=52,[7192043]=53,[7192044]=54,[7192045]=55,[7192046]=56,
  [7192047]=57,[7192048]=58,[7192049]=59,[7192050]=60,[7192051]=61,[7192052]=62,[7192053]=63,[7192054]=64,
  [7192055]=65,[7192056]=66,[7192057]=67,[7192058]=68,[7192059]=69,[7192060]=70,[7192061]=71,[7192062]=72,
  [7192063]=73,[7192064]=74,[7192065]=75,[7192066]=76,[7192067]=77,[7192068]=78,[7192069]=79,[7192070]=80,
  [7192071]=81,[7192072]=82,[7192073]=83,[7192074]=84,[7192075]=85,[7192076]=86,[7192077]=87,[7192078]=88,
  [7192079]=89,[7192080]=90,[7192081]=91,[7192082]=92,[7192083]=93,[7192084]=94,[7192085]=95,[7192086]=96,
  [7192087]=97,[7192088]=98,[7192089]=99,[7192090]=100,[7192091]=101,[7192092]=102,[7192093]=103,[7192094]=104,
  [7192095]=105,[7192096]=106,[7192097]=107,[7192098]=108,[7192099]=109,[7192100]=110,[7192101]=111,[7192102]=112,
  [7192103]=113,[7192104]=114,[7192105]=115,[7192106]=116,[7192107]=117,[7192108]=118,[7192109]=119,[7192110]=120,
  [7192111]=121,[7192112]=122,[7192113]=123,[7192114]=124,[7192115]=125,[7192116]=126,[7192117]=127,[7192118]=128,
  [7192119]=129,[7192120]=130,[7192121]=131,[7192122]=132,[7192123]=133,[7192124]=134,[7192125]=135,[7192126]=136,
  [7192127]=137,[7192128]=138,[7192129]=139,[7192130]=140,[7192131]=141,[7192132]=142,[7192133]=143,[7192134]=144,
  [7192135]=145,[7192136]=146,[7192137]=147,[7192138]=148,[7192139]=149,[7192140]=150,[7192141]=151,[7192142]=152,
  [7192143]=153,[7192144]=154,[7192145]=155,[7192146]=156,[7192147]=157,[7192148]=158,[7192149]=159,[7192150]=160,
  [7192151]=161,[7192152]=162,[7192153]=163,[7192154]=164,[7192155]=165,[7192156]=166,[7192157]=167,[7192158]=168,
  [7192159]=169,[7192160]=170,[7192161]=171,[7192162]=172,[7192163]=173,[7192164]=174,[7192165]=175,[7192166]=176,
  [7192167]=177,[7192168]=178,[7192169]=179,[7192170]=180,[7192171]=181,[7192172]=182,[7192173]=183,[7192174]=184,
  [7192175]=185,[7192176]=186,[7192177]=187,[7192178]=188,[7192179]=189,[7192180]=190,[7192181]=191,[7192182]=192,
  [7192183]=193,[7192184]=194,[7192185]=195,[7192186]=196,[7192187]=197,[7192188]=198,[7192189]=199,[7192190]=200,
  [7192191]=201,[7192192]=202,[7192193]=203,[7192194]=204,[7192195]=205,[7192196]=206,[7192197]=207,[7192198]=208,
  [7192199]=209,[7192200]=210,[7192201]=211,[7192202]=212,[7192203]=213,[7192204]=214,[7192205]=215,[7192206]=216,
  [7192207]=217,[7192208]=218,[7192209]=219,[7192210]=220,[7192211]=221,[7192212]=222,[7192213]=223,[7192214]=224,
  [7192215]=225,[7192216]=226,[7192217]=227,[7192218]=228,[7192219]=229,[7192220]=230,[7192221]=231,[7192222]=232,
  [7192223]=233,[7192224]=234,[7192225]=235,[7192226]=236,[7192227]=237,[7192228]=238,[7192229]=239,[7192230]=240,
  [7192231]=241,[7192232]=256,[7192233]=257,[7192234]=258,[7192235]=259,[7192236]=260,[7192237]=261,[7192238]=262,
  [7192239]=263,[7192240]=264,[7192241]=265,[7192242]=266,[7192243]=267,[7192244]=268,[7192245]=269,[7192246]=270,
  [7192247]=271,[7192248]=272,[7192249]=273,[7192250]=274,[7192251]=275,[7192252]=276,[7192253]=277,[7192254]=278,
  [7192255]=279,[7192256]=280,[7192257]=281,[7192258]=282,[7192259]=283,[7192260]=284,[7192261]=285,[7192262]=286,
  [7192263]=287,[7192264]=288,[7192265]=289,[7192266]=290,[7192267]=291,[7192268]=292,[7192269]=293,[7192270]=294,
  [7192271]=295,[7192272]=296,[7192273]=297,[7192274]=298,[7192275]=299,[7192276]=300,[7192277]=302,[7192278]=304,
  [7192279]=305,[7192280]=306,[7192281]=307,[7192282]=308,[7192283]=309,[7192284]=310,[7192285]=311,[7192286]=312,
  [7192287]=313,[7192288]=314,[7192289]=315,[7192290]=316,[7192291]=317,[7192292]=318,[7192293]=319,[7192294]=320,
  [7192295]=321,[7192296]=322,[7192297]=323,[7192298]=324,[7192299]=325,[7192300]=326,[7192301]=327,[7192302]=328,
  [7192303]=329,[7192304]=330,[7192305]=331,[7192306]=332,[7192307]=333,[7192308]=334,[7192309]=335,[7192310]=336,
  [7192311]=337,[7192312]=338,[7192313]=339,[7192314]=340,[7192315]=341,[7192316]=342,[7192317]=343,[7192318]=344,
  [7192319]=345,[7192320]=346,[7192321]=347,[7192322]=348,[7192323]=349,[7192324]=350,[7192325]=351,[7192326]=352,
  [7192327]=353,[7192328]=354,[7192329]=355,[7192330]=356,[7192331]=357,[7192332]=358,[7192333]=359,[7192334]=360,
  [7192335]=361,[7192336]=362,[7192337]=363,[7192338]=364,[7192339]=365,[7192340]=366,[7192341]=367,[7192342]=368,
  [7192343]=369,[7192344]=370,[7192345]=371,[7192346]=372,[7192347]=373,[7192348]=374,[7192349]=375,[7192350]=376,
  [7192351]=377,[7192352]=378,[7192353]=379,[7192354]=380,[7192355]=381,[7192356]=382,[7192357]=383,[7192358]=384,
  [7192359]=385,[7192360]=386,[7192361]=387,[7192362]=388,[7192363]=389,[7192364]=390,[7192365]=391,[7192366]=392,
  [7192367]=393,[7192368]=394,[7192369]=395,[7192370]=396,[7192371]=397,[7192372]=398,[7192373]=399,[7192374]=400,
  [7192375]=401,[7192376]=402,[7192377]=404,[7192378]=405,[7192379]=406,[7192380]=407,[7192381]=408,[7192382]=409,
  [7192383]=410,[7192384]=411,[7192385]=412,[7192386]=413,[7192387]=414,[7192388]=415,[7192389]=416,
}

-- REWARD: 75 entries. ap_id -> in-game reward bit index (0..127). Checked when
-- reward_data[bit//8] & (1 << (bit%8)) != 0; in-game bit i maps to fe_id i+0x200.
-- (The client always treats reward bit 1 as set — FE never flags the starting
-- character — so REWARD_FORCE_BIT below is reported unconditionally in gameplay.)
local LOC_REWARD = {
  [7192390]=32,[7192391]=33,[7192392]=34,[7192393]=35,[7192394]=36,[7192395]=37,[7192396]=38,[7192397]=39,
  [7192398]=40,[7192399]=41,[7192400]=42,[7192401]=43,[7192402]=44,[7192403]=91,[7192404]=47,[7192405]=48,
  [7192406]=46,[7192407]=92,[7192408]=89,[7192409]=52,[7192410]=49,[7192411]=50,[7192412]=51,[7192413]=53,
  [7192414]=54,[7192415]=55,[7192416]=56,[7192417]=59,[7192418]=60,[7192419]=61,[7192420]=62,[7192421]=63,
  [7192422]=64,[7192423]=65,[7192424]=66,[7192425]=67,[7192426]=68,[7192427]=69,[7192428]=70,[7192429]=71,
  [7192430]=72,[7192431]=73,[7192432]=74,[7192433]=75,[7192434]=76,[7192435]=77,[7192436]=78,[7192437]=79,
  [7192438]=80,[7192439]=81,[7192440]=82,[7192441]=83,[7192442]=84,[7192443]=85,[7192444]=86,[7192445]=87,
  [7192446]=88,[7192447]=1,[7192448]=2,[7192449]=3,[7192450]=4,[7192451]=5,[7192452]=6,[7192453]=7,
  [7192454]=8,[7192455]=9,[7192456]=10,[7192457]=13,[7192458]=14,[7192459]=15,[7192460]=16,[7192461]=17,
  [7192462]=18,[7192463]=19,[7192464]=20,
}
-- Client force-flags reward bit 1 (the starting character FE never marks obtained).
local REWARD_FORCE_BIT = 1

-- OBJECTIVE: 32 entries. ap_id -> objective index (0..31). "Objective N Status" is
-- checked when objective_progress[index] > 0. Reported only while the objective
-- count is known and > 0 (a vanilla/objective-less seed scans none of these).
local LOC_OBJECTIVE = {
  [7192467]=0,[7192468]=1,[7192469]=2,[7192470]=3,[7192471]=4,[7192472]=5,[7192473]=6,[7192474]=7,
  [7192475]=8,[7192476]=9,[7192477]=10,[7192478]=11,[7192479]=12,[7192480]=13,[7192481]=14,[7192482]=15,
  [7192483]=16,[7192484]=17,[7192485]=18,[7192486]=19,[7192487]=20,[7192488]=21,[7192489]=22,[7192490]=23,
  [7192491]=24,[7192492]=25,[7192493]=26,[7192494]=27,[7192495]=28,[7192496]=29,[7192497]=30,[7192498]=31,
}

-- ── Internal state ────────────────────────────────────────────────────────────
local reported         = {}     -- ap_id -> true once returned from poll()
local server_locations = nil    -- set of ap_ids the server expects (nil = all)
local items_received   = {}     -- ordered stream (extended ITEM lines)
local slot_number      = 0
local rom_ok           = nil    -- cached "4FE" signature result
local sig_domain       = nil    -- {domain, addr} that yielded the signature
local mem              = {}
local log_fn           = nil

-- Per-poll snapshots, refreshed each frame.
local treasure   = {}    -- byte index 0..63
local reward     = {}    -- byte index 0..15
local objprog    = {}    -- byte index 0..31

-- ── Logging ───────────────────────────────────────────────────────────────────
local function log(msg)
  if log_fn then pcall(log_fn, "[ff4fe] " .. tostring(msg)) end
end

-- ── Memory API (resolved at init; 2-arg domain form + current-domain fallback) ─
local function resolve_memory_api()
  if not memory then return false end
  mem.read_u8 = memory.read_u8 or memory.readbyte
  return mem.read_u8 ~= nil
end

local function rd(addr, domain)
  if not mem.read_u8 then return nil end
  local ok, v = pcall(mem.read_u8, addr, domain)
  if ok and type(v) == "number" then return v end
  ok, v = pcall(mem.read_u8, addr)              -- older API: current domain
  if ok and type(v) == "number" then return v end
  return nil
end

local function read_u8(addr, domain) return rd(addr, domain or WRAM) end

-- Read from CARTRAM, falling back to the "SRAM" domain name on cores that use it.
local function read_cartram_u8(off)
  local ok, v = pcall(mem.read_u8, off, CARTRAM)
  if ok and type(v) == "number" then return v end
  ok, v = pcall(mem.read_u8, off, "SRAM")
  if ok and type(v) == "number" then return v end
  return nil
end

-- Read one byte trying a list of {domain, addr} pairs in order (for the ROM sig).
local function read_first(pairs_list)
  for _, p in ipairs(pairs_list) do
    local ok, v = pcall(mem.read_u8, p[2], p[1])
    if ok and type(v) == "number" then return v, p end
  end
  return nil
end

local function bit_and(a, b)
  -- 16-bit safe AND without the bit library (cores vary).
  local res, bitval = 0, 1
  while a > 0 and b > 0 do
    if a % 2 == 1 and b % 2 == 1 then res = res + bitval end
    a = math.floor(a / 2); b = math.floor(b / 2); bitval = bitval * 2
  end
  return res
end

-- LSB-first single-bit test inside a byte array (treasure_data[byte] & (2**bit)).
local POW2 = { [0]=1, 2, 4, 8, 16, 32, 64, 128 }
local function bit_set_lsb(byte_array, bit_index)
  local b = byte_array[math.floor(bit_index / 8)]
  if b == nil then return false end
  return bit_and(b, POW2[bit_index % 8]) ~= 0
end

-- Domain read for a {domain, off} sentinel pair.
local function read_sentinel(s)
  if s[1] == CARTRAM then return read_cartram_u8(s[2]) end
  return read_u8(s[2], s[1])
end

-- ── ROM identity: the FF4FE AP build's header begins "4FE" ─────────────────────
-- Tries CARTROM/ROM LoROM 0x7FC0, the System Bus header, then the HiROM offset.
-- Whichever domain yields "4FE" is cached and reused.
local function rom_is_ap()
  if rom_ok ~= nil then return rom_ok end
  local first, picked = read_first({
    { "CARTROM",    SIG_CARTROM_LO },
    { "ROM",        SIG_CARTROM_LO },
    { "System Bus", SIG_BUS_ADDR },
    { "CARTROM",    SIG_CARTROM_HI },
    { "ROM",        SIG_CARTROM_HI },
  })
  if first == nil then return false end           -- ROM not readable yet; retry
  if first ~= string.byte(ROM_SIG, 1) then
    rom_ok = false
    log("non-FF4FE/non-AP ROM (no '4FE' header) — detection idle, no writes")
    return false
  end
  for i = 2, #ROM_SIG do
    local ok, b = pcall(mem.read_u8, picked[2] + i - 1, picked[1])
    if not ok or type(b) ~= "number" then return false end
    if b ~= string.byte(ROM_SIG, i) then
      rom_ok = false
      log("non-FF4FE/non-AP ROM (no '4FE' header) — detection idle, no writes")
      return false
    end
  end
  rom_ok = true
  sig_domain = picked
  log(("FF4FE ROM verified ('4FE' header via %s 0x%X)"):format(picked[1], picked[2]))
  return true
end

-- ── Multiworld context ────────────────────────────────────────────────────────
local function load_locations(ids)
  if type(ids) ~= "table" then return end
  server_locations = {}
  local n = 0
  for _, id in ipairs(ids) do
    local v = tonumber(id)
    if v then server_locations[v] = true; n = n + 1 end
  end
  log("server location set: " .. n .. " ids")
end

local function wanted(ap_id)
  if server_locations == nil then return true end   -- no set provided → report all
  return server_locations[ap_id] == true
end

-- Item-stream filter, same policy as the ALttP/FFMQ modules. Even though FF4FE is
-- items_handling=0b111 (server-driven), the in-game write path is deferred, so this
-- only feeds a future delivery wiring; own-location items the game already granted
-- are dropped and server/starting entries dropped.
local function accept_item(it)
  if it.player == nil then return true end          -- legacy ITEM:<id> line
  if it.player == 0 and (it.location or 0) <= 0 then return false end
  return true
end

-- ── Snapshot + safe-state gate ────────────────────────────────────────────────
local function refresh_snapshot()
  for i = 0, TREASURE_BYTES - 1 do treasure[i] = read_u8(TREASURE_OFF + i, WRAM) end
  for i = 0, REWARD_BYTES   - 1 do reward[i]   = read_u8(REWARD_OFF   + i, WRAM) end
  for i = 0, OBJPROG_BYTES  - 1 do objprog[i]  = read_u8(OBJPROG_OFF  + i, WRAM) end
end

-- connection_check gate: every sentinel must read exactly 0 (in a safe gameplay
-- state, not a cutscene/battle/menu, and not RAM still initialised to junk).
local function in_safe_state()
  for _, s in ipairs(SENTINELS) do
    local v = read_sentinel(s)
    if v == nil or v ~= 0 then return false end
  end
  return true
end

-- Objective count from SNI cart space (bank 0x10). LoROM file offset for
-- 0x10F0FC = ((0x10 & 0x7F) << 15) | (0xF0FC & 0x7FFF) = 0x087EFC. Probed in the
-- ROM domains; nil when unreadable (objectives then simply aren't scanned).
local function lorom_file_offset(sni_addr)
  local bank = math.floor(sni_addr / 0x10000)
  local addr = sni_addr % 0x10000
  return ((bank % 0x80) * 0x8000) + (addr % 0x8000)
end

local function read_cart_rom_u8(sni_addr)
  local off = lorom_file_offset(sni_addr)
  local v, _ = read_first({
    { "CARTROM",    off },
    { "ROM",        off },
    { "System Bus", sni_addr % 0x1000000 },
  })
  return v
end

local function objective_count()
  return read_cart_rom_u8(OBJ_COUNT_CARTADDR)
end

local function scan_into(new)
  -- Treasure: LSB-first bit == fe_id in the 64-byte array.
  for ap_id, bit in pairs(LOC_TREASURE) do
    if not reported[ap_id] and wanted(ap_id) and bit_set_lsb(treasure, bit) then
      reported[ap_id] = true; new[#new + 1] = ap_id
    end
  end
  -- Reward: LSB-first bit in the 16-byte array (bit 1 force-flagged like the client).
  for ap_id, bit in pairs(LOC_REWARD) do
    if not reported[ap_id] and wanted(ap_id) then
      if bit == REWARD_FORCE_BIT or bit_set_lsb(reward, bit) then
        reported[ap_id] = true; new[#new + 1] = ap_id
      end
    end
  end
  -- Objectives: progress[index] > 0, but only when the seed actually has objectives.
  local oc = objective_count()
  if oc ~= nil and oc > 0 then
    for ap_id, idx in pairs(LOC_OBJECTIVE) do
      if not reported[ap_id] and wanted(ap_id) and idx < oc then
        local v = objprog[idx]
        if v ~= nil and v > 0 then reported[ap_id] = true; new[#new + 1] = ap_id end
      end
    end
  end
end

-- ── Module contract ───────────────────────────────────────────────────────────

function M.init(ctx)
  if ctx and type(ctx.log) == "function" then log_fn = ctx.log end
  if not resolve_memory_api() then
    log("BizHawk memory API unavailable — module idle")
    ADDRESSES_VERIFIED = false
    return
  end
  local cfg = (ctx and ctx.config) or {}
  slot_number = tonumber(cfg.slot_number) or 0
  load_locations(cfg.locations)
  local n = 0
  for _ in pairs(LOC_TREASURE)  do n = n + 1 end
  for _ in pairs(LOC_REWARD)    do n = n + 1 end
  for _ in pairs(LOC_OBJECTIVE) do n = n + 1 end
  log(("ready: slot #%d, %d location flags"):format(slot_number, n))
end

function M.poll()
  local new = {}
  if not ADDRESSES_VERIFIED then return new end
  if not rom_is_ap() then return new end
  if not in_safe_state() then return new end
  refresh_snapshot()
  scan_into(new)
  return new
end

function M.is_goal_complete()
  if not ADDRESSES_VERIFIED or not rom_is_ap() then return false end
  -- check_victory: every sentinel must read < 0x02, then victory byte > 0.
  for _, s in ipairs(SENTINELS) do
    local v = read_sentinel(s)
    if v == nil or v >= 0x02 then return false end
  end
  local victory = read_cartram_u8(VICTORY_OFF)
  return victory ~= nil and victory > 0
end

-- Remote items: see the file header. items_handling = 0b111 (the AP server drives
-- delivery), but FF4FE's apply path is intricate decision logic over the live
-- inventory / junk-tier / sell settings / seed flags, with guarded WRAM+SRAM writes
-- gated on the game's own received-item counter — the documented deferred piece. We
-- record the stream (so a future wiring has it) but make no write (never a wrong
-- WRAM/SRAM write) until it can be confirmed in-emulator. Checks + goal flow
-- regardless.
function M.receive_item(item_id, meta)
  if type(meta) == "table" then
    items_received[#items_received + 1] = {
      item     = tonumber(item_id),
      index    = tonumber(meta.index),
      player   = tonumber(meta.player),
      flags    = tonumber(meta.flags),
      location = tonumber(meta.locId),
    }
  else
    items_received[#items_received + 1] = { item = tonumber(item_id) }
  end
  -- intentionally no memory write (documented; deferred until in-emulator verified)
end

return M
