-- ═══════════════════════════════════════════════════════════════════════════════
-- ff6wc.lua — game module for the Archipelago BizHawk connector.
--            Final Fantasy 6 Worlds Collide (SNES)
--
-- STATUS: location DETECTION + goal are REAL and SOURCE-DERIVED from the official
-- AP world worlds/ff6wc (Client.py + Rom.py + Locations.py + __init__.py, branch
-- Final-Fantasy-6-Worlds-Collide-AP of Javinat0r/Archipelago — the canonical FF6WC
-- apworld, distributed via the AP Discord). The two location tables (58 event-flag
-- checks + 259 treasure chests) plus the special-cased Lone Wolf / Narshe Weapon
-- Shop pairs and the point-of-no-return links were GENERATED by PARSING the source
-- (Rom.event_flag_location_names + Rom.treasure_chest_data, each name's AP id =
-- base_id 6000 + its index in Locations.location_table); the event/treasure bit math,
-- the "6WC" ROM signature, the map/menu in-game gate and the victory byte are all
-- replicated exactly from Client.py, and mock-verified through MoonSharp against
-- synthetic SNES memory. The generated tables independently cross-check against the
-- community EmoTracker autotracking addresses (Whelk 0x1EA6/0x20, Tritoch 0x1ED3/
-- 0x40, Tzen Thief 0x1ECF/0x10 all match). Loads crash-free on any ROM; self-
-- disables on a non-6WC cartridge.
--
-- MEMORY MODEL (SNI → BizHawk)  — the same translation the A Link to the Past and
-- Final Fantasy Mystic Quest modules document (FF6WC's client is an SNIClient too):
-- ────────────────────────────
--   SNI WRAM_START(0xF50000)+off → domain "WRAM",    offset off (= $7E0000+off)
--   SNI SRAM_START(0xE00000)+off → domain "CARTRAM", offset off (fallback "SRAM")
--   FF6/FF3us is a HiROM cartridge: the "6WC…" ROM name the client validates lives
--   in the SNES internal header at $00:FFC0 (System Bus) / file offset 0xFFC0
--   (HiROM CARTROM) — read like the EarthBound module's "MOM2AP" probe, multi-domain
--   with HiROM-first fallbacks.
--
-- WHAT THIS DOES (mirrors worlds/ff6wc/Client.py game_watcher)
--   • poll(): the client's flag scan → AP location ids, gated to the slot's server
--     location set and to the in-game gate the client uses (connection_check):
--       - map_index = read16(0xF50082) & 0x01FF  must be ≥ 6 and ≠ 255
--       - menu byte at 0xF50059 must be 0
--     Then:
--       - Event-flag checks: event byte at WRAM 0x1E80 + (event_id//8), bit
--         1<<(event_id%8) (LSB-first); reported when set.   [location_check]
--       - Treasure chests: 40-byte block at WRAM 0x1E40; byte = (chest_addr-0x1E40),
--         bit = 1<<bit_index; reported when set.             [treasure_check]
--       - Lone Wolf 1/2 & Narshe Weapon Shop 1/2: the client's branch on
--         Encountered / First-Reward-Picked / Both-Rewards-Picked event bits.
--       - Point-of-no-return: clearing a gate boss (Wrexsoul, Nerapa, Imperial Camp,
--         Cranes, Phantom Train, Burning House, Collapsing House) back-fills the
--         now-unreachable chests behind it, exactly as Client.py does.
--   • is_goal_complete(): CARTRAM victory byte at 0xE07E04 ≠ 0 (Client.py
--     check_victory2 — the patched game sets it when Kefka is defeated).
--   • receive_item(): NO-OP for now (documented). items_handling = 0b111 — the AP
--     SERVER drives ALL item delivery; the reference client applies each received
--     item with intricate, type-specific guarded writes (characters: init+recruit
--     bits + obtained counter + SwdTech/Blitz unlock; espers: esper bit + counter;
--     items: scan the 255-slot field inventory for a free/!matching slot and bump
--     the quantity), bumping items_received at 0xF51DC9 after each. That whole
--     write path needs in-emulator verification before it is wired — a wrong WRAM
--     write would corrupt the save — so it is intentionally left out rather than
--     shipped unverified, exactly like the other SNES modules in this wave. Checks
--     + goal flow regardless.
--
-- MODULE CONTRACT (called by bizhawk_ap_connector.lua)
--   M.init(ctx) / M.poll() -> {ids} / M.is_goal_complete() -> bool /
--   M.receive_item(item_id, meta)
-- ═══════════════════════════════════════════════════════════════════════════════

local M = {}
M.name = "ff6wc"

local ADDRESSES_VERIFIED = true   -- tables generated from worlds/ff6wc source

-- ── Memory domains ────────────────────────────────────────────────────────────
local WRAM    = "WRAM"
local CARTRAM = "CARTRAM"     -- SNES battery SRAM in BizHawk; fallback "SRAM"

-- ── SNI-space constants (Client.py + Rom.py), as BizHawk-domain offsets ────────
-- WRAM offsets are net of WRAM_START (0xF50000); CARTRAM offsets net of 0xE00000.
local EVENT_BASE_OFF    = 0x1E80      -- WRAM: event-flag array base ($F51E80)
local TREASURE_BASE_OFF = 0x1E40      -- WRAM: 40-byte treasure-chest block ($F51E40)
local TREASURE_LEN      = 40
local MAP_INDEX_OFF     = 0x0082      -- WRAM: u16 map index ($F50082); & 0x01FF
local MENU_OFF          = 0x0059      -- WRAM: menu byte ($F50059); must be 0
local VICTORY_OFF       = 0x7E04      -- CARTRAM: victory byte ($E07E04); goal when != 0

-- ROM identity: the patched ROM name begins "6WC" (Client.py validate_rom:
-- rom_name[:3] == b"6WC"). HiROM header at $00:FFC0 / file offset 0xFFC0.
local ROM_SIG          = "6WC"
local SIG_BUS_ADDR     = 0x00FFC0     -- "System Bus": the client's literal address
local SIG_CARTROM_HI   = 0xFFC0       -- "CARTROM"/"ROM": HiROM file header offset
local SIG_CARTROM_LO   = 0x7FC0       -- LoROM offset (last-ditch fallback)

-- ── Location tables (GENERATED from worlds/ff6wc source; see file header) ───────
-- ap_id = 6000 + index in Locations.location_table.

-- EVENT-FLAG checks (58). ap_id -> { wram_byte_off, mask }.
-- byte = EVENT_BASE_OFF + (event_id//8); checked when read & mask (LSB-first).
local LOC_EVENT = {
  [6000]={7846,32},[6002]={7882,128},[6004]={7950,2},[6005]={7818,4},[6007]={7831,128},[6047]={7830,2},[6051]={7834,128},
  [6052]={7844,1},[6066]={7816,1},[6068]={7835,1},[6070]={7835,4},[6072]={7835,8},[6073]={7834,4},[6074]={7843,8},
  [6086]={7852,4},[6087]={7813,4},[6090]={7828,2},[6092]={7828,32},[6094]={7859,2},[6103]={7808,16},[6104]={7832,64},
  [6106]={7899,32},[6107]={7843,128},[6129]={7810,1},[6131]={7889,4},[6132]={7815,128},[6134]={7814,128},[6135]={7858,4},
  [6158]={7811,32},[6159]={7820,2},[6161]={7819,128},[6164]={7821,8},[6166]={7819,8},[6181]={7826,1},[6183]={7859,16},
  [6185]={7831,4},[6187]={7899,4},[6195]={7826,32},[6197]={7882,8},[6205]={7857,64},[6206]={7894,4},[6216]={7845,64},
  [6218]={7863,16},[6219]={7818,1},[6222]={7834,16},[6232]={7823,64},[6237]={7828,4},[6239]={7843,64},[6240]={7843,32},
  [6264]={7816,64},[6266]={7887,16},[6267]={7892,2},[6269]={7891,64},[6271]={7853,16},[6272]={7853,32},[6273]={7843,16},
  [6274]={7844,2},[6275]={7843,4},
}

-- TREASURE chests (259). ap_id -> { byte_index_0_39, mask }.
-- byte = TREASURE_BASE_OFF + index; checked when read & mask (LSB-first).
local LOC_TREASURE = {
  [6010]={15,8},[6011]={16,32},[6012]={16,64},[6013]={15,16},[6014]={15,32},[6015]={16,1},[6016]={15,64},
  [6017]={15,128},[6018]={15,4},[6019]={8,16},[6020]={16,2},[6021]={16,4},[6022]={16,8},[6023]={16,16},
  [6024]={13,128},[6025]={13,64},[6026]={15,2},[6027]={14,8},[6028]={14,4},[6029]={14,2},[6030]={14,1},
  [6031]={14,16},[6032]={14,32},[6033]={14,64},[6034]={14,128},[6035]={15,1},[6036]={32,2},[6037]={20,128},
  [6038]={9,1},[6039]={9,4},[6040]={9,2},[6041]={9,8},[6042]={29,128},[6043]={30,1},[6044]={9,16},
  [6045]={8,64},[6046]={8,128},[6054]={32,128},[6055]={32,64},[6056]={33,1},[6057]={22,1},[6058]={21,64},
  [6059]={21,128},[6060]={23,64},[6061]={21,8},[6062]={21,32},[6063]={24,8},[6064]={21,16},[6065]={22,2},
  [6076]={23,16},[6077]={23,32},[6078]={23,4},[6079]={23,8},[6080]={20,8},[6081]={20,4},[6082]={20,32},
  [6083]={20,16},[6084]={20,64},[6085]={29,64},[6096]={16,128},[6097]={11,128},[6098]={17,1},[6099]={17,2},
  [6100]={23,128},[6101]={24,1},[6102]={24,2},[6109]={12,2},[6110]={2,4},[6111]={2,8},[6112]={24,32},
  [6113]={24,16},[6114]={24,128},[6115]={24,64},[6116]={25,1},[6117]={25,2},[6118]={25,4},[6119]={25,8},
  [6120]={25,64},[6121]={25,16},[6122]={25,32},[6123]={19,4},[6124]={18,64},[6125]={18,128},[6126]={19,1},
  [6127]={19,2},[6128]={19,8},[6137]={6,4},[6138]={26,16},[6139]={26,8},[6140]={26,4},[6141]={6,128},
  [6142]={30,8},[6143]={7,16},[6144]={7,8},[6145]={7,4},[6146]={17,64},[6147]={18,2},[6148]={17,128},
  [6149]={18,1},[6150]={18,4},[6151]={18,32},[6152]={18,16},[6153]={18,8},[6154]={5,1},[6155]={4,128},
  [6156]={4,64},[6157]={4,32},[6168]={10,4},[6169]={10,8},[6170]={10,16},[6171]={10,128},[6172]={10,32},
  [6173]={10,64},[6174]={11,4},[6175]={11,8},[6176]={11,16},[6177]={11,32},[6178]={11,1},[6179]={11,2},
  [6180]={11,64},[6188]={13,1},[6189]={13,2},[6190]={22,32},[6191]={22,64},[6192]={22,128},[6193]={23,2},
  [6194]={22,16},[6199]={26,32},[6200]={32,4},[6201]={13,32},[6202]={13,4},[6203]={13,8},[6204]={13,16},
  [6208]={19,16},[6209]={19,32},[6210]={19,64},[6211]={19,128},[6212]={20,2},[6213]={20,1},[6220]={7,128},
  [6221]={8,1},[6223]={29,1},[6224]={29,2},[6225]={29,4},[6226]={28,16},[6227]={24,4},[6228]={26,2},
  [6229]={29,32},[6230]={29,16},[6231]={26,1},[6234]={21,4},[6235]={21,1},[6236]={21,2},[6248]={28,2},
  [6249]={29,8},[6250]={28,4},[6251]={30,2},[6252]={26,128},[6253]={26,64},[6254]={27,2},[6255]={27,4},
  [6256]={27,32},[6257]={27,8},[6258]={27,64},[6259]={27,16},[6260]={30,4},[6261]={27,128},[6262]={28,1},
  [6263]={27,1},[6279]={12,32},[6280]={12,64},[6281]={12,128},[6282]={12,4},[6283]={12,16},[6284]={12,8},
  [6285]={12,1},[6286]={6,16},[6287]={6,32},[6288]={6,64},[6289]={22,8},[6290]={6,8},[6291]={28,32},
  [6292]={4,16},[6293]={1,64},[6294]={1,128},[6295]={2,2},[6296]={2,1},[6297]={8,4},[6298]={8,2},
  [6299]={8,32},[6300]={30,32},[6301]={30,16},[6302]={7,32},[6303]={31,8},[6304]={0,4},[6305]={1,4},
  [6306]={17,8},[6307]={17,4},[6308]={17,32},[6309]={17,16},[6310]={1,2},[6311]={1,1},[6312]={0,128},
  [6313]={0,64},[6314]={0,32},[6315]={0,16},[6316]={32,8},[6317]={32,16},[6318]={32,32},[6319]={1,8},
  [6320]={1,16},[6321]={1,32},[6322]={7,64},[6323]={6,1},[6324]={5,4},[6325]={5,2},[6326]={5,64},
  [6327]={5,128},[6328]={5,32},[6329]={5,8},[6330]={5,16},[6331]={6,2},[6332]={4,1},[6333]={4,4},
  [6334]={4,8},[6335]={4,2},[6336]={31,128},[6337]={31,32},[6338]={31,64},[6339]={3,64},[6340]={3,128},
  [6341]={33,64},[6342]={33,32},[6343]={33,128},[6344]={33,8},[6345]={33,16},[6346]={33,4},[6347]={34,1},
  [6348]={33,2},[6349]={3,2},[6350]={3,1},[6351]={28,64},[6352]={2,64},[6353]={2,128},[6354]={2,32},
  [6355]={28,128},[6356]={2,16},[6357]={31,16},[6358]={32,1},[6359]={3,4},[6360]={3,16},[6361]={3,8},
  [6362]={3,32},[6363]={28,8},[6364]={31,2},[6365]={31,1},[6366]={31,4},[6367]={30,128},[6368]={30,64},
}

-- SPECIAL-CASE checks (Client.py location_check branch). Each group has an
-- "initial" (Encountered) bit, a "first" (First Reward Picked) bit and a "both"
-- (Both Rewards Picked) bit, all in the event-flag array. Resolution, exactly per
-- the client: if (initial OR both): location = first ? loc1 : loc2; if both: BOTH.
-- Each entry: { wram_byte_off, mask }.
local SPECIALS = {
  { loc1 = 6214, loc2 = 6215,                              -- Lone Wolf 1 / 2
    initial = {8017, 32}, first = {7891, 128}, both = {7880, 2} },
  { loc1 = 6049, loc2 = 6050,                              -- Narshe Weapon Shop 1 / 2
    initial = {8000, 32}, first = {7830, 32},  both = {7830, 128} },
}

-- POINT-OF-NO-RETURN back-fill (Client.py point_of_no_return_checks): when the
-- TRIGGER event-flag check fires, these chest ap_ids are also reported (they sit
-- behind a one-way boss and can no longer be opened). trigger ap_id -> {passed ids}.
local PONR = {
  [6070]={6076,6077,6078,6079},
  [6092]={6096,6097,6098,6099},
  [6131]={6146,6147,6148,6149,6150,6151,6152,6153},
  [6134]={6137,6138,6139,6140},
  [6135]={6141,6142,6143,6144,6145},
  [6164]={6168,6169,6170,6171,6172,6173,6174,6175,6176,6177,6178,6179,6180},
  [6181]={6188,6189},
}

-- ── Internal state ────────────────────────────────────────────────────────────
local reported         = {}     -- ap_id -> true once returned from poll()
local server_locations = nil    -- set of ap_ids the server expects (nil = all)
local items_received   = {}     -- ordered stream (extended ITEM lines)
local slot_number      = 0
local remote_items     = false
local rom_ok           = nil    -- cached "6WC" signature result
local sig_domain       = nil    -- {domain, addr} that yielded the signature
local mem              = {}
local log_fn           = nil

-- Per-poll snapshot of the 40-byte treasure block, refreshed each frame.
local treasure = {}     -- byte index 0..39

-- ── Logging ───────────────────────────────────────────────────────────────────
local function log(msg)
  if log_fn then pcall(log_fn, "[ff6wc] " .. tostring(msg)) end
end

-- ── Memory API (resolved at init; 2-arg domain form + current-domain fallback) ─
local function resolve_memory_api()
  if not memory then return false end
  mem.read_u8     = memory.read_u8     or memory.readbyte
  mem.read_u16_le = memory.read_u16_le or memory.readword
  return mem.read_u8 ~= nil
end

local function rd8(addr, domain)
  if not mem.read_u8 then return nil end
  local ok, v = pcall(mem.read_u8, addr, domain)
  if ok and type(v) == "number" then return v end
  ok, v = pcall(mem.read_u8, addr)              -- older API: current domain
  if ok and type(v) == "number" then return v end
  return nil
end

local function read_u8(addr, domain) return rd8(addr, domain or WRAM) end

local function read_u16(addr, domain)
  domain = domain or WRAM
  if mem.read_u16_le then
    local ok, v = pcall(mem.read_u16_le, addr, domain)
    if ok and type(v) == "number" then return v end
    ok, v = pcall(mem.read_u16_le, addr)
    if ok and type(v) == "number" then return v end
  end
  -- Fall back to two byte reads (little-endian).
  local lo = read_u8(addr, domain)
  local hi = read_u8(addr + 1, domain)
  if lo == nil or hi == nil then return nil end
  return lo + hi * 256
end

-- Read from CARTRAM, falling back to the "SRAM" domain name on cores that use it.
local function read_cartram_u8(off)
  local ok, v = pcall(mem.read_u8, off, CARTRAM)
  if ok and type(v) == "number" then return v end
  ok, v = pcall(mem.read_u8, off, "SRAM")
  if ok and type(v) == "number" then return v end
  return nil
end

-- Read one byte trying a list of {domain, addr} pairs in order (for the ROM sig).
local function read_first(pairs_list)
  for _, p in ipairs(pairs_list) do
    local ok, v = pcall(mem.read_u8, p[2], p[1])
    if ok and type(v) == "number" then return v, p end
  end
  return nil
end

local function bit_and(a, b)
  -- 16-bit safe AND without the bit library (cores vary).
  local res, bitval = 0, 1
  while a > 0 and b > 0 do
    if a % 2 == 1 and b % 2 == 1 then res = res + bitval end
    a = math.floor(a / 2); b = math.floor(b / 2); bitval = bitval * 2
  end
  return res
end

-- ── ROM identity: the patched ROM name begins "6WC" ───────────────────────────
-- Tries System Bus 0x00FFC0 (the client's literal address), then CARTROM/ROM HiROM
-- (FF6 is HiROM) and the LoROM offset as a last-ditch fallback. Whichever domain
-- yields "6WC" is cached and reused.
local function rom_is_ap()
  if rom_ok ~= nil then return rom_ok end
  local first, picked = read_first({
    { "System Bus", SIG_BUS_ADDR },
    { "CARTROM",    SIG_CARTROM_HI },
    { "ROM",        SIG_CARTROM_HI },
    { "CARTROM",    SIG_CARTROM_LO },
    { "ROM",        SIG_CARTROM_LO },
  })
  if first == nil then return false end           -- ROM not readable yet; retry
  if first ~= string.byte(ROM_SIG, 1) then
    rom_ok = false
    log("non-6WC/non-AP ROM (no '6WC' header) — detection idle, no writes")
    return false
  end
  for i = 2, #ROM_SIG do
    local ok, b = pcall(mem.read_u8, picked[2] + i - 1, picked[1])
    if not ok or type(b) ~= "number" then return false end
    if b ~= string.byte(ROM_SIG, i) then
      rom_ok = false
      log("non-6WC/non-AP ROM (no '6WC' header) — detection idle, no writes")
      return false
    end
  end
  rom_ok = true
  sig_domain = picked
  log(("FF6WC ROM verified ('6WC' header via %s 0x%X)"):format(picked[1], picked[2]))
  return true
end

-- ── Multiworld context ────────────────────────────────────────────────────────
local function load_locations(ids)
  if type(ids) ~= "table" then return end
  server_locations = {}
  local n = 0
  for _, id in ipairs(ids) do
    local v = tonumber(id)
    if v then server_locations[v] = true; n = n + 1 end
  end
  log("server location set: " .. n .. " ids")
end

local function wanted(ap_id)
  if server_locations == nil then return true end   -- no set provided → report all
  return server_locations[ap_id] == true
end

-- Item-stream filter, same policy as the ALttP/EarthBound modules. items_handling
-- is 0b111 (server-driven) for FF6WC, but the patched game still grants its own
-- locally-found items in practice (the client only forwards remote items), so own-
-- world items are dropped unless the slot is in explicit remote mode; server/
-- starting-inventory entries are dropped too.
local function accept_item(it)
  if it.player == nil then return true end          -- legacy ITEM:<id> line
  if it.player == 0 and (it.location or 0) <= 0 then return false end
  if (not remote_items) and it.player == slot_number then return false end
  return true
end

-- ── Detection helpers ─────────────────────────────────────────────────────────

-- Report an ap_id once, honoring the server filter. Returns true if newly added.
local function report(new, ap_id)
  if not reported[ap_id] and wanted(ap_id) then
    reported[ap_id] = true
    new[#new + 1] = ap_id
    return true
  end
  return false
end

-- Mirror of Rom.get_map_index + Client.connection_check: in-game when the map index
-- (low 9 bits of the 16-bit value at 0xF50082) is ≥ 6 and ≠ 255, and the menu byte
-- at 0xF50059 is 0.
local function in_gameplay()
  local mv = read_u16(MAP_INDEX_OFF, WRAM)
  if mv == nil then return false end
  local map_index = bit_and(mv, 0x01FF)
  if map_index < 6 or map_index == 255 then return false end
  local menu = read_u8(MENU_OFF, WRAM)
  return menu ~= nil and menu == 0
end

local function refresh_treasure()
  for i = 0, TREASURE_LEN - 1 do
    treasure[i] = read_u8(TREASURE_BASE_OFF + i, WRAM)
  end
end

-- An event-flag bit at { byte_off, mask } is set?
local function event_set(byte_off, mask)
  local b = read_u8(byte_off, WRAM)
  return b ~= nil and bit_and(b, mask) ~= 0
end

local function scan_into(new)
  -- Event-flag checks (with point-of-no-return back-fill on the trigger checks).
  for ap_id, em in pairs(LOC_EVENT) do
    if not reported[ap_id] and wanted(ap_id) and event_set(em[1], em[2]) then
      reported[ap_id] = true
      new[#new + 1] = ap_id
      local passed = PONR[ap_id]
      if passed then
        for _, pid in ipairs(passed) do report(new, pid) end
      end
    end
  end

  -- Treasure chests (40-byte block snapshot).
  for ap_id, tm in pairs(LOC_TREASURE) do
    if not reported[ap_id] and wanted(ap_id) then
      local b = treasure[tm[1]]
      if b ~= nil and bit_and(b, tm[2]) ~= 0 then
        reported[ap_id] = true
        new[#new + 1] = ap_id
      end
    end
  end

  -- Special-cased Lone Wolf / Narshe Weapon Shop pairs.
  for _, g in ipairs(SPECIALS) do
    if not (reported[g.loc1] and reported[g.loc2]) then
      local initial = event_set(g.initial[1], g.initial[2])
      local both    = event_set(g.both[1],    g.both[2])
      if initial or both then
        if both then
          report(new, g.loc1)
          report(new, g.loc2)
        else
          local first = event_set(g.first[1], g.first[2])
          report(new, first and g.loc1 or g.loc2)
        end
      end
    end
  end
end

-- ── Module contract ───────────────────────────────────────────────────────────

function M.init(ctx)
  if ctx and type(ctx.log) == "function" then log_fn = ctx.log end
  if not resolve_memory_api() then
    log("BizHawk memory API unavailable — module idle")
    ADDRESSES_VERIFIED = false
    return
  end
  local cfg = (ctx and ctx.config) or {}
  slot_number = tonumber(cfg.slot_number) or 0
  local sd = cfg.slot_data
  if type(sd) == "table" then
    remote_items = (sd.remote_items == true) or (tonumber(sd.remote_items) == 1)
  end
  load_locations(cfg.locations)
  local ne, nt = 0, 0
  for _ in pairs(LOC_EVENT)    do ne = ne + 1 end
  for _ in pairs(LOC_TREASURE) do nt = nt + 1 end
  log(("ready: slot #%d, remote_items=%s, %d event + %d treasure + %d special location flags")
      :format(slot_number, tostring(remote_items), ne, nt, #SPECIALS * 2))
end

function M.poll()
  local new = {}
  if not ADDRESSES_VERIFIED then return new end
  if not rom_is_ap() then return new end
  if not in_gameplay() then return new end
  refresh_treasure()
  scan_into(new)
  return new
end

function M.is_goal_complete()
  if not ADDRESSES_VERIFIED or not rom_is_ap() then return false end
  -- Client.check_victory2: CARTRAM victory byte at $E07E04 ≠ 0.
  local v = read_cartram_u8(VICTORY_OFF)
  return v ~= nil and v ~= 0
end

-- Remote multiworld items: see the file header. items_handling = 0b111 (server-
-- driven). Applying received items is the client's intricate per-type guarded-write
-- path (characters: init+recruit bits + obtained counter + SwdTech/Blitz unlock at
-- 0xF51CF7/0xF51D28; espers: esper bit at 0xF51A69 + counter at 0xF51FC8; items:
-- scan the 255-slot field inventory at 0xF51869/0xF51969 for a free/matching slot
-- and bump the quantity), bumping items_received at 0xF51DC9 after each. That whole
-- path needs in-emulator verification before it is wired — a wrong WRAM write would
-- corrupt the save — so we record the stream (a future wiring has it) but make no
-- write until then.
function M.receive_item(item_id, meta)
  if type(meta) == "table" then
    items_received[#items_received + 1] = {
      item     = tonumber(item_id),
      index    = tonumber(meta.index),
      player   = tonumber(meta.player),
      flags    = tonumber(meta.flags),
      location = tonumber(meta.locId),
    }
  else
    items_received[#items_received + 1] = { item = tonumber(item_id) }
  end
  -- intentionally no memory write (documented; deferred until in-emulator verified)
  -- accept_item() is retained above so a future delivery wiring filters the stream
  -- with the same own-world/remote policy as the other SNES modules.
  local _ = accept_item
end

return M
