-- ═══════════════════════════════════════════════════════════════════════════════
-- lufia2ac.lua — game module for the Archipelago BizHawk connector.
--               Lufia II: Rise of the Sinistrals — Ancient Cave mode (SNES)
--
-- STATUS: location DETECTION + goal are REAL and SOURCE-DERIVED from the official
-- AP world worlds/lufia2ac (Client.py + Locations.py + __init__.py + Rom.py, main
-- branch). Every address, counter and the location-id math were read directly out
-- of the SNIClient (worlds/lufia2ac/Client.py) and Locations.py; the id offsets
-- (Boss 0x01C2, Iris 0x039C+, blue-chest count 113) were GENERATED by parsing the
-- source, not hand-copied. Loads crash-free on any ROM; self-disables on a non-AP
-- cartridge. Mock-verified through MoonSharp against synthetic CARTRAM.
--
-- ITEM DELIVERY IS DEFERRED (see receive_item): items_handling = 0b111 (FULLY
-- REMOTE) — unlike a self-granting world, Lufia hands EVERY received item to the
-- game through the client's RX cartridge-SRAM handshake. That write path is
-- faithfully transcribed here from Client.py but GATED behind RECEIVE_ITEMS_VERIFIED
-- (default false) because writing into battery SRAM mid-frame is the one piece that
-- needs in-emulator confirmation before shipping. Until then receive_item only
-- records the stream and performs NO writes (never a wrong write).
--
-- MEMORY MODEL (SNI → BizHawk)
-- ────────────────────────────
--   The lufia2ac client is an SNIClient. It reads/writes ONLY cartridge battery
--   SRAM — SNI SRAM_START(0xE00000)+off → BizHawk domain "CARTRAM" (fallback
--   "SRAM" on cores that name it so), offset off. (It does NOT touch WRAM at all.)
--   Client.py constants, expressed as CARTRAM offsets (net of SRAM_START):
--     SIGN_ADDR  = 0x2000   16 bytes "ArchipelagoLufia"  (gameplay/AP gate)
--     GOAL_ADDR  = 0x2030   10 bytes  goal record (see is_goal_complete)
--     DEATH_ADDR = 0x203D   DeathLink (not used here)
--     TX_ADDR    = 0x2040   game → client telemetry  (location counters below)
--     RX_ADDR    = 0x2800   client → game item queue (receive_item, gated)
--   The ROM-name signature the SNIClient's validate_rom checks ("L2AC" at ROM
--   0x007FC0) is a SEPARATE check; the CARTRAM "ArchipelagoLufia" signature is the
--   one game_watcher gates every poll on, so it is what we use here.
--
-- LOCATION MODEL (mirrors worlds/lufia2ac/Client.py game_watcher TX block)
--   NOT a flag-bit scan — a pair of COUNTERS plus a small index array:
--     • blue chests : u16 count n at TX+0  → ap_id = START_ID + i for i in 0..n-1
--     • other locs  : u16 count m at TX+10 → array of u16 at TX+32; each value v
--                     → ap_id = START_ID + v  (v = 0x01C2 Boss, 0x039C..0x03A4 Iris)
--   START_ID = 0xAC0000 (Locations.py). The server-location filter still applies,
--   so only ids the slot actually owns are reported.
--
-- GOAL (mirrors game_watcher Goal block)
--   read 10 bytes at GOAL+0; let k = byte[0]; goal complete when byte[k] == 0x01.
--   (The ROM bakes the index k for the chosen goal — final-floor / boss / iris /
--   boss+iris — into the record, so a single read covers every goal option.)
--
-- MODULE CONTRACT (called by bizhawk_ap_connector.lua)
--   M.init(ctx) / M.poll() -> {ids} / M.is_goal_complete() -> bool /
--   M.receive_item(item_id, meta)
-- ═══════════════════════════════════════════════════════════════════════════════

local M = {}
M.name = "lufia2ac"

-- Detection + goal are source-derived and fully self-contained (absolute AP ids,
-- no per-slot base offset needed). Item WRITES are the only deferred piece.
local ADDRESSES_VERIFIED      = true
-- Cartridge-SRAM item delivery is transcribed from Client.py but not yet confirmed
-- in a real emulator; keep it OFF so receive_item never performs an unverified
-- write. Flip to true only after an in-emulator playthrough confirms the RX path.
local RECEIVE_ITEMS_VERIFIED  = false

-- ── Memory domains ────────────────────────────────────────────────────────────
local CARTRAM = "CARTRAM"     -- SNES battery SRAM in BizHawk; fallback "SRAM"

-- ── CARTRAM offsets (Client.py, net of SRAM_START = 0xE00000) ──────────────────
local SIGN_ADDR  = 0x2000     -- "ArchipelagoLufia" (16 bytes)
local GOAL_ADDR  = 0x2030     -- goal record (10 bytes)
local TX_ADDR    = 0x2040     -- game → client
local RX_ADDR    = 0x2800     -- client → game (item delivery)

-- TX sub-fields (Client.py tx_data = read(TX_ADDR, 12) + loc array at TX+32).
local TX_BLUE_COUNT   = TX_ADDR + 0      -- u16: blue chests checked
local TX_OTHER_COUNT  = TX_ADDR + 10     -- u16: other locations checked
local TX_OTHER_ARRAY  = TX_ADDR + 32     -- u16[]: location offsets (value v → id)

-- RX sub-fields (Client.py rx_data = read(RX_ADDR, 4)).
local RX_RECV_COUNT   = RX_ADDR + 0      -- u16: items the game has consumed

local AP_SIGN = "ArchipelagoLufia"       -- 16 chars

-- ── Location id math (Locations.py) ───────────────────────────────────────────
local START_ID  = 0xAC0000               -- 11272192
local BLUE_MAX  = 113                     -- BlueChestCount.overall_max (= 100+7+6)
local OFF_BOSS  = 0x01C2                  -- Boss        → START_ID + 0x01C2
local OFF_IRIS  = 0x039C                  -- Iris 1..9   → START_ID + 0x039C + (0..8)

-- ── Internal state ────────────────────────────────────────────────────────────
local reported         = {}     -- ap_id -> true once returned from poll()
local server_locations = nil    -- set of ap_ids the server expects (nil = all)
local items_received   = {}     -- ordered stream (extended ITEM lines)
local slot_number      = 0
local rom_ok           = nil    -- cached "ArchipelagoLufia" signature result
local mem              = {}
local log_fn           = nil

-- ── Logging ───────────────────────────────────────────────────────────────────
local function log(msg)
  if log_fn then pcall(log_fn, "[lufia2ac] " .. tostring(msg)) end
end

-- ── Memory API (resolved at init; 2-arg domain form + current-domain fallback) ─
local function resolve_memory_api()
  if not memory then return false end
  mem.read_u8   = memory.read_u8     or memory.readbyte
  mem.read_u16  = memory.read_u16_le or memory.readword
  mem.write_u8  = memory.write_u8    or memory.writebyte
  mem.write_u16 = memory.write_u16_le or memory.writeword
  return mem.read_u8 ~= nil
end

-- Read with the CARTRAM domain, falling back to "SRAM" (some cores name it so),
-- then to the no-domain (current-domain) form on the oldest API.
local function rd_cart(fn, addr)
  if not fn then return nil end
  local ok, v = pcall(fn, addr, CARTRAM)
  if ok and type(v) == "number" then return v end
  ok, v = pcall(fn, addr, "SRAM")
  if ok and type(v) == "number" then return v end
  ok, v = pcall(fn, addr)
  if ok and type(v) == "number" then return v end
  return nil
end

local function read_u8(addr)  return rd_cart(mem.read_u8,  addr) end
local function read_u16(addr) return rd_cart(mem.read_u16, addr) end

local function write_u8(addr, value)
  if not mem.write_u8 then return false end
  if pcall(mem.write_u8, addr, value, CARTRAM) then return true end
  if pcall(mem.write_u8, addr, value, "SRAM")  then return true end
  if pcall(mem.write_u8, addr, value)          then return true end
  return false
end

local function write_u16(addr, value)
  -- Prefer a native 16-bit writer; otherwise compose from two byte writes.
  if mem.write_u16 then
    if pcall(mem.write_u16, addr, value, CARTRAM) then return true end
    if pcall(mem.write_u16, addr, value, "SRAM")  then return true end
    if pcall(mem.write_u16, addr, value)          then return true end
  end
  local lo = value % 256
  local hi = math.floor(value / 256) % 256
  return write_u8(addr, lo) and write_u8(addr + 1, hi)
end

-- ── ROM identity: the AP basepatch writes "ArchipelagoLufia" at CARTRAM 0x2000 ──
local function rom_is_ap()
  if rom_ok ~= nil then return rom_ok end
  for i = 1, #AP_SIGN do
    local b = read_u8(SIGN_ADDR + i - 1)
    if b == nil then return false end          -- not readable yet; retry next poll
    if b ~= string.byte(AP_SIGN, i) then
      rom_ok = false
      log("non-AP ROM (no 'ArchipelagoLufia' signature) — detection idle, no writes")
      return false
    end
  end
  rom_ok = true
  log("AP ROM verified ('ArchipelagoLufia' signature present)")
  return true
end

-- ── Multiworld context ────────────────────────────────────────────────────────
local function load_locations(ids)
  if type(ids) ~= "table" then return end
  server_locations = {}
  local n = 0
  for _, id in ipairs(ids) do
    local v = tonumber(id)
    if v then server_locations[v] = true; n = n + 1 end
  end
  log("server location set: " .. n .. " ids")
end

local function wanted(ap_id)
  if server_locations == nil then return true end   -- no set provided → report all
  return server_locations[ap_id] == true
end

local function report(new, ap_id)
  if not reported[ap_id] and wanted(ap_id) then
    reported[ap_id] = true
    new[#new + 1] = ap_id
  end
end

-- ── Detection: the client's TX-counter scan ───────────────────────────────────
local function scan_into(new)
  -- Blue chests: report START_ID + i for i in 0 .. count-1 (clamped to BLUE_MAX,
  -- exactly as Client.py clamps total_blue_chests_checked to overall_max).
  local blue = read_u16(TX_BLUE_COUNT)
  if blue then
    if blue > BLUE_MAX then blue = BLUE_MAX end
    for i = 0, blue - 1 do
      report(new, START_ID + i)
    end
  end

  -- Other locations (Boss + Iris treasures): m u16 offsets at TX+32; each value v
  -- maps to START_ID + v.
  local other = read_u16(TX_OTHER_COUNT)
  if other and other > 0 then
    if other > 256 then other = 256 end        -- sanity bound (table is small)
    for k = 0, other - 1 do
      local v = read_u16(TX_OTHER_ARRAY + 2 * k)
      if v then report(new, START_ID + v) end
    end
  end
end

-- ── Module contract ───────────────────────────────────────────────────────────

function M.init(ctx)
  if ctx and type(ctx.log) == "function" then log_fn = ctx.log end
  if not resolve_memory_api() then
    log("BizHawk memory API unavailable — module idle")
    ADDRESSES_VERIFIED = false
    return
  end
  local cfg = (ctx and ctx.config) or {}
  slot_number = tonumber(cfg.slot_number) or 0
  load_locations(cfg.locations)
  log(("ready: slot #%d, blue-chest max %d, START_ID 0x%X (detection live%s)")
      :format(slot_number, BLUE_MAX, START_ID,
              RECEIVE_ITEMS_VERIFIED and ", item delivery on" or ", item delivery deferred"))
end

function M.poll()
  local new = {}
  if not ADDRESSES_VERIFIED then return new end
  if not rom_is_ap() then return new end
  scan_into(new)
  return new
end

-- Goal: read 10 bytes at GOAL+0; index k = byte[0]; complete when byte[k] == 0x01.
-- (Client.py: goal_data[goal_data[0]] == 0x01.)
function M.is_goal_complete()
  if not ADDRESSES_VERIFIED or not rom_is_ap() then return false end
  local k = read_u8(GOAL_ADDR)
  if k == nil then return false end
  if k > 9 then return false end                -- record is 10 bytes; stay in range
  local b = read_u8(GOAL_ADDR + k)
  return b == 0x01
end

-- Remote multiworld items. items_handling = 0b111 (fully remote): the game grants
-- NOTHING locally, so every received item must be delivered through the client's
-- RX cartridge-SRAM handshake. The protocol below is transcribed exactly from
-- Client.py's RX block:
--   snes_items_received = u16 at RX+0   (the game's own consumed-count)
--   if snes_items_received < #stream:
--       item_code = item.item - items_start_id
--       n = snes_items_received + 1
--       write u16 item_code at RX + 2*(n+1)
--       write u16 n          at RX
-- The game owns RX+0 and bumps it as it consumes; we only ever write the SINGLE
-- next item, so re-entrancy and resends can't double-deliver.
--
-- This is GATED behind RECEIVE_ITEMS_VERIFIED because writing into battery SRAM
-- mid-frame is the one piece that needs in-emulator confirmation. While the gate
-- is closed we record the stream (so flipping the flag later is a one-line change)
-- and perform NO writes — never a wrong write.
function M.receive_item(item_id, meta)
  if type(meta) == "table" then
    items_received[#items_received + 1] = {
      item     = tonumber(item_id),
      index    = tonumber(meta.index),
      player   = tonumber(meta.player),
      flags    = tonumber(meta.flags),
      location = tonumber(meta.location or meta.locId),
    }
  else
    items_received[#items_received + 1] = { item = tonumber(item_id) }
  end

  if not RECEIVE_ITEMS_VERIFIED then return end           -- deferred: no writes yet
  if not ADDRESSES_VERIFIED or not rom_is_ap() then return end

  -- The launcher delivers AP item codes already net of items_start_id is NOT
  -- guaranteed — the connector forwards the raw AP item id. Client.py subtracts
  -- items_start_id (= 0xAC0000, same base as locations) to get the in-game code.
  local recv = read_u16(RX_RECV_COUNT)
  if recv == nil then return end
  if recv < #items_received then
    local it = items_received[recv + 1]
    if it and it.item then
      local code = it.item - START_ID            -- items_start_id == 0xAC0000
      if code < 0 then code = 0 end
      local n = recv + 1
      write_u16(RX_ADDR + 2 * (n + 1), code % 65536)
      write_u16(RX_RECV_COUNT, n)
    end
  end
end

return M
