-- ═══════════════════════════════════════════════════════════════════════════════
-- Mega Man X2.lua — game module for the Archipelago BizHawk connector.
--                   Mega Man X2 (SNES)
--
-- STATUS: COMMUNITY world. location DETECTION + goal are REAL and SOURCE-DERIVED
-- from the official apworld worlds/mmx2 (Client.py game_watcher + Locations.py +
-- Levels.py, TheLX5/Archipelago @ branch `mmx2`). The 135-entry location table was
-- GENERATED by JOINING Locations.all_locations (name → AP id) with
-- Levels.location_id_to_level_id (name → [stage, internal_id, data_bit]) using the
-- real Names.LocationName module — not hand-copied — so every (AP id →
-- internal_id/data_bit) pair is exact. Mock-verified through MoonSharp against
-- synthetic WRAM/CARTROM. Loads crash-free on any ROM; self-disables on a non-AP
-- cartridge.
--
-- SOURCE: https://github.com/TheLX5/Archipelago  (branch `mmx2`, worlds/mmx2)
--         game string "Mega Man X2", patch_suffix ".apmmx2", items_handling 0b111.
--
-- MEMORY MODEL (SNI → BizHawk)  — same SNIClient bridge family as Mega Man X
-- ──────────────────────────────────────────────────────────────────────────
--   The mmx2 client is an SNIClient. Its SNI addresses translate to BizHawk SNES
--   memory domains:
--     SNI WRAM_START(0xF50000)+off → domain "WRAM",    offset off (= $7E0000+off)
--     SNI ROM_START(0x000000)+off  → domain "CARTROM", offset off (raw ROM file
--                                    offset; LoROM. Fallbacks "ROM"/"System Bus")
--   Note: the mmx2 base patch fills a 1.5 MB (0x180000) ROM and the client's
--   settings live high in CARTROM at 0x17FFExx — confirmed by Rom.py's writes.
--   The client reads several contiguous RAM blocks; this module reads the same:
--     MMX2_RAM = WRAM+0x1F800 (the AP scratch/data block base). Sub-fields:
--       • game_state      = WRAM 0x000D0  (1 byte)   game_state_data[0]
--       • menu_state      = WRAM 0x000D1  (1 byte)
--       • gameplay_state  = WRAM 0x000D2  (1 byte)
--       • validation word = WRAM 0x1F811  (u16 LE)   == 0xDEAD when patched+running
--       • defeated_bosses = WRAM 0x1F8A0  (0x20 idx)  index by data_bit
--       • cleared_levels  = WRAM 0x1F880  (0x20 idx)  index by data_bit
--       • heart_tanks     = WRAM 0x1F840  (1 byte)    MASK
--       • upgrades        = WRAM 0x1F841  (1 byte)    MASK (upgrades AND sub-tanks)
--       • shoryuken       = WRAM 0x1F842  (1 byte)    != 0
--       • sigma_access    = WRAM 0x1F846  (1 byte)    != 0
--       • collected_pickups = WRAM 0x1F8C0 (0x4E idx) index by data_bit
--     game_settings (pickupsanity gate) = CARTROM 0x17FFE7 (per-seed-baked byte)
--   IDENTITY / VALIDATION (two gates, both mirrored from Client.py):
--     1) ROM header title at CARTROM 0x7FC0 begins with "MMX2" (validate_rom:
--        rom_name[:4] == b"MMX2"). This is baked by the AP basepatch.
--     2) The live AP-validation word (WRAM 0x1F811/0x1F812, little-endian) ==
--        0xDEAD (game_watcher's per-frame "ROM properly validated" check). Only a
--        patched-and-running ROM sets this.
--
-- HOW MMX2 CHECKS WORK (mirrors Client.py game_watcher; per-location internal_id)
--   Each location carries {internal_id, data_bit}:
--     0x000 Boss clear  : defeated_bosses[data_bit] != 0          (INDEX, not mask)
--     0x001 Maverick    : cleared_levels[data_bit]  != 0          (INDEX)
--     0x002 Heart Tank  : heart_tanks & data_bit != 0             (MASK on one byte)
--     0x003 Upgrade     : upgrades    & data_bit != 0             (MASK)
--     0x004 Sub Tank    : upgrades    & data_bit != 0             (MASK; same byte as 003)
--     0x005 Shoryuken   : shoryuken    != 0                        (data_bit unused)
--     0x006 Sigma access: sigma_access != 0                        (data_bit unused)
--     0x007 Intro clear : game_state==0x02 AND menu_state==0x00 AND gameplay_state==0x01
--     0x020 Pickup      : gated on pickupsanity (CARTROM 0x17FFE7);
--                          collected_pickups[data_bit] != 0  (INDEX)
--
-- WHAT THIS DOES
--   • poll(): the game_watcher location scan above → AP location ids, gated to the
--     slot's server location set and to the in-game state. game_watcher bails when
--     game_state[0] == 0 (title / no save) and reports checks while game_state != 0
--     with validation == 0xDEAD. We require the live 0xDEAD word plus game_state != 0.
--   • is_goal_complete(): Sigma defeated — the victory location ("Defeated Sigma",
--     AP id 12454933) is internal_id 0x000, data_bit 0x17 → defeated_bosses[0x17]
--     (WRAM 0x1F8B7) != 0. The apworld places the locked Victory item there;
--     defeating Sigma is the goal.
--   • receive_item(): NO-OP (documented). items_handling = 0b111 (FULL remote) —
--     the mmx2 client owns ALL item delivery via an intricate, heavily-state-gated
--     set of WRAM writes (weapon/upgrade/sub-tank/heart-tank/enhancement/boss-
--     access arrays, a recv-index handshake at MMX2_RAM+0x00, an SFX strobe, a
--     per-item queue that waits on menu/gameplay/pause/can-move/screen-brightness/
--     ride-armor states, an arsenal save/load round-trip through AP data-storage,
--     plus EnergyLink/DeathLink/HP-trade). That path is the one piece that needs
--     in-emulator verification before it is wired, so it is left out rather than
--     shipped unverified (a wrong write would corrupt the save / desync recv-index).
--     Checks + goal above are fully functional regardless of this gap.
--
-- MODULE CONTRACT (called by bizhawk_ap_connector.lua)
--   M.init(ctx) / M.poll() -> {ids} / M.is_goal_complete() -> bool /
--   M.receive_item(item_id, meta)
-- ═══════════════════════════════════════════════════════════════════════════════

local M = {}
M.name = "Mega Man X2"

local ADDRESSES_VERIFIED = true   -- table generated from worlds/mmx2 source

-- ── Memory domains ────────────────────────────────────────────────────────────
local WRAM    = "WRAM"
local CARTROM = "CARTROM"     -- SNES cartridge ROM in BizHawk; fallbacks below

-- ── Addresses / constants (worlds/mmx2/Client.py module top) ──────────────────
-- Expressed as BizHawk-domain offsets (already net of WRAM_START / ROM_START).
-- MMX2_RAM = WRAM_START + 0x1F800.
local MMX2_RAM_OFF      = 0x1F800

local GAME_STATE_OFF    = 0x000D0     -- WRAM: game_state_data[0]
local MENU_STATE_OFF    = 0x000D1     -- WRAM: menu_state
local GAMEPLAY_STATE_OFF= 0x000D2     -- WRAM: gameplay_state

-- MMX2_RAM sub-fields (offsets RELATIVE to MMX2_RAM_OFF).
local R_VALIDATION      = 0x00011     -- u16 LE; == 0xDEAD when patched+running
local R_HEART_TANKS     = 0x00040     -- u8 mask: collected heart-tank flags
local R_UPGRADES        = 0x00041     -- u8 mask: collected upgrade/sub-tank flags
local R_SHORYUKEN       = 0x00042     -- u8: != 0 once Shoryuken collected
local R_SIGMA_ACCESS    = 0x00046     -- u8: != 0 once Sigma access collected
local R_CLEARED_BASE    = 0x00080     -- cleared_levels[];   index by data_bit (0x20)
local R_BOSSES_BASE     = 0x000A0     -- defeated_bosses[];   index by data_bit (0x20)
local R_PICKUPS_BASE    = 0x000C0     -- collected_pickups[]; index by data_bit (0x4E)

-- Absolute WRAM offsets derived from MMX2_RAM_OFF (computed once).
local VALIDATION_OFF    = MMX2_RAM_OFF + R_VALIDATION     -- 0x1F811
local HEART_TANKS_OFF   = MMX2_RAM_OFF + R_HEART_TANKS    -- 0x1F840
local UPGRADES_OFF      = MMX2_RAM_OFF + R_UPGRADES       -- 0x1F841
local SHORYUKEN_OFF     = MMX2_RAM_OFF + R_SHORYUKEN      -- 0x1F842
local SIGMA_ACCESS_OFF  = MMX2_RAM_OFF + R_SIGMA_ACCESS   -- 0x1F846
local CLEARED_BASE_OFF  = MMX2_RAM_OFF + R_CLEARED_BASE   -- 0x1F880
local BOSSES_BASE_OFF   = MMX2_RAM_OFF + R_BOSSES_BASE    -- 0x1F8A0
local PICKUPS_BASE_OFF  = MMX2_RAM_OFF + R_PICKUPS_BASE   -- 0x1F8C0

-- game_settings / pickupsanity gate lives in CARTROM (per-seed-baked).
local PICKUPSANITY_OFF  = 0x17FFE7    -- CARTROM: MMX2_PICKUPSANITY_ACTIVE

local ROMHASH_OFF       = 0x7FC0      -- CARTROM: ROM-header title; first 4 = "MMX2"

-- Block sizes (match the client's snes_read lengths).
local LEN_BOSSES        = 0x20
local LEN_CLEARED       = 0x20
local LEN_PICKUPS       = 0x4E

-- Live validation word value.
local VALIDATION_OK     = 0xDEAD

-- Goal: Sigma defeated — boss clear index 0x17 (victory location "Defeated Sigma").
local GOAL_BOSS_INDEX   = 0x17

-- Check-type tags (Client.py game_watcher internal_id values).
local T_BOSS        = 0x000
local T_MAVERICK    = 0x001
local T_HEART_TANK  = 0x002
local T_UPGRADE     = 0x003
local T_SUB_TANK    = 0x004
local T_SHORYUKEN   = 0x005
local T_SIGMA       = 0x006
local T_INTRO       = 0x007
local T_PICKUP      = 0x020

-- ── Location table (GENERATED from worlds/mmx2 Locations.py ⋈ Levels.py) ───────
-- ap_id -> { internal_id, data_bit }. 135 entries. AP ids are absolute
-- location_name_to_id values (STARTING_ID 0xBE0C00-based); detection is
-- self-contained (no per-slot base offset needed).
local LOC = {
  [12454912]={0x000,0x18},[12454913]={0x000,0x00},[12454914]={0x000,0x01},[12454915]={0x000,0x02},
  [12454916]={0x000,0x03},[12454917]={0x000,0x19},[12454918]={0x000,0x1D},[12454919]={0x000,0x04},
  [12454920]={0x000,0x1A},[12454921]={0x000,0x1B},[12454922]={0x000,0x05},[12454923]={0x000,0x1C},
  [12454924]={0x000,0x06},[12454925]={0x000,0x07},[12454926]={0x000,0x08},[12454927]={0x000,0x09},
  [12454928]={0x000,0x0A},[12454929]={0x000,0x0B},[12454930]={0x000,0x0C},[12454931]={0x000,0x0D},
  [12454932]={0x000,0x16},[12454933]={0x000,0x17},[12454934]={0x000,0x0E},[12454935]={0x000,0x0F},
  [12454936]={0x000,0x10},[12454937]={0x000,0x11},[12454938]={0x000,0x12},[12454939]={0x000,0x13},
  [12454940]={0x000,0x14},[12454941]={0x000,0x15},[12454942]={0x002,0x20},[12454943]={0x002,0x40},
  [12454944]={0x002,0x02},[12454945]={0x002,0x01},[12454946]={0x002,0x08},[12454947]={0x002,0x10},
  [12454948]={0x002,0x04},[12454949]={0x002,0x80},[12454950]={0x004,0x80},[12454951]={0x004,0x10},
  [12454952]={0x004,0x20},[12454953]={0x004,0x40},[12454954]={0x003,0x02},[12454955]={0x003,0x04},
  [12454956]={0x003,0x01},[12454957]={0x003,0x08},[12454958]={0x005,0x01},[12454976]={0x020,0x00},
  [12454977]={0x020,0x01},[12454978]={0x020,0x02},[12454979]={0x020,0x03},[12454980]={0x020,0x04},
  [12454981]={0x020,0x05},[12454982]={0x020,0x06},[12454983]={0x020,0x07},[12454984]={0x020,0x08},
  [12454985]={0x020,0x09},[12454986]={0x020,0x0A},[12454987]={0x020,0x0B},[12454988]={0x020,0x0C},
  [12454989]={0x020,0x0D},[12454990]={0x020,0x0E},[12454991]={0x020,0x0F},[12454992]={0x020,0x10},
  [12454993]={0x020,0x11},[12454994]={0x020,0x12},[12454995]={0x020,0x13},[12454996]={0x020,0x14},
  [12454997]={0x020,0x15},[12454998]={0x020,0x16},[12454999]={0x020,0x17},[12455000]={0x020,0x18},
  [12455001]={0x020,0x19},[12455002]={0x020,0x1A},[12455003]={0x020,0x1B},[12455004]={0x020,0x1C},
  [12455005]={0x020,0x1D},[12455006]={0x020,0x1E},[12455007]={0x020,0x1F},[12455008]={0x020,0x20},
  [12455009]={0x020,0x21},[12455010]={0x020,0x22},[12455011]={0x020,0x23},[12455012]={0x020,0x24},
  [12455013]={0x020,0x25},[12455014]={0x020,0x26},[12455015]={0x020,0x27},[12455016]={0x020,0x28},
  [12455017]={0x020,0x29},[12455018]={0x020,0x2A},[12455019]={0x020,0x2B},[12455020]={0x020,0x2C},
  [12455021]={0x020,0x2D},[12455022]={0x020,0x2E},[12455023]={0x020,0x2F},[12455024]={0x020,0x30},
  [12455025]={0x020,0x31},[12455026]={0x020,0x32},[12455027]={0x020,0x33},[12455028]={0x020,0x34},
  [12455029]={0x020,0x35},[12455030]={0x020,0x36},[12455031]={0x020,0x37},[12455032]={0x020,0x38},
  [12455033]={0x020,0x39},[12455034]={0x020,0x3A},[12455035]={0x020,0x3B},[12455036]={0x020,0x3C},
  [12455037]={0x020,0x3D},[12455038]={0x020,0x3E},[12455039]={0x020,0x3F},[12455040]={0x020,0x40},
  [12455041]={0x020,0x41},[12455042]={0x020,0x42},[12455043]={0x020,0x43},[12455044]={0x020,0x44},
  [12455045]={0x020,0x45},[12455046]={0x020,0x46},[12455047]={0x020,0x47},[12455048]={0x020,0x48},
  [12455049]={0x020,0x49},[12455050]={0x020,0x4A},[12455051]={0x020,0x4B},[12455052]={0x020,0x4C},
  [12455053]={0x020,0x4D},[12455104]={0x001,0x06},[12455105]={0x001,0x02},[12455106]={0x001,0x0E},
  [12455107]={0x001,0x04},[12455108]={0x001,0x0C},[12455109]={0x001,0x00},[12455110]={0x001,0x08},
  [12455111]={0x001,0x0A},[12455112]={0x007,0x00},[12455113]={0x006,0x00},
}

-- ── Internal state ────────────────────────────────────────────────────────────
local reported         = {}     -- ap_id -> true once returned from poll()
local server_locations = nil    -- set of ap_ids the server expects (nil = all)
local rom_ok           = nil    -- cached "MMX2" header result
local mem              = {}
local log_fn           = nil

-- ── Logging ───────────────────────────────────────────────────────────────────
local function log(msg)
  if log_fn then pcall(log_fn, "[mmx2] " .. tostring(msg)) end
end

-- ── Memory API (resolved at init; 2-arg domain form + current-domain fallback) ─
local function resolve_memory_api()
  if not memory then return false end
  mem.read_u8  = memory.read_u8     or memory.readbyte
  mem.read_u16 = memory.read_u16_le or memory.readword
  return mem.read_u8 ~= nil
end

local function rd(fn, addr, domain)
  if not fn then return nil end
  local ok, v = pcall(fn, addr, domain)
  if ok and type(v) == "number" then return v end
  ok, v = pcall(fn, addr)                       -- older API: current domain
  if ok and type(v) == "number" then return v end
  return nil
end

local function read_wram_u8(off)   return rd(mem.read_u8,  off, WRAM) end
local function read_wram_u16(off)  return rd(mem.read_u16, off, WRAM) end

-- CARTROM reads with "ROM" / "System Bus" domain-name fallbacks (cores vary;
-- the raw-file-offset CARTROM/ROM form is what every SNES BizHawk core exposes).
local function read_cartrom_u8(off)
  local ok, v = pcall(mem.read_u8, off, CARTROM)
  if ok and type(v) == "number" then return v end
  ok, v = pcall(mem.read_u8, off, "ROM")
  if ok and type(v) == "number" then return v end
  return nil
end

local function bit_and(a, b)
  -- 8/16-bit safe AND without the bit library (cores vary).
  local res, bitval = 0, 1
  while a > 0 and b > 0 do
    if a % 2 == 1 and b % 2 == 1 then res = res + bitval end
    a = math.floor(a / 2); b = math.floor(b / 2); bitval = bitval * 2
  end
  return res
end

-- ── ROM identity: the SNES header title starts with "MMX2" (validate_rom) ──────
local function rom_is_ap()
  if rom_ok ~= nil then return rom_ok end
  local sig = "MMX2"
  for i = 1, #sig do
    local b = read_cartrom_u8(ROMHASH_OFF + i - 1)
    if b == nil then return false end          -- not readable yet; retry next poll
    if b ~= string.byte(sig, i) then
      rom_ok = false
      log("non-MMX2 ROM (no 'MMX2' header) — detection idle, no reports")
      return false
    end
  end
  rom_ok = true
  log("MMX2 ROM verified ('MMX2' header title present)")
  return true
end

-- ── Multiworld context ────────────────────────────────────────────────────────
local function load_locations(ids)
  if type(ids) ~= "table" then return end
  server_locations = {}
  local n = 0
  for _, id in ipairs(ids) do
    local v = tonumber(id)
    if v then server_locations[v] = true; n = n + 1 end
  end
  log("server location set: " .. n .. " ids")
end

local function wanted(ap_id)
  if server_locations == nil then return true end   -- no set provided → report all
  return server_locations[ap_id] == true
end

-- ── Per-poll snapshots (read once per poll, matching game_watcher) ────────────
local snap = {}     -- the RAM blocks the client reads, refreshed each poll

local function read_region_wram(off, len)
  local t = {}
  for i = 0, len - 1 do t[i] = read_wram_u8(off + i) end
  return t
end

local function refresh_snapshot()
  snap.game_state     = read_wram_u8(GAME_STATE_OFF)
  snap.menu_state     = read_wram_u8(MENU_STATE_OFF)
  snap.gameplay_state = read_wram_u8(GAMEPLAY_STATE_OFF)
  snap.validation     = read_wram_u16(VALIDATION_OFF)
  -- index-based arrays (read the exact spans the client reads)
  snap.bosses  = read_region_wram(BOSSES_BASE_OFF,  LEN_BOSSES)
  snap.cleared = read_region_wram(CLEARED_BASE_OFF, LEN_CLEARED)
  snap.pickups = read_region_wram(PICKUPS_BASE_OFF, LEN_PICKUPS)
  -- single mask/flag bytes
  snap.heart_tanks  = read_wram_u8(HEART_TANKS_OFF)
  snap.upgrades     = read_wram_u8(UPGRADES_OFF)
  snap.shoryuken    = read_wram_u8(SHORYUKEN_OFF)
  snap.sigma_access = read_wram_u8(SIGMA_ACCESS_OFF)
  -- pickupsanity gate lives in CARTROM (per-seed-baked settings byte).
  snap.pickupsanity = (read_cartrom_u8(PICKUPSANITY_OFF) or 0) ~= 0
end

-- Live AP-validation word == 0xDEAD (game_watcher's per-frame gate).
local function validation_ok()
  return snap.validation ~= nil and snap.validation == VALIDATION_OK
end

-- ── One location's "checked?" test (mirrors game_watcher per internal_id) ─────
local function location_checked(internal_id, data_bit)
  if internal_id == T_BOSS then
    local v = snap.bosses[data_bit]                 -- defeated_bosses[data_bit] != 0
    return v ~= nil and v ~= 0
  elseif internal_id == T_MAVERICK then
    local v = snap.cleared[data_bit]                -- cleared_levels[data_bit] != 0
    return v ~= nil and v ~= 0
  elseif internal_id == T_HEART_TANK then
    local v = snap.heart_tanks                      -- heart_tanks & data_bit
    return v ~= nil and bit_and(v, data_bit) ~= 0
  elseif internal_id == T_UPGRADE or internal_id == T_SUB_TANK then
    local v = snap.upgrades                          -- upgrades & data_bit
    return v ~= nil and bit_and(v, data_bit) ~= 0
  elseif internal_id == T_SHORYUKEN then
    local v = snap.shoryuken                         -- shoryuken != 0
    return v ~= nil and v ~= 0
  elseif internal_id == T_SIGMA then
    local v = snap.sigma_access                      -- sigma_access != 0
    return v ~= nil and v ~= 0
  elseif internal_id == T_INTRO then
    -- game_state==0x02 AND menu_state==0x00 AND gameplay_state==0x01
    return snap.game_state == 0x02
       and snap.menu_state == 0x00
       and snap.gameplay_state == 0x01
  elseif internal_id == T_PICKUP then
    if not snap.pickupsanity then return false end
    local v = snap.pickups[data_bit]                 -- collected_pickups[data_bit] != 0
    return v ~= nil and v ~= 0
  end
  return false
end

-- ── Detection gate ────────────────────────────────────────────────────────────
-- game_watcher bails when game_state (game_state_data[0]) == 0 (title/no save)
-- and reports checks while game_state != 0. We also require the live 0xDEAD
-- validation word so a non-AP / un-booted ROM never reports.
local function in_gameplay()
  if not validation_ok() then return false end
  return snap.game_state ~= nil and snap.game_state ~= 0
end

-- ── Module contract ───────────────────────────────────────────────────────────
function M.init(ctx)
  if ctx and type(ctx.log) == "function" then log_fn = ctx.log end
  if not resolve_memory_api() then
    log("BizHawk memory API unavailable — module idle")
    ADDRESSES_VERIFIED = false
    return
  end
  local cfg = (ctx and ctx.config) or {}
  load_locations(cfg.locations)
  local n = 0; for _ in pairs(LOC) do n = n + 1 end
  log("ready: " .. n .. " location flags (items_handling=0b111; receive_item is a "
      .. "documented no-op pending in-emulator verification)")
end

function M.poll()
  local new = {}
  if not ADDRESSES_VERIFIED then return new end
  if not rom_is_ap() then return new end
  refresh_snapshot()
  if not in_gameplay() then return new end
  for ap_id, ld in pairs(LOC) do
    if not reported[ap_id] and wanted(ap_id) and location_checked(ld[1], ld[2]) then
      reported[ap_id] = true
      new[#new + 1] = ap_id
    end
  end
  return new
end

function M.is_goal_complete()
  if not ADDRESSES_VERIFIED or not rom_is_ap() then return false end
  refresh_snapshot()
  if not validation_ok() then return false end
  -- Sigma defeated: defeated_bosses[0x17] != 0 (the "Defeated Sigma" victory loc).
  local v = snap.bosses[GOAL_BOSS_INDEX]
  return v ~= nil and v ~= 0
end

-- Remote multiworld items: see the file header. items_handling = 0b111 means the
-- mmx2 client owns ALL item delivery — there is no game-self-grant fallback. The
-- delivery path is an intricate, heavily-state-gated set of WRAM writes (weapon/
-- upgrade/tank/enhancement/boss-access arrays + a recv-index handshake + arsenal
-- save/load + EnergyLink/DeathLink/HP-trade). It is the one piece deferred until
-- it can be confirmed in-emulator. No-op (never a wrong write) until then; checks
-- + goal above are fully functional regardless.
function M.receive_item(item_id, meta)
  -- intentionally empty (documented)
end

return M
