-- ═══════════════════════════════════════════════════════════════════════════════
-- Mega Man X.lua — game module for the Archipelago BizHawk connector.
--                 Mega Man X (SNES)
--
-- STATUS: COMMUNITY world. location DETECTION + goal are REAL and SOURCE-DERIVED
-- from the official apworld worlds/mmx (Client.py game_watcher + Locations.py +
-- Levels.py, TheLX5/Archipelago @ branch `mmx`, world_version 1.6.2). The
-- 83-entry location table was GENERATED by JOINING Locations.all_locations
-- (name → AP id) with Levels.location_id_to_level_id (name → [stage, internal_id,
-- data_bit]) — not hand-copied — so every (AP id → internal_id/data_bit) pair is
-- exact. Mock-verified through MoonSharp against synthetic WRAM/CARTROM. Loads
-- crash-free on any ROM; self-disables on a non-AP cartridge.
--
-- SOURCE: https://github.com/TheLX5/Archipelago  (branch `mmx`, worlds/mmx)
--         game string "Mega Man X", patch_suffix ".apmmx", items_handling 0b111.
--
-- MEMORY MODEL (SNI → BizHawk)  — see Research_V2/SNES_BRIDGE_2026-06-12.md
-- ──────────────────────────────────────────────────────────────────────────
--   The mmx client is an SNIClient. Its SNI addresses translate to BizHawk SNES
--   memory domains:
--     SNI WRAM_START(0xF50000)+off → domain "WRAM",    offset off (= $7E0000+off)
--     SNI ROM_START(0x000000)+off  → domain "CARTROM", offset off (raw ROM file
--                                    offset; LoROM. Fallbacks "ROM"/"System Bus")
--   The client reads four contiguous RAM blocks; this module reads the same bytes:
--     • game_data       = snes_read(MMX_RAM = WRAM+0x1EE00, 0x140)   → WRAM
--         game_data[X]            → WRAM 0x1EE00 + X
--     • game_progress   = snes_read(MMX_UPGRADE_DATA = WRAM+0x01F10, 0xF0) → WRAM
--         game_progress[X]        → WRAM 0x01F10 + X
--     • game_state_data = snes_read(MMX_GAME_STATE = WRAM+0x000D1, 0x3)    → WRAM
--         game_state_data[0..2]   → WRAM 0x000D1 / 0x000D2 / 0x000D3
--     • game_settings   = snes_read(MMX_SETTINGS = ROM+0x167C20, 0x20)     → CARTROM
--         game_settings[X]        → CARTROM 0x167C20 + X
--   IDENTITY / VALIDATION (two gates, both mirrored from Client.py):
--     1) ROM header title at CARTROM 0x7FC0 begins with "MMX1" (validate_rom:
--        rom_name[:4] == b"MMX1"). This is baked by the AP basepatch.
--     2) The live AP-validation word game_data[0x13:0x15] (WRAM 0x1EE13/0x1EE14,
--        little-endian) == 0xDEAD (game_watcher's per-frame "ROM properly
--        validated" check). Only a patched-and-running ROM sets this.
--
-- HOW MMX CHECKS WORK (mirrors Client.py game_watcher; per-location internal_id)
--   Each location carries {internal_id, data_bit}:
--     0x000 Boss clear  : game_data[0x80 + data_bit] != 0          (INDEX, not mask)
--     0x001 Maverick    : game_data[0x60 + data_bit] != 0          (stage clear, INDEX)
--     0x002 Heart Tank  : game_data[0x05] & data_bit != 0          (MASK on one byte)
--     0x003 Upgrade     : game_data[0x06] & data_bit != 0          (MASK)
--     0x004 Sub Tank    : game_data[0x06] & data_bit != 0          (MASK; same byte as 003)
--     0x005 Hadouken    : game_data[0x07] != 0                     (data_bit unused)
--     0x007 Intro clear : game_state_data == {0x02,0x00,0x01} AND
--                          game_progress[0x8B] (WRAM 0x01F9B) == 0x04
--     0x020 Pickup      : gated on pickupsanity (game_settings[0x07], CARTROM
--                          0x167C27); game_data[0xC0 + data_bit] != 0  (INDEX)
--
-- WHAT THIS DOES
--   • poll(): the game_watcher location scan above → AP location ids, gated to the
--     slot's server location set and to the in-game state (game_state_data[0]==0x02,
--     i.e. a save is loaded and the player is in the world — game_watcher only
--     reports checks while game_state != 0 and treats state[0]==0x02 as "active").
--   • is_goal_complete(): Sigma defeated — the victory location
--     (Sigma's Fortress Stage 4 - Sigma Defeated) is internal_id 0x000, data_bit
--     0x1F → game_data[0x80 + 0x1F] = game_data[0x9F] (WRAM 0x1EE9F) != 0. The
--     apworld places the locked Victory item there; defeating Sigma is the goal.
--   • receive_item(): NO-OP (documented). items_handling = 0b111 (FULL remote) —
--     the mmx client owns ALL item delivery via an intricate, heavily-state-gated
--     set of WRAM writes (weapon/upgrade/sub-tank/heart-tank/enhancement/boss-
--     access arrays, a recv-index handshake at game_data[0x00:0x02], an SFX strobe,
--     a per-item queue that waits on menu/gameplay/pause/can-move/screen-brightness
--     states, an arsenal save/load round-trip through AP data-storage, plus
--     EnergyLink/DeathLink/SharedDamage). That path is the one piece that needs
--     in-emulator verification before it is wired, so it is left out rather than
--     shipped unverified (a wrong write would corrupt the save / desync recv-index).
--     Checks + goal above are fully functional regardless of this gap.
--
-- MODULE CONTRACT (called by bizhawk_ap_connector.lua)
--   M.init(ctx) / M.poll() -> {ids} / M.is_goal_complete() -> bool /
--   M.receive_item(item_id, meta)
-- ═══════════════════════════════════════════════════════════════════════════════

local M = {}
M.name = "Mega Man X"

local ADDRESSES_VERIFIED = true   -- table generated from worlds/mmx source

-- ── Memory domains ────────────────────────────────────────────────────────────
local WRAM    = "WRAM"
local CARTROM = "CARTROM"     -- SNES cartridge ROM in BizHawk; fallbacks below

-- ── Addresses / constants (worlds/mmx/Client.py module top) ───────────────────
-- Expressed as BizHawk-domain offsets (already net of WRAM_START / ROM_START).
local MMX_RAM_OFF       = 0x1EE00      -- WRAM: base of the 0x140-byte game_data block
local PROGRESS_OFF      = 0x01F10      -- WRAM: base of the 0xF0-byte game_progress block
local GAME_STATE_OFF    = 0x000D1      -- WRAM: game_state_data[0] (then +1, +2)
local SETTINGS_OFF      = 0x167C20     -- CARTROM: base of the 0x20-byte game_settings block
local ROMHASH_OFF       = 0x7FC0       -- CARTROM: ROM-header title; first 4 = "MMX1"

-- game_data[] sub-fields (offsets RELATIVE to MMX_RAM_OFF).
local GD_VALIDATION     = 0x13         -- u16 LE; == 0xDEAD when patched+running
local GD_HEART_TANKS    = 0x05         -- u8 mask: collected heart-tank flags
local GD_UPGRADES       = 0x06         -- u8 mask: collected upgrade/sub-tank flags
local GD_HADOUKEN       = 0x07         -- u8: != 0 once Hadouken collected
local GD_BOSSES_BASE    = 0x80         -- defeated_bosses[]; index by data_bit
local GD_CLEARED_BASE   = 0x60         -- cleared_levels[];  index by data_bit
local GD_PICKUPS_BASE   = 0xC0         -- collected_pickups[]; index by data_bit

-- game_progress[] sub-fields (offsets RELATIVE to PROGRESS_OFF).
local GP_INTRO_DONE     = 0x8B         -- completed_intro_level; == 0x04 on intro clear

-- game_settings[] sub-fields (offsets RELATIVE to SETTINGS_OFF, in CARTROM).
local GS_PICKUPSANITY   = 0x07         -- pickupsanity enabled?

-- Live validation word value.
local VALIDATION_OK     = 0xDEAD

-- Goal: Sigma defeated — boss clear index 0x1F (Sigma's Fortress 4 - Sigma).
local GOAL_BOSS_INDEX   = 0x1F

-- Check-type tags (Client.py game_watcher internal_id values).
local T_BOSS        = 0x000
local T_MAVERICK    = 0x001
local T_HEART_TANK  = 0x002
local T_UPGRADE     = 0x003
local T_SUB_TANK    = 0x004
local T_HADOUKEN    = 0x005
local T_INTRO       = 0x007
local T_PICKUP      = 0x020

-- ── Location table (GENERATED from worlds/mmx Locations.py ⋈ Levels.py) ────────
-- ap_id -> { internal_id, data_bit }. 83 entries. AP ids are absolute
-- location_name_to_id values (STARTING_ID 0xBE0800-based); detection is
-- self-contained (no per-slot base offset needed).
local LOC = {
  [12453888]={0x000,0x00},[12453889]={0x000,0x01},[12453890]={0x000,0x02},[12453891]={0x000,0x03},
  [12453892]={0x000,0x04},[12453893]={0x000,0x05},[12453894]={0x000,0x06},[12453895]={0x000,0x07},
  [12453896]={0x000,0x08},[12453897]={0x000,0x09},[12453898]={0x000,0x0A},[12453899]={0x000,0x0B},
  [12453900]={0x000,0x0C},[12453901]={0x000,0x0D},[12453902]={0x000,0x0E},[12453903]={0x000,0x0F},
  [12453904]={0x000,0x10},[12453905]={0x000,0x11},[12453906]={0x000,0x12},[12453907]={0x000,0x1E},
  [12453908]={0x000,0x13},[12453909]={0x000,0x1F},[12453910]={0x007,0x00},[12453911]={0x000,0x18},
  [12453912]={0x000,0x19},[12453913]={0x000,0x1A},[12453914]={0x000,0x1B},[12453915]={0x000,0x17},
  [12453916]={0x000,0x15},[12453917]={0x000,0x16},[12453918]={0x000,0x1C},[12453919]={0x000,0x1D},
  [12453936]={0x002,0x02},[12453937]={0x004,0x20},[12453938]={0x002,0x01},[12453939]={0x004,0x40},
  [12453940]={0x002,0x40},[12453941]={0x002,0x80},[12453942]={0x002,0x20},[12453943]={0x002,0x08},
  [12453944]={0x002,0x04},[12453945]={0x004,0x10},[12453946]={0x002,0x10},[12453947]={0x004,0x80},
  [12453952]={0x005,0x00},[12453953]={0x003,0x08},[12453954]={0x003,0x04},[12453955]={0x003,0x01},
  [12453956]={0x003,0x02},[12453968]={0x020,0x00},[12453969]={0x020,0x01},[12453970]={0x020,0x05},
  [12453971]={0x020,0x06},[12453972]={0x020,0x07},[12453973]={0x020,0x02},[12453974]={0x020,0x03},
  [12453975]={0x020,0x04},[12453976]={0x020,0x0E},[12453977]={0x020,0x0F},[12453978]={0x020,0x0B},
  [12453979]={0x020,0x0C},[12453980]={0x020,0x0D},[12453983]={0x020,0x08},[12453984]={0x020,0x09},
  [12453985]={0x020,0x0A},[12453986]={0x020,0x13},[12453987]={0x020,0x15},[12453988]={0x020,0x14},
  [12453989]={0x020,0x16},[12453990]={0x020,0x17},[12453991]={0x020,0x18},[12453992]={0x020,0x19},
  [12453993]={0x020,0x1A},[12453994]={0x020,0x12},[12453995]={0x020,0x1B},[12454000]={0x001,0x04},
  [12454001]={0x001,0x0E},[12454002]={0x001,0x0A},[12454003]={0x001,0x00},[12454004]={0x001,0x0C},
  [12454005]={0x001,0x02},[12454006]={0x001,0x08},[12454007]={0x001,0x06},
}

-- ── Internal state ────────────────────────────────────────────────────────────
local reported         = {}     -- ap_id -> true once returned from poll()
local server_locations = nil    -- set of ap_ids the server expects (nil = all)
local rom_ok           = nil    -- cached "MMX1" header result
local mem              = {}
local log_fn           = nil

-- ── Logging ───────────────────────────────────────────────────────────────────
local function log(msg)
  if log_fn then pcall(log_fn, "[mmx] " .. tostring(msg)) end
end

-- ── Memory API (resolved at init; 2-arg domain form + current-domain fallback) ─
local function resolve_memory_api()
  if not memory then return false end
  mem.read_u8  = memory.read_u8     or memory.readbyte
  mem.read_u16 = memory.read_u16_le or memory.readword
  return mem.read_u8 ~= nil
end

local function rd(fn, addr, domain)
  if not fn then return nil end
  local ok, v = pcall(fn, addr, domain)
  if ok and type(v) == "number" then return v end
  ok, v = pcall(fn, addr)                       -- older API: current domain
  if ok and type(v) == "number" then return v end
  return nil
end

local function read_wram_u8(off)   return rd(mem.read_u8,  off, WRAM) end
local function read_wram_u16(off)  return rd(mem.read_u16, off, WRAM) end

-- CARTROM reads with "ROM" / "System Bus" domain-name fallbacks (cores vary;
-- the raw-file-offset CARTROM/ROM form is what every SNES BizHawk core exposes).
local function read_cartrom_u8(off)
  local ok, v = pcall(mem.read_u8, off, CARTROM)
  if ok and type(v) == "number" then return v end
  ok, v = pcall(mem.read_u8, off, "ROM")
  if ok and type(v) == "number" then return v end
  return nil
end

local function bit_and(a, b)
  -- 8/16-bit safe AND without the bit library (cores vary).
  local res, bitval = 0, 1
  while a > 0 and b > 0 do
    if a % 2 == 1 and b % 2 == 1 then res = res + bitval end
    a = math.floor(a / 2); b = math.floor(b / 2); bitval = bitval * 2
  end
  return res
end

-- ── ROM identity: the SNES header title starts with "MMX1" (validate_rom) ──────
local function rom_is_ap()
  if rom_ok ~= nil then return rom_ok end
  local sig = "MMX1"
  for i = 1, #sig do
    local b = read_cartrom_u8(ROMHASH_OFF + i - 1)
    if b == nil then return false end          -- not readable yet; retry next poll
    if b ~= string.byte(sig, i) then
      rom_ok = false
      log("non-MMX1 ROM (no 'MMX1' header) — detection idle, no reports")
      return false
    end
  end
  rom_ok = true
  log("MMX ROM verified ('MMX1' header title present)")
  return true
end

-- ── Multiworld context ────────────────────────────────────────────────────────
local function load_locations(ids)
  if type(ids) ~= "table" then return end
  server_locations = {}
  local n = 0
  for _, id in ipairs(ids) do
    local v = tonumber(id)
    if v then server_locations[v] = true; n = n + 1 end
  end
  log("server location set: " .. n .. " ids")
end

local function wanted(ap_id)
  if server_locations == nil then return true end   -- no set provided → report all
  return server_locations[ap_id] == true
end

-- ── Per-poll snapshots (read once per poll, matching game_watcher) ────────────
local snap = {}     -- the four RAM blocks the client reads, refreshed each poll

local function read_region_wram(off, len)
  local t = {}
  for i = 0, len - 1 do t[i] = read_wram_u8(off + i) end
  return t
end

local function refresh_snapshot()
  -- game_data (0x140), game_progress (0xF0), game_state_data (0x3) from WRAM.
  snap.game_data     = read_region_wram(MMX_RAM_OFF,    0x140)
  snap.game_progress = read_region_wram(PROGRESS_OFF,   0xF0)
  snap.state0 = read_wram_u8(GAME_STATE_OFF)
  snap.state1 = read_wram_u8(GAME_STATE_OFF + 1)
  snap.state2 = read_wram_u8(GAME_STATE_OFF + 2)
  -- pickupsanity gate lives in CARTROM (per-seed-baked settings block).
  snap.pickupsanity = (read_cartrom_u8(SETTINGS_OFF + GS_PICKUPSANITY) or 0) ~= 0
end

local function gd(off)  -- game_data byte by relative offset
  return snap.game_data[off]
end

-- Live AP-validation word == 0xDEAD (game_watcher's per-frame gate).
local function validation_ok()
  local lo = snap.game_data[GD_VALIDATION]
  local hi = snap.game_data[GD_VALIDATION + 1]
  if lo == nil or hi == nil then return false end
  return (lo + hi * 256) == VALIDATION_OK
end

-- ── One location's "checked?" test (mirrors game_watcher per internal_id) ─────
local function location_checked(internal_id, data_bit)
  if internal_id == T_BOSS then
    local v = gd(GD_BOSSES_BASE + data_bit)        -- defeated_bosses[data_bit] != 0
    return v ~= nil and v ~= 0
  elseif internal_id == T_MAVERICK then
    local v = gd(GD_CLEARED_BASE + data_bit)       -- cleared_levels[data_bit] != 0
    return v ~= nil and v ~= 0
  elseif internal_id == T_HEART_TANK then
    local v = gd(GD_HEART_TANKS)                    -- collected_heart_tanks & data_bit
    return v ~= nil and bit_and(v, data_bit) ~= 0
  elseif internal_id == T_UPGRADE or internal_id == T_SUB_TANK then
    local v = gd(GD_UPGRADES)                       -- collected_upgrades & data_bit
    return v ~= nil and bit_and(v, data_bit) ~= 0
  elseif internal_id == T_HADOUKEN then
    local v = gd(GD_HADOUKEN)                       -- collected_hadouken != 0
    return v ~= nil and v ~= 0
  elseif internal_id == T_INTRO then
    -- game_state_data == b'\x02\x00\x01' and game_progress[0x8B] == 0x04
    if snap.state0 ~= 0x02 or snap.state1 ~= 0x00 or snap.state2 ~= 0x01 then return false end
    local p = snap.game_progress[GP_INTRO_DONE]
    return p ~= nil and p == 0x04
  elseif internal_id == T_PICKUP then
    if not snap.pickupsanity then return false end
    local v = gd(GD_PICKUPS_BASE + data_bit)        -- collected_pickups[data_bit] != 0
    return v ~= nil and v ~= 0
  end
  return false
end

-- ── Detection gate ────────────────────────────────────────────────────────────
-- game_watcher bails when game_state (game_state_data[0]) == 0 (title/no save)
-- and only commits checks while state[0] == 0x02 (in the world). We also require
-- the live 0xDEAD validation word so a non-AP / un-booted ROM never reports.
local function in_gameplay()
  if not validation_ok() then return false end
  return snap.state0 ~= nil and snap.state0 == 0x02
end

-- ── Module contract ───────────────────────────────────────────────────────────
function M.init(ctx)
  if ctx and type(ctx.log) == "function" then log_fn = ctx.log end
  if not resolve_memory_api() then
    log("BizHawk memory API unavailable — module idle")
    ADDRESSES_VERIFIED = false
    return
  end
  local cfg = (ctx and ctx.config) or {}
  load_locations(cfg.locations)
  local n = 0; for _ in pairs(LOC) do n = n + 1 end
  log("ready: " .. n .. " location flags (items_handling=0b111; receive_item is a "
      .. "documented no-op pending in-emulator verification)")
end

function M.poll()
  local new = {}
  if not ADDRESSES_VERIFIED then return new end
  if not rom_is_ap() then return new end
  refresh_snapshot()
  if not in_gameplay() then return new end
  for ap_id, ld in pairs(LOC) do
    if not reported[ap_id] and wanted(ap_id) and location_checked(ld[1], ld[2]) then
      reported[ap_id] = true
      new[#new + 1] = ap_id
    end
  end
  return new
end

function M.is_goal_complete()
  if not ADDRESSES_VERIFIED or not rom_is_ap() then return false end
  refresh_snapshot()
  if not validation_ok() then return false end
  -- Sigma defeated: defeated_bosses[0x1F] != 0.
  local v = gd(GD_BOSSES_BASE + GOAL_BOSS_INDEX)
  return v ~= nil and v ~= 0
end

-- Remote multiworld items: see the file header. items_handling = 0b111 means the
-- mmx client owns ALL item delivery — there is no game-self-grant fallback. The
-- delivery path is an intricate, heavily-state-gated set of WRAM writes (weapon/
-- upgrade/tank/enhancement/boss-access arrays + a recv-index handshake + arsenal
-- save/load + EnergyLink/DeathLink/SharedDamage). It is the one piece deferred
-- until it can be confirmed in-emulator. No-op (never a wrong write) until then;
-- checks + goal above are fully functional regardless.
function M.receive_item(item_id, meta)
  -- intentionally empty (documented)
end

return M
