-- ═══════════════════════════════════════════════════════════════════════════════
-- Mega Man X3.lua — game module for the Archipelago BizHawk connector.
--                   Mega Man X3 (SNES)
--
-- STATUS: COMMUNITY world. location DETECTION + goal are REAL and SOURCE-DERIVED
-- from the official apworld worlds/mmx3 (Client.py game_watcher + Locations.py +
-- Levels.py, TheLX5/Archipelago @ branch `mmx3-main`, world_version 1.5.2). The
-- 121-entry location table was GENERATED by JOINING Locations.all_locations
-- (name → AP id) with Levels.location_id_to_level_id (name → [level_id,
-- internal_id, data_bit]) — not hand-copied — so every (AP id → internal_id/
-- data_bit) pair is exact (121/121 names matched, 0 mismatches). Mock-verified
-- through MoonSharp against synthetic WRAM/CARTROM. Loads crash-free on any ROM;
-- self-disables on a non-AP cartridge.
--
-- SOURCE: https://github.com/TheLX5/Archipelago  (branch `mmx3-main`, worlds/mmx3)
--         game string "Mega Man X3", patch_suffix ".apmmx3", items_handling 0b111.
--
-- MEMORY MODEL (SNI → BizHawk)  — see Research_V2/SNES_BRIDGE_2026-06-12.md
-- ──────────────────────────────────────────────────────────────────────────
--   The mmx3 client is an SNIClient. Its SNI addresses translate to BizHawk SNES
--   memory domains:
--     SNI WRAM_START(0xF50000)+off → domain "WRAM",    offset off (= $7E0000+off)
--     SNI ROM_START(0x000000)+off  → domain "CARTROM", offset off (raw ROM file
--                                    offset; LoROM. Fallbacks "ROM"/"System Bus")
--   This module reads the same WRAM blocks the client's game_watcher reads:
--     • game_state       = WRAM 0x000D0   (1 byte)
--     • menu_state       = WRAM 0x000D1   (1 byte)
--     • gameplay_state   = WRAM 0x000D2   (1 byte)
--     • validation       = WRAM 0x0F43D   (u16 LE; == 0xDEAD when patched+running)
--     • bit_byte_vile    = WRAM 0x01FD8   (1 byte)
--     • cleared_levels   = WRAM 0x0F400   (0x20 bytes; indexed by data_bit)
--     • defeated_bosses  = WRAM 0x0F440   (0x20 bytes; indexed by internal_id&0x1F)
--     • victory          = WRAM 0x0F46B   (1 byte; != 0 ⇒ goal reached)
--     • heart_tanks      = WRAM 0x0F462   (1 byte mask)
--     • upgrades(armor)  = WRAM 0x0F463   (1 byte mask: sub-tanks + armor upgrades)
--     • ride_chips       = WRAM 0x0F464   (1 byte mask: ride armors + chips)
--     • collected_pickups= WRAM 0x0F480   (0x40 bytes; indexed by internal_id&0x3F)
--   Pickupsanity gate lives in CARTROM (per-seed-baked):
--     • pickupsanity     = CARTROM 0x17FFE7 (!= 0 ⇒ pickup checks active)
--   IDENTITY / VALIDATION (two gates, both mirrored from Client.py):
--     1) ROM header title at CARTROM 0x7FC0 begins with "MMX3" (validate_rom:
--        rom_name[:4] == b"MMX3"). This is baked by the AP basepatch.
--     2) The live AP-validation word at WRAM 0x0F43D (little-endian) == 0xDEAD
--        (game_watcher's per-frame "ROM properly validated" check). Only a
--        patched-and-running ROM sets this.
--
-- HOW MMX3 CHECKS WORK (mirrors Client.py game_watcher; per-location internal_id)
--   Each location carries [level_id, internal_id, data_bit]. game_watcher decodes
--   the internal_id (note: low values are EXACT matches, 0x1xx/0x2xx/0x3xx are
--   RANGE checks — same order as the source if/elif chain):
--     internal_id == 0x02 Heart Tank : bit = 1 << (level_id-1); heart_tanks & bit
--     internal_id == 0x03 Sub Tank   : upgrades(armor) & data_bit
--     internal_id == 0x04 Upgrade    : upgrades(armor) & data_bit
--     internal_id == 0x05 Ride Armor : ride_chips & data_bit
--     internal_id == 0x06 Chip       : ride_chips & data_bit
--     internal_id == 0x09 Vile       : bit_byte_vile & 0x30
--     internal_id == 0x0A Byte       : bit_byte_vile & 0x0C
--     internal_id == 0x0B Bit        : bit_byte_vile & 0x03
--     internal_id == 0x0E Victory    : victory != 0
--     internal_id >= 0x300 Medal     : cleared_levels[data_bit]      != 0
--     internal_id >= 0x200 Boss      : defeated_bosses[internal_id & 0x1F] != 0
--     internal_id >= 0x100 Pickup    : (pickupsanity) collected_pickups[internal_id & 0x3F] != 0
--
-- WHAT THIS DOES
--   • poll(): the game_watcher location scan above → AP location ids, gated to the
--     slot's server location set and to the in-game state. game_watcher only
--     commits checks while game_state (WRAM 0x000D0) == 0x02 (a save is loaded and
--     the player is in the world); we require that plus the live 0xDEAD word.
--   • is_goal_complete(): Victory — the apworld places the locked Victory item at
--     the victory location (internal_id 0x0E). game_watcher reports the goal from
--     the WRAM victory flag at 0x0F46B (MMX3_VICTORY) != 0. Defeating Dr. Doppler
--     and reaching the ending sets it.
--   • receive_item(): NO-OP (documented). items_handling = 0b111 (FULL remote) —
--     the mmx3 client owns ALL item delivery via an intricate, heavily-state-gated
--     set of WRAM writes (weapon/upgrade/sub-tank/heart-tank/ride-armor/chip/
--     boss-access arrays, a recv-index handshake at MMX3_RECV_INDEX, an SFX strobe,
--     a per-item queue that waits on menu/gameplay/pause/can-move/screen-brightness/
--     frozen-systems/ride-armor states, an arsenal save/load round-trip through AP
--     data-storage, plus EnergyLink/DeathLink/HP-trade). That path is the one piece
--     that needs in-emulator verification before it is wired, so it is left out
--     rather than shipped unverified (a wrong write would corrupt the save / desync
--     recv-index). Checks + goal above are fully functional regardless of this gap.
--
-- MODULE CONTRACT (called by bizhawk_ap_connector.lua)
--   M.init(ctx) / M.poll() -> {ids} / M.is_goal_complete() -> bool /
--   M.receive_item(item_id, meta)
-- ═══════════════════════════════════════════════════════════════════════════════

local M = {}
M.name = "Mega Man X3"

local ADDRESSES_VERIFIED = true   -- table generated from worlds/mmx3 source

-- ── Memory domains ────────────────────────────────────────────────────────────
local WRAM    = "WRAM"
local CARTROM = "CARTROM"     -- SNES cartridge ROM in BizHawk; fallbacks below

-- ── Addresses / constants (worlds/mmx3/Client.py module top) ──────────────────
-- Expressed as BizHawk-domain offsets (already net of WRAM_START / ROM_START).
-- WRAM offsets (= SNI addr − 0xF50000):
local GAME_STATE_OFF     = 0x000D0     -- game_state[0]  (0x02 == in world)
local MENU_STATE_OFF     = 0x000D1     -- menu_state[0]
local GAMEPLAY_STATE_OFF = 0x000D2     -- gameplay_state[0]
local VALIDATION_OFF     = 0x0F43D     -- u16 LE; == 0xDEAD when patched+running
local BIT_BYTE_VILE_OFF  = 0x01FD8     -- bit/byte/vile defeat flags (one byte)
local CLEARED_BASE_OFF   = 0x0F400     -- cleared_levels[]  (0x20); index by data_bit
local BOSSES_BASE_OFF    = 0x0F440     -- defeated_bosses[] (0x20); index iid&0x1F
local VICTORY_OFF        = 0x0F46B     -- victory flag; != 0 ⇒ goal
local HEART_TANKS_OFF    = 0x0F462     -- collected heart-tank mask
local UPGRADES_OFF       = 0x0F463     -- collected armor/sub-tank mask
local RIDE_CHIPS_OFF     = 0x0F464     -- collected ride-armor/chip mask
local PICKUPS_BASE_OFF   = 0x0F480     -- collected_pickups[] (0x40); index iid&0x3F

-- CARTROM offsets (= SNI addr, ROM_START == 0):
local PICKUPSANITY_OFF   = 0x17FFE7    -- pickupsanity active? (per-seed-baked)
local ROMHASH_OFF        = 0x7FC0      -- ROM-header title; first 4 = "MMX3"

-- Live validation word value.
local VALIDATION_OK      = 0xDEAD

-- Goal: Victory flag (MMX3_VICTORY) != 0.  (victory location internal_id 0x0E.)

-- Check-type tags (Client.py game_watcher internal_id decode — exact-match group).
local T_HEART_TANK  = 0x002
local T_SUB_TANK    = 0x003
local T_UPGRADE     = 0x004
local T_RIDE_ARMOR  = 0x005
local T_CHIP        = 0x006
local T_VILE        = 0x009
local T_BYTE        = 0x00A
local T_BIT         = 0x00B
local T_VICTORY     = 0x00E

-- ── Location table (GENERATED from worlds/mmx3 Locations.py ⋈ Levels.py) ───────
-- ap_id -> { level_id, internal_id, data_bit }. 121 entries. AP ids are absolute
-- location_name_to_id values (starting_id 0xBE0000-based); detection is
-- self-contained (no per-slot base offset needed).
local LOC = {
  [12451840]={0x00,0x200,0x00},[12451841]={0x00,0x201,0x00},[12451842]={0x02,0x204,0x00},
  [12451843]={0x04,0x206,0x00},[12451844]={0x04,0x207,0x00},[12451845]={0x07,0x20A,0x00},
  [12451846]={0x07,0x20B,0x00},[12451847]={0x05,0x208,0x00},[12451848]={0x06,0x209,0x00},
  [12451849]={0x08,0x20C,0x00},[12451850]={0x08,0x20D,0x00},[12451851]={0x03,0x205,0x00},
  [12451852]={0x01,0x202,0x00},[12451853]={0x01,0x203,0x00},[12451854]={0x0A,0x20E,0x00},
  [12451855]={0x0A,0x20F,0x00},[12451856]={0x0B,0x210,0x00},[12451858]={0x0C,0x212,0x00},
  [12451859]={0x0C,0x213,0x00},[12451860]={0x0C,0x214,0x00},[12451861]={0x0C,0x215,0x00},
  [12451862]={0x0C,0x216,0x00},[12451863]={0x0C,0x217,0x00},[12451864]={0x0C,0x218,0x00},
  [12451865]={0x0C,0x219,0x00},[12451866]={0x0C,0x21A,0x00},[12451868]={0x0C,0x00E,0x00},
  [12451869]={0x09,0x009,0x00},[12451870]={0xFF,0x00B,0x00},[12451871]={0xFF,0x00A,0x00},
  [12451872]={0x02,0x002,0x02},[12451873]={0x02,0x003,0x10},[12451874]={0x04,0x002,0x08},
  [12451875]={0x07,0x002,0x40},[12451876]={0x07,0x003,0x40},[12451877]={0x05,0x002,0x10},
  [12451878]={0x05,0x003,0x20},[12451879]={0x06,0x002,0x20},[12451880]={0x08,0x002,0x80},
  [12451881]={0x08,0x003,0x80},[12451882]={0x03,0x002,0x04},[12451883]={0x01,0x002,0x01},
  [12451884]={0x02,0x004,0x08},[12451885]={0x04,0x006,0x80},[12451886]={0x07,0x004,0x01},
  [12451887]={0x05,0x004,0x04},[12451888]={0x06,0x006,0x40},[12451889]={0x08,0x004,0x02},
  [12451890]={0x03,0x006,0x20},[12451891]={0x01,0x006,0x10},[12451894]={0x04,0x005,0x02},
  [12451895]={0x06,0x005,0x04},[12451896]={0x03,0x005,0x08},[12451897]={0x01,0x005,0x01},
  [12451904]={0x00,0x100,0x00},[12451905]={0x00,0x101,0x00},[12451906]={0x02,0x104,0x00},
  [12451907]={0x02,0x105,0x00},[12451908]={0x02,0x106,0x00},[12451909]={0x02,0x107,0x00},
  [12451910]={0x02,0x108,0x00},[12451911]={0x04,0x112,0x00},[12451912]={0x04,0x113,0x00},
  [12451913]={0x04,0x114,0x00},[12451914]={0x05,0x118,0x00},[12451915]={0x05,0x119,0x00},
  [12451916]={0x05,0x11B,0x00},[12451917]={0x05,0x115,0x00},[12451918]={0x05,0x116,0x00},
  [12451919]={0x05,0x117,0x00},[12451920]={0x05,0x11A,0x00},[12451921]={0x05,0x11C,0x00},
  [12451922]={0x06,0x124,0x00},[12451923]={0x06,0x125,0x00},[12451924]={0x06,0x121,0x00},
  [12451925]={0x06,0x11D,0x00},[12451926]={0x06,0x11E,0x00},[12451927]={0x06,0x11F,0x00},
  [12451928]={0x06,0x120,0x00},[12451929]={0x06,0x122,0x00},[12451930]={0x06,0x123,0x00},
  [12451931]={0x08,0x128,0x00},[12451932]={0x08,0x129,0x00},[12451933]={0x08,0x12A,0x00},
  [12451934]={0x03,0x10E,0x00},[12451935]={0x03,0x10B,0x00},[12451936]={0x03,0x110,0x00},
  [12451937]={0x03,0x109,0x00},[12451938]={0x03,0x10A,0x00},[12451939]={0x03,0x10C,0x00},
  [12451940]={0x03,0x10D,0x00},[12451941]={0x03,0x10F,0x00},[12451942]={0x03,0x111,0x00},
  [12451943]={0x01,0x102,0x00},[12451944]={0x01,0x103,0x00},[12451945]={0x0A,0x137,0x00},
  [12451946]={0x0A,0x136,0x00},[12451947]={0x0A,0x138,0x00},[12451948]={0x0C,0x139,0x00},
  [12451949]={0x09,0x12F,0x00},[12451950]={0x09,0x12B,0x00},[12451951]={0x09,0x12C,0x00},
  [12451952]={0x09,0x12D,0x00},[12451953]={0x09,0x12E,0x00},[12451954]={0x09,0x130,0x00},
  [12451955]={0x09,0x131,0x00},[12451956]={0x09,0x132,0x00},[12451957]={0x09,0x134,0x00},
  [12451958]={0x09,0x135,0x00},[12451959]={0x09,0x133,0x00},[12451960]={0x07,0x126,0x00},
  [12451961]={0x07,0x127,0x00},[12451968]={0x02,0x302,0x0C},[12451969]={0x04,0x306,0x00},
  [12451970]={0x07,0x30C,0x0E},[12451971]={0x05,0x308,0x04},[12451972]={0x06,0x30A,0x06},
  [12451973]={0x08,0x30E,0x08},[12451974]={0x03,0x304,0x0A},[12451975]={0x01,0x300,0x02},
  [12451976]={0x01,0x312,0x1E},
}

-- ── Internal state ────────────────────────────────────────────────────────────
local reported         = {}     -- ap_id -> true once returned from poll()
local server_locations = nil    -- set of ap_ids the server expects (nil = all)
local rom_ok           = nil    -- cached "MMX3" header result
local mem              = {}
local log_fn           = nil

-- ── Logging ───────────────────────────────────────────────────────────────────
local function log(msg)
  if log_fn then pcall(log_fn, "[mmx3] " .. tostring(msg)) end
end

-- ── Memory API (resolved at init; 2-arg domain form + current-domain fallback) ─
local function resolve_memory_api()
  if not memory then return false end
  mem.read_u8  = memory.read_u8     or memory.readbyte
  mem.read_u16 = memory.read_u16_le or memory.readword
  return mem.read_u8 ~= nil
end

local function rd(fn, addr, domain)
  if not fn then return nil end
  local ok, v = pcall(fn, addr, domain)
  if ok and type(v) == "number" then return v end
  ok, v = pcall(fn, addr)                       -- older API: current domain
  if ok and type(v) == "number" then return v end
  return nil
end

local function read_wram_u8(off)   return rd(mem.read_u8,  off, WRAM) end
local function read_wram_u16(off)  return rd(mem.read_u16, off, WRAM) end

-- CARTROM reads with "ROM" / "System Bus" domain-name fallbacks (cores vary;
-- the raw-file-offset CARTROM/ROM form is what every SNES BizHawk core exposes).
local function read_cartrom_u8(off)
  local ok, v = pcall(mem.read_u8, off, CARTROM)
  if ok and type(v) == "number" then return v end
  ok, v = pcall(mem.read_u8, off, "ROM")
  if ok and type(v) == "number" then return v end
  return nil
end

local function bit_and(a, b)
  -- 8/16-bit safe AND without the bit library (cores vary).
  local res, bitval = 0, 1
  while a > 0 and b > 0 do
    if a % 2 == 1 and b % 2 == 1 then res = res + bitval end
    a = math.floor(a / 2); b = math.floor(b / 2); bitval = bitval * 2
  end
  return res
end

-- ── ROM identity: the SNES header title starts with "MMX3" (validate_rom) ──────
local function rom_is_ap()
  if rom_ok ~= nil then return rom_ok end
  local sig = "MMX3"
  for i = 1, #sig do
    local b = read_cartrom_u8(ROMHASH_OFF + i - 1)
    if b == nil then return false end          -- not readable yet; retry next poll
    if b ~= string.byte(sig, i) then
      rom_ok = false
      log("non-MMX3 ROM (no 'MMX3' header) — detection idle, no reports")
      return false
    end
  end
  rom_ok = true
  log("MMX3 ROM verified ('MMX3' header title present)")
  return true
end

-- ── Multiworld context ────────────────────────────────────────────────────────
local function load_locations(ids)
  if type(ids) ~= "table" then return end
  server_locations = {}
  local n = 0
  for _, id in ipairs(ids) do
    local v = tonumber(id)
    if v then server_locations[v] = true; n = n + 1 end
  end
  log("server location set: " .. n .. " ids")
end

local function wanted(ap_id)
  if server_locations == nil then return true end   -- no set provided → report all
  return server_locations[ap_id] == true
end

-- ── Per-poll snapshots (read once per poll, matching game_watcher) ────────────
local snap = {}     -- the RAM blocks the client reads, refreshed each poll

local function read_region_wram(off, len)
  local t = {}
  for i = 0, len - 1 do t[i] = read_wram_u8(off + i) end
  return t
end

local function refresh_snapshot()
  snap.game_state     = read_wram_u8(GAME_STATE_OFF)
  snap.menu_state     = read_wram_u8(MENU_STATE_OFF)
  snap.gameplay_state = read_wram_u8(GAMEPLAY_STATE_OFF)
  snap.validation     = read_wram_u16(VALIDATION_OFF)
  snap.bit_byte_vile  = read_wram_u8(BIT_BYTE_VILE_OFF)
  snap.victory        = read_wram_u8(VICTORY_OFF)
  snap.heart_tanks    = read_wram_u8(HEART_TANKS_OFF)
  snap.upgrades       = read_wram_u8(UPGRADES_OFF)
  snap.ride_chips     = read_wram_u8(RIDE_CHIPS_OFF)
  snap.cleared_levels = read_region_wram(CLEARED_BASE_OFF, 0x20)
  snap.defeated_bosses= read_region_wram(BOSSES_BASE_OFF,  0x20)
  snap.collected_pick = read_region_wram(PICKUPS_BASE_OFF, 0x40)
  -- pickupsanity gate lives in CARTROM (per-seed-baked settings byte).
  snap.pickupsanity   = (read_cartrom_u8(PICKUPSANITY_OFF) or 0) ~= 0
end

-- Live AP-validation word == 0xDEAD (game_watcher's per-frame gate).
local function validation_ok()
  return snap.validation ~= nil and snap.validation == VALIDATION_OK
end

-- ── One location's "checked?" test (mirrors game_watcher per internal_id) ─────
-- Order matters: exact-match low ids first, then the 0x3xx/0x2xx/0x1xx ranges,
-- exactly like the source if/elif chain.
local function location_checked(level_id, internal_id, data_bit)
  if internal_id == T_HEART_TANK then
    -- bit = 1 << (level_id - 1); heart_tanks & bit
    local v = snap.heart_tanks
    if v == nil then return false end
    local bit = 1
    for _ = 2, level_id do bit = bit * 2 end          -- 1 << (level_id-1)
    return bit_and(v, bit) ~= 0
  elseif internal_id == T_SUB_TANK or internal_id == T_UPGRADE then
    local v = snap.upgrades                            -- armor/sub-tank mask
    return v ~= nil and bit_and(v, data_bit) ~= 0
  elseif internal_id == T_RIDE_ARMOR or internal_id == T_CHIP then
    local v = snap.ride_chips                          -- ride-armor/chip mask
    return v ~= nil and bit_and(v, data_bit) ~= 0
  elseif internal_id == T_VILE then
    local v = snap.bit_byte_vile
    return v ~= nil and bit_and(v, 0x30) ~= 0
  elseif internal_id == T_BYTE then
    local v = snap.bit_byte_vile
    return v ~= nil and bit_and(v, 0x0C) ~= 0
  elseif internal_id == T_BIT then
    local v = snap.bit_byte_vile
    return v ~= nil and bit_and(v, 0x03) ~= 0
  elseif internal_id == T_VICTORY then
    return snap.victory ~= nil and snap.victory ~= 0
  elseif internal_id >= 0x300 then
    -- Maverick Medal: cleared_levels[data_bit] != 0
    local v = snap.cleared_levels[data_bit]
    return v ~= nil and v ~= 0
  elseif internal_id >= 0x200 then
    -- Boss clear: defeated_bosses[internal_id & 0x1F] != 0
    local v = snap.defeated_bosses[bit_and(internal_id, 0x1F)]
    return v ~= nil and v ~= 0
  elseif internal_id >= 0x100 then
    -- Pickups: gated on pickupsanity; collected_pickups[internal_id & 0x3F] != 0
    if not snap.pickupsanity then return false end
    local v = snap.collected_pick[bit_and(internal_id, 0x3F)]
    return v ~= nil and v ~= 0
  end
  return false
end

-- ── Detection gate ────────────────────────────────────────────────────────────
-- game_watcher bails when game_state (WRAM 0x000D0) == 0 (title/no save) and only
-- commits checks while game_state == 0x02 (in the world). We also require the live
-- 0xDEAD validation word so a non-AP / un-booted ROM never reports.
local function in_gameplay()
  if not validation_ok() then return false end
  return snap.game_state ~= nil and snap.game_state == 0x02
end

-- ── Module contract ───────────────────────────────────────────────────────────
function M.init(ctx)
  if ctx and type(ctx.log) == "function" then log_fn = ctx.log end
  if not resolve_memory_api() then
    log("BizHawk memory API unavailable — module idle")
    ADDRESSES_VERIFIED = false
    return
  end
  local cfg = (ctx and ctx.config) or {}
  load_locations(cfg.locations)
  local n = 0; for _ in pairs(LOC) do n = n + 1 end
  log("ready: " .. n .. " location flags (items_handling=0b111; receive_item is a "
      .. "documented no-op pending in-emulator verification)")
end

function M.poll()
  local new = {}
  if not ADDRESSES_VERIFIED then return new end
  if not rom_is_ap() then return new end
  refresh_snapshot()
  if not in_gameplay() then return new end
  for ap_id, ld in pairs(LOC) do
    if not reported[ap_id] and wanted(ap_id) and location_checked(ld[1], ld[2], ld[3]) then
      reported[ap_id] = true
      new[#new + 1] = ap_id
    end
  end
  return new
end

function M.is_goal_complete()
  if not ADDRESSES_VERIFIED or not rom_is_ap() then return false end
  refresh_snapshot()
  if not validation_ok() then return false end
  -- Victory flag (MMX3_VICTORY, WRAM 0x0F46B) != 0.
  return snap.victory ~= nil and snap.victory ~= 0
end

-- Remote multiworld items: see the file header. items_handling = 0b111 means the
-- mmx3 client owns ALL item delivery — there is no game-self-grant fallback. The
-- delivery path is an intricate, heavily-state-gated set of WRAM writes (weapon/
-- upgrade/sub-tank/heart-tank/ride-armor/chip/boss-access arrays + a recv-index
-- handshake + arsenal save/load + EnergyLink/DeathLink/HP-trade). It is the one
-- piece deferred until it can be confirmed in-emulator. No-op (never a wrong
-- write) until then; checks + goal above are fully functional regardless.
function M.receive_item(item_id, meta)
  -- intentionally empty (documented)
end

return M
