-- ═══════════════════════════════════════════════════════════════════════════════
-- mmbn3.lua — game module for the Archipelago BizHawk connector.
--             Mega Man Battle Network 3 — Blue Version (GBA)
--
-- STATUS: location DETECTION + goal are REAL and SOURCE-DERIVED from the official
-- AP world worlds/mmbn3 (Locations.py + Rom.py) and its shipped BizHawk bridge
-- (data/lua/connector_mmbn3.lua + MMBN3Client.py, main branch). The 263-entry
-- location table below was GENERATED by parsing Locations.py (every uncommented
-- LocationData row → ap_id / flag_byte / flag_mask), not hand-copied, and the
-- check + goal math replicate the connector's game_watcher byte-for-byte. Loads
-- crash-free on any ROM and self-disables on a non-AP / untrustworthy save.
--
-- SOURCE OF TRUTH
--   world   : https://github.com/ArchipelagoMW/Archipelago/tree/main/worlds/mmbn3
--   client  : https://github.com/ArchipelagoMW/Archipelago/blob/main/MMBN3Client.py
--   bridge  : https://github.com/ArchipelagoMW/Archipelago/blob/main/data/lua/connector_mmbn3.lua
--   game id : "mmbn3"   game string : "MegaMan Battle Network 3"
--
-- MEMORY MODEL (BizHawk GBA — the EXACT bytes the connector reads)
-- ────────────────────────────────────────────────────────────────
--   The MMBN3 connector reads GBA work RAM through the System Bus, where WRAM is
--   mapped at 0x02000000. Every "checked" flag lives in a 0x434-byte block the
--   connector slurps with memory.read_bytes_as_dict(0x02000000, 0x434). A
--   location is checked when:
--       WRAM[flag_byte] & flag_mask ~= 0          (Locations.py / MMBN3Client
--                                                   check_location_packet)
--   We address the SAME bytes via the "EWRAM" domain using EWRAM-relative
--   offsets (off = flag_byte - 0x02000000), so the table is host-portable and
--   matches the launcher's memory.read_u8(addr, "EWRAM") API exactly. Offsets
--   span 0x05F .. 0x433 — all inside that block.
--
--   CANARY GATE (connector check_all_locations / is_game_complete): WRAM byte
--   0x020001A9 ("canary") is an intentionally-unused flag. When it reads 0xFF
--   the save RAM is untrustworthy (mid-load / title demo) and the connector
--   sends NO checks. We replicate that exactly — it is the connector's own
--   in-game gate, so a title screen never reports a check.
--
-- GOAL (connector is_game_complete, line ~112)
--   WRAM 0x02000433 & 0x01  ("Alpha defeated"), gated by: canary ~= 0xFF AND
--   NOT on the title/full-screen-menu (0x020097F8 & 0x04 == 0 ⇒ on title), and
--   latched once true. Mirrors the connector, which also latches game_complete.
--   The world places the "Victory" event at the Alpha_Defeated location and its
--   completion_condition is state.has(Victory) — i.e. defeating Alpha.
--
-- ITEM DELIVERY (items_handling = 0b101: remote items + starting inventory)
-- ──────────────────────────────────────────────────────────────────────────
--   MMBN3 is NOT a self-granting ROM — remote items ARE delivered by the
--   connector's SendItemToGame path. That path is intricate and write-heavy:
--   per-item-TYPE RAM writes (chip count arrays at 0x02001F60 with a ROM-side
--   chip-code lookup at 0x08011510, program arrays at 0x02001A80 with a color
--   index, subchips at 0x02001A30, key items at 0x020019C0 with special HP/Reg
--   side-effects, zenny at 0x020018F4, bugfrags at 0x020018F8, progressive
--   Undernet ranks), all sequenced behind an "is itemable?" state machine
--   (not in menu / transition / dialog / battle / title) and a received-item
--   index handshake stored in WRAM at 0x020000AE. Getting any of the array
--   strides, code-index lookups, or the itemable gate wrong corrupts the
--   player's save. Per the launcher's port policy that one piece is the part
--   that must be confirmed in-emulator before it is wired, so receive_item is
--   intentionally a documented NO-OP here (never a wrong write). Checks + goal
--   are fully functional; a solo or co-op seed reports every check and the goal.
--   See the C# plugin header for the same note.
--
-- MODULE CONTRACT (called by bizhawk_ap_connector.lua)
--   M.init(ctx) / M.poll() -> {ids} / M.is_goal_complete() -> bool /
--   M.receive_item(item_id, meta)
-- ═══════════════════════════════════════════════════════════════════════════════

local M = {}
M.name = "mmbn3"

local ADDRESSES_VERIFIED = true   -- table generated from worlds/mmbn3 source

-- ── Memory domains ────────────────────────────────────────────────────────────
local EWRAM = "EWRAM"

-- ── Addresses / constants (connector_mmbn3.lua, WRAM @ 0x02000000) ────────────
-- All offsets are EWRAM-relative (System-Bus addr 0x020000XX → EWRAM 0xXX).
local FLAGS_BLOCK_LEN   = 0x434       -- bytes the connector reads at 0x02000000
local CANARY_OFF        = 0x1A9       -- EWRAM: 0x020001A9; 0xFF ⇒ RAM untrusted
local CANARY_BAD        = 0xFF
local TITLE_OFF         = 0x97F8       -- EWRAM: 0x020097F8; (&0x04)==0 ⇒ on title
local TITLE_MASK        = 0x04
local GOAL_OFF          = 0x433        -- EWRAM: 0x02000433
local GOAL_MASK         = 0x01         -- Alpha defeated

-- ── Location table (GENERATED from worlds/mmbn3/Locations.py) ─────────────────
-- ap_id -> { ewram_offset, flag_mask }. 263 entries (every uncommented
-- LocationData). Checked when EWRAM[off] & mask ~= 0. (off = flag_byte-0x2000000)
local LOC = {
  [11735040]={0x1D0,0x40},[11735041]={0x1D0,0x80},[11735042]={0x1D1,0x40},[11735043]={0x1D1,0x80},
  [11735044]={0x1D2,0x80},[11735045]={0x1D2,0x40},[11735046]={0x1D8,0x40},[11735047]={0x1D8,0x80},
  [11735048]={0x1D9,0x80},[11735049]={0x1D9,0x40},[11735050]={0x1E0,0x80},[11735051]={0x1E0,0x20},
  [11735052]={0x1E1,0x40},[11735053]={0x1E1,0x80},[11735054]={0x1E8,0x80},[11735055]={0x1E9,0x80},
  [11735056]={0x1E9,0x40},[11735057]={0x1F0,0x80},[11735058]={0x1F0,0x40},[11735059]={0x1F1,0x80},
  [11735060]={0x1F1,0x40},[11735061]={0x1F2,0x40},[11735062]={0x1F2,0x80},[11735063]={0x1F3,0x40},
  [11735064]={0x1F3,0x20},[11735065]={0x1F3,0x80},[11735066]={0x1F4,0x40},[11735067]={0x1F4,0x80},
  [11735068]={0x1F5,0x80},[11735069]={0x1F5,0x20},[11735070]={0x1F5,0x40},[11735071]={0x1F6,0x80},
  [11735072]={0x1F6,0x20},[11735073]={0x1F6,0x40},[11735074]={0x200,0x40},[11735075]={0x200,0x20},
  [11735076]={0x200,0x80},[11735077]={0x201,0x80},[11735078]={0x201,0x20},[11735079]={0x201,0x40},
  [11735080]={0x202,0x80},[11735081]={0x202,0x40},[11735082]={0x202,0x20},[11735083]={0x208,0x2},
  [11735084]={0x208,0x4},[11735085]={0x208,0x1},[11735086]={0x209,0x4},[11735087]={0x209,0x1},
  [11735088]={0x209,0x2},[11735089]={0x210,0x80},[11735090]={0x210,0x20},[11735091]={0x210,0x40},
  [11735092]={0x211,0x40},[11735093]={0x211,0x80},[11735094]={0x211,0x20},[11735095]={0x212,0x10},
  [11735096]={0x212,0x80},[11735097]={0x212,0x40},[11735098]={0x212,0x20},[11735099]={0x213,0x40},
  [11735100]={0x213,0x80},[11735101]={0x213,0x20},[11735102]={0x1EB,0x20},[11735103]={0x218,0x20},
  [11735104]={0x218,0x80},[11735105]={0x218,0x40},[11735106]={0x219,0x20},[11735107]={0x219,0x40},
  [11735108]={0x219,0x80},[11735109]={0x21A,0x80},[11735110]={0x21A,0x40},[11735111]={0x21A,0x20},
  [11735112]={0x21B,0x20},[11735113]={0x21B,0x80},[11735114]={0x21B,0x40},[11735115]={0x21C,0x20},
  [11735116]={0x21C,0x80},[11735117]={0x21C,0x40},[11735118]={0x220,0x10},[11735119]={0x220,0x40},
  [11735120]={0x220,0x20},[11735121]={0x221,0x40},[11735122]={0x221,0x20},[11735123]={0x222,0x40},
  [11735124]={0x222,0x20},[11735125]={0x223,0x40},[11735126]={0x223,0x20},[11735127]={0x240,0x80},
  [11735128]={0x242,0x80},[11735129]={0x244,0x8},[11735130]={0x248,0x8},[11735131]={0x247,0x40},
  [11735132]={0x247,0x80},[11735133]={0x242,0x8},[11735134]={0x242,0x4},[11735135]={0x240,0x8},
  [11735136]={0x241,0x80},[11735137]={0x249,0x8},[11735138]={0x241,0x8},[11735139]={0x248,0x80},
  [11735140]={0x247,0x8},[11735141]={0x24B,0x20},[11735142]={0x246,0x8},[11735143]={0x24B,0x80},
  [11735144]={0x249,0x80},[11735145]={0x245,0x8},[11735146]={0x245,0x80},[11735147]={0x246,0x80},
  [11735148]={0x243,0x80},[11735149]={0x243,0x8},[11735150]={0x244,0x40},[11735151]={0x24B,0x2},
  [11735152]={0x24B,0x8},[11735153]={0x24A,0x80},[11735154]={0x239,0x80},[11735155]={0x23B,0x80},
  [11735156]={0x23B,0x40},[11735157]={0x23A,0x40},[11735158]={0x23A,0x80},[11735159]={0x23C,0x80},
  [11735160]={0x1F6,0x1},[11735161]={0x208,0x80},[11735162]={0x208,0x40},[11735163]={0x208,0x20},
  [11735164]={0x209,0x20},[11735165]={0x209,0x80},[11735166]={0x209,0x40},[11735172]={0x1D0,0x20},
  [11735173]={0x1E0,0x40},[11735174]={0x1E8,0x40},[11735175]={0x1F6,0x10},[11735176]={0x239,0x40},
  [11735177]={0x241,0x4},[11735178]={0x249,0x40},[11735179]={0x244,0x80},[11735180]={0x24B,0x1},
  [11735181]={0x23C,0x40},[11735182]={0x5F,0x4},[11735183]={0x5F,0x2},[11735184]={0x164,0x8},
  [11735185]={0x162,0x10},[11735186]={0x162,0x8},[11735187]={0x163,0x40},[11735188]={0x163,0x10},
  [11735189]={0x162,0x4},[11735190]={0x163,0x4},[11735191]={0x162,0x1},[11735192]={0x164,0x10},
  [11735193]={0x163,0x2},[11735194]={0x164,0x80},[11735195]={0x24D,0x20},[11735196]={0x24D,0x10},
  [11735197]={0x24C,0x1},[11735198]={0x24C,0x40},[11735199]={0x24C,0x8},[11735200]={0x24C,0x80},
  [11735201]={0x24D,0x8},[11735202]={0x161,0x40},[11735203]={0x24C,0x4},[11735204]={0x24D,0x4},
  [11735205]={0x24C,0x2},[11735206]={0x162,0x20},[11735207]={0x160,0x1},[11735208]={0x24E,0x80},
  [11735209]={0x24C,0x20},[11735210]={0x24D,0x80},[11735211]={0x24C,0x10},[11735212]={0x24D,0x40},
  [11735213]={0x24D,0x2},[11735214]={0x161,0x1},[11735215]={0x300,0x8},[11735216]={0x300,0x4},
  [11735217]={0x300,0x2},[11735218]={0x300,0x1},[11735219]={0x301,0x80},[11735220]={0x301,0x40},
  [11735221]={0x301,0x20},[11735222]={0x301,0x10},[11735223]={0x301,0x8},[11735228]={0x301,0x4},
  [11735229]={0x301,0x2},[11735230]={0x301,0x1},[11735231]={0x302,0x80},[11735232]={0x302,0x40},
  [11735233]={0x302,0x20},[11735234]={0x302,0x10},[11735235]={0x24E,0x40},[11735236]={0x188,0x4},
  [11735237]={0x188,0x2},[11735238]={0x188,0x1},[11735239]={0x189,0x80},[11735240]={0x302,0x8},
  [11735241]={0x302,0x4},[11735242]={0x302,0x2},[11735243]={0x302,0x1},[11735244]={0x303,0x80},
  [11735245]={0x430,0x80},[11735246]={0x430,0x40},[11735247]={0x430,0x20},[11735248]={0x430,0x10},
  [11735249]={0x430,0x8},[11735250]={0x430,0x4},[11735251]={0x430,0x2},[11735252]={0x430,0x1},
  [11735253]={0x431,0x80},[11735254]={0x431,0x40},[11735255]={0x431,0x20},[11735256]={0x431,0x10},
  [11735257]={0x431,0x8},[11735258]={0x431,0x4},[11735259]={0x431,0x2},[11735260]={0x431,0x1},
  [11735261]={0x432,0x80},[11735262]={0x432,0x40},[11735263]={0x432,0x20},[11735264]={0x432,0x10},
  [11735265]={0x432,0x8},[11735266]={0x432,0x4},[11735267]={0x432,0x2},[11735268]={0x432,0x1},
  [11735269]={0x433,0x80},[11735270]={0x433,0x40},[11735271]={0x433,0x20},[11735272]={0x433,0x10},
  [11735273]={0x433,0x8},[11735274]={0x433,0x4},[11735275]={0x433,0x2},[11735276]={0x5F,0x8},
  [11735277]={0x249,0x4},[11735278]={0x1C0,0x80},[11735279]={0x1C0,0x40},[11735280]={0x1C0,0x20},
  [11735281]={0x1C0,0x10},[11735282]={0x1C0,0x8},[11735283]={0x1C0,0x4},[11735284]={0x1C0,0x2},
  [11735285]={0x1C0,0x1},[11735286]={0x1C1,0x80},[11735287]={0x1C1,0x40},[11735288]={0x1C1,0x20},
  [11735289]={0x1C1,0x10},[11735290]={0x1C1,0x8},[11735291]={0x1C1,0x4},[11735292]={0x1C1,0x2},
  [11735293]={0x1C1,0x1},[11735294]={0x1C2,0x80},[11735295]={0x1C2,0x40},[11735296]={0x1C2,0x20},
  [11735297]={0x1C2,0x10},[11735298]={0x1C2,0x8},[11735299]={0x1C2,0x4},[11735300]={0x1C2,0x2},
  [11735301]={0x1C2,0x1},[11735302]={0x1C3,0x80},[11735303]={0x1C3,0x40},[11735304]={0x1C3,0x20},
  [11735305]={0x1C3,0x10},[11735306]={0x1C3,0x8},[11735307]={0x1C3,0x4},[11735308]={0x1C3,0x2},
  [11735309]={0x1C3,0x1},[11735310]={0x301,0x1},[11735311]={0x178,0x40},
}

-- ── State ─────────────────────────────────────────────────────────────────────
local reported         = {}     -- ap_id -> true once returned from poll()
local server_locations = nil    -- set of ap_ids the server expects (nil = all)
local goal_latched     = false  -- mirrors the connector's game_complete latch
local mem              = {}
local log_fn           = nil

-- ── Logging ───────────────────────────────────────────────────────────────────
local function log(msg)
  if log_fn then pcall(log_fn, "[mmbn3] " .. tostring(msg)) end
end

-- ── Memory API (resolved at init; 2-arg domain form + current-domain fallback) ─
local function resolve_memory_api()
  if not memory then return false end
  mem.read_u8 = memory.read_u8 or memory.readbyte
  return mem.read_u8 ~= nil
end

local function read_u8(addr, domain)
  if not mem.read_u8 then return nil end
  local ok, v = pcall(mem.read_u8, addr, domain)
  if ok and type(v) == "number" then return v end
  ok, v = pcall(mem.read_u8, addr)            -- older API: current domain
  if ok and type(v) == "number" then return v end
  return nil
end

-- ── Bit helper (pure Lua, no bit library dependency) ──────────────────────────
local function bit_and(a, b)
  local res, bitval = 0, 1
  while a > 0 and b > 0 do
    if a % 2 == 1 and b % 2 == 1 then res = res + bitval end
    a = math.floor(a / 2); b = math.floor(b / 2); bitval = bitval * 2
  end
  return res
end

-- ── Multiworld context ────────────────────────────────────────────────────────
local function load_locations(ids)
  if type(ids) ~= "table" then return end
  server_locations = {}
  local n = 0
  for _, id in ipairs(ids) do
    local v = tonumber(id)
    if v then server_locations[v] = true; n = n + 1 end
  end
  log("server location set: " .. n .. " ids")
end

local function wanted(ap_id)
  if server_locations == nil then return true end
  return server_locations[ap_id] == true
end

-- ── Flag block (read once per poll) ───────────────────────────────────────────
local flags = {}     -- ewram offset -> value, refreshed each poll

local function refresh_flags()
  for off = 0, FLAGS_BLOCK_LEN - 1 do
    flags[off] = read_u8(off, EWRAM)
  end
end

local function flag_set(off, mask)
  local byte = flags[off]
  if byte == nil then return false end
  return bit_and(byte, mask) ~= 0
end

-- ── Detection gate (connector check_all_locations canary guard) ───────────────
-- The connector refuses to send checks when the canary byte reads 0xFF (save RAM
-- not yet trustworthy — covers the title-screen demo and mid-load frames).
local function flags_trustworthy()
  local canary = flags[CANARY_OFF]
  if canary == nil then return false end       -- not readable yet
  return canary ~= CANARY_BAD
end

local function on_title()
  -- is_game_complete: (0x020097F8 & 0x04) == 0 ⇒ on title / full-screen menu.
  local b = read_u8(TITLE_OFF, EWRAM)
  if b == nil then return true end             -- unknown ⇒ treat as title (safe)
  return bit_and(b, TITLE_MASK) == 0
end

-- ── Module contract ───────────────────────────────────────────────────────────
function M.init(ctx)
  if ctx and type(ctx.log) == "function" then log_fn = ctx.log end
  if not resolve_memory_api() then
    log("BizHawk memory API unavailable — module idle")
    ADDRESSES_VERIFIED = false
    return
  end
  local cfg = (ctx and ctx.config) or {}
  load_locations(cfg.locations)
  local n = 0; for _ in pairs(LOC) do n = n + 1 end
  log("ready: " .. n .. " location flags")
end

function M.poll()
  local new = {}
  if not ADDRESSES_VERIFIED then return new end
  refresh_flags()
  if not flags_trustworthy() then return new end   -- canary guard
  for ap_id, entry in pairs(LOC) do
    if not reported[ap_id] and wanted(ap_id) and flag_set(entry[1], entry[2]) then
      reported[ap_id] = true
      new[#new + 1] = ap_id
    end
  end
  return new
end

function M.is_goal_complete()
  if not ADDRESSES_VERIFIED then return false end
  if goal_latched then return true end
  refresh_flags()
  if not flags_trustworthy() then return false end
  if on_title() then return false end
  if flag_set(GOAL_OFF, GOAL_MASK) then
    goal_latched = true
    log("goal reached (Alpha defeated)")
    return true
  end
  return false
end

-- Remote multiworld items: see the file header. items_handling = 0b101, so
-- remote items ARE part of this game — but the connector's SendItemToGame path
-- is intricate, save-mutating, and gated behind an "is itemable?" state machine
-- and a WRAM received-index handshake (0x020000AE). That delivery is the one
-- piece deferred until it can be confirmed in-emulator; applying it wrong would
-- corrupt the save. NO-OP (never a wrong write) until then — checks + goal are
-- fully functional regardless.
function M.receive_item(item_id, meta)
  -- intentionally empty (documented)
end

return M
