-- ═══════════════════════════════════════════════════════════════════════════════
-- pokemon_rb.lua — game module for the Archipelago BizHawk connector.
--                  Pokémon Red & Blue (Game Boy)
--
-- STATUS: location DETECTION + goal are REAL and SOURCE-DERIVED from the official
-- AP world worlds/pokemon_rb (client.py + locations.py + rom.py, main branch). The
-- 709-entry location table was GENERATED by executing the real locations.py and
-- replicating client.py's exact location_map / location_bytes_bits build (NOT
-- hand-copied), so the ap_id → flag mapping is byte-for-byte what the official
-- client uses. Loads crash-free on any cartridge; self-disables on a non-Pokémon
-- ROM (validates the GB header game title, exactly like client.validate_rom).
--
-- MEMORY MODEL (BizHawk GB domains)
-- ──────────────────────────────────
--   The PokemonRBClient (a BizHawkClient) reads work RAM ("WRAM") for all flag
--   arrays and reads the cartridge header ("ROM") only to identify the game.
--   client.py DATA_LOCATIONS (all WRAM unless noted):
--     EventFlag      0x1735, len 0x140    Missable   0x161A, len 0x20
--     Hidden         0x16DE, len 0x0E     Rod        0x1716, len 0x01
--     DexSanityFlag  0x1A71, len 19       GameStatus 0x1A84, len 1
--     ResetCheck     0x0100, len 4        CrashCheck1 0x1731,len 2
--     CrashCheck2    0x1617, len 1        CrashCheck3 0x1A70, len 1
--     CrashCheck4    0x16DD, len 1
--   A location is "checked" when  data[array][byte] & (1 << bit)  is set, where
--   (array, byte, bit) come from the location's flag (byte=flag//8, bit=flag%8;
--   Rod uses byte=0, bit=flag). Two "list" locations need BOTH an EventFlag bit
--   AND a Missable bit set (client.py "list" branch).
--
-- ROM IDENTITY (client.validate_rom): the GB header game title at ROM 0x134 (12
--   bytes) is "POKEMON RED\0" or "POKEMON BLUE". There is no separate AP magic —
--   the patched ROM keeps the original title; the seed name lives at ROM 0xFFDB.
--   We mirror validate_rom: accept either title, otherwise stay idle.
--
-- GOAL (client.py VICTORY): EventFlag byte 280 bit 0 (the Hall-of-Fame event) —
--   `data["EventFlag"][280] & 1`. No check location uses that flag.
--
-- WHAT THIS DOES (mirrors worlds/pokemon_rb/client.py game_watcher)
--   • poll(): read the five flag arrays → AP location ids, gated to the slot's
--     server location set AND to the in-game / not-crashed gate (GameStatus is
--     0x2A or 0xAC, ResetCheck ≠ 0x7FFFFFFF, the four CrashCheck guards) so the
--     title screen / a corrupted frame never reports checks. This is the exact
--     gate client.game_watcher uses before it collects locations.
--   • is_goal_complete(): EventFlag[280] & 1 (the default + only goal).
--   • receive_item(): NO-OP (documented). items_handling = 0b001 — the server
--     sends only THIS slot's own items, and the PATCHED GAME grants its locally
--     found items itself, so a SOLO seed plays fully and every check is reported
--     in a multiworld. Delivering REMOTE items is the client's APItem-byte
--     handshake (write the next item's code to WRAM 0x00FF only while the game
--     has cleared it to 0, tracking the save's own ItemIndex at 0x1A6E); that is
--     a guarded WRAM WRITE that must be confirmed in-emulator before shipping, so
--     it is intentionally left out rather than risk mis-applying an item. The
--     pipe bridge still delivers items launcher-side for games that implement it;
--     here it is the one deferred piece (same posture as cvcotm.lua).
--
-- MODULE CONTRACT (called by bizhawk_ap_connector.lua)
--   M.init(ctx) / M.poll() -> {ids} / M.is_goal_complete() -> bool /
--   M.receive_item(item_id, meta)
-- ═══════════════════════════════════════════════════════════════════════════════

local M = {}
M.name = "pokemon_rb"

local ADDRESSES_VERIFIED = true   -- table generated from worlds/pokemon_rb source

-- ── Memory domains ────────────────────────────────────────────────────────────
local WRAM = "WRAM"
local ROM  = "ROM"

-- ── Flag-array bases + lengths (client.py DATA_LOCATIONS, WRAM) ────────────────
local ARR = {
  -- code 1=EventFlag 2=Missable 3=Hidden 4=Rod 5=DexSanityFlag
  [1] = { base = 0x1735, len = 0x140 },   -- EventFlag
  [2] = { base = 0x161A, len = 0x20  },   -- Missable
  [3] = { base = 0x16DE, len = 0x0E  },   -- Hidden
  [4] = { base = 0x1716, len = 0x01  },   -- Rod
  [5] = { base = 0x1A71, len = 19    },   -- DexSanityFlag
}

-- ── Gate addresses (client.game_watcher) ──────────────────────────────────────
local GAME_STATUS_ADDR = 0x1A84    -- must be 0x2A or 0xAC once a save is loaded
local RESET_BASE       = 0x0100    -- 4 bytes; 0x7FFFFFFF (\xff\xff\xff\x7f) = pre-load
local CRASH1_ADDR      = 0x1731    -- 2 bytes: b0 & 0xF0 == 0 AND b1 == 0
local CRASH2_ADDR      = 0x1617    -- 1 byte: == 0
local CRASH3_ADDR      = 0x1A70    -- 1 byte: <= 10
local CRASH4_ADDR      = 0x16DD    -- 1 byte: <= 3

-- ── ROM identity (client.validate_rom): GB header game title ──────────────────
local ROM_TITLE_ADDR = 0x134
local ROM_TITLE_RED  = "POKEMON RED\0"   -- 12 bytes
local ROM_TITLE_BLUE = "POKEMON BLUE"    -- 12 bytes

-- ── Goal (client.py VICTORY): EventFlag byte 280, bit 0 ───────────────────────
local GOAL_EVENT_BYTE = 280
local GOAL_EVENT_BIT  = 0

-- ── Location table (GENERATED from worlds/pokemon_rb) ─────────────────────────
-- Single-flag locations: ap_id -> packed = arr*1000000 + byte*100 + bit
--   (arr 1=EventFlag 2=Missable 3=Hidden 4=Rod 5=DexSanityFlag). 707 entries.
local LOC = {
  [172000000]=4000003,[172000001]=4000004,[172000002]=4000005,[172000003]=1000001,[172000004]=1000002,[172000005]=1000300,
  [172000006]=1000404,[172000007]=1012000,[172000008]=1000501,[172000009]=1000701,[172000010]=1001000,[172000011]=1012300,
  [172000012]=1001301,[172000013]=1001406,[172000014]=1002400,[172000015]=1002306,[172000016]=1016800,[172000017]=1017104,
  [172000018]=1003700,[172000019]=1014400,[172000020]=1004201,[172000021]=1004406,[172000022]=1018800,[172000023]=1014307,
  [172000024]=1004800,[172000025]=1004904,[172000026]=1004905,[172000027]=1004906,[172000028]=1004907,[172000029]=1006000,
  [172000030]=1005300,[172000031]=1024105,[172000032]=1022307,[172000033]=1015306,[172000034]=1015000,[172000035]=1007100,
  [172000036]=1007500,[172000037]=1027200,[172000038]=1009007,[172000039]=1008300,[172000040]=1010400,[172000041]=1011800,
  [172000042]=1010800,[172000043]=1017506,[172000044]=1017507,[172000045]=2000006,[172000046]=2000301,[172000047]=2000302,
  [172000048]=2000303,[172000049]=2000304,[172000050]=2000306,[172000051]=2000307,[172000052]=2000400,[172000053]=2000405,
  [172000054]=2000406,[172000055]=2000603,[172000056]=2000605,[172000057]=2000606,[172000058]=2000607,[172000059]=2000701,
  [172000060]=2000702,[172000061]=2000703,[172000062]=2000704,[172000063]=2000705,[172000064]=2000706,[172000065]=2000707,
  [172000066]=2000807,[172000067]=2000900,[172000068]=2000901,[172000069]=2001006,[172000070]=2001007,[172000071]=2001100,
  [172000072]=2001101,[172000073]=2001102,[172000074]=2001104,[172000075]=2001105,[172000076]=2001106,[172000077]=2001107,
  [172000078]=2001204,[172000079]=2001205,[172000080]=2001206,[172000081]=2001207,[172000082]=2001300,[172000083]=2001301,
  [172000084]=2001302,[172000085]=2001303,[172000086]=2001304,[172000087]=2001307,[172000088]=2001400,[172000089]=2001402,
  [172000090]=2001403,[172000091]=2001404,[172000092]=2001405,[172000093]=2001406,[172000094]=2001407,[172000095]=2001500,
  [172000096]=2001501,[172000097]=2001503,[172000098]=2001504,[172000099]=2001505,[172000100]=2001506,[172000101]=2001507,
  [172000102]=2001600,[172000103]=2001601,[172000104]=2001602,[172000105]=2001604,[172000106]=2001605,[172000107]=2001606,
  [172000110]=2001800,[172000111]=2001804,[172000112]=2001805,[172000113]=2001806,[172000114]=2001903,[172000115]=2001904,
  [172000116]=2001905,[172000117]=2002001,[172000118]=2002002,[172000119]=2002100,[172000120]=2002101,[172000121]=2002204,
  [172000122]=2002205,[172000123]=2002206,[172000124]=2002303,[172000125]=2002304,[172000126]=2002305,[172000127]=2002306,
  [172000128]=2002307,[172000129]=2002400,[172000130]=2002401,[172000131]=2002402,[172000132]=2002403,[172000133]=2002404,
  [172000134]=2002405,[172000135]=2002406,[172000136]=2002407,[172000137]=2002500,[172000138]=2002501,[172000139]=2002502,
  [172000140]=2002503,[172000141]=2002504,[172000142]=2002505,[172000143]=2002506,[172000144]=2002507,[172000145]=2002600,
  [172000146]=2002602,[172000147]=2002603,[172000148]=2002604,[172000149]=2002605,[172000150]=2002807,[172000151]=2002900,
  [172000152]=2002901,[172000153]=2002902,[172000154]=1027600,[172000155]=1027601,[172000156]=1027602,[172000157]=1027603,
  [172000158]=1027604,[172000159]=1027605,[172000160]=1027606,[172000161]=1027607,[172000162]=3000000,[172000163]=3000001,
  [172000164]=3000002,[172000165]=3000003,[172000166]=3000004,[172000167]=3000005,[172000168]=3000006,[172000169]=3000007,
  [172000170]=3000100,[172000171]=3000101,[172000172]=3000102,[172000173]=3000103,[172000174]=3000104,[172000175]=3000105,
  [172000176]=3000106,[172000177]=3000107,[172000178]=3000201,[172000179]=3000202,[172000180]=3000203,[172000181]=3000204,
  [172000182]=3000205,[172000183]=3000206,[172000184]=3000207,[172000185]=3000300,[172000186]=3000301,[172000187]=3000302,
  [172000188]=3000303,[172000189]=3000304,[172000190]=3000305,[172000191]=3000306,[172000192]=3000307,[172000193]=3000400,
  [172000194]=3000401,[172000195]=3000403,[172000196]=3000404,[172000197]=3000405,[172000198]=3000406,[172000199]=3000407,
  [172000200]=3000500,[172000201]=3000501,[172000202]=3000502,[172000203]=3000503,[172000204]=3000504,[172000205]=3000505,
  [172000206]=3000506,[172000207]=3000507,[172000208]=3000600,[172000209]=3000601,[172000210]=3000602,[172000211]=3000603,
  [172000212]=3000604,[172000213]=3000605,[172000214]=1000700,[172000215]=1004700,[172000216]=1000503,[172000217]=1000307,
  [172000218]=1000502,[172000219]=1000305,[172000220]=1000306,[172000221]=1000505,[172000222]=1000506,[172000223]=1000507,
  [172000224]=1000600,[172000225]=1000601,[172000226]=1000602,[172000227]=1000603,[172000228]=1000606,[172000229]=1000604,
  [172000230]=1000605,[172000231]=1000702,[172000232]=1000704,[172000233]=1000703,[172000234]=1000607,[172000235]=1000800,
  [172000236]=1000707,[172000237]=1000706,[172000238]=1000801,[172000239]=1000802,[172000240]=1000803,[172000241]=1000804,
  [172000242]=1000805,[172000243]=1000807,[172000244]=1000806,[172000245]=1000900,[172000246]=1000901,[172000247]=1000902,
  [172000248]=1000903,[172000249]=1000904,[172000250]=1000905,[172000251]=1001203,[172000252]=1001202,[172000253]=1001200,
  [172000254]=1001201,[172000255]=1001107,[172000256]=1001106,[172000257]=1001104,[172000258]=1001105,[172000259]=1000907,
  [172000260]=1001103,[172000261]=1001102,[172000262]=1001501,[172000263]=1001502,[172000264]=1001405,[172000265]=1001500,
  [172000266]=1001403,[172000267]=1001404,[172000268]=1001401,[172000269]=1001400,[172000270]=1001503,[172000271]=1001504,
  [172000272]=1001306,[172000273]=1001307,[172000274]=1001304,[172000275]=1001305,[172000276]=1001302,[172000277]=1001303,
  [172000278]=1001603,[172000279]=1001604,[172000280]=1001605,[172000281]=1001602,[172000282]=1001606,[172000283]=1001607,
  [172000284]=1001700,[172000285]=1001507,[172000286]=1001506,[172000287]=1001505,[172000288]=1001600,[172000289]=1001703,
  [172000290]=1001702,[172000291]=1001701,[172000292]=1001706,[172000293]=1001804,[172000294]=1001704,[172000295]=1001803,
  [172000296]=1001801,[172000297]=1001705,[172000298]=1001802,[172000299]=1001800,[172000300]=1001707,[172000301]=1001805,
  [172000302]=1001806,[172000303]=1001807,[172000304]=1001901,[172000305]=1001902,[172000306]=1001903,[172000307]=1002106,
  [172000308]=1002105,[172000309]=1002103,[172000310]=1002104,[172000311]=1002006,[172000312]=1002005,[172000313]=1002102,
  [172000314]=1002100,[172000315]=1002101,[172000316]=1002107,[172000317]=1002200,[172000318]=1002201,[172000319]=1002202,
  [172000320]=1002204,[172000321]=1002205,[172000322]=1002206,[172000323]=1002207,[172000324]=1002203,[172000325]=1002300,
  [172000326]=1002407,[172000327]=1002406,[172000328]=1002402,[172000329]=1002405,[172000330]=1002404,[172000331]=1002403,
  [172000332]=1002304,[172000333]=1002305,[172000334]=1002401,[172000335]=1002301,[172000336]=1002500,[172000337]=1002501,
  [172000338]=1002502,[172000339]=1002603,[172000340]=1002602,[172000341]=1002604,[172000342]=1002601,[172000343]=1002600,
  [172000344]=1002507,[172000345]=1002506,[172000346]=1002504,[172000347]=1002505,[172000348]=1002503,[172000349]=1002703,
  [172000350]=1002702,[172000351]=1002701,[172000352]=1002700,[172000353]=1002607,[172000354]=1002606,[172000355]=1002705,
  [172000356]=1002801,[172000357]=1002804,[172000358]=1002707,[172000359]=1002706,[172000360]=1002805,[172000361]=1002800,
  [172000362]=1002802,[172000363]=1002803,[172000364]=1002704,[172000365]=1003004,[172000366]=1003000,[172000367]=1002905,
  [172000368]=1002904,[172000369]=1002807,[172000370]=1002903,[172000371]=1002806,[172000372]=1002900,[172000373]=1002901,
  [172000374]=1002902,[172000375]=1003105,[172000376]=1003201,[172000377]=1003200,[172000378]=1003100,[172000379]=1003007,
  [172000380]=1003107,[172000381]=1003106,[172000382]=1003005,[172000383]=1003104,[172000384]=1003006,[172000385]=1003405,
  [172000386]=1003404,[172000387]=1003305,[172000388]=1003304,[172000389]=1003306,[172000390]=1003400,[172000391]=1003300,
  [172000392]=1003506,[172000393]=1003600,[172000394]=1003406,[172000395]=1003504,[172000396]=1003507,[172000397]=1003502,
  [172000398]=1003505,[172000399]=1003500,[172000400]=1003501,[172000401]=1003503,[172000402]=1003706,[172000403]=1003801,
  [172000404]=1003800,[172000405]=1003707,[172000406]=1003705,[172000407]=1003703,[172000408]=1003704,[172000409]=1000005,
  [172000410]=1000100,[172000411]=1000102,[172000412]=1000007,[172000413]=1000101,[172000414]=1000105,[172000415]=1000104,
  [172000416]=1000103,[172000417]=1003804,[172000418]=1003807,[172000419]=1003802,[172000420]=1003806,[172000421]=1003803,
  [172000422]=1003805,[172000423]=1004000,[172000424]=1003904,[172000425]=1003907,[172000426]=1003902,[172000427]=1003901,
  [172000428]=1003900,[172000429]=1003906,[172000430]=1003903,[172000431]=1003905,[172000432]=1004001,[172000433]=1004002,
  [172000434]=1004007,[172000435]=1004006,[172000436]=1004005,[172000437]=1004004,[172000438]=1004003,[172000439]=1004100,
  [172000440]=1004101,[172000441]=1004105,[172000442]=1004106,[172000443]=1004107,[172000444]=1004102,[172000445]=1004103,
  [172000446]=1004104,[172000447]=1004200,[172000448]=1004301,[172000449]=1004303,[172000450]=1004302,[172000451]=1004300,
  [172000452]=1004205,[172000453]=1004204,[172000454]=1004203,[172000455]=1004202,[172000456]=1004305,[172000457]=1004307,
  [172000458]=1004500,[172000459]=1004501,[172000460]=1004304,[172000461]=1004405,[172000462]=1004306,[172000463]=1004503,
  [172000464]=1004505,[172000465]=1004504,[172000466]=1004506,[172000467]=1004704,[172000468]=1004706,[172000469]=1004705,
  [172000470]=1004702,[172000471]=1004703,[172000472]=1004701,[172000473]=1004807,[172000474]=1004806,[172000475]=1004804,
  [172000476]=1004805,[172000477]=1004803,[172000478]=1004801,[172000479]=1004802,[172000480]=1004902,[172000481]=1004903,
  [172000482]=1005000,[172000483]=1005201,[172000484]=1005200,[172000485]=1005107,[172000486]=1005105,[172000487]=1005104,
  [172000488]=1005106,[172000489]=1005102,[172000490]=1005103,[172000491]=1005101,[172000492]=1005100,[172000493]=1005007,
  [172000494]=1005005,[172000495]=1005006,[172000496]=1005003,[172000497]=1005002,[172000498]=1005001,[172000499]=1005204,
  [172000500]=1005205,[172000501]=1005402,[172000502]=1005404,[172000503]=1005407,[172000504]=1005403,[172000505]=1005506,
  [172000506]=1005505,[172000507]=1005500,[172000508]=1005405,[172000509]=1005406,[172000510]=1000107,[172000511]=1000106,
  [172000512]=1002002,[172000513]=1002001,[172000514]=1002000,[172000515]=1001906,[172000516]=1001907,[172000517]=1001207,
  [172000518]=1001204,[172000519]=1001205,[172000520]=1001206,[172000521]=1000205,[172000522]=1000204,[172000523]=1000203,
  [172000524]=1000202,[172000525]=1004606,[172000526]=1004605,[172000527]=1004604,[172000528]=1004603,[172000529]=1004602,
  [172000530]=1004601,[172000531]=1004600,[172000532]=1021102,[172000533]=1021103,[172000534]=1021104,[172000535]=1005502,
  [172000536]=1005504,[172000537]=1005503,[172000538]=3000606,[172000539]=3000607,[172000540]=3000700,[172000541]=3000701,
  [172000542]=3000702,[172000543]=3000703,[172000544]=3000704,[172000545]=3000705,[172000546]=3000706,[172000547]=3000707,
  [172000548]=3000800,[172000549]=5000000,[172000550]=5000001,[172000551]=5000002,[172000552]=5000003,[172000553]=5000004,
  [172000554]=5000005,[172000555]=5000006,[172000556]=5000007,[172000557]=5000100,[172000558]=5000101,[172000559]=5000102,
  [172000560]=5000103,[172000561]=5000104,[172000562]=5000105,[172000563]=5000106,[172000564]=5000107,[172000565]=5000200,
  [172000566]=5000201,[172000567]=5000202,[172000568]=5000203,[172000569]=5000204,[172000570]=5000205,[172000571]=5000206,
  [172000572]=5000207,[172000573]=5000300,[172000574]=5000301,[172000575]=5000302,[172000576]=5000303,[172000577]=5000304,
  [172000578]=5000305,[172000579]=5000306,[172000580]=5000307,[172000581]=5000400,[172000582]=5000401,[172000583]=5000402,
  [172000584]=5000403,[172000585]=5000404,[172000586]=5000405,[172000587]=5000406,[172000588]=5000407,[172000589]=5000500,
  [172000590]=5000501,[172000591]=5000502,[172000592]=5000503,[172000593]=5000504,[172000594]=5000505,[172000595]=5000506,
  [172000596]=5000507,[172000597]=5000600,[172000598]=5000601,[172000599]=5000602,[172000600]=5000603,[172000601]=5000604,
  [172000602]=5000605,[172000603]=5000606,[172000604]=5000607,[172000605]=5000700,[172000606]=5000701,[172000607]=5000702,
  [172000608]=5000703,[172000609]=5000704,[172000610]=5000705,[172000611]=5000706,[172000612]=5000707,[172000613]=5000800,
  [172000614]=5000801,[172000615]=5000802,[172000616]=5000803,[172000617]=5000804,[172000618]=5000805,[172000619]=5000806,
  [172000620]=5000807,[172000621]=5000900,[172000622]=5000901,[172000623]=5000902,[172000624]=5000903,[172000625]=5000904,
  [172000626]=5000905,[172000627]=5000906,[172000628]=5000907,[172000629]=5001000,[172000630]=5001001,[172000631]=5001002,
  [172000632]=5001003,[172000633]=5001004,[172000634]=5001005,[172000635]=5001006,[172000636]=5001007,[172000637]=5001100,
  [172000638]=5001101,[172000639]=5001102,[172000640]=5001103,[172000641]=5001104,[172000642]=5001105,[172000643]=5001106,
  [172000644]=5001107,[172000645]=5001200,[172000646]=5001201,[172000647]=5001202,[172000648]=5001203,[172000649]=5001204,
  [172000650]=5001205,[172000651]=5001206,[172000652]=5001207,[172000653]=5001300,[172000654]=5001301,[172000655]=5001302,
  [172000656]=5001303,[172000657]=5001304,[172000658]=5001305,[172000659]=5001306,[172000660]=5001307,[172000661]=5001400,
  [172000662]=5001401,[172000663]=5001402,[172000664]=5001403,[172000665]=5001404,[172000666]=5001405,[172000667]=5001406,
  [172000668]=5001407,[172000669]=5001500,[172000670]=5001501,[172000671]=5001502,[172000672]=5001503,[172000673]=5001504,
  [172000674]=5001505,[172000675]=5001506,[172000676]=5001507,[172000677]=5001600,[172000678]=5001601,[172000679]=5001602,
  [172000680]=5001603,[172000681]=5001604,[172000682]=5001605,[172000683]=5001606,[172000684]=5001607,[172000685]=5001700,
  [172000686]=5001701,[172000687]=5001702,[172000688]=5001703,[172000689]=5001704,[172000690]=5001705,[172000691]=5001706,
  [172000692]=5001707,[172000693]=5001800,[172000694]=5001801,[172000695]=5001802,[172000696]=5001803,[172000697]=5001804,
  [172000698]=5001805,[172000699]=5001806,[172000700]=1005600,[172000701]=1005601,[172000702]=1005602,[172000703]=1005603,
  [172000704]=1005604,[172000705]=1005605,[172000706]=1005606,[172000707]=1005607,[172000708]=1005700,
}

-- "list" locations (client.py "list" branch): ap_id -> {evt_byte, evt_bit, mis_byte, mis_bit}.
-- BOTH the EventFlag bit AND the Missable bit must be set. 2 entries.
local LOC_LIST = {
  [172000108]={212,7,16,7},
  [172000109]={212,6,17,0},
}

-- ── State ─────────────────────────────────────────────────────────────────────
local reported         = {}     -- ap_id -> true once returned from poll()
local server_locations = nil    -- set of ap_ids the server expects (nil = all)
local rom_ok           = nil     -- cached ROM-title result
local mem              = {}
local log_fn           = nil

-- ── Logging ───────────────────────────────────────────────────────────────────
local function log(msg)
  if log_fn then pcall(log_fn, "[pokemon_rb] " .. tostring(msg)) end
end

-- ── Memory API (resolved at init; 2-arg domain form + current-domain fallback) ─
local function resolve_memory_api()
  if not memory then return false end
  mem.read_u8 = memory.read_u8 or memory.readbyte
  return mem.read_u8 ~= nil
end

local function read_u8(addr, domain)
  if not mem.read_u8 then return nil end
  local ok, v = pcall(mem.read_u8, addr, domain)
  if ok and type(v) == "number" then return v end
  ok, v = pcall(mem.read_u8, addr)            -- older API: current domain
  if ok and type(v) == "number" then return v end
  return nil
end

local function bit_and(a, b)
  local res, bitval = 0, 1
  while a > 0 and b > 0 do
    if a % 2 == 1 and b % 2 == 1 then res = res + bitval end
    a = math.floor(a / 2); b = math.floor(b / 2); bitval = bitval * 2
  end
  return res
end

local POW2 = { [0]=1, 2, 4, 8, 16, 32, 64, 128 }

-- ── ROM identity: mirror client.validate_rom (GB header game title) ───────────
local function title_matches(target)
  for i = 1, #target do
    local b = read_u8(ROM_TITLE_ADDR + i - 1, ROM)
    if b == nil then return nil end             -- not readable yet; retry next poll
    if b ~= string.byte(target, i) then return false end
  end
  return true
end

local function rom_is_ap()
  if rom_ok ~= nil then return rom_ok end
  local red = title_matches(ROM_TITLE_RED)
  if red == nil then return false end           -- ROM domain not ready; retry
  if red then rom_ok = true; log("ROM verified (POKEMON RED)"); return true end
  local blue = title_matches(ROM_TITLE_BLUE)
  if blue == nil then return false end
  if blue then rom_ok = true; log("ROM verified (POKEMON BLUE)"); return true end
  rom_ok = false
  log("non-Pokémon R/B ROM (header title mismatch) — detection idle")
  return false
end

-- ── Multiworld context ────────────────────────────────────────────────────────
local function load_locations(ids)
  if type(ids) ~= "table" then return end
  server_locations = {}
  local n = 0
  for _, id in ipairs(ids) do
    local v = tonumber(id)
    if v then server_locations[v] = true; n = n + 1 end
  end
  log("server location set: " .. n .. " ids")
end

local function wanted(ap_id)
  if server_locations == nil then return true end
  return server_locations[ap_id] == true
end

-- ── Flag arrays (read once per poll) ──────────────────────────────────────────
-- arrays[arr_code][byte] = value. Each array refreshed fully each poll, exactly
-- like client.game_watcher reads the whole DATA_LOCATIONS block per frame.
local arrays = { [1]={}, [2]={}, [3]={}, [4]={}, [5]={} }

local function refresh_arrays()
  for code, info in pairs(ARR) do
    local a = arrays[code]
    for i = 0, info.len - 1 do
      a[i] = read_u8(info.base + i, WRAM)
    end
  end
end

local function arr_bit(arr_code, byte, bit)
  local a = arrays[arr_code]
  local v = a and a[byte]
  if v == nil then return false end
  return bit_and(v, POW2[bit]) ~= 0
end

-- packed -> arr, byte, bit
local function unpack_flag(packed)
  local arr  = math.floor(packed / 1000000)
  local rest = packed - arr * 1000000
  local byte = math.floor(rest / 100)
  local bit  = rest - byte * 100
  return arr, byte, bit
end

-- ── Detection gate (client.game_watcher: in-game AND not crashed) ─────────────
local function in_game()
  -- Pre-load guards: GameStatus 0, or ResetCheck == 0x7FFFFFFF (\xff\xff\xff\x7f)
  local status = read_u8(GAME_STATUS_ADDR, WRAM)
  if status == nil or status == 0 then return false end
  local r0 = read_u8(RESET_BASE + 0, WRAM)
  local r1 = read_u8(RESET_BASE + 1, WRAM)
  local r2 = read_u8(RESET_BASE + 2, WRAM)
  local r3 = read_u8(RESET_BASE + 3, WRAM)
  if r0 == 0xFF and r1 == 0xFF and r2 == 0xFF and r3 == 0x7F then return false end

  -- Crash guards: GameStatus must be 0x2A or 0xAC, and the four sentinels sane.
  if status ~= 0x2A and status ~= 0xAC then return false end
  local c1a = read_u8(CRASH1_ADDR + 0, WRAM)
  local c1b = read_u8(CRASH1_ADDR + 1, WRAM)
  if c1a == nil or c1b == nil then return false end
  if bit_and(c1a, 0xF0) ~= 0 or c1b ~= 0 then return false end
  local c2 = read_u8(CRASH2_ADDR, WRAM)
  if c2 == nil or c2 ~= 0 then return false end
  local c3 = read_u8(CRASH3_ADDR, WRAM)
  if c3 == nil or c3 > 10 then return false end
  local c4 = read_u8(CRASH4_ADDR, WRAM)
  if c4 == nil or c4 > 3 then return false end
  return true
end

-- ── Module contract ───────────────────────────────────────────────────────────
function M.init(ctx)
  if ctx and type(ctx.log) == "function" then log_fn = ctx.log end
  if not resolve_memory_api() then
    log("BizHawk memory API unavailable — module idle")
    ADDRESSES_VERIFIED = false
    return
  end
  local cfg = (ctx and ctx.config) or {}
  load_locations(cfg.locations)
  local n = 0
  for _ in pairs(LOC) do n = n + 1 end
  for _ in pairs(LOC_LIST) do n = n + 1 end
  log("ready: " .. n .. " location flags")
end

function M.poll()
  local new = {}
  if not ADDRESSES_VERIFIED then return new end
  if not rom_is_ap() then return new end
  if not in_game() then return new end
  refresh_arrays()
  -- single-flag locations
  for ap_id, packed in pairs(LOC) do
    if not reported[ap_id] and wanted(ap_id) then
      local arr, byte, bit = unpack_flag(packed)
      if arr_bit(arr, byte, bit) then
        reported[ap_id] = true
        new[#new + 1] = ap_id
      end
    end
  end
  -- "list" locations: EventFlag bit AND Missable bit (arr 1 and arr 2)
  for ap_id, q in pairs(LOC_LIST) do
    if not reported[ap_id] and wanted(ap_id) then
      if arr_bit(1, q[1], q[2]) and arr_bit(2, q[3], q[4]) then
        reported[ap_id] = true
        new[#new + 1] = ap_id
      end
    end
  end
  return new
end

function M.is_goal_complete()
  if not ADDRESSES_VERIFIED or not rom_is_ap() then return false end
  refresh_arrays()
  return arr_bit(1, GOAL_EVENT_BYTE, GOAL_EVENT_BIT)
end

-- Remote multiworld items: see the file header. items_handling = 0b001 means the
-- server only sends THIS slot's own items and the patched game grants its locally
-- found items itself, so solo play and check reporting work fully. Applying REMOTE
-- items is the client's guarded APItem-byte WRAM write (WRAM 0x00FF, gated on the
-- save's ItemIndex at 0x1A6E and the byte being 0); that is deferred until it can
-- be confirmed in-emulator. No-op (never a wrong write) until then.
function M.receive_item(item_id, meta)
  -- intentionally empty (documented)
end

return M
