-- ═══════════════════════════════════════════════════════════════════════════════
-- pokemon_platinum.lua — game module for the Archipelago BizHawk connector.
--                        Pokémon Platinum (Nintendo DS, BizHawk melonDS core)
--
-- STATUS: location DETECTION + goal are REAL and SOURCE-DERIVED from the official
-- community AP world https://github.com/ljtpetersen/platinum_archipelago
-- (client.py + data_gen/locations.toml + data_gen/event_checks.toml, world
-- version 0.2.0, minimum_ap_version 0.6.7). The 761-entry location table below was
-- GENERATED by parsing data_gen/locations.toml with Python and replicating the
-- client's exact raw-id + check model (NOT hand-copied), so the ap_id → flag/var/
-- once mapping is byte-for-byte what PokemonPlatinumClient.game_watcher uses. Loads
-- crash-free on any cartridge; self-disables on a non-AP ROM (validates the NDS
-- header game title, exactly like client.validate_rom).
--
-- MEMORY MODEL (BizHawk melonDS NDS domains)
-- ───────────────────────────────────────────
--   The PokemonPlatinumClient is a BizHawkClient. Every save-data read in
--   client.py uses the "ARM9 System Bus" domain; the ROM identity read uses
--   "ROM". (DS main RAM is also exposed by melonDS as "Main RAM"; this module
--   follows the apworld and uses the SAME domain the apworld reads — "ARM9 System
--   Bus" — so the discovered pointer values stay consistent with the apworld.)
--
--   AP struct discovery (client.get_struct_addr):
--     u32 @ 0x023DFFFC ("ARM9 System Bus")  → ap_struct address (must satisfy
--       0x02000000 < addr < 0x023DFFFC). The 16-byte header at ap_struct must
--       equal  b' AP ' * 3 + version_u32_le  (AP_MAGIC=" AP ", version 1) — the
--       exact validate done before any save read. Re-checked every poll; if the
--       struct moves/clears, discovery restarts (stand-in for guarded_read).
--
--   Save block (VersionData v1, all offsets from client.py AP_VERSION_DATA[1]):
--     savedata_ptr = u32 @ ap_struct + 16 ("ARM9 System Bus")
--     vars_flags   @ savedata_ptr + 0xDC0, size 0x3E0
--                    vars  = bytes [0x000 .. 0x240)   (u16 LE array, var 0x4000+)
--                    flags = bytes [0x240 .. 0x3E0)   (bit array)
--     once_flags   @ savedata_ptr + 0xCF60 + 4, 2 bytes (16 once-location flags)
--   A re-read of ap_struct's header AND savedata_ptr after the bulk read discards
--   the sample on any change (the apworld's guarded_read contract).
--
-- LOCATION MODEL (client.VarsFlags.is_checked, by raw_id = (table<<16)|id)
--   table 0/1/2 (base/overworld/hidden) → FlagCheck : flags[id//8] & (1<<id%8),
--                                          guarded by id>0  (734 of these)
--   table 3 (once)                      → OnceCheck : once_flags[id//8] & bit (15)
--   12 base-table entries               → VarCheck  : op(vars_u16[id-0x4000],val)
--                                          (ops used: eq, ge)
--   table 4 (dex) / table 5 (trainers)  → only present with dexsanity/trainersanity,
--                                          which this world does NOT ship yet
--                                          (README "What is Missing"); never mapped
--                                          here, so they stay idle if ever seen.
--   Only ids in the slot's server-location set are reported.
--
-- GOAL (client.game_watcher): the only goal option is "champion" (Goal=0) →
--   event_checks["beat_cynthia"] = FlagCheck(id=2404) → flags byte 300 bit 4.
--
-- ITEMS: items_handling = 0b001 (RemoteItems off, the default) — the server sends
--   only THIS slot's own items and the PATCHED GAME grants its locally-found items
--   itself, so a SOLO seed plays fully and every check is reported in a multiworld.
--   Delivering REMOTE items (RemoteItems on → 0b011) is the client's guarded
--   ring-buffer write into the AP struct's remote_item_queue (offset 44, gated on
--   recv_state==1, recv_item_count, and the queue's own front/back/capacity — a
--   multi-write that MUST be confirmed in-emulator before shipping). It is
--   intentionally deferred (receive_item is a documented no-op) rather than risk a
--   wrong write — the same posture as pokemon_rb.lua / cvcotm.lua. The launcher
--   still replays the full item stream; this module just does not consume it yet.
--
-- MODULE CONTRACT (called by bizhawk_ap_connector.lua)
--   M.init(ctx) / M.poll() -> {ids} / M.is_goal_complete() -> bool /
--   M.receive_item(item_id, meta)
-- ═══════════════════════════════════════════════════════════════════════════════

local M = {}
M.name = "pokemon_platinum"

local ADDRESSES_VERIFIED = true   -- table generated from the apworld source

-- ── Memory domains ────────────────────────────────────────────────────────────
local SYS = "ARM9 System Bus"   -- every save read (client.py)
local ROM = "ROM"               -- identity only

-- ── AP struct discovery (client.py) ───────────────────────────────────────────
local AP_STRUCT_PTR   = 0x023DFFFC        -- u32 here → ap_struct addr
local AP_STRUCT_MIN   = 0x02000000
local AP_MAGIC        = " AP "            -- AP_MAGIC, repeated 3×
local AP_VERSION      = 1                 -- AP_SUPPORTED_VERSIONS = {1}

-- ── VersionData v1 (client.py AP_VERSION_DATA[1]) ──────────────────────────────
local SAVEDATA_PTR_OFF   = 16
local VARS_FLAGS_OFF     = 0xDC0          -- vars_flags_offset_in_save
local VARS_FLAGS_SIZE    = 0x3E0
local FLAGS_OFF_IN_VF    = 0x240          -- flags start inside vars_flags
local VARS_OFF_IN_VF     = 0              -- vars  start inside vars_flags
local AP_SAVE_OFF        = 0xCF60
local ONCE_OFF_IN_AP     = 4              -- once_loc_flags_offset_in_ap_save
local ONCE_COUNT         = 16             -- → (16+7)//8 = 2 bytes

-- ── Goal: event_checks["beat_cynthia"] = FlagCheck(2404) ───────────────────────
local GOAL_FLAG = 2404

-- ── Location tables (GENERATED from data_gen/locations.toml) ──────────────────
-- FLAG_LOC[raw_id] = flag_id   (FlagCheck; client tests flags[id//8] & (1<<id%8),
--   id>0). base + overworld + hidden tables. 734 entries; none inverted.
local FLAG_LOC = {
  [1]=117,[2]=116,[3]=116,[4]=157,[5]=157,[6]=156,
  [7]=156,[8]=125,[9]=125,[10]=146,[11]=146,[12]=158,
  [13]=158,[14]=182,[15]=182,[17]=147,[18]=2445,[19]=532,
  [20]=154,[22]=132,[23]=162,[24]=107,[26]=143,[27]=143,
  [28]=108,[29]=144,[30]=2914,[31]=2914,[33]=2915,[34]=2916,
  [36]=392,[38]=500,[39]=274,[40]=237,[41]=238,[42]=239,
  [43]=2940,[44]=2940,[45]=2940,[46]=2940,[47]=130,[48]=192,
  [49]=193,[50]=266,[51]=265,[52]=191,[53]=242,[54]=197,
  [55]=159,[56]=159,[57]=131,[58]=128,[59]=312,[60]=227,
  [61]=2918,[62]=121,[63]=281,[64]=267,[66]=352,[67]=319,
  [68]=2923,[69]=141,[70]=140,[71]=278,[72]=161,[73]=2924,
  [74]=2925,[75]=210,[76]=279,[77]=183,[78]=199,[79]=263,
  [80]=198,[81]=2926,[82]=205,[83]=204,[84]=188,[86]=314,
  [87]=2927,[88]=202,[89]=163,[90]=313,[91]=201,[92]=285,
  [93]=222,[94]=315,[95]=206,[96]=2929,[97]=2930,[98]=2931,
  [99]=2932,[100]=2933,[101]=2934,[102]=2935,[103]=117,[104]=194,
  [105]=540,[106]=2941,[107]=261,[109]=213,[110]=218,[111]=218,
  [112]=203,[113]=217,[114]=299,[115]=317,[116]=296,[117]=297,
  [119]=298,[120]=2973,[121]=2974,[122]=2975,[124]=2976,[125]=2977,
  [127]=308,[128]=309,[129]=310,[130]=3012,[131]=3013,[132]=3014,
  [133]=3015,[134]=3016,[135]=3017,[136]=3018,[137]=3019,[138]=3020,
  [139]=3021,[140]=3022,[141]=3023,[142]=3024,[143]=3025,[144]=3026,
  [145]=3027,[146]=3028,[147]=3029,[148]=3030,[149]=3031,[65536]=1014,
  [65537]=1015,[65538]=1016,[65539]=1017,[65540]=1018,[65541]=1019,[65542]=1020,
  [65543]=1021,[65544]=1022,[65545]=1023,[65546]=1024,[65547]=1025,[65548]=1026,
  [65549]=1027,[65550]=1028,[65551]=1029,[65552]=1030,[65553]=1031,[65554]=1032,
  [65555]=1033,[65556]=1034,[65557]=1035,[65558]=1036,[65559]=1037,[65560]=1038,
  [65562]=1040,[65563]=1041,[65564]=1042,[65565]=1043,[65566]=1044,[65567]=1045,
  [65568]=1046,[65569]=1047,[65570]=1048,[65571]=1049,[65572]=1050,[65573]=1051,
  [65574]=1052,[65575]=1053,[65576]=1054,[65577]=1055,[65578]=1056,[65579]=1057,
  [65580]=1058,[65581]=1059,[65582]=1060,[65583]=1061,[65584]=1062,[65585]=1063,
  [65586]=1064,[65587]=1065,[65588]=1066,[65589]=1067,[65590]=1068,[65591]=1069,
  [65592]=1070,[65593]=1071,[65594]=1072,[65595]=1073,[65596]=1074,[65597]=1075,
  [65598]=1076,[65599]=1077,[65600]=1078,[65601]=1079,[65602]=1080,[65603]=1081,
  [65604]=1082,[65605]=1083,[65606]=1084,[65607]=1085,[65608]=1086,[65609]=1087,
  [65610]=1088,[65611]=1089,[65612]=1090,[65613]=1091,[65614]=1092,[65615]=1093,
  [65616]=1094,[65617]=1095,[65618]=1096,[65619]=1097,[65620]=1098,[65621]=1099,
  [65622]=1100,[65623]=1101,[65624]=1102,[65625]=1103,[65626]=1104,[65627]=1105,
  [65628]=2936,[65629]=1107,[65630]=1108,[65631]=1109,[65632]=1110,[65633]=1111,
  [65634]=1112,[65635]=1113,[65636]=1114,[65637]=1115,[65638]=1116,[65639]=1117,
  [65640]=1118,[65641]=1119,[65642]=1120,[65643]=1121,[65644]=1122,[65645]=1123,
  [65646]=1124,[65647]=1125,[65648]=1126,[65649]=1127,[65650]=1128,[65651]=1129,
  [65652]=1130,[65653]=1131,[65654]=1132,[65655]=1133,[65656]=1134,[65657]=1135,
  [65658]=1136,[65659]=1137,[65660]=1138,[65661]=1139,[65662]=1140,[65663]=1141,
  [65664]=1142,[65665]=1143,[65666]=1144,[65667]=1145,[65668]=1146,[65669]=1147,
  [65670]=1148,[65671]=1149,[65672]=1150,[65673]=1151,[65674]=1152,[65675]=1153,
  [65676]=1154,[65677]=1155,[65678]=1156,[65679]=1157,[65680]=1158,[65681]=1159,
  [65682]=1160,[65683]=1161,[65684]=1162,[65685]=1163,[65686]=1164,[65687]=1165,
  [65688]=1166,[65689]=1167,[65690]=1168,[65691]=1169,[65692]=1170,[65693]=1171,
  [65694]=1172,[65695]=1173,[65696]=1174,[65697]=1175,[65698]=1176,[65699]=1177,
  [65700]=1178,[65701]=1179,[65702]=1180,[65703]=1181,[65704]=1182,[65705]=1183,
  [65706]=1184,[65707]=1185,[65708]=1186,[65709]=1187,[65710]=1188,[65711]=1189,
  [65712]=1190,[65713]=1191,[65714]=1192,[65715]=1193,[65716]=1194,[65717]=1195,
  [65718]=1196,[65719]=1197,[65720]=1198,[65721]=1199,[65722]=1200,[65723]=1201,
  [65724]=1202,[65725]=1203,[65726]=1204,[65727]=1205,[65728]=1206,[65729]=1207,
  [65730]=1208,[65731]=1209,[65732]=1210,[65733]=1211,[65734]=1212,[65735]=1213,
  [65736]=1214,[65737]=1215,[65738]=1216,[65739]=1217,[65740]=1218,[65741]=1219,
  [65742]=1220,[65743]=1221,[65744]=1222,[65745]=1223,[65746]=1224,[65747]=1225,
  [65748]=1226,[65749]=1227,[65750]=1228,[65751]=1229,[65752]=1230,[65753]=1231,
  [65754]=1232,[65755]=1233,[65756]=1234,[65757]=1235,[65758]=1236,[65759]=1237,
  [65760]=1238,[65761]=1239,[65762]=1240,[65763]=1241,[65764]=1242,[65765]=1243,
  [65766]=1244,[65767]=1245,[65768]=1246,[65769]=1247,[65770]=1248,[65771]=1249,
  [65772]=1250,[65773]=1251,[65775]=1253,[65776]=1254,[65777]=1255,[65778]=1256,
  [65779]=1257,[65780]=1258,[65782]=1260,[65783]=1261,[65784]=1262,[65785]=1263,
  [65786]=1264,[65787]=1265,[65788]=1266,[65789]=1267,[65790]=1268,[65791]=1270,
  [65792]=1271,[65793]=1272,[65794]=1273,[65795]=1274,[65796]=1275,[65797]=1276,
  [65798]=1277,[65799]=1278,[65800]=1279,[65801]=1280,[65802]=1281,[65803]=1282,
  [65804]=1283,[65805]=1284,[65806]=1285,[65807]=1286,[65808]=1287,[65809]=1288,
  [65810]=1289,[65811]=1290,[65812]=1291,[65813]=1292,[65814]=1293,[65815]=1294,
  [65816]=1295,[65817]=1296,[65818]=1297,[65819]=1298,[65820]=1299,[65821]=1300,
  [65822]=1301,[65823]=1302,[65824]=1303,[65825]=1304,[65826]=1305,[65827]=1306,
  [65828]=1307,[65829]=1308,[65830]=1309,[65831]=1310,[65832]=1311,[65833]=1312,
  [65834]=1313,[65835]=1314,[65836]=1315,[65837]=1316,[65838]=1317,[65839]=1318,
  [65840]=1319,[65841]=1320,[65842]=1321,[65843]=1322,[65844]=1323,[65845]=1324,
  [65846]=1325,[65847]=1326,[65848]=1327,[65849]=1328,[65850]=1329,[65851]=1330,
  [65852]=1331,[65853]=1332,[65854]=1333,[65855]=1334,[65856]=1335,[65858]=1337,
  [65859]=1338,[65860]=1339,[65864]=2972,[65865]=2978,[65866]=2979,[65867]=2980,
  [65868]=2981,[65869]=2982,[65870]=2983,[65871]=2984,[131072]=730,[131073]=731,
  [131074]=732,[131075]=733,[131076]=734,[131077]=735,[131078]=736,[131079]=737,
  [131080]=738,[131081]=739,[131082]=740,[131083]=741,[131084]=742,[131085]=743,
  [131086]=744,[131087]=745,[131088]=746,[131089]=747,[131090]=748,[131091]=749,
  [131092]=750,[131093]=751,[131094]=752,[131095]=753,[131096]=754,[131097]=755,
  [131098]=756,[131099]=757,[131100]=758,[131101]=759,[131102]=760,[131103]=761,
  [131104]=762,[131105]=763,[131106]=764,[131107]=765,[131108]=766,[131109]=767,
  [131110]=768,[131111]=769,[131112]=770,[131113]=771,[131114]=772,[131115]=773,
  [131116]=774,[131117]=775,[131118]=776,[131119]=777,[131120]=778,[131121]=779,
  [131122]=780,[131123]=781,[131128]=786,[131129]=787,[131132]=790,[131133]=791,
  [131134]=792,[131135]=793,[131136]=794,[131137]=795,[131138]=796,[131139]=797,
  [131140]=798,[131141]=799,[131142]=800,[131143]=801,[131144]=802,[131145]=803,
  [131146]=804,[131147]=805,[131148]=806,[131149]=807,[131150]=808,[131151]=809,
  [131152]=810,[131153]=811,[131154]=812,[131155]=813,[131156]=814,[131157]=815,
  [131158]=816,[131159]=817,[131160]=818,[131161]=819,[131162]=820,[131163]=821,
  [131164]=822,[131165]=823,[131166]=824,[131167]=825,[131168]=826,[131169]=827,
  [131170]=828,[131171]=829,[131172]=830,[131173]=831,[131174]=832,[131175]=833,
  [131176]=834,[131177]=835,[131178]=836,[131179]=837,[131180]=838,[131181]=839,
  [131182]=840,[131183]=841,[131184]=842,[131185]=843,[131186]=844,[131187]=845,
  [131188]=846,[131189]=847,[131190]=848,[131191]=849,[131192]=850,[131193]=851,
  [131194]=852,[131195]=853,[131196]=854,[131197]=855,[131198]=856,[131199]=857,
  [131200]=858,[131201]=859,[131202]=860,[131203]=861,[131204]=862,[131205]=863,
  [131206]=864,[131207]=865,[131208]=866,[131209]=867,[131210]=868,[131211]=869,
  [131212]=870,[131213]=871,[131214]=872,[131215]=873,[131216]=874,[131217]=875,
  [131218]=876,[131219]=877,[131220]=878,[131221]=879,[131222]=880,[131223]=881,
  [131224]=882,[131225]=883,[131226]=884,[131227]=885,[131228]=886,[131229]=887,
  [131230]=888,[131231]=889,[131232]=890,[131233]=891,[131234]=892,[131235]=893,
  [131236]=894,[131237]=895,[131238]=896,[131239]=897,[131240]=898,[131241]=899,
  [131242]=900,[131243]=901,[131244]=902,[131245]=903,[131246]=904,[131247]=905,
  [131248]=906,[131249]=907,[131250]=908,[131251]=909,[131252]=910,[131253]=911,
  [131254]=912,[131255]=913,[131256]=914,[131257]=915,[131258]=916,[131259]=917,
  [131260]=918,[131261]=919,[131262]=920,[131263]=921,[131264]=922,[131265]=923,
  [131266]=924,[131267]=925,[131268]=926,[131269]=927,[131270]=928,[131271]=929,
  [131272]=930,[131273]=931,[131274]=932,[131275]=933,[131276]=934,[131277]=935,
  [131278]=936,[131279]=937,[131280]=938,[131281]=939,[131282]=940,[131283]=941,
  [131284]=942,[131285]=943,[131286]=944,[131287]=945,[131288]=946,[131289]=947,
  [131290]=948,[131295]=953,[131296]=954,[131297]=955,[131298]=956,[131299]=957,
  [131300]=958,[131328]=986,[131329]=987,[131330]=988,[131331]=989,[131332]=990,
  [131333]=991,[131334]=992,[131335]=993,[131336]=994,[131337]=995,[131338]=996,
  [131339]=997,[131340]=998,[131341]=999,[131342]=1000,[131343]=1001,[131344]=1002,
  [131345]=1003,[131346]=1004,[131347]=1005,[131348]=1006,[131356]=2943,[131357]=2944,
  [131358]=2945,[131359]=2946,[131360]=2947,[131361]=2948,[131362]=2949,[131363]=2950,
  [131364]=2951,[131365]=2952,[131366]=2953,[131367]=2954,[131368]=2955,[131369]=2956,
  [131370]=2957,[131371]=2958,[131372]=2959,[131373]=2960,[131374]=2961,[131375]=2962,
  [131376]=2963,[131377]=2964,[131378]=2965,[131379]=2966,[131380]=2967,[131381]=2968,
  [131382]=2969,[131383]=2970,
}

-- ONCE_LOC[raw_id] = once_id   (OnceCheck; once_flags[id//8] & (1<<id%8)). 15.
local ONCE_LOC = {
  [196608]=0,[196609]=1,[196610]=2,[196611]=3,[196612]=4,[196613]=5,
  [196614]=6,[196615]=7,[196616]=8,[196617]=9,[196618]=10,[196619]=11,
  [196620]=12,[196621]=13,[196622]=14,
}

-- VAR_LOC[raw_id] = { var_index, value, op }   (VarCheck; vars_u16[var_index]
--   compared to value by op). op: 0=eq 1=ne 2=lt 3=le 4=gt 5=ge. 12 entries.
local VAR_LOC = {
  [16]={122,2,5},[21]={140,1,5},[25]={164,4,5},
  [32]={113,2,5},[35]={198,1,0},[37]={119,1,5},
  [65]={140,1,5},[85]={214,1,0},[108]={212,1,0},
  [118]={247,1,0},[123]={137,2,0},[126]={124,4,0},
}

-- ── State ─────────────────────────────────────────────────────────────────────
local log_fn            = nil
local mem               = {}
local rom_ok            = nil       -- AP ROM identity (nil=unknown,false=no,true=yes)
local why_disabled      = "init() not run"
local ap_struct         = 0         -- 0 until discovered/validated
local server_locations  = nil       -- set of ap_ids the server expects (nil = all)
local reported          = {}        -- ap_id -> true once returned from poll()
local goal_reached      = false
local n_flag, n_once, n_var = 0, 0, 0

local POW2 = { [0]=1, 2, 4, 8, 16, 32, 64, 128 }

local function log(msg)
  if log_fn then pcall(log_fn, "[pokemon_platinum] " .. tostring(msg)) end
end

-- ── Memory API (resolved at init; 2-arg domain form + current-domain fallback) ─
local function resolve_memory_api()
  if not memory then return false end
  mem.read_u8  = memory.read_u8     or memory.readbyte
  mem.read_u16 = memory.read_u16_le or memory.readword
  mem.read_u32 = memory.read_u32_le or memory.readdword
  mem.read_rng = memory.read_bytes_as_array or memory.readbyterange
  return mem.read_u8 ~= nil and mem.read_u32 ~= nil
end

local function rd(fn, addr, domain)
  if not fn then return nil end
  local ok, v = pcall(fn, addr, domain)
  if ok and type(v) == "number" then return v end
  ok, v = pcall(fn, addr)                       -- older API: current domain
  if ok and type(v) == "number" then return v end
  return nil
end

local function read_u8(a, d)  return rd(mem.read_u8,  a, d) end
local function read_u32(a, d) return rd(mem.read_u32, a, d) end

-- Read `len` bytes → 1-based array (or nil). Bulk API first (both 0- and 1-based
-- variants normalized), per-byte fallback.
local function read_range(addr, len, domain)
  if mem.read_rng then
    local ok, t = pcall(mem.read_rng, addr, len, domain)
    if ok and type(t) == "table" then
      if t[0] ~= nil then
        local out = {}
        for i = 0, len - 1 do out[i + 1] = t[i] end
        return out
      end
      if t[1] ~= nil or len == 0 then return t end
    end
  end
  local out = {}
  for i = 0, len - 1 do
    local v = read_u8(addr + i, domain)
    if not v then return nil end
    out[i + 1] = v
  end
  return out
end

-- ── ROM identity: mirror client.validate_rom (NDS header game title @ ROM 0) ───
-- Vanilla = "POKEMON PL"; AP-patched = "PLAP <hex version>" (e.g. "PLAP 1").
local function read_rom_title()
  local b = read_range(0, 12, ROM)
  if not b then return nil end
  local out = {}
  for i = 1, #b do
    local c = b[i]
    if c and c ~= 0 then out[#out + 1] = string.char(c) end
  end
  return table.concat(out)
end

local function rom_is_ap()
  if rom_ok ~= nil then return rom_ok end
  local title = read_rom_title()
  if title == nil then return false end          -- ROM domain not ready; retry
  if title == "POKEMON PL" then
    rom_ok = false
    why_disabled = "unpatched vanilla Pokémon Platinum ROM (apply the seed's " ..
                   ".applatinum patch) — checks/goal DISABLED"
    log(why_disabled)
    return false
  end
  if title:sub(1, 5) == "PLAP " then
    local ver = tonumber((title:sub(6):gsub("%s+$", "")), 16)
    if ver == AP_VERSION then
      rom_ok = true
      log("AP ROM verified: '" .. title .. "'")
      return true
    end
    rom_ok = false
    why_disabled = "AP ROM version '" .. title .. "' != supported version " ..
                   AP_VERSION .. " — checks/goal DISABLED"
    log(why_disabled)
    return false
  end
  rom_ok = false
  why_disabled = "ROM title '" .. tostring(title) ..
                 "' is not a Pokémon Platinum AP ROM — module disabled"
  log(why_disabled)
  return false
end

-- ── AP struct discovery + validation (client.get_struct_addr / header guard) ──
local function header_ok(addr)
  -- 16-byte header: " AP "×3 + version (4 LE).
  local b = read_range(addr, 16, SYS)
  if not b then return false end
  for i = 1, 12 do
    if b[i] ~= string.byte(AP_MAGIC, ((i - 1) % 4) + 1) then return false end
  end
  -- version little-endian u32
  if b[13] ~= (AP_VERSION % 256) then return false end
  if b[14] ~= 0 or b[15] ~= 0 or b[16] ~= 0 then return false end
  return true
end

local function discover_struct()
  local addr = read_u32(AP_STRUCT_PTR, SYS)
  if not addr then return false end
  if addr <= AP_STRUCT_MIN or addr >= AP_STRUCT_PTR then return false end
  if not header_ok(addr) then return false end
  ap_struct = addr
  log(string.format("AP struct found at 0x%X", addr))
  return true
end

-- ── Multiworld context ────────────────────────────────────────────────────────
local function load_locations(ids)
  if type(ids) ~= "table" then return end
  server_locations = {}
  local n = 0
  for _, id in ipairs(ids) do
    local v = tonumber(id)
    if v then server_locations[v] = true; n = n + 1 end
  end
  log("server location set: " .. n .. " ids")
end

local function wanted(ap_id)
  if server_locations == nil then return true end
  return server_locations[ap_id] == true
end

-- op: 0=eq 1=ne 2=lt 3=le 4=gt 5=ge
local function cmp(a, op, b)
  if     op == 0 then return a == b
  elseif op == 1 then return a ~= b
  elseif op == 2 then return a <  b
  elseif op == 3 then return a <= b
  elseif op == 4 then return a >  b
  else                return a >= b end
end

-- ── Module contract ───────────────────────────────────────────────────────────
function M.init(ctx)
  if ctx and type(ctx.log) == "function" then log_fn = ctx.log end
  if not ADDRESSES_VERIFIED then
    log("address map not verified — module idle"); return
  end
  if not resolve_memory_api() then
    why_disabled = "BizHawk memory API unavailable"; log(why_disabled)
    ADDRESSES_VERIFIED = false; return
  end
  local cfg = (ctx and ctx.config) or {}
  load_locations(cfg.locations)
  for _ in pairs(FLAG_LOC) do n_flag = n_flag + 1 end
  for _ in pairs(ONCE_LOC) do n_once = n_once + 1 end
  for _ in pairs(VAR_LOC)  do n_var  = n_var  + 1 end
  log(string.format("ready: %d flag + %d once + %d var location checks, goal flag %d",
                    n_flag, n_once, n_var, GOAL_FLAG))
end

-- bit test in a 1-based byte array: flag_id // 8 → byte (1-based), id % 8 → bit.
local function flag_set(arr, flag_id)
  local byte = math.floor(flag_id / 8) + 1
  local v = arr[byte]
  if not v then return false end
  return (v % POW2[(flag_id % 8) + 1]) >= POW2[flag_id % 8]
end

function M.poll()
  local out = {}
  if not ADDRESSES_VERIFIED then return out end
  if not rom_is_ap() then return out end

  -- Discover/re-validate the AP struct (cleared if it moved).
  if ap_struct == 0 then
    discover_struct()
    return out
  end
  if not header_ok(ap_struct) then ap_struct = 0; return out end

  local savedata_ptr = read_u32(ap_struct + SAVEDATA_PTR_OFF, SYS)
  if not savedata_ptr or savedata_ptr <= AP_STRUCT_MIN then return out end

  -- Bulk reads (the apworld's two guarded_read blocks).
  local vf   = read_range(savedata_ptr + VARS_FLAGS_OFF, VARS_FLAGS_SIZE, SYS)
  local once = vf and read_range(savedata_ptr + AP_SAVE_OFF + ONCE_OFF_IN_AP,
                                 math.floor((ONCE_COUNT + 7) / 8), SYS)
  if not vf or not once then return out end

  -- guarded_read stand-in: discard if the struct header changed or the
  -- savedata pointer moved while we were reading.
  if not header_ok(ap_struct)
     or read_u32(ap_struct + SAVEDATA_PTR_OFF, SYS) ~= savedata_ptr then
    return out
  end

  -- vars (u16 LE) and flags (bit array) sub-views into vars_flags. flags index k
  -- corresponds to vf[FLAGS_OFF_IN_VF + k + 1]; var u16 #i is at vf bytes
  -- VARS_OFF_IN_VF + i*2 (+1/+2 for 1-based).
  local function flags_byte(idx)   return vf[FLAGS_OFF_IN_VF + idx + 1] end
  local function var_u16(var_idx)
    local off = VARS_OFF_IN_VF + var_idx * 2
    local lo, hi = vf[off + 1], vf[off + 2]
    if not lo or not hi then return nil end
    return lo + hi * 256
  end

  local function flag_id_set(flag_id)
    if flag_id <= 0 then return false end        -- client guards id>0
    local v = flags_byte(math.floor(flag_id / 8))
    if not v then return false end
    return (v % POW2[(flag_id % 8) + 1]) >= POW2[flag_id % 8]
  end
  local function once_id_set(once_id)
    return flag_set(once, once_id)
  end

  -- FlagCheck locations.
  for raw, flag_id in pairs(FLAG_LOC) do
    if not reported[raw] and wanted(raw) and flag_id_set(flag_id) then
      reported[raw] = true
      out[#out + 1] = raw
    end
  end
  -- OnceCheck locations.
  for raw, once_id in pairs(ONCE_LOC) do
    if not reported[raw] and wanted(raw) and once_id_set(once_id) then
      reported[raw] = true
      out[#out + 1] = raw
    end
  end
  -- VarCheck locations.
  for raw, q in pairs(VAR_LOC) do
    if not reported[raw] and wanted(raw) then
      local v = var_u16(q[1])
      if v ~= nil and cmp(v, q[3], q[2]) then
        reported[raw] = true
        out[#out + 1] = raw
      end
    end
  end

  -- Goal: beat_cynthia flag.
  if not goal_reached and flag_id_set(GOAL_FLAG) then
    goal_reached = true
    log("goal flag " .. GOAL_FLAG .. " (beat_cynthia) set — goal complete")
  end

  return out
end

function M.is_goal_complete()
  return goal_reached
end

-- Remote multiworld items: see the file header. items_handling = 0b001 (the
-- default, RemoteItems off) means the server sends only THIS slot's own items and
-- the patched game grants its locally-found items itself, so solo play and check
-- reporting work fully. Applying REMOTE items is the client's guarded ring-buffer
-- write into the AP struct's remote_item_queue; that is deferred until it can be
-- confirmed in-emulator, rather than shipped unverified. No-op (never a wrong
-- write) until then.
function M.receive_item(item_id, meta)
  -- intentionally empty (documented)
end

return M
