-- ═══════════════════════════════════════════════════════════════════════════════
-- pokemon_bw.lua — game module for the Archipelago BizHawk connector.
--                  Pokémon Black and White (Nintendo DS, BizHawk melonDS core)
--
-- STATUS: location DETECTION + goal are REAL and SOURCE-DERIVED from the official
-- community AP world https://github.com/BlastSlimey/PokemonBWAP
-- (pokemon_bw/bizhawk_client.py + client/locations.py + client/goals.py +
-- generate/locations/*.py, apworld pokemon_bw.apworld v0.3.999, world_version
-- 0.3.200, minimum_ap_version 0.6.3). The 633-entry flag-location table and
-- 649-entry dex-location table below were GENERATED by importing the world's OWN
-- data tables (data/locations/ingame_items/*.py + data/locations/dexsanity.py)
-- and running its OWN lookup() id-assignment formulas with Python (NOT
-- hand-copied), so the ap_id → flag/dex mapping is byte-for-byte what
-- PokemonBWClient.game_watcher uses. Loads crash-free on any cartridge;
-- self-disables on a non-AP ROM (validates the NDS game-title header, exactly
-- like client.validate_rom).
--
-- WHY A GENERATED TABLE (not an algorithmic loc_id→flag formula): the world's
-- lookup() builds ids as flag_id*100 + domain + suffix for the `other` (300000)
-- and `tm_hm` (500000) domains, so a two-digit "#nn" suffix pushes some ids OUT
-- of their nominal 100000-band (e.g. flag 1439 → id 443900, which naively looks
-- like a 400000 "badge" id). 42 ids collide bands this way — a band-based reverse
-- formula is provably wrong for them, so the exact generated table is authoritative.
--
-- MEMORY MODEL (BizHawk melonDS NDS domains)
-- ───────────────────────────────────────────
--   PokemonBWClient is a BizHawkClient. EVERY save-data read AND the ROM-identity
--   header read in bizhawk_client.py use the "Main RAM" domain (ram_read_write_
--   domain) — NOT "ARM9 System Bus" (that is what Pokémon Platinum uses; BW is
--   different). This module follows the apworld and uses "Main RAM" for all reads,
--   so the discovered pointer/flag values stay consistent with the apworld.
--
--   Save-data discovery (client.early_setup):
--     save_data_address = u24 LE @ 0x000024 ("Main RAM")  (a 3-byte read; ≈
--       0x21B310 in vanilla White). All save offsets below are relative to it.
--   In-game gate (client.game_watcher):
--     u8 @ 0x000034 ("Main RAM"); 0 = not in a loaded save → skip this poll.
--   ROM identity (client.validate_rom): 18 bytes @ 0x3FFA80 ("Main RAM") must
--     equal  b'POKEMON B\0\0\0IRBO01' (Black)  or  b'POKEMON W\0\0\0IRAO01'
--     (White). The AP-patched ROM keeps the original gamecode, so this is the
--     same signature on a patched cartridge — it disables only on a non-BW ROM.
--
--   Flags block  @ save + 0x20C38, size ceil(2912/8)=364 bytes (bit array).
--   Dex block    @ save + 0x21EC4, size ceil(650/8)=82  bytes (caught-flags bits).
--   Vars block   @ save + 0x209BC (u16 LE array; var #v at +2*v) — goal var reads.
--
-- LOCATION MODEL (client check_flag_locations / check_dex_locations)
--   FLAG locations (overworld 100000 / hidden 200000 / other 300000 /
--     badge 400000 / tm_hm 500000 domains): set when
--       flags[flag_id // 8] & (1 << (flag_id % 8)) != 0.
--     Multiple ap_ids can share one flag_id (suffix "#1/#2" variants) — when the
--     flag sets, ALL wanted ap_ids on that flag report, exactly as the client's
--     missing_flag_loc_ids[flag] list does.
--   DEX locations (dexsanity 600000 domain): set when
--       dex[(dex_number-1) // 8] & (1 << ((dex_number-1) % 8)) != 0.
--     (client maps dex bit k → dex_number k+1, i.e. dex_number d → bit d-1.)
--     Only present when slot_data options.dexsanity != 0 (else the client never
--     reads the dex block — this module mirrors that and skips it).
--   Only ap_ids in the slot's server-location set are reported.
--
-- GOAL (client.goals.get_method, by slot_data options.goal — DEFAULT "ghetsis"):
--   ghetsis          → flag 0x1D3
--   champion         → flag 0x1D4
--   cynthia          → var 0xE4 >= 2
--   cobalion         → flag 649
--   tmhm_hunt        → flag 0x191
--   seven_sages_hunt → var 0xCC >= 6  AND flag 0x1D3
--   legendary_hunt   → flags 649,650,651,801,779,810 AND flag 0x1CE
--   pokemon_master   → ALL of the above combined
--   (When slot_data is unavailable the module defaults to "ghetsis", the world's
--    own Goal default = 0.)
--
-- ITEMS: items_handling = 0b111 (ctx.items_handling set in client.validate_rom) —
--   the AP SERVER drives ALL item delivery, including this slot's own and remote
--   items. The reference client WRITES received items into the running game's
--   save RAM and bumps the game's own received-item counter (a guarded multi-write
--   into the live save). That guarded-write path is the documented deferred piece
--   (receive_item below is a no-op) until it can be confirmed in-emulator, rather
--   than shipped unverified — a wrong save-RAM write would corrupt the save. Same
--   posture as ff1.lua / pokemon_platinum.lua / cvcotm.lua. Checks + goal flow
--   regardless; the launcher still replays the full item stream, this module just
--   does not consume it yet.
--
-- MODULE CONTRACT (called by bizhawk_ap_connector.lua)
--   M.init(ctx) / M.poll() -> {ids} / M.is_goal_complete() -> bool /
--   M.receive_item(item_id, meta)
-- ═══════════════════════════════════════════════════════════════════════════════

local M = {}
M.name = "pokemon_bw"

local ADDRESSES_VERIFIED = true   -- tables generated from the apworld source

-- ── Memory domain ─────────────────────────────────────────────────────────────
local RAM = "Main RAM"   -- every read in bizhawk_client.py (save + ROM identity)

-- ── Fixed addresses (Main RAM offsets; client.py) ─────────────────────────────
local DATA_ADDR_PTR   = 0x000024     -- u24 LE here → save_data_address
local INGAME_STATE    = 0x000034     -- u8: 0 = not in a save
local HEADER_ADDR     = 0x3FFA80     -- NDS game-title header copy
local HEADER_BLACK    = "POKEMON B\0\0\0IRBO01"
local HEADER_WHITE    = "POKEMON W\0\0\0IRAO01"

-- ── Save-relative offsets / sizes (client.py) ─────────────────────────────────
local FLAGS_OFF       = 0x20C38      -- flags bit array
local FLAGS_BYTES     = 364          -- ceil(2912/8)
local DEX_OFF         = 0x21EC4      -- caught-dex bit array
local DEX_BYTES       = 82           -- ceil(650/8)
local VAR_OFF         = 0x209BC      -- u16 LE var array
local SAVE_ADDR_MIN   = 0x000100     -- sanity floor for the discovered pointer

-- ── Goal flag/var constants (client.goals) ────────────────────────────────────
local GOAL_FLAG_GHETSIS   = 0x1D3
local GOAL_FLAG_CHAMPION  = 0x1D4
local GOAL_VAR_CYNTHIA    = 0xE4    -- >= 2
local GOAL_FLAG_COBALION  = 649
local GOAL_FLAG_TMHM      = 0x191
local GOAL_VAR_SAGES      = 0xCC    -- >= 6 (AND ghetsis)
local GOAL_FLAG_RESZEK    = 0x1CE   -- Reshiram/Zekrom (legendary hunt)
local LEGENDARY_FLAGS     = { 649, 650, 651, 801, 779, 810, 0x1CE }

-- ── Location tables (GENERATED from the apworld; see header) ──────────────────
-- FLAG_LOC[ap_id] = flag_id  (FlagCheck over the flags block; many ap_ids may
--   share a flag_id — suffix variants — and all report when the flag sets). 633.
local FLAG_LOC = {
  [100181]=181,[100435]=435,[100436]=436,[101106]=1106,[101107]=1107,[101108]=1108,
  [101109]=1109,[101110]=1110,[101111]=1111,[101112]=1112,[101113]=1113,[101114]=1114,
  [101115]=1115,[101116]=1116,[101117]=1117,[101118]=1118,[101119]=1119,[101120]=1120,
  [101121]=1121,[101122]=1122,[101123]=1123,[101124]=1124,[101125]=1125,[101126]=1126,
  [101127]=1127,[101128]=1128,[101129]=1129,[101130]=1130,[101131]=1131,[101132]=1132,
  [101133]=1133,[101134]=1134,[101135]=1135,[101136]=1136,[101137]=1137,[101138]=1138,
  [101139]=1139,[101140]=1140,[101141]=1141,[101142]=1142,[101143]=1143,[101144]=1144,
  [101145]=1145,[101146]=1146,[101147]=1147,[101148]=1148,[101149]=1149,[101150]=1150,
  [101151]=1151,[101152]=1152,[101153]=1153,[101154]=1154,[101155]=1155,[101156]=1156,
  [101157]=1157,[101158]=1158,[101159]=1159,[101160]=1160,[101161]=1161,[101162]=1162,
  [101163]=1163,[101164]=1164,[101165]=1165,[101166]=1166,[101167]=1167,[101168]=1168,
  [101169]=1169,[101170]=1170,[101171]=1171,[101172]=1172,[101173]=1173,[101174]=1174,
  [101175]=1175,[101176]=1176,[101177]=1177,[101178]=1178,[101179]=1179,[101180]=1180,
  [101181]=1181,[101182]=1182,[101183]=1183,[101184]=1184,[101185]=1185,[101186]=1186,
  [101187]=1187,[101188]=1188,[101189]=1189,[101190]=1190,[101191]=1191,[101192]=1192,
  [101193]=1193,[101194]=1194,[101195]=1195,[101196]=1196,[101197]=1197,[101198]=1198,
  [101199]=1199,[101200]=1200,[101201]=1201,[101202]=1202,[101203]=1203,[101204]=1204,
  [101205]=1205,[101206]=1206,[101207]=1207,[101208]=1208,[101209]=1209,[101210]=1210,
  [101211]=1211,[101212]=1212,[101213]=1213,[101214]=1214,[101215]=1215,[101216]=1216,
  [101217]=1217,[101218]=1218,[101219]=1219,[101220]=1220,[101221]=1221,[101222]=1222,
  [101223]=1223,[101224]=1224,[101225]=1225,[101226]=1226,[101227]=1227,[101228]=1228,
  [101229]=1229,[101230]=1230,[101231]=1231,[101232]=1232,[101233]=1233,[101234]=1234,
  [101235]=1235,[101236]=1236,[101237]=1237,[101238]=1238,[101239]=1239,[101240]=1240,
  [101241]=1241,[101242]=1242,[101243]=1243,[101244]=1244,[101245]=1245,[101246]=1246,
  [101247]=1247,[101248]=1248,[101249]=1249,[101250]=1250,[101251]=1251,[101252]=1252,
  [101253]=1253,[101254]=1254,[101255]=1255,[101256]=1256,[101257]=1257,[101258]=1258,
  [101259]=1259,[101260]=1260,[101261]=1261,[101262]=1262,[101263]=1263,[101264]=1264,
  [101265]=1265,[101266]=1266,[101267]=1267,[101268]=1268,[101269]=1269,[101270]=1270,
  [101271]=1271,[101272]=1272,[101273]=1273,[101274]=1274,[101275]=1275,[101276]=1276,
  [101277]=1277,[101278]=1278,[101279]=1279,[101280]=1280,[101281]=1281,[101282]=1282,
  [101283]=1283,[101284]=1284,[101285]=1285,[101286]=1286,[101287]=1287,[101288]=1288,
  [101289]=1289,[101290]=1290,[101291]=1291,[101292]=1292,[101293]=1293,[101294]=1294,
  [101295]=1295,[101296]=1296,[101297]=1297,[101298]=1298,[101299]=1299,[101300]=1300,
  [101301]=1301,[101302]=1302,[101303]=1303,[101304]=1304,[101305]=1305,[101306]=1306,
  [101307]=1307,[101308]=1308,[101309]=1309,[101310]=1310,[101311]=1311,[101312]=1312,
  [101313]=1313,[101314]=1314,[101315]=1315,[101316]=1316,[101317]=1317,[101318]=1318,
  [101319]=1319,[101320]=1320,[101321]=1321,[101322]=1322,[101323]=1323,[101324]=1324,
  [101325]=1325,[101326]=1326,[101327]=1327,[101328]=1328,[101329]=1329,[101330]=1330,
  [101361]=1361,[101362]=1362,[101363]=1363,[101364]=1364,[101365]=1365,[101366]=1366,
  [101367]=1367,[101368]=1368,[101369]=1369,[101370]=1370,[101371]=1371,[101372]=1372,
  [101373]=1373,[101374]=1374,[101375]=1375,[101376]=1376,[101377]=1377,[101378]=1378,
  [101379]=1379,[101380]=1380,[101381]=1381,[101382]=1382,[101383]=1383,[101384]=1384,
  [101385]=1385,[101386]=1386,[101387]=1387,[101388]=1388,[101389]=1389,[101390]=1390,
  [101391]=1391,[101392]=1392,[101393]=1393,[101394]=1394,[101395]=1395,[101396]=1396,
  [101397]=1397,[101398]=1398,[101399]=1399,[101400]=1400,[101401]=1401,[101402]=1402,
  [101403]=1403,[101404]=1404,[101405]=1405,[101406]=1406,[101407]=1407,[101408]=1408,
  [101409]=1409,[101410]=1410,[101411]=1411,[200438]=438,[200445]=445,[200446]=446,[200448]=448,
  [200449]=449,[200451]=451,[200453]=453,[200454]=454,[200455]=455,[200456]=456,[200457]=457,
  [200459]=459,[200460]=460,[200461]=461,[200900]=900,[200901]=901,[200902]=902,[200903]=903,
  [200904]=904,[200905]=905,[200906]=906,[200907]=907,[200908]=908,[200940]=940,[200941]=941,
  [200942]=942,[200943]=943,[200944]=944,[200945]=945,[200946]=946,[200947]=947,[200948]=948,
  [200949]=949,[200950]=950,[200951]=951,[200952]=952,[200953]=953,[200955]=955,[200957]=957,
  [200958]=958,[200959]=959,[200960]=960,[200961]=961,[200962]=962,[200964]=964,[200965]=965,
  [200966]=966,[200967]=967,[200968]=968,[200969]=969,[200970]=970,[200971]=971,[200972]=972,
  [200973]=973,[200974]=974,[200975]=975,[200976]=976,[200977]=977,[200978]=978,[200979]=979,
  [200980]=980,[200981]=981,[200983]=983,[200984]=984,[200985]=985,[200986]=986,[200987]=987,
  [200988]=988,[200989]=989,[200990]=990,[200991]=991,[200992]=992,[200993]=993,[200994]=994,
  [200995]=995,[200996]=996,[200999]=999,[201001]=1001,[201002]=1002,[201006]=1006,
  [201007]=1007,[201008]=1008,[201011]=1011,[201012]=1012,[201013]=1013,[201014]=1014,
  [201015]=1015,[201016]=1016,[201017]=1017,[201018]=1018,[201019]=1019,[201021]=1021,
  [201022]=1022,[201023]=1023,[201026]=1026,[201027]=1027,[201028]=1028,[201029]=1029,
  [201030]=1030,[201031]=1031,[201032]=1032,[201033]=1033,[201034]=1034,[201035]=1035,
  [201036]=1036,[201037]=1037,[201038]=1038,[201039]=1039,[201040]=1040,[201041]=1041,
  [201042]=1042,[201043]=1043,[201044]=1044,[201045]=1045,[201046]=1046,[201047]=1047,
  [201048]=1048,[201049]=1049,[201050]=1050,[201051]=1051,[201052]=1052,[201053]=1053,
  [201054]=1054,[201055]=1055,[201056]=1056,[201057]=1057,[201058]=1058,[201059]=1059,
  [201060]=1060,[201061]=1061,[201062]=1062,[201063]=1063,[201064]=1064,[201065]=1065,
  [201066]=1066,[201067]=1067,[201068]=1068,[201069]=1069,[201070]=1070,[201071]=1071,
  [201072]=1072,[201073]=1073,[201074]=1074,[201075]=1075,[201076]=1076,[310900]=109,
  [311100]=111,[311800]=118,[311900]=119,[312000]=120,[312100]=121,[312200]=122,[312300]=123,
  [312400]=124,[312500]=125,[313200]=132,[313400]=134,[314400]=144,[314500]=145,[314701]=147,
  [314702]=147,[314703]=147,[315300]=153,[316300]=163,[316400]=164,[316901]=169,[316902]=169,
  [318700]=187,[318900]=189,[319000]=190,[319100]=191,[319201]=192,[319202]=192,[319203]=192,
  [325100]=251,[325200]=252,[325300]=253,[326100]=261,[326200]=262,[326300]=263,[326400]=264,
  [326601]=266,[326602]=266,[326603]=266,[326604]=266,[326605]=266,[326606]=266,[326800]=268,
  [326900]=269,[327300]=273,[327600]=276,[327900]=279,[330100]=301,[331000]=310,[331200]=312,
  [331600]=316,[331800]=318,[331900]=319,[332300]=323,[332400]=324,[332500]=325,[332800]=328,
  [335000]=350,[335601]=356,[335602]=356,[335900]=359,[336200]=362,[336500]=365,[336600]=366,
  [336700]=367,[338900]=389,[339100]=391,[339200]=392,[339300]=393,[339400]=394,[339501]=395,
  [339502]=395,[339503]=395,[339504]=395,[339505]=395,[339600]=396,[339801]=398,[339802]=398,
  [339803]=398,[339900]=399,[340401]=404,[340402]=404,[340403]=404,[340500]=405,[340600]=406,
  [340800]=408,[340900]=409,[341101]=411,[341102]=411,[341103]=411,[341104]=411,[341105]=411,
  [341106]=411,[341107]=411,[341108]=411,[341109]=411,[341110]=411,[341200]=412,[341400]=414,
  [341500]=415,[341900]=419,[342200]=422,[342300]=423,[342400]=424,[342601]=426,[342702]=427,
  [342803]=428,[343100]=431,[343201]=432,[343202]=432,[343203]=432,[343204]=432,[343205]=432,
  [343300]=433,[343401]=434,[343402]=434,[343900]=439,[344000]=440,[344200]=442,[344400]=444,
  [344700]=447,[345000]=450,[345200]=452,[345800]=458,[400370]=370,[400371]=371,[400372]=372,
  [400373]=373,[400374]=374,[400375]=375,[400376]=376,[400377]=377,[443900]=1439,[444000]=1440,
  [444600]=1446,[444700]=1447,[444800]=1448,[444900]=1449,[456700]=1567,[460200]=1602,
  [460300]=1603,[460400]=1604,[460600]=1606,[460700]=1607,[460800]=1608,[477400]=1774,
  [477700]=1777,[477800]=1778,[477900]=1779,[478000]=1780,[478300]=1783,[478400]=1784,
  [478500]=1785,[478600]=1786,[478900]=1789,[479000]=1790,[479700]=1797,[479800]=1798,
  [480200]=1802,[480300]=1803,[480400]=1804,[480500]=1805,[487100]=1871,[487200]=1872,
  [487300]=1873,[487400]=1874,[487500]=1875,[487600]=1876,[495100]=1951,[495200]=1952,
  [496900]=1969,[497000]=1970,[500200]=2002,[500300]=2003,[513300]=133,[513500]=135,
  [517400]=174,[517500]=175,[517600]=176,[525800]=258,[526000]=260,[526500]=265,[526700]=267,
  [527000]=270,[527100]=271,[527200]=272,[529000]=290,[530800]=308,[534600]=346,[537000]=370,
  [537100]=371,[537200]=372,[537300]=373,[537500]=375,[537600]=376,[537700]=377,[539000]=390,
  [539700]=397,[540700]=407,[541000]=410,[541300]=413,[541600]=416,[541700]=417,[541800]=418,
  [542000]=420,[542100]=421,[542500]=425,[542900]=429,[543000]=430,
}

-- DEX_LOC[ap_id] = dex_number  (dexsanity; bit (dex_number-1) of the dex block).
-- Only consulted when slot_data options.dexsanity != 0. 649 entries.
local DEX_LOC = {
  [600001]=1,[600002]=2,[600003]=3,[600004]=4,[600005]=5,[600006]=6,[600007]=7,[600008]=8,
  [600009]=9,[600010]=10,[600011]=11,[600012]=12,[600013]=13,[600014]=14,[600015]=15,
  [600016]=16,[600017]=17,[600018]=18,[600019]=19,[600020]=20,[600021]=21,[600022]=22,
  [600023]=23,[600024]=24,[600025]=25,[600026]=26,[600027]=27,[600028]=28,[600029]=29,
  [600030]=30,[600031]=31,[600032]=32,[600033]=33,[600034]=34,[600035]=35,[600036]=36,
  [600037]=37,[600038]=38,[600039]=39,[600040]=40,[600041]=41,[600042]=42,[600043]=43,
  [600044]=44,[600045]=45,[600046]=46,[600047]=47,[600048]=48,[600049]=49,[600050]=50,
  [600051]=51,[600052]=52,[600053]=53,[600054]=54,[600055]=55,[600056]=56,[600057]=57,
  [600058]=58,[600059]=59,[600060]=60,[600061]=61,[600062]=62,[600063]=63,[600064]=64,
  [600065]=65,[600066]=66,[600067]=67,[600068]=68,[600069]=69,[600070]=70,[600071]=71,
  [600072]=72,[600073]=73,[600074]=74,[600075]=75,[600076]=76,[600077]=77,[600078]=78,
  [600079]=79,[600080]=80,[600081]=81,[600082]=82,[600083]=83,[600084]=84,[600085]=85,
  [600086]=86,[600087]=87,[600088]=88,[600089]=89,[600090]=90,[600091]=91,[600092]=92,
  [600093]=93,[600094]=94,[600095]=95,[600096]=96,[600097]=97,[600098]=98,[600099]=99,
  [600100]=100,[600101]=101,[600102]=102,[600103]=103,[600104]=104,[600105]=105,[600106]=106,
  [600107]=107,[600108]=108,[600109]=109,[600110]=110,[600111]=111,[600112]=112,[600113]=113,
  [600114]=114,[600115]=115,[600116]=116,[600117]=117,[600118]=118,[600119]=119,[600120]=120,
  [600121]=121,[600122]=122,[600123]=123,[600124]=124,[600125]=125,[600126]=126,[600127]=127,
  [600128]=128,[600129]=129,[600130]=130,[600131]=131,[600132]=132,[600133]=133,[600134]=134,
  [600135]=135,[600136]=136,[600137]=137,[600138]=138,[600139]=139,[600140]=140,[600141]=141,
  [600142]=142,[600143]=143,[600144]=144,[600145]=145,[600146]=146,[600147]=147,[600148]=148,
  [600149]=149,[600150]=150,[600151]=151,[600152]=152,[600153]=153,[600154]=154,[600155]=155,
  [600156]=156,[600157]=157,[600158]=158,[600159]=159,[600160]=160,[600161]=161,[600162]=162,
  [600163]=163,[600164]=164,[600165]=165,[600166]=166,[600167]=167,[600168]=168,[600169]=169,
  [600170]=170,[600171]=171,[600172]=172,[600173]=173,[600174]=174,[600175]=175,[600176]=176,
  [600177]=177,[600178]=178,[600179]=179,[600180]=180,[600181]=181,[600182]=182,[600183]=183,
  [600184]=184,[600185]=185,[600186]=186,[600187]=187,[600188]=188,[600189]=189,[600190]=190,
  [600191]=191,[600192]=192,[600193]=193,[600194]=194,[600195]=195,[600196]=196,[600197]=197,
  [600198]=198,[600199]=199,[600200]=200,[600201]=201,[600202]=202,[600203]=203,[600204]=204,
  [600205]=205,[600206]=206,[600207]=207,[600208]=208,[600209]=209,[600210]=210,[600211]=211,
  [600212]=212,[600213]=213,[600214]=214,[600215]=215,[600216]=216,[600217]=217,[600218]=218,
  [600219]=219,[600220]=220,[600221]=221,[600222]=222,[600223]=223,[600224]=224,[600225]=225,
  [600226]=226,[600227]=227,[600228]=228,[600229]=229,[600230]=230,[600231]=231,[600232]=232,
  [600233]=233,[600234]=234,[600235]=235,[600236]=236,[600237]=237,[600238]=238,[600239]=239,
  [600240]=240,[600241]=241,[600242]=242,[600243]=243,[600244]=244,[600245]=245,[600246]=246,
  [600247]=247,[600248]=248,[600249]=249,[600250]=250,[600251]=251,[600252]=252,[600253]=253,
  [600254]=254,[600255]=255,[600256]=256,[600257]=257,[600258]=258,[600259]=259,[600260]=260,
  [600261]=261,[600262]=262,[600263]=263,[600264]=264,[600265]=265,[600266]=266,[600267]=267,
  [600268]=268,[600269]=269,[600270]=270,[600271]=271,[600272]=272,[600273]=273,[600274]=274,
  [600275]=275,[600276]=276,[600277]=277,[600278]=278,[600279]=279,[600280]=280,[600281]=281,
  [600282]=282,[600283]=283,[600284]=284,[600285]=285,[600286]=286,[600287]=287,[600288]=288,
  [600289]=289,[600290]=290,[600291]=291,[600292]=292,[600293]=293,[600294]=294,[600295]=295,
  [600296]=296,[600297]=297,[600298]=298,[600299]=299,[600300]=300,[600301]=301,[600302]=302,
  [600303]=303,[600304]=304,[600305]=305,[600306]=306,[600307]=307,[600308]=308,[600309]=309,
  [600310]=310,[600311]=311,[600312]=312,[600313]=313,[600314]=314,[600315]=315,[600316]=316,
  [600317]=317,[600318]=318,[600319]=319,[600320]=320,[600321]=321,[600322]=322,[600323]=323,
  [600324]=324,[600325]=325,[600326]=326,[600327]=327,[600328]=328,[600329]=329,[600330]=330,
  [600331]=331,[600332]=332,[600333]=333,[600334]=334,[600335]=335,[600336]=336,[600337]=337,
  [600338]=338,[600339]=339,[600340]=340,[600341]=341,[600342]=342,[600343]=343,[600344]=344,
  [600345]=345,[600346]=346,[600347]=347,[600348]=348,[600349]=349,[600350]=350,[600351]=351,
  [600352]=352,[600353]=353,[600354]=354,[600355]=355,[600356]=356,[600357]=357,[600358]=358,
  [600359]=359,[600360]=360,[600361]=361,[600362]=362,[600363]=363,[600364]=364,[600365]=365,
  [600366]=366,[600367]=367,[600368]=368,[600369]=369,[600370]=370,[600371]=371,[600372]=372,
  [600373]=373,[600374]=374,[600375]=375,[600376]=376,[600377]=377,[600378]=378,[600379]=379,
  [600380]=380,[600381]=381,[600382]=382,[600383]=383,[600384]=384,[600385]=385,[600386]=386,
  [600387]=387,[600388]=388,[600389]=389,[600390]=390,[600391]=391,[600392]=392,[600393]=393,
  [600394]=394,[600395]=395,[600396]=396,[600397]=397,[600398]=398,[600399]=399,[600400]=400,
  [600401]=401,[600402]=402,[600403]=403,[600404]=404,[600405]=405,[600406]=406,[600407]=407,
  [600408]=408,[600409]=409,[600410]=410,[600411]=411,[600412]=412,[600413]=413,[600414]=414,
  [600415]=415,[600416]=416,[600417]=417,[600418]=418,[600419]=419,[600420]=420,[600421]=421,
  [600422]=422,[600423]=423,[600424]=424,[600425]=425,[600426]=426,[600427]=427,[600428]=428,
  [600429]=429,[600430]=430,[600431]=431,[600432]=432,[600433]=433,[600434]=434,[600435]=435,
  [600436]=436,[600437]=437,[600438]=438,[600439]=439,[600440]=440,[600441]=441,[600442]=442,
  [600443]=443,[600444]=444,[600445]=445,[600446]=446,[600447]=447,[600448]=448,[600449]=449,
  [600450]=450,[600451]=451,[600452]=452,[600453]=453,[600454]=454,[600455]=455,[600456]=456,
  [600457]=457,[600458]=458,[600459]=459,[600460]=460,[600461]=461,[600462]=462,[600463]=463,
  [600464]=464,[600465]=465,[600466]=466,[600467]=467,[600468]=468,[600469]=469,[600470]=470,
  [600471]=471,[600472]=472,[600473]=473,[600474]=474,[600475]=475,[600476]=476,[600477]=477,
  [600478]=478,[600479]=479,[600480]=480,[600481]=481,[600482]=482,[600483]=483,[600484]=484,
  [600485]=485,[600486]=486,[600487]=487,[600488]=488,[600489]=489,[600490]=490,[600491]=491,
  [600492]=492,[600493]=493,[600494]=494,[600495]=495,[600496]=496,[600497]=497,[600498]=498,
  [600499]=499,[600500]=500,[600501]=501,[600502]=502,[600503]=503,[600504]=504,[600505]=505,
  [600506]=506,[600507]=507,[600508]=508,[600509]=509,[600510]=510,[600511]=511,[600512]=512,
  [600513]=513,[600514]=514,[600515]=515,[600516]=516,[600517]=517,[600518]=518,[600519]=519,
  [600520]=520,[600521]=521,[600522]=522,[600523]=523,[600524]=524,[600525]=525,[600526]=526,
  [600527]=527,[600528]=528,[600529]=529,[600530]=530,[600531]=531,[600532]=532,[600533]=533,
  [600534]=534,[600535]=535,[600536]=536,[600537]=537,[600538]=538,[600539]=539,[600540]=540,
  [600541]=541,[600542]=542,[600543]=543,[600544]=544,[600545]=545,[600546]=546,[600547]=547,
  [600548]=548,[600549]=549,[600550]=550,[600551]=551,[600552]=552,[600553]=553,[600554]=554,
  [600555]=555,[600556]=556,[600557]=557,[600558]=558,[600559]=559,[600560]=560,[600561]=561,
  [600562]=562,[600563]=563,[600564]=564,[600565]=565,[600566]=566,[600567]=567,[600568]=568,
  [600569]=569,[600570]=570,[600571]=571,[600572]=572,[600573]=573,[600574]=574,[600575]=575,
  [600576]=576,[600577]=577,[600578]=578,[600579]=579,[600580]=580,[600581]=581,[600582]=582,
  [600583]=583,[600584]=584,[600585]=585,[600586]=586,[600587]=587,[600588]=588,[600589]=589,
  [600590]=590,[600591]=591,[600592]=592,[600593]=593,[600594]=594,[600595]=595,[600596]=596,
  [600597]=597,[600598]=598,[600599]=599,[600600]=600,[600601]=601,[600602]=602,[600603]=603,
  [600604]=604,[600605]=605,[600606]=606,[600607]=607,[600608]=608,[600609]=609,[600610]=610,
  [600611]=611,[600612]=612,[600613]=613,[600614]=614,[600615]=615,[600616]=616,[600617]=617,
  [600618]=618,[600619]=619,[600620]=620,[600621]=621,[600622]=622,[600623]=623,[600624]=624,
  [600625]=625,[600626]=626,[600627]=627,[600628]=628,[600629]=629,[600630]=630,[600631]=631,
  [600632]=632,[600633]=633,[600634]=634,[600635]=635,[600636]=636,[600637]=637,[600638]=638,
  [600639]=639,[600640]=640,[600641]=641,[600642]=642,[600643]=643,[600644]=644,[600645]=645,
  [600646]=646,[600647]=647,[600648]=648,[600649]=649,
}

-- ── State ─────────────────────────────────────────────────────────────────────
local log_fn            = nil
local mem               = {}
local rom_ok            = nil       -- AP ROM identity (nil=unknown,false=no,true=yes)
local rom_version       = nil       -- "black" / "white" once identified
local why_disabled      = "init() not run"
local server_locations  = nil       -- set of ap_ids the server expects (nil = all)
local reported          = {}        -- ap_id -> true once returned from poll()
local goal_reached      = false
local goal_name         = "ghetsis" -- from slot_data; default = world's Goal default
local dexsanity_on      = true      -- slot_data options.dexsanity != 0
local n_flag, n_dex     = 0, 0

-- Powers of two, indices 0..8 (the [8]=256 entry is needed by the modulo bit
-- test below: testing bit 7 uses POW2[(id%8)+1] = POW2[8]).
local POW2 = { [0]=1, 2, 4, 8, 16, 32, 64, 128, 256 }

local function log(msg)
  if log_fn then pcall(log_fn, "[pokemon_bw] " .. tostring(msg)) end
end

-- ── Memory API (resolved at init; 2-arg domain form + current-domain fallback) ─
local function resolve_memory_api()
  if not memory then return false end
  mem.read_u8  = memory.read_u8     or memory.readbyte
  mem.read_u16 = memory.read_u16_le or memory.readword
  mem.read_u24 = memory.read_u24_le
  mem.read_u32 = memory.read_u32_le or memory.readdword
  mem.read_rng = memory.read_bytes_as_array or memory.readbyterange
  return mem.read_u8 ~= nil
end

local function rd(fn, addr, domain)
  if not fn then return nil end
  local ok, v = pcall(fn, addr, domain)
  if ok and type(v) == "number" then return v end
  ok, v = pcall(fn, addr)                       -- older API: current domain
  if ok and type(v) == "number" then return v end
  return nil
end

local function read_u8(a, d)  return rd(mem.read_u8,  a, d) end
local function read_u16(a, d) return rd(mem.read_u16, a, d) end

-- Read `len` bytes → 1-based array (or nil). Bulk API first (both 0- and 1-based
-- variants normalized), per-byte fallback.
local function read_range(addr, len, domain)
  if mem.read_rng then
    local ok, t = pcall(mem.read_rng, addr, len, domain)
    if ok and type(t) == "table" then
      if t[0] ~= nil then
        local out = {}
        for i = 0, len - 1 do out[i + 1] = t[i] end
        return out
      end
      if t[1] ~= nil or len == 0 then return t end
    end
  end
  local out = {}
  for i = 0, len - 1 do
    local v = read_u8(addr + i, domain)
    if not v then return nil end
    out[i + 1] = v
  end
  return out
end

-- u24 LE read with fallback to three u8 reads (read_u24_le may be absent).
local function read_u24(addr, domain)
  local v = rd(mem.read_u24, addr, domain)
  if v ~= nil then return v end
  local b = read_range(addr, 3, domain)
  if not b then return nil end
  return b[1] + b[2] * 256 + b[3] * 65536
end

-- ── ROM identity: mirror client.validate_rom (18-byte NDS header @ Main RAM) ──
local function header_matches(bytes, sig)
  if #bytes < #sig then return false end
  for i = 1, #sig do
    if bytes[i] ~= string.byte(sig, i) then return false end
  end
  return true
end

local function rom_is_ap()
  if rom_ok ~= nil then return rom_ok end
  local b = read_range(HEADER_ADDR, 18, RAM)
  if not b then return false end                 -- RAM not ready; retry
  if header_matches(b, HEADER_BLACK) then
    rom_ok = true; rom_version = "black"
    log("AP ROM verified: Pokémon Black (IRBO)")
    return true
  end
  if header_matches(b, HEADER_WHITE) then
    rom_ok = true; rom_version = "white"
    log("AP ROM verified: Pokémon White (IRAO)")
    return true
  end
  -- A short/zero header during boot reads as not-yet-ready, not a wrong ROM —
  -- keep rom_ok nil so we retry until the header is populated.
  local nonzero = false
  for i = 1, #b do if b[i] and b[i] ~= 0 then nonzero = true; break end end
  if not nonzero then return false end
  rom_ok = false
  why_disabled = "loaded ROM is not a Pokémon Black/White (US) cartridge — " ..
                 "checks/goal DISABLED"
  log(why_disabled)
  return false
end

-- ── Multiworld context ────────────────────────────────────────────────────────
local function load_locations(ids)
  if type(ids) ~= "table" then return end
  server_locations = {}
  local n = 0
  for _, id in ipairs(ids) do
    local v = tonumber(id)
    if v then server_locations[v] = true; n = n + 1 end
  end
  log("server location set: " .. n .. " ids")
end

local function wanted(ap_id)
  if server_locations == nil then return true end
  return server_locations[ap_id] == true
end

-- Apply slot_data: goal name + dexsanity inclusion (client.early_setup /
-- goals.get_method). Tolerant of the various shapes ctx.config may carry.
local function apply_slot_data(cfg)
  local sd = cfg and (cfg.slot_data or cfg.slotdata)
  if type(sd) ~= "table" then return end
  local opts = sd.options or sd
  if type(opts) == "table" then
    if type(opts.goal) == "string" then goal_name = opts.goal end
    if opts.dexsanity ~= nil then
      local d = tonumber(opts.dexsanity)
      dexsanity_on = not (d == 0)
    end
  end
end

-- ── Bit test in a 1-based byte array ──────────────────────────────────────────
-- flag id // 8 → byte (1-based), id % 8 → bit. (client.get_flag.)
local function bit_set(arr, id)
  local byte = math.floor(id / 8) + 1
  local v = arr[byte]
  if not v then return false end
  return (v % POW2[(id % 8) + 1]) >= POW2[id % 8]
end

-- ── Module contract ───────────────────────────────────────────────────────────
function M.init(ctx)
  if ctx and type(ctx.log) == "function" then log_fn = ctx.log end
  if not ADDRESSES_VERIFIED then
    log("address map not verified — module idle"); return
  end
  if not resolve_memory_api() then
    why_disabled = "BizHawk memory API unavailable"; log(why_disabled)
    ADDRESSES_VERIFIED = false; return
  end
  local cfg = (ctx and ctx.config) or {}
  load_locations(cfg.locations)
  apply_slot_data(cfg)
  for _ in pairs(FLAG_LOC) do n_flag = n_flag + 1 end
  for _ in pairs(DEX_LOC)  do n_dex  = n_dex  + 1 end
  log(string.format("ready: %d flag + %d dex location checks, goal '%s', dexsanity %s",
                    n_flag, n_dex, goal_name, tostring(dexsanity_on)))
end

-- Read the flags block (save-relative). Returns 1-based byte array or nil.
local function read_flags(save_addr)
  return read_range(save_addr + FLAGS_OFF, FLAGS_BYTES, RAM)
end
local function read_dex(save_addr)
  return read_range(save_addr + DEX_OFF, DEX_BYTES, RAM)
end
local function read_var(save_addr, var_idx)
  return read_u16(save_addr + VAR_OFF + 2 * var_idx, RAM)
end

-- Goal evaluation against the freshly-read flags block + on-demand var reads
-- (client.goals.*). flags is the 1-based byte array; save_addr for var reads.
local function goal_met(flags, save_addr)
  local function fset(id) return bit_set(flags, id) end
  local function vge(var, val)
    local v = read_var(save_addr, var)
    return v ~= nil and v >= val
  end
  local function ghetsis()        return fset(GOAL_FLAG_GHETSIS) end
  local function champion()       return fset(GOAL_FLAG_CHAMPION) end
  local function cynthia()        return vge(GOAL_VAR_CYNTHIA, 2) end
  local function cobalion()       return fset(GOAL_FLAG_COBALION) end
  local function tmhm()           return fset(GOAL_FLAG_TMHM) end
  local function seven_sages()    return vge(GOAL_VAR_SAGES, 6) and ghetsis() end
  local function legendary()
    for _, f in ipairs(LEGENDARY_FLAGS) do if not fset(f) then return false end end
    return true
  end

  if     goal_name == "ghetsis"          then return ghetsis()
  elseif goal_name == "champion"         then return champion()
  elseif goal_name == "cynthia"          then return cynthia()
  elseif goal_name == "cobalion"         then return cobalion()
  elseif goal_name == "tmhm_hunt"        then return tmhm()
  elseif goal_name == "seven_sages_hunt" then return seven_sages()
  elseif goal_name == "legendary_hunt"   then return legendary()
  elseif goal_name == "pokemon_master"   then
    return ghetsis() and champion() and cynthia() and cobalion()
       and tmhm() and seven_sages() and legendary()
  else
    return false   -- unknown goal → never auto-complete (client.error)
  end
end

function M.poll()
  local out = {}
  if not ADDRESSES_VERIFIED then return out end
  if not rom_is_ap() then return out end

  -- In-game gate (client.game_watcher: ingame_state byte must be nonzero).
  local state = read_u8(INGAME_STATE, RAM)
  if not state or state == 0 then return out end

  -- Discover the save-data base (client.early_setup).
  local save_addr = read_u24(DATA_ADDR_PTR, RAM)
  if not save_addr or save_addr < SAVE_ADDR_MIN then return out end

  -- Bulk flag read (client.check_flag_locations).
  local flags = read_flags(save_addr)
  if not flags then return out end

  for raw, flag_id in pairs(FLAG_LOC) do
    if not reported[raw] and wanted(raw) and bit_set(flags, flag_id) then
      reported[raw] = true
      out[#out + 1] = raw
    end
  end

  -- Dex reads only when dexsanity is enabled (client.check_dex_locations skips
  -- the read entirely when client.dexsanity_included is false).
  if dexsanity_on then
    local dex = read_dex(save_addr)
    if dex then
      for raw, dex_number in pairs(DEX_LOC) do
        if not reported[raw] and wanted(raw) and bit_set(dex, dex_number - 1) then
          reported[raw] = true
          out[#out + 1] = raw
        end
      end
    end
  end

  -- Goal (client.goal_checking_method for the slot's goal option).
  if not goal_reached and goal_met(flags, save_addr) then
    goal_reached = true
    log("goal '" .. goal_name .. "' satisfied — goal complete")
  end

  return out
end

function M.is_goal_complete()
  return goal_reached
end

-- Remote multiworld items: see the file header. items_handling = 0b111 — the
-- server drives ALL delivery and the reference client WRITES received items into
-- the running game's save RAM (a guarded multi-write, bumping the game's own
-- received-item counter). That is deferred until it can be confirmed in-emulator,
-- rather than shipped unverified — a wrong save-RAM write would corrupt the save.
-- No-op (never a wrong write) until then; the launcher still replays the full
-- item stream, this module just does not consume it yet.
function M.receive_item(item_id, meta)
  -- intentionally empty (documented)
end

return M
