-- ═══════════════════════════════════════════════════════════════════════════════
-- smz3.lua — game module for the Archipelago BizHawk connector.
--          SMZ3 — Super Metroid + A Link to the Past Crossover (SNES)
--
-- STATUS: location DETECTION + goal are REAL and SOURCE-DERIVED from the official
-- AP world worlds/smz3 (Client.py = SMZ3SNIClient, Rom.py, __init__.py,
-- TotalSMZ3/Location.py + TotalSMZ3/Item.py + the whole TotalSMZ3/Regions tree).
-- The two 316-entry location tables below (100 Super Metroid + 216 A Link to the
-- Past) were GENERATED by AST-parsing every Location(self, <Id>, <addr>, ...) call
-- in the Regions tree, applying the exact id math the client uses
--   ap_id = locations_start_id(85000) + convertLocSMZ3IDToAPID(Id)
-- (convertLocSMZ3IDToAPID only shifts Id 486..492 down by 34 — visible in LOC_Z3).
-- Mock-verified through MoonSharp against synthetic SRAM ring-queue records.
-- Loads/runs crash-free on any ROM; self-disables on a non-SMZ3 cartridge.
--
-- items_handling = 0b101 (Client.py validate_rom: "local items and remote start
-- inventory"). The PATCHED GAME grants its own locally-found items, so a SOLO seed
-- plays fully and every check is reported in a multiworld. Delivering REMOTE
-- multiworld items is the RECV-ring-queue write path; it is implemented below
-- exactly as Client.py does it, but held behind REMOTE_ITEMS_VERIFIED=false until
-- it can be confirmed in-emulator (a wrong player/item-id encoding could corrupt a
-- save), so receive_item only RECORDS the stream today. Detection + goal are live.
--
-- MEMORY MODEL (SNI → BizHawk)
-- ────────────────────────────
--   The smz3 client is an SNIClient. SNI/FXPAK addresses translate to BizHawk
--   SNES memory domains (same mapping alttp.lua / super_metroid.lua use):
--     SNI WRAM_START(0xF50000)+off → domain "WRAM"    (= $7E0000+off)
--     SNI SRAM_START(0xE00000)+off → domain "CARTRAM" (fallback "SRAM")
--     SNI ROM_START (0x000000)+off → domain "ROM"     (fallback CARTRAM)
--   The multiworld ring queues + cursors live in SRAM; the active-game flag is in
--   SRAM ($E033FE); the Z3 game-mode byte is WRAM $7E0010 and the SM game-mode
--   byte is WRAM $7E0998. The "ZSM" ROM signature is in the ROM header at $00FFC0.
--
-- HOW SMZ3 CHECKS WORK (a SEND ring queue, like Super Metroid — no flag scan)
--   The SMZ3 basepatch maintains a SEND queue in SRAM: the game appends a record
--   per collected location and bumps a write counter; the client advances a read
--   cursor and turns each record's encoded value into a location id. SMZ3 has TWO
--   on-ROM queue layouts ("old" and "new"/optimized); the client picks between
--   them by ROM-name byte 7 (a digit ⇒ new). Both are implemented here exactly as
--   Client.game_watcher does:
--     • record value → item_index:  is_z3 = (hi & 0x80)≠0; masked = is_z3 ? hi&0x7F
--       : hi; item_index = ((lo | (masked<<8)) >> 3) + (256 if is_z3 else 0).
--       That item_index IS the SMZ3-internal location Id (Z3 ids are 256+n), so
--       ap_id = 85000 + convertLocSMZ3IDToAPID(item_index)  →  LOC_SM / LOC_Z3.
--   The RECV queue (client→game, granted items) is the mirror write path — see
--   receive_item (gated).
--
-- GOAL (Client.game_watcher): the active game is read from SRAM $E033FE (byte 0
--   ≠0 ⇒ Super Metroid is running, else A Link to the Past). When the ACTIVE game
--   reaches its endgame mode — SM ∈ {0x26,0x27} (Mother Brain dead / ending) or
--   Z3 ∈ {0x19,0x1A} (credits) — the run is complete (Defeat Ganon + Mother Brain).
--
-- MODULE CONTRACT (called by bizhawk_ap_connector.lua)
--   M.init(ctx) / M.poll() -> {ids} / M.is_goal_complete() -> bool /
--   M.receive_item(item_id, meta)
-- ═══════════════════════════════════════════════════════════════════════════════

local M = {}
M.name = "smz3"

-- Detection + goal are generated from source and mock-verified — LIVE.
local ADDRESSES_VERIFIED = true
-- Remote multiworld item delivery (RECV-queue writes) — implemented, source-
-- derived, but held inert until verified in-emulator. items_handling=0b101 means
-- local items are granted by the patched game regardless, so a solo seed and all
-- check reporting work with this false; only OTHER-player item delivery waits.
local REMOTE_ITEMS_VERIFIED = false

-- ── Memory domains ────────────────────────────────────────────────────────────
local WRAM    = "WRAM"
local CARTRAM = "CARTRAM"     -- SNES battery SRAM in BizHawk; fallback "SRAM"
local ROM     = "ROM"         -- SNES cartridge ROM in BizHawk; fallback CARTRAM

-- ── SNI-space constants, as BizHawk-domain offsets (Client.py module top) ─────
-- WRAM game-mode bytes.
local Z3_GAMEMODE_OFF = 0x0010            -- WRAM: A Link to the Past main module
local SM_GAMEMODE_OFF = 0x0998            -- WRAM: Super Metroid game-state byte

-- ROM header: first 3 bytes of the name field are "ZSM" on an SMZ3 ROM; byte 7
-- (a digit) selects the new/optimized queue layout (Client.validate_rom).
local ROMNAME_OFF     = 0x00FFC0          -- ROM domain
local ROMNAME_SIZE    = 0x15

-- SRAM ring-queue region. Client.py bases everything on SRAM_START + 0x4000.
local QUEUE_BASE      = 0x4000            -- CARTRAM (SRAM): ptr-table + records base
local CURRENTGAME_OFF = 0x33FE            -- CARTRAM: [0]≠0 ⇒ SM active, else Z3

-- Endgame modes per active game (Client.py ENDGAME / SM_ENDGAME).
local Z3_ENDGAME = { [0x19]=true, [0x1A]=true }     -- credits
local SM_ENDGAME = { [0x26]=true, [0x27]=true }     -- Mother Brain dead / ending

-- In-game modes (Client.SMZ3_INGAME_MODES) — used as a poll gate so the
-- title/demo never reports checks. Both games share these mode byte values.
local INGAME_MODES = { [0x07]=true, [0x09]=true, [0x0B]=true }

-- AP base ids (TotalSMZ3/Location.py + Item.py).
local LOCATIONS_START_ID = 85000
local ITEMS_START_ID     = 84000

-- ROM player-name table is bounded; foreign player ids clamp to 0 (Rom.py
-- ROM_PLAYER_LIMIT = 256, used by Client.game_watcher).
local ROM_PLAYER_LIMIT = 256

-- ── Queue layout variants (Client.game_watcher) ───────────────────────────────
-- All offsets are RELATIVE to QUEUE_BASE. send_msg_byte = index of the value
-- byte pair inside an 8-byte (old) / 2-byte (new) SEND record.
local LAYOUT_OLD = {
  send_ptr_off      = 0x680,   -- u16 read cursor (we own) ; +2 = u16 write count
  send_size         = 8,       -- bytes per SEND record
  send_msg_byte     = 4,       -- value lo/hi at record+4 / +5
  send_table_off    = 0x700,   -- SEND records base
  recv_ptr_off      = 0x600,   -- (data[2..3] here = u16 item_out_ptr)
  recv_size         = 4,       -- bytes per RECV record
  recv_table_off    = 0x602,   -- u16 RECV write cursor (we own)
}
local LAYOUT_NEW = {
  send_ptr_off      = 0xD3C,
  send_size         = 2,
  send_msg_byte     = 0,       -- value lo/hi at record+0 / +1
  send_table_off    = 0xDA0,
  recv_ptr_off      = 0xD36,
  recv_size         = 2,
  recv_table_off    = 0xD38,
}

-- ── Location tables (GENERATED — see header) ──────────────────────────────────
-- SM half: smz3 internal location Id (0..255) -> AP location id. 100 entries.
local LOC_SM = {
  [0]=85000,[1]=85001,[2]=85002,[3]=85003,[4]=85004,[5]=85005,[6]=85006,[7]=85007,
  [8]=85008,[9]=85009,[10]=85010,[11]=85011,[12]=85012,[13]=85013,[14]=85014,[15]=85015,
  [16]=85016,[17]=85017,[18]=85018,[19]=85019,[21]=85021,[22]=85022,[23]=85023,[24]=85024,
  [25]=85025,[26]=85026,[27]=85027,[28]=85028,[29]=85029,[30]=85030,[31]=85031,[33]=85033,
  [34]=85034,[35]=85035,[36]=85036,[37]=85037,[38]=85038,[39]=85039,[40]=85040,[41]=85041,
  [42]=85042,[43]=85043,[44]=85044,[48]=85048,[49]=85049,[50]=85050,[51]=85051,[52]=85052,
  [53]=85053,[54]=85054,[55]=85055,[56]=85056,[57]=85057,[58]=85058,[59]=85059,[60]=85060,
  [61]=85061,[62]=85062,[63]=85063,[64]=85064,[65]=85065,[66]=85066,[67]=85067,[68]=85068,
  [70]=85070,[71]=85071,[73]=85073,[74]=85074,[75]=85075,[76]=85076,[77]=85077,[78]=85078,
  [79]=85079,[80]=85080,[128]=85128,[129]=85129,[130]=85130,[131]=85131,[132]=85132,[133]=85133,
  [134]=85134,[135]=85135,[136]=85136,[137]=85137,[138]=85138,[139]=85139,[140]=85140,[141]=85141,
  [142]=85142,[143]=85143,[144]=85144,[145]=85145,[146]=85146,[147]=85147,[148]=85148,[149]=85149,
  [150]=85150,[151]=85151,[152]=85152,[154]=85154,
}

-- Z3 half: smz3 internal location Id (256..510) -> AP location id. 216 entries.
local LOC_Z3 = {
  [256]=85256,[257]=85257,[258]=85258,[259]=85259,[260]=85260,[261]=85261,[262]=85262,[263]=85263,
  [264]=85264,[265]=85265,[266]=85266,[267]=85267,[268]=85268,[269]=85269,[270]=85270,[271]=85271,
  [272]=85272,[273]=85273,[274]=85274,[275]=85275,[276]=85276,[277]=85277,[278]=85278,[279]=85279,
  [280]=85280,[281]=85281,[282]=85282,[283]=85283,[284]=85284,[285]=85285,[286]=85286,[287]=85287,
  [289]=85289,[290]=85290,[291]=85291,[292]=85292,[293]=85293,[295]=85295,[296]=85296,[297]=85297,
  [298]=85298,[299]=85299,[300]=85300,[301]=85301,[307]=85307,[308]=85308,[309]=85309,[310]=85310,
  [314]=85314,[315]=85315,[316]=85316,[317]=85317,[318]=85318,[319]=85319,[320]=85320,[321]=85321,
  [322]=85322,[323]=85323,[324]=85324,[325]=85325,[326]=85326,[327]=85327,[328]=85328,[329]=85329,
  [330]=85330,[331]=85331,[332]=85332,[333]=85333,[334]=85334,[335]=85335,[336]=85336,[337]=85337,
  [338]=85338,[339]=85339,[340]=85340,[341]=85341,[342]=85342,[343]=85343,[344]=85344,[345]=85345,
  [346]=85346,[347]=85347,[348]=85348,[349]=85349,[350]=85350,[351]=85351,[352]=85352,[353]=85353,
  [354]=85354,[355]=85355,[356]=85356,[357]=85357,[358]=85358,[359]=85359,[360]=85360,[361]=85361,
  [362]=85362,[363]=85363,[364]=85364,[365]=85365,[366]=85366,[367]=85367,[368]=85368,[369]=85369,
  [370]=85370,[371]=85371,[372]=85372,[373]=85373,[374]=85374,[375]=85375,[376]=85376,[377]=85377,
  [378]=85378,[379]=85379,[380]=85380,[381]=85381,[382]=85382,[383]=85383,[384]=85384,[385]=85385,
  [386]=85386,[387]=85387,[388]=85388,[389]=85389,[390]=85390,[391]=85391,[392]=85392,[393]=85393,
  [394]=85394,[395]=85395,[396]=85396,[397]=85397,[398]=85398,[399]=85399,[400]=85400,[401]=85401,
  [402]=85402,[403]=85403,[404]=85404,[405]=85405,[406]=85406,[407]=85407,[408]=85408,[409]=85409,
  [410]=85410,[411]=85411,[412]=85412,[413]=85413,[414]=85414,[415]=85415,[416]=85416,[417]=85417,
  [418]=85418,[419]=85419,[420]=85420,[421]=85421,[422]=85422,[423]=85423,[424]=85424,[425]=85425,
  [426]=85426,[427]=85427,[428]=85428,[429]=85429,[430]=85430,[431]=85431,[432]=85432,[433]=85433,
  [434]=85434,[435]=85435,[436]=85436,[437]=85437,[438]=85438,[439]=85439,[440]=85440,[441]=85441,
  [442]=85442,[443]=85443,[444]=85444,[445]=85445,[446]=85446,[447]=85447,[448]=85448,[449]=85449,
  [450]=85450,[451]=85451,[459]=85459,[460]=85460,[461]=85461,[462]=85462,[463]=85463,[464]=85464,
  [465]=85465,[466]=85466,[467]=85467,[468]=85468,[469]=85469,[470]=85470,[471]=85471,[486]=85452,
  [487]=85453,[488]=85454,[489]=85455,[490]=85456,[491]=85457,[492]=85458,[496]=85496,[497]=85497,
  [498]=85498,[499]=85499,[500]=85500,[506]=85506,[507]=85507,[508]=85508,[509]=85509,[510]=85510,
}

-- ── Internal state ────────────────────────────────────────────────────────────
local server_locations = nil    -- set of ap_ids the server expects (nil = all)
local items_received   = {}     -- ordered stream (extended ITEM lines)
local slot_number      = 0
local layout           = LAYOUT_OLD   -- resolved at ROM check (byte-7 digit ⇒ NEW)
local rom_ok           = nil    -- cached "ZSM" signature result (nil until checked)
local mem              = {}
local log_fn           = nil

-- ── Logging ───────────────────────────────────────────────────────────────────
local function log(msg)
  if log_fn then pcall(log_fn, "[smz3] " .. tostring(msg)) end
end

-- ── Memory API (resolved at init; 2-arg domain form + current-domain fallback) ─
local function resolve_memory_api()
  if not memory then return false end
  mem.read_u8   = memory.read_u8     or memory.readbyte
  mem.read_u16  = memory.read_u16_le or memory.readword
  mem.write_u8  = memory.write_u8    or memory.writebyte
  mem.write_u16 = memory.write_u16_le or memory.writeword
  return mem.read_u8 ~= nil
end

local function rd(fn, addr, domain)
  if not fn then return nil end
  local ok, v = pcall(fn, addr, domain)
  if ok and type(v) == "number" then return v end
  ok, v = pcall(fn, addr)                       -- older API: current domain
  if ok and type(v) == "number" then return v end
  return nil
end

local function read_wram_u8(off) return rd(mem.read_u8, off, WRAM) end

-- ROM-domain read with a CARTRAM fallback (some cores fold the cart header into
-- CARTRAM; the signature lives in the ROM header either way).
local function read_rom_u8(off)
  local ok, v = pcall(mem.read_u8, off, ROM)
  if ok and type(v) == "number" then return v end
  ok, v = pcall(mem.read_u8, off, CARTRAM)
  if ok and type(v) == "number" then return v end
  ok, v = pcall(mem.read_u8, off, "SRAM")
  if ok and type(v) == "number" then return v end
  return nil
end

-- CARTRAM (SRAM) reads/writes with a "SRAM" domain-name fallback.
local function cartram_read_u8(off)
  local ok, v = pcall(mem.read_u8, off, CARTRAM)
  if ok and type(v) == "number" then return v end
  ok, v = pcall(mem.read_u8, off, "SRAM")
  if ok and type(v) == "number" then return v end
  return nil
end
local function cartram_read_u16(off)
  local lo = cartram_read_u8(off); local hi = cartram_read_u8(off + 1)
  if lo == nil or hi == nil then return nil end
  return lo + hi * 256
end
local function cartram_write_u8(off, value)
  if pcall(mem.write_u8, off, value, CARTRAM) then return true end
  return pcall(mem.write_u8, off, value, "SRAM")
end
local function cartram_write_u16(off, value)
  cartram_write_u8(off, value % 256)
  cartram_write_u8(off + 1, math.floor(value / 256) % 256)
end

local function band(a, b)
  -- bitwise AND without the bit library (cores vary).
  local res, bitval = 0, 1
  while a > 0 and b > 0 do
    if a % 2 == 1 and b % 2 == 1 then res = res + bitval end
    a = math.floor(a / 2); b = math.floor(b / 2); bitval = bitval * 2
  end
  return res
end

-- ── ROM identity: the AP basepatch leaves "ZSM" at the ROM-name field, and a
-- digit at byte 7 marks the new/optimized queue layout (Client.validate_rom) ──
local function rom_is_ap()
  if rom_ok ~= nil then return rom_ok end
  local z = read_rom_u8(ROMNAME_OFF)
  local s = read_rom_u8(ROMNAME_OFF + 1)
  local m = read_rom_u8(ROMNAME_OFF + 2)
  if z == nil or s == nil or m == nil then return false end     -- not readable yet
  rom_ok = (z == string.byte("Z") and s == string.byte("S") and m == string.byte("M"))
  if rom_ok then
    -- byte 7 in b"1234567890" ⇒ new message queue (optimized for AP 0.4.4+).
    local b7 = read_rom_u8(ROMNAME_OFF + 7)
    local is_new = b7 ~= nil and ((b7 >= string.byte("1") and b7 <= string.byte("9"))
                                  or b7 == string.byte("0"))
    layout = is_new and LAYOUT_NEW or LAYOUT_OLD
    log(("SMZ3 ROM verified ('ZSM' signature); %s message queue")
        :format(is_new and "new/optimized" or "old"))
  else
    log("non-SMZ3 ROM (no 'ZSM' signature) — detection idle, no writes")
  end
  return rom_ok
end

-- ── Multiworld context ────────────────────────────────────────────────────────
local function load_locations(ids)
  if type(ids) ~= "table" then return end
  server_locations = {}
  local n = 0
  for _, id in ipairs(ids) do
    local v = tonumber(id); if v then server_locations[v] = true; n = n + 1 end
  end
  log("server location set: " .. n .. " ids")
end

local function wanted(ap_id)
  if server_locations == nil then return true end   -- no set provided → report all
  return server_locations[ap_id] == true
end

-- Convert a decoded SEND-queue item_index (= smz3 internal location Id, Z3 ids are
-- 256+n) into an AP location id via the generated tables. nil for unknown ids.
local function smz3_index_to_ap(item_index)
  if item_index >= 256 then return LOC_Z3[item_index] end
  return LOC_SM[item_index]
end

-- Item-stream filter, same policy as the other SNES modules: items_handling=0b101
-- means the patched game grants own-world found items itself, so own-world entries
-- are dropped here; server/starting-inventory (player 0, no location) too.
local function accept_item(it)
  if it.player == nil then return true end          -- legacy ITEM:<id> line
  if it.player == 0 and (it.location or 0) <= 0 then return false end
  if it.player == slot_number then return false end -- our own items: game grants them
  return true
end

local function delivery_list()
  local out = {}
  for _, it in ipairs(items_received) do
    if accept_item(it) then out[#out + 1] = it end
  end
  return out
end

-- ── Active-game + gameplay gates ──────────────────────────────────────────────
-- Returns "sm", "z3" or nil. Mirrors Client: SRAM $33FE byte0 ≠0 ⇒ SM.
local function active_game()
  local cg = cartram_read_u8(CURRENTGAME_OFF)
  if cg == nil then return nil end
  return cg ~= 0 and "sm" or "z3"
end

local function game_mode()
  local g = active_game()
  if g == "sm" then return read_wram_u8(SM_GAMEMODE_OFF), g end
  if g == "z3" then return read_wram_u8(Z3_GAMEMODE_OFF), g end
  return nil, nil
end

local function in_gameplay()
  local m = game_mode()
  return m ~= nil and INGAME_MODES[m] == true
end

-- ── Module contract ───────────────────────────────────────────────────────────

function M.init(ctx)
  if ctx and type(ctx.log) == "function" then log_fn = ctx.log end
  if not resolve_memory_api() then
    log("BizHawk memory API unavailable — module idle")
    ADDRESSES_VERIFIED = false
    return
  end
  local cfg = (ctx and ctx.config) or {}
  slot_number = tonumber(cfg.slot_number) or 0
  load_locations(cfg.locations)

  local n = 0
  for _ in pairs(LOC_SM) do n = n + 1 end
  for _ in pairs(LOC_Z3) do n = n + 1 end
  log(("ready: slot #%d, %d location ids (detection live; remote-item delivery %s)")
      :format(slot_number, n,
              REMOTE_ITEMS_VERIFIED and "live" or "recorded-only (gated)"))
end

function M.poll()
  local new = {}
  if not ADDRESSES_VERIFIED then return new end
  if not rom_is_ap() then return new end
  if not in_gameplay() then return new end

  -- SEND queue: ptr table at QUEUE_BASE+send_ptr_off holds [read_u16, write_u16].
  local read_idx  = cartram_read_u16(QUEUE_BASE + layout.send_ptr_off)
  local write_cnt = cartram_read_u16(QUEUE_BASE + layout.send_ptr_off + 2)
  if read_idx == nil or write_cnt == nil then return new end

  local guard = 0
  while read_idx < write_cnt and guard < 512 do
    guard = guard + 1
    local rec = QUEUE_BASE + layout.send_table_off + read_idx * layout.send_size
    local lo = cartram_read_u8(rec + layout.send_msg_byte)
    local hi = cartram_read_u8(rec + layout.send_msg_byte + 1)
    if lo == nil or hi == nil then break end

    -- Client.game_watcher decode: Z3 items flag the high bit of the hi byte.
    local is_z3   = band(hi, 0x80) ~= 0
    local masked  = is_z3 and band(hi, 0x7F) or hi
    local item_index = math.floor((lo + masked * 256) / 8) + (is_z3 and 256 or 0)

    local ap_id = smz3_index_to_ap(item_index)
    if ap_id and wanted(ap_id) then new[#new + 1] = ap_id end

    read_idx = read_idx + 1
    cartram_write_u16(QUEUE_BASE + layout.send_ptr_off, read_idx)   -- advance cursor
  end
  return new
end

function M.is_goal_complete()
  if not ADDRESSES_VERIFIED or not rom_is_ap() then return false end
  local m, g = game_mode()
  if m == nil then return false end
  if g == "sm" then return SM_ENDGAME[m] == true end
  return Z3_ENDGAME[m] == true
end

-- Record the grant, then (when verified) push pending REMOTE items into the RECV
-- ring and bump the write cursor — the mirror of Client.game_watcher's recv path.
-- Held behind REMOTE_ITEMS_VERIFIED until confirmed in-emulator; until then this
-- only records the stream (own-world items are granted by the patched game).
function M.receive_item(item_id, meta)
  if type(meta) == "table" then
    items_received[#items_received + 1] = {
      item     = tonumber(item_id),
      index    = tonumber(meta.index),
      player   = tonumber(meta.player),
      flags    = tonumber(meta.flags),
      location = tonumber(meta.locId),
    }
  else
    items_received[#items_received + 1] = { item = tonumber(item_id) }
  end

  if not (ADDRESSES_VERIFIED and REMOTE_ITEMS_VERIFIED) then return end
  if not rom_is_ap() or not in_gameplay() then return end

  -- RECV queue (Client.game_watcher): item_out_ptr = u16 at recv_ptr_off+2.
  local out_ptr = cartram_read_u16(QUEUE_BASE + layout.recv_ptr_off + 2)
  if out_ptr == nil then return end

  local list = delivery_list()
  local guard = 0
  while out_ptr < #list and guard < 512 do
    guard = guard + 1
    local it = list[out_ptr + 1]
    if not it or not it.item then break end

    local g_item_id = band((it.item or 0) - ITEMS_START_ID, 0xFFFF)
    local pid = it.player or 0
    if pid >= ROM_PLAYER_LIMIT then pid = 0 end

    local rec = QUEUE_BASE + out_ptr * layout.recv_size
    if layout.recv_size == 2 then
      -- new queue: bytes([player_id, item_id])  (single byte each)
      cartram_write_u8(rec + 0, band(pid, 0xFF))
      cartram_write_u8(rec + 1, band(g_item_id, 0xFF))
    else
      -- old queue: bytes([pid&0xFF, pid>>8, item&0xFF, item>>8])
      cartram_write_u8(rec + 0, band(pid, 0xFF))
      cartram_write_u8(rec + 1, band(math.floor(pid / 256), 0xFF))
      cartram_write_u8(rec + 2, band(g_item_id, 0xFF))
      cartram_write_u8(rec + 3, band(math.floor(g_item_id / 256), 0xFF))
    end

    out_ptr = out_ptr + 1
    cartram_write_u16(QUEUE_BASE + layout.recv_table_off, out_ptr)
  end
end

return M
