-- ═══════════════════════════════════════════════════════════════════════════════
-- "The Minish Cap.lua" — game module for the Archipelago BizHawk connector.
--                        The Legend of Zelda: The Minish Cap (GBA)
--
-- COMMUNITY APWORLD — this game is NOT in ArchipelagoMW/Archipelago main.
--   Source : https://github.com/eternalcode0/TMC-APWorld   (world_version 0.3.1)
--   World id ("game"): "The Minish Cap"   (tmc/archipelago.json)
--   Authors: EternalCode, Myth197
--
-- STATUS: location DETECTION + goal + item delivery are SOURCE-DERIVED from the
-- official community AP world tmc/ (client.py + locations.py + rom.py, main
-- branch). The 511-entry LOC table below was GENERATED by parsing locations.py
-- (`all_locations`, every entry with a real EWRAM `ram_addr`), NOT hand-copied,
-- and the check / goal / item-delivery math replicates MinishCapClient.game_watcher
-- byte-for-byte. Loads crash-free on any ROM and self-disables on a non-AP /
-- non-Minish-Cap cartridge.
--
-- MEMORY MODEL (BizHawk GBA domains — exactly the domains client.py reads)
-- ────────────────────────────────────────────────────────────────────────
--   "ROM"   cartridge: the 8-byte game identifier "GBAZELDA" @0xA0 (validate_rom),
--           the AP-patched player-name marker @0x600 (16 bytes; zero on a vanilla
--           cartridge — this is what distinguishes an AP ROM from a stock dump).
--   "IWRAM" internal RAM: game_task @0x1002, task_substate @0x1004 (gameplay gate
--           + goal), room/area id @0x0BF4 (u16 LE).
--   "EWRAM" work RAM: every location flag (per-location `ram_addr` byte), the
--           received-item index @0x2A44 (u16 BE), the item-delivery mailbox
--           @0x3FF10 + the "player safe" guard byte @0x2A4A, and the goal
--           trigger (game_task transitions to 0x04 on Vaati's defeat).
--
-- DETECTION (handle_location_sending, client.py line ~285)
--   For each server location with a readable `ram_addr = (addr, mask)`:
--     checked  when  (EWRAM[addr] | mask) == EWRAM[addr]      (ALL mask bits set)
--   This is the exact client predicate `loc_ram[0] | mask == loc_ram[0]` (Python
--   `|` binds tighter than `==`). Gated to the slot's server location set and to
--   the in-gameplay state so the title/file screens never report a check.
--
-- GOAL (game_watcher line ~236): game_task == 0x04. Vaati's defeat triggers a
--   cutscene that sets game_task to 0x04 — the client sends CLIENT_GOAL on that
--   transition. (Goal=Pedestal seeds patch the stained-glass scene to jump to the
--   same credits path, so this single trigger covers both goal options.)
--
-- ITEM DELIVERY (items_handling = 0b101: remote items + starting inventory)
-- ──────────────────────────────────────────────────────────────────────────
--   The Minish Cap is NOT a self-granting ROM for remote items. The client hands
--   the patched game each received item by writing the 2-byte AP item id
--   (pid = id>>8, sid = id&0xFF) into the EWRAM mailbox @0x3FF10, GUARDED so it
--   only writes while the mailbox reads [0,0] AND the ROM's "player safe" byte
--   @0x2A4A == 1 (set by the game when it is safe to receive). On a confirmed
--   write the game's ASM consumes the mailbox (zeroes it) and the client advances
--   the received-item counter (u16 BE @0x2A44). We replicate that exact guarded
--   handshake: one item per poll, indexed by the game's own received counter, and
--   EVERY write is gated behind the AP-ROM identity AND the in-gameplay state, so
--   the module can never write into a foreign or unpatched cartridge.
--   (remote_items=true upgrades the server to items_handling 0b111 client-side;
--   that path only changes WHICH items the server sends, not how we deliver them.)
--
-- NOT COVERED (documented, gated out so they are never falsely reported)
--   • 15 Goron Merchant slots (ids 6029034-6029048) and 100 Kinstone Fusion
--     locations (ids 6029601-6029700) have `ram_addr = None` in the source — the
--     client resolves them through its bit-counting `handle_special_sending`
--     (EWRAM 0x2CA3) and its event/data-store path, NOT a readable flag. Those
--     intricate stateful paths are deferred until they can be confirmed in-
--     emulator; their ids are filtered so this module never claims them.
--
-- MODULE CONTRACT (called by bizhawk_ap_connector.lua)
--   M.init(ctx) / M.poll() -> {ids} / M.is_goal_complete() -> bool /
--   M.receive_item(item_id, meta)
-- ═══════════════════════════════════════════════════════════════════════════════

local M = {}
M.name = "The Minish Cap"

local ADDRESSES_VERIFIED = true   -- table generated from tmc/locations.py source

-- ── Memory domains ────────────────────────────────────────────────────────────
local EWRAM = "EWRAM"
local IWRAM = "IWRAM"
local ROM   = "ROM"

-- ── Addresses / constants (tmc/client.py ROM_ADDRS + RAM_ADDRS) ───────────────
local ROM_NAME_ADDR     = 0xA0        -- ROM: 8-byte game identifier
local ROM_NAME          = "GBAZELDA"  -- validate_rom exact match
local AP_MARKER_ADDR    = 0x600       -- ROM: AP-patched player name (zero on vanilla)
local AP_MARKER_LEN     = 16

local GAME_TASK_ADDR    = 0x1002      -- IWRAM: 0x02 = in-game update, 0x04 = goal cutscene
local TASK_SUBSTATE_ADDR = 0x1004     -- IWRAM: 0x02 = update substate
local GAME_TASK_GAMEPLAY = 0x02
local GAME_TASK_GOAL     = 0x04

local RECV_INDEX_ADDR   = 0x2A44      -- EWRAM: received-item index (u16 BE)
local ITEM_MAILBOX_ADDR = 0x3FF10     -- EWRAM: 2-byte item mailbox (guarded write)
local PLAYER_SAFE_ADDR  = 0x2A4A      -- EWRAM: "player safe" guard byte (== 1 when safe)

-- ── Location table (GENERATED from tmc/locations.py `all_locations`) ──────────
-- ap_id -> {EWRAM addr, bit mask}. 511 entries (every location with a readable
-- ram_addr). Checked when (EWRAM[addr] | mask) == EWRAM[addr].
local LOC = {
  [6029000]={0x2CDE,0x40},[6029001]={0x2CF5,0x01},[6029002]={0x2CF5,0x02},[6029003]={0x2D1E,0x20},
  [6029004]={0x2D1E,0x40},[6029005]={0x2D1E,0x80},[6029006]={0x2D1F,0x01},[6029007]={0x2D1F,0x02},
  [6029008]={0x2D1F,0x04},[6029009]={0x2D1F,0x08},[6029010]={0x2D1F,0x10},[6029011]={0x2D1F,0x20},
  [6029012]={0x2D1F,0x40},[6029013]={0x2D1F,0x80},[6029014]={0x2D20,0x01},[6029015]={0x2D20,0x02},
  [6029016]={0x2D20,0x04},[6029017]={0x2D20,0x08},[6029018]={0x2CD3,0x02},[6029019]={0x2CEE,0x80},
  [6029020]={0x2D2C,0x02},[6029021]={0x2CA3,0x04},[6029022]={0x2CD6,0x40},[6029023]={0x2EA7,0x01},
  [6029024]={0x2EA7,0x02},[6029025]={0x2EA7,0x04},[6029026]={0x2EA8,0x04},[6029027]={0x2CE6,0x08},
  [6029028]={0x2D0A,0x80},[6029029]={0x2D13,0x20},[6029030]={0x2CF3,0x01},[6029031]={0x2CD5,0x01},
  [6029032]={0x2CE0,0x80},[6029033]={0x2CFD,0x01},[6029049]={0x2EA5,0x10},[6029050]={0x2EA5,0x20},
  [6029051]={0x2EA5,0x40},[6029052]={0x2EA5,0x80},[6029053]={0x2CFC,0x40},[6029054]={0x2CD5,0x02},
  [6029055]={0x2D11,0x01},[6029056]={0x2D0B,0x80},[6029057]={0x2D0C,0x01},[6029058]={0x2D0C,0x02},
  [6029059]={0x2D0B,0x40},[6029060]={0x2D04,0x04},[6029061]={0x2D04,0x08},[6029062]={0x2D04,0x10},
  [6029063]={0x2CFC,0x80},[6029064]={0x2CD5,0x20},[6029065]={0x2D1D,0x40},[6029066]={0x2EA5,0x02},
  [6029067]={0x2CFD,0x02},[6029068]={0x2CA5,0x08},[6029069]={0x2CA5,0x10},[6029070]={0x2CA5,0x18},
  [6029071]={0x2CA5,0x20},[6029072]={0x2CA5,0x28},[6029073]={0x2CA5,0x30},[6029074]={0x2CA5,0x38},
  [6029075]={0x2CA5,0x40},[6029076]={0x2CA5,0x48},[6029077]={0x2CA5,0x80},[6029078]={0x2EA4,0x10},
  [6029079]={0x2C9C,0x02},[6029080]={0x2EA4,0x08},[6029081]={0x2CF2,0x20},[6029082]={0x2CF2,0x40},
  [6029083]={0x2CF2,0x80},[6029084]={0x2CF2,0x10},[6029085]={0x2CFD,0x04},[6029086]={0x2EA4,0x20},
  [6029087]={0x2CFD,0x80},[6029088]={0x2CFE,0x01},[6029089]={0x2D14,0x08},[6029090]={0x2CEB,0x01},
  [6029091]={0x2CFE,0x20},[6029092]={0x2CFE,0x10},[6029093]={0x2CFE,0x08},[6029094]={0x2CCD,0x20},
  [6029095]={0x2D2B,0x08},[6029096]={0x2D1C,0x10},[6029097]={0x2D1C,0x20},[6029098]={0x2D1C,0x40},
  [6029099]={0x2D1C,0x80},[6029100]={0x2D1D,0x01},[6029101]={0x2EA6,0x40},[6029102]={0x2CBE,0x04},
  [6029103]={0x2CBE,0x08},[6029104]={0x2CA2,0x20},[6029105]={0x2D0E,0x10},[6029106]={0x2D2C,0x08},
  [6029107]={0x2EA6,0x02},[6029108]={0x2D28,0x10},[6029109]={0x2D28,0x20},[6029110]={0x2C9E,0x40},
  [6029112]={0x2CA2,0x10},[6029113]={0x2CD2,0x04},[6029114]={0x2D0D,0x04},[6029115]={0x2D0D,0x01},
  [6029116]={0x2D0D,0x02},[6029117]={0x2D22,0x08},[6029118]={0x2CEF,0x80},[6029119]={0x2D04,0x40},
  [6029120]={0x2CE5,0x20},[6029121]={0x2D1E,0x10},[6029122]={0x2D1D,0x80},[6029123]={0x2D1E,0x04},
  [6029124]={0x2D11,0x02},[6029125]={0x2D13,0x04},[6029126]={0x2CCB,0x20},[6029127]={0x2CF2,0x04},
  [6029128]={0x2D2A,0x80},[6029129]={0x2D2A,0x40},[6029130]={0x2CD3,0x40},[6029131]={0x2CD1,0x02},
  [6029132]={0x2EA6,0x20},[6029133]={0x2CD0,0x04},[6029134]={0x2CD0,0x08},[6029135]={0x2CD0,0x10},
  [6029136]={0x2D05,0x08},[6029137]={0x2D05,0x10},[6029138]={0x2CBD,0x02},[6029139]={0x2B3F,0x20},
  [6029140]={0x2CBD,0x01},[6029141]={0x2D02,0x80},[6029142]={0x2D03,0x02},[6029143]={0x2D03,0x04},
  [6029144]={0x2D03,0x08},[6029145]={0x2D03,0x10},[6029146]={0x2D03,0x20},[6029147]={0x2D03,0x40},
  [6029148]={0x2CCB,0x10},[6029149]={0x2D0C,0x20},[6029150]={0x2D0C,0x10},[6029151]={0x2D0C,0x40},
  [6029152]={0x2D02,0x40},[6029154]={0x2CBD,0x04},[6029155]={0x2D2C,0x04},[6029156]={0x2EA6,0x04},
  [6029157]={0x2CF2,0x08},[6029158]={0x2D2A,0x04},[6029159]={0x2D28,0x04},[6029160]={0x2D11,0x10},
  [6029161]={0x2EA4,0x40},[6029162]={0x2CA3,0x01},[6029163]={0x2EA4,0x04},[6029164]={0x2D02,0x08},
  [6029165]={0x2CD2,0x08},[6029166]={0x2CC3,0x08},[6029167]={0x2CD3,0x01},[6029168]={0x2D02,0x10},
  [6029169]={0x2D02,0x20},[6029170]={0x2CD2,0x20},[6029171]={0x2CD2,0x80},[6029172]={0x2CC3,0x10},
  [6029173]={0x2CF0,0x08},[6029174]={0x2D11,0x04},[6029175]={0x2CF5,0x04},[6029176]={0x2CF4,0x04},
  [6029178]={0x2EA5,0x01},[6029179]={0x2CF2,0x01},[6029180]={0x2CDB,0x08},[6029181]={0x2D2A,0x08},
  [6029182]={0x2D2A,0x10},[6029183]={0x2D2A,0x20},[6029184]={0x2D2B,0x04},[6029185]={0x2CD3,0x10},
  [6029186]={0x2CD2,0x40},[6029187]={0x2D04,0x80},[6029188]={0x2D05,0x02},[6029189]={0x2D05,0x01},
  [6029190]={0x2CA7,0x04},[6029191]={0x2D1D,0x20},[6029192]={0x2D20,0x10},[6029193]={0x2D20,0x20},
  [6029194]={0x2D20,0x40},[6029195]={0x2D20,0x80},[6029196]={0x2D21,0x01},[6029197]={0x2D21,0x02},
  [6029198]={0x2D21,0x04},[6029199]={0x2D21,0x08},[6029200]={0x2D21,0x10},[6029201]={0x2D21,0x20},
  [6029202]={0x2D21,0x40},[6029203]={0x2D21,0x80},[6029204]={0x2D22,0x01},[6029205]={0x2D22,0x02},
  [6029206]={0x2D22,0x04},[6029207]={0x2CCF,0x10},[6029208]={0x2CEF,0x01},[6029209]={0x2CCE,0x08},
  [6029210]={0x2CCE,0x10},[6029211]={0x2CCE,0x20},[6029212]={0x2CCE,0x40},[6029213]={0x2CCE,0x80},
  [6029214]={0x2CCF,0x01},[6029215]={0x2CE4,0x04},[6029216]={0x2CE3,0x80},[6029217]={0x2CCF,0x02},
  [6029218]={0x2CCF,0x04},[6029219]={0x2CA3,0x02},[6029220]={0x2D0D,0x08},[6029221]={0x2D0D,0x10},
  [6029222]={0x2D0D,0x20},[6029223]={0x2D0D,0x40},[6029224]={0x2D0D,0x80},[6029225]={0x2D0E,0x01},
  [6029226]={0x2D0E,0x02},[6029227]={0x2D0E,0x04},[6029228]={0x2D0E,0x08},[6029229]={0x2D0F,0x40},
  [6029230]={0x2D0F,0x80},[6029231]={0x2D10,0x01},[6029232]={0x2D10,0x02},[6029233]={0x2D10,0x04},
  [6029234]={0x2D10,0x08},[6029235]={0x2D10,0x10},[6029236]={0x2D10,0x20},[6029237]={0x2CC5,0x02},
  [6029238]={0x2D24,0x08},[6029239]={0x2D24,0x10},[6029240]={0x2D24,0x20},[6029241]={0x2D10,0x80},
  [6029242]={0x2CD4,0x02},[6029243]={0x2D24,0x02},[6029244]={0x2D24,0x04},[6029245]={0x2D24,0x01},
  [6029246]={0x2D28,0x01},[6029247]={0x2CDE,0x02},[6029248]={0x2CA2,0x04},[6029249]={0x2D23,0x80},
  [6029250]={0x2D2B,0x20},[6029251]={0x2CA2,0x80},[6029252]={0x2EA5,0x04},[6029253]={0x2D1C,0x02},
  [6029254]={0x2D1C,0x04},[6029255]={0x2D2C,0x01},[6029256]={0x2EA6,0x01},[6029257]={0x2CF0,0x01},
  [6029258]={0x2CD4,0x01},[6029259]={0x2D04,0x20},[6029260]={0x2D0C,0x08},[6029261]={0x2D0E,0x40},
  [6029262]={0x2D0E,0x80},[6029263]={0x2D0F,0x01},[6029264]={0x2D0F,0x02},[6029265]={0x2D0F,0x04},
  [6029266]={0x2D0F,0x08},[6029267]={0x2D0F,0x10},[6029268]={0x2D0F,0x20},[6029269]={0x2D10,0x40},
  [6029270]={0x2D23,0x20},[6029271]={0x2D11,0x08},[6029272]={0x2CF3,0x02},[6029273]={0x2CF4,0x01},
  [6029274]={0x2CF3,0x80},[6029275]={0x2CF3,0x40},[6029276]={0x2CF3,0x20},[6029277]={0x2CF3,0x10},
  [6029278]={0x2CF3,0x04},[6029279]={0x2CF3,0x08},[6029281]={0x2EA7,0x10},[6029282]={0x2D23,0x04},
  [6029283]={0x2CBD,0x10},[6029284]={0x2CA2,0x08},[6029285]={0x2D23,0x01},[6029286]={0x2EA6,0x10},
  [6029287]={0x2D22,0x40},[6029288]={0x2D04,0x01},[6029289]={0x2D04,0x02},[6029290]={0x2CC0,0x04},
  [6029291]={0x2CC0,0x08},[6029292]={0x2CC0,0x10},[6029293]={0x2D22,0x10},[6029294]={0x2D2B,0x80},
  [6029295]={0x2EA6,0x08},[6029296]={0x2CDE,0x08},[6029297]={0x2CDE,0x01},[6029298]={0x2CF0,0x20},
  [6029299]={0x2CDE,0x10},[6029300]={0x2CDE,0x20},[6029301]={0x2D2C,0x20},[6029302]={0x2D2C,0x10},
  [6029303]={0x2EA7,0x08},[6029304]={0x2D22,0x80},[6029305]={0x2CDE,0x04},[6029306]={0x2CD4,0x04},
  [6029307]={0x2D0C,0x80},[6029308]={0x2CF0,0x10},[6029309]={0x2D2B,0x40},[6029310]={0x2CC2,0x08},
  [6029311]={0x2CC2,0x10},[6029312]={0x2CA2,0x02},[6029313]={0x2CD2,0x10},[6029315]={0x2CD3,0x20},
  [6029316]={0x2CEF,0x40},[6029317]={0x2CC7,0x04},[6029318]={0x2CE9,0x02},[6029319]={0x2EA7,0x20},
  [6029320]={0x2CD3,0x04},[6029321]={0x2D27,0x20},[6029322]={0x2CD3,0x08},[6029323]={0x2D27,0x40},
  [6029325]={0x2D14,0x10},[6029326]={0x2D14,0x20},[6029327]={0x2D12,0x40},[6029328]={0x2D12,0x80},
  [6029329]={0x2D02,0x04},[6029330]={0x2CD0,0x01},[6029331]={0x2D05,0x20},[6029332]={0x2D05,0x04},
  [6029333]={0x2D25,0x10},[6029334]={0x2CD0,0x02},[6029335]={0x2CDA,0x80},[6029336]={0x2CA2,0x40},
  [6029337]={0x2CD0,0x80},[6029338]={0x2CD3,0x80},[6029339]={0x2D27,0x10},[6029340]={0x2D25,0x20},
  [6029341]={0x2D25,0x40},[6029342]={0x2D25,0x80},[6029343]={0x2D26,0x01},[6029344]={0x2D26,0x02},
  [6029345]={0x2D26,0x04},[6029346]={0x2D26,0x08},[6029347]={0x2D26,0x10},[6029348]={0x2D26,0x20},
  [6029349]={0x2D26,0x40},[6029350]={0x2D26,0x80},[6029351]={0x2D27,0x01},[6029352]={0x2D27,0x02},
  [6029353]={0x2D27,0x04},[6029354]={0x2D27,0x08},[6029355]={0x2D25,0x04},[6029356]={0x2D25,0x01},
  [6029357]={0x2CD1,0x10},[6029358]={0x2CD7,0x08},[6029359]={0x2CD8,0x08},[6029360]={0x2CDA,0x02},
  [6029361]={0x2CD7,0x80},[6029362]={0x2CD7,0x40},[6029363]={0x2CD8,0x04},[6029364]={0x2CD7,0x20},
  [6029365]={0x2CD8,0x01},[6029366]={0x2CD8,0x40},[6029367]={0x2CD7,0x10},[6029368]={0x2CD8,0x10},
  [6029369]={0x2CDA,0x08},[6029370]={0x2CD8,0x02},[6029371]={0x2CD8,0x80},[6029372]={0x2CD9,0x01},
  [6029373]={0x2CD8,0x20},[6029374]={0x2CDC,0x20},[6029375]={0x2CDC,0x40},[6029376]={0x2CDC,0x80},
  [6029377]={0x2CE8,0x20},[6029378]={0x2CE8,0x40},[6029379]={0x2CDD,0x04},[6029380]={0x2CDD,0x02},
  [6029381]={0x2CDD,0x01},[6029382]={0x2CDD,0x40},[6029383]={0x2CDD,0x80},[6029385]={0x2D45,0x04},
  [6029386]={0x2D43,0x20},[6029387]={0x2D41,0x08},[6029388]={0x2D41,0x02},[6029389]={0x2D40,0x80},
  [6029390]={0x2D42,0x01},[6029391]={0x2D40,0x10},[6029392]={0x2D44,0x04},[6029393]={0x2D44,0x02},
  [6029394]={0x2D45,0x80},[6029395]={0x2D40,0x04},[6029396]={0x2D40,0x08},[6029397]={0x2D3F,0x08},
  [6029398]={0x2D46,0x04},[6029399]={0x2D43,0x80},[6029400]={0x2D44,0x80},[6029401]={0x2C9C,0x04},
  [6029402]={0x2D5A,0x04},[6029403]={0x2D5B,0x40},[6029404]={0x2D5B,0x80},[6029405]={0x2D5C,0x01},
  [6029406]={0x2D5C,0x02},[6029407]={0x2D5C,0x04},[6029408]={0x2D59,0x04},[6029409]={0x2D59,0x02},
  [6029410]={0x2D58,0x80},[6029411]={0x2D58,0x40},[6029412]={0x2D57,0x01},[6029413]={0x2D5B,0x10},
  [6029414]={0x2D57,0x02},[6029415]={0x2D59,0x10},[6029416]={0x2D59,0x20},[6029417]={0x2D5A,0x01},
  [6029418]={0x2D5B,0x01},[6029419]={0x2D5A,0x80},[6029420]={0x2D5B,0x02},[6029421]={0x2D5B,0x04},
  [6029422]={0x2C9C,0x08},[6029423]={0x2EA4,0x80},[6029424]={0x2D05,0x80},[6029425]={0x2D74,0x08},
  [6029426]={0x2D05,0x40},[6029427]={0x2D06,0x01},[6029428]={0x2D06,0x20},[6029429]={0x2D06,0x40},
  [6029450]={0x2D06,0x80},[6029451]={0x2D07,0x01},[6029452]={0x2D07,0x08},[6029453]={0x2D07,0x04},
  [6029454]={0x2D07,0x02},[6029455]={0x2D07,0x20},[6029456]={0x2D6F,0x10},[6029457]={0x2D73,0x80},
  [6029458]={0x2D73,0x02},[6029459]={0x2D06,0x02},[6029460]={0x2D73,0x20},[6029461]={0x2D73,0x40},
  [6029462]={0x2D06,0x04},[6029463]={0x2D07,0x40},[6029464]={0x2D74,0x02},[6029465]={0x2D74,0x80},
  [6029466]={0x2D08,0x01},[6029467]={0x2D08,0x02},[6029468]={0x2D71,0x40},[6029469]={0x2D08,0x10},
  [6029470]={0x2D06,0x08},[6029471]={0x2D06,0x10},[6029472]={0x2D73,0x04},[6029473]={0x2D72,0x04},
  [6029474]={0x2D74,0x20},[6029475]={0x2D8E,0x04},[6029476]={0x2D8D,0x80},[6029477]={0x2D94,0x20},
  [6029478]={0x2D94,0x40},[6029479]={0x2D94,0x80},[6029480]={0x2D95,0x01},[6029481]={0x2D95,0x02},
  [6029482]={0x2D8B,0x80},[6029483]={0x2D96,0x20},[6029484]={0x2D96,0x40},[6029485]={0x2D96,0x80},
  [6029486]={0x2D97,0x01},[6029487]={0x2D97,0x02},[6029488]={0x2D97,0x04},[6029489]={0x2D95,0x80},
  [6029490]={0x2D96,0x01},[6029491]={0x2D96,0x02},[6029492]={0x2D96,0x04},[6029493]={0x2D96,0x08},
  [6029494]={0x2D96,0x10},[6029495]={0x2D93,0x04},[6029496]={0x2D92,0x80},[6029497]={0x2D8F,0x04},
  [6029498]={0x2D8F,0x08},[6029499]={0x2D93,0x40},[6029500]={0x2D8B,0x01},[6029501]={0x2D8B,0x04},
  [6029502]={0x2D8B,0x02},[6029503]={0x2D8D,0x10},[6029504]={0x2D8C,0x80},[6029505]={0x2D92,0x40},
  [6029506]={0x2D8F,0x80},[6029507]={0x2D91,0x80},[6029508]={0x2D8F,0x20},[6029509]={0x2D8F,0x40},
  [6029510]={0x2D95,0x04},[6029511]={0x2D95,0x08},[6029512]={0x2D95,0x10},[6029513]={0x2D95,0x20},
  [6029514]={0x2D95,0x40},[6029515]={0x2D8C,0x01},[6029516]={0x2C9C,0x20},[6029517]={0x2DAA,0x40},
  [6029518]={0x2DAA,0x10},[6029519]={0x2DA7,0x04},[6029520]={0x2DA7,0x08},[6029521]={0x2DA7,0x10},
  [6029522]={0x2DA7,0x20},[6029523]={0x2DA7,0x40},[6029524]={0x2DA7,0x02},[6029525]={0x2DA4,0x80},
  [6029526]={0x2DA4,0x02},[6029527]={0x2DA3,0x40},[6029528]={0x2DA2,0x10},[6029529]={0x2DAB,0x02},
  [6029530]={0x2DAB,0x04},[6029531]={0x2DA9,0x80},[6029532]={0x2DA9,0x40},[6029533]={0x2DA6,0x80},
  [6029534]={0x2DAC,0x01},[6029535]={0x2DA5,0x80},[6029536]={0x2DA2,0x20},[6029537]={0x2DA5,0x02},
  [6029538]={0x2DA2,0x80},[6029539]={0x2DAB,0x20},[6029540]={0x2C9C,0x40},[6029541]={0x2EA7,0x80},
  [6029542]={0x2EA8,0x01},[6029543]={0x2EA8,0x02},[6029544]={0x2DC2,0x02},[6029545]={0x2DC1,0x08},
  [6029546]={0x2DC0,0x20},[6029547]={0x2DBF,0x80},[6029548]={0x2DBB,0x40},[6029549]={0x2DBB,0x80},
  [6029550]={0x2DBC,0x01},[6029551]={0x2DBC,0x02},[6029552]={0x2DBC,0x08},
}

-- ── State ─────────────────────────────────────────────────────────────────────
local reported         = {}     -- ap_id -> true once returned from poll()
local server_locations = nil    -- set of ap_ids the server expects (nil = all)
local rom_ok           = nil     -- cached AP-ROM result
local goal_reached     = false
local mem              = {}
local log_fn           = nil

-- Item stream: raw_items[absolute AP index] = { id=, player=, flags=, location= }.
-- Delivery indexes it by the game's own received-item counter (EWRAM 0x2A44).
local raw_items        = {}
local legacy_next      = 0
local delivered_log    = 0

-- ── Logging ───────────────────────────────────────────────────────────────────
local function log(msg)
  if log_fn then pcall(log_fn, "[tmc] " .. tostring(msg)) end
end

-- ── Memory API (resolved at init; 2-arg domain form + current-domain fallback) ─
local function resolve_memory_api()
  if not memory then return false end
  mem.read_u8  = memory.read_u8  or memory.readbyte
  mem.write_u8 = memory.write_u8 or memory.writebyte
  return mem.read_u8 ~= nil
end

local function read_u8(addr, domain)
  if not mem.read_u8 then return nil end
  local ok, v = pcall(mem.read_u8, addr, domain)
  if ok and type(v) == "number" then return v end
  ok, v = pcall(mem.read_u8, addr)            -- older API: current domain
  if ok and type(v) == "number" then return v end
  return nil
end

local function write_u8(addr, value, domain)
  if not mem.write_u8 then return false end
  return (pcall(mem.write_u8, addr, value, domain))
end

-- ── Bit AND (pure Lua, no bit library dependency) ─────────────────────────────
local function bit_and(a, b)
  local res, bitval = 0, 1
  while a > 0 and b > 0 do
    if a % 2 == 1 and b % 2 == 1 then res = res + bitval end
    a = math.floor(a / 2); b = math.floor(b / 2); bitval = bitval * 2
  end
  return res
end

-- ── String read from a memory domain (client drops 0 bytes) ───────────────────
local function read_string(addr, len, domain)
  local out = {}
  for i = 0, len - 1 do
    local b = read_u8(addr + i, domain)
    if b == nil then return nil end
    if b ~= 0 then out[#out + 1] = string.char(b) end
  end
  return table.concat(out)
end

-- ── ROM identity: validate_rom checks "GBAZELDA" @0xA0; the AP patch additionally
--    writes the player name @0x600 (zero on a vanilla cartridge). Gating on BOTH
--    means the module never acts on a stock dump or a different GBA Zelda. ──────
local function rom_is_ap()
  if rom_ok ~= nil then return rom_ok end
  local name = read_string(ROM_NAME_ADDR, #ROM_NAME, ROM)
  if name == nil then return false end           -- not readable yet; retry next poll
  if name ~= ROM_NAME then
    rom_ok = false
    log("non-Minish-Cap ROM (id '" .. tostring(name) .. "') — detection idle")
    return false
  end
  -- AP-patch marker: the player name at ROM 0x600 is non-empty only on a patched ROM.
  local marker = read_string(AP_MARKER_ADDR, AP_MARKER_LEN, ROM)
  if marker == nil then return false end
  if #marker == 0 then
    rom_ok = false
    log("Minish Cap ROM has no AP player-name marker @0x600 — vanilla cartridge, detection idle")
    return false
  end
  rom_ok = true
  log("AP Minish Cap ROM verified (id 'GBAZELDA', slot '" .. marker .. "')")
  return true
end

-- ── Multiworld context ────────────────────────────────────────────────────────
local function load_locations(ids)
  if type(ids) ~= "table" then return end
  server_locations = {}
  local n = 0
  for _, id in ipairs(ids) do
    local v = tonumber(id)
    if v then server_locations[v] = true; n = n + 1 end
  end
  log("server location set: " .. n .. " ids")
end

local function wanted(ap_id)
  if server_locations == nil then return true end
  return server_locations[ap_id] == true
end

-- ── In-game gate (game_watcher line ~240) ─────────────────────────────────────
-- The client processes locations/items only when game_task == 0x02 OR
-- task_substate == 0x02 (i.e. normal gameplay update). File/title screens never
-- satisfy this, so no check is ever reported off the title-screen demo.
local function in_gameplay(game_task, task_substate)
  return game_task == GAME_TASK_GAMEPLAY or task_substate == GAME_TASK_GAMEPLAY
end

-- ── Item delivery (handle_item_receiving, client.py line ~257) ────────────────
-- One guarded write per poll: write the 2-byte AP id into the mailbox @0x3FF10
-- only while it reads [0,0] AND the "player safe" byte @0x2A4A == 1, then advance
-- the received-item counter (u16 BE @0x2A44). The game's ASM consumes the mailbox
-- (zeroes it) — exactly the client's guarded_write + counter-bump handshake.
-- Caller has already verified rom_ok + in-gameplay, so this never writes into a
-- foreign / unpatched cartridge.
local function deliver_next()
  -- Mailbox must be empty (game has consumed the previous item).
  local mb0 = read_u8(ITEM_MAILBOX_ADDR,     EWRAM)
  local mb1 = read_u8(ITEM_MAILBOX_ADDR + 1, EWRAM)
  if mb0 == nil or mb1 == nil or mb0 ~= 0 or mb1 ~= 0 then return end
  -- "Player safe" guard: only deliver when the ROM says it is safe to receive.
  local safe = read_u8(PLAYER_SAFE_ADDR, EWRAM)
  if safe ~= 1 then return end

  local hi = read_u8(RECV_INDEX_ADDR,     EWRAM)
  local lo = read_u8(RECV_INDEX_ADDR + 1, EWRAM)
  if hi == nil or lo == nil then return end
  local received_index = (hi * 0x100) + lo

  local item = raw_items[received_index]            -- 0-based stream index
  if item == nil then return end                    -- nothing new to deliver

  local id  = item.id
  local pid = math.floor(id / 0x100) % 0x100        -- id >> 8
  local sid = id % 0x100                            -- id & 0xFF

  -- Guarded write: mailbox high+low bytes. (Re-checked [0,0] above this frame.)
  if not write_u8(ITEM_MAILBOX_ADDR,     pid, EWRAM) then return end
  if not write_u8(ITEM_MAILBOX_ADDR + 1, sid, EWRAM) then return end

  -- Advance the received-item counter (u16 BE).
  local nxt = received_index + 1
  write_u8(RECV_INDEX_ADDR,     math.floor(nxt / 0x100) % 0x100, EWRAM)
  write_u8(RECV_INDEX_ADDR + 1, nxt % 0x100, EWRAM)

  delivered_log = delivered_log + 1
  if delivered_log <= 5 or delivered_log % 25 == 0 then
    log(string.format("delivered item #%d (AP id %d -> pid 0x%X sid 0x%X) as index %d",
                      delivered_log, id, pid, sid, nxt))
  end
end

-- ── Module contract ───────────────────────────────────────────────────────────
function M.init(ctx)
  if ctx and type(ctx.log) == "function" then log_fn = ctx.log end
  if not resolve_memory_api() then
    log("BizHawk memory API unavailable — module idle")
    ADDRESSES_VERIFIED = false
    return
  end
  local cfg = (ctx and ctx.config) or {}
  load_locations(cfg.locations)
  local n = 0; for _ in pairs(LOC) do n = n + 1 end
  log("ready: " .. n .. " location flags, item delivery active")
end

function M.poll()
  local new = {}
  if not ADDRESSES_VERIFIED then return new end
  if not rom_is_ap() then return new end

  local game_task     = read_u8(GAME_TASK_ADDR,     IWRAM)
  local task_substate = read_u8(TASK_SUBSTATE_ADDR, IWRAM)
  if game_task == nil or task_substate == nil then return new end

  -- Goal: Vaati's defeat sets game_task to 0x04 (checked before the gameplay
  -- gate, because the same byte being 0x04 means we are no longer in 0x02).
  if not goal_reached and game_task == GAME_TASK_GOAL then
    goal_reached = true
    log("goal reached (game_task == 0x04 — Vaati defeated)")
  end

  if not in_gameplay(game_task, task_substate) then return new end

  -- Location detection: (EWRAM[addr] | mask) == EWRAM[addr] for each wanted loc.
  for ap_id, def in pairs(LOC) do
    if not reported[ap_id] and wanted(ap_id) then
      local byte = read_u8(def[1], EWRAM)
      if byte ~= nil and bit_and(byte, def[2]) == def[2] then
        reported[ap_id] = true
        new[#new + 1] = ap_id
      end
    end
  end

  -- Item delivery shares this poll's verified gate (rom_ok + in-gameplay).
  deliver_next()

  return new
end

function M.is_goal_complete()
  return goal_reached
end

-- Enqueue a received AP item by its ABSOLUTE stream index. Delivery happens in
-- poll() via the game's own received-count handshake (EWRAM 0x2A44 / 0x3FF10).
function M.receive_item(item_id, meta)
  local id = tonumber(item_id)
  if not id then return end

  if meta and meta.index ~= nil then
    local idx = tonumber(meta.index)
    if idx and idx >= 0 then
      raw_items[idx] = {
        id       = id,
        player   = tonumber(meta.player),
        flags    = tonumber(meta.flags),
        location = tonumber(meta.location),
      }
      if idx >= legacy_next then legacy_next = idx + 1 end
      return
    end
  end

  -- Legacy plain "ITEM:<id>" line — append in arrival order.
  raw_items[legacy_next] = { id = id }
  legacy_next = legacy_next + 1
end

return M
