-- ═══════════════════════════════════════════════════════════════════════════════
-- tloz_oos.lua — game module for the Archipelago BizHawk connector.
--                The Legend of Zelda: Oracle of Seasons (Game Boy Color)
--
-- STATUS: location DETECTION + goal are REAL and SOURCE-DERIVED from the official
-- AP world worlds/tloz_oos (Client.py + data/locations.py + common/Util.py, the
-- `oos` branch of github.com/Dinopony/ArchipelagoOoS, world_version 21.0.0). The
-- 255-entry flag table + 16-entry Gasha counter list below were GENERATED by a
-- Python script that imports the real LOCATIONS_DATA and replicates, byte-for-byte:
--   • common/Util.py build_location_name_to_id_dict()  → the AP location id, which
--     for every flag location is literally  flag_byte*0x100 + bit_mask  (default
--     mask 0x20). There is NO separate base offset — the id IS the (byte,mask).
--   • the room→flag_byte fixup at the bottom of locations.py (chest-style
--     locations with no explicit flag_byte derive one from their room number).
--   • Client.py process_checked_locations() detection math + the deterministic
--     Gasha-Nut counter rule.
-- so the ids AND the detection bytes/masks are exact, not hand-copied. Loads
-- crash-free on any ROM; self-disables when the cartridge is not Oracle of Seasons.
--
-- MEMORY MODEL (BizHawk Game Boy Color — same as the LADX module)
-- ───────────────────────────────────────────────────────────────
--   The OoS AP client (Client.py, a BizHawkClient) reads GBC memory through the
--   "System Bus" domain for everything except its two ROM-identity reads. We do
--   the same: all RAM addresses here are GB System-Bus addresses.
--     • Location check flags live in a 0x500-byte block at 0xC600..0xCB00 (one or
--       more bits per location). A check is "done" when
--         flag_bytes[flag_byte - 0xC600] & bit_mask == bit_mask
--       (Client.py uses `== bit_mask`, not `> 0`, so multi-bit masks like 0x60
--       require ALL their bits — replicated exactly).
--     • 16 deterministic "Gasha Nut #N" locations are NOT individual flag bits;
--       they are gated by a COUNTER:  count = flag_bytes[0xC649-0xC600] >> 2 ,
--       and the first `count` of the ordered Gasha ids are reported checked.
--     • game_state (0xC2EE) == 2 means the player is actually in-game.
--     • current_room = (0xCC49 << 8) | 0xCC4C  drives the goal.
--   ROM identity (the two ROM-domain reads the client uses):
--     • 0x0134 (9 bytes) = GB header title; an Oracle of Seasons cart reads
--       "ZELDA DIN" there (Ages reads "ZELDA NAYRU"). Used as the AP-cart gate.
--     • 0xFFFC0 (64 bytes) = AP-written slot name (the client's auth) — not needed
--       for detection, so not read here.
--
-- DETECTION GATE (mirrors Client.py game_watcher)
--   poll() reports a check only when game_state (0xC2EE) == 2 (the exact guard
--   `read_result[0][0] != 2: return` the client uses). The title screen / menus /
--   save-select frames read a different state, so they never report checks.
--
-- GOAL (mirrors Client.py process_game_completion — BOTH goal options)
--   • beat_onox  (slot_data goal == 0, the default): current_room == 0x0790
--     (the room with Din's descending crystal after Onox/Dragon Onox).
--   • beat_ganon (slot_data goal == 1, linked/Ganon ending): current_room ==
--     0x059A (Zelda lying down) AND flag 0xCA9A & 0x80 (Ganon beaten).
--   The module learns which goal applies from ctx.slot_data.goal when present; with
--   no slot_data it accepts EITHER completion condition (so a solo seed still
--   finishes), which can never false-positive — both are end-of-game rooms.
--
-- receive_item(): DOCUMENTED NO-OP. OoS items_handling = 0b001 — the PATCHED GAME
-- grants its own locally-found items, so a SOLO seed plays fully and every check is
-- reported in a multiworld. Delivering REMOTE multiworld items is the client's
-- guarded write path (it polls a received-item index at 0xC6A0, then writes the
-- next item's id/subid into the 2-byte struct at 0xCBFB ONLY when that struct is
-- empty AND the player is not inside Blaino's Gym — Blaino calls a writing player a
-- cheater). That write handshake is the one piece that needs in-emulator
-- verification before it is trusted, so it is GATED OFF here rather than shipped
-- unverified (a mistimed write could be rejected or corrupt the item struct).
-- Check reporting + goal are fully live regardless.
--
-- MODULE CONTRACT (called by bizhawk_ap_connector.lua)
--   M.init(ctx) / M.poll() -> {ids} / M.is_goal_complete() -> bool /
--   M.receive_item(item_id, meta)
-- ═══════════════════════════════════════════════════════════════════════════════

local M = {}
M.name = "tloz_oos"

local ADDRESSES_VERIFIED = true   -- table generated from worlds/tloz_oos source

-- ── Memory domain ─────────────────────────────────────────────────────────────
-- The AP client reads GB memory via the System Bus (portable across GB cores).
local SYSBUS = "System Bus"
local ROM    = "ROM"

-- ── Addresses / constants (Client.py ROM_ADDRS / RAM_ADDRS) ───────────────────
local GAME_IDENT_ADDR    = 0x0134       -- ROM: GB header title (9 bytes)
local GAME_IDENT_STR     = "ZELDA DIN"  -- Oracle of Seasons internal title
local GAME_STATE_ADDR    = 0xC2EE       -- System Bus: in-game when == 2
local GAME_STATE_INGAME  = 2
local FLAGS_BASE         = 0xC600       -- location_flags block start (0x500 long)
local FLAGS_LOW          = 0xC600
local FLAGS_HIGH         = 0xCB00       -- exclusive top of the 0x500 window
local MAP_GROUP_ADDR     = 0xCC49       -- current_map_group (high byte of room)
local MAP_ID_ADDR        = 0xCC4C       -- current_map_id   (low byte of room)

-- Gasha counter: count = read_u8(0xC649) >> 2 ; first `count` gasha ids checked.
local GASHA_COUNTER_ADDR = 0xC649

-- Goal rooms / flags (Client.py process_game_completion).
local ROOM_AFTER_DRAGONOX = 0x0790      -- beat_onox  win room
local ROOM_ZELDA_ENDING   = 0x059A      -- beat_ganon win room
local GANON_FLAG_ADDR      = 0xCA9A      -- beat_ganon: & 0x80 == Ganon beaten
local GANON_FLAG_MASK      = 0x80
local GOAL_BEAT_ONOX       = 0          -- OracleOfSeasonsGoal.option_beat_onox
local GOAL_BEAT_GANON      = 1          -- OracleOfSeasonsGoal.option_beat_ganon

-- ── Location table (GENERATED from worlds/tloz_oos; 255 flag entries) ──────────
-- ap_id -> { a = flag byte address, m = mask }. ap_id == a*0x100 + m by source
-- construction. Checked when (read_u8(a) & m) == m  (note: equality, not > 0).
local LOC = {
  [12992257]={a=0xC63F,m=0x01},[12992258]={a=0xC63F,m=0x02},[12992260]={a=0xC63F,m=0x04},[12992264]={a=0xC63F,m=0x08},
  [12992272]={a=0xC63F,m=0x10},[12992288]={a=0xC63F,m=0x20},[12992320]={a=0xC63F,m=0x40},[12992384]={a=0xC63F,m=0x80},
  [12992513]={a=0xC640,m=0x01},[12992514]={a=0xC640,m=0x02},[12992516]={a=0xC640,m=0x04},[12992520]={a=0xC640,m=0x08},
  [12992544]={a=0xC640,m=0x20},[12992576]={a=0xC640,m=0x40},[12992640]={a=0xC640,m=0x80},[12992784]={a=0xC641,m=0x10},
  [12992800]={a=0xC641,m=0x20},[12992832]={a=0xC641,m=0x40},[12992896]={a=0xC641,m=0x80},[12993025]={a=0xC642,m=0x01},
  [12993026]={a=0xC642,m=0x02},[12993028]={a=0xC642,m=0x04},[12993032]={a=0xC642,m=0x08},[12993040]={a=0xC642,m=0x10},
  [12993056]={a=0xC642,m=0x20},[12993088]={a=0xC642,m=0x40},[13030660]={a=0xC6D5,m=0x04},[13030664]={a=0xC6D5,m=0x08},
  [13030672]={a=0xC6D5,m=0x10},[13030688]={a=0xC6D5,m=0x20},[13030720]={a=0xC6D5,m=0x40},[13030784]={a=0xC6D5,m=0x80},
  [13030913]={a=0xC6D6,m=0x01},[13030914]={a=0xC6D6,m=0x02},[13030916]={a=0xC6D6,m=0x04},[13030920]={a=0xC6D6,m=0x08},
  [13043776]={a=0xC708,m=0x40},[13045536]={a=0xC70F,m=0x20},[13045792]={a=0xC710,m=0x20},[13048352]={a=0xC71A,m=0x20},
  [13053216]={a=0xC72D,m=0x20},[13064992]={a=0xC75B,m=0x20},[13066016]={a=0xC75F,m=0x20},[13067808]={a=0xC766,m=0x20},
  [13068064]={a=0xC767,m=0x20},[13070880]={a=0xC772,m=0x20},[13074976]={a=0xC782,m=0x20},[13078048]={a=0xC78E,m=0x20},
  [13082144]={a=0xC79E,m=0x20},[13086496]={a=0xC7AF,m=0x20},[13087008]={a=0xC7B1,m=0x20},[13088544]={a=0xC7B7,m=0x20},
  [13088800]={a=0xC7B8,m=0x20},[13093152]={a=0xC7C9,m=0x20},[13095200]={a=0xC7D1,m=0x20},[13096992]={a=0xC7D8,m=0x20},
  [13097504]={a=0xC7DA,m=0x20},[13099808]={a=0xC7E3,m=0x20},[13104160]={a=0xC7F4,m=0x20},[13104416]={a=0xC7F5,m=0x20},
  [13105184]={a=0xC7F8,m=0x20},[13105440]={a=0xC7F9,m=0x20},[13106976]={a=0xC7FF,m=0x20},[13108768]={a=0xC806,m=0x20},
  [13109024]={a=0xC807,m=0x20},[13110048]={a=0xC80B,m=0x20},[13115424]={a=0xC820,m=0x20},[13122080]={a=0xC83A,m=0x20},
  [13122336]={a=0xC83B,m=0x20},[13122368]={a=0xC83B,m=0x40},[13122432]={a=0xC83B,m=0x80},[13123616]={a=0xC840,m=0x20},
  [13123872]={a=0xC841,m=0x20},[13124128]={a=0xC842,m=0x20},[13125408]={a=0xC847,m=0x20},[13129504]={a=0xC857,m=0x20},
  [13129760]={a=0xC858,m=0x20},[13131808]={a=0xC860,m=0x20},[13133344]={a=0xC866,m=0x20},[13134112]={a=0xC869,m=0x20},
  [13140000]={a=0xC880,m=0x20},[13140768]={a=0xC883,m=0x20},[13141536]={a=0xC886,m=0x20},[13141792]={a=0xC887,m=0x20},
  [13142048]={a=0xC888,m=0x20},[13143584]={a=0xC88E,m=0x20},[13143840]={a=0xC88F,m=0x20},[13144352]={a=0xC891,m=0x20},
  [13145120]={a=0xC894,m=0x20},[13145376]={a=0xC895,m=0x20},[13145920]={a=0xC897,m=0x40},[13145984]={a=0xC897,m=0x80},
  [13146144]={a=0xC898,m=0x20},[13146400]={a=0xC899,m=0x20},[13146912]={a=0xC89B,m=0x20},[13147168]={a=0xC89C,m=0x20},
  [13148448]={a=0xC8A1,m=0x20},[13148960]={a=0xC8A3,m=0x20},[13149216]={a=0xC8A4,m=0x20},[13150496]={a=0xC8A9,m=0x20},
  [13151264]={a=0xC8AC,m=0x20},[13153056]={a=0xC8B3,m=0x20},[13153312]={a=0xC8B4,m=0x20},[13153568]={a=0xC8B5,m=0x20},
  [13173024]={a=0xC901,m=0x20},[13173536]={a=0xC903,m=0x20},[13174048]={a=0xC905,m=0x20},[13174304]={a=0xC906,m=0x20},
  [13175072]={a=0xC909,m=0x20},[13176096]={a=0xC90D,m=0x20},[13176608]={a=0xC90F,m=0x20},[13176864]={a=0xC910,m=0x20},
  [13177120]={a=0xC911,m=0x20},[13177376]={a=0xC912,m=0x20},[13177632]={a=0xC913,m=0x20},[13177888]={a=0xC914,m=0x20},
  [13178656]={a=0xC917,m=0x20},[13179168]={a=0xC919,m=0x20},[13179680]={a=0xC91B,m=0x20},[13180704]={a=0xC91F,m=0x20},
  [13181984]={a=0xC924,m=0x20},[13183264]={a=0xC929,m=0x20},[13183520]={a=0xC92A,m=0x20},[13183776]={a=0xC92B,m=0x20},
  [13184032]={a=0xC92C,m=0x20},[13184288]={a=0xC92D,m=0x20},[13185312]={a=0xC931,m=0x20},[13186080]={a=0xC934,m=0x20},
  [13186592]={a=0xC936,m=0x20},[13187104]={a=0xC938,m=0x20},[13189152]={a=0xC940,m=0x20},[13189408]={a=0xC941,m=0x20},
  [13190176]={a=0xC944,m=0x20},[13190688]={a=0xC946,m=0x20},[13192224]={a=0xC94C,m=0x20},[13192480]={a=0xC94D,m=0x20},
  [13192992]={a=0xC94F,m=0x20},[13193248]={a=0xC950,m=0x20},[13193504]={a=0xC951,m=0x20},[13194016]={a=0xC953,m=0x20},
  [13194272]={a=0xC954,m=0x20},[13197088]={a=0xC95F,m=0x20},[13197344]={a=0xC960,m=0x20},[13198112]={a=0xC963,m=0x20},
  [13198368]={a=0xC964,m=0x20},[13199648]={a=0xC969,m=0x20},[13200416]={a=0xC96C,m=0x20},[13200672]={a=0xC96D,m=0x20},
  [13202208]={a=0xC973,m=0x20},[13202720]={a=0xC975,m=0x20},[13204256]={a=0xC97B,m=0x20},[13205280]={a=0xC97F,m=0x20},
  [13206304]={a=0xC983,m=0x20},[13207584]={a=0xC988,m=0x20},[13207840]={a=0xC989,m=0x20},[13208352]={a=0xC98B,m=0x20},
  [13208608]={a=0xC98C,m=0x20},[13209376]={a=0xC98F,m=0x20},[13209888]={a=0xC991,m=0x20},[13211424]={a=0xC997,m=0x20},
  [13211936]={a=0xC999,m=0x20},[13212960]={a=0xC99D,m=0x20},[13213472]={a=0xC99F,m=0x20},[13214496]={a=0xC9A3,m=0x20},
  [13215008]={a=0xC9A5,m=0x20},[13216544]={a=0xC9AB,m=0x20},[13217056]={a=0xC9AD,m=0x20},[13217568]={a=0xC9AF,m=0x20},
  [13217824]={a=0xC9B0,m=0x20},[13218592]={a=0xC9B3,m=0x20},[13221664]={a=0xC9BF,m=0x20},[13222176]={a=0xC9C1,m=0x20},
  [13222432]={a=0xC9C2,m=0x20},[13222688]={a=0xC9C3,m=0x20},[13222944]={a=0xC9C4,m=0x20},[13226016]={a=0xC9D0,m=0x20},
  [13227296]={a=0xC9D5,m=0x20},[13230112]={a=0xC9E0,m=0x20},[13230368]={a=0xC9E1,m=0x20},[13234464]={a=0xC9F1,m=0x20},
  [13236000]={a=0xC9F7,m=0x20},[13236768]={a=0xC9FA,m=0x20},[13237024]={a=0xC9FB,m=0x20},[13238592]={a=0xCA01,m=0x40},
  [13238848]={a=0xCA02,m=0x40},[13239104]={a=0xCA03,m=0x40},[13239360]={a=0xCA04,m=0x40},[13239616]={a=0xCA05,m=0x40},
  [13239872]={a=0xCA06,m=0x40},[13240128]={a=0xCA07,m=0x40},[13240384]={a=0xCA08,m=0x40},[13241888]={a=0xCA0E,m=0x20},
  [13242656]={a=0xCA11,m=0x20},[13242912]={a=0xCA12,m=0x20},[13247008]={a=0xCA22,m=0x20},[13247264]={a=0xCA23,m=0x20},
  [13247520]={a=0xCA24,m=0x20},[13248544]={a=0xCA28,m=0x20},[13248800]={a=0xCA29,m=0x20},[13249056]={a=0xCA2A,m=0x20},
  [13249568]={a=0xCA2C,m=0x20},[13250336]={a=0xCA2F,m=0x20},[13250848]={a=0xCA31,m=0x20},[13251104]={a=0xCA32,m=0x20},
  [13251616]={a=0xCA34,m=0x20},[13251872]={a=0xCA35,m=0x20},[13253920]={a=0xCA3D,m=0x20},[13255456]={a=0xCA43,m=0x20},
  [13255712]={a=0xCA44,m=0x20},[13255968]={a=0xCA45,m=0x20},[13256480]={a=0xCA47,m=0x20},[13256736]={a=0xCA48,m=0x20},
  [13258528]={a=0xCA4F,m=0x20},[13258784]={a=0xCA50,m=0x20},[13259296]={a=0xCA52,m=0x20},[13259808]={a=0xCA54,m=0x20},
  [13260832]={a=0xCA58,m=0x20},[13261344]={a=0xCA5A,m=0x20},[13262624]={a=0xCA5F,m=0x20},[13263904]={a=0xCA64,m=0x20},
  [13265440]={a=0xCA6A,m=0x20},[13265696]={a=0xCA6B,m=0x20},[13266976]={a=0xCA70,m=0x20},[13268256]={a=0xCA75,m=0x20},
  [13270304]={a=0xCA7D,m=0x20},[13270816]={a=0xCA7F,m=0x20},[13271072]={a=0xCA80,m=0x20},[13271584]={a=0xCA82,m=0x20},
  [13273632]={a=0xCA8A,m=0x20},[13273888]={a=0xCA8B,m=0x20},[13274144]={a=0xCA8C,m=0x20},[13274400]={a=0xCA8D,m=0x20},
  [13274656]={a=0xCA8E,m=0x20},[13283872]={a=0xCAB2,m=0x20},[13284128]={a=0xCAB3,m=0x20},[13284384]={a=0xCAB4,m=0x20},
  [13284640]={a=0xCAB5,m=0x20},[13284928]={a=0xCAB6,m=0x40},[13284960]={a=0xCAB6,m=0x60},[13286176]={a=0xCABB,m=0x20},
  [13286432]={a=0xCABC,m=0x20},[13286688]={a=0xCABD,m=0x20},[13286784]={a=0xCABD,m=0x80},[13287456]={a=0xCAC0,m=0x20},
  [13288736]={a=0xCAC5,m=0x20},[13288992]={a=0xCAC6,m=0x20},[13289248]={a=0xCAC7,m=0x20},[13289504]={a=0xCAC8,m=0x20},
  [13292064]={a=0xCAD2,m=0x20},[13296416]={a=0xCAE3,m=0x20},[13296928]={a=0xCAE5,m=0x20},[13300256]={a=0xCAF2,m=0x20},
  [13301024]={a=0xCAF5,m=0x20},[13301792]={a=0xCAF8,m=0x20},[13302560]={a=0xCAFB,m=0x20},
}

-- ── Gasha Nut counter locations (GENERATED; 16 ordered ids) ───────────────────
-- These are NOT flag bits. count = read_u8(0xC649) >> 2 ; the first `count` of
-- these ordered ids are reported checked (Client.py process_checked_locations).
local GASHA_IDS = {
  12994816,12994817,12994818,12994819,12994820,12994821,12994822,12994823,
  12994824,12994825,12994826,12994827,12994828,12994829,12994830,12994831,
}

-- ── State ─────────────────────────────────────────────────────────────────────
local reported         = {}     -- ap_id -> true once returned from poll()
local server_locations = nil    -- set of ap_ids the server expects (nil = all)
local rom_ok           = nil     -- cached OoS-cart result
local goal_option      = nil     -- slot_data goal (0/1), or nil = accept either
local mem              = {}
local log_fn           = nil

-- ── Logging ───────────────────────────────────────────────────────────────────
local function log(msg)
  if log_fn then pcall(log_fn, "[tloz_oos] " .. tostring(msg)) end
end

-- ── Memory API (resolved at init; 2-arg domain form + current-domain fallback) ─
local function resolve_memory_api()
  if not memory then return false end
  mem.read_u8 = memory.read_u8 or memory.readbyte
  return mem.read_u8 ~= nil
end

local function read_u8(addr, domain)
  if not mem.read_u8 then return nil end
  local ok, v = pcall(mem.read_u8, addr, domain)
  if ok and type(v) == "number" then return v end
  ok, v = pcall(mem.read_u8, addr)            -- older API: current domain
  if ok and type(v) == "number" then return v end
  return nil
end

local function bit_and(a, b)
  local res, bitval = 0, 1
  while a > 0 and b > 0 do
    if a % 2 == 1 and b % 2 == 1 then res = res + bitval end
    a = math.floor(a / 2); b = math.floor(b / 2); bitval = bitval * 2
  end
  return res
end

-- ── ROM identity: an Oracle of Seasons cart reads "ZELDA DIN" at header 0x0134.
--    (Ages reads "ZELDA NAYRU"; vanilla/garbage carts read neither.) Matches the
--    client's own validate_rom check exactly, so this self-disables on anything
--    that is not running Oracle of Seasons, never on a real OoS cart. ───────────
local function rom_is_ap()
  if rom_ok ~= nil then return rom_ok end
  for i = 1, #GAME_IDENT_STR do
    local b = read_u8(GAME_IDENT_ADDR + i - 1, ROM)
    if b == nil then return false end           -- not readable yet; retry next poll
    if b ~= string.byte(GAME_IDENT_STR, i) then
      rom_ok = false
      log("non-OoS ROM (no 'ZELDA DIN' at 0x0134) — detection idle")
      return false
    end
  end
  rom_ok = true
  log("Oracle of Seasons cart detected ('ZELDA DIN' at 0x0134) — detection live")
  return true
end

-- ── Multiworld context ────────────────────────────────────────────────────────
local function load_locations(ids)
  if type(ids) ~= "table" then return end
  server_locations = {}
  local n = 0
  for _, id in ipairs(ids) do
    local v = tonumber(id)
    if v then server_locations[v] = true; n = n + 1 end
  end
  log("server location set: " .. n .. " ids")
end

local function load_goal(slot_data)
  if type(slot_data) ~= "table" then return end
  -- slot_data may carry goal directly or nested under "options" (the world's
  -- on_package reads slot_data["options"]["goal"]). Accept either shape.
  local g = slot_data.goal
  if g == nil and type(slot_data.options) == "table" then g = slot_data.options.goal end
  local gv = tonumber(g)
  if gv ~= nil then
    goal_option = gv
    log("goal option = " .. tostring(gv) ..
        (gv == GOAL_BEAT_GANON and " (beat_ganon)" or " (beat_onox)"))
  end
end

local function wanted(ap_id)
  if server_locations == nil then return true end
  return server_locations[ap_id] == true
end

-- ── Detection gate (Client.py game_watcher: read_result[0][0] == 2) ───────────
local function in_gameplay()
  local s = read_u8(GAME_STATE_ADDR, SYSBUS)
  return s ~= nil and s == GAME_STATE_INGAME
end

-- ── Per-flag evaluation: (byte & mask) == mask  (note equality) ───────────────
local function flag_done(entry)
  local b = read_u8(entry.a, SYSBUS)
  if b == nil then return false end
  return bit_and(b, entry.m) == entry.m
end

local function current_room()
  local hi = read_u8(MAP_GROUP_ADDR, SYSBUS)
  local lo = read_u8(MAP_ID_ADDR, SYSBUS)
  if hi == nil or lo == nil then return nil end
  return hi * 0x100 + lo
end

-- ── Module contract ───────────────────────────────────────────────────────────
function M.init(ctx)
  if ctx and type(ctx.log) == "function" then log_fn = ctx.log end
  if not resolve_memory_api() then
    log("BizHawk memory API unavailable — module idle")
    ADDRESSES_VERIFIED = false
    return
  end
  local cfg = (ctx and ctx.config) or {}
  load_locations(cfg.locations)
  load_goal(cfg.slot_data)
  local n = 0; for _ in pairs(LOC) do n = n + 1 end
  log("ready: " .. n .. " flag locations + " .. #GASHA_IDS ..
      " gasha (0x" .. string.format("%04X", FLAGS_LOW) ..
      "..0x" .. string.format("%04X", FLAGS_HIGH) .. ")")
end

function M.poll()
  local new = {}
  if not ADDRESSES_VERIFIED then return new end
  if not rom_is_ap() then return new end
  if not in_gameplay() then return new end

  -- Flag-bit locations.
  for ap_id, entry in pairs(LOC) do
    if not reported[ap_id] and wanted(ap_id) and flag_done(entry) then
      reported[ap_id] = true
      new[#new + 1] = ap_id
    end
  end

  -- Deterministic Gasha Nuts: first `count` ids, count = byte(0xC649) >> 2.
  local gc = read_u8(GASHA_COUNTER_ADDR, SYSBUS)
  if gc ~= nil then
    local count = math.floor(gc / 4)
    if count > #GASHA_IDS then count = #GASHA_IDS end
    for i = 1, count do
      local ap_id = GASHA_IDS[i]
      if not reported[ap_id] and wanted(ap_id) then
        reported[ap_id] = true
        new[#new + 1] = ap_id
      end
    end
  end

  return new
end

function M.is_goal_complete()
  if not ADDRESSES_VERIFIED or not rom_is_ap() then return false end
  if not in_gameplay() then return false end
  local room = current_room()
  if room == nil then return false end

  -- beat_onox: reached the room with Din's descending crystal.
  local onox_done = (room == ROOM_AFTER_DRAGONOX)
  -- beat_ganon: reached Zelda's ending room AND Ganon flag set.
  local ganon_done = false
  if room == ROOM_ZELDA_ENDING then
    local f = read_u8(GANON_FLAG_ADDR, SYSBUS)
    ganon_done = (f ~= nil and bit_and(f, GANON_FLAG_MASK) == GANON_FLAG_MASK)
  end

  if goal_option == GOAL_BEAT_ONOX then
    return onox_done
  elseif goal_option == GOAL_BEAT_GANON then
    return ganon_done
  end
  -- Unknown goal (no slot_data): accept either end-of-game condition. Neither
  -- can false-positive — both are terminal rooms.
  return onox_done or ganon_done
end

-- Remote multiworld items: see the file header. OoS items_handling = 0b001 means
-- the patched game grants its own found items, so solo play and check reporting
-- work fully; delivering REMOTE items is the client's guarded write handshake
-- (poll the received-item index at 0xC6A0, write id/subid into the struct at
-- 0xCBFB only when empty and not inside Blaino's Gym). That write path is the one
-- piece deferred until it can be confirmed in-emulator. No-op (never a wrong
-- write) until then.
function M.receive_item(item_id, meta)
  -- intentionally empty (documented)
end

return M
