-- ═══════════════════════════════════════════════════════════════════════════════
-- tloz_ooa.lua — game module for the Archipelago BizHawk connector.
--                The Legend of Zelda: Oracle of Ages (Game Boy Color)
--
-- STATUS: location DETECTION + goal are REAL and SOURCE-DERIVED from the official
-- AP world worlds/tloz_ooa (Client.py + data/Locations.py + Data.py, the `oos`
-- branch of github.com/SenPierre/ArchipelagoOoA, apworld VERSION 0.4.3). The
-- 226-entry flag table below was GENERATED by a Python script that imports the
-- real LOCATIONS_DATA and replicates, byte-for-byte:
--   • Data.py build_location_name_to_id_dict()  → the AP location id. Unlike the
--     sibling Oracle of Seasons world, OoA assigns ids SEQUENTIALLY: a counter
--     starts at BASE_LOCATION_ID = 27022002000 and increments once per key in
--     LOCATIONS_DATA dict order. The id is NOT derived from (flag_byte,mask); the
--     ORDER of the source dict is load-bearing, so the table was produced by
--     importing the real module (not hand-copied) to preserve it exactly.
--   • Client.py process_checked_locations() detection math: for each location
--     with a "flag_byte" (skipping any 0xFFFF), a check is done when
--       flag_bytes[flag_byte - 0xC600] & bit_mask == bit_mask
--     ("== bit_mask", not "> 0" — replicated exactly). bit_mask defaults to 0x20.
--     A handful of locations carry a LIST of flag_bytes (the same item reachable
--     from several rooms); the client tests each and stops at the FIRST match
--     ("break"), so each such id maps to several {a,m} alternatives here and is
--     reported when ANY one is set — identical semantics.
-- so the ids AND the detection bytes/masks are exact. Loads crash-free on any
-- ROM; self-disables when the cartridge is not Oracle of Ages.
--
-- (OoA has NO Gasha-Nut counter — unlike Oracle of Seasons, its Gasha-related
-- locations are ordinary flag bits already present in the table.)
--
-- MEMORY MODEL (BizHawk Game Boy Color — same as the LADX / OoS modules)
-- ───────────────────────────────────────────────────────────────
--   The OoA AP client (Client.py, a BizHawkClient) reads GBC memory through the
--   "System Bus" domain for everything except its two ROM-identity reads. We do
--   the same: all RAM addresses here are GB System-Bus addresses.
--     • Location check flags live in a 0x500-byte block at 0xC600..0xCB00 (one or
--       more bits per location). A check is "done" when
--         flag_bytes[flag_byte - 0xC600] & bit_mask == bit_mask.
--     • game_state (0xC2EE) == 2 means the player is actually in-game.
--     • current_room = (0xCC2D << 8) | 0xCC30  drives the beat_ganon goal.
--   ROM identity (the ROM-domain read the client's validate_rom uses):
--     • 0x0134 (11 bytes) = GB header title; an Oracle of Ages cart reads
--       "ZELDA NAYRU" there (Seasons reads "ZELDA DIN"). Used as the AP-cart gate.
--     • 0xFFFC0 (64 bytes) = AP-written slot name (the client's auth) — not needed
--       for detection, so not read here.
--
-- DETECTION GATE (mirrors Client.py game_watcher)
--   poll() reports a check only when game_state (0xC2EE) == 2 (the exact guard
--   `read_result[0][0] != 2: return` the client uses). The title screen / menus /
--   save-select frames read a different state, so they never report checks.
--
-- GOAL (mirrors Client.py process_game_completion — BOTH goal options)
--   • beat_veran  (slot_data goal == 0, the default): flag 0xC6D8 & 0x80 (Veran
--     beaten). NOTE: unlike Seasons' beat_onox, OoA's default goal is a pure FLAG
--     test with NO room requirement.
--   • beat_ganon  (slot_data goal == 1, linked/Ganon ending): current_room ==
--     0x05F1 (Zelda lying down) AND flag 0xCAF1 & 0x80 (Ganon beaten).
--   The module learns which goal applies from ctx.slot_data.goal when present; with
--   no slot_data it accepts EITHER completion condition (so a solo seed still
--   finishes). Both are terminal conditions (final boss flags), so neither can
--   false-positive during normal play.
--
-- receive_item(): DOCUMENTED NO-OP. OoA items_handling = 0b101 (remote items +
-- starting inventory) — so unlike a fully-local seed, the multiworld DOES rely on
-- the client to deliver remote items. Delivery is the client's guarded write path:
-- it polls a received-item COUNT at 0xC6A8 (2 bytes, little-endian) and, only while
-- the pending-item struct at 0xCBFB reads 0 (empty), writes the next item's
-- id/subid into 0xCBFB. (The "empty" guard doubles as the Blaino's-Gym safety the
-- Seasons client documents — Blaino calls a writing player a cheater; the struct is
-- never empty mid-fight.) That write handshake needs in-emulator verification
-- before it is trusted, so it is GATED OFF here rather than shipped unverified (a
-- mistimed write could be rejected or corrupt the item struct). Check reporting +
-- goal are fully live regardless; the locally-found and starting items the patched
-- ROM grants itself are unaffected.
--
-- MODULE CONTRACT (called by bizhawk_ap_connector.lua)
--   M.init(ctx) / M.poll() -> {ids} / M.is_goal_complete() -> bool /
--   M.receive_item(item_id, meta)
-- ═══════════════════════════════════════════════════════════════════════════════

local M = {}
M.name = "tloz_ooa"

local ADDRESSES_VERIFIED = true   -- table generated from worlds/tloz_ooa source

-- ── Memory domain ─────────────────────────────────────────────────────────────
-- The AP client reads GB memory via the System Bus (portable across GB cores).
local SYSBUS = "System Bus"
local ROM    = "ROM"

-- ── Addresses / constants (Client.py ROM_ADDRS / RAM_ADDRS) ───────────────────
local GAME_IDENT_ADDR    = 0x0134        -- ROM: GB header title (11 bytes)
local GAME_IDENT_STR     = "ZELDA NAYRU" -- Oracle of Ages internal title
local GAME_STATE_ADDR    = 0xC2EE        -- System Bus: in-game when == 2
local GAME_STATE_INGAME  = 2
local FLAGS_BASE         = 0xC600        -- location_flags block start (0x500 long)
local FLAGS_LOW          = 0xC600
local FLAGS_HIGH         = 0xCB00        -- exclusive top of the 0x500 window
local MAP_GROUP_ADDR     = 0xCC2D        -- current_map_group (high byte of room)
local MAP_ID_ADDR        = 0xCC30        -- current_map_id   (low byte of room)

-- Goal rooms / flags (Client.py process_game_completion).
local VERAN_FLAG_ADDR    = 0xC6D8        -- beat_veran: & 0x80 == Veran beaten
local VERAN_FLAG_MASK    = 0x80
local ROOM_ZELDA_ENDING  = 0x05F1        -- beat_ganon win room
local GANON_FLAG_ADDR    = 0xCAF1        -- beat_ganon: & 0x80 == Ganon beaten
local GANON_FLAG_MASK    = 0x80
local GOAL_BEAT_VERAN    = 0             -- OracleOfAgesGoal.option_beat_veran
local GOAL_BEAT_GANON    = 1             -- OracleOfAgesGoal.option_beat_ganon

-- ── Location table (GENERATED from worlds/tloz_ooa; 226 flag entries) ──────────
-- ap_id -> list of { a = flag byte address, m = mask } ALTERNATIVES. The id is the
-- sequential AP id from build_location_name_to_id_dict(). A location is checked
-- when ANY alternative satisfies (read_u8(a) & m) == m (Client.py tests each
-- flag_byte and breaks on the first hit; note the comparison is equality, not >0).
local LOC = {
  [27022002000]={{a=0xC739,m=0x20}},[27022002001]={{a=0xC8AE,m=0x20}},[27022002002]={{a=0xC749,m=0x20}},[27022002003]={{a=0xC643,m=0x20}},
  [27022002004]={{a=0xC643,m=0x40}},[27022002005]={{a=0xC643,m=0x80}},[27022002006]={{a=0xC642,m=0x01}},[27022002007]={{a=0xC642,m=0x02}},
  [27022002008]={{a=0xC642,m=0x08}},[27022002009]={{a=0xC8F9,m=0x20}},[27022002010]={{a=0xC615,m=0x01}},[27022002011]={{a=0xC9E1,m=0x20}},
  [27022002012]={{a=0xC8FC,m=0x20}},[27022002013]={{a=0xC643,m=0x01}},[27022002014]={{a=0xC643,m=0x02}},[27022002015]={{a=0xC643,m=0x04}},
  [27022002016]={{a=0xCACB,m=0x20}},[27022002017]={{a=0xC6D1,m=0x20}},[27022002018]={{a=0xC6D9,m=0x02}},[27022002019]={{a=0xC738,m=0x20}},
  [27022002020]={{a=0xC798,m=0x20}},[27022002021]={{a=0xC6D0,m=0x08}},[27022002022]={{a=0xC6D8,m=0x40}},[27022002023]={{a=0xCABF,m=0x20}},
  [27022002024]={{a=0xCAB6,m=0x20}},[27022002025]={{a=0xCAED,m=0x20}},[27022002026]={{a=0xC642,m=0x80}},[27022002027]={{a=0xC642,m=0x20}},
  [27022002028]={{a=0xC642,m=0x40}},[27022002029]={{a=0xC784,m=0x20}},[27022002030]={{a=0xCAB3,m=0x20}},[27022002031]={{a=0xCAB5,m=0x20}},
  [27022002032]={{a=0xC6D9,m=0x04}},[27022002033]={{a=0xCAE9,m=0x20}},[27022002034]={{a=0xCACA,m=0x20}},[27022002035]={{a=0xC7CE,m=0x20}},
  [27022002036]={{a=0xC7DE,m=0x20}},[27022002037]={{a=0xC6D6,m=0x40}},[27022002038]={{a=0xC6D6,m=0x80}},[27022002039]={{a=0xCAF7,m=0x20}},
  [27022002040]={{a=0xC8FD,m=0x20}},[27022002041]={{a=0xC7EC,m=0x20},{a=0xCAB8,m=0x20},{a=0xC7F4,m=0x20}},[27022002042]={{a=0xC86E,m=0x20},{a=0xC86F,m=0x20}},[27022002043]={{a=0xC88F,m=0x20}},
  [27022002044]={{a=0xC6D3,m=0x10}},[27022002045]={{a=0xC763,m=0x20}},[27022002046]={{a=0xC6D3,m=0x40}},[27022002047]={{a=0xC6D5,m=0x20}},
  [27022002048]={{a=0xCAC3,m=0x20}},[27022002049]={{a=0xCAC0,m=0x20}},[27022002050]={{a=0xC7BE,m=0x20}},[27022002051]={{a=0xC709,m=0x20}},
  [27022002052]={{a=0xCABD,m=0x20}},[27022002053]={{a=0xCAB9,m=0x20}},[27022002054]={{a=0xC7FC,m=0x20}},[27022002055]={{a=0xC7F7,m=0x20}},
  [27022002056]={{a=0xC6D0,m=0x80}},[27022002057]={{a=0xC6D1,m=0x08}},[27022002058]={{a=0xC7FF,m=0x20}},[27022002059]={{a=0xCAE0,m=0x20}},
  [27022002060]={{a=0xCAE1,m=0x20}},[27022002061]={{a=0xC80E,m=0x20}},[27022002062]={{a=0xC7FD,m=0x20}},[27022002063]={{a=0xC8E7,m=0x20}},
  [27022002064]={{a=0xC81F,m=0x40}},[27022002065]={{a=0xC81F,m=0x20}},[27022002066]={{a=0xCAD8,m=0x20}},[27022002067]={{a=0xCAD8,m=0x40}},
  [27022002068]={{a=0xC83E,m=0x20}},[27022002069]={{a=0xCAEE,m=0x20}},[27022002070]={{a=0xCADD,m=0x20}},[27022002071]={{a=0xC7C0,m=0x20}},
  [27022002072]={{a=0xCAAC,m=0x20}},[27022002073]={{a=0xCAC7,m=0x20}},[27022002074]={{a=0xC791,m=0x20}},[27022002075]={{a=0xCAAB,m=0x20}},
  [27022002076]={{a=0xCAC8,m=0x20}},[27022002077]={{a=0xCAE4,m=0x20}},[27022002078]={{a=0xC7D5,m=0x20}},[27022002079]={{a=0xC74F,m=0x20}},
  [27022002080]={{a=0xC7A0,m=0x20}},[27022002081]={{a=0xCAF8,m=0x20}},[27022002082]={{a=0xC8FF,m=0x20}},[27022002083]={{a=0xC86D,m=0x20}},
  [27022002084]={{a=0xC77C,m=0x20}},[27022002085]={{a=0xC72F,m=0x20}},[27022002086]={{a=0xC73E,m=0x20}},[27022002087]={{a=0xC73F,m=0x20}},
  [27022002088]={{a=0xC7E6,m=0x20}},[27022002089]={{a=0xC7E7,m=0x20}},[27022002090]={{a=0xC7E8,m=0x20}},[27022002091]={{a=0xC756,m=0x20}},
  [27022002092]={{a=0xC7F3,m=0x20}},[27022002093]={{a=0xC6D2,m=0x80}},[27022002094]={{a=0xC71F,m=0x20}},[27022002095]={{a=0xC7F5,m=0x20}},
  [27022002096]={{a=0xC886,m=0x20}},[27022002097]={{a=0xC906,m=0x20}},[27022002098]={{a=0xC78B,m=0x20}},[27022002099]={{a=0xCAB1,m=0x20}},
  [27022002100]={{a=0xC8AF,m=0x20}},[27022002101]={{a=0xC711,m=0x20}},[27022002102]={{a=0xCAC1,m=0x20}},[27022002103]={{a=0xC70D,m=0x20}},
  [27022002104]={{a=0xC908,m=0x20}},[27022002105]={{a=0xC905,m=0x20}},[27022002106]={{a=0xC915,m=0x20}},[27022002107]={{a=0xC916,m=0x20}},
  [27022002108]={{a=0xC91A,m=0x20}},[27022002109]={{a=0xC91C,m=0x20}},[27022002110]={{a=0xC91D,m=0x20}},[27022002111]={{a=0xC91F,m=0x20}},
  [27022002112]={{a=0xC923,m=0x20}},[27022002113]={{a=0xC925,m=0x20}},[27022002114]={{a=0xC91E,m=0x20}},[27022002115]={{a=0xC910,m=0x20}},
  [27022002116]={{a=0xC913,m=0x20}},[27022002117]={{a=0xC93E,m=0x20}},[27022002118]={{a=0xC940,m=0x20}},[27022002119]={{a=0xC941,m=0x20}},
  [27022002120]={{a=0xC945,m=0x20}},[27022002121]={{a=0xC948,m=0x20}},[27022002122]={{a=0xC939,m=0x20}},[27022002123]={{a=0xC942,m=0x20}},
  [27022002124]={{a=0xC927,m=0x20}},[27022002125]={{a=0xC928,m=0x20}},[27022002126]={{a=0xC930,m=0x20}},[27022002127]={{a=0xC92E,m=0x20}},
  [27022002128]={{a=0xC92B,m=0x20}},[27022002129]={{a=0xC94E,m=0x20}},[27022002130]={{a=0xC958,m=0x20}},[27022002131]={{a=0xC95C,m=0x20}},
  [27022002132]={{a=0xC960,m=0x20}},[27022002133]={{a=0xC965,m=0x20}},[27022002134]={{a=0xC95E,m=0x20}},[27022002135]={{a=0xC961,m=0x20}},
  [27022002136]={{a=0xC964,m=0x20}},[27022002137]={{a=0xC94B,m=0x20}},[27022002138]={{a=0xC950,m=0x20}},[27022002139]={{a=0xC955,m=0x20}},
  [27022002140]={{a=0xC956,m=0x20}},[27022002141]={{a=0xC94A,m=0x20}},[27022002142]={{a=0xC974,m=0x20}},[27022002143]={{a=0xC97A,m=0x20}},
  [27022002144]={{a=0xC987,m=0x20}},[27022002145]={{a=0xC98B,m=0x20}},[27022002146]={{a=0xC98F,m=0x20}},[27022002147]={{a=0xC990,m=0x20}},
  [27022002148]={{a=0xC992,m=0x20}},[27022002149]={{a=0xC97B,m=0x20}},[27022002150]={{a=0xC96F,m=0x20}},[27022002151]={{a=0xC96B,m=0x20}},
  [27022002152]={{a=0xC9AD,m=0x20}},[27022002153]={{a=0xC9BA,m=0x20}},[27022002154]={{a=0xC9BC,m=0x20}},[27022002155]={{a=0xC9BE,m=0x20}},
  [27022002156]={{a=0xC99F,m=0x20}},[27022002157]={{a=0xC999,m=0x20}},[27022002158]={{a=0xC99B,m=0x20}},[27022002159]={{a=0xC99E,m=0x20}},
  [27022002160]={{a=0xC9A3,m=0x20}},[27022002161]={{a=0xC9A5,m=0x20}},[27022002162]={{a=0xC9BF,m=0x20}},[27022002163]={{a=0xCA13,m=0x20}},
  [27022002164]={{a=0xCA14,m=0x20}},[27022002165]={{a=0xCA1B,m=0x20}},[27022002166]={{a=0xCA1C,m=0x20}},[27022002167]={{a=0xCA1D,m=0x20}},
  [27022002168]={{a=0xCA1F,m=0x20}},[27022002169]={{a=0xCA21,m=0x20}},[27022002170]={{a=0xCA25,m=0x20}},[27022002171]={{a=0xCA3C,m=0x20}},
  [27022002172]={{a=0xCA3F,m=0x20}},[27022002173]={{a=0xCA41,m=0x20}},[27022002174]={{a=0xCA45,m=0x20}},[27022002175]={{a=0xCA2C,m=0x20}},
  [27022002176]={{a=0xCA2E,m=0x20}},[27022002177]={{a=0xCA31,m=0x20}},[27022002178]={{a=0xCA36,m=0x20}},[27022002179]={{a=0xCA4C,m=0x20}},
  [27022002180]={{a=0xCA4D,m=0x20}},[27022002181]={{a=0xCA4E,m=0x20}},[27022002182]={{a=0xCA53,m=0x20}},[27022002183]={{a=0xCA50,m=0x20}},
  [27022002184]={{a=0xCA4B,m=0x20}},[27022002185]={{a=0xCA55,m=0x20}},[27022002186]={{a=0xCA54,m=0x20}},[27022002187]={{a=0xCA5F,m=0x20}},
  [27022002188]={{a=0xCA64,m=0x20}},[27022002189]={{a=0xCA65,m=0x20}},[27022002190]={{a=0xCA6A,m=0x20}},[27022002191]={{a=0xCA6C,m=0x20}},
  [27022002192]={{a=0xCA72,m=0x20}},[27022002193]={{a=0xCA62,m=0x20}},[27022002194]={{a=0xCAA7,m=0x20}},[27022002195]={{a=0xCA7B,m=0x20}},
  [27022002196]={{a=0xCA7C,m=0x20}},[27022002197]={{a=0xCA7E,m=0x20}},[27022002198]={{a=0xCA85,m=0x20}},[27022002199]={{a=0xCA92,m=0x20}},
  [27022002200]={{a=0xCA94,m=0x20}},[27022002201]={{a=0xCA97,m=0x20}},[27022002202]={{a=0xCA9F,m=0x20}},[27022002203]={{a=0xCAA3,m=0x20}},
  [27022002204]={{a=0xCAA4,m=0x20}},[27022002205]={{a=0xCAA6,m=0x20}},[27022002206]={{a=0xCA91,m=0x20}},[27022002207]={{a=0xCA98,m=0x20}},
  [27022002208]={{a=0xCA79,m=0x20}},[27022002209]={{a=0xCA78,m=0x20}},[27022002210]={{a=0xC911,m=0x20}},[27022002211]={{a=0xC938,m=0x20}},
  [27022002212]={{a=0xC949,m=0x20}},[27022002213]={{a=0xC969,m=0x20}},[27022002214]={{a=0xC9B8,m=0x20}},[27022002215]={{a=0xCA37,m=0x20}},
  [27022002216]={{a=0xCA61,m=0x20}},[27022002217]={{a=0xCA77,m=0x20}},[27022002218]={{a=0xC778,m=0x20},{a=0xC878,m=0x20}},[27022002219]={{a=0xC825,m=0x20}},
  [27022002220]={{a=0xC880,m=0x20}},[27022002221]={{a=0xC7AC,m=0x20}},[27022002222]={{a=0xC713,m=0x20}},[27022002223]={{a=0xC808,m=0x20}},
  [27022002224]={{a=0xC82D,m=0x20}},[27022002225]={{a=0xC7C1,m=0x20},{a=0xC8C1,m=0x20}},
}

-- ── State ─────────────────────────────────────────────────────────────────────
local reported         = {}     -- ap_id -> true once returned from poll()
local server_locations = nil    -- set of ap_ids the server expects (nil = all)
local rom_ok           = nil     -- cached OoA-cart result
local goal_option      = nil     -- slot_data goal (0/1), or nil = accept either
local mem              = {}
local log_fn           = nil

-- ── Logging ───────────────────────────────────────────────────────────────────
local function log(msg)
  if log_fn then pcall(log_fn, "[tloz_ooa] " .. tostring(msg)) end
end

-- ── Memory API (resolved at init; 2-arg domain form + current-domain fallback) ─
local function resolve_memory_api()
  if not memory then return false end
  mem.read_u8 = memory.read_u8 or memory.readbyte
  return mem.read_u8 ~= nil
end

local function read_u8(addr, domain)
  if not mem.read_u8 then return nil end
  local ok, v = pcall(mem.read_u8, addr, domain)
  if ok and type(v) == "number" then return v end
  ok, v = pcall(mem.read_u8, addr)            -- older API: current domain
  if ok and type(v) == "number" then return v end
  return nil
end

local function bit_and(a, b)
  local res, bitval = 0, 1
  while a > 0 and b > 0 do
    if a % 2 == 1 and b % 2 == 1 then res = res + bitval end
    a = math.floor(a / 2); b = math.floor(b / 2); bitval = bitval * 2
  end
  return res
end

-- ── ROM identity: an Oracle of Ages cart reads "ZELDA NAYRU" at header 0x0134.
--    (Seasons reads "ZELDA DIN"; vanilla/garbage carts read neither.) Matches the
--    client's own validate_rom check exactly, so this self-disables on anything
--    that is not running Oracle of Ages, never on a real OoA cart. ─────────────
local function rom_is_ap()
  if rom_ok ~= nil then return rom_ok end
  for i = 1, #GAME_IDENT_STR do
    local b = read_u8(GAME_IDENT_ADDR + i - 1, ROM)
    if b == nil then return false end           -- not readable yet; retry next poll
    if b ~= string.byte(GAME_IDENT_STR, i) then
      rom_ok = false
      log("non-OoA ROM (no 'ZELDA NAYRU' at 0x0134) — detection idle")
      return false
    end
  end
  rom_ok = true
  log("Oracle of Ages cart detected ('ZELDA NAYRU' at 0x0134) — detection live")
  return true
end

-- ── Multiworld context ────────────────────────────────────────────────────────
local function load_locations(ids)
  if type(ids) ~= "table" then return end
  server_locations = {}
  local n = 0
  for _, id in ipairs(ids) do
    local v = tonumber(id)
    if v then server_locations[v] = true; n = n + 1 end
  end
  log("server location set: " .. n .. " ids")
end

local function load_goal(slot_data)
  if type(slot_data) ~= "table" then return end
  -- slot_data may carry goal directly or nested under "options". Accept either.
  local g = slot_data.goal
  if g == nil and type(slot_data.options) == "table" then g = slot_data.options.goal end
  local gv = tonumber(g)
  if gv ~= nil then
    goal_option = gv
    log("goal option = " .. tostring(gv) ..
        (gv == GOAL_BEAT_GANON and " (beat_ganon)" or " (beat_veran)"))
  end
end

local function wanted(ap_id)
  if server_locations == nil then return true end
  return server_locations[ap_id] == true
end

-- ── Detection gate (Client.py game_watcher: read_result[0][0] == 2) ───────────
local function in_gameplay()
  local s = read_u8(GAME_STATE_ADDR, SYSBUS)
  return s ~= nil and s == GAME_STATE_INGAME
end

-- ── Per-flag evaluation: ANY alternative with (byte & mask) == mask (equality).
--    Mirrors Client.py iterating the flag_byte list and breaking on first hit. ──
local function flag_done(alts)
  for _, e in ipairs(alts) do
    local b = read_u8(e.a, SYSBUS)
    if b ~= nil and bit_and(b, e.m) == e.m then return true end
  end
  return false
end

local function current_room()
  local hi = read_u8(MAP_GROUP_ADDR, SYSBUS)
  local lo = read_u8(MAP_ID_ADDR, SYSBUS)
  if hi == nil or lo == nil then return nil end
  return hi * 0x100 + lo
end

-- ── Module contract ───────────────────────────────────────────────────────────
function M.init(ctx)
  if ctx and type(ctx.log) == "function" then log_fn = ctx.log end
  if not resolve_memory_api() then
    log("BizHawk memory API unavailable — module idle")
    ADDRESSES_VERIFIED = false
    return
  end
  local cfg = (ctx and ctx.config) or {}
  load_locations(cfg.locations)
  load_goal(cfg.slot_data)
  local n = 0; for _ in pairs(LOC) do n = n + 1 end
  log("ready: " .. n .. " flag locations (0x" .. string.format("%04X", FLAGS_LOW) ..
      "..0x" .. string.format("%04X", FLAGS_HIGH) .. ")")
end

function M.poll()
  local new = {}
  if not ADDRESSES_VERIFIED then return new end
  if not rom_is_ap() then return new end
  if not in_gameplay() then return new end

  -- Flag-bit locations.
  for ap_id, alts in pairs(LOC) do
    if not reported[ap_id] and wanted(ap_id) and flag_done(alts) then
      reported[ap_id] = true
      new[#new + 1] = ap_id
    end
  end

  return new
end

function M.is_goal_complete()
  if not ADDRESSES_VERIFIED or not rom_is_ap() then return false end
  if not in_gameplay() then return false end

  -- beat_veran: Veran flag set (NO room requirement — OoA default goal).
  local vf = read_u8(VERAN_FLAG_ADDR, SYSBUS)
  local veran_done = (vf ~= nil and bit_and(vf, VERAN_FLAG_MASK) == VERAN_FLAG_MASK)

  -- beat_ganon: reached Zelda's ending room AND Ganon flag set.
  local ganon_done = false
  local room = current_room()
  if room == ROOM_ZELDA_ENDING then
    local gf = read_u8(GANON_FLAG_ADDR, SYSBUS)
    ganon_done = (gf ~= nil and bit_and(gf, GANON_FLAG_MASK) == GANON_FLAG_MASK)
  end

  if goal_option == GOAL_BEAT_VERAN then
    return veran_done
  elseif goal_option == GOAL_BEAT_GANON then
    return ganon_done
  end
  -- Unknown goal (no slot_data): accept either terminal condition. Neither can
  -- false-positive — both are final-boss-defeated flags.
  return veran_done or ganon_done
end

-- Remote multiworld items: see the file header. OoA items_handling = 0b101
-- (remote items + starting inventory). Delivering REMOTE items is the client's
-- guarded write path (poll the received-item count at 0xC6A8, write id/subid into
-- the struct at 0xCBFB only while it is empty). That write path is the one piece
-- deferred until it can be confirmed in-emulator. No-op (never a wrong write)
-- until then; check reporting + goal are fully live regardless.
function M.receive_item(item_id, meta)
  -- intentionally empty (documented)
end

return M
