-- ═══════════════════════════════════════════════════════════════════════════════
-- wario_land_4.lua — game module for the Archipelago BizHawk connector.
--                    Wario Land 4 (GBA)
--
-- COMMUNITY APWORLD. Not in ArchipelagoMW/Archipelago main. Source:
--   https://github.com/lilDavid/Archipelago-Wario-Land-4   (author: lil David,
--   world_version 3.3.3, minimum_ap_version 0.6.0). The base patch lives at
--   https://github.com/lilDavid/WL4-Archipelago-Patch .
--
-- STATUS: location DETECTION + goal are REAL and SOURCE-DERIVED from that world
-- (client.py = WL4Client(BizHawkClient) + locations.py + data.py + rom.py, main
-- branch). The 292-entry location table below was GENERATED by importing the
-- world's own locations.py and calling LocationData.to_ap_id() — not hand-copied,
-- so every id is exact. Loads crash-free on any ROM and self-disables on a
-- non-AP / non-WL4 cartridge (the 12-byte ROM name guard).
--
-- MEMORY MODEL (BizHawk GBA "System Bus" domain — exactly what client.py reads)
-- ────────────────────────────────────────────────────────────────────────────
--   WL4Client reads everything through the GBA System Bus with ABSOLUTE
--   addresses (resolved from the world's basepatch.sym), not EWRAM-relative
--   offsets. We mirror that one-to-one:
--     System Bus 0x080000A0, 12  -> cartridge internal name (ROM identity)
--     System Bus 0x03000C3A  u16 -> GlobalGameMode (main game mode)
--     System Bus 0x03000A68      -> W4ItemStatus: the inventory array,
--                                   len(Passage)=6 * 6 levels * u32 = 144 bytes.
--   INVENTORY LAYOUT (handle_inventory): the array is 36 little-endian u32, one
--   per (passage, level): status_word = u32 @ W4ItemStatus + (passage*6+level)*4.
--   The per-level "collection" bitfield is status_word >> 8. A location is
--   CHECKED when  (status_word >> 8) & location.flag  is non-zero, where
--   location.flag is the raw ItemFlag value (JEWEL_NE=1<<0 … DIAMOND_11=1<<18,
--   CD=1<<4, KEYZER=1<<5). This is get_collected_locations() byte-for-byte.
--
-- DETECTION GATE (handle_inventory): GlobalGameMode ∈ {SELECT=1, INGAME=2}.
--   On the title cutscene (mode 0) the inventory is not yet meaningful, so the
--   client never scans it there — neither do we.
--
-- GOAL (handle_goal): u32 @ W4ItemStatus + 4*(6*GOLDEN + BOSS_LEVEL)
--   = W4ItemStatus + 4*(6*5 + 4) = W4ItemStatus + 0x88, masked with
--   ItemFlag.DIVA_CLEAR (1<<4 = 0x10): the Golden Diva defeated flag. (This
--   high word is read RAW, NOT >>8 — the client masks the raw status word.)
--   The flag only sets after the final boss, so it cannot false-positive before
--   then; we additionally require the AP ROM identity.
--
-- ITEM DELIVERY (items_handling = LOCAL_ITEMS = 0b001)
-- ──────────────────────────────────────────────────────────────────────────
--   WL4 is a SELF-GRANTING ROM: the patch makes the game award its own locally
--   found items, and items_handling=0b001 means the server sends only OTHER
--   players' items to us. A SOLO seed therefore plays fully and every check is
--   reported with NO item writes at all. Delivering REMOTE multiworld items is
--   the client's guarded System-Bus mailbox handshake (handle_received_items):
--   it writes IncomingItemID (0x03006280) + an encoded sender string into
--   IncomingItemSender (0x03006282) + sets MultiworldState (0x03006281) to
--   ITEM_QUEUED, all guarded on the game mode AND MultiworldState==IDLE, then
--   the game's ASM consumes it and bumps received_item_count (W4ItemStatus+14).
--   That write path needs in-emulator verification (a wrong System-Bus write
--   into the live game corrupts state), and the sender-string encoding depends
--   on per-seed player names the module is not handed, so it is intentionally
--   left as a documented NO-OP rather than shipped unverified. Checks + goal
--   flow fully regardless. See receive_item() at the bottom.
--
-- MODULE CONTRACT (called by bizhawk_ap_connector.lua)
--   M.init(ctx) / M.poll() -> {ids} / M.is_goal_complete() -> bool /
--   M.receive_item(item_id, meta)
-- ═══════════════════════════════════════════════════════════════════════════════

local M = {}
M.name = "wario_land_4"

local ADDRESSES_VERIFIED = true   -- table generated from the WL4 world source

-- ── Memory domain ─────────────────────────────────────────────────────────────
-- The WL4 BizHawkClient uses "System Bus" for every read (absolute GBA addresses).
local SYSBUS = "System Bus"
local ROMDOM = "ROM"   -- fallback alias used only if System Bus rejects the ROM read

-- ── Addresses / constants (worlds WL4 client.py + data.py basepatch.sym) ───────
local ROM_NAME_ADDR    = 0x080000A0   -- System Bus: cartridge internal name (12 bytes)
local AP_NAME_US       = "WARIOLANDAPE"  -- patched US/EU header (update_header)
local AP_NAME_JP       = "WARIOLANDAPJ"  -- patched JP header
-- Unpatched headers that must self-disable: "WARIOLANDE\0\0" / "WARIOLAND\0\0\0".

local GAME_MODE_ADDR   = 0x03000C3A   -- System Bus: GlobalGameMode (u16)
local GAMEMODE_SELECT  = 1
local GAMEMODE_INGAME  = 2

local ITEM_STATUS_ADDR = 0x03000A68   -- System Bus: W4ItemStatus inventory base
local PASSAGE_COUNT    = 6             -- len(Passage)
local LEVELS_PER_PASS  = 6             -- 6 u32 per passage (<6I)

-- Goal: W4ItemStatus + 4*(6*GOLDEN + BOSS_LEVEL); GOLDEN=5, BOSS_LEVEL=4.
local GOAL_PASSAGE     = 5
local GOAL_LEVEL       = 4
local GOAL_MASK        = 0x10          -- ItemFlag.DIVA_CLEAR (1<<4)

-- ── Location table (GENERATED from the WL4 world's locations.py) ──────────────
-- ap_id -> {passage, level, flag_value}. 292 entries. A location is checked when
-- (u32 @ ITEM_STATUS_ADDR + (passage*6+level)*4 >> 8) & flag_value ~= 0.
local LOC = {
  [15466539]={0,0,1024},[15466604]={0,0,2048},[15466634]={0,0,512},[15466721]={0,0,1},
  [15466722]={0,0,2},[15466723]={0,0,4},[15466724]={0,0,8},[15466726]={0,0,32},
  [15466727]={0,0,64},[15466729]={0,0,256},[15466733]={0,0,4096},[15468065]={1,0,1},
  [15468066]={1,0,2},[15468075]={1,0,1024},[15468076]={1,0,2048},[15468097]={1,0,1},
  [15468161]={1,0,1},[15468170]={1,0,512},[15468226]={1,0,2},[15468259]={1,0,4},
  [15468260]={1,0,8},[15468261]={1,0,16},[15468262]={1,0,32},[15468263]={1,0,64},
  [15468269]={1,0,4096},[15468270]={1,0,8192},[15468271]={1,0,16384},[15468322]={1,1,2},
  [15468323]={1,1,4},[15468327]={1,1,64},[15468332]={1,1,2048},[15468334]={1,1,8192},
  [15468482]={1,1,2},[15468483]={1,1,4},[15468513]={1,1,1},[15468516]={1,1,8},
  [15468517]={1,1,16},[15468518]={1,1,32},[15468521]={1,1,256},[15468522]={1,1,512},
  [15468523]={1,1,1024},[15468525]={1,1,4096},[15468527]={1,1,16384},[15468528]={1,1,32768},
  [15468577]={1,2,1},[15468578]={1,2,2},[15468579]={1,2,4},[15468580]={1,2,8},
  [15468585]={1,2,256},[15468587]={1,2,1024},[15468589]={1,2,4096},[15468610]={1,2,2},
  [15468674]={1,2,2},[15468737]={1,2,1},[15468739]={1,2,4},[15468740]={1,2,8},
  [15468746]={1,2,512},[15468773]={1,2,16},[15468774]={1,2,32},[15468775]={1,2,64},
  [15468780]={1,2,2048},[15468782]={1,2,8192},[15468783]={1,2,16384},[15468833]={1,3,1},
  [15468835]={1,3,4},[15468841]={1,3,256},[15468842]={1,3,512},[15468843]={1,3,1024},
  [15468865]={1,3,1},[15468929]={1,3,1},[15468995]={1,3,4},[15469026]={1,3,2},
  [15469028]={1,3,8},[15469029]={1,3,16},[15469030]={1,3,32},[15469031]={1,3,64},
  [15469036]={1,3,2048},[15469037]={1,3,4096},[15469281]={1,4,1},[15469282]={1,4,2},
  [15469283]={1,4,4},[15469601]={2,0,1},[15469602]={2,0,2},[15469603]={2,0,4},
  [15469604]={2,0,8},[15469609]={2,0,256},[15469610]={2,0,512},[15469611]={2,0,1024},
  [15469761]={2,0,1},[15469762]={2,0,2},[15469763]={2,0,4},[15469764]={2,0,8},
  [15469797]={2,0,16},[15469798]={2,0,32},[15469804]={2,0,2048},[15469805]={2,0,4096},
  [15469857]={2,1,1},[15469859]={2,1,4},[15469860]={2,1,8},[15469863]={2,1,64},
  [15469865]={2,1,256},[15469868]={2,1,2048},[15469871]={2,1,16384},[15470017]={2,1,1},
  [15470019]={2,1,4},[15470020]={2,1,8},[15470050]={2,1,2},[15470053]={2,1,16},
  [15470054]={2,1,32},[15470058]={2,1,512},[15470059]={2,1,1024},[15470061]={2,1,4096},
  [15470062]={2,1,8192},[15470064]={2,1,32768},[15470115]={2,2,4},[15470116]={2,2,8},
  [15470122]={2,2,512},[15470124]={2,2,2048},[15470126]={2,2,8192},[15470127]={2,2,16384},
  [15470275]={2,2,4},[15470276]={2,2,8},[15470305]={2,2,1},[15470306]={2,2,2},
  [15470309]={2,2,16},[15470310]={2,2,32},[15470313]={2,2,256},[15470315]={2,2,1024},
  [15470317]={2,2,4096},[15470320]={2,2,32768},[15470321]={2,2,65536},[15470322]={2,2,131072},
  [15470323]={2,2,262144},[15470378]={2,3,512},[15470379]={2,3,1024},[15470433]={2,3,1},
  [15470439]={2,3,64},[15470465]={2,3,1},[15470471]={2,3,64},[15470472]={2,3,128},
  [15470537]={2,3,256},[15470562]={2,3,2},[15470563]={2,3,4},[15470564]={2,3,8},
  [15470565]={2,3,16},[15470566]={2,3,32},[15470572]={2,3,2048},[15470573]={2,3,4096},
  [15470817]={2,4,1},[15470818]={2,4,2},[15470819]={2,4,4},[15471138]={3,0,2},
  [15471139]={3,0,4},[15471140]={3,0,8},[15471147]={3,0,1024},[15471148]={3,0,2048},
  [15471171]={3,0,4},[15471177]={3,0,256},[15471201]={3,0,1},[15471207]={3,0,64},
  [15471233]={3,0,1},[15471235]={3,0,4},[15471245]={3,0,4096},[15471298]={3,0,2},
  [15471300]={3,0,8},[15471333]={3,0,16},[15471334]={3,0,32},[15471338]={3,0,512},
  [15471342]={3,0,8192},[15471393]={3,1,1},[15471394]={3,1,2},[15471395]={3,1,4},
  [15471396]={3,1,8},[15471401]={3,1,256},[15471402]={3,1,512},[15471403]={3,1,1024},
  [15471404]={3,1,2048},[15471463]={3,1,64},[15471553]={3,1,1},[15471554]={3,1,2},
  [15471555]={3,1,4},[15471556]={3,1,8},[15471589]={3,1,16},[15471590]={3,1,32},
  [15471597]={3,1,4096},[15471649]={3,2,1},[15471650]={3,2,2},[15471651]={3,2,4},
  [15471652]={3,2,8},[15471658]={3,2,512},[15471659]={3,2,1024},[15471721]={3,2,256},
  [15471809]={3,2,1},[15471810]={3,2,2},[15471811]={3,2,4},[15471812]={3,2,8},
  [15471845]={3,2,16},[15471846]={3,2,32},[15471852]={3,2,2048},[15471853]={3,2,4096},
  [15471971]={3,3,4},[15471977]={3,3,256},[15471978]={3,3,512},[15472003]={3,3,4},
  [15472097]={3,3,1},[15472098]={3,3,2},[15472100]={3,3,8},[15472101]={3,3,16},
  [15472102]={3,3,32},[15472353]={3,4,1},[15472354]={3,4,2},[15472355]={3,4,4},
  [15472673]={4,0,1},[15472674]={4,0,2},[15472675]={4,0,4},[15472682]={4,0,512},
  [15472685]={4,0,4096},[15472833]={4,0,1},[15472834]={4,0,2},[15472835]={4,0,4},
  [15472868]={4,0,8},[15472869]={4,0,16},[15472870]={4,0,32},[15472873]={4,0,256},
  [15472875]={4,0,1024},[15472876]={4,0,2048},[15472878]={4,0,8192},[15472930]={4,1,2},
  [15472931]={4,1,4},[15472938]={4,1,512},[15472939]={4,1,1024},[15472940]={4,1,2048},
  [15472941]={4,1,4096},[15473090]={4,1,2},[15473091]={4,1,4},[15473121]={4,1,1},
  [15473124]={4,1,8},[15473125]={4,1,16},[15473126]={4,1,32},[15473129]={4,1,256},
  [15473134]={4,1,8192},[15473135]={4,1,16384},[15473136]={4,1,32768},[15473137]={4,1,65536},
  [15473185]={4,2,1},[15473195]={4,2,1024},[15473196]={4,2,2048},[15473257]={4,2,256},
  [15473258]={4,2,512},[15473345]={4,2,1},[15473378]={4,2,2},[15473379]={4,2,4},
  [15473380]={4,2,8},[15473381]={4,2,16},[15473382]={4,2,32},[15473389]={4,2,4096},
  [15473390]={4,2,8192},[15473391]={4,2,16384},[15473441]={4,3,1},[15473442]={4,3,2},
  [15473443]={4,3,4},[15473444]={4,3,8},[15473449]={4,3,256},[15473450]={4,3,512},
  [15473547]={4,3,1024},[15473601]={4,3,1},[15473602]={4,3,2},[15473603]={4,3,4},
  [15473604]={4,3,8},[15473637]={4,3,16},[15473638]={4,3,32},[15473644]={4,3,2048},
  [15473645]={4,3,4096},[15473646]={4,3,8192},[15473889]={4,4,1},[15473890]={4,4,2},
  [15473891]={4,4,4},[15474401]={5,0,1},[15474402]={5,0,2},[15474403]={5,0,4},
  [15474404]={5,0,8},[15474406]={5,0,32},[15474409]={5,0,256},[15474410]={5,0,512},
  [15474411]={5,0,1024},[15474412]={5,0,2048},[15474413]={5,0,4096},[15474414]={5,0,8192},
  [15474415]={5,0,16384},[15474416]={5,0,32768},[15474417]={5,0,65536},[15474418]={5,0,131072},
}

-- ── State ─────────────────────────────────────────────────────────────────────
local reported         = {}     -- ap_id -> true once returned from poll()
local server_locations = nil    -- set of ap_ids the server expects (nil = all)
local rom_ok           = nil     -- cached AP-name result
local goal_reached     = false
local mem              = {}
local log_fn           = nil

-- ── Logging ───────────────────────────────────────────────────────────────────
local function log(msg)
  if log_fn then pcall(log_fn, "[wario_land_4] " .. tostring(msg)) end
end

-- ── Memory API (resolved at init; 2-arg domain form + current-domain fallback) ─
local function resolve_memory_api()
  if not memory then return false end
  mem.read_u8  = memory.read_u8     or memory.readbyte
  mem.read_u16 = memory.read_u16_le or memory.readword
  mem.read_u32 = memory.read_u32_le or memory.readdword
  return mem.read_u8 ~= nil
end

local function rd(fn, addr, domain)
  if not fn then return nil end
  local ok, v = pcall(fn, addr, domain)
  if ok and type(v) == "number" then return v end
  ok, v = pcall(fn, addr)            -- older API: current domain
  if ok and type(v) == "number" then return v end
  return nil
end

local function read_u8(addr, domain)  return rd(mem.read_u8,  addr, domain) end
local function read_u16(addr, domain) return rd(mem.read_u16, addr, domain) end
local function read_u32(addr, domain) return rd(mem.read_u32, addr, domain) end

-- ── Bit helpers (pure Lua, no bit library dependency) ─────────────────────────
local function bit_and(a, b)
  local res, bitval = 0, 1
  while a > 0 and b > 0 do
    if a % 2 == 1 and b % 2 == 1 then res = res + bitval end
    a = math.floor(a / 2); b = math.floor(b / 2); bitval = bitval * 2
  end
  return res
end

-- status_word >> 8 (logical shift on a non-negative 32-bit value).
local function shr8(v)
  return math.floor(v / 256)
end

-- ── ROM identity: the patched cartridge header reads "WARIOLANDAP{E,J}" ────────
local function rom_is_ap()
  if rom_ok ~= nil then return rom_ok end
  local chars = {}
  for i = 0, #AP_NAME_US - 1 do
    -- Read the 12-byte name through the System Bus (the ROM lives at 0x08000000
    -- on the bus); fall back to the "ROM" domain only if System Bus refuses.
    local b = read_u8(ROM_NAME_ADDR + i, SYSBUS)
    if b == nil then b = read_u8((ROM_NAME_ADDR - 0x08000000) + i, ROMDOM) end
    if b == nil then return false end          -- not readable yet; retry next poll
    chars[#chars + 1] = string.char(b)
  end
  local name = table.concat(chars)
  if name ~= AP_NAME_US and name ~= AP_NAME_JP then
    rom_ok = false
    log("non-AP/non-WL4 ROM (header '" .. name .. "') — detection idle")
    return false
  end
  rom_ok = true
  log("AP ROM verified (header '" .. name .. "')")
  return true
end

-- ── Multiworld context ────────────────────────────────────────────────────────
local function load_locations(ids)
  if type(ids) ~= "table" then return end
  server_locations = {}
  local n = 0
  for _, id in ipairs(ids) do
    local v = tonumber(id)
    if v then server_locations[v] = true; n = n + 1 end
  end
  log("server location set: " .. n .. " ids")
end

local function wanted(ap_id)
  if server_locations == nil then return true end
  return server_locations[ap_id] == true
end

-- ── Detection gate (handle_inventory): GlobalGameMode ∈ {SELECT, INGAME} ──────
local function in_gameplay()
  local mode = read_u16(GAME_MODE_ADDR, SYSBUS)
  return mode == GAMEMODE_SELECT or mode == GAMEMODE_INGAME
end

-- Cache the 36-entry inventory once per poll (status_word per passage/level).
local inv = {}     -- key = passage*6+level -> u32 status word

local function refresh_inventory()
  for slot = 0, PASSAGE_COUNT * LEVELS_PER_PASS - 1 do
    inv[slot] = read_u32(ITEM_STATUS_ADDR + slot * 4, SYSBUS)
  end
end

-- A location is checked when (status_word >> 8) & flag_value ~= 0
-- (get_collected_locations: collection = status_bits >> 8; if collection & bit).
local function location_checked(passage, level, flag_value)
  local status = inv[passage * LEVELS_PER_PASS + level]
  if status == nil then return false end
  return bit_and(shr8(status), flag_value) ~= 0
end

-- ── Module contract ───────────────────────────────────────────────────────────
function M.init(ctx)
  if ctx and type(ctx.log) == "function" then log_fn = ctx.log end
  if not resolve_memory_api() then
    log("BizHawk memory API unavailable — module idle")
    ADDRESSES_VERIFIED = false
    return
  end
  local cfg = (ctx and ctx.config) or {}
  load_locations(cfg.locations)
  local n = 0; for _ in pairs(LOC) do n = n + 1 end
  log("ready: " .. n .. " location flags (System Bus inventory scan)")
end

function M.poll()
  local new = {}
  if not ADDRESSES_VERIFIED then return new end
  if not rom_is_ap() then return new end
  if not in_gameplay() then return new end

  refresh_inventory()
  for ap_id, info in pairs(LOC) do
    if not reported[ap_id] and wanted(ap_id)
       and location_checked(info[1], info[2], info[3]) then
      reported[ap_id] = true
      new[#new + 1] = ap_id
    end
  end

  -- Goal: the GOLDEN/BOSS_LEVEL status word & DIVA_CLEAR (read RAW, not >>8).
  if not goal_reached then
    local status = inv[GOAL_PASSAGE * LEVELS_PER_PASS + GOAL_LEVEL]
    if status == nil then
      status = read_u32(ITEM_STATUS_ADDR + (GOAL_PASSAGE * LEVELS_PER_PASS + GOAL_LEVEL) * 4, SYSBUS)
    end
    if status and bit_and(status, GOAL_MASK) ~= 0 then
      goal_reached = true
      log("goal reached (Golden Diva defeated — DIVA_CLEAR set)")
    end
  end

  return new
end

function M.is_goal_complete()
  if not ADDRESSES_VERIFIED or not rom_is_ap() then return false end
  if goal_reached then return true end
  -- Re-read the goal word directly so a goal-only poll still answers correctly.
  local status = read_u32(
    ITEM_STATUS_ADDR + (GOAL_PASSAGE * LEVELS_PER_PASS + GOAL_LEVEL) * 4, SYSBUS)
  if status and bit_and(status, GOAL_MASK) ~= 0 then
    goal_reached = true
  end
  return goal_reached
end

-- Remote multiworld items: see the file header. items_handling = LOCAL_ITEMS
-- (0b001) means the PATCHED GAME grants its own locally-found items, so solo
-- play and check reporting work fully; applying REMOTE items is the client's
-- guarded System-Bus mailbox handshake (IncomingItemID + IncomingItemSender +
-- MultiworldState), which depends on per-seed player-name encoding the module
-- is not handed and needs in-emulator confirmation before any System-Bus write.
-- No-op (never a wrong write) until then.
function M.receive_item(item_id, meta)
  -- intentionally empty (documented)
end

return M
