-- ═══════════════════════════════════════════════════════════════════════════════
-- yoshisisland.lua — game module for the Archipelago BizHawk connector.
--          Super Mario World 2: Yoshi's Island (SNES)
--
-- STATUS: location DETECTION + goal are REAL and SOURCE-DERIVED from the official
-- AP world worlds/yoshisisland (Client.py game_watcher + Rom.py location_table,
-- main branch, world_version 1.0.0). The 235-entry location table was GENERATED by
-- PARSING worlds/yoshisisland/Rom.py location_table (ap_id → [wram_addr, bit]) with
-- Python — not hand-copied — so every (AP id → flag byte / bit) pair is exact.
-- Loads crash-free on any ROM; self-disables on a non-AP cartridge.
--
-- MEMORY MODEL (SNI → BizHawk)  — see Research_V2/SNES_BRIDGE_2026-06-12.md
-- ──────────────────────────────────────────────────────────────────────────
--   The Yoshi's Island client is an SNIClient. Its SNI addresses translate to
--   BizHawk SNES memory domains:
--     SNI WRAM_START(0xF50000)+off → domain "WRAM",    offset off (= $7E0000+off)
--     SNI ROM_START(0x000000)+off  → domain "CARTROM", offset off (raw ROM file
--                                    offset; LoROM. Fallbacks "ROM"/"System Bus")
--   Unlike ALttP/SM, Yoshi's Island does NOT use SRAM/CARTRAM for detection. It
--   reads WRAM for live progress and CARTROM only for the ROM-header AP signature.
--   The identity string the client's validate_rom() checks is "YOSHIAP", written
--   by the patcher at CARTROM 0x7FC0 (rom_name[:7] == b"YOSHIAP").
--
-- HOW YOSHI'S ISLAND CHECKS WORK (mirrors worlds/yoshisisland/Client.py game_watcher)
--   The client reads a single flat WRAM region (0x1440, 0x80 bytes) and tests one
--   bit per location:
--       data        = location_ram[loc_addr - 0x1440]   -- the byte at loc_addr
--       masked_data = data & (1 << bit)
--       bit_set     = masked_data != 0
--       invert_bit  = (len(loc_data) >= 3) and loc_data[2]   -- inverted flag
--       checked iff  bit_set != invert_bit
--   In the current apworld EVERY location is the 2-element form [addr, bit] (no
--   invert entry exists), so the test reduces to a plain "bit is set". The table
--   below still carries an optional third field so a future inverted flag stays
--   faithful without a code change.
--   (loc_addr is 0x146D..0x14B2; bits 0..4. Each level contributes Red Coins /
--    Flowers / Stars / Level Clear, plus a few extra-panel / bonus-panel bits.)
--
-- WHAT THIS DOES
--   • poll(): the game_watcher location scan above → AP location ids, gated to the
--     slot's server location set and to the in-game state (GAME_MODE ∈ the five
--     VALID_GAME_STATES the client accepts).
--   • is_goal_complete(): GOALFLAG (WRAM 0x14B6) != 0x00 — the client sets
--     finished_game + CLIENT_GOAL on exactly that condition (it is the same flag
--     for the Bowser / Luigi-hunt goals, the patcher selects which fills it).
--   • receive_item(): NO-OP (documented). items_handling = 0b111 (full remote):
--     the Yoshi's Island client owns ALL item delivery — there is no game-self-
--     grant fallback. It delivers by writing the next item's "item code" into a
--     single WRAM byte (item_values[item][0] = 0x1467), gated on a recv-progress
--     counter (ITEMQUEUE_HIGH = WRAM 0x1465, a u16) AND on the live game state
--     (GAME_MODE valid, ITEM_RECEIVED == 0 i.e. the previous grant consumed).
--     Reproducing that handshake byte-for-byte is the one piece that needs
--     in-emulator verification before it is wired, so it is left out rather than
--     shipped unverified (a wrong write to 0x1467 mid-grant could drop/duplicate
--     an item). No writes until then; checks + goal above are fully functional.
--
-- MODULE CONTRACT (called by bizhawk_ap_connector.lua)
--   M.init(ctx) / M.poll() -> {ids} / M.is_goal_complete() -> bool /
--   M.receive_item(item_id, meta)
-- ═══════════════════════════════════════════════════════════════════════════════

local M = {}
M.name = "yoshisisland"

local ADDRESSES_VERIFIED = true   -- table parsed from worlds/yoshisisland/Rom.py

-- ── Memory domains ────────────────────────────────────────────────────────────
local WRAM    = "WRAM"
local CARTROM = "CARTROM"     -- SNES cartridge ROM in BizHawk; fallbacks below

-- ── Addresses / constants (worlds/yoshisisland/Client.py module top) ──────────
-- Expressed as BizHawk-domain offsets (already net of WRAM_START / ROM_START).
local ROMHASH_OFF   = 0x7FC0     -- CARTROM: ROM-header AP id; first 7 = "YOSHIAP"
local GAME_MODE_OFF = 0x0118     -- WRAM: main game-mode byte
local GOALFLAG_OFF  = 0x14B6     -- WRAM: non-zero once the goal is met
local LOC_REGION    = 0x1440     -- WRAM: base of the 0x80-byte location flag region

-- The five game modes in which the client scans for checks (Client.py
-- VALID_GAME_STATES). Outside these the world is on a menu / transition.
local VALID_GAME_STATES = { [0x0F]=true, [0x10]=true, [0x2C]=true, [0x16]=true, [0x1D]=true }

-- Bit value lookup (no bit library — cores vary).
local POW2 = { [0]=1, [1]=2, [2]=4, [3]=8, [4]=16, [5]=32, [6]=64, [7]=128 }

-- ── Location table (GENERATED from worlds/yoshisisland/Rom.py location_table) ──
-- ap_id -> { wram_addr, bit [, invert] }. 235 entries. wram_addr is the absolute
-- WRAM-domain offset of the flag byte (= $7E0000 + wram_addr); bit is 0..4. AP ids
-- are absolute location ids (0x305000-based), so detection is self-contained.
local LOC = {
  [3166240]={0x146D,0},[3166241]={0x146D,1},[3166242]={0x146D,2},[3166243]={0x146D,3},
  [3166244]={0x146E,0},[3166245]={0x146E,1},[3166246]={0x146E,2},[3166247]={0x146E,3},
  [3166248]={0x146F,0},[3166249]={0x146F,1},[3166250]={0x146F,2},[3166251]={0x146F,3},
  [3166252]={0x1470,0},[3166253]={0x1470,1},[3166254]={0x1470,2},[3166255]={0x1470,3},
  [3166257]={0x1471,0},[3166258]={0x1471,1},[3166259]={0x1471,2},[3166260]={0x1471,3},
  [3166261]={0x1472,0},[3166262]={0x1472,1},[3166263]={0x1472,2},[3166264]={0x1472,3},
  [3166265]={0x1473,0},[3166266]={0x1473,1},[3166267]={0x1473,2},[3166268]={0x1473,3},
  [3166269]={0x1474,0},[3166270]={0x1474,1},[3166271]={0x1474,2},[3166272]={0x1474,3},
  [3166273]={0x1479,0},[3166274]={0x1479,1},[3166275]={0x1479,2},[3166276]={0x1479,3},
  [3166277]={0x147A,0},[3166278]={0x147A,1},[3166279]={0x147A,2},[3166280]={0x147A,3},
  [3166281]={0x147B,0},[3166282]={0x147B,1},[3166283]={0x147B,2},[3166284]={0x147B,3},
  [3166285]={0x147C,0},[3166286]={0x147C,1},[3166287]={0x147C,2},[3166288]={0x147C,3},
  [3166289]={0x147D,0},[3166290]={0x147D,1},[3166291]={0x147D,2},[3166292]={0x147D,3},
  [3166293]={0x147E,0},[3166294]={0x147E,1},[3166295]={0x147E,2},[3166296]={0x147E,3},
  [3166297]={0x147F,0},[3166298]={0x147F,1},[3166299]={0x147F,2},[3166300]={0x147F,3},
  [3166301]={0x1480,0},[3166302]={0x1480,1},[3166303]={0x1480,2},[3166304]={0x1480,3},
  [3166305]={0x1485,0},[3166306]={0x1485,1},[3166307]={0x1485,2},[3166308]={0x1485,3},
  [3166309]={0x1486,0},[3166310]={0x1486,1},[3166311]={0x1486,2},[3166312]={0x1486,3},
  [3166313]={0x1487,0},[3166314]={0x1487,1},[3166315]={0x1487,2},[3166316]={0x1487,3},
  [3166317]={0x1488,0},[3166318]={0x1488,1},[3166319]={0x1488,2},[3166320]={0x1488,3},
  [3166321]={0x1489,0},[3166322]={0x1489,1},[3166323]={0x1489,2},[3166324]={0x1489,3},
  [3166325]={0x148A,0},[3166326]={0x148A,1},[3166327]={0x148A,2},[3166328]={0x148A,3},
  [3166329]={0x148B,0},[3166330]={0x148B,1},[3166331]={0x148B,2},[3166332]={0x148B,3},
  [3166333]={0x148C,0},[3166334]={0x148C,1},[3166335]={0x148C,2},[3166336]={0x148C,3},
  [3166337]={0x1491,0},[3166338]={0x1491,1},[3166339]={0x1491,2},[3166340]={0x1491,3},
  [3166341]={0x1492,0},[3166342]={0x1492,1},[3166343]={0x1492,2},[3166344]={0x1492,3},
  [3166345]={0x1493,0},[3166346]={0x1493,1},[3166347]={0x1493,2},[3166348]={0x1493,3},
  [3166349]={0x1494,0},[3166350]={0x1494,1},[3166351]={0x1494,2},[3166352]={0x1494,3},
  [3166353]={0x1495,0},[3166354]={0x1495,1},[3166355]={0x1495,2},[3166356]={0x1495,3},
  [3166357]={0x1496,0},[3166358]={0x1496,1},[3166359]={0x1496,2},[3166360]={0x1496,3},
  [3166361]={0x1497,0},[3166362]={0x1497,1},[3166363]={0x1497,2},[3166364]={0x1497,3},
  [3166365]={0x1498,0},[3166366]={0x1498,1},[3166367]={0x1498,2},[3166368]={0x1498,3},
  [3166369]={0x149D,0},[3166370]={0x149D,1},[3166371]={0x149D,2},[3166372]={0x149D,3},
  [3166373]={0x149E,0},[3166374]={0x149E,1},[3166375]={0x149E,2},[3166376]={0x149E,3},
  [3166377]={0x149F,0},[3166378]={0x149F,1},[3166379]={0x149F,2},[3166380]={0x149F,3},
  [3166381]={0x14A0,0},[3166382]={0x14A0,1},[3166383]={0x14A0,2},[3166384]={0x14A0,3},
  [3166385]={0x14A1,0},[3166386]={0x14A1,1},[3166387]={0x14A1,2},[3166388]={0x14A1,3},
  [3166389]={0x14A2,0},[3166390]={0x14A2,1},[3166391]={0x14A2,2},[3166392]={0x14A2,3},
  [3166393]={0x14A3,0},[3166394]={0x14A3,1},[3166395]={0x14A3,2},[3166396]={0x14A3,3},
  [3166397]={0x14A4,0},[3166398]={0x14A4,1},[3166399]={0x14A4,2},[3166400]={0x14A4,3},
  [3166401]={0x14A9,0},[3166402]={0x14A9,1},[3166403]={0x14A9,2},[3166404]={0x14A9,3},
  [3166405]={0x14AA,0},[3166406]={0x14AA,1},[3166407]={0x14AA,2},[3166408]={0x14AA,3},
  [3166409]={0x14AB,0},[3166410]={0x14AB,1},[3166411]={0x14AB,2},[3166412]={0x14AB,3},
  [3166413]={0x14AC,0},[3166414]={0x14AC,1},[3166415]={0x14AC,2},[3166416]={0x14AC,3},
  [3166417]={0x14AD,0},[3166418]={0x14AD,1},[3166419]={0x14AD,2},[3166420]={0x14AD,3},
  [3166421]={0x14AE,0},[3166422]={0x14AE,1},[3166423]={0x14AE,2},[3166424]={0x14AE,3},
  [3166425]={0x14AF,0},[3166426]={0x14AF,1},[3166427]={0x14AF,2},[3166428]={0x14AF,3},
  [3166429]={0x14B0,0},[3166430]={0x14B0,1},[3166431]={0x14B0,2},[3166432]={0x1475,0},
  [3166433]={0x1475,1},[3166434]={0x1475,2},[3166435]={0x1475,3},[3166436]={0x1481,0},
  [3166437]={0x1481,1},[3166438]={0x1481,2},[3166439]={0x1481,3},[3166440]={0x148D,0},
  [3166441]={0x148D,1},[3166442]={0x148D,2},[3166443]={0x148D,3},[3166444]={0x1499,0},
  [3166445]={0x1499,1},[3166446]={0x1499,2},[3166447]={0x1499,3},[3166448]={0x14A5,0},
  [3166449]={0x14A5,1},[3166450]={0x14A5,2},[3166451]={0x14A5,3},[3166452]={0x14B1,0},
  [3166453]={0x14B1,1},[3166454]={0x14B1,2},[3166455]={0x14B1,3},[3166456]={0x146F,4},
  [3166457]={0x1473,4},[3166458]={0x1479,4},[3166459]={0x147B,4},[3166460]={0x147E,4},
  [3166461]={0x147F,4},[3166462]={0x1486,4},[3166463]={0x148B,4},[3166464]={0x1492,4},
  [3166465]={0x1496,4},[3166466]={0x1497,4},[3166467]={0x149D,4},[3166468]={0x14A9,4},
  [3166469]={0x14AF,4},[3166470]={0x1476,4},[3166471]={0x1482,4},[3166472]={0x148E,4},
  [3166473]={0x149A,4},[3166474]={0x14A6,4},[3166475]={0x14B2,4},
}

-- ── Internal state ────────────────────────────────────────────────────────────
local reported         = {}     -- ap_id -> true once returned from poll()
local server_locations = nil    -- set of ap_ids the server expects (nil = all)
local rom_ok           = nil    -- cached "YOSHIAP" signature result
local mem              = {}
local log_fn           = nil

-- ── Logging ───────────────────────────────────────────────────────────────────
local function log(msg)
  if log_fn then pcall(log_fn, "[yoshisisland] " .. tostring(msg)) end
end

-- ── Memory API (resolved at init; 2-arg domain form + current-domain fallback) ─
local function resolve_memory_api()
  if not memory then return false end
  mem.read_u8  = memory.read_u8     or memory.readbyte
  mem.read_u16 = memory.read_u16_le or memory.readword
  return mem.read_u8 ~= nil
end

local function rd(fn, addr, domain)
  if not fn then return nil end
  local ok, v = pcall(fn, addr, domain)
  if ok and type(v) == "number" then return v end
  ok, v = pcall(fn, addr)                       -- older API: current domain
  if ok and type(v) == "number" then return v end
  return nil
end

local function read_wram_u8(off) return rd(mem.read_u8, off, WRAM) end

-- CARTROM reads with "ROM" / "System Bus" domain-name fallbacks (cores vary;
-- the raw-file-offset CARTROM/ROM form is what every SNES BizHawk core exposes).
local function read_cartrom_u8(off)
  local ok, v = pcall(mem.read_u8, off, CARTROM)
  if ok and type(v) == "number" then return v end
  ok, v = pcall(mem.read_u8, off, "ROM")
  if ok and type(v) == "number" then return v end
  return nil
end

local function bit_and(a, b)
  -- 8/16-bit safe AND without the bit library (cores vary).
  local res, bitval = 0, 1
  while a > 0 and b > 0 do
    if a % 2 == 1 and b % 2 == 1 then res = res + bitval end
    a = math.floor(a / 2); b = math.floor(b / 2); bitval = bitval * 2
  end
  return res
end

-- ── ROM identity: the SNES header AP id starts with "YOSHIAP" (validate_rom) ───
local function rom_is_ap()
  if rom_ok ~= nil then return rom_ok end
  local sig = "YOSHIAP"
  for i = 1, #sig do
    local b = read_cartrom_u8(ROMHASH_OFF + (i - 1))
    if b == nil then return false end                 -- not readable yet; retry
    if b ~= string.byte(sig, i) then
      rom_ok = false
      log("non-AP ROM (no 'YOSHIAP' signature) — detection idle, no reports")
      return false
    end
  end
  rom_ok = true
  log("Yoshi's Island AP ROM verified ('YOSHIAP' signature present)")
  return true
end

-- ── Multiworld context ────────────────────────────────────────────────────────
local function load_locations(ids)
  if type(ids) ~= "table" then return end
  server_locations = {}
  local n = 0
  for _, id in ipairs(ids) do
    local v = tonumber(id)
    if v then server_locations[v] = true; n = n + 1 end
  end
  log("server location set: " .. n .. " ids")
end

local function wanted(ap_id)
  if server_locations == nil then return true end   -- no set provided → report all
  return server_locations[ap_id] == true
end

-- ── One location's "checked?" test (mirrors Client.py game_watcher) ───────────
-- data = WRAM[addr]; masked = data & (1<<bit); bit_set = masked != 0;
-- checked iff bit_set != invert.
local function location_checked(ld)
  local data = read_wram_u8(ld[1])
  if data == nil then return false end
  local bit_set = bit_and(data, POW2[ld[2]]) ~= 0
  local invert  = (ld[3] == true) or (ld[3] ~= nil and ld[3] ~= 0 and ld[3] ~= false)
  return bit_set ~= invert
end

-- ── Detection gate ────────────────────────────────────────────────────────────
local function game_mode() return read_wram_u8(GAME_MODE_OFF) end

local function in_gameplay()
  local m = game_mode()
  return m ~= nil and VALID_GAME_STATES[m] == true
end

-- ── Module contract ───────────────────────────────────────────────────────────
function M.init(ctx)
  if ctx and type(ctx.log) == "function" then log_fn = ctx.log end
  if not resolve_memory_api() then
    log("BizHawk memory API unavailable — module idle")
    ADDRESSES_VERIFIED = false
    return
  end
  local cfg = (ctx and ctx.config) or {}
  load_locations(cfg.locations)
  local n = 0; for _ in pairs(LOC) do n = n + 1 end
  log("ready: " .. n .. " location flags (items_handling=0b111; receive_item is a "
      .. "documented no-op pending in-emulator verification)")
end

function M.poll()
  local new = {}
  if not ADDRESSES_VERIFIED then return new end
  if not rom_is_ap() then return new end
  if not in_gameplay() then return new end
  for ap_id, ld in pairs(LOC) do
    if not reported[ap_id] and wanted(ap_id) and location_checked(ld) then
      reported[ap_id] = true
      new[#new + 1] = ap_id
    end
  end
  return new
end

function M.is_goal_complete()
  if not ADDRESSES_VERIFIED or not rom_is_ap() then return false end
  local g = read_wram_u8(GOALFLAG_OFF)
  return g ~= nil and g ~= 0x00
end

-- Remote multiworld items: see the file header. items_handling = 0b111 means the
-- Yoshi's Island client owns ALL item delivery — there is no game-self-grant
-- fallback. The delivery path writes the next item's code into WRAM 0x1467 gated
-- on a u16 recv-progress counter (WRAM 0x1465) and on precise game/ITEM_RECEIVED
-- states. It is the one piece deferred until it can be confirmed in-emulator.
-- No-op (never a wrong write) until then; checks + goal above are fully
-- functional regardless.
function M.receive_item(item_id, meta)
  -- intentionally empty (documented)
end

return M
