using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
using Microsoft.Win32;
using LauncherV2.Core;

namespace LauncherV2.Plugins.TwilightPrincess;

// ═══════════════════════════════════════════════════════════════════════════════
// TwilightPrincessPlugin — install / patch / launch for
// "The Legend of Zelda: Twilight Princess" via the Archipelago multiworld.
//
// ── HONEST REALITY CHECK (2026-06-16, verified against AP sources) ──────────
//
//   * AP WORLD — game string "Twilight Princess" (verified: confirmed by
//     WritingHusky/Twilight_Princess_apworld sources and multiworld.gg tutorial
//     page at https://multiworld.gg/tutorial/Twilight%20Princess/setup_en).
//     GameId = "twilight_princess". This is a COMMUNITY apworld — NOT in AP main.
//     The .apworld file is installed by the user into their AP worlds/ folder.
//
//   * THREE COMPONENTS — verified from the setup guide at:
//     https://multiworld.gg/tutorial/Twilight%20Princess/setup_en
//     and https://github.com/WritingHusky/Twilight_Princess_apworld/blob/main/docs/setup_en.md
//
//     1. TP Randomizer (tprandomizer.com) — A randomizer tool for Twilight
//        Princess. Required to generate the patched game data from the user's
//        vanilla GCN/Wii ISO and the .aptp seed file. The user must download
//        this separately from https://tprandomizer.com/ (Windows application).
//        The .aptp file (generated by the AP server, named
//        "AP_XXXXX_P#_<slotname>.aptp") is loaded into the TP Randomizer
//        alongside the vanilla ISO to produce a patched game folder / GCI file
//        (RandomizerAP.US.gci) that Dolphin loads.
//
//     2. Dolphin emulator — standard GCN/Wii emulator. The user installs it
//        themselves (latest official release at dolphin-emu.org). The patched
//        game data (Wii save / GCI) is placed in Dolphin's save data, and the
//        ISO is launched via Dolphin command line:
//        Dolphin.exe -b -e "<iso>". The randomizer REL loader also lives in
//        Dolphin's save data alongside RandomizerAP.US.gci.
//
//     3. Twilight Princess Client — a PYTHON CLIENT BUNDLED IN THE AP APWORLD
//        (and expected to be shipped with the AP installation when the apworld
//        is installed). It is launched via ArchipelagoLauncher.exe as
//        "Twilight Princess Client". It hooks Dolphin memory to track location
//        checks and deliver items. Verified client name from setup guide:
//        "Twilight Princess Client".
//        ("ArchipelagoLauncher.exe" lives in C:\ProgramData\Archipelago —
//        READ-ONLY for our launcher — we detect it but never write there.)
//
//   * ISO — North American GameCube or Wii version:
//       GCN (GameCube):  disc ID "RZDE01" (Region: USA)
//       Wii:             disc ID "RZDE01" (same game ID for NA Wii version)
//     We validate by reading the first 4 bytes for "RZDE" (game code), which
//     covers both the GCN and Wii NA releases. File must be .iso or .gcm;
//     size 1–8 GB accepted (GCN ~1.4 GB, Wii dual-layer ~7.9 GB).
//
//   * ConnectsItself = true — the Twilight Princess Client (via AP Launcher)
//     owns the AP slot. The launcher must NOT hold an ApClient on the same
//     slot while the game runs (they would kick each other off the AP server).
//     The launcher provides credential prefill only.
//
//   * SupportsStandalone = false — this integration is AP-seed-only.
//
//   * PATCH FILE — the AP server generates a .aptp seed file. This plugin
//     lets the user register their .aptp file path in Settings so it is
//     readily accessible when they open the TP Randomizer.
//
// ── WHAT THIS PLUGIN DOES ────────────────────────────────────────────────────
//   1. SETTINGS — lets user configure:
//      - TP Randomizer exe path (downloaded from tprandomizer.com separately).
//      - Vanilla ISO path (GCN or Wii, North American; validated for "RZDE").
//      - .aptp file path (generated per-session by the AP server).
//      - Dolphin exe path (auto-detected from common paths).
//      All four paths stored in a sidecar JSON (Games/ROMs/twilight_princess/).
//   2. INSTALL — no binary to auto-download (TP Randomizer and Dolphin are
//      large self-updating apps the user installs separately). "Install" step
//      just verifies prerequisites and instructs the user.
//   3. LAUNCH (AP):
//      a. Warn if prerequisites are missing (randomizer, Dolphin, AP Launcher).
//      b. Launch ArchipelagoLauncher.exe with "Twilight Princess Client"
//         --connect <server> [--password <pw>]. Client hooks Dolphin.
//      c. Launch Dolphin with -b -e "<iso>".
//      Order: Client first (waits for Dolphin), then Dolphin.
//   4. News from WritingHusky/Twilight_Princess_apworld releases.
//
// ── UNVERIFIED / DEFENSIVE ───────────────────────────────────────────────────
//   * TP Randomizer CLI / silent-patch args: not verified. We open the GUI
//     and instruct the user to load their .aptp + ISO manually.
//   * Exact AP client name: "Twilight Princess Client" (from setup guide).
//     If the name differs in the installed apworld, the AP Launcher opens a
//     menu and the user picks the correct client there.
//   * "RZDE" as a disc ID prefix covers both GCN NA (RZDE01) and Wii NA
//     (RZDE01). Japanese GCN is RZDJ01, PAL GCN is RZDP01 — those are
//     rejected with a clear message.
// ═══════════════════════════════════════════════════════════════════════════════

public sealed class TwilightPrincessPlugin : IGamePlugin
{
    // ── Constants ────────────────────────────────────────────────────────────

    // Community apworld repo (WritingHusky/Twilight_Princess_apworld).
    private const string TpApworldOwner  = "WritingHusky";
    private const string TpApworldRepo   = "Twilight_Princess_apworld";
    private static readonly string TpApworldRepoUrl =
        $"https://github.com/{TpApworldOwner}/{TpApworldRepo}";
    private static readonly string TpApworldReleasesUrl =
        $"https://api.github.com/repos/{TpApworldOwner}/{TpApworldRepo}/releases";

    // Standard AP Launcher.
    private const string ApLauncherExeName = "ArchipelagoLauncher.exe";
    private const string ApProgramDataDir  = @"C:\ProgramData\Archipelago"; // READ-ONLY

    // The client name as listed in the AP Launcher for this apworld (verified
    // from setup guide: "Twilight Princess Client").
    private const string TpClientName = "Twilight Princess Client";

    // Reference URLs.
    private const string TpRandoUrl    = "https://tprandomizer.com/";
    private const string DolphinUrl    = "https://dolphin-emu.org/download/";
    private const string SetupGuideUrl =
        "https://multiworld.gg/tutorial/Twilight%20Princess/setup_en";
    private static readonly string ApworldPageUrl = TpApworldRepoUrl;

    // ISO validation: North American disc code prefix "RZDE" (bytes 0–3).
    // GCN NA: RZDE01 | Wii NA: RZDE01
    private static readonly byte[] TpDiscIdPrefix =
        new byte[] { 0x52, 0x5A, 0x44, 0x45 }; // "RZDE"

    // GCN ISOs ~1.35 GB; Wii ISOs ~7.9 GB. Accept 500 MB–8.5 GB.
    private const long MinIsoBytes = 500L  * 1024 * 1024;
    private const long MaxIsoBytes = 9000L * 1024 * 1024;

    private static readonly HttpClient _http = new()
    {
        Timeout = TimeSpan.FromMinutes(5),
        DefaultRequestHeaders = { { "User-Agent", "Archipelago-Launcher/2.0" } }
    };

    private const string VersionFileName = "tp_apworld_version.dat";

    // ── IGamePlugin — Identity ────────────────────────────────────────────────

    public string GameId      => "twilight_princess";
    public string DisplayName => "The Legend of Zelda: Twilight Princess";
    public string Subtitle    => "GameCube / Wii via Dolphin · Archipelago";

    /// EXACT AP game string (verified: "Twilight Princess").
    public string ApWorldName => "Twilight Princess";

    public string IconPath =>
        Path.Combine(AppContext.BaseDirectory, "Assets", "twilight_princess.png");

    public string ThemeAccentColor => "#3A1A6E"; // twilight purple

    public string[] GameBadges => new[]
    {
        "Requires GCN/Wii ISO (North American)",
        "Requires Dolphin",
        "Requires AP Launcher + TP apworld",
    };

    public string Description =>
        "The Legend of Zelda: Twilight Princess is the 2006 dark-themed GameCube/Wii " +
        "adventure following Link and the mysterious Midna across Hyrule. " +
        "This is the Archipelago integration: the Twilight Princess Randomizer patches " +
        "your vanilla North American ISO using a .aptp seed file (generated by your AP " +
        "multiworld room), Dolphin runs the result, and the Twilight Princess Client " +
        "hooks Dolphin memory to track location checks and deliver items. " +
        "You supply your own North American ISO; the launcher guides you through " +
        "connecting the TP Randomizer, Dolphin, and the Archipelago Launcher.";

    public string? VideoPreviewUrl => null;
    public string[] ScreenshotUrls => Array.Empty<string>();

    // ── Version state ─────────────────────────────────────────────────────────

    public string? InstalledVersion { get; private set; }
    public string? AvailableVersion { get; private set; }

    /// "Installed" = the user has set a valid TP Randomizer exe path.
    public bool IsInstalled => IsRandoConfigured();
    public bool IsRunning   { get; private set; }

    // ── Paths ─────────────────────────────────────────────────────────────────

    public string GameDirectory =>
        Path.Combine(AppContext.BaseDirectory, "Games", "ROMs", GameId);

    private string VersionFilePath =>
        Path.Combine(GameDirectory, VersionFileName);

    private string SettingsSidecarPath =>
        Path.Combine(GameDirectory, $"{GameId}_launcher.json");

    // ── Internal state ────────────────────────────────────────────────────────

    private Process? _tpClientProcess;
    private Process? _dolphinProcess;

    // ── AP bridge events ──────────────────────────────────────────────────────
    // The TP Client (via AP Launcher) owns the slot — the launcher relays nothing.
#pragma warning disable CS0067
    public event Action<long[]>? LocationsChecked;
    public event Action?         GoalCompleted;
    public event Action<int>?    GameExited;
#pragma warning restore CS0067

    // ── Lifecycle — CheckForUpdate ────────────────────────────────────────────

    public async Task CheckForUpdateAsync(CancellationToken ct = default)
    {
        // "InstalledVersion" tracks the apworld release the user has noted.
        try
        {
            InstalledVersion = File.Exists(VersionFilePath)
                ? (await File.ReadAllTextAsync(VersionFilePath, ct)).Trim()
                : (IsRandoConfigured() ? "configured" : null);
        }
        catch { InstalledVersion = null; }

        try
        {
            // CDN HEAD redirect — no REST API quota consumed.
            AvailableVersion = GitHubHelper.NormalizeTag(
                await GitHubHelper.FetchLatestTagAsync(TpApworldOwner, TpApworldRepo, ct));
        }
        catch { AvailableVersion = null; }
    }

    // ── Lifecycle — InstallOrUpdate ───────────────────────────────────────────

    public async Task InstallOrUpdateAsync(
        IProgress<(int Pct, string Msg)> progress,
        CancellationToken ct = default)
    {
        await Task.CompletedTask;

        // Nothing to auto-download. Guide the user through prerequisites.
        progress.Report((10, "Checking prerequisites..."));

        var s = LoadSettings();
        var missing = new List<string>();

        if (string.IsNullOrWhiteSpace(s.RandoExePath) || !File.Exists(s.RandoExePath))
            missing.Add("TP Randomizer (download from tprandomizer.com)");

        string? dolphin = ResolveDolphinExe(s);
        if (dolphin == null)
            missing.Add("Dolphin Emulator (download from dolphin-emu.org)");

        string? apLauncher = FindApLauncherExe();
        if (apLauncher == null)
            missing.Add("Archipelago Launcher (install from archipelago.gg)");

        if (!string.IsNullOrWhiteSpace(s.VanillaIsoPath) && File.Exists(s.VanillaIsoPath))
        {
            string? isoErr = ValidateIso(s.VanillaIsoPath);
            if (isoErr != null)
                missing.Add("Valid North American Twilight Princess ISO (see Settings)");
        }
        else
        {
            missing.Add("Twilight Princess ISO — North American GCN or Wii (see Settings)");
        }

        progress.Report((50, "Checking apworld releases..."));

        string? latestApworld = null;
        try
        {
            string json = await _http.GetStringAsync(TpApworldReleasesUrl, ct);
            using var doc = JsonDocument.Parse(json);
            if (doc.RootElement.ValueKind == JsonValueKind.Array)
            {
                var first = doc.RootElement.EnumerateArray().FirstOrDefault();
                if (first.ValueKind == JsonValueKind.Object &&
                    first.TryGetProperty("tag_name", out var t))
                    latestApworld = NormalizeTag(t.GetString());
            }
        }
        catch { /* network unavailable — skip */ }

        if (latestApworld != null)
            AvailableVersion = latestApworld;

        Directory.CreateDirectory(GameDirectory);

        if (missing.Count > 0)
        {
            string missingList = string.Join("\n  • ", missing);
            progress.Report((100,
                $"Setup incomplete. Missing:\n  • {missingList}\n\n" +
                "STEPS:\n" +
                "  1. Download and install the TP Randomizer from tprandomizer.com.\n" +
                "     Set its path in the Settings tab.\n" +
                "  2. Install Dolphin from dolphin-emu.org.\n" +
                "  3. Install Archipelago from archipelago.gg (provides the TP Client).\n" +
                "  4. Download the Twilight Princess apworld (.apworld file) from:\n" +
                "     " + TpApworldRepoUrl + "/releases\n" +
                "     Copy the .apworld file into your Archipelago worlds/ folder.\n" +
                "  5. Set your North American Twilight Princess ISO in the Settings tab.\n\n" +
                "For full setup instructions, see:\n" + SetupGuideUrl));
            return;
        }

        progress.Report((100,
            "All prerequisites found.\n\n" +
            "HOW TO PLAY:\n" +
            "  1. Generate your multiworld and download your .aptp seed file.\n" +
            "  2. Open the TP Randomizer (Settings tab > Open Randomizer).\n" +
            "     Load your vanilla ISO and the .aptp file, then generate the patched data.\n" +
            "  3. Place RandomizerAP.US.gci and the REL loader in Dolphin's GCN save folder.\n" +
            "  4. Click Play — the launcher starts the Twilight Princess Client (via the\n" +
            "     Archipelago Launcher) and then Dolphin with your vanilla ISO.\n\n" +
            "Refer to the full setup guide for patching details:\n" + SetupGuideUrl));
    }

    // ── Lifecycle — Verify ────────────────────────────────────────────────────

    public async Task<bool> VerifyInstallAsync(CancellationToken ct = default)
    {
        await Task.CompletedTask;
        var s = LoadSettings();
        return IsRandoConfigured(s)
            && ResolveDolphinExe(s) != null
            && FindApLauncherExe() != null
            && !string.IsNullOrWhiteSpace(s.VanillaIsoPath)
            && File.Exists(s.VanillaIsoPath)
            && ValidateIso(s.VanillaIsoPath) == null;
    }

    // ── ConnectsItself / SupportsStandalone ───────────────────────────────────

    /// The TP Client (via AP Launcher) owns the AP slot — the launcher must not
    /// hold a competing ApClient connection while the game is running.
    public bool ConnectsItself     => true;

    /// No standalone (non-AP) play through this integration.
    public bool SupportsStandalone => false;

    // ── Lifecycle — Launch ────────────────────────────────────────────────────

    public Task LaunchAsync(ApSession session, CancellationToken ct = default)
    {
        var s = LoadSettings();

        // Guard: ISO must be configured.
        if (string.IsNullOrWhiteSpace(s.VanillaIsoPath) || !File.Exists(s.VanillaIsoPath))
        {
            MessageBox.Show(
                "No Twilight Princess ISO configured. Please set your North American " +
                "GCN or Wii ISO path in the Settings tab first.",
                "ISO Not Configured",
                MessageBoxButton.OK,
                MessageBoxImage.Warning);
            return Task.CompletedTask;
        }

        // Start the TP Client via ArchipelagoLauncher.exe.
        StartTpClient(session);

        // Start Dolphin with the vanilla ISO.
        StartDolphin(s.VanillaIsoPath);

        return Task.CompletedTask;
    }

    public Task StopAsync()
    {
        try { _tpClientProcess?.Kill(entireProcessTree: true); } catch { }
        try { _dolphinProcess?.Kill(entireProcessTree: true); } catch { }
        IsRunning        = false;
        _tpClientProcess = null;
        _dolphinProcess  = null;
        return Task.CompletedTask;
    }

    // ── AP bridge — inert (ConnectsItself) ───────────────────────────────────

    public Task ReceiveItemsAsync(ApNetworkItem[] items, int index,
        CancellationToken ct = default)
        => Task.CompletedTask;

    public void OnApStateChanged(ApConnectionState state) { }

    // ── Settings UI ───────────────────────────────────────────────────────────

    public UIElement? CreateSettingsPanel()
    {
        var muted   = new SolidColorBrush(Color.FromRgb(0x72, 0x7A, 0x99));
        var fg      = new SolidColorBrush(Color.FromRgb(0xCC, 0xD0, 0xE0));
        var success = new SolidColorBrush(Color.FromRgb(0x4C, 0xAF, 0x50));
        var warn    = new SolidColorBrush(Color.FromRgb(0xE0, 0xA0, 0x30));

        var panel = new System.Windows.Controls.StackPanel
            { Margin = new Thickness(0, 0, 0, 20) };

        // ── Overview ──────────────────────────────────────────────────────
        panel.Children.Add(new System.Windows.Controls.TextBlock
        {
            Text =
                "Twilight Princess Archipelago uses three components:\n" +
                "  1. TP Randomizer (tprandomizer.com) — patches your vanilla ISO\n" +
                "     using the .aptp file from your AP multiworld session.\n" +
                "  2. Dolphin — GCN/Wii emulator that runs the patched game.\n" +
                "  3. Twilight Princess Client — part of the Archipelago Launcher;\n" +
                "     hooks Dolphin to track checks and deliver items.\n\n" +
                "The launcher launches the Client and Dolphin for you. You must\n" +
                "patch the game manually with the TP Randomizer before your first session.",
            FontSize = 11, Foreground = fg,
            TextWrapping = System.Windows.TextWrapping.Wrap,
            Margin = new Thickness(0, 0, 0, 14),
        });

        var s = LoadSettings();

        // ── Section: TP Randomizer ────────────────────────────────────────
        panel.Children.Add(SectionHeader("TP RANDOMIZER", muted));

        bool randoOk = IsRandoConfigured(s);
        panel.Children.Add(new System.Windows.Controls.TextBlock
        {
            Text = randoOk
                ? "Configured: " + s.RandoExePath
                : "Not configured. Download from tprandomizer.com, then select the exe below.",
            FontSize = 11,
            Foreground = randoOk ? success : warn,
            TextWrapping = System.Windows.TextWrapping.Wrap,
            Margin = new Thickness(0, 0, 0, 6),
        });

        // Open Randomizer button (shown when configured).
        if (randoOk)
        {
            var openBtn = new System.Windows.Controls.Button
            {
                Content             = "Open Randomizer",
                Width               = 160,
                Padding             = new Thickness(0, 6, 0, 6),
                HorizontalAlignment = System.Windows.HorizontalAlignment.Left,
                Margin              = new Thickness(0, 0, 0, 6),
                Background          = new SolidColorBrush(Color.FromRgb(0x1A, 0x1E, 0x30)),
                Foreground          = fg,
                BorderBrush         = new SolidColorBrush(Color.FromRgb(0x2A, 0x30, 0x50)),
            };
            string randoExeCapture = s.RandoExePath!;
            openBtn.Click += (_, _) =>
            {
                try
                {
                    Process.Start(new ProcessStartInfo
                    {
                        FileName         = randoExeCapture,
                        WorkingDirectory = Path.GetDirectoryName(randoExeCapture) ?? "",
                        UseShellExecute  = true,
                    });
                }
                catch (Exception ex)
                {
                    MessageBox.Show("Could not open the TP Randomizer:\n" + ex.Message,
                        "Launch Error", MessageBoxButton.OK, MessageBoxImage.Warning);
                }
            };
            panel.Children.Add(openBtn);
        }

        // Rando exe picker row.
        var randoRow = new System.Windows.Controls.DockPanel { Margin = new Thickness(0, 0, 0, 4) };
        var randoBox = new System.Windows.Controls.TextBox
        {
            Text        = s.RandoExePath ?? "",
            IsReadOnly  = true,
            FontSize    = 12,
            Margin      = new Thickness(0, 0, 8, 0),
            Background  = new SolidColorBrush(Color.FromRgb(0x0C, 0x10, 0x20)),
            Foreground  = fg,
            BorderBrush = new SolidColorBrush(Color.FromRgb(0x1E, 0x22, 0x33)),
            ToolTip     = "Path to the TP Randomizer executable.",
        };
        var randoBtn = new System.Windows.Controls.Button
        {
            Content     = "Select Randomizer...",
            Width       = 160,
            Padding     = new Thickness(0, 6, 0, 6),
            Background  = new SolidColorBrush(Color.FromRgb(0x1A, 0x1E, 0x30)),
            Foreground  = fg,
            BorderBrush = new SolidColorBrush(Color.FromRgb(0x2A, 0x30, 0x50)),
        };
        randoBtn.Click += (_, _) =>
        {
            var dlg = new Microsoft.Win32.OpenFileDialog
            {
                Title  = "Select TP Randomizer executable",
                Filter = "Executable (*.exe)|*.exe|All files (*.*)|*.*",
            };
            if (dlg.ShowDialog() != true) return;
            var cur = LoadSettings();
            cur.RandoExePath = dlg.FileName;
            SaveSettings(cur);
            randoBox.Text = dlg.FileName;
        };
        System.Windows.Controls.DockPanel.SetDock(randoBtn, System.Windows.Controls.Dock.Right);
        randoRow.Children.Add(randoBtn);
        randoRow.Children.Add(randoBox);
        panel.Children.Add(randoRow);

        panel.Children.Add(new System.Windows.Controls.TextBlock
        {
            Text =
                "To patch the game for your AP session:\n" +
                "  1. Download your .aptp seed file from the AP multiworld room.\n" +
                "  2. Open the TP Randomizer (above).\n" +
                "  3. Load your vanilla North American ISO and the .aptp file.\n" +
                "  4. Generate the patch. Place RandomizerAP.US.gci and the REL\n" +
                "     loader into Dolphin's GCN save data folder (see setup guide).",
            FontSize = 11, Foreground = muted,
            TextWrapping = System.Windows.TextWrapping.Wrap,
            Margin = new Thickness(0, 4, 0, 14),
        });

        // ── Section: Vanilla ISO ──────────────────────────────────────────
        panel.Children.Add(SectionHeader(
            "VANILLA ISO (North American GCN or Wii)", muted));

        string isoPath = s.VanillaIsoPath ?? "";
        bool isoOk = !string.IsNullOrWhiteSpace(isoPath)
                     && File.Exists(isoPath)
                     && ValidateIso(isoPath) == null;

        panel.Children.Add(new System.Windows.Controls.TextBlock
        {
            Text = isoOk
                ? "Validated: " + isoPath
                : string.IsNullOrWhiteSpace(isoPath)
                    ? "No ISO selected. Pick your North American Twilight Princess ISO below."
                    : "ISO not found or failed validation: " + isoPath,
            FontSize = 11,
            Foreground = isoOk ? success : warn,
            TextWrapping = System.Windows.TextWrapping.Wrap,
            Margin = new Thickness(0, 0, 0, 6),
        });

        var isoRow = new System.Windows.Controls.DockPanel { Margin = new Thickness(0, 0, 0, 4) };
        var isoBox = new System.Windows.Controls.TextBox
        {
            Text        = isoPath,
            IsReadOnly  = true,
            FontSize    = 12,
            Margin      = new Thickness(0, 0, 8, 0),
            Background  = new SolidColorBrush(Color.FromRgb(0x0C, 0x10, 0x20)),
            Foreground  = fg,
            BorderBrush = new SolidColorBrush(Color.FromRgb(0x1E, 0x22, 0x33)),
            ToolTip     = "North American Twilight Princess ISO (disc ID starts with \"RZDE\"). " +
                          "GCN (~1.4 GB) or Wii (~7.9 GB). Never modified — Dolphin reads it directly.",
        };
        var isoBtn = new System.Windows.Controls.Button
        {
            Content     = "Select ISO...",
            Width       = 120,
            Padding     = new Thickness(0, 6, 0, 6),
            Background  = new SolidColorBrush(Color.FromRgb(0x1A, 0x1E, 0x30)),
            Foreground  = fg,
            BorderBrush = new SolidColorBrush(Color.FromRgb(0x2A, 0x30, 0x50)),
        };
        isoBtn.Click += (_, _) =>
        {
            var dlg = new Microsoft.Win32.OpenFileDialog
            {
                Title  = "Select Twilight Princess ISO (North American GCN or Wii)",
                Filter = "ISO / GCM (*.iso;*.gcm)|*.iso;*.gcm|All files (*.*)|*.*",
            };
            if (dlg.ShowDialog() != true) return;

            string? bad = ValidateIso(dlg.FileName);
            if (bad != null)
            {
                MessageBox.Show(bad, "Invalid ISO",
                    MessageBoxButton.OK, MessageBoxImage.Warning);
                return;
            }

            var cur = LoadSettings();
            cur.VanillaIsoPath = dlg.FileName;
            SaveSettings(cur);
            isoBox.Text = dlg.FileName;
        };
        System.Windows.Controls.DockPanel.SetDock(isoBtn, System.Windows.Controls.Dock.Right);
        isoRow.Children.Add(isoBtn);
        isoRow.Children.Add(isoBox);
        panel.Children.Add(isoRow);

        panel.Children.Add(new System.Windows.Controls.TextBlock
        {
            Text = "Validation: first 4 bytes must be \"RZDE\" (North American game code). " +
                   "Both GCN and Wii NA releases share this code. " +
                   "Japanese is RZDJ01; PAL is RZDP01 — those are not supported.",
            FontSize = 11, Foreground = muted,
            TextWrapping = System.Windows.TextWrapping.Wrap,
            Margin = new Thickness(0, 4, 0, 14),
        });

        // ── Section: Dolphin ──────────────────────────────────────────────
        panel.Children.Add(SectionHeader("DOLPHIN EMULATOR", muted));

        string? detectedDolphin = s.DolphinExePath;
        if (string.IsNullOrWhiteSpace(detectedDolphin) || !File.Exists(detectedDolphin))
            detectedDolphin = DetectDolphinExe();

        bool dolphinOk = !string.IsNullOrWhiteSpace(detectedDolphin)
                         && File.Exists(detectedDolphin);
        panel.Children.Add(new System.Windows.Controls.TextBlock
        {
            Text = dolphinOk
                ? "Found: " + detectedDolphin
                : "Dolphin not found. Download from dolphin-emu.org and set path below.",
            FontSize = 11,
            Foreground = dolphinOk ? success : warn,
            TextWrapping = System.Windows.TextWrapping.Wrap,
            Margin = new Thickness(0, 0, 0, 6),
        });

        var dolphinRow = new System.Windows.Controls.DockPanel { Margin = new Thickness(0, 0, 0, 4) };
        var dolphinBox = new System.Windows.Controls.TextBox
        {
            Text        = detectedDolphin ?? "",
            IsReadOnly  = true,
            FontSize    = 12,
            Margin      = new Thickness(0, 0, 8, 0),
            Background  = new SolidColorBrush(Color.FromRgb(0x0C, 0x10, 0x20)),
            Foreground  = fg,
            BorderBrush = new SolidColorBrush(Color.FromRgb(0x1E, 0x22, 0x33)),
        };
        var dolphinBtn = new System.Windows.Controls.Button
        {
            Content     = "Select Dolphin...",
            Width       = 130,
            Padding     = new Thickness(0, 6, 0, 6),
            Background  = new SolidColorBrush(Color.FromRgb(0x1A, 0x1E, 0x30)),
            Foreground  = fg,
            BorderBrush = new SolidColorBrush(Color.FromRgb(0x2A, 0x30, 0x50)),
        };
        dolphinBtn.Click += (_, _) =>
        {
            var dlg = new Microsoft.Win32.OpenFileDialog
            {
                Title  = "Select Dolphin.exe",
                Filter = "Dolphin (*.exe)|*.exe|All files (*.*)|*.*",
            };
            if (dlg.ShowDialog() != true) return;
            if (!dlg.FileName.EndsWith(".exe", StringComparison.OrdinalIgnoreCase))
            {
                MessageBox.Show("That does not look like a Dolphin executable.",
                    "Invalid Exe", MessageBoxButton.OK, MessageBoxImage.Warning);
                return;
            }
            var cur = LoadSettings();
            cur.DolphinExePath = dlg.FileName;
            SaveSettings(cur);
            dolphinBox.Text = dlg.FileName;
        };
        System.Windows.Controls.DockPanel.SetDock(dolphinBtn, System.Windows.Controls.Dock.Right);
        dolphinRow.Children.Add(dolphinBtn);
        dolphinRow.Children.Add(dolphinBox);
        panel.Children.Add(dolphinRow);

        panel.Children.Add(new System.Windows.Controls.TextBlock
        {
            Text = "Common Dolphin paths:\n" +
                   "  • %LOCALAPPDATA%\\Dolphin\\Dolphin.exe\n" +
                   "  • %ProgramFiles%\\Dolphin\\Dolphin.exe\n" +
                   "  • %ProgramFiles(x86)%\\Dolphin\\Dolphin.exe\n" +
                   "Dolphin is launched with: Dolphin.exe -b -e \"<ISO>\"",
            FontSize = 11, Foreground = muted,
            TextWrapping = System.Windows.TextWrapping.Wrap,
            Margin = new Thickness(0, 4, 0, 14),
        });

        // ── Section: AP Launcher ──────────────────────────────────────────
        panel.Children.Add(SectionHeader(
            "ARCHIPELAGO LAUNCHER (TWILIGHT PRINCESS CLIENT)", muted));

        string? apLauncher = FindApLauncherExe();
        panel.Children.Add(new System.Windows.Controls.TextBlock
        {
            Text = apLauncher != null
                ? "Found: " + apLauncher
                : "Archipelago Launcher not found in " + ApProgramDataDir + ".\n" +
                  "Install Archipelago from archipelago.gg and copy the Twilight Princess\n" +
                  "apworld (.apworld file) from " + TpApworldRepoUrl + "/releases\n" +
                  "into your Archipelago worlds/ folder.",
            FontSize = 11,
            Foreground = apLauncher != null ? success : warn,
            TextWrapping = System.Windows.TextWrapping.Wrap,
            Margin = new Thickness(0, 0, 0, 14),
        });

        // ── Section: Links ────────────────────────────────────────────────
        panel.Children.Add(SectionHeader("LINKS", muted));
        foreach (var (label, url) in new[]
        {
            ("TP AP Setup Guide ↗",        SetupGuideUrl),
            ("TP Randomizer ↗",            TpRandoUrl),
            ("TP apworld (GitHub) ↗",      ApworldPageUrl),
            ("Dolphin Emulator ↗",         DolphinUrl),
            ("Archipelago Official ↗",     "https://archipelago.gg"),
        })
        {
            var btn = new System.Windows.Controls.Button
            {
                Content             = label,
                HorizontalAlignment = System.Windows.HorizontalAlignment.Left,
                Padding             = new Thickness(0, 2, 0, 2),
                Background          = Brushes.Transparent,
                BorderThickness     = new Thickness(0),
                FontSize            = 12,
                Margin              = new Thickness(0, 0, 0, 4),
                Foreground          = new SolidColorBrush(Color.FromRgb(0x60, 0x9A, 0xFF)),
                Cursor              = System.Windows.Input.Cursors.Hand,
            };
            string u = url;
            btn.Click += (_, _) =>
            {
                try { Process.Start(new ProcessStartInfo(u) { UseShellExecute = true }); }
                catch { }
            };
            panel.Children.Add(btn);
        }

        return panel;
    }

    private static System.Windows.Controls.TextBlock SectionHeader(
        string text, System.Windows.Media.Brush brush)
        => new System.Windows.Controls.TextBlock
        {
            Text       = text,
            FontSize   = 10,
            FontWeight = FontWeights.SemiBold,
            Foreground = brush,
            Margin     = new Thickness(0, 8, 0, 8),
        };

    // ── News — WritingHusky/Twilight_Princess_apworld releases ────────────────

    public async Task<NewsItem[]> GetNewsAsync(CancellationToken ct = default)
    {
        try
        {
            string json = await _http.GetStringAsync(TpApworldReleasesUrl, ct);
            using var doc = JsonDocument.Parse(json);
            if (doc.RootElement.ValueKind != JsonValueKind.Array)
                return Array.Empty<NewsItem>();

            var items = new List<NewsItem>();
            foreach (var el in doc.RootElement.EnumerateArray())
            {
                string? tag = el.TryGetProperty("tag_name", out var t)
                    ? t.GetString() : null;
                if (tag == null) continue;

                DateTimeOffset date = DateTimeOffset.MinValue;
                if (el.TryGetProperty("published_at", out var d) &&
                    d.ValueKind == JsonValueKind.String)
                    DateTimeOffset.TryParse(d.GetString(), out date);

                items.Add(new NewsItem(
                    Title:   el.TryGetProperty("name",     out var n) ? n.GetString() ?? "" : "",
                    Body:    el.TryGetProperty("body",     out var b) ? b.GetString() ?? "" : "",
                    Version: NormalizeTag(tag) ?? "",
                    Date:    date,
                    Url:     el.TryGetProperty("html_url", out var u) ? u.GetString() : null
                ));
                if (items.Count >= 10) break;
            }
            return items.ToArray();
        }
        catch { return Array.Empty<NewsItem>(); }
    }

    // ── Private helpers — launch ──────────────────────────────────────────────

    /// Start the Twilight Princess Client via ArchipelagoLauncher.exe.
    private void StartTpClient(ApSession session)
    {
        string? launcherExe = FindApLauncherExe();
        if (launcherExe == null)
        {
            MessageBox.Show(
                "Archipelago Launcher not found in " + ApProgramDataDir + ".\n\n" +
                "Please install Archipelago from https://archipelago.gg and install\n" +
                "the Twilight Princess apworld into your worlds/ folder.\n\n" +
                "Dolphin will still be launched, but location checks will not be tracked.",
                "AP Launcher Not Found",
                MessageBoxButton.OK,
                MessageBoxImage.Warning);
            return;
        }

        // Args: "Twilight Princess Client" [--connect <server>] [--password <pw>]
        var args = new List<string> { $"\"{TpClientName}\"" };
        if (!string.IsNullOrWhiteSpace(session.ServerUri))
            args.Add($"--connect \"{session.ServerUri}\"");
        if (!string.IsNullOrWhiteSpace(session.Password))
            args.Add($"--password \"{session.Password}\"");

        try
        {
            var proc = Process.Start(new ProcessStartInfo
            {
                FileName         = launcherExe,
                Arguments        = string.Join(" ", args),
                WorkingDirectory = Path.GetDirectoryName(launcherExe) ?? ApProgramDataDir,
                UseShellExecute  = false,
            });
            if (proc != null)
            {
                _tpClientProcess = proc;
                IsRunning = true;
                try
                {
                    proc.EnableRaisingEvents = true;
                    proc.Exited += (_, _) =>
                    {
                        IsRunning = false;
                        GameExited?.Invoke(proc.ExitCode);
                    };
                }
                catch { /* non-fatal */ }
            }
        }
        catch (Exception ex)
        {
            MessageBox.Show(
                "Could not start the Archipelago Launcher:\n" + ex.Message +
                "\n\nDolphin will still be launched. Start the Twilight Princess Client " +
                "manually from the Archipelago Launcher if needed.",
                "Client Launch Error",
                MessageBoxButton.OK,
                MessageBoxImage.Warning);
        }
    }

    /// Start Dolphin with the vanilla ISO: Dolphin.exe -b -e "<isoPath>".
    private void StartDolphin(string isoPath)
    {
        var s = LoadSettings();
        string? dolphinExe = ResolveDolphinExe(s);
        if (dolphinExe == null)
        {
            MessageBox.Show(
                "Dolphin.exe not found. Please install Dolphin from:\n" + DolphinUrl +
                "\n\nThen set the Dolphin path in Settings.",
                "Dolphin Not Found",
                MessageBoxButton.OK,
                MessageBoxImage.Warning);
            return;
        }

        try
        {
            var proc = Process.Start(new ProcessStartInfo
            {
                FileName         = dolphinExe,
                Arguments        = $"-b -e \"{isoPath}\"",
                WorkingDirectory = Path.GetDirectoryName(dolphinExe) ?? "",
                UseShellExecute  = false,
            });
            if (proc != null)
            {
                _dolphinProcess = proc;
                IsRunning = true;
                try
                {
                    proc.EnableRaisingEvents = true;
                    proc.Exited += (_, _) =>
                    {
                        IsRunning = false;
                        GameExited?.Invoke(proc.ExitCode);
                    };
                }
                catch { /* non-fatal */ }
            }
        }
        catch (Exception ex)
        {
            MessageBox.Show(
                "Could not start Dolphin:\n" + ex.Message,
                "Dolphin Launch Error",
                MessageBoxButton.OK,
                MessageBoxImage.Warning);
        }
    }

    // ── Private helpers — Dolphin detection ──────────────────────────────────

    private static string? ResolveDolphinExe(TpSettings? s = null)
    {
        if (s != null
            && !string.IsNullOrWhiteSpace(s.DolphinExePath)
            && File.Exists(s.DolphinExePath))
            return s.DolphinExePath;
        return DetectDolphinExe();
    }

    private static string? DetectDolphinExe()
    {
        string[] exeNames = { "Dolphin.exe", "DolphinQt2.exe" };
        string local   = Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData);
        string prog    = Environment.GetFolderPath(Environment.SpecialFolder.ProgramFiles);
        string progX86 = Environment.GetFolderPath(Environment.SpecialFolder.ProgramFilesX86);

        string[] roots =
        {
            Path.Combine(local,   "Dolphin"),
            Path.Combine(local,   "Programs", "Dolphin"),
            Path.Combine(prog,    "Dolphin"),
            Path.Combine(prog,    "Dolphin Emulator"),
            Path.Combine(progX86, "Dolphin"),
            Path.Combine(progX86, "Dolphin Emulator"),
        };

        foreach (string root in roots)
        {
            if (!Directory.Exists(root)) continue;
            foreach (string name in exeNames)
            {
                string candidate = Path.Combine(root, name);
                if (File.Exists(candidate)) return candidate;
            }
            try
            {
                foreach (string sub in Directory.EnumerateDirectories(root))
                {
                    foreach (string name in exeNames)
                    {
                        string candidate = Path.Combine(sub, name);
                        if (File.Exists(candidate)) return candidate;
                    }
                }
            }
            catch { }
        }
        return null;
    }

    // ── Private helpers — AP Launcher detection ───────────────────────────────

    private static string? FindApLauncherExe()
    {
        string candidate = Path.Combine(ApProgramDataDir, ApLauncherExeName);
        return File.Exists(candidate) ? candidate : null;
    }

    // ── Private helpers — ISO validation ─────────────────────────────────────

    /// Returns null if the ISO is acceptable; otherwise a human-readable reason.
    private static string? ValidateIso(string path)
    {
        if (string.IsNullOrWhiteSpace(path))
            return "No file selected.";

        string ext = Path.GetExtension(path).ToLowerInvariant();
        if (ext != ".iso" && ext != ".gcm")
            return "The file must be a GameCube/Wii ISO (.iso or .gcm).";

        FileInfo fi;
        try { fi = new FileInfo(path); }
        catch { return "Could not access the file. Is it on a network drive or locked?"; }

        if (!fi.Exists)
            return "File does not exist: " + path;

        if (fi.Length < MinIsoBytes || fi.Length > MaxIsoBytes)
            return $"Unexpected file size ({fi.Length / (1024 * 1024)} MB). " +
                   "A Twilight Princess GCN ISO is ~1,400 MB; a Wii ISO is ~7,900 MB.";

        try
        {
            byte[] header = new byte[TpDiscIdPrefix.Length];
            using var f = File.OpenRead(path);
            int read = f.Read(header, 0, header.Length);
            if (read < TpDiscIdPrefix.Length)
                return "Could not read the disc header. The file may be corrupt.";

            for (int i = 0; i < TpDiscIdPrefix.Length; i++)
            {
                if (header[i] != TpDiscIdPrefix[i])
                {
                    string found = Encoding.ASCII.GetString(header);
                    return $"This does not appear to be a North American Twilight Princess " +
                           $"disc (found game code \"{found}\" — expected \"RZDE\"). " +
                           "Japanese is RZDJ01, PAL is RZDP01; only the North American " +
                           "release (RZDE01) is supported by the TP Randomizer.";
                }
            }
        }
        catch (Exception ex)
        {
            return "Could not read the ISO header: " + ex.Message;
        }

        return null; // valid
    }

    // ── Private helpers — settings sidecar ───────────────────────────────────

    private bool IsRandoConfigured(TpSettings? s = null)
    {
        s ??= LoadSettings();
        return !string.IsNullOrWhiteSpace(s.RandoExePath) && File.Exists(s.RandoExePath);
    }

    private static string? NormalizeTag(string? tag)
    {
        if (string.IsNullOrWhiteSpace(tag)) return null;
        tag = tag.Trim();
        return tag.StartsWith('v') && tag.Length > 1 && char.IsDigit(tag[1])
            ? tag[1..] : tag;
    }

    private sealed class TpSettings
    {
        public string? RandoExePath   { get; set; }
        public string? VanillaIsoPath { get; set; }
        public string? DolphinExePath { get; set; }
    }

    private TpSettings LoadSettings()
    {
        try
        {
            if (File.Exists(SettingsSidecarPath))
            {
                string txt = File.ReadAllText(SettingsSidecarPath);
                if (!string.IsNullOrWhiteSpace(txt))
                    return JsonSerializer.Deserialize<TpSettings>(txt) ?? new();
            }
        }
        catch { }
        return new();
    }

    private void SaveSettings(TpSettings s)
    {
        try
        {
            Directory.CreateDirectory(GameDirectory);
            File.WriteAllText(
                SettingsSidecarPath,
                JsonSerializer.Serialize(s, new JsonSerializerOptions { WriteIndented = true }),
                new UTF8Encoding(false));
        }
        catch { /* non-fatal */ }
    }
}
