using System;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace LauncherV2.Core.Archipelago;

// ApWorldProvisioner — what has to happen after an install for the game to be
// USABLE, rather than merely present.
//
// Installing a plugin put its .apworld inside London's own tree and stopped
// there. Two things were missing, and both are invisible until someone tries
// to do something:
//
//   1. Archipelago only loads worlds from its own custom_worlds folder. A
//      world that is not there cannot be generated with, no matter how
//      installed the plugin says it is.
//   2. The option list every "Create YAML" form draws comes from a TEMPLATE,
//      and templates are generated by Archipelago from the worlds it can load
//      -- they are not shipped inside an apworld. So a freshly installed game
//      had no options to show even once its world was in place.
//
// Both are done here, in that order, because the second reads what the first
// writes.
//
// SCOPE: this only ever touches the engine the player nominated for London to
// generate with, and only ever adds worlds and regenerates derived templates.
// The separate Settings → AP World folder still exists for mirroring into a
// DIFFERENT Archipelago install, which is a different intent.
public static class ApWorldProvisioner
{
    /// Archipelago's own launcher runs this component headlessly: it loads
    /// every world it can find and writes one template per game.
    public const string TemplateComponent = "Generate Template Options";

    public sealed record Result(int WorldsCopied, bool TemplatesRebuilt, string? Note);

    // Regenerating templates loads every installed world, so it is slow and
    // pointless to do twice at once. One at a time, and never on top of itself.
    private static readonly SemaphoreSlim _gate = new(1, 1);

    /// Put a game's world where Archipelago looks, then rebuild the option
    /// templates so its options can be shown. Never throws: a game that is
    /// installed and playable must not be reported as failed because a
    /// derived file could not be refreshed.
    public static async Task<Result> ProvisionAsync(
        IGamePlugin plugin, ApEngine.Report? engine, CancellationToken ct = default)
    {
        if (engine is not { Usable: true })
            return new Result(0, false, null);   // nothing to provision into

        int copied;
        try
        {
            var sync = ApworldSync.Sync(plugin, engine.CustomWorldsDir);
            if (sync.Error != null)
                return new Result(0, false, sync.Error);
            copied = sync.Copied;
        }
        catch (Exception ex)
        {
            return new Result(0, false, ex.Message);
        }

        // Nothing new arrived -- the templates already describe what is there.
        if (copied == 0) return new Result(0, false, null);

        bool rebuilt = await RebuildTemplatesAsync(engine, ct).ConfigureAwait(false);
        return new Result(copied, rebuilt,
            rebuilt ? null : "the option templates could not be refreshed");
    }

    /// Ask Archipelago to rewrite every option template. Returns false when
    /// the engine could not be asked or did not finish.
    public static async Task<bool> RebuildTemplatesAsync(
        ApEngine.Report? engine, CancellationToken ct = default)
    {
        if (engine is not { Usable: true, HasLauncher: true }) return false;

        string exe = Path.Combine(engine.Root, ApEngine.LauncherExeName);
        if (!File.Exists(exe)) return false;

        if (!await _gate.WaitAsync(TimeSpan.FromMinutes(3), ct).ConfigureAwait(false))
            return false;
        try
        {
            var psi = new ProcessStartInfo(exe)
            {
                WorkingDirectory = engine.Root,
                UseShellExecute  = false,
                CreateNoWindow   = true,
                RedirectStandardOutput = true,
                RedirectStandardError  = true,
            };
            // Passed as one argument: the component name contains spaces, and
            // splitting it would ask Archipelago to run a component called
            // "Generate", which does not exist.
            psi.ArgumentList.Add(TemplateComponent);

            using var proc = Process.Start(psi);
            if (proc == null) return false;

            // Drained, not ignored: a full pipe buffer deadlocks the child,
            // and this child prints a line for every broken world it meets.
            var outTask = proc.StandardOutput.ReadToEndAsync(ct);
            var errTask = proc.StandardError.ReadToEndAsync(ct);

            using var timeout = CancellationTokenSource.CreateLinkedTokenSource(ct);
            timeout.CancelAfter(TimeSpan.FromMinutes(5));
            try
            {
                await proc.WaitForExitAsync(timeout.Token).ConfigureAwait(false);
            }
            catch (OperationCanceledException)
            {
                try { proc.Kill(entireProcessTree: true); } catch (Exception) { }
                return false;
            }
            await Task.WhenAll(outTask, errTask).ConfigureAwait(false);

            // Archipelago's component finishes by OPENING the templates folder
            // in Explorer — helpful when a person ran it by hand, and pure
            // noise when London ran it in the background. Several players have
            // reported the mystery window. We cannot change Archipelago, but
            // we can close the exact window our own call just caused: only
            // Explorer, only that folder, only right now.
            CloseExplorerAt(engine.TemplatesDir);

            return proc.ExitCode == 0;
        }
        catch (Exception)
        {
            return false;
        }
        finally
        {
            _gate.Release();
        }
    }

    /// Close Explorer windows showing exactly this folder. Scoped on
    /// purpose: matching by path means a window the player opened on some
    /// OTHER folder can never be touched, and matching right after our own
    /// generator ran means the one we close is the one we caused.
    private static void CloseExplorerAt(string folder)
    {
        try
        {
            string want = Path.GetFullPath(folder)
                              .TrimEnd(Path.DirectorySeparatorChar);
            Type? shellType = Type.GetTypeFromProgID("Shell.Application");
            if (shellType == null) return;

            // The window can appear a moment after the process exits, so look
            // a few times before concluding there is nothing to clean up.
            for (int attempt = 0; attempt < 6; attempt++)
            {
                dynamic shell = Activator.CreateInstance(shellType)!;
                bool closed = false;
                foreach (dynamic w in shell.Windows())
                {
                    string? url;
                    try { url = w.LocationURL as string; } catch { continue; }
                    if (string.IsNullOrEmpty(url)) continue;
                    if (!url.StartsWith("file:///", StringComparison.OrdinalIgnoreCase)) continue;
                    string path = Uri.UnescapeDataString(url.Substring(8))
                                     .Replace('/', Path.DirectorySeparatorChar)
                                     .TrimEnd(Path.DirectorySeparatorChar);
                    if (string.Equals(path, want, StringComparison.OrdinalIgnoreCase))
                    {
                        try { w.Quit(); closed = true; } catch { }
                    }
                }
                if (closed) return;
                System.Threading.Thread.Sleep(500);
            }
        }
        catch (Exception) { /* a window we cannot close is only cosmetic */ }
    }

    /// True when this game already has an option template to draw a form from.
    public static bool HasTemplate(ApEngine.Report? engine, string apWorldName)
        => engine is { Usable: true }
           && apWorldName.Length > 0
           && File.Exists(Path.Combine(engine.TemplatesDir, apWorldName + ".yaml"));

    // ───────────────────────────── full refresh ────────────────────────────

    public sealed record Refresh(bool Ok, int Removed, int Written, string? Note);

    ///
    /// Throw every generated template away and let Archipelago write them all
    /// again.
    ///
    /// Rebuilding alone only OVERWRITES: a template for a world that was
    /// renamed, removed, or that now fails to load simply stays behind, and
    /// the Create YAML form keeps drawing yesterday's options from it. That is
    /// how a game ends up showing six shuffles when the world has four.
    ///
    /// ⚠ Only the .yaml files sitting directly in Templates. The folder also
    /// holds `Presets\`, 169 curated starting points that Archipelago ships
    /// and NOTHING regenerates — deleting those would destroy work no button
    /// can bring back. So: no recursion, no other extensions.
    ///
    public static async Task<Refresh> RefreshTemplatesAsync(
        ApEngine.Report? engine, CancellationToken ct = default)
    {
        if (engine is not { Usable: true, HasLauncher: true })
            return new Refresh(false, 0, 0, "no Archipelago engine is set up yet");

        string dir = engine.TemplatesDir;
        int removed = 0;
        try
        {
            if (Directory.Exists(dir))
                foreach (string f in Directory.EnumerateFiles(dir, "*.yaml",
                                                              SearchOption.TopDirectoryOnly))
                {
                    try { File.Delete(f); removed++; }
                    catch (IOException) { /* open in an editor: leave it, it gets overwritten */ }
                    catch (UnauthorizedAccessException) { }
                }
        }
        catch (Exception) { /* an unreadable folder is one the rebuild will fill */ }

        bool ok = await RebuildTemplatesAsync(engine, ct).ConfigureAwait(false);
        int written = 0;
        try
        {
            if (Directory.Exists(dir))
                written = Directory.GetFiles(dir, "*.yaml", SearchOption.TopDirectoryOnly).Length;
        }
        catch (Exception) { }

        // Wiping and then failing to rebuild would leave every game without a
        // form. Say so plainly rather than reporting a clean number.
        if (!ok && written == 0)
            return new Refresh(false, removed, 0,
                "Archipelago did not finish writing the templates — nothing to draw forms from");
        return new Refresh(ok, removed, written, null);
    }

    ///
    /// What the templates were built from, as one short string.
    ///
    /// Templates are DERIVED: from the launcher that asked for them and from
    /// the worlds installed at that moment. When either moves, they are stale
    /// — which is invisible, because a stale template still draws a form.
    /// Comparing this against the stamp from last time is how the staleness
    /// becomes something the launcher can notice on its own.
    ///
    public static string Fingerprint(ApEngine.Report? engine, string launcherVersion)
    {
        var sb = new System.Text.StringBuilder(launcherVersion);
        try
        {
            // The engine's own version is part of what the templates were
            // built from: a new Archipelago ships new bundled worlds and new
            // options for old ones, with not one file in custom_worlds
            // changing. Without this line an engine update left every form
            // drawing the previous release's options.
            if (engine?.Version != null)
                sb.Append("|engine:").Append(engine.Version);

            if (engine is { Usable: true } && Directory.Exists(engine.CustomWorldsDir))
                foreach (string f in Directory.GetFiles(engine.CustomWorldsDir, "*.apworld")
                                              .OrderBy(x => x, StringComparer.OrdinalIgnoreCase))
                {
                    var fi = new FileInfo(f);
                    sb.Append('|').Append(fi.Name).Append(':').Append(fi.Length)
                      .Append(':').Append(fi.LastWriteTimeUtc.Ticks);
                }
        }
        catch (Exception) { /* a fingerprint we cannot take is one that differs */ }
        return sb.ToString();
    }
}
