using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
using Microsoft.Win32;
using LauncherV2.Core;

namespace LauncherV2.Plugins.WindWaker;

// ═══════════════════════════════════════════════════════════════════════════════
// WindWakerPlugin — install / patch / launch for "The Wind Waker" — the
// Nintendo GameCube game played through the Archipelago multiworld.
//
// ── HONEST REALITY CHECK (2026-06-14, verified against AP main repo + tanjo3) ─
//
//   * AP WORLD — game string "The Wind Waker" (verified: worlds/tww/__init__.py,
//     game = "The Wind Waker"). GameId = "tww". AP-main (ArchipelagoMW) in-tree.
//     No separate apworld to distribute — it ships with AP itself.
//
//   * THREE COMPONENTS — verified by examining worlds/tww/TWWClient.py +
//     tanjo3/wwrando + the official setup guide (archipelago.gg/tutorial/
//     The%20Wind%20Waker/setup/en):
//
//     1. wwrando (tanjo3/wwrando, "archipelago" branch / "ap_2.x" releases)
//        A fork of the Wind Waker Randomizer with AP support. This is a SEPARATE
//        Windows application (Qt-based GUI; ships as wwrando_ap-<ver>-windows.zip
//        containing a wwrando_ap.exe or similar). It takes the user's vanilla GCN
//        ISO and an `.aptww` patch file (generated by the AP server) and produces
//        a PATCHED ISO that the emulator runs. The ".aptww" is passed as
//        "plando_file" in the GUI — there are no verified batch-mode / silent-
//        patch CLI args, so this plugin opens wwrando's GUI and instructs the
//        user to load their .aptww + ISO and click Randomize. Latest AP-flavour
//        release: tag "ap_2.5.1" (2026-04-05), Windows asset
//        "wwrando_ap-2.5.1-windows.zip" (verified). Pinned fallback used when the
//        GitHub API is unreachable.
//
//     2. Dolphin emulator — standard GameCube emulator. The user installs it
//        themselves (latest official release at dolphin-emu.org). This plugin
//        detects common installation paths for the launcher's Dolphin path hint
//        but does NOT download or manage Dolphin (it is a large, well-known, self-
//        updating application). The patched ISO is launched via Dolphin's command
//        line: Dolphin.exe -b -e "<patchedIso>". For Dolphin 5.x+ the flag is
//        "-b -e <iso>"; for builds that renamed the exe to "DolphinQt2.exe" both
//        names are tried.
//
//     3. TWW Client — this is a PYTHON CLIENT BUNDLED IN ARCHIPELAGO ITSELF
//        (worlds/tww/TWWClient.py, launched via ArchipelagoLauncher.exe as "The
//        Wind Waker Client"). It uses dolphin_memory_engine to hook Dolphin,
//        reads the slot name from GC RAM (SLOT_NAME_ADDR = 0x803FE8A0) and auto-
//        authenticates, then sends location checks and delivers items. Verified
//        CLI (from TWWClient.py main()): the standard AP get_base_parser()
//        arguments:
//            ArchipelagoLauncher.exe "The Wind Waker Client"
//                --connect <server:port>
//                --password <pw>
//        (server/password optional — the client's GUI accepts them too).
//        "ArchipelagoLauncher.exe" lives in C:\ProgramData\Archipelago (READ-ONLY
//        for our launcher — we detect it but never write there). No standalone
//        TWW Client exe exists; the client is part of the AP installation.
//
//   * ISO VALIDATION — The Wind Waker North American GameCube ISO:
//       Game ID bytes 0x000000: "GZLE99" (6 bytes, ASCII) — this exact check is
//       VERIFIED from TWWClient.py line:
//           dolphin_memory_engine.read_bytes(0x80000000, 6) != b"GZLE99"
//       The disc header at offset 0 in a GCN ISO is the 4-byte game ID plus
//       region/maker, making "GZLE99" the canonical identification. We validate
//       by reading the first 6 bytes of the ISO file. (RAM base 0x80000000 maps
//       to the disc header in Dolphin memory — we read from the ISO file itself,
//       not from RAM, so we read ISO bytes 0–5 directly.) A valid GCN ISO is at
//       least 512 MB; we accept 400 MB–4 GB to accommodate compressed images.
//
//   * GCN ISO FORMAT — GameCube ISOs (also called .gcm) are raw disc images.
//       Extension: .iso or .gcm. The disc header starts at byte 0 in the image.
//       Standard TWW (NA) disc ID: "GZLE" + maker "99" = "GZLE99".
//
//   * ConnectsItself = true — the TWW Client (via AP Launcher) owns the AP slot.
//     SupportsStandalone = false — the game requires the wwrando patch + Dolphin,
//     and there is no meaningful "play without AP" flow in this integration.
//
//   * PATCHED ISO LIFETIME — The patched ISO is generated in the user's chosen
//     output folder (default: Games/ROMs/tww/patched/). It is specific to the
//     AP seed/slot. On launch we look for the most recently generated .iso/.gcm
//     in that folder.
//
// ── WHAT THIS PLUGIN DOES ─────────────────────────────────────────────────────
//   1. INSTALL wwrando (AP fork) from tanjo3/wwrando GitHub releases. Downloads
//      the Windows zip, extracts into Games/TWWRando/. Stamps version.
//   2. SETTINGS:
//      - ISO path picker (validates "GZLE99" magic + size), copies to ROM library
//        (original never modified), stores path in sidecar JSON.
//      - wwrando install path (defaults to Games/TWWRando/, user can override).
//      - Dolphin path picker (auto-detect from common paths, user can override).
//      - aptww file path picker (copied to Games/ROMs/tww/ for convenience).
//   3. PATCH: guides user to open wwrando with their ISO + .aptww file, or opens
//      wwrando GUI with a hint about the files (we cannot inject aptww/iso args
//      silently since wwrando's no-ui mode reads from its own saved settings,
//      not from CLI positional args). The post-launch note instructs the user.
//   4. LAUNCH (AP):
//      a. Warn if no patched ISO exists yet (user must patch with wwrando first).
//      b. Detect ArchipelagoLauncher.exe in ProgramData\Archipelago (READ-ONLY).
//         If found, launch it with "The Wind Waker Client" --connect <server>
//         --password <pw>. If not found, launch ArchipelagoLauncher.exe with
//         those args anyway (user must install AP).
//      c. Launch Dolphin with the patched ISO: Dolphin.exe -b -e "<iso>".
//      The order: Client first, then Dolphin (the client waits for Dolphin to
//      hook anyway per its connection loop).
//   5. News from tanjo3/wwrando releases.
//
// ── DEFENSIVE / UNVERIFIED ("verify at build time") ───────────────────────────
//   * wwrando Windows exe name inside the zip: likely "wwrando_ap.exe" or
//     similar. Resolution is fuzzy ("*wwrando*", "*rando*", first non-installer
//     exe) — verified at actual build time when the zip is extracted.
//   * Dolphin exe name: "Dolphin.exe" or "DolphinQt2.exe". Both are tried.
//   * ArchipelagoLauncher.exe args for TWW Client: standard AP launcher usage
//     "The Wind Waker Client" --connect <server> --password <pw> — matches the
//     get_base_parser() pattern. If the launcher UI ignores the client-name arg
//     and opens a menu, the user picks "The Wind Waker Client" from it manually.
// ═══════════════════════════════════════════════════════════════════════════════

public sealed class WindWakerPlugin : IGamePlugin
{
    // ── Constants ────────────────────────────────────────────────────────────

    // wwrando (AP fork) — tanjo3/wwrando, "ap_*" tagged releases (verified).
    private const string WWRANDO_OWNER   = "tanjo3";
    private const string WWRANDO_REPO    = "wwrando";
    private const string WwrandoRepoUrl  = $"https://github.com/{WWRANDO_OWNER}/{WWRANDO_REPO}";
    private const string GH_WWRANDO_RELEASES_URL =
        $"https://api.github.com/repos/{WWRANDO_OWNER}/{WWRANDO_REPO}/releases";

    // Pinned fallback: tag ap_2.5.1 (2026-04-05), verified asset name.
    private const string FallbackWwrandoVersion = "ap_2.5.1";
    private const string FallbackWwrandoZipName = "wwrando_ap-2.5.1-windows.zip";
    private static readonly string FallbackWwrandoZipUrl =
        $"{WwrandoRepoUrl}/releases/download/{FallbackWwrandoVersion}/{FallbackWwrandoZipName}";

    // Standard AP Launcher (bundled in any AP install).
    private const string ApLauncherExeName  = "ArchipelagoLauncher.exe";
    private const string ApProgramDataDir   = @"C:\ProgramData\Archipelago";   // READ-ONLY
    // The game client name as registered in AP worlds/tww/__init__.py:
    //   Component("The Wind Waker Client", func=run_client, ...)
    private const string TwwClientName     = "The Wind Waker Client";

    // Official setup guide + AP page.
    private const string SetupGuideUrl  = "https://archipelago.gg/tutorial/The%20Wind%20Waker/setup/en";
    private const string ArchipelagoUrl = "https://archipelago.gg";
    private const string DolphinUrl     = "https://dolphin-emu.org/download/";

    // GCN ISO validation: TWW NA disc ID "GZLE99" in first 6 bytes (verified).
    private static readonly byte[] TwwDiscId = new byte[] { 0x47, 0x5A, 0x4C, 0x45, 0x39, 0x39 }; // "GZLE99"
    private const long MinIsoBytes = 400L * 1024 * 1024;   // 400 MB
    private const long MaxIsoBytes = 4L  * 1024 * 1024 * 1024; // 4 GB

    private static readonly HttpClient _http = new()
    {
        Timeout = TimeSpan.FromMinutes(20),
        DefaultRequestHeaders = { { "User-Agent", "Archipelago-Launcher/2.0" } }
    };

    private const string VersionFileName = "tww_rando_version.dat";

    // ── IGamePlugin — Identity ────────────────────────────────────────────────

    public string GameId      => "tww";
    public string DisplayName => "The Legend of Zelda: The Wind Waker";
    public string Subtitle    => "GameCube via Dolphin · Archipelago";

    /// EXACT AP game string (worlds/tww/__init__.py game = "The Wind Waker").
    public string ApWorldName => "The Wind Waker";

    public string IconPath =>
        Path.Combine(AppContext.BaseDirectory, "Assets", "tww.png");

    public string ThemeAccentColor => "#1A6EBC";  // ocean blue

    public string[] GameBadges => new[]
    {
        "Requires GCN ISO (North American)",
        "Requires Dolphin",
        "Requires AP Launcher",
    };

    public string Description =>
        "The Legend of Zelda: The Wind Waker is Nintendo's beloved 2002 GameCube " +
        "adventure across a vast ocean. This is the Archipelago integration: wwrando " +
        "(the Wind Waker AP Randomizer) patches your vanilla ISO into a multiworld " +
        "seed, Dolphin runs the patched game, and the Archipelago TWW Client monitors " +
        "Dolphin memory to track locations and deliver items. You bring your own North " +
        "American GameCube ISO; the launcher installs wwrando, helps you set up Dolphin " +
        "and the AP Launcher, and guides you through the one-time patching step.";

    public string? VideoPreviewUrl => null;
    public string[] ScreenshotUrls => Array.Empty<string>();

    // ── Version state ─────────────────────────────────────────────────────────
    public string? InstalledVersion { get; private set; }
    public string? AvailableVersion { get; private set; }

    /// "Installed" = wwrando AP exe is present in our managed folder.
    public bool IsInstalled => ResolveWwrandoExe() != null;
    public bool IsRunning   { get; private set; }

    // ── Paths ─────────────────────────────────────────────────────────────────

    /// Where we extract the wwrando Windows build.
    public string WwrandoDirectory { get; set; }
        = Path.Combine(AppContext.BaseDirectory, "Games", "TWWRando");

    /// IGamePlugin.GameDirectory — alias for WwrandoDirectory.
    public string GameDirectory => WwrandoDirectory;

    private string VersionFilePath => Path.Combine(WwrandoDirectory, VersionFileName);

    /// Default output folder for patched ISOs.
    private string PatchedIsoDirectory
        => Path.Combine(AppContext.BaseDirectory, "Games", "ROMs", GameId, "patched");

    /// This plugin's own settings sidecar (Games/ROMs/tww/tww_launcher.json).
    private string SettingsSidecarDir
        => Path.Combine(AppContext.BaseDirectory, "Games", "ROMs", GameId);
    private string SettingsSidecarPath
        => Path.Combine(SettingsSidecarDir, $"{GameId}_launcher.json");

    // ── Internal state ────────────────────────────────────────────────────────

    private Process? _twwClientProcess;
    private Process? _dolphinProcess;

    // ── AP bridge events ──────────────────────────────────────────────────────
    // The TWW Client (via AP Launcher) owns the slot — the launcher relays nothing.
#pragma warning disable CS0067
    public event Action<long[]>? LocationsChecked;
    public event Action?         GoalCompleted;
#pragma warning restore CS0067

    public event Action<int>? GameExited;

    // ── Lifecycle — CheckForUpdate ────────────────────────────────────────────

    public async Task CheckForUpdateAsync(CancellationToken ct = default)
    {
        try
        {
            InstalledVersion = File.Exists(VersionFilePath) && IsInstalled
                ? (await File.ReadAllTextAsync(VersionFilePath, ct)).Trim()
                : (IsInstalled ? "installed" : null);
        }
        catch { InstalledVersion = null; }

        try
        {
            // CDN HEAD redirect — no REST API quota consumed.
            AvailableVersion = GitHubHelper.NormalizeTag(
                await GitHubHelper.FetchLatestTagAsync(WWRANDO_OWNER, WWRANDO_REPO, ct));
        }
        catch { AvailableVersion = null; }
    }

    // ── Lifecycle — InstallOrUpdate ───────────────────────────────────────────

    public async Task InstallOrUpdateAsync(
        IProgress<(int Pct, string Msg)> progress,
        CancellationToken ct = default)
    {
        progress.Report((2, "Checking latest wwrando (AP fork) release..."));
        var (version, zipUrl, zipName) = await ResolveLatestWwrandoAsync(ct);
        AvailableVersion = version;

        // Already current?
        if (IsInstalled
            && File.Exists(VersionFilePath)
            && (await File.ReadAllTextAsync(VersionFilePath, ct)).Trim() == version)
        {
            InstalledVersion = version;
            progress.Report((100, $"wwrando {version} is up to date."));
            return;
        }

        if (zipUrl == null)
            throw new InvalidOperationException(
                "Could not find the wwrando Windows download on GitHub. Check your " +
                "internet connection or download manually from " +
                WwrandoRepoUrl + "/releases (look for a tag starting with \"ap_\"). " +
                "You also need Dolphin (https://dolphin-emu.org/download/) and the " +
                "Archipelago Launcher (https://archipelago.gg/). Read the setup guide: " +
                SetupGuideUrl);

        await DownloadAndExtractWwrandoAsync(zipUrl, zipName ?? FallbackWwrandoZipName,
            version, progress, ct);

        await File.WriteAllTextAsync(VersionFilePath, version, ct);
        InstalledVersion = version;

        Directory.CreateDirectory(PatchedIsoDirectory);

        progress.Report((100,
            $"wwrando {version} installed. " +
            "NEXT STEPS: (1) Make sure Dolphin is installed. " +
            "(2) Make sure the Archipelago Launcher is installed from archipelago.gg. " +
            "(3) Use Settings to point to your Wind Waker GCN ISO (North American .iso). " +
            "(4) When you have a .aptww file from your AP multiworld, open wwrando " +
            "(Launch > Open Patcher), load the .aptww and your ISO, and click Randomize " +
            "to produce the patched ISO. Then click Play to start the TWW Client and Dolphin."));
    }

    // ── Lifecycle — Verify ────────────────────────────────────────────────────

    public async Task<bool> VerifyInstallAsync(CancellationToken ct = default)
    {
        await Task.CompletedTask;
        return IsInstalled;
    }

    // ── Lifecycle — Launch ────────────────────────────────────────────────────

    /// ConnectsItself = true: the TWW Client (via AP Launcher) holds the AP slot.
    public bool ConnectsItself     => true;

    /// No standalone non-AP play via this integration (wwrando is for AP seeds).
    public bool SupportsStandalone => false;

    public Task LaunchAsync(ApSession session, CancellationToken ct = default)
    {
        // Step 1: warn if no patched ISO is available.
        string? patchedIso = FindMostRecentPatchedIso();
        if (patchedIso == null)
        {
            MessageBox.Show(
                "No patched Wind Waker ISO found in:\n" + PatchedIsoDirectory + "\n\n" +
                "Before launching, you must patch your vanilla ISO with wwrando:\n" +
                "  1. Open wwrando (Install > Open Patcher on this tab).\n" +
                "  2. Select your .aptww file (from the AP multiworld organizer).\n" +
                "  3. Select your vanilla Wind Waker ISO (North American).\n" +
                "  4. Click Randomize. The patched ISO is saved in the output folder.\n\n" +
                "Then click Play again.",
                "Patch Required",
                MessageBoxButton.OK,
                MessageBoxImage.Information);
            return Task.CompletedTask;
        }

        // Step 2: start the TWW Client via ArchipelagoLauncher.exe.
        StartTwwClient(session);

        // Step 3: start Dolphin with the patched ISO.
        StartDolphin(patchedIso);

        return Task.CompletedTask;
    }

    public Task LaunchStandaloneAsync(CancellationToken ct = default)
    {
        // No standalone mode — the integration only makes sense with AP.
        MessageBox.Show(
            "The Wind Waker AP integration requires an Archipelago multiworld session " +
            "and a patched ISO generated by wwrando. There is no standalone (non-AP) play " +
            "through this launcher entry.\n\n" +
            "To open wwrando's patcher, use the Open Patcher button in Settings.",
            "No Standalone Mode",
            MessageBoxButton.OK,
            MessageBoxImage.Information);
        return Task.CompletedTask;
    }

    public Task StopAsync()
    {
        try { _twwClientProcess?.Kill(entireProcessTree: true); } catch { }
        try { _dolphinProcess?.Kill(entireProcessTree: true); } catch { }
        IsRunning         = false;
        _twwClientProcess = null;
        _dolphinProcess   = null;
        return Task.CompletedTask;
    }

    // ── AP bridge — inert (ConnectsItself) ───────────────────────────────────

    public Task ReceiveItemsAsync(ApNetworkItem[] items, int index, CancellationToken ct = default)
        => Task.CompletedTask;

    public void OnApStateChanged(ApConnectionState state) { }

    // ── Settings UI ───────────────────────────────────────────────────────────

    public UIElement? CreateSettingsPanel()
    {
        var muted   = new SolidColorBrush(Color.FromRgb(0x72, 0x7A, 0x99));
        var fg      = new SolidColorBrush(Color.FromRgb(0xCC, 0xD0, 0xE0));
        var success = new SolidColorBrush(Color.FromRgb(0x4C, 0xAF, 0x50));
        var warn    = new SolidColorBrush(Color.FromRgb(0xE0, 0xA0, 0x30));
        var panel   = new System.Windows.Controls.StackPanel { Margin = new Thickness(0, 0, 0, 20) };

        // ── Overview ──────────────────────────────────────────────────────
        panel.Children.Add(new System.Windows.Controls.TextBlock
        {
            Text =
                "The Wind Waker Archipelago uses three components:\n" +
                "  1. wwrando — patches your GCN ISO into an AP seed.\n" +
                "  2. Dolphin — GameCube emulator that runs the patched ISO.\n" +
                "  3. TWW Client — part of the Archipelago Launcher; hooks Dolphin.\n\n" +
                "The launcher installs wwrando. You install Dolphin and the AP Launcher " +
                "separately. The client connects and auto-authenticates from Dolphin memory " +
                "— you do not type your slot name.",
            FontSize = 11, Foreground = fg, TextWrapping = System.Windows.TextWrapping.Wrap,
            Margin = new Thickness(0, 0, 0, 14),
        });

        // ── Section: wwrando ──────────────────────────────────────────────
        panel.Children.Add(SectionHeader("WWRANDO (AP PATCHER)", muted));

        string? randoExe = ResolveWwrandoExe();
        panel.Children.Add(new System.Windows.Controls.TextBlock
        {
            Text = randoExe != null
                ? "Installed: " + randoExe
                : "Not installed — use the Install button on the Play tab.",
            FontSize = 11,
            Foreground = randoExe != null ? success : muted,
            TextWrapping = System.Windows.TextWrapping.Wrap,
            Margin = new Thickness(0, 0, 0, 6),
        });

        // Open wwrando GUI button (only shown if installed)
        if (randoExe != null)
        {
            var openBtn = new System.Windows.Controls.Button
            {
                Content = "Open Patcher (wwrando)",
                Width   = 200,
                Padding = new Thickness(0, 6, 0, 6),
                HorizontalAlignment = System.Windows.HorizontalAlignment.Left,
                Margin      = new Thickness(0, 0, 0, 12),
                Background  = new SolidColorBrush(Color.FromRgb(0x1A, 0x1E, 0x30)),
                Foreground  = fg,
                BorderBrush = new SolidColorBrush(Color.FromRgb(0x2A, 0x30, 0x50)),
            };
            string randoExeCapture = randoExe;
            openBtn.Click += (_, _) =>
            {
                try
                {
                    Process.Start(new ProcessStartInfo
                    {
                        FileName         = randoExeCapture,
                        WorkingDirectory = Path.GetDirectoryName(randoExeCapture) ?? WwrandoDirectory,
                        UseShellExecute  = true,
                    });
                }
                catch (Exception ex)
                {
                    MessageBox.Show(
                        "Could not open wwrando:\n" + ex.Message,
                        "Launch Error", MessageBoxButton.OK, MessageBoxImage.Warning);
                }
            };
            panel.Children.Add(openBtn);
        }

        panel.Children.Add(new System.Windows.Controls.TextBlock
        {
            Text =
                "To patch your ISO:\n" +
                "  1. Get a .aptww file from the AP multiworld room (the organizer " +
                "exports one per player).\n" +
                "  2. Open wwrando (above or from Install tab).\n" +
                "  3. Load the .aptww file in the \"APTWW File\" field.\n" +
                "  4. Set your vanilla GCN ISO path.\n" +
                "  5. Click Randomize. The patched ISO lands in the output folder.\n\n" +
                "Patched ISOs are saved to:\n" + PatchedIsoDirectory,
            FontSize = 11, Foreground = muted,
            TextWrapping = System.Windows.TextWrapping.Wrap,
            Margin = new Thickness(0, 0, 0, 14),
        });

        // ── Section: vanilla ISO ──────────────────────────────────────────
        panel.Children.Add(SectionHeader("VANILLA WIND WAKER ISO (North American GCN)", muted));

        var settings   = LoadSettings();
        string isoPath = settings.VanillaIsoPath ?? "";

        bool isoOk = !string.IsNullOrWhiteSpace(isoPath) && File.Exists(isoPath)
                     && ValidateIso(isoPath) == null;

        panel.Children.Add(new System.Windows.Controls.TextBlock
        {
            Text = isoOk
                ? "Validated: " + isoPath
                : string.IsNullOrWhiteSpace(isoPath)
                    ? "No ISO selected. Pick your North American Wind Waker GCN ISO below."
                    : "ISO not found or failed validation: " + isoPath,
            FontSize = 11,
            Foreground = isoOk ? success : warn,
            TextWrapping = System.Windows.TextWrapping.Wrap,
            Margin = new Thickness(0, 0, 0, 6),
        });

        var isoRow = new System.Windows.Controls.DockPanel { Margin = new Thickness(0, 0, 0, 4) };
        var isoBox = new System.Windows.Controls.TextBox
        {
            Text        = isoPath,
            IsReadOnly  = true,
            FontSize    = 12,
            Margin      = new Thickness(0, 0, 8, 0),
            Background  = new SolidColorBrush(Color.FromRgb(0x0C, 0x10, 0x20)),
            Foreground  = fg,
            BorderBrush = new SolidColorBrush(Color.FromRgb(0x1E, 0x22, 0x33)),
            ToolTip     = "Your vanilla North American Wind Waker GCN ISO. " +
                          "Must start with disc ID \"GZLE99\". Not modified — a copy " +
                          "is kept in the launcher's ROM library.",
        };
        var isoBtn = new System.Windows.Controls.Button
        {
            Content     = "Select ISO...",
            Width       = 120,
            Padding     = new Thickness(0, 6, 0, 6),
            Background  = new SolidColorBrush(Color.FromRgb(0x1A, 0x1E, 0x30)),
            Foreground  = fg,
            BorderBrush = new SolidColorBrush(Color.FromRgb(0x2A, 0x30, 0x50)),
        };
        isoBtn.Click += (_, _) =>
        {
            var dlg = new Microsoft.Win32.OpenFileDialog
            {
                Title  = "Select your Wind Waker GCN ISO (North American)",
                Filter = "GameCube ISO (*.iso;*.gcm)|*.iso;*.gcm|All files (*.*)|*.*",
            };
            if (dlg.ShowDialog() != true) return;

            string? bad = ValidateIso(dlg.FileName);
            if (bad != null)
            {
                MessageBox.Show(bad, "Invalid ISO",
                    MessageBoxButton.OK, MessageBoxImage.Warning);
                return;
            }

            // Copy into ROM library (original never modified).
            try
            {
                Directory.CreateDirectory(SettingsSidecarDir);
                string dest = Path.Combine(SettingsSidecarDir, Path.GetFileName(dlg.FileName));
                if (!string.Equals(dlg.FileName, dest, StringComparison.OrdinalIgnoreCase))
                    File.Copy(dlg.FileName, dest, overwrite: true);
                var s = LoadSettings();
                s.VanillaIsoPath = dest;
                SaveSettings(s);
                isoBox.Text = dest;
            }
            catch (Exception ex)
            {
                MessageBox.Show(
                    "Could not copy the ISO into the launcher library:\n" + ex.Message +
                    "\n\nYour original file was not modified.",
                    "Copy Failed", MessageBoxButton.OK, MessageBoxImage.Warning);
            }
        };
        System.Windows.Controls.DockPanel.SetDock(isoBtn, System.Windows.Controls.Dock.Right);
        isoRow.Children.Add(isoBtn);
        isoRow.Children.Add(isoBox);
        panel.Children.Add(isoRow);

        panel.Children.Add(new System.Windows.Controls.TextBlock
        {
            Text = "Validation: first 6 bytes must be \"GZLE99\" (North American disc ID). " +
                   "Your original ISO is never modified — a copy is stored in the launcher " +
                   "library. Pass this copy path to wwrando as the \"Vanilla Wind Waker ISO\".",
            FontSize = 11, Foreground = muted,
            TextWrapping = System.Windows.TextWrapping.Wrap,
            Margin = new Thickness(0, 4, 0, 14),
        });

        // ── Section: Dolphin ──────────────────────────────────────────────
        panel.Children.Add(SectionHeader("DOLPHIN EMULATOR", muted));

        string? detectedDolphin = settings.DolphinExePath;
        if (string.IsNullOrWhiteSpace(detectedDolphin) || !File.Exists(detectedDolphin))
            detectedDolphin = DetectDolphinExe();

        bool dolphinOk = !string.IsNullOrWhiteSpace(detectedDolphin) && File.Exists(detectedDolphin);
        panel.Children.Add(new System.Windows.Controls.TextBlock
        {
            Text = dolphinOk
                ? "Found: " + detectedDolphin
                : "Dolphin not found. Download from dolphin-emu.org and set path below, or " +
                  "place Dolphin.exe somewhere this launcher can find it (see common paths below).",
            FontSize = 11,
            Foreground = dolphinOk ? success : warn,
            TextWrapping = System.Windows.TextWrapping.Wrap,
            Margin = new Thickness(0, 0, 0, 6),
        });

        var dolphinRow = new System.Windows.Controls.DockPanel { Margin = new Thickness(0, 0, 0, 4) };
        var dolphinBox = new System.Windows.Controls.TextBox
        {
            Text        = detectedDolphin ?? "",
            IsReadOnly  = true,
            FontSize    = 12,
            Margin      = new Thickness(0, 0, 8, 0),
            Background  = new SolidColorBrush(Color.FromRgb(0x0C, 0x10, 0x20)),
            Foreground  = fg,
            BorderBrush = new SolidColorBrush(Color.FromRgb(0x1E, 0x22, 0x33)),
        };
        var dolphinBtn = new System.Windows.Controls.Button
        {
            Content     = "Select Dolphin...",
            Width       = 130,
            Padding     = new Thickness(0, 6, 0, 6),
            Background  = new SolidColorBrush(Color.FromRgb(0x1A, 0x1E, 0x30)),
            Foreground  = fg,
            BorderBrush = new SolidColorBrush(Color.FromRgb(0x2A, 0x30, 0x50)),
        };
        dolphinBtn.Click += (_, _) =>
        {
            var dlg = new Microsoft.Win32.OpenFileDialog
            {
                Title  = "Select Dolphin.exe",
                Filter = "Dolphin (*.exe)|*.exe|All files (*.*)|*.*",
            };
            if (dlg.ShowDialog() != true) return;
            if (!dlg.FileName.EndsWith(".exe", StringComparison.OrdinalIgnoreCase))
            {
                MessageBox.Show("That does not look like a Dolphin executable.",
                    "Invalid Exe", MessageBoxButton.OK, MessageBoxImage.Warning);
                return;
            }
            var s = LoadSettings();
            s.DolphinExePath = dlg.FileName;
            SaveSettings(s);
            dolphinBox.Text = dlg.FileName;
        };
        System.Windows.Controls.DockPanel.SetDock(dolphinBtn, System.Windows.Controls.Dock.Right);
        dolphinRow.Children.Add(dolphinBtn);
        dolphinRow.Children.Add(dolphinBox);
        panel.Children.Add(dolphinRow);

        panel.Children.Add(new System.Windows.Controls.TextBlock
        {
            Text = "Common Dolphin paths:\n" +
                   "  • %LOCALAPPDATA%\\Dolphin\\Dolphin.exe\n" +
                   "  • %ProgramFiles%\\Dolphin\\Dolphin.exe\n" +
                   "  • %ProgramFiles(x86)%\\Dolphin\\Dolphin.exe\n" +
                   "Dolphin is launched with: Dolphin.exe -b -e \"<patched-iso>\"",
            FontSize = 11, Foreground = muted,
            TextWrapping = System.Windows.TextWrapping.Wrap,
            Margin = new Thickness(0, 4, 0, 14),
        });

        // ── Section: AP Launcher ──────────────────────────────────────────
        panel.Children.Add(SectionHeader("ARCHIPELAGO LAUNCHER (TWW CLIENT)", muted));

        string? apLauncher = FindApLauncherExe();
        panel.Children.Add(new System.Windows.Controls.TextBlock
        {
            Text = apLauncher != null
                ? "Found: " + apLauncher
                : "Archipelago Launcher not found in " + ApProgramDataDir + ".\n" +
                  "Install Archipelago from archipelago.gg to get the TWW Client.",
            FontSize = 11,
            Foreground = apLauncher != null ? success : warn,
            TextWrapping = System.Windows.TextWrapping.Wrap,
            Margin = new Thickness(0, 0, 0, 14),
        });

        // ── Section: patched ISO ──────────────────────────────────────────
        panel.Children.Add(SectionHeader("PATCHED ISO", muted));

        string? latest = FindMostRecentPatchedIso();
        panel.Children.Add(new System.Windows.Controls.TextBlock
        {
            Text = latest != null
                ? "Most recent patched ISO: " + latest
                : "No patched ISO found in " + PatchedIsoDirectory + ".\n" +
                  "After running wwrando, set its output folder to that path.",
            FontSize = 11,
            Foreground = latest != null ? success : muted,
            TextWrapping = System.Windows.TextWrapping.Wrap,
            Margin = new Thickness(0, 0, 0, 14),
        });

        // ── Section: links ────────────────────────────────────────────────
        panel.Children.Add(SectionHeader("LINKS", muted));
        foreach (var (label, url) in new[]
        {
            ("TWW AP Setup Guide ↗",     SetupGuideUrl),
            ("wwrando (GitHub) ↗",       WwrandoRepoUrl),
            ("Dolphin Emulator ↗",       DolphinUrl),
            ("Archipelago Official ↗",   ArchipelagoUrl),
        })
        {
            var btn = new System.Windows.Controls.Button
            {
                Content             = label,
                HorizontalAlignment = System.Windows.HorizontalAlignment.Left,
                Padding             = new Thickness(0, 2, 0, 2),
                Background          = Brushes.Transparent,
                BorderThickness     = new Thickness(0),
                FontSize            = 12,
                Margin              = new Thickness(0, 0, 0, 4),
                Foreground          = new SolidColorBrush(Color.FromRgb(0x60, 0x9A, 0xFF)),
                Cursor              = System.Windows.Input.Cursors.Hand,
            };
            string u = url;
            btn.Click += (_, _) =>
            {
                try { Process.Start(new ProcessStartInfo(u) { UseShellExecute = true }); }
                catch { }
            };
            panel.Children.Add(btn);
        }

        return panel;
    }

    private static System.Windows.Controls.TextBlock SectionHeader(string text, System.Windows.Media.Brush brush)
        => new System.Windows.Controls.TextBlock
        {
            Text        = text,
            FontSize    = 10,
            FontWeight  = FontWeights.SemiBold,
            Foreground  = brush,
            Margin      = new Thickness(0, 8, 0, 8),
        };

    // ── News ─────────────────────────────────────────────────────────────────

    public async Task<NewsItem[]> GetNewsAsync(CancellationToken ct = default)
    {
        try
        {
            string json = await _http.GetStringAsync(GH_WWRANDO_RELEASES_URL, ct);
            using var doc = JsonDocument.Parse(json);
            if (doc.RootElement.ValueKind != JsonValueKind.Array)
                return Array.Empty<NewsItem>();

            var items = new List<NewsItem>();
            foreach (var el in doc.RootElement.EnumerateArray())
            {
                string? tag = el.TryGetProperty("tag_name", out var t) ? t.GetString() : null;
                // Only include AP-flavoured releases (tag starts with "ap_" or "ap").
                if (tag == null || (!tag.StartsWith("ap", StringComparison.OrdinalIgnoreCase)))
                    continue;

                DateTimeOffset date = DateTimeOffset.MinValue;
                if (el.TryGetProperty("published_at", out var d) && d.ValueKind == JsonValueKind.String)
                    DateTimeOffset.TryParse(d.GetString(), out date);

                items.Add(new NewsItem(
                    Title:   el.TryGetProperty("name",     out var n) ? n.GetString() ?? "" : "",
                    Body:    el.TryGetProperty("body",     out var b) ? b.GetString() ?? "" : "",
                    Version: NormalizeTag(tag) ?? "",
                    Date:    date,
                    Url:     el.TryGetProperty("html_url", out var u) ? u.GetString() : null
                ));
                if (items.Count >= 10) break;
            }
            return items.ToArray();
        }
        catch { return Array.Empty<NewsItem>(); }
    }

    // ── Private helpers — release resolution ──────────────────────────────────

    private static string? NormalizeTag(string? tag)
    {
        if (string.IsNullOrWhiteSpace(tag)) return null;
        tag = tag.Trim();
        return tag.StartsWith('v') && tag.Length > 1 && char.IsDigit(tag[1])
            ? tag[1..]
            : tag;
    }

    /// Resolve the latest AP-flavoured wwrando release (tags starting with "ap").
    /// Returns (version, windowsZipUrl, zipAssetName). Falls back to pinned when
    /// the API is unreachable.
    private async Task<(string Version, string? ZipUrl, string? ZipName)>
        ResolveLatestWwrandoAsync(CancellationToken ct)
    {
        try
        {
            string json = await _http.GetStringAsync(GH_WWRANDO_RELEASES_URL, ct);
            using var doc = JsonDocument.Parse(json);
            if (doc.RootElement.ValueKind != JsonValueKind.Array)
                goto fallback;

            foreach (var rel in doc.RootElement.EnumerateArray())
            {
                string? tag = rel.TryGetProperty("tag_name", out var t) ? t.GetString() : null;
                // Only consider AP-flavoured releases.
                if (tag == null || !tag.StartsWith("ap", StringComparison.OrdinalIgnoreCase))
                    continue;

                if (!rel.TryGetProperty("assets", out var assets) ||
                    assets.ValueKind != JsonValueKind.Array)
                    continue;

                foreach (var a in assets.EnumerateArray())
                {
                    string? name = a.TryGetProperty("name", out var n) ? n.GetString() : null;
                    string? url  = a.TryGetProperty("browser_download_url", out var u) ? u.GetString() : null;
                    if (name == null || url == null) continue;

                    string lower = name.ToLowerInvariant();
                    if (!lower.EndsWith(".zip")) continue;
                    if (lower.Contains("linux") || lower.Contains("macos") || lower.Contains("mac") ||
                        lower.Contains("qt5"))   continue;  // skip non-Windows; also prefer non-qt5 build
                    if (lower.Contains("windows") || lower.Contains("win"))
                        return (tag, url, name);
                }

                // Last resort: any non-linux/mac zip in this AP release.
                foreach (var a in assets.EnumerateArray())
                {
                    string? name = a.TryGetProperty("name", out var n) ? n.GetString() : null;
                    string? url  = a.TryGetProperty("browser_download_url", out var u) ? u.GetString() : null;
                    if (name == null || url == null) continue;
                    string lower = name.ToLowerInvariant();
                    if (!lower.EndsWith(".zip")) continue;
                    if (lower.Contains("linux") || lower.Contains("macos") || lower.Contains("mac")) continue;
                    return (tag, url, name);
                }
            }
        }
        catch (OperationCanceledException) { throw; }
        catch { /* API unreachable → pinned fallback */ }

        fallback:
        return (FallbackWwrandoVersion, FallbackWwrandoZipUrl, FallbackWwrandoZipName);
    }

    // ── Private helpers — wwrando exe resolution ──────────────────────────────

    /// Find the wwrando AP exe in our install folder. Prefers the first exe whose
    /// name contains "wwrando" or "rando" (excluding installers/helpers). Falls
    /// back to the single non-helper exe if exactly one exists.
    private string? ResolveWwrandoExe()
    {
        try
        {
            if (!Directory.Exists(WwrandoDirectory)) return null;

            string[] exes = Directory.EnumerateFiles(
                WwrandoDirectory, "*.exe", SearchOption.TopDirectoryOnly).ToArray();

            // Prefer a plausibly-named app exe.
            foreach (string exe in exes)
            {
                string name = Path.GetFileNameWithoutExtension(exe).ToLowerInvariant();
                if (IsHelperExe(name)) continue;
                if (name.Contains("wwrando") || name.Contains("rando") ||
                    name.Contains("wind")    || name.Contains("waker"))
                    return exe;
            }
            // Single non-helper exe.
            string[] candidates = exes
                .Where(e => !IsHelperExe(Path.GetFileNameWithoutExtension(e).ToLowerInvariant()))
                .ToArray();
            return candidates.Length == 1 ? candidates[0] : null;
        }
        catch { return null; }
    }

    private static bool IsHelperExe(string nameLowerNoExt)
        => nameLowerNoExt.Contains("unins")    ||
           nameLowerNoExt.Contains("setup")    ||
           nameLowerNoExt.Contains("crash")    ||
           nameLowerNoExt.Contains("vcredist") ||
           nameLowerNoExt.Contains("dxsetup");

    // ── Private helpers — launch ──────────────────────────────────────────────

    /// Start the TWW Client via ArchipelagoLauncher.exe. Passes "The Wind Waker
    /// Client" as the client name and --connect / --password from the session.
    /// If the launcher opens a menu instead of auto-selecting, the user picks
    /// the client there. Best effort — does not block launch if AP is absent.
    private void StartTwwClient(ApSession session)
    {
        string? launcherExe = FindApLauncherExe();
        if (launcherExe == null)
        {
            MessageBox.Show(
                "Archipelago Launcher not found in " + ApProgramDataDir + ".\n\n" +
                "Please install Archipelago from https://archipelago.gg to get the " +
                "Wind Waker Client. Without it, Dolphin will launch but location " +
                "checks will not be tracked.",
                "AP Launcher Not Found",
                MessageBoxButton.OK,
                MessageBoxImage.Warning);
            return;
        }

        // Build args: "The Wind Waker Client" --connect <server> [--password <pw>]
        var args = new List<string> { $"\"{TwwClientName}\"" };
        if (!string.IsNullOrWhiteSpace(session.ServerUri))
            args.Add($"--connect \"{session.ServerUri}\"");
        if (!string.IsNullOrWhiteSpace(session.Password))
            args.Add($"--password \"{session.Password}\"");

        try
        {
            var proc = Process.Start(new ProcessStartInfo
            {
                FileName         = launcherExe,
                Arguments        = string.Join(" ", args),
                WorkingDirectory = Path.GetDirectoryName(launcherExe) ?? ApProgramDataDir,
                UseShellExecute  = false,
            });
            if (proc != null)
            {
                _twwClientProcess = proc;
                IsRunning = true;
                try
                {
                    proc.EnableRaisingEvents = true;
                    proc.Exited += (_, _) =>
                    {
                        IsRunning = false;
                        GameExited?.Invoke(proc.ExitCode);
                    };
                }
                catch { /* non-fatal */ }
            }
        }
        catch (Exception ex)
        {
            MessageBox.Show(
                "Could not start the Archipelago Launcher:\n" + ex.Message +
                "\n\nDolphin will still be launched. Start the TWW Client manually " +
                "from the Archipelago Launcher if needed.",
                "Client Launch Error",
                MessageBoxButton.OK,
                MessageBoxImage.Warning);
        }
    }

    /// Start Dolphin with the patched ISO: Dolphin.exe -b -e "<isoPath>".
    private void StartDolphin(string patchedIso)
    {
        string? dolphinExe = ResolveDolphinExe();
        if (dolphinExe == null)
        {
            MessageBox.Show(
                "Dolphin.exe not found. Please install Dolphin from:\n" +
                DolphinUrl + "\n\nThen set the Dolphin path in Settings.",
                "Dolphin Not Found",
                MessageBoxButton.OK,
                MessageBoxImage.Warning);
            return;
        }

        try
        {
            // -b = start in background/no-gui (or suppress splash); -e = boot ISO.
            var proc = Process.Start(new ProcessStartInfo
            {
                FileName         = dolphinExe,
                Arguments        = $"-b -e \"{patchedIso}\"",
                WorkingDirectory = Path.GetDirectoryName(dolphinExe) ?? "",
                UseShellExecute  = false,
            });
            if (proc != null)
            {
                _dolphinProcess = proc;
                IsRunning = true;
                try
                {
                    proc.EnableRaisingEvents = true;
                    proc.Exited += (_, _) =>
                    {
                        IsRunning = false;
                        GameExited?.Invoke(proc.ExitCode);
                    };
                }
                catch { /* non-fatal */ }
            }
        }
        catch (Exception ex)
        {
            MessageBox.Show(
                "Could not start Dolphin:\n" + ex.Message,
                "Dolphin Launch Error",
                MessageBoxButton.OK,
                MessageBoxImage.Warning);
        }
    }

    // ── Private helpers — Dolphin detection ──────────────────────────────────

    private string? ResolveDolphinExe()
    {
        var s = LoadSettings();
        if (!string.IsNullOrWhiteSpace(s.DolphinExePath) && File.Exists(s.DolphinExePath))
            return s.DolphinExePath;
        return DetectDolphinExe();
    }

    /// Scan common Dolphin install locations on Windows. Returns the first exe
    /// found, or null. Never throws.
    private static string? DetectDolphinExe()
    {
        string[] exeNames = { "Dolphin.exe", "DolphinQt2.exe" };

        string localApp = Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData);
        string progFiles = Environment.GetFolderPath(Environment.SpecialFolder.ProgramFiles);
        string progX86   = Environment.GetFolderPath(Environment.SpecialFolder.ProgramFilesX86);

        string[] searchRoots =
        {
            Path.Combine(localApp,   "Dolphin"),
            Path.Combine(localApp,   "Programs", "Dolphin"),
            Path.Combine(progFiles,  "Dolphin"),
            Path.Combine(progFiles,  "Dolphin Emulator"),
            Path.Combine(progX86,    "Dolphin"),
            Path.Combine(progX86,    "Dolphin Emulator"),
        };

        foreach (string root in searchRoots)
        {
            if (!Directory.Exists(root)) continue;
            foreach (string name in exeNames)
            {
                string candidate = Path.Combine(root, name);
                if (File.Exists(candidate)) return candidate;
            }
            // Also walk one level deep (e.g. Dolphin\Dolphin-x64\Dolphin.exe)
            try
            {
                foreach (string sub in Directory.EnumerateDirectories(root))
                {
                    foreach (string name in exeNames)
                    {
                        string candidate = Path.Combine(sub, name);
                        if (File.Exists(candidate)) return candidate;
                    }
                }
            }
            catch { /* skip */ }
        }
        return null;
    }

    // ── Private helpers — AP Launcher detection ───────────────────────────────

    /// ArchipelagoLauncher.exe in ProgramData\Archipelago (READ-ONLY detection).
    private static string? FindApLauncherExe()
    {
        string candidate = Path.Combine(ApProgramDataDir, ApLauncherExeName);
        return File.Exists(candidate) ? candidate : null;
    }

    // ── Private helpers — ISO validation ─────────────────────────────────────

    /// Validate a GCN ISO: reads first 6 bytes and checks for TWW NA disc ID
    /// "GZLE99", and checks file size. Returns null if valid, else error message.
    private static string? ValidateIso(string path)
    {
        if (string.IsNullOrWhiteSpace(path))
            return "No file selected.";

        string ext = Path.GetExtension(path).ToLowerInvariant();
        if (ext != ".iso" && ext != ".gcm")
            return "The file must be a GameCube ISO (.iso or .gcm).";

        FileInfo fi;
        try { fi = new FileInfo(path); }
        catch { return "Could not access the file. Is it on a network drive or locked?"; }

        if (!fi.Exists)
            return "File does not exist: " + path;

        if (fi.Length < MinIsoBytes || fi.Length > MaxIsoBytes)
            return $"Unexpected file size ({fi.Length / (1024 * 1024)} MB). " +
                   "A Wind Waker ISO should be between 400 MB and 4 GB.";

        try
        {
            byte[] header = new byte[TwwDiscId.Length];
            using var f = File.OpenRead(path);
            int read = f.Read(header, 0, header.Length);
            if (read < TwwDiscId.Length)
                return "Could not read the disc header. The file may be corrupt.";

            for (int i = 0; i < TwwDiscId.Length; i++)
            {
                if (header[i] != TwwDiscId[i])
                    return $"This does not appear to be a North American Wind Waker disc " +
                           $"(disc ID is \"{System.Text.Encoding.ASCII.GetString(header)}\" — " +
                           $"expected \"GZLE99\"). Only the North American GameCube release is " +
                           $"supported. Japanese is GZLJ01, European is GZLP01.";
            }
        }
        catch (Exception ex)
        {
            return "Could not read the ISO header: " + ex.Message;
        }

        return null; // valid
    }

    // ── Private helpers — patched ISO resolution ──────────────────────────────

    /// Find the most recently written .iso or .gcm in the patched ISO folder.
    private string? FindMostRecentPatchedIso()
    {
        try
        {
            if (!Directory.Exists(PatchedIsoDirectory)) return null;
            return Directory
                .EnumerateFiles(PatchedIsoDirectory, "*.iso", SearchOption.TopDirectoryOnly)
                .Concat(Directory.EnumerateFiles(PatchedIsoDirectory, "*.gcm", SearchOption.TopDirectoryOnly))
                .OrderByDescending(f => File.GetLastWriteTimeUtc(f))
                .FirstOrDefault();
        }
        catch { return null; }
    }

    // ── Private helpers — download + extract wwrando ──────────────────────────

    private async Task DownloadAndExtractWwrandoAsync(
        string zipUrl,
        string zipName,
        string version,
        IProgress<(int Pct, string Msg)> progress,
        CancellationToken ct)
    {
        string tempZip = Path.Combine(Path.GetTempPath(),
            $"wwrando-{version}-{Guid.NewGuid():N}.zip");
        try
        {
            progress.Report((5, $"Downloading wwrando {version}..."));
            using var response = await _http.GetAsync(
                zipUrl, HttpCompletionOption.ResponseHeadersRead, ct);
            response.EnsureSuccessStatusCode();

            long total      = response.Content.Headers.ContentLength ?? -1;
            long downloaded = 0;

            await using (var src = await response.Content.ReadAsStreamAsync(ct))
            await using (var dst = File.Create(tempZip))
            {
                var buf = new byte[81920];
                int bytesRead;
                while ((bytesRead = await src.ReadAsync(buf, ct)) > 0)
                {
                    await dst.WriteAsync(buf.AsMemory(0, bytesRead), ct);
                    downloaded += bytesRead;
                    if (total > 0)
                    {
                        int pct = (int)(5 + 70 * downloaded / total);
                        progress.Report((pct, $"Downloading wwrando... {downloaded / 1_000_000} MB"));
                    }
                }
                await dst.FlushAsync(ct);
            }

            progress.Report((80, "Extracting wwrando..."));
            Directory.CreateDirectory(WwrandoDirectory);
            System.IO.Compression.ZipFile.ExtractToDirectory(tempZip, WwrandoDirectory, overwriteFiles: true);

            // Flatten a single top-level subfolder if the exe is not yet in the root.
            if (ResolveWwrandoExe() == null)
            {
                string[] subdirs = Directory.GetDirectories(WwrandoDirectory);
                if (subdirs.Length == 1)
                {
                    string sub = subdirs[0];
                    foreach (string fileSrc in Directory.EnumerateFiles(
                        sub, "*", SearchOption.AllDirectories))
                    {
                        string rel     = Path.GetRelativePath(sub, fileSrc);
                        string fileDst = Path.Combine(WwrandoDirectory, rel);
                        Directory.CreateDirectory(Path.GetDirectoryName(fileDst)!);
                        File.Move(fileSrc, fileDst, overwrite: true);
                    }
                    Directory.Delete(sub, recursive: true);
                }
            }

            progress.Report((95, "Finalizing..."));
        }
        finally
        {
            try { if (File.Exists(tempZip)) File.Delete(tempZip); } catch { }
        }
    }

    // ── Private helpers — settings sidecar ───────────────────────────────────

    private sealed class TwwSettings
    {
        public string? VanillaIsoPath  { get; set; }
        public string? DolphinExePath  { get; set; }
    }

    private TwwSettings LoadSettings()
    {
        try
        {
            if (File.Exists(SettingsSidecarPath))
            {
                string txt = File.ReadAllText(SettingsSidecarPath);
                if (!string.IsNullOrWhiteSpace(txt))
                    return JsonSerializer.Deserialize<TwwSettings>(txt) ?? new();
            }
        }
        catch { }
        return new();
    }

    private void SaveSettings(TwwSettings s)
    {
        try
        {
            Directory.CreateDirectory(SettingsSidecarDir);
            File.WriteAllText(
                SettingsSidecarPath,
                JsonSerializer.Serialize(s, new JsonSerializerOptions { WriteIndented = true }),
                new UTF8Encoding(false));
        }
        catch { /* non-fatal */ }
    }
}
