using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Win32;
using LauncherV2.Core;

// NOTE on type qualification (BUILD GOTCHA — CS0104):
// The real launcher project sets BOTH <UseWPF>true</UseWPF> and
// <UseWindowsForms>true</UseWindowsForms>. That makes a long list of simple type
// names ambiguous between WPF and WinForms (Application, MessageBox, Clipboard,
// Color, Brush(es), Button, TextBox, CheckBox, Orientation, FontWeights,
// HorizontalAlignment, Thickness, Cursors, …). To avoid CS0104 this file
// deliberately does NOT do `using System.Windows.Controls;` /
// `using System.Windows.Media;` — every WPF UI type below is written FULLY
// QUALIFIED (System.Windows.Controls.*, System.Windows.Media.*,
// System.Windows.MessageBox, System.Windows.Thickness, …). GlobalUsings.cs in the
// project already aliases the short names, so this file must NOT add any file-level
// `using X = System.Windows...;` alias of its own (that would be CS1537).

namespace LauncherV2.Plugins.Factorio;

// ═══════════════════════════════════════════════════════════════════════════════
// FactorioPlugin — detect / guide / launch for "Factorio" (Wube Software) played
// through its OFFICIAL Archipelago integration. NATIVE "ConnectsItself" — the AP
// slot connection is owned by a SEPARATE bundled tool (the Factorio Client), not
// by the game process and not by the launcher, exactly like the shipped Undertale
// plugin (an external-client honest case).
//
// WHAT KIND OF INTEGRATION IS THIS? (verified this session — see REALITY CHECK)
// ─────────────────────────────────────────────────────────────────────────────
// Factorio's Archipelago support is part of AP-MAIN itself (worlds/factorio), NOT
// a third-party mod repo with a one-click download. The moving pieces are:
//
//   * The "Factorio Client" — a Python client that SHIPS INSIDE the Archipelago
//     install the player already has (registered as
//     Component("Factorio Client", func=launch_client, component_type=Type.CLIENT)
//     in worlds/factorio/__init__.py; on Windows the bundled installer produces
//     ArchipelagoFactorioClient.exe). It OWNS the AP slot connection: it launches
//     a Factorio *server* with the generated AP mod and relays between that server
//     and the Archipelago multiworld.
//   * The player's OWN Factorio (Steam appid 427520, or the standalone build from
//     factorio.com). The client needs the path to that game's
//     bin\x64\factorio(.exe) set in its host.yaml (factorio_options: executable).
//   * The per-seed AP Factorio mod (an "AP_*.zip"), generated by the multiworld,
//     which goes into Factorio's mods folder (%AppData%\Factorio\mods for the
//     client's own Factorio, or the dedicated server's mods folder).
//
// HONESTY NOTE — this is a GUIDED case (like Undertale / Ship of Harkinian), and
// like Undertale the AP slot is held by a SEPARATE long-running tool (the Factorio
// Client), not by the game process. The concrete, verified reasons the launcher
// canNOT do a fake "one-click install":
//
//   1. There is NO redistributable runnable game and NO standalone mod zip the
//      launcher may ship: Factorio is paid software (Steam / factorio.com), and the
//      client + generator that drive it live INSIDE the player's Archipelago
//      install. The launcher must not, and does not, ship or recreate either.
//   2. The OFFICIAL, documented setup (the AP "Factorio" setup guide) is:
//        a. Install a DEDICATED, isolated Factorio for the client to control
//           (standalone build recommended; a second copy is needed if you also
//           host on the same machine).
//        b. In ArchipelagoFactorioClient's host.yaml, set
//             factorio_options:
//               executable: C:\\path\\to\\factorio\\bin\\x64\\factorio
//           (double backslashes required).
//        c. Put the generated AP_*.zip mod into the Factorio mods folder
//           (%AppData%\Factorio\mods, or the server's mods folder).
//        d. Run ArchipelagoFactorioClient.exe and type  /connect <server:port>
//           into its input box.
//      Reproducing that (download a multi-hundred-MB game, edit the client's
//      host.yaml, drop a per-seed mod, drive the client) is exactly the bundled
//      client's job — so, like Undertale did not reproduce /auto_patch, this
//      plugin does NOT fake it.
//   3. CONNECTION IS CLIENT-OWNED, NOT in-game and NOT launcher-relay. The launcher
//      cannot pass connection args to the game and must NOT hold its own ApClient
//      on the slot (the Factorio Client would be kicked, or kick us). Hence
//      ConnectsItself = true.
//
// WHAT THIS PLUGIN HONESTLY DOES:
//   * DETECT the player's Factorio:
//       - Steam appid 427520 via registry → libraryfolders.vdf →
//         appmanifest_427520.acf → steamapps\common\Factorio (the same pipeline the
//         shipped Subnautica/Stardew plugins use), and
//       - the standalone build: %AppData%\Factorio (Roaming user data) and a
//         user-set install-folder override.
//     so it can tell the player exactly where bin\x64\factorio(.exe) lives.
//   * LOCATE the Archipelago install (READ-ONLY) to find the bundled client
//     ArchipelagoFactorioClient.exe — searching %ProgramData%\Archipelago,
//     %LocalAppData%\Archipelago, %ProgramFiles%\Archipelago, and a user-set
//     Archipelago-folder override.
//     ***CRITICAL SECURITY: C:\ProgramData\Archipelago is treated as READ-ONLY.
//        This plugin only READS it to find the bundled client. It NEVER writes,
//        creates, deletes, or modifies anything under any Archipelago install.***
//   * GUIDE the irreducible steps in InstallOrUpdate / Settings (get Factorio, set
//     the client's host.yaml executable, drop the AP mod, run the client and
//     /connect), with direct links (Factorio download/Steam page, AP releases, the
//     official setup guide, archipelago.gg).
//   * LAUNCH best-effort: start ArchipelagoFactorioClient.exe (the bundled client
//     owns the connection — the player then types /connect <server:port>). The
//     session's server/slot are surfaced in the panel/notes to copy. If the client
//     cannot be located, fail with honest guidance instead of a fake success.
//     SupportsStandalone = true launches Factorio itself (bin\x64\factorio.exe, or
//     steam://rungameid/427520) for plain, non-AP play.
//   * NEVER claim an install exists when it does not, never modify the player's
//     Factorio or Archipelago installs (§11 + the read-only rule above), and keep
//     its settings in its OWN JSON sidecar (does not touch Core/SettingsStore).
//
// REALITY CHECK (2026-06-14) — facts verified this session against AP-main + the
// official setup guide (https://archipelago.gg/tutorial/Factorio/setup_en):
//   * AP game string: "Factorio" — VERIFIED in worlds/factorio/__init__.py
//     (FactorioWorld.game = "Factorio"). World id "factorio".
//   * Client component: Component("Factorio Client", func=launch_client,
//     component_type=Type.CLIENT) in worlds/factorio/__init__.py; the Windows
//     bundled exe is ArchipelagoFactorioClient.exe (installed with Archipelago if
//     the client was selected during install).
//   * Steam appid 427520 (store.steampowered.com/app/427520).
//   * factorio(.exe) lives at bin\x64\factorio(.exe) in every Factorio install
//     (Steam and standalone). Standalone user data (mods/saves/config) is at
//     %AppData%\Factorio (Roaming).
//   * host.yaml (next to the client): factorio_options: executable:
//     C:\\path\\to\\factorio\\bin\\x64\\factorio  (double backslashes required).
//   * Mod: the generated AP_*.zip goes into the Factorio mods folder
//     (%AppData%\Factorio\mods, or the dedicated server's mods folder).
//   * Connect: run ArchipelagoFactorioClient.exe, type  /connect <server:port>.
//
// DEFENSIVE / UNVERIFIED DETAILS (flagged, "verify at build time", Undertale-style):
//   * The bundled client exe name is "ArchipelagoFactorioClient.exe" on Windows
//     (verified from the setup guide). LocateFactorioClientExe() prefers that exact
//     name, then a fuzzy "*factorio*client*.exe" / "*factorioclient*.exe" anywhere
//     under the resolved Archipelago install, so a differently-cased build still
//     resolves. If the user installed Archipelago without the Factorio client, no
//     exe is found and the plugin stays HONEST (guides the user to install it /
//     point at it). It NEVER writes into the Archipelago folder while searching.
//   * "IsInstalled" here means BOTH halves are present: a Factorio executable is
//     resolvable AND the bundled ArchipelagoFactorioClient.exe is locatable. The
//     game alone, or the client alone, is not enough to play, so neither flips it
//     true by itself.
//   * The launcher cannot verify the user actually edited host.yaml or dropped the
//     AP mod (those live inside the read-only Archipelago install / the player's
//     Factorio mods folder, which it does not modify); the Settings panel is
//     explicit about those remaining manual steps.
// ═══════════════════════════════════════════════════════════════════════════════

public sealed class FactorioPlugin : IGamePlugin
{
    // ── Constants ──────────────────────────────────────────────────────────────

    /// Factorio's Steam application id (VERIFIED — store.steampowered.com/app/427520).
    private const string SteamAppId = "427520";

    /// Standard Steam install sub-folder name (steamapps\common\Factorio).
    private const string SteamCommonFolderName = "Factorio";

    /// The bundled Windows client exe (installed with Archipelago when the Factorio
    /// client component is selected). Verified from the official setup guide.
    private const string PreferredClientExeName = "ArchipelagoFactorioClient.exe";

    /// Factorio's main executable, relative to any Factorio install root.
    private static readonly string FactorioExeRelPath =
        Path.Combine("bin", "x64", "factorio.exe");

    private static readonly string SteamRunUrl = $"steam://rungameid/{SteamAppId}";

    // Links.
    private const string SetupGuideUrl  = "https://archipelago.gg/tutorial/Factorio/setup_en";
    private const string FactorioSite   = "https://factorio.com/download";
    private const string SteamStoreUrl  = "https://store.steampowered.com/app/427520";
    private const string ApReleasesUrl  = "https://github.com/ArchipelagoMW/Archipelago/releases";
    private const string ApReleasesApiUrl =
        "https://api.github.com/repos/ArchipelagoMW/Archipelago/releases";
    private const string ArchipelagoSite = "https://archipelago.gg";

    private static readonly HttpClient _http = new()
    {
        Timeout = TimeSpan.FromMinutes(2),
        DefaultRequestHeaders = { { "User-Agent", "Archipelago-Launcher/2.0" } }
    };

    // ── IGamePlugin — Identity ────────────────────────────────────────────────

    public string GameId      => "factorio";
    public string DisplayName => "Factorio";
    public string Subtitle    => "Native PC · Archipelago";

    /// EXACT AP game string — VERIFIED against worlds/factorio/__init__.py
    /// (FactorioWorld.game = "Factorio").
    public string ApWorldName => "Factorio";

    public string IconPath =>
        Path.Combine(AppContext.BaseDirectory, "Assets", "factorio.png");

    public string ThemeAccentColor => "#C8842A";   // Factorio amber/copper
    public string[] GameBadges     => new[] { "Requires Factorio + Archipelago" };

    public string Description =>
        "Factorio is Wube Software's acclaimed factory-building game: you crash-land " +
        "on an alien planet and automate your way from hand-mining to a planet-" +
        "spanning production line. This is the official Archipelago integration — " +
        "your research/technologies are shuffled into the multiworld. You bring your " +
        "own copy of Factorio (Steam or the standalone build from factorio.com), and " +
        "Archipelago's bundled \"Factorio Client\" (ArchipelagoFactorioClient.exe, " +
        "installed with Archipelago) launches a Factorio server with the generated " +
        "Archipelago mod and connects it to the multiworld. The launcher detects your " +
        "Factorio install, locates the bundled client, guides the one-time setup, and " +
        "can start the client for you — you then type /connect <server> in the client.";

    public string? VideoPreviewUrl => null;
    public string[] ScreenshotUrls => Array.Empty<string>();

    // ── Version state ───────────────────────────────────────────────────────────
    // Factorio's AP integration is versioned by the Archipelago release the user
    // runs (the client + generator ship inside it), not by a standalone mod tag.
    // There is no independent version stamp this plugin can author honestly, so
    // these stay null (the news feed surfaces AP release versions instead).
    public string? InstalledVersion => null;
    public string? AvailableVersion => null;

    /// Installed == BOTH halves resolvable: a Factorio executable AND the bundled
    /// ArchipelagoFactorioClient.exe. Either alone is not enough to actually play.
    public bool IsInstalled => ResolveFactorioExe() != null && LocateFactorioClientExe() != null;

    public bool IsRunning { get; private set; }

    /// Reports the resolved Factorio install dir when known, else "" (interface
    /// contract: empty string when not installed/known).
    public string GameDirectory => ResolveFactorioDir() ?? "";

    // ── Paths ───────────────────────────────────────────────────────────────────

    /// This plugin's OWN settings sidecar (kept out of the shared SettingsStore so
    /// the plugin stays a single self-contained source file — same approach as the
    /// Subnautica / Undertale / Doom plugins). BOM-less UTF-8.
    private string SettingsSidecarDir
        => Path.Combine(AppContext.BaseDirectory, "Games", "ROMs", GameId);
    private string SettingsSidecarPath
        => Path.Combine(SettingsSidecarDir, "factorio_launcher.json");

    /// Standalone Factorio user-data folder (Roaming) — holds mods/saves/config.
    private static string StandaloneUserDataDir
        => Path.Combine(
            Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData),
            "Factorio");

    // ── Internal state ──────────────────────────────────────────────────────────

    private Process? _clientProcess;

    /// User overrides (loaded in the ctor, persisted in the sidecar).
    private string? _overrideFactorioDir;      // a Factorio install root (contains bin\x64\factorio.exe)
    private string? _overrideArchipelagoDir;   // an Archipelago install root (READ-ONLY; holds the client exe)

    // ── AP bridge events ──────────────────────────────────────────────────────
    // The external Factorio Client owns the AP slot and relays checks/items/goal to
    // the server itself (it drives the Factorio server). The launcher relays
    // nothing. These exist only for interface compatibility (ConnectsItself = true).
#pragma warning disable CS0067
    public event Action<long[]>? LocationsChecked;
    public event Action?         GoalCompleted;
#pragma warning restore CS0067

    public event Action<int>? GameExited;

    // ── Constructor — restore previously chosen folders ────────────────────────

    public FactorioPlugin()
    {
        try
        {
            var s = LoadSettings();
            if (!string.IsNullOrWhiteSpace(s.FactorioDir) && Directory.Exists(s.FactorioDir))
                _overrideFactorioDir = s.FactorioDir;
            if (!string.IsNullOrWhiteSpace(s.ArchipelagoDir) && Directory.Exists(s.ArchipelagoDir))
                _overrideArchipelagoDir = s.ArchipelagoDir;
        }
        catch { /* fall back to detection only */ }
    }

    // ── Lifecycle — CheckForUpdate ────────────────────────────────────────────
    // No independent version to compare (the client + generator ship inside the
    // player's Archipelago install). Contract: never throw on network failure.

    public Task CheckForUpdateAsync(CancellationToken ct = default)
        => Task.CompletedTask;

    // ── Lifecycle — InstallOrUpdate ───────────────────────────────────────────
    // HONEST guided setup. There is nothing for the launcher to download here (the
    // Factorio game is the player's paid copy, and the client + generator + the
    // per-seed mod come from the player's Archipelago install / the multiworld). So
    // this reports the current detection state and the exact remaining manual steps
    // — it never fabricates an install, and it never writes to the Archipelago
    // folder (read-only).

    public Task InstallOrUpdateAsync(
        IProgress<(int Pct, string Msg)> progress,
        CancellationToken ct = default)
    {
        progress.Report((10, "Looking for your Factorio installation..."));
        string? factorioDir = ResolveFactorioDir();

        progress.Report((45, "Looking for Archipelago's bundled Factorio Client..."));
        string? clientExe = LocateFactorioClientExe();

        bool haveGame   = factorioDir != null;
        bool haveClient = clientExe   != null;

        if (haveGame && haveClient)
        {
            progress.Report((100,
                $"Ready: Factorio found at \"{factorioDir}\" and the bundled client at " +
                $"\"{clientExe}\". One-time setup if you have not done it: in the client's " +
                "host.yaml set  factorio_options: executable  to  " +
                $"\"{FactorioExeForGuidance(factorioDir!)}\"  (double backslashes), and put " +
                "your generated AP_*.zip mod into Factorio's mods folder " +
                $"(\"{Path.Combine(StandaloneUserDataDir, "mods")}\"). Press Play to start " +
                "the client, then type  /connect <server:port>  in it. See the Setup Guide " +
                "link in Settings."));
            return Task.CompletedTask;
        }

        // Give the most specific guidance we can for whatever is missing.
        var sb = new StringBuilder();
        if (!haveGame)
            sb.Append("Factorio was not detected. Install it (Steam appid ").Append(SteamAppId)
              .Append(", or the standalone build from factorio.com), then point this plugin at " +
                      "the Factorio folder (the one containing bin\\x64\\factorio.exe) in Settings. ");
        if (!haveClient)
            sb.Append("Archipelago's bundled \"Factorio Client\" (ArchipelagoFactorioClient.exe) " +
                      "was not found. Install Archipelago and CHECK the Factorio client during " +
                      "setup, then point this plugin at your Archipelago folder in Settings. ");
        sb.Append("Then in the client's host.yaml set  factorio_options: executable  to your " +
                  "Factorio bin\\x64\\factorio (double backslashes), drop your generated AP_*.zip " +
                  "mod into Factorio's mods folder, run the client, and type  /connect " +
                  "<server:port>. See the Setup Guide link in Settings.");

        progress.Report((100, sb.ToString()));
        return Task.CompletedTask;
    }

    // ── Lifecycle — Verify ────────────────────────────────────────────────────

    public Task<bool> VerifyInstallAsync(CancellationToken ct = default)
        => Task.FromResult(IsInstalled);

    // ── AutoMod-style validation of a user-picked Factorio folder ─────────────

    /// Used by the Settings folder picker for the FACTORIO install. Accept it only
    /// when it contains bin\x64\factorio.exe (or the user picked a parent we can
    /// descend into). Returns null when acceptable, else a short reason.
    public string? ValidateExistingInstall(string folder)
    {
        if (string.IsNullOrWhiteSpace(folder) || !Directory.Exists(folder))
            return "That folder does not exist. Pick your Factorio install folder " +
                   "(the one containing bin\\x64\\factorio.exe).";

        if (LooksLikeFactorioDir(folder))
            return null;

        // Be forgiving: the user may have picked the Steam "common" parent.
        try
        {
            string nested = Path.Combine(folder, SteamCommonFolderName);
            if (LooksLikeFactorioDir(nested)) return null;
        }
        catch { /* ignore */ }

        return "That does not look like a Factorio installation. Pick the folder that " +
               "contains bin\\x64\\factorio.exe (for Steam this is usually " +
               @"...\steamapps\common\Factorio).";
    }

    // ── Lifecycle — Launch ────────────────────────────────────────────────────
    // Best effort: start the bundled Factorio Client so the player gets one-click
    // launch. The connection itself is entered into that client (type
    // /connect <server:port>), so we do NOT pass connection args and we do NOT hold
    // an ApClient on the slot (ConnectsItself = true). If the client cannot be
    // located, fail with honest guidance.

    public Task LaunchAsync(ApSession session, CancellationToken ct = default)
    {
        _ = session; // connection is made in the Factorio Client, not via args here
        LaunchFactorioClient();
        return Task.CompletedTask;
    }

    /// Factorio is a complete game — plain (non-AP) play is possible (launch the
    /// game itself rather than the AP client).
    public bool SupportsStandalone => true;

    /// The external Factorio Client owns the AP slot connection (see header). The
    /// launcher must NOT connect its own ApClient to the same slot while the client
    /// runs, or they would kick each other off.
    public bool ConnectsItself => true;

    public Task LaunchStandaloneAsync(CancellationToken ct = default)
    {
        LaunchFactorioGame();
        return Task.CompletedTask;
    }

    public Task StopAsync()
    {
        // We only ever started the bundled Factorio Client (or the game) from here.
        // Kill what WE launched — never the user's AP server / other processes.
        try { _clientProcess?.Kill(entireProcessTree: true); } catch { }
        IsRunning = false;
        // No password/args are written to disk by this plugin (the connection is
        // entered in the client), so there is nothing sensitive to scrub.
        _clientProcess = null;
        return Task.CompletedTask;
    }

    // ── AP bridge — inert (see header) ────────────────────────────────────────

    public Task ReceiveItemsAsync(ApNetworkItem[] items, int index, CancellationToken ct = default)
    {
        // The Factorio Client receives items from the AP server directly and relays
        // them into the Factorio server; there is nothing for the launcher to forward.
        return Task.CompletedTask;
    }

    public void OnApStateChanged(ApConnectionState state)
    {
        // The Factorio Client renders its own connection state; no launcher HUD
        // channel into the game.
    }

    // ── Settings UI ───────────────────────────────────────────────────────────

    public System.Windows.UIElement? CreateSettingsPanel()
    {
        var muted   = new System.Windows.Media.SolidColorBrush(System.Windows.Media.Color.FromRgb(0x72, 0x7A, 0x99));
        var fg      = new System.Windows.Media.SolidColorBrush(System.Windows.Media.Color.FromRgb(0xCC, 0xD0, 0xE0));
        var success = new System.Windows.Media.SolidColorBrush(System.Windows.Media.Color.FromRgb(0x4C, 0xAF, 0x50));
        var warn    = new System.Windows.Media.SolidColorBrush(System.Windows.Media.Color.FromRgb(0xE0, 0xA0, 0x30));

        var panel = new System.Windows.Controls.StackPanel { Margin = new System.Windows.Thickness(0, 0, 0, 20) };

        // ── Honesty header ────────────────────────────────────────────────
        panel.Children.Add(new System.Windows.Controls.TextBlock
        {
            Text = "Factorio's Archipelago support is part of Archipelago itself, not a " +
                   "one-click mod. You bring your own copy of Factorio (Steam or the " +
                   "standalone build); Archipelago's bundled \"Factorio Client\" " +
                   "(ArchipelagoFactorioClient.exe) launches a Factorio server with the " +
                   "generated Archipelago mod and connects it to the multiworld. The " +
                   "launcher detects your install, locates the client, guides the one-time " +
                   "setup, and can start the client — but you connect from the client " +
                   "(/connect <server>), not here. Some details below were verified against " +
                   "the official setup guide, not byte-for-byte offline.",
            FontSize = 11, Foreground = warn,
            TextWrapping = System.Windows.TextWrapping.Wrap,
            Margin = new System.Windows.Thickness(0, 0, 0, 14),
        });

        // ── Section: Factorio install (detect + override) ─────────────────
        panel.Children.Add(SectionHeader("FACTORIO INSTALL", muted));

        string? steamDir    = DetectSteamFactorioDir();
        string? factorioDir = ResolveFactorioDir();
        panel.Children.Add(new System.Windows.Controls.TextBlock
        {
            Text = factorioDir != null
                ? (_overrideFactorioDir != null
                    ? "Using your selected folder: " + factorioDir
                    : "Detected (" + (steamDir != null ? "Steam appid " + SteamAppId : "standalone") +
                      "): " + factorioDir)
                : "Factorio not detected. Pick your install folder below, or install Factorio " +
                  "(Steam appid " + SteamAppId + ", or factorio.com).",
            FontSize = 11, Foreground = factorioDir != null ? success : muted,
            TextWrapping = System.Windows.TextWrapping.Wrap,
            Margin = new System.Windows.Thickness(0, 0, 0, 6),
        });

        var dirRow = new System.Windows.Controls.DockPanel { Margin = new System.Windows.Thickness(0, 0, 0, 4) };
        var dirBox = new System.Windows.Controls.TextBox
        {
            Text = _overrideFactorioDir ?? factorioDir ?? "", IsReadOnly = true, FontSize = 12,
            Margin = new System.Windows.Thickness(0, 0, 8, 0),
            Background  = new System.Windows.Media.SolidColorBrush(System.Windows.Media.Color.FromRgb(0x0C, 0x10, 0x20)),
            Foreground  = fg,
            BorderBrush = new System.Windows.Media.SolidColorBrush(System.Windows.Media.Color.FromRgb(0x1E, 0x22, 0x33)),
            ToolTip     = "Your Factorio install folder (the one containing bin\\x64\\factorio.exe). " +
                          "Detected from Steam / the standalone build automatically; set it here to " +
                          "override.",
        };
        var dirBtn = new System.Windows.Controls.Button
        {
            Content = "Select folder...", Width = 120, Padding = new System.Windows.Thickness(0, 6, 0, 6),
            Background  = new System.Windows.Media.SolidColorBrush(System.Windows.Media.Color.FromRgb(0x1A, 0x1E, 0x30)),
            Foreground  = fg,
            BorderBrush = new System.Windows.Media.SolidColorBrush(System.Windows.Media.Color.FromRgb(0x2A, 0x30, 0x50)),
        };
        dirBtn.Click += (_, _) =>
        {
            var dlg = new OpenFolderDialog
            {
                Title            = "Select your Factorio install folder (contains bin\\x64\\factorio.exe)",
                InitialDirectory = Directory.Exists(_overrideFactorioDir ?? factorioDir ?? "")
                                   ? (_overrideFactorioDir ?? factorioDir!)
                                   : AppContext.BaseDirectory,
            };
            if (dlg.ShowDialog() == true)
            {
                string picked = dlg.FolderName;
                string? bad   = ValidateExistingInstall(picked);
                if (bad != null)
                {
                    System.Windows.MessageBox.Show(bad, "Not a Factorio folder",
                        System.Windows.MessageBoxButton.OK, System.Windows.MessageBoxImage.Warning);
                    return;
                }
                if (!LooksLikeFactorioDir(picked))
                {
                    string nested = Path.Combine(picked, SteamCommonFolderName);
                    if (LooksLikeFactorioDir(nested)) picked = nested;
                }
                _overrideFactorioDir = picked;
                dirBox.Text = picked;
                SaveFactorioDir(picked);
            }
        };
        System.Windows.Controls.DockPanel.SetDock(dirBtn, System.Windows.Controls.Dock.Right);
        dirRow.Children.Add(dirBtn);
        dirRow.Children.Add(dirBox);
        panel.Children.Add(dirRow);

        panel.Children.Add(new System.Windows.Controls.TextBlock
        {
            Text = "Steam installs are detected automatically (appid " + SteamAppId + "); the " +
                   "standalone build is detected via %AppData%\\Factorio. Use this picker for a " +
                   "non-standard location.",
            FontSize = 11, Foreground = muted,
            TextWrapping = System.Windows.TextWrapping.Wrap,
            Margin = new System.Windows.Thickness(0, 6, 0, 12),
        });

        // ── Section: Archipelago install / bundled client (READ-ONLY) ─────
        panel.Children.Add(SectionHeader("ARCHIPELAGO INSTALL (BUNDLED FACTORIO CLIENT)", muted));

        string? clientExe = LocateFactorioClientExe();
        panel.Children.Add(new System.Windows.Controls.TextBlock
        {
            Text = clientExe != null
                ? "✓ Bundled client found: " + clientExe
                : "ArchipelagoFactorioClient.exe not found. Install Archipelago and check the " +
                  "Factorio client during setup, or point this at your Archipelago folder below. " +
                  "(The launcher only READS the Archipelago folder — it never modifies it.)",
            FontSize = 11, Foreground = clientExe != null ? success : muted,
            TextWrapping = System.Windows.TextWrapping.Wrap,
            Margin = new System.Windows.Thickness(0, 0, 0, 6),
        });

        var apRow = new System.Windows.Controls.DockPanel { Margin = new System.Windows.Thickness(0, 0, 0, 4) };
        var apBox = new System.Windows.Controls.TextBox
        {
            Text = _overrideArchipelagoDir ?? ResolveArchipelagoDir() ?? "", IsReadOnly = true, FontSize = 12,
            Margin = new System.Windows.Thickness(0, 0, 8, 0),
            Background  = new System.Windows.Media.SolidColorBrush(System.Windows.Media.Color.FromRgb(0x0C, 0x10, 0x20)),
            Foreground  = fg,
            BorderBrush = new System.Windows.Media.SolidColorBrush(System.Windows.Media.Color.FromRgb(0x1E, 0x22, 0x33)),
            ToolTip     = "Your Archipelago install folder (where ArchipelagoFactorioClient.exe " +
                          "lives). Auto-detected under ProgramData / LocalAppData / Program Files. " +
                          "This folder is READ ONLY to the launcher.",
        };
        var apBtn = new System.Windows.Controls.Button
        {
            Content = "Select folder...", Width = 120, Padding = new System.Windows.Thickness(0, 6, 0, 6),
            Background  = new System.Windows.Media.SolidColorBrush(System.Windows.Media.Color.FromRgb(0x1A, 0x1E, 0x30)),
            Foreground  = fg,
            BorderBrush = new System.Windows.Media.SolidColorBrush(System.Windows.Media.Color.FromRgb(0x2A, 0x30, 0x50)),
        };
        apBtn.Click += (_, _) =>
        {
            var dlg = new OpenFolderDialog
            {
                Title            = "Select your Archipelago folder (contains ArchipelagoFactorioClient.exe)",
                InitialDirectory = Directory.Exists(_overrideArchipelagoDir ?? ResolveArchipelagoDir() ?? "")
                                   ? (_overrideArchipelagoDir ?? ResolveArchipelagoDir()!)
                                   : AppContext.BaseDirectory,
            };
            if (dlg.ShowDialog() == true)
            {
                string picked = dlg.FolderName;
                if (FindFactorioClientExeIn(picked) == null)
                {
                    var go = System.Windows.MessageBox.Show(
                        "ArchipelagoFactorioClient.exe was not found in that folder. Pick the " +
                        "Archipelago folder that contains it (e.g. C:\\ProgramData\\Archipelago).\n\n" +
                        "Use this folder anyway?",
                        "Client not found here",
                        System.Windows.MessageBoxButton.YesNo, System.Windows.MessageBoxImage.Warning);
                    if (go != System.Windows.MessageBoxResult.Yes) return;
                }
                _overrideArchipelagoDir = picked;
                apBox.Text = picked;
                SaveArchipelagoDir(picked);
            }
        };
        System.Windows.Controls.DockPanel.SetDock(apBtn, System.Windows.Controls.Dock.Right);
        apRow.Children.Add(apBtn);
        apRow.Children.Add(apBox);
        panel.Children.Add(apRow);

        panel.Children.Add(new System.Windows.Controls.TextBlock
        {
            Text = "The launcher only READS this folder to find the bundled client; it never " +
                   "writes to, or changes, anything in your Archipelago install.",
            FontSize = 11, Foreground = muted,
            TextWrapping = System.Windows.TextWrapping.Wrap,
            Margin = new System.Windows.Thickness(0, 6, 0, 12),
        });

        // ── Section: setup + connection steps ─────────────────────────────
        panel.Children.Add(SectionHeader("SETUP & CONNECTION", muted));
        string exeGuidance = factorioDir != null
            ? FactorioExeForGuidance(factorioDir)
            : @"C:\\path\\to\\factorio\\bin\\x64\\factorio";
        string modsGuidance = Path.Combine(StandaloneUserDataDir, "mods");
        panel.Children.Add(new System.Windows.Controls.TextBlock
        {
            Text =
                "1) Own and install Factorio (Steam appid " + SteamAppId + ", or the standalone " +
                "build from factorio.com). The setup guide recommends a DEDICATED, isolated " +
                "Factorio for the client to control (a second copy if you also host on this PC).\n" +
                "2) Install Archipelago and check the \"Factorio Client\" during setup, so " +
                "ArchipelagoFactorioClient.exe is present.\n" +
                "3) In the client's host.yaml, set\n" +
                "      factorio_options:\n" +
                "        executable: " + exeGuidance + "\n" +
                "   (double backslashes required).\n" +
                "4) Put your generated AP_*.zip mod into Factorio's mods folder\n" +
                "      " + modsGuidance + "\n" +
                "   (or the dedicated server's mods folder).\n\n" +
                "To play: press Play here (it starts ArchipelagoFactorioClient.exe), then in the " +
                "client's input box type  /connect <server:port>  (e.g. /connect archipelago.gg:38281) " +
                "and your slot/password when prompted. The client launches the Factorio server with " +
                "the mod and relays everything. (The connection is entered in the client — the " +
                "launcher does not connect to your slot itself.)",
            FontSize = 11, Foreground = fg,
            TextWrapping = System.Windows.TextWrapping.Wrap,
            Margin = new System.Windows.Thickness(0, 0, 0, 12),
        });

        // ── Links ─────────────────────────────────────────────────────────
        panel.Children.Add(SectionHeader("LINKS", muted));
        foreach (var (label, url) in new[]
        {
            ("Factorio Setup Guide ↗",   SetupGuideUrl),
            ("Factorio Download ↗",      FactorioSite),
            ("Factorio on Steam ↗",      SteamStoreUrl),
            ("Archipelago Releases ↗",   ApReleasesUrl),
            ("Archipelago Official ↗",   ArchipelagoSite),
        })
        {
            var btn = new System.Windows.Controls.Button
            {
                Content = label,
                HorizontalAlignment = System.Windows.HorizontalAlignment.Left,
                Padding = new System.Windows.Thickness(0, 2, 0, 2),
                Background = System.Windows.Media.Brushes.Transparent,
                BorderThickness = new System.Windows.Thickness(0), FontSize = 12,
                Margin = new System.Windows.Thickness(0, 0, 0, 4),
                Foreground = new System.Windows.Media.SolidColorBrush(System.Windows.Media.Color.FromRgb(0x60, 0x9A, 0xFF)),
                Cursor = System.Windows.Input.Cursors.Hand,
            };
            string u = url;
            btn.Click += (_, _) => { try { Process.Start(
                new ProcessStartInfo(u) { UseShellExecute = true }); } catch { } };
            panel.Children.Add(btn);
        }
        return panel;
    }

    private static System.Windows.Controls.TextBlock SectionHeader(
        string text, System.Windows.Media.Brush muted)
        => new System.Windows.Controls.TextBlock
        {
            Text = text, FontSize = 10, FontWeight = System.Windows.FontWeights.SemiBold,
            Foreground = muted, Margin = new System.Windows.Thickness(0, 8, 0, 8),
        };

    // ── News feed ─────────────────────────────────────────────────────────────
    // Factorio's integration ships with the Archipelago release, so the most honest
    // "news" is the AP release stream (the Factorio Client + generator come from
    // there). Never throws — empty on failure.

    public async Task<NewsItem[]> GetNewsAsync(CancellationToken ct = default)
    {
        try
        {
            string json = await _http.GetStringAsync(ApReleasesApiUrl, ct);
            using var doc = JsonDocument.Parse(json);
            if (doc.RootElement.ValueKind != JsonValueKind.Array)
                return Array.Empty<NewsItem>();

            var items = new List<NewsItem>();
            foreach (var el in doc.RootElement.EnumerateArray())
            {
                DateTimeOffset date = DateTimeOffset.MinValue;
                if (el.TryGetProperty("published_at", out var d) && d.ValueKind == JsonValueKind.String)
                    DateTimeOffset.TryParse(d.GetString(), out date);

                items.Add(new NewsItem(
                    Title:   el.TryGetProperty("name",     out var n) ? n.GetString() ?? "" : "",
                    Body:    el.TryGetProperty("body",     out var b) ? b.GetString() ?? "" : "",
                    Version: el.TryGetProperty("tag_name", out var t) ? t.GetString() ?? "" : "",
                    Date:    date,
                    Url:     el.TryGetProperty("html_url", out var u) ? u.GetString() : null
                ));
                if (items.Count >= 10) break;
            }
            return items.ToArray();
        }
        catch { return Array.Empty<NewsItem>(); }
    }

    // ── Private helpers — Factorio install resolution ─────────────────────────

    /// The Factorio install dir to use: the override (if set and valid) wins, else
    /// the Steam-detected install, else the standalone build under %AppData%. Null
    /// when nothing is found.
    private string? ResolveFactorioDir()
    {
        if (!string.IsNullOrWhiteSpace(_overrideFactorioDir) &&
            LooksLikeFactorioDir(_overrideFactorioDir))
            return _overrideFactorioDir;

        try
        {
            string? steam = DetectSteamFactorioDir();
            if (steam != null) return steam;
        }
        catch { /* ignore — try standalone */ }

        try
        {
            // The standalone build's user-data folder (%AppData%\Factorio) holds
            // mods/saves/config but NOT bin\x64\factorio.exe; the actual program may
            // be anywhere. We only treat %AppData%\Factorio as a Factorio root if the
            // user happens to have extracted the program there too (some do). The
            // override picker is the reliable route for an arbitrary standalone path.
            if (LooksLikeFactorioDir(StandaloneUserDataDir))
                return StandaloneUserDataDir;
        }
        catch { /* ignore */ }

        return null;
    }

    /// The full path to factorio.exe under the resolved Factorio install, or null.
    private string? ResolveFactorioExe()
    {
        string? dir = ResolveFactorioDir();
        if (dir == null) return null;
        string exe = Path.Combine(dir, FactorioExeRelPath);
        return File.Exists(exe) ? exe : null;
    }

    /// A folder "looks like" a Factorio install if bin\x64\factorio.exe exists
    /// under it.
    private static bool LooksLikeFactorioDir(string dir)
    {
        try
        {
            if (string.IsNullOrWhiteSpace(dir) || !Directory.Exists(dir)) return false;
            return File.Exists(Path.Combine(dir, FactorioExeRelPath));
        }
        catch { return false; }
    }

    /// Build the host.yaml-style executable value for guidance text: the resolved
    /// factorio(.exe) path with single backslashes doubled (as the guide requires),
    /// and the ".exe" trimmed (the guide writes "...\\bin\\x64\\factorio").
    private static string FactorioExeForGuidance(string factorioDir)
    {
        string exe = Path.Combine(factorioDir, "bin", "x64", "factorio");
        return exe.Replace("\\", "\\\\");
    }

    /// Detect the Steam Factorio install: read the Steam root from the registry,
    /// gather all library roots from libraryfolders.vdf, and find the one whose
    /// appmanifest_427520.acf exists → steamapps\common\Factorio.
    private static string? DetectSteamFactorioDir()
    {
        foreach (string steamRoot in SteamRoots())
        {
            if (string.IsNullOrWhiteSpace(steamRoot)) continue;
            foreach (string lib in SteamLibraryRoots(steamRoot))
            {
                try
                {
                    string steamapps = Path.Combine(lib, "steamapps");
                    string manifest  = Path.Combine(steamapps, $"appmanifest_{SteamAppId}.acf");
                    if (!File.Exists(manifest)) continue;

                    string common = Path.Combine(steamapps, "common");
                    string? installDir = ReadAcfInstallDir(manifest);
                    if (installDir != null)
                    {
                        string candidate = Path.Combine(common, installDir);
                        if (LooksLikeFactorioDir(candidate)) return candidate;
                    }
                    string conventional = Path.Combine(common, SteamCommonFolderName);
                    if (LooksLikeFactorioDir(conventional)) return conventional;
                }
                catch { /* try the next library */ }
            }
        }
        return null;
    }

    // ── Private helpers — Archipelago install / bundled client (READ-ONLY) ─────

    /// The Archipelago install dir to use (READ-ONLY). The override wins if it
    /// still exists; else the first standard location that exists. We do NOT require
    /// the client exe here (LocateFactorioClientExe does that) — this is just "where
    /// Archipelago is".
    private string? ResolveArchipelagoDir()
    {
        if (!string.IsNullOrWhiteSpace(_overrideArchipelagoDir) &&
            Directory.Exists(_overrideArchipelagoDir))
            return _overrideArchipelagoDir;

        foreach (string dir in StandardArchipelagoDirs())
        {
            try { if (Directory.Exists(dir)) return dir; }
            catch { /* ignore */ }
        }
        return null;
    }

    /// Standard Archipelago install roots to probe (READ-ONLY):
    ///   * %ProgramData%\Archipelago   (the default Windows installer location)
    ///   * %LocalAppData%\Archipelago
    ///   * %ProgramFiles%\Archipelago, %ProgramFiles(x86)%\Archipelago
    private static IEnumerable<string> StandardArchipelagoDirs()
    {
        var seen = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        foreach (string? root in new[]
        {
            Environment.GetFolderPath(Environment.SpecialFolder.CommonApplicationData), // ProgramData
            Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),
            Environment.GetFolderPath(Environment.SpecialFolder.ProgramFiles),
            Environment.GetFolderPath(Environment.SpecialFolder.ProgramFilesX86),
        })
        {
            if (string.IsNullOrWhiteSpace(root)) continue;
            string dir = Path.Combine(root, "Archipelago");
            if (seen.Add(dir)) yield return dir;
        }
    }

    /// Locate the bundled ArchipelagoFactorioClient.exe (READ-ONLY scan). Checks the
    /// resolved Archipelago dir first, then every standard location. Returns the exe
    /// path or null. NEVER writes anything while searching.
    private string? LocateFactorioClientExe()
    {
        // 1. The resolved/override Archipelago dir.
        string? apDir = ResolveArchipelagoDir();
        if (apDir != null)
        {
            string? hit = FindFactorioClientExeIn(apDir);
            if (hit != null) return hit;
        }

        // 2. Every other standard location (in case the override points elsewhere).
        foreach (string dir in StandardArchipelagoDirs())
        {
            if (apDir != null && string.Equals(dir, apDir, StringComparison.OrdinalIgnoreCase))
                continue;
            string? hit = FindFactorioClientExeIn(dir);
            if (hit != null) return hit;
        }
        return null;
    }

    /// Find ArchipelagoFactorioClient.exe inside `dir`: prefer the exact name at the
    /// root, else a fuzzy "*factorio*client*" / "*factorioclient*" exe anywhere under
    /// it. READ-ONLY (enumeration only); all failures degrade to null.
    private static string? FindFactorioClientExeIn(string dir)
    {
        try
        {
            if (string.IsNullOrWhiteSpace(dir) || !Directory.Exists(dir)) return null;

            string preferred = Path.Combine(dir, PreferredClientExeName);
            if (File.Exists(preferred)) return preferred;

            foreach (string exe in Directory.EnumerateFiles(dir, "*.exe", SearchOption.AllDirectories))
            {
                string name = Path.GetFileNameWithoutExtension(exe).ToLowerInvariant();
                if (name.Contains("factorio") && name.Contains("client"))
                    return exe;
            }
        }
        catch { /* permission / vanished — null (never throws into a scan) */ }
        return null;
    }

    // ── Private helpers — launch ──────────────────────────────────────────────

    /// Launch the bundled Factorio Client (the AP entry point). If it cannot be
    /// located, throw with honest guidance so the UI surfaces the real next step.
    private void LaunchFactorioClient()
    {
        string? exe = LocateFactorioClientExe();
        if (exe == null)
            throw new FileNotFoundException(
                "Archipelago's bundled Factorio Client (ArchipelagoFactorioClient.exe) was not " +
                "found. Install Archipelago and check the \"Factorio Client\" during setup, then " +
                "point this plugin at your Archipelago folder in Settings. Then run the client and " +
                "type  /connect <server:port>.",
                PreferredClientExeName);

        var proc = Process.Start(new ProcessStartInfo
        {
            FileName         = exe,
            WorkingDirectory = Path.GetDirectoryName(exe) ?? "",
            UseShellExecute  = true,   // the client may attach a console window of its own
        }) ?? throw new InvalidOperationException("Failed to start the Factorio Client.");

        _clientProcess = proc;
        IsRunning      = true;
        try
        {
            proc.EnableRaisingEvents = true;
            proc.Exited += (_, _) =>
            {
                IsRunning = false;
                GameExited?.Invoke(proc.ExitCode);
            };
        }
        catch { /* some processes don't expose Exited — non-fatal */ }
    }

    /// Launch Factorio itself (standalone / non-AP play): prefer bin\x64\factorio.exe
    /// in the resolved install; if that cannot be found but Steam is present, fall
    /// back to the steam:// URL. Surfaces a clear message rather than failing opaquely.
    private void LaunchFactorioGame()
    {
        string? exe = ResolveFactorioExe();
        if (exe != null && File.Exists(exe))
        {
            var proc = Process.Start(new ProcessStartInfo
            {
                FileName         = exe,
                WorkingDirectory = Path.GetDirectoryName(exe) ?? "",
                UseShellExecute  = true,
            }) ?? throw new InvalidOperationException("Failed to start Factorio.");

            _clientProcess = proc;
            IsRunning      = true;
            try
            {
                proc.EnableRaisingEvents = true;
                proc.Exited += (_, _) =>
                {
                    IsRunning = false;
                    GameExited?.Invoke(proc.ExitCode);
                };
            }
            catch { /* non-fatal */ }
            return;
        }

        // Fall back to Steam if we at least know Steam is installed.
        if (SteamRoots().Any(r => !string.IsNullOrWhiteSpace(r) && Directory.Exists(r)))
        {
            try
            {
                Process.Start(new ProcessStartInfo(SteamRunUrl) { UseShellExecute = true });
                IsRunning = true; // best-effort; Steam owns the process, so we won't track exit
                return;
            }
            catch { /* fall through to the error below */ }
        }

        throw new FileNotFoundException(
            "Could not find Factorio (bin\\x64\\factorio.exe). Open this game's Settings and pick " +
            "your Factorio install folder, or install Factorio via Steam.",
            "factorio.exe");
    }

    // ── Private helpers — Steam detection (adapted from the Subnautica plugin) ──

    /// Candidate Steam install roots from the registry (HKCU SteamPath +
    /// HKLM WOW6432Node/Valve InstallPath), plus the conventional Program Files (x86)
    /// location. Duplicates are harmless (callers de-dup).
    private static IEnumerable<string> SteamRoots()
    {
        string? hkcu = ReadRegistryString(Registry.CurrentUser,
            @"Software\Valve\Steam", "SteamPath");
        if (!string.IsNullOrWhiteSpace(hkcu)) yield return NormalizeSteamPath(hkcu);

        string? hklm = ReadRegistryString(Registry.LocalMachine,
            @"SOFTWARE\WOW6432Node\Valve\Steam", "InstallPath");
        if (!string.IsNullOrWhiteSpace(hklm)) yield return NormalizeSteamPath(hklm);

        string? hklm64 = ReadRegistryString(Registry.LocalMachine,
            @"SOFTWARE\Valve\Steam", "InstallPath");
        if (!string.IsNullOrWhiteSpace(hklm64)) yield return NormalizeSteamPath(hklm64);

        string? progX86 = Environment.GetFolderPath(Environment.SpecialFolder.ProgramFilesX86);
        if (!string.IsNullOrWhiteSpace(progX86))
            yield return Path.Combine(progX86, "Steam");
    }

    /// Steam stores its SteamPath with forward slashes; normalize for Path APIs.
    private static string NormalizeSteamPath(string p)
        => p.Replace('/', '\\').TrimEnd('\\');

    /// All Steam library roots: the Steam root itself plus every "path" entry in
    /// steamapps\libraryfolders.vdf. Tolerant text scan.
    private static IEnumerable<string> SteamLibraryRoots(string steamRoot)
    {
        var seen = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        if (seen.Add(steamRoot)) yield return steamRoot;

        string vdf = Path.Combine(steamRoot, "steamapps", "libraryfolders.vdf");
        if (!File.Exists(vdf)) yield break;

        string text;
        try { text = File.ReadAllText(vdf); }
        catch { yield break; }

        foreach (string path in ExtractVdfPaths(text))
        {
            string norm = path.Replace('/', '\\').TrimEnd('\\');
            if (norm.Length > 0 && seen.Add(norm))
                yield return norm;
        }
    }

    /// Pull every  "path"   "<value>"  pair out of a libraryfolders.vdf body.
    /// Handles the Steam-VDF escaping of backslashes (\\ → \).
    private static IEnumerable<string> ExtractVdfPaths(string text)
    {
        const string key = "\"path\"";
        int i = 0;
        while ((i = text.IndexOf(key, i, StringComparison.OrdinalIgnoreCase)) >= 0)
        {
            i += key.Length;
            int open = text.IndexOf('"', i);
            if (open < 0) yield break;
            int close = text.IndexOf('"', open + 1);
            if (close < 0) yield break;

            string raw = text.Substring(open + 1, close - open - 1);
            yield return raw.Replace("\\\\", "\\");
            i = close + 1;
        }
    }

    /// Read the "installdir" value from an appmanifest_*.acf (same quoted-pair
    /// format as VDF). Returns null if absent.
    private static string? ReadAcfInstallDir(string acfPath)
    {
        try
        {
            string text = File.ReadAllText(acfPath);
            const string key = "\"installdir\"";
            int i = text.IndexOf(key, StringComparison.OrdinalIgnoreCase);
            if (i < 0) return null;
            i += key.Length;
            int open = text.IndexOf('"', i);
            if (open < 0) return null;
            int close = text.IndexOf('"', open + 1);
            if (close < 0) return null;
            return text.Substring(open + 1, close - open - 1).Replace("\\\\", "\\");
        }
        catch { return null; }
    }

    /// Safe registry string read; null on any failure (key/value missing, etc.).
    private static string? ReadRegistryString(RegistryKey hive, string subKey, string valueName)
    {
        try
        {
            using RegistryKey? k = hive.OpenSubKey(subKey);
            return k?.GetValue(valueName) as string;
        }
        catch { return null; }
    }

    // ── Private helpers — self-contained settings sidecar ─────────────────────
    // Kept in this plugin's OWN JSON file (does not modify Core/SettingsStore).
    // BOM-less UTF-8, read-modify-write.

    private sealed class FactorioSettings
    {
        /// A Factorio install root (contains bin\x64\factorio.exe).
        public string? FactorioDir    { get; set; }
        /// An Archipelago install root (READ-ONLY; holds ArchipelagoFactorioClient.exe).
        public string? ArchipelagoDir { get; set; }
    }

    private FactorioSettings LoadSettings()
    {
        try
        {
            if (File.Exists(SettingsSidecarPath))
            {
                string txt = File.ReadAllText(SettingsSidecarPath);
                if (!string.IsNullOrWhiteSpace(txt))
                    return JsonSerializer.Deserialize<FactorioSettings>(txt) ?? new();
            }
        }
        catch { /* corrupt → defaults */ }
        return new();
    }

    private void SaveSettings(FactorioSettings s)
    {
        try
        {
            Directory.CreateDirectory(SettingsSidecarDir);
            File.WriteAllText(SettingsSidecarPath,
                JsonSerializer.Serialize(s, new JsonSerializerOptions { WriteIndented = true }),
                new UTF8Encoding(false));
        }
        catch { /* non-fatal — the setting just won't persist this time */ }
    }

    private void SaveFactorioDir(string dir)    { var s = LoadSettings(); s.FactorioDir = dir;    SaveSettings(s); }
    private void SaveArchipelagoDir(string dir) { var s = LoadSettings(); s.ArchipelagoDir = dir; SaveSettings(s); }
}
